CONTAINER OMMDBoneRoot {
	NAME OMMDBoneRoot;

	GROUP BONE_ROOT_GRP {
		DEFAULT 1;

		LONG BONE_DISPLAY_TYPE {
			CUSTOMGUI QUICKTABRADIO;
			ANIM OFF;

			CYCLE {
				BONE_DISPLAY_TYPE_ON;
				BONE_DISPLAY_TYPE_OFF;
				BONE_DISPLAY_TYPE_MOVABLE;
				BONE_DISPLAY_TYPE_ROTATABLE;
				BONE_DISPLAY_TYPE_VISIBLE;
				BONE_DISPLAY_TYPE_ENABLED;
				BONE_DISPLAY_TYPE_IK;
			}
		}

		BUTTON ADD_BONE_BUTTON {
			FIT_H;
			SCALE_H;
		}
	}
}
