if(MAXON_COMPILE_DEFINITIONS_INCLUDED)
    return()
endif()

set(MAXON_COMPILE_DEFINITIONS
	MAXON_TARGET_64BIT
	MAXON_SILENT_INIT # mute console output during kernel init.
)

set(MAXON_COMPILE_DEFINITIONS_DEBUG
	MAXON_TARGET_DEBUG
)

set(MAXON_COMPILE_DEFINITIONS_RELEASE
	MAXON_TARGET_RELEASE
)

set(MAXON_COMPILE_DEFINITIONS_WIN
	UNICODE
	_UNICODE
	_CONSOLE
	__64BIT
	"PSAPI_VERSION=1"
	_HAS_AUTO_PTR_ETC
	__PC
	_CRT_SECURE_NO_WARNINGS
	_WINDOWS
	_WIN64
	MAXON_TARGET_WINDOWS
	_WINDLL
	_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING
)

set(MAXON_COMPILE_DEFINITIONS_WIN_DEBUG
	_DEBUG
)

set(MAXON_COMPILE_DEFINITIONS_WIN_RELEASE
	_RELEASE
	NDEBUG
)

set(MAXON_COMPILE_DEFINITIONS_INCLUDED ON)