if(MAXON_LINK_OPTIONS_INCLUDED)
	return()
endif()

set(MAXON_LINK_OPTIONS_CLANGCL_MSVC
	-INCREMENTAL:NO
	-NXCOMPAT
	-ERRORREPORT:PROMPT
	-DYNAMICBASE
	-TLBID:1
	-IGNORE:4099
	-DEBUG:FULL
	-OPT:REF
	-OPT:ICF
)

set(MAXON_LINK_OPTIONS_CLANGCL_MSVC_DEBUG
)

set(MAXON_LINK_OPTIONS_CLANGCL_MSVC_RELEASE
)

set(MAXON_DEBUG_INFO_IN_RELEASE ON)

set(MAXON_LINK_OPTIONS_LINUX_CLANG_GCC
	-fuse-ld=gold
)

set(MAXON_LINK_OPTIONS_INCLUDED ON)
