include_guard()

set(WARNINGS_AS_ERRORS_CLANG_BASE
-Werror=unused-result
-Werror=unused-value
-Werror=return-type
-Werror=unused-lambda-capture
-Werror=shadow
-Werror=return-stack-address
-Werror=pessimizing-move
-Werror=unused-const-variable
-Werror=backslash-newline-escape
-Werror=overloaded-virtual
-Werror=shorten-64-to-32
-Werror=unused-variable
-Werror=missing-prototypes
-Werror=reinterpret-base-class
-Wdeprecated-declarations
)

# String containing warnings we want to explicitly disable.
# between the different clang versions the warnings have changed and in clang-6 not all
# disables work. Therefore we use -Wno-unknown-warning-option to stop warnings about
# unknown disable warning flags.
set(MUTED_WARNINGS_CLANG_BASE
-Wno-\#pragma-messages
-Wno-anon-enum-enum-conversion
-Wno-assign-enum
-Wno-bad-function-cast
-Wno-braced-scalar-init
-Wno-c++20-compat
-Wno-c++20-extensions
-Wno-c++98-compat-extra-semi
-Wno-c++98-compat-pedantic
-Wno-c++98-compat
-Wno-c99-extensions
-Wno-cast-align
-Wno-cast-qual
-Wno-comma
-Wno-covered-switch-default
-Wno-declaration-after-statement
-Wno-delete-non-abstract-non-virtual-dtor
-Wno-deprecated-copy-dtor
-Wno-deprecated-dynamic-exception-spec
-Wno-disabled-macro-expansion
-Wno-documentation-pedantic
-Wno-documentation-unknown-command
-Wno-double-promotion
-Wno-duplicate-enum
-Wno-error=documentation
-Wno-error=unreachable-code
-Wno-exit-time-destructors
-Wno-extra-semi-stmt
-Wno-extra-semi
-Wno-float-equal
-Wno-format-non-iso
-Wno-format-nonliteral
-Wno-four-char-constants
-Wno-global-constructors
-Wno-gnu-zero-variadic-macro-arguments
-Wno-header-hygiene
-Wno-implicit-fallthrough
-Wno-implicit-int-float-conversion
-Wno-inconsistent-missing-destructor-override
-Wno-int-in-bool-context
-Wno-language-extension-token
-Wno-literal-conversion
-Wno-microsoft-enum-value
-Wno-microsoft-unqualified-friend
-Wno-missing-noreturn
-Wno-missing-variable-declarations
-Wno-newline-eof
-Wno-non-virtual-dtor
-Wno-nonportable-system-include-path
-Wno-old-style-cast
-Wno-pedantic
-Wno-pragma-pack-suspicious-include
-Wno-range-loop-bind-reference
-Wno-redundant-parens
-Wno-reserved-id-macro
-Wno-reserved-identifier
-Wno-self-assign
-Wno-shadow-field-in-constructor
-Wno-shadow-field
-Wno-shadow-uncaptured-local
-Wno-shift-sign-overflow
-Wno-sign-conversion
-Wno-string-conversion
-Wno-suggest-destructor-override
-Wno-suggest-override
-Wno-switch-enum
-Wno-switch
-Wno-tautological-compare
-Wno-tautological-overlap-compare
-Wno-tautological-type-limit-compare
-Wno-tautological-unsigned-zero-compare
-Wno-undef
-Wno-undefined-func-template
-Wno-undefined-reinterpret-cast
-Wno-unknown-pragmas
-Wno-unneeded-member-function
-Wno-unreachable-code-break
-Wno-unreachable-code-return
-Wno-unused-command-line-argument
-Wno-unused-local-typedef
-Wno-unused-macros
-Wno-unused-member-function
-Wno-unused-parameter
-Wno-unused-private-field
-Wno-unused-template
-Wno-zero-as-null-pointer-constant
-Wsometimes-uninitialized
)

set(MUTED_WARNINGS_CLANG_11
)

set(MUTED_WARNINGS_CLANG_12
-Wno-ordered-compare-function-pointers
-Wno-compound-token-split-by-space
-Wno-tautological-value-range-compare
)

set(MUTED_WARNINGS_CLANG_13
-Wno-unused-but-set-parameter
-Wno-reserved-identifier
-Wno-cast-function-type
-Wno-null-pointer-subtraction
)

set(MUTED_WARNINGS_CLANG_16
-Wno-unsafe-buffer-usage
-Wno-deprecated-copy-with-user-provided-copy
-Wno-alloca
)

set(MUTED_WARNINGS_CLANG_17
-Wno-switch-default
-Wno-invalid-offsetof
-Wno-missing-include-dirs
-Wno-documentation-deprecated-sync
)
