#ifndef CBCIRCULAR_H__
#define CBCIRCULAR_H__

enum
{
	CIRCULARCURVE_CENTER				= 1101,
	CIRCULARCURVE_P1					= 1102,
	CIRCULARCURVE_P2					= 1103,
	CIRCULARCURVE_ISCLOCKWISE			= 1104
};

#endif // CBCIRCULAR_H__
