#ifndef COLLIDERTAG_H__
#define COLLIDERTAG_H__

enum
{
	COLLIDER_BOUNCE    = 11010, // real
	COLLIDER_FRICTION    = 11011, // real

	COLLIDER_SET_EXCL   = 11012, // button
	COLLIDER_SHOW_EXCL  = 11013, // button
	COLLIDER_DRAW_EXCL  = 11014, // bool
	COLLIDER_TEXT_EXCL  = 11015, // group
	COLLIDER_CLEAR_EXCL = 11016, // button

	COLLIDER_USE        = 11017, // bool
	CLOTH_PBD_COLLIDER_SIDE = 11018, // Int Cycle
		CLOTH_PBD_COLLIDER_SIDE_NORMALS = 0,
		CLOTH_PBD_COLLIDER_SIDE_INVNORMALS = 1,
		CLOTH_PBD_COLLIDER_SIDE_BOTH = 2,
	COLLIDER_HOLLOW = 11019, // bool
	COLLIDER_STICKINESS = 11020, // real
	COLLIDER_DUMMY
};


#endif // COLLIDERTAG_H__
