#ifndef FAIPDFIMPORT_H__
#define FAIPDFIMPORT_H__

enum
{
	AIIMPORTFILTER_SCALE					= 2000,
		
	AIIMPORTFILTER_CREATE_VECTOROBJECT		= 3000,
	AIIMPORTFILTER_FORCE_PDF				= 3001,
	AIIMPORTFILTER_GREEDY_FILL				= 3002,
};

#endif // FAIPDFIMPORT_H__
