#ifndef FGLTFIMPORTER_H__
#define FGLTFIMPORTER_H__

enum
{
	GLTFIMPORTER_GROUP						= 999,

	GLTFIMPORTER_GROUP_SETTINGS,
		GLTFIMPORTER_TARGET_IDSTRING,
		GLTFIMPORTER_UNITSCALE,
		GLTFIMPORTER_CAMERAS,
		GLTFIMPORTER_GEOMETRY,
		GLTFIMPORTER_NORMALS,
			GLTFIMPORTER_NORMALS_NONE,
			GLTFIMPORTER_NORMALS_VERTEX,
			GLTFIMPORTER_NORMALS_PHONG,
		GLTFIMPORTER_PHONGANGLE,
		GLTFIMPORTER_VERTEXCOLORS,
		GLTFIMPORTER_UVS,
		GLTFIMPORTER_FLIPZ,
		GLTFIMPORTER_MATERIALS,
		GLTFIMPORTER_ANIMATION,
			GLTFIMPORTER_ANIMATION_NONE,
			GLTFIMPORTER_ANIMATION_TRACKS,
			GLTFIMPORTER_ANIMATION_TAKES,
};

#endif // FGLTFIMPORTER_H__
