#ifndef FLCHANNELMIX_H__
#define FLCHANNELMIX_H__

enum
{
	FIELDLAYER_CHANNELMIX_GROUP_VALUE								= 1100, // GROUP
	FIELDLAYER_CHANNELMIX_GROUP_COLOR								= 1101,	// GROUP
	FIELDLAYER_CHANNELMIX_GROUP_DIRECTION						= 1102,	// GROUP
	FIELDLAYER_CHANNELMIX_GROUP_ROTATION						= 1103,	// GROUP

	FIELDLAYER_CHANNELMIX_VALUE											= 1000,	// INT CYCLE
	FIELDLAYER_CHANNELMIX_COLORMODE									= 1001, // INT CYCLE
		FIELDLAYER_CHANNELMIX_COLORMODE_DIRECT					= 0,
		FIELDLAYER_CHANNELMIX_COLORMODE_CHANNELS				= 1,
	FIELDLAYER_CHANNELMIX_COLOR											= 1002,	// INT CYCLE
	FIELDLAYER_CHANNELMIX_COLOR_RED									= 1003, // INT CYCLE
	FIELDLAYER_CHANNELMIX_COLOR_GREEN								= 1004,	// INT CYCLE
	FIELDLAYER_CHANNELMIX_COLOR_BLUE								= 1005, // INT CYCLE
	FIELDLAYER_CHANNELMIX_ALPHA											= 1006, // INT CYCLE

	FIELDLAYER_CHANNELMIX_DIRECTIONMODE							= 1007, // INT CYCLE
		FIELDLAYER_CHANNELMIX_DIRECTIONMODE_DIRECT			= 0,
		FIELDLAYER_CHANNELMIX_DIRECTIONMODE_CHANNELS		= 1,
	FIELDLAYER_CHANNELMIX_DIRECTION_X								= 1008,	// INT CYCLE
	FIELDLAYER_CHANNELMIX_DIRECTION_Y								= 1009, // INT CYCLE
	FIELDLAYER_CHANNELMIX_DIRECTION_Z								= 1010,	// INT CYCLE
	FIELDLAYER_CHANNELMIX_DIRECTION									= 1011,	// INT CYCLE

	FIELDLAYER_CHANNELMIX_ROTATIONMODE							= 1012, // INT CYCLE
		FIELDLAYER_CHANNELMIX_ROTATIONMODE_DIRECT				= 0,
		FIELDLAYER_CHANNELMIX_ROTATIONMODE_CHANNELS			= 1,
	FIELDLAYER_CHANNELMIX_ROTATION_X								= 1013,	// INT CYCLE
	FIELDLAYER_CHANNELMIX_ROTATION_Y								= 1014, // INT CYCLE
	FIELDLAYER_CHANNELMIX_ROTATION_Z								= 1015,	// INT CYCLE
	FIELDLAYER_CHANNELMIX_ROTATION									= 1016,	// INT CYCLE

	FIELDLAYER_CHANNELMIX_SOURCELIST								= 1017,	// FIELDLIST
	
	FIELDLAYER_CHANNELMIX_PIVOTMODE									= 1018, // INT CYCLE
		FIELDLAYER_CHANNELMIX_PIVOTMODE_DIRECT					= 0,
		FIELDLAYER_CHANNELMIX_PIVOTMODE_CHANNELS				= 1,
	FIELDLAYER_CHANNELMIX_PIVOT_X										= 1019,	// INT CYCLE
	FIELDLAYER_CHANNELMIX_PIVOT_Y										= 1020, // INT CYCLE
	FIELDLAYER_CHANNELMIX_PIVOT_Z										= 1021,	// INT CYCLE
	FIELDLAYER_CHANNELMIX_PIVOT											= 1022,	// INT CYCLE
	
	FIELDLAYER_CHANNELMIX_SOURCE_VALUE							= 0, 
	FIELDLAYER_CHANNELMIX_SOURCE_COLOR							= 1,
	FIELDLAYER_CHANNELMIX_SOURCE_COLOR_R						= 2, 
	FIELDLAYER_CHANNELMIX_SOURCE_COLOR_G						= 3, 
	FIELDLAYER_CHANNELMIX_SOURCE_COLOR_B						= 4, 
	FIELDLAYER_CHANNELMIX_SOURCE_COLOR_ALPHA				= 5,
	FIELDLAYER_CHANNELMIX_SOURCE_DIRECTION					= 6,
	FIELDLAYER_CHANNELMIX_SOURCE_DIRECTION_X				= 7, 
	FIELDLAYER_CHANNELMIX_SOURCE_DIRECTION_Y				= 8, 
	FIELDLAYER_CHANNELMIX_SOURCE_DIRECTION_Z				= 9, 
	FIELDLAYER_CHANNELMIX_SOURCE_ROTATION						= 10,
	FIELDLAYER_CHANNELMIX_SOURCE_ROTATION_X					= 11,
	FIELDLAYER_CHANNELMIX_SOURCE_ROTATION_Y					= 12,
	FIELDLAYER_CHANNELMIX_SOURCE_ROTATION_Z					= 13,
	FIELDLAYER_CHANNELMIX_SOURCE_SOLID							= 14,
	FIELDLAYER_CHANNELMIX_SOURCE_PIVOT							= 15,
	FIELDLAYER_CHANNELMIX_SOURCE_PIVOT_X						= 16,
	FIELDLAYER_CHANNELMIX_SOURCE_PIVOT_Y						= 17,
	FIELDLAYER_CHANNELMIX_SOURCE_PIVOT_Z						= 18,
	
	FIELDLAYER_CHANNELMIX_DUMMY
};
#endif	// FLCHANNELMIX_H__

