#ifndef FLDECAY_H__
#define FLDECAY_H__

enum
{
	// Falloff controls
	FIELDLAYER_DECAY_MODE = 1000,	// Int Cycle
	FIELDLAYER_DECAY_DECAY_STRENGTH = 1001,	// Float
	FIELDLAYER_DECAY_FIELDS = 1002,	// FieldList
	FIELDLAYER_DECAY_FIELDS_GRP = 1003,	// Group

	FIELDLAYER_DECAY_MODE_MAX = 0,
	FIELDLAYER_DECAY_MODE_MIN = 1,
};
#endif															// FLDECAY_H__
