#ifndef GVDYNPROXIMITY_H__
#define GVDYNPROXIMITY_H__

#include "gvbase.h"

enum
{
	DYNAMICS_PROXIMITY_NODE_OBJECT = 10001,
	DYNAMICS_PROXIMITY_NODE_MODE = 10002,
	DYNAMICS_PROXIMITY_NODE_MODE_CENTER = 0,
	DYNAMICS_PROXIMITY_NODE_MODE_BOUNDING_BOX = 1,
	DYNAMICS_PROXIMITY_NODE_MODE_SHAPE = 2,
	DYNAMICS_PROXIMITY_NODE_EXCLUDE_OBJECT = 10003,

	DYNAMICS_PROXIMITY_NODE_INPUT_OBJECT = 10101,
	DYNAMICS_PROXIMITY_NODE_INPUT_INDEX = 10102,
	DYNAMICS_PROXIMITY_NODE_INPUT_EXCLUDE_OBJECT = 10103,
	DYNAMICS_PROXIMITY_NODE_INPUT_EXCLUDE_INDEX = 10104,
	DYNAMICS_PROXIMITY_NODE_INPUT_POINT = 10111,

	DYNAMICS_PROXIMITY_NODE_OUTPUT_OBJECT = 10211,
	DYNAMICS_PROXIMITY_NODE_OUTPUT_TAG = 10212,
	DYNAMICS_PROXIMITY_NODE_OUTPUT_INDEX = 10213,
	DYNAMICS_PROXIMITY_NODE_OUTPUT_DISTANCE = 10221,
	DYNAMICS_PROXIMITY_NODE_OUTPUT_POSITION = 10222,
	DYNAMICS_PROXIMITY_NODE_OUTPUT_LOCAL_POSITION = 10223,
	DYNAMICS_PROXIMITY_NODE_OUTPUT_POINT_INDEX = 10224,
};

#endif // GVDYNPROXIMITY_H__
