#ifndef GVSPLINE_H__
#define GVSPLINE_H__

#include "gvbase.h"

enum
{
	GV_SPLINE_MODE									= 1000,
		GV_SPLINE_OPERATOR_MODE_GLOBAL = 100,
		GV_SPLINE_OPERATOR_MODE_LOCAL = 101,
	GV_SPLINE_USE_NATURAL = 102,
	GV_SPLINE_ALL_SEGMENTS = 1001,

	GV_SPLINE_INPUT_OBJECT					= 2000,
	GV_SPLINE_INPUT_POINT,
	GV_SPLINE_INPUT_SEGMENT,

	GV_SPLINE_OUTPUT_POSITION			= 3000,
	GV_SPLINE_OUTPUT_TANGENT,
	GV_SPLINE_OUTPUT_LENGTH,
	GV_SPLINE_OUTPUT_IS_CLOSED,
	GV_SPLINE_OUTPUT_SEGMENTS,
	GV_SPLINE_
};

#endif // GVSPLINE_H__
