#ifndef ODEFLECTOR_H__
#define ODEFLECTOR_H__

enum
{
	DEFLECTOROBJECT_SIZEX				= 1000,
	DEFLECTOROBJECT_SIZEY				= 1001,
	DEFLECTOROBJECT_SPLIT				= 1002,
	DEFLECTOROBJECT_ELASTICITY	= 1003
};

#endif // ODEFLECTOR_H__
