#ifndef OEINHERITANCE_H__
#define OEINHERITANCE_H__

enum
{
	//groups
	MGINHERITANCEEFFECTOR_GROUPPARAMETER	= 990,
	MGINHERITANCEEFFECTOR_GROUPEFFECTOR		= 991,

	//subgroups
	MGINHERITANCEEFFECTOR_GROUPTRANSFORM	= 995,

	//------------------------------
	//Effector controls
	MGINHERITANCEEFFECTOR_STRENGTH				= 1000,

	MGINHERITANCEEFFECTOR_SELECTION				=	1021,

	//-------------------------------
	//Parameter controls
	MGINHERITANCEEFFECTOR_POSITION_ACTIVE = 1060,
	MGINHERITANCEEFFECTOR_SCALE_ACTIVE		= 1061,
	MGINHERITANCEEFFECTOR_ROTATION_ACTIVE = 1062,
	MGINHERITANCEEFFECTOR_OBJECT					= 1100,
	MGINHERITANCEEFFECTOR_MORPHMG					= 1101,
	MGINHERITANCEEFFECTOR_MODE						= 1102,
	MGINHERITANCEEFFECTOR_MODE_DIRECT			= 0,
	MGINHERITANCEEFFECTOR_MODE_ANIMATION	= 1,
	MGINHERITANCEEFFECTOR_ANIMATEFROM			= 1103,
	MGINHERITANCEEFFECTOR_ANIMATETO				= 1104,
	MGINHERITANCEEFFECTOR_EASE						= 1105,
	MGINHERITANCEEFFECTOR_EASE_IN					= 0,
	MGINHERITANCEEFFECTOR_EASE_OUT				= 1,
	MGINHERITANCEEFFECTOR_STEP						= 1106,
	MGINHERITANCEEFFECTOR_FALLOFFTIME			= 1107,
	MGINHERITANCEEFFECTOR_SPACEMODE				= 1108,
	MGINHERITANCEEFFECTOR_SPACEMODE_GLOBAL = 0,
	MGINHERITANCEEFFECTOR_SPACEMODE_NODE	= 1,
	MGINHERITANCEEFFECTOR_LOOPANIMATION		= 1109
};
#endif // OEINHERITANCE_H__
