#ifndef OFPCONDITION_H__
#define OFPCONDITION_H__

enum
{
	FP_CONDITION_BYPASS = 1000,
	FP_CONDITION_OBJECT_GROUP = 2000,
	FP_CONDITION_OBJECT_CHANNEL = 2001,
		FP_CONDITION_OBJECT_CHANNEL_AGE = 0,
		FP_CONDITION_OBJECT_CHANNEL_COLOR,
		FP_CONDITION_OBJECT_CHANNEL_GROUP,
		FP_CONDITION_OBJECT_CHANNEL_POSITION,
		FP_CONDITION_OBJECT_CHANNEL_VELOCITY,
	FP_CONDITION_OBJECT_EXTRACT = 2002,
		FP_CONDITION_OBJECT_EXTRACT_COMPONENT_X = 0,
		FP_CONDITION_OBJECT_EXTRACT_COMPONENT_Y,
		FP_CONDITION_OBJECT_EXTRACT_COMPONENT_Z,
		FP_CONDITION_OBJECT_EXTRACT_COMPONENT_W,
		FP_CONDITION_OBJECT_EXTRACT_CROSS,
		FP_CONDITION_OBJECT_EXTRACT_DEFAULT,
		FP_CONDITION_OBJECT_EXTRACT_DOT,
		FP_CONDITION_OBJECT_EXTRACT_LENGTH,
		FP_CONDITION_OBJECT_EXTRACT_MAX,
		FP_CONDITION_OBJECT_EXTRACT_MIN,
		FP_CONDITION_OBJECT_EXTRACT_NORMALIZE,
	FP_CONDITION_OBJECT_EXTRACTVECTORVALUE = 2004,
	FP_CONDITION_OBJECT_EXTRACTCHANNEL = 2005,
	FP_CONDITION_OBJECT_CMPOPERATOR = 2006,
		FP_CONDITION_OBJECT_CMPOPERATOR_EQUALS = 0,
		FP_CONDITION_OBJECT_CMPOPERATOR_GREATERTHAN,
		FP_CONDITION_OBJECT_CMPOPERATOR_GREATERTHANEQUALS,
		FP_CONDITION_OBJECT_CMPOPERATOR_INSIDE,
		FP_CONDITION_OBJECT_CMPOPERATOR_LESSTHAN,
		FP_CONDITION_OBJECT_CMPOPERATOR_LESSTHANEQUALS,
		FP_CONDITION_OBJECT_CMPOPERATOR_NOTEQUALS,
		FP_CONDITION_OBJECT_CMPOPERATOR_OUTSIDE,
	FP_CONDITION_OBJECT_CMPSCALARVALUE = 2007,
	FP_CONDITION_OBJECT_CMPVECTORVALUE = 2008,
	FP_CONDITION_OBJECT_SCALARRANGE_LOWER = 2009,
	FP_CONDITION_OBJECT_SCALARRANGE_UPPER = 2010,
	FP_CONDITION_OBJECT_VECTORRANGE_LOWER = 2011,
	FP_CONDITION_OBJECT_VECTORRANGE_UPPER = 2012,
	FP_CONDITION_OBJECT_CMPERRORTOLERANCE = 2013,
	FP_CONDITION_OBJECT_DUMMY
};

#endif // OFPCONDITION_H__
