#ifndef OMOGRAPH_MATRIX_H__
#define OMOGRAPH_MATRIX_H__

enum
{
	MGMATRIXOBJECT_MODE									= 1020,
	MGMATRIXOBJECT_MODE_MATRIX					= 0,
	MGMATRIXOBJECT_MODE_TP							= 1,
	MGMATRIXOBJECT_PARTICLE_GROUP				= 1021,
	MGMATRIXOBJECT_PARTICLE_BLENDFOLLOW = 1022,
	MGMATRIXOBJECT_PARTICLE_BLENDDIRECT = 1023,
	MGMATRIXOBJECT_TPPRIORITY						= 1024,
	MGMATRIXOBJECT_TPPRIORITY_BEFORE		= 0,
	MGMATRIXOBJECT_TPPRIORITY_AFTER			= 1,
	MGMATRIXOBJECT_GROUPBASE						= 3000
};
#endif // OMOGRAPH_MATRIX_H__
