#ifndef OPOINTCREATOR_PANEL_H__
#define OPOINTCREATOR_PANEL_H__

enum
{
	ID_POINTCREATOR_CREATORTYPE = 5999,
	ID_POINTCREATOR_CREATORTYPE_DISTRIBUTION = 1,
	ID_POINTCREATOR_CREATORTYPE_SHADER = 2,
	
	ID_POINTCREATOR_CREATEPOINTSTAB = 6000,
	ID_POINTCREATOR_CREATEPOINTSNAME = 6001,
	ID_POINTCREATOR_CREATEPOINTSDISTRIBUTION = 6002,
	ID_POINTCREATOR_CREATEPOINTSUNIFORM = 1,
	ID_POINTCREATOR_CREATEPOINTSNORMAL = 2,
	ID_POINTCREATOR_CREATEPOINTSINVNORMAL = 3,
	ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL = 4,
	
	ID_POINTCREATOR_CREATEPOINTSNORMAL_STANDARDDEVIATION = 6003,
	ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_X = 6004,
	ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_Y = 6005,
	ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_Z = 6006,
	ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_ON = 1,
	ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_OFF = 2,
	ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_INV = 3,
	ID_POINTCREATOR_CREATEDPOINTAMOUNT = 6007,
	ID_POINTCREATOR_CREATEPOINTSSEED = 6008,
	ID_POINTCREATOR_CREATEPOINTS_ONLY_INSIDE = 6009,
	ID_POINTCREATOR_CREATEPOINTS_ONLY_INSIDE_HIGH_QUALITY = 6038,
	ID_POINTCREATOR_CREATEPOINTS_PEROBJECT = 6010,
	
	ID_POINTCREATOR_CREATEPOINTS_TRANSFORMATIONTAB = 6011,
	ID_POINTCREATOR_CREATEPOINTS_TRANSLATE = 6012,
	ID_POINTCREATOR_CREATEPOINTS_SCALE = 6013,
	ID_POINTCREATOR_CREATEPOINTS_ROTATE = 6014,

	
	ID_POINTCREATOR_SHADERTAB = 6016,
	ID_POINTCREATOR_SHADERNAME = 6017,
	ID_POINTCREATOR_SHADERINPUT = 6018,
	
	ID_POINTCREATOR_SHADER_SAMPLEMODE = 6035,
	ID_POINTCREATOR_SHADER_SAMPLEMODE_VOLUME = 1,
	ID_POINTCREATOR_SHADER_SAMPLEMODE_SURFACE = 2,
	ID_POINTCREATOR_SHADERSAMPLEAMOUNT = 6036,
	ID_POINTCREATOR_SHADERSAMPLEDENSITY = 6019,
	ID_POINTCREATOR_SHADERSAMPLESEED = 6020,
	ID_POINTCREATOR_SHADERSAMPLESAMPLEDEPTH = 6021,
	
	ID_POINTCREATOR_SHADER_CHANNELSELECT = 6022,
	
	ID_POINTCREATOR_SHADER_CHANNELSELECT_COLOR = 807,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_DIFFUSION = 808,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_LUMINANCE = 809,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_TRANSPARENCY = 810,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_REFLECTION = 811,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_ENVIRONMENT = 812,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_BUMP = 814,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_ALPHA = 815,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_SPECULAR = 816,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_DISPLACEMENT = 819,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_NORMAL = 3301,
	ID_POINTCREATOR_SHADER_CHANNELSELECT_DIRECT = 830,
	
	ID_POINTCREATOR_SHADER_EDIT_CHANNEL = 6023,
	ID_POINTCREATOR_SHADER_MATERIALTAG = 6024,
	ID_POINTCREATOR_SHADER_SHADER = 6025,
	ID_POINTCREATOR_SHADER_GROUPPROJECTION = 6026,
	ID_POINTCREATOR_SHADER_TEXTAG_OFFSETX = 6027,
	ID_POINTCREATOR_SHADER_TEXTAG_OFFSETY = 6028,
	ID_POINTCREATOR_SHADER_TEXTAG_LENGTHX = 6029,
	ID_POINTCREATOR_SHADER_TEXTAG_LENGTHY = 6030,
	ID_POINTCREATOR_SHADER_TEXTAG_TILE = 6031,
	ID_POINTCREATOR_SHADER_GROUPALPHA = 6032,
	ID_POINTCREATOR_SHADER_USE = 6033,
	ID_POINTCREATOR_SHADER_USE_ALPHA = 1,
	ID_POINTCREATOR_SHADER_USE_GRAY = 2,
	ID_POINTCREATOR_SHADER_USE_RED = 3,
	ID_POINTCREATOR_SHADER_USE_GREEN = 4,
	ID_POINTCREATOR_SHADER_USE_BLUE = 5,
	ID_POINTCREATOR_SHADER_INVERTALPHA = 6034,
	ID_POINTCREATOR_SHADER_PEROBJECT = 6037,
	
};

#endif // OPOINTCREATOR_PANEL_H__