#ifndef OPOINTPROJECTOR_H__
#define OPOINTPROJECTOR_H__

enum
{
	POINTPROJECTOR_GROUP_PARAMS						= 1000,	// GROUP
	POINTPROJECTOR_LINK										= 1001,	// LINK
	POINTPROJECTOR_MODE										= 1002,	// LONG CYCLE
		POINTPROJECTOR_MODE_PARALLEL					= 1,		// CYCLE VALUE
		POINTPROJECTOR_MODE_SPHERICAL					= 2,		// CYCLE VALUE
	POINTPROJECTOR_ALIGNMENT							= 1007,	// LONG
		POINTPROJECTOR_ALIGNMENT_POSITIVE_X		= 3,		// CYCLE VALUE
		POINTPROJECTOR_ALIGNMENT_NEGATIVE_X		= 4,		// CYCLE VALUE
		POINTPROJECTOR_ALIGNMENT_POSITIVE_Y		= 5,		// CYCLE VALUE
		POINTPROJECTOR_ALIGNMENT_NEGATIVE_Y		= 6,		// CYCLE VALUE
		POINTPROJECTOR_ALIGNMENT_POSITIVE_Z		= 7,		// CYCLE VALUE
		POINTPROJECTOR_ALIGNMENT_NEGATIVE_Z		= 8,		// CYCLE VALUE
	POINTPROJECTOR_INCLUDE_HIERARCHY			= 1006,	// BOOL
	POINTPROJECTOR_OFFSET									= 1003,	// REAL
	POINTPROJECTOR_STRENGTH								= 1004,	// REAL
	POINTPROJECTOR_FALLOFF								= 1005,	// FIELDLIST
	POINTPROJECTOR_FALLOFF_GROUP_PARAMS   = 1006, // GROUP
};

#endif // OPOINTPROJECTOR_H__
