#ifndef OSOLIDIFYGENERATORSELECTION_H__
#define OSOLIDIFYGENERATORSELECTION_H__

enum
{
	ID_SOLIDIFYGENERATOR_SELECTION_POLYGONS = 4000,
	SOLIDIFYGENERATOR_SELECTION_POLYGON_SOURCE = 4001,
	SOLIDIFYGENERATOR_SELECTION_POLYGON_CAP = 4002,
	SOLIDIFYGENERATOR_SELECTION_POLYGON_BOUNDARY = 4003,
	ID_SOLIDIFYGENERATOR_SELECTION_POLY = 4004,

	
	ID_SOLIDIFYGENERATOR_SELECTION_EDGES = 4010,
	SOLIDIFYGENERATOR_SELECTION_EDGE_BORDER_SOURCE = 4011,
	SOLIDIFYGENERATOR_SELECTION_EDGE_BORDER_CAP = 4012,

	ID_SOLIDIFYGENERATOR_SELECTION_VERTICES = 4020,
	SOLIDIFYGENERATOR_SELECTION_VERTEX_SOURCE = 4021,
	SOLIDIFYGENERATOR_SELECTION_VERTEX_CAP = 4022,

	SOLIDIFYGENERATOR_SELECTION_NAME_POLYGON_SOURCE = 4101,
	SOLIDIFYGENERATOR_SELECTION_NAME_POLYGON_CAP = 4102,
	SOLIDIFYGENERATOR_SELECTION_NAME_POLYGON_BOUNDARY = 4103,
	
	SOLIDIFYGENERATOR_SELECTION_NAME_EDGE_BORDER_SOURCE = 4111,
	SOLIDIFYGENERATOR_SELECTION_NAME_EDGE_BORDER_CAP = 4112,

	SOLIDIFYGENERATOR_SELECTION_NAME_VERTEX_SOURCE = 4121,
	SOLIDIFYGENERATOR_SELECTION_NAME_VERTEX_CAP = 4122,

	SOLIDIFYGENERATOR_SELECTION_INDEX_POLYGON_SOURCE = 4201,
	SOLIDIFYGENERATOR_SELECTION_INDEX_POLYGON_CAP = 4202,
	SOLIDIFYGENERATOR_SELECTION_INDEX_POLYGON_BOUNDARY = 4203,

	SOLIDIFYGENERATOR_SELECTION_INDEX_EDGE_BORDER_SOURCE = 4211,
	SOLIDIFYGENERATOR_SELECTION_INDEX_EDGE_BORDER_CAP = 4212,
	
	SOLIDIFYGENERATOR_SELECTION_INDEX_VERTEX_SOURCE = 4221,
	SOLIDIFYGENERATOR_SELECTION_INDEX_VERTEX_CAP = 4222
};

#endif
