#ifndef OXREF_H__
#define OXREF_H__

enum
{
	ID_CA_XREF_PIVOT_GROUP = 5000,
	ID_CA_XREF_ANIM_GROUP,

	ID_CA_XREF_SHOWOBJECTS = 1000,
	ID_CA_XREF_FILE,
	ID_CA_XREF_PROXY_FILE,
	ID_CA_XREF_SWAP,
	ID_CA_XREF_REFRESH,
	ID_CA_XREF_OPTIONS,
	ID_CA_XREF_LOADED,
	ID_CA_XREF_NAMESPACE,
	ID_CA_XREF_EDIT,
	ID_CA_XREF_FILE_SELECT,
	ID_CA_XREF_PROXY_FILE_SELECT,
	ID_CA_XREF_ANIMATE,
	ID_CA_XREF_TIME,
	ID_CA_XREF_OFFSET,
	ID_CA_XREF_SCALE,
	ID_CA_XREF_GENERATOR,
	ID_CA_XREF_PIVOT_POS,
	ID_CA_XREF_PIVOT_SCL,
	ID_CA_XREF_PIVOT_ROT,

	ID_CA_XREF_REFID = 10000,
	ID_CA_XREF_REF_NAME,
	ID_CA_XREF_RELATIVE,
	ID_CA_XREF_SWAP_STATE,
	ID_CA_XREF_REF_REV,
	ID_CA_XREF_FLAGS,
	ID_CA_XREF_REF_STATEFILE,
	ID_CA_XREF_COPYID,
	ID_CA_XREF_DATA_CONTAINER,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_XREF_DUMMY
};

#endif // OXREF_H__
