#ifndef PREFSCOMMUNICATION_H__
#define PREFSCOMMUNICATION_H__

enum
{
	PREF_COMMUNICATION_MAINGROUP								= 999,
	PREF_COMMUNICATION_BUGREPORTS								= 1003,
	
	PREF_COMMUNICATION_QUICKSTART_DIALOG = 1030,

	PREF_COMMUNICATION_DUMMY
};

#endif // PREFSCOMMUNICATION_H__
