#ifndef _GoZ_PREFERENCES_
#define _GoZ_PREFERENCES_


enum {
        GOZ_SCALE_FACTOR_EXPORT = 1000,
        GOZ_SCALE_FACTOR_IMPORT,

        GOZ_IMPORT_GROUP,
        GOZ_IMPORT_COLOR_MAP,
        GOZ_IMPORT_NORMAL_MAP,
        GOZ_IMPORT_DISPLACEMENT_MAP,
        GOZ_IMPORT_UVW,
        GOZ_IMPORT_POLYPAINT,
        GOZ_IMPORT_POLYGROUP,

        GOZ_EXPORT_GROUP,
        GOZ_EXPORT_COLOR_MAP,
        GOZ_EXPORT_NORMAL_MAP,
        GOZ_EXPORT_DISPLACEMENT_MAP,
        GOZ_EXPORT_UVW,
        GOZ_EXPORT_POLYPAINT,
        GOZ_EXPORT_POLYGROUP,
        PREFS_GOZ_GROUP,
        GOZ_EXPORT_CONNECTWITHCHILDREN,
        GOZ_EXPORT_SHIFTKEY,
        GOZ_IMPORT_REPLACEEXISTING,
        GOZ_IMPORT_CREASE_EDGE,
        GOZ_EXPORT_CREASE_EDGE,
        GOZ_EXPORT_BAKE_MATERIALS,
        GOZ_EXPORT_BAKEDTEXTURE_WIDTH,
        GOZ_EXPORT_BAKEDTEXTURE_HEIGHT,
        GOZ_EXPORT_BAKEDTEXTURE_FORMAT,
        GOZ_EXPORT_BAKEDTEXTURE_DEPTH,
          GOZ_EXPORT_BAKEDTEXTURE_DEPTH_8	  = 0,
          GOZ_EXPORT_BAKEDTEXTURE_DEPTH_16	= 1,
          GOZ_EXPORT_BAKEDTEXTURE_DEPTH_32	= 2,
        GOZ_IMPORT_TARGET,
          GOZ_IMPORT_TARGET_AUTO = 0,
          GOZ_IMPORT_TARGET_STANDARD = 1,
          GOZ_IMPORT_TARGET_REDSHIFT = 2
};


#endif