#ifndef PREFSBROWSER_H__
#define PREFSBROWSER_H__

enum
{
	PREF_BROWSER_MAIN_GROUP				= 999,
	PREF_BROWSER_PREVIEWWIDTH			= 1011,
	PREF_BROWSER_PREVIEWHEIGHT		= 1012,

	PREF_BROWSER_DOWNLOAD_LOCATION	= 1013,
	PREF_BROWSER_CLEAR_DOWNLOADED		= 1014,
	PREF_BROWSER_DOWNLOADED_SIZE		= 1015,
	PREF_BROWSER_SHOW_UNAVAILABLE		= 1016,
	PREF_BROWSER_DATABASE_PATHS			= 1017,
	PREF_BROWSER_RECALCULATE_SIZE   = 1018,
	PREF_BROWSER_WATCHFOLDER_AUTOMOUNT_DOCUMENTS = 1019,

	PREF_BROWSER_SIZESTR					= 2001,
	PREF_BROWSER_SEKSTR						= 2002,

	PREFS_BROWSER_DUMMY
};

#endif // PREFSBROWSER_H__
