#ifndef TALIGNTOSPLINE_H__
#define TALIGNTOSPLINE_H__

enum
{
	ALIGNTOSPLINETAG_TANGENTIAL				  = 1000,
	ALIGNTOSPLINETAG_LINK							  = 1001,
	ALIGNTOSPLINETAG_RAIL							  = 1002,
	ALIGNTOSPLINETAG_POSITION					  =	1003,
	ALIGNTOSPLINETAG_SEGMENT					  = 1004,
	ALIGNTOSPLINETAG_AXIS							  = 1007,
		ALIGNTOSPLINETAG_AXIS_POSITIVE_X    = 0,
		ALIGNTOSPLINETAG_AXIS_NEGATIVE_X    = 3,
		ALIGNTOSPLINETAG_AXIS_POSITIVE_Y		= 1,
		ALIGNTOSPLINETAG_AXIS_NEGATIVE_Y		= 4,
		ALIGNTOSPLINETAG_AXIS_POSITIVE_Z		= 2,
		ALIGNTOSPLINETAG_AXIS_NEGATIVE_Z		= 5,
	ALIGNTOSPLINETAG_OVERSHOOT				= 1008,
		ALIGNTOSPLINETAG_OVERSHOOT_LOOP     = 0,
		ALIGNTOSPLINETAG_OVERSHOOT_EXTEND   = 1,
		ALIGNTOSPLINETAG_OVERSHOOT_CLAMP    = 2
};

#endif // TALIGNTOSPLINE_H__
