#ifndef TCHARACTERDEF_H__
#define TCHARACTERDEF_H__

enum
{
	CD_BODYPART_GROUP = 1000, // Group

	// BodyPart Attributes
	CD_BODYPART_SKELETON = 2000,
	CD_BODYPART_CONTROLLERS,
	CD_BODYPART_CONTAINER_ID,

	// functions
	CD_SETREFERENCEPOSE,
	CD_GOTOREFERENCEPOSE,
	CD_OPENMANAGER,
	CD_CREATESOLVER,

	CD_LAST
};

#endif // TCHARACTERDEF_H__
