#ifndef TCUSTOMDATABASE_H__
#define TCUSTOMDATABASE_H__

enum
{
	ID_CUSTOMDATATAG_TAGPROPRETY = 1001,
	ID_CUSTOMDATATAG_MODE = 1002,
		ID_CUSTOMDATATAG_MODE_VERTEX = 0,
		ID_CUSTOMDATATAG_MODE_POLYVERTEX = 1,
};

#endif // TCUSTOMDATABASE_H__

