#ifndef TEDGESELECTION_H__
#define TEDGESELECTION_H__

enum
{
	EDGESELECTIONTAG_FIELDGROUP			= 2000,			// GROUP
	EDGESELECTIONTAG_FIELDS					= 2001,			// FIEDLIST
	EDGESELECTIONTAG_ENABLEFIELDS		= 2002,			// BOOL
	EDGESELECTIONTAG_FIELDTOLERANCE = 2003,			// FLOAT
	EDGESELECTIONTAG_DEFORMEDSTATE	= 2004,			// BOOL
	EDGESELECTIONTAG_FIELDTAB 			= 2005,

	EDGESELECTIONTAG_COMMAND1 = 1000, // virtual ID
	EDGESELECTIONTAG_COMMAND2 = 1001,
	EDGESELECTIONTAG_COMMAND3 = 1002,
	EDGESELECTIONTAG_COMMAND4 = 1003,
	EDGESELECTIONTAG_COMMAND5 = 1004,
	EDGESELECTIONTAG_COMMAND6 = 1005,
	EDGESELECTIONTAG_COMMANDTAB = 1006,
	EDGESELECTIONTAG_UPDATE = 1007,
	EDGESELECTIONTAG_COUNT = 1008,
	EDGESELECTIONTAG_UNHIDEALL = 1009,
	EDGESELECTIONTAG_MODIFIERHINT = 1010
};

#endif // TEDGESELECTION_H__
