#ifndef TFRACTUREVORONOI_H__
#define TFRACTUREVORONOI_H__

enum
{
	ID_FRACTURETAG_LOCKMATRIX = 7998,
	ID_FRACTURETAG_TAGMODE = 7999,
	ID_FRACTURETAG_TAGMODE_OBJECT = 1,
	ID_FRACTURETAG_TAGMODE_SPLINE = 2,
	ID_FRACTURETAG_TAGMODE_TP = 3,
	ID_FRACTURETAG_TAGMODE_DEFAULT = 4,
	ID_FRACTURETAG_TAGMODE_MIXOBJECTSPLINE = 5,
	ID_FRACTURETAG_MAINTAB = 8000,
	ID_FRACTURETAG_OBJECTLINK = 8001,
	ID_FRACTURETAG_POINTCREATIONTYPE = 8002,
	ID_FRACTURETAG_VERTICES = 1,
	ID_FRACTURETAG_EDGES = 2,
	ID_FRACTURETAG_POLYS = 3,
	ID_FRACTURETAG_SURFACE = 4,
	ID_FRACTURETAG_VOLUME = 5,
	ID_FRACTURETAG_POINTAMOUNT = 8003,
	ID_FRACTURETAG_SEED = 8004,
	ID_FRACTURETAG_OFFSET = 8005,
	ID_FRACTURETAG_LOCK = 8006,
	ID_FRACTURETAG_POLY = 8007,
	ID_FRACTURETAG_TP = 8011,
	ID_FRACTURETAG_TP_SUBGROUPS = 8008,
	ID_FRACTURETAG_SPLINE = 8009,
	ID_FRACTURETAG_SPLINE_DISTRIBUTION = 8010,
	ID_FRACTURETAG_SPLINE_EVEN = 1,
	ID_FRACTURETAG_SPLINE_STEP = 2,
	ID_FRACTURETAG_SPLINE_COUNT = 3,
	ID_FRACTURETAG_SPLINE_VERTICES = 4
	
};
#endif // TFRACTUREVORONOI_H__