#ifndef THAIRSPLINEDYNAMICS_H__
#define THAIRSPLINEDYNAMICS_H__

enum
{
	HAIR_SDYNAMICS_TAG_GROUP_ADVANCED = 3000,
	HAIR_SDYNAMICS_TAG_GROUP_PROPERTIES = 3001,
	HAIR_SDYNAMICS_TAG_GROUP_FORCES= 3002,
	HAIR_SDYNAMICS_TAG_GROUP_CACHE= 3003,

	HAIR_SDYNAMICS_TAG_ENABLE = 1000,
	HAIR_SDYNAMICS_TAG_COLLISIONS = 1001,
	HAIR_SDYNAMICS_TAG_AUTOTIME = 1002,
	HAIR_SDYNAMICS_TAG_START = 1003,
	HAIR_SDYNAMICS_TAG_STOP = 1004,
	HAIR_SDYNAMICS_TAG_DRAG = 1005,
	HAIR_SDYNAMICS_TAG_GRAVITY = 1006,
	HAIR_SDYNAMICS_TAG_STIFFNESS = 1007,
	HAIR_SDYNAMICS_TAG_EXTRA_STIFF = 1008,
	HAIR_SDYNAMICS_TAG_SUBDIV = 1009,
	HAIR_SDYNAMICS_TAG_ITERATIONS = 10102,
	HAIR_SDYNAMICS_TAG_RADIUS = 1011,

	HAIR_SDYNAMICS_TAG_MASS = 1012,
	HAIR_SDYNAMICS_TAG_SETMASS = 1013,
	HAIR_SDYNAMICS_TAG_SET_FIXED = 1014,
	HAIR_SDYNAMICS_TAG_RELEASE_FIXED = 1015,
	HAIR_SDYNAMICS_TAG_CLEAR_FIXED = 1016,
	HAIR_SDYNAMICS_TAG_DRAW_FIXED = 1017,

	HAIR_SDYNAMICS_TAG_RUBBER = 1018,
	HAIR_SDYNAMICS_TAG_SET_STATE = 1019,
	HAIR_SDYNAMICS_TAG_FIXED = 1020,

	HAIR_SDYNAMICS_TAG_FORCES_INCEXC = 1021,
	HAIR_SDYNAMICS_TAG_FORCES_INCLUDE = 1022,

	HAIR_SDYNAMICS_REST_MIX = 1023,
	HAIR_SDYNAMICS_REST_HOLD = 1024,
	HAIR_SDYNAMICS_ELASTIC_LIMIT = 1025,
	HAIR_SDYNAMICS_ELASTIC_DEFORM = 1026,

	HAIR_SDYNAMICS_CACHE_ENABLE = 1027,
	HAIR_SDYNAMICS_CACHE_CALCULATE = 1028,
	HAIR_SDYNAMICS_CACHE_COMPRESSED = 1029,
	HAIR_SDYNAMICS_CACHE_DELETE = 1030,
	HAIR_SDYNAMICS_CACHE_INFO2 = 1031,
	HAIR_SDYNAMICS_CACHE_CACHE_FRAME = 1032,
	HAIR_SDYNAMICS_CACHE_CACHE_LOAD = 1033,
	HAIR_SDYNAMICS_CACHE_CACHE_SAVE = 1034,
	HAIR_SDYNAMICS_CACHE_CACHE_LIMIT = 1035,
	HAIR_SDYNAMICS_CACHE_TEXT_LIMIT = 1036,

	//	HAIR_CONSTRAINTS_TAG_SET_ANCHOR = 5000,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SDYNAMICS_TAG_INCEXC_INCLUDE = 0,
	HAIR_SDYNAMICS_TAG_INCEXC_EXCLUDE = 1,

	//////////////////////////////////////////////////////////////////////////
	// START OF PBD SDYNAMICS INTEGRATION
	HAIR_SDYNAMICS_LEGACY_SETTINGS_GROUP = 19998,
	HAIR_SDYNAMICS_PBD_SETTINGS_GROUP = 19999,

	HAIR_SDYNAMICS_PBD_BENDINESS = 20001,
	HAIR_SDYNAMICS_PBD_STRETCHINESS = 20002,
	HAIR_SDYNAMICS_PBD_FRICTION = 20003,
	HAIR_SDYNAMICS_PBD_RADIUS = 20004,
	HAIR_SDYNAMICS_PBD_MASS = 20005,
	HAIR_SDYNAMICS_PBD_TEARING = 20006,
	HAIR_SDYNAMICS_PBD_TEARPAST = 20007,
	HAIR_SDYNAMICS_PBD_TWISTINESS = 20008,
	HAIR_SDYNAMICS_PBD_FORCES_GROUP = 20012,
	HAIR_SDYNAMICS_PBD_FORCES_INEXCLUDE = 20013,
	HAIR_SDYNAMICS_PBD_DRAW_FIXED = 20014,
	HAIR_SDYNAMICS_PBD_FIXED = 20015,
	HAIR_SDYNAMICS_PBD_SET_FIXED = 20016,
	HAIR_SDYNAMICS_PBD_RELEASE_FIXED = 20017,
	HAIR_SDYNAMICS_PBD_CLEAR_FIXED = 20018,
	HAIR_SDYNAMICS_PBD_BOUNCINESS = 20019,
	HAIR_SDYNAMICS_CACHE_CALCULATE_ALL = 20020,
	HAIR_SDYNAMICS_CACHE_DELETE_ALL = 20021,
	HAIR_SDYNAMICS_LEGACYON = 20022,
	HAIR_SDYNAMICS_PBD_FOLLOW_ANIMATION_GROUP = 20023,
	HAIR_SDYNAMICS_PBD_FOLLOW_ANIMATION_FORCE = 20024,
	HAIR_SDYNAMICS_PBD_FOLLOW_ANIMATION_FORCE_STRENGTH = 20025,
	HAIR_SDYNAMICS_PBD_FOLLOW_ANIMATION_FORCE_STRENGTH_WEIGHTS = 20026,
	HAIR_SDYNAMICS_PBD_FOLLOW_ANIMATION_FORCE_STRENGTH_SCALE = 20027,
	HAIR_SDYNAMICS_PBD_FOLLOW_ANIMATION_PINS = 20028,
	HAIR_SDYNAMICS_PBD_FOLLOW_ANIMATION_PINS_STRETCHINESS = 20029,
	HAIR_SDYNAMICS_PBD_FOLLOW_ANIMATION_PINS_STRETCHINESS_WEIGHTS = 20030,
	HAIR_SDYNAMICS_PBD_FOLLOW_ANIMATION_PINS_STRETCHINESS_SCALE = 20031,
	HAIR_SDYNAMICS_PBD_TARGET_LENGTH = 20032,
	HAIR_SDYNAMICS_PBD_STICKINESS = 20033,
	HAIR_SDYNAMICS_PBD_FORCES_INEXMODE = 20034,
		HAIR_SDYNAMICS_PBD_FORCES_INEXMODE_INCLUDE = 0,
		HAIR_SDYNAMICS_PBD_FORCES_INEXMODE_EXCLUDE = 1,
	HAIR_SDYNAMICS_PBD_FOLLOW_SHAPE = 20035,
	HAIR_SDYNAMICS_PBD_FORCES_INEX_PYRO = 20036,
	HAIR_SDYNAMICS_PBD_BENDINESS_WEIGHTS = 20037,
	HAIR_SDYNAMICS_PBD_STRETCHINESS_WEIGHTS = 20038,
	HAIR_SDYNAMICS_PBD_FRICTION_WEIGHTS = 20039,
	HAIR_SDYNAMICS_PBD_RADIUS_WEIGHTS = 20040,
	HAIR_SDYNAMICS_PBD_MASS_WEIGHTS = 20041,
	HAIR_SDYNAMICS_PBD_TEARING_WEIGHTS = 20042,
	HAIR_SDYNAMICS_PBD_MAPMINTEARPAST = 20043,
	HAIR_SDYNAMICS_PBD_BOUNCINESS_WEIGHTS = 20044,
	HAIR_SDYNAMICS_PBD_STICKINESS_WEIGHTS = 20045,
	HAIR_SDYNAMICS_PBD_TARGET_LENGTH_WEIGHTS = 20046,
	HAIR_SDYNAMICS_PBD_TARGET_LENGTH_MIN = 20047,
	HAIR_SDYNAMICS_TAG_DUMMY
};

#endif // THAIRSPLINEDYNAMICS_H__
