#ifndef TMGSELECTION_H__
#define TMGSELECTION_H__

enum
{
	MGSELECTIONTAG_CLEAR						= 1000,		// Button
	MGSELECTIONTAG_INVERT						= 1001,		// Button
	MGSELECTIONTAG_NUMBERS					= 1002,		// Bool

	MGSELECTIONTAG_USEFIELDS				= 1003,		// Bool
	MGSELECTIONTAG_FIELDGROUP				= 1004,		// Group
	MGSELECTIONTAG_FIELDS						= 1005,		// FieldList
	MGSELECTIONTAG_FIELDTOLERANCE		= 1006,		// Float
	MGSELECTIONTAG_FIELDDEFORM			= 1007,		// Bool

	MGSELECTIONTAG_DUMMY__
};
#endif // TMGSELECTION_H__
