#ifndef TMOGRAPH_CACHE_H__
#define TMOGRAPH_CACHE_H__

enum
{
	MGCACHETAG_GROUP_PLAYBACK				= 900,		// GROUP
	MGCACHETAG_GROUP_BUILD					= 901,		// GROUP

	MGCACHETAG_MODE_INTERNAL				= 0,
	MGCACHETAG_MODE_EXTERNAL				= 1,

	MGCACHETAG_BAKESEQUENCE					= 1000,		// BUTTON
	MGCACHETAG_BAKEFRAME						= 1001,		// BUTTON
	MGCACHETAG_CLEARFRAME						= 1002,		// BUTTON
	MGCACHETAG_CLEARCACHE						= 1003,		// BUTTON
	MGCACHETAG_BAKEFROM							= 1004,		// TIME
	MGCACHETAG_BAKETO								= 1005,		// TIME
	MGCACHETAG_BAKESEQUENCE_ACTIVE	= 1006,		// BOOL
	MGCACHETAG_MEMORYUSED						= 1007,		// STATICTEXT
	MGCACHETAG_ACTIVE								= 1008,		// BOOL
	MGCACHETAG_OFFSET								= 1009,		// TIME
	MGCACHETAG_LOOP									= 1010,		// BOOL
	MGCACHETAG_LOOP_BLEND						= 1011,		// FLOAT
	MGCACHETAG_STRENGTH							= 1012,		// FLOAT
	MGCACHETAG_CACHE_EXPORT					= 1013,		// BUTTON
	MGCACHETAG_ACTIVE_CACHEFILE			= 1014,		// FILENAME HIDDEN
	MGCACHETAG_CACHE_ISSEQUENCE			= 1017,		// BOOL HIDDEN
	MGCACHETAG_LOOPSTART						= 1018,		// INT HIDDEN
	MGCACHETAG_LOOPEND							= 1019,		// INT HIDDEN
	MGCACHETAG_EXPORT_CACHEFILE			= 1020,		// FILENAME
	MGCACHETAG_CACHE_IMPORT					= 1021,		// BUTTON
	MGCACHETAG_EXPORT_TOKENS				= 1022,		// POPUP
	MGCACHETAG_MODE									= 1023,		// INT CYCLE
	MGCACHETAG_BAKETOEXTERNAL				= 1024,		// BUTTON
	MGCACHETAG_IMPORT_CACHEFILE			= 1025,		// FILENAME
	MGCACHETAG_IMPORT_TOKENS				= 1026		// POPUP

};
#endif // TMOGRAPH_CACHE_H__
