#ifndef TOOLFITCIRCLE_H__
#define TOOLFITCIRCLE_H__

enum
{
	MDATA_FITCIRCLE_PROJECTREGULAR      = 1100, //BOOL
	MDATA_FITCIRCLE_PROJECTTOSURFACE    = 1101, //BOOL
	MDATA_FITCIRCLE_ANGLE               = 1102, //REAL
	MDATA_FITCIRCLE_ABSOLUTERADIUS      = 1103, //BOOL
	MDATA_FITCIRCLE_SCALE               = 1104, //REAL
	MDATA_FITCIRCLE_RADIUS              = 1105, //REAL
	MDATA_FITCIRCLE_WEIGHT              = 1106, //REAL
	MDATA_FITCIRCLE_SELECTOUTLINE       = 1107, //BOOL
	MDATA_FITCIRCLE_ROUNDNESS           = 1108, //REAL
	MDATA_FITCIRCLE_ADJUSTINNERPOINTS   = 1109, //BOOL
    MDATA_FITCIRCLE_
};

#endif // TOOLFITCIRCLE_H__
