#ifndef TOOLMEASURE_H__
#define TOOLMEASURE_H__

enum
{
	MDATA_MEASURE_SELECTION			= 1000,
	MDATA_MEASURE_3RD_POINT,
	MDATA_MEASURE_DIST1,
	MDATA_MEASURE_DIST2,
	MDATA_MEASURE_ANGLE,
	MDATA_MEASURE_DELETE,
	MDATA_MEASURE_NEW,
	MDATA_MEASURE_SHOWDIST1,
	MDATA_MEASURE_SHOWDIST2,
	MDATA_MEASURE_SHOWANGLE,
	MDATA_MEASURE_COLORP,
	MDATA_MEASURE_COLOR1,
	MDATA_MEASURE_COLOR2,
	MDATA_MEASURE_CREATEOBJECT,
	MDATA_MEASURE_DIR1,
	MDATA_MEASURE_DIR2,
	MDATA_MEASURE_UPVECTOR,
	MDATA_MEASURE_ROTMATRIX,
	MDATA_MEASURE_FIXROT,
	MDATA_MEASURE_VISIBLE,

	MDATA_MEASURE_PNT1_LINK			= 2000,
	MDATA_MEASURE_PNT1_MODE,
	MDATA_MEASURE_PNT1_IDX,
	MDATA_MEASURE_PNT1_VECTOR,

	MDATA_MEASURE_PNT2_LINK			= 2100,
	MDATA_MEASURE_PNT2_MODE,
	MDATA_MEASURE_PNT2_IDX,
	MDATA_MEASURE_PNT2_VECTOR,

	MDATA_MEASURE_PNT3_LINK			= 2200,
	MDATA_MEASURE_PNT3_MODE,
	MDATA_MEASURE_PNT3_IDX,
	MDATA_MEASURE_PNT3_VECTOR,

		MDATA_MEASURE_PNT_MODE_FREE 	= 0,
		MDATA_MEASURE_PNT_MODE_POINT	= 1,
		MDATA_MEASURE_PNT_MODE_EDGE		= 2,
		MDATA_MEASURE_PNT_MODE_POLY		= 3,

	MDATA_MEASUREGROUP_COLORS		= 3000,
	MDATA_MEASUREGROUP_P1,
	MDATA_MEASUREGROUP_P2,
	MDATA_MEASUREGROUP_P3,

	MDATA_MEASURE_
};

#endif // TOOLMEASURE_H__
