#ifndef TOOLATTRIBUTETRANSFER_H__
#define TOOLATTRIBUTETRANSFER_H__

enum
{
	MDATA_ATTRIBUTETRANSFER_SOURCEOBJIDX = 1000,           // LONG
	MDATA_ATTRIBUTETRANSFER_TARGETOBJIDX = 1001,           // LONG
	MDATA_ATTRIBUTETRANSFER_TRANSFORM = 1002,              // LONG
		MDATA_ATTRIBUTETRANSFER_TRANSFORM_OFF = 0,
		MDATA_ATTRIBUTETRANSFER_TRANSFORM_FLIP_X = 1,
		MDATA_ATTRIBUTETRANSFER_TRANSFORM_FLIP_Y = 2,
		MDATA_ATTRIBUTETRANSFER_TRANSFORM_FLIP_Z = 4,
	MDATA_ATTRIBUTETRANSFER_SPACE = 1003,                  // LONG
		MDATA_ATTRIBUTETRANSFER_SPACE_LOCAL = 10,
		MDATA_ATTRIBUTETRANSFER_SPACE_GLOBAL = 11,
	
	MDATA_ATTRIBUTETRANSFER_TYPE_WEIGHTS = 10000,           // BOOL
	MDATA_ATTRIBUTETRANSFER_TYPE_TEXTURE = 10001,           // BOOL
	MDATA_ATTRIBUTETRANSFER_TYPE_POSEMORPH = 10002,         // BOOL
	MDATA_ATTRIBUTETRANSFER_TYPE_EDGESELECTION = 10003,     // BOOL
	MDATA_ATTRIBUTETRANSFER_TYPE_POINTSELECTION = 10004,    // BOOL
	MDATA_ATTRIBUTETRANSFER_TYPE_POLYGONSELECTION = 10005,  // BOOL
	MDATA_ATTRIBUTETRANSFER_TYPE_UVW = 10006,               // BOOL
	MDATA_ATTRIBUTETRANSFER_TYPE_VERTEXMAP = 10007,         // BOOL
	MDATA_ATTRIBUTETRANSFER_TYPE_NORMAL = 10008,            // BOOL
	MDATA_ATTRIBUTETRANSFER_TYPE_VERTEXCOLOR = 10009        // BOOL
};

#endif // TOOLATTRIBUTETRANSFER_H__
