#ifndef TOOLSPLINEPEN_H__
#define TOOLSPLINEPEN_H__

enum
{
	MDATA_SPLINEPEN_MODE					 = 1100,	// INTEGER
	MDATA_SPLINEPEN_MODE_LINEAR		 = 0,
	MDATA_SPLINEPEN_MODE_CUBIC		 = 1,
	MDATA_SPLINEPEN_MODE_AKIMA		 = 2,
	MDATA_SPLINEPEN_MODE_BSPLINE	 = 3,
	MDATA_SPLINEPEN_MODE_BEZIER		 = 4,
	MDATA_SPLINEPEN_TANGENT_MODE	 = 1101,	// BOOLEAN
	MDATA_SPLINEPEN_LOCK_ROTATION	 = 1102,	// BOOLEAN
	MDATA_SPLINEPEN_LOCK_SCALE		 = 1103,	// BOOLEAN
	MDATA_SPLINEPEN_CREATE_SPLINES = 1104,	// BOOLEAN
	MDATA_SPLINEPEN_NEW_SPLINE		 = 1105		// BUTTON
};

#endif	// TOOLSPLINEPEN_H__
