#ifndef TOOLSCULPTBRUSHWAX_H__
#define TOOLSCULPTBRUSHWAX_H__

enum
{
	ToolSculptBrushWax_Start = 20000,

	MDATA_SCULPTBRUSH_WAXMODE,
		MDATA_SCULPTBRUSH_WAXMODE_A,
		MDATA_SCULPTBRUSH_WAXMODE_B,
		MDATA_SCULPTBRUSH_WAXMODE_C,
};

#endif // TOOLSCULPTBRUSHWAX_H__
