#ifndef TOOLSETVALUE_H__
#define TOOLSETVALUE_H__

enum
{
	MDATA_SETVALUE_SETX												= 2008, // BOOL
	MDATA_SETVALUE_SETY												= 2009, // BOOL
	MDATA_SETVALUE_SETZ												= 2010, // BOOL
		MDATA_SETVALUE_SET_LEAVE									= 0,
		MDATA_SETVALUE_SET_SET										= 1,
		MDATA_SETVALUE_SET_CENTER									= 2,
		MDATA_SETVALUE_SET_QUANTIZE								= 3,
		MDATA_SETVALUE_CRUMPLE_ALONGNORMALS				= 4,
		MDATA_SETVALUE_CRUMPLE_AXIAL							= 5,
		MDATA_SETVALUE_CRUMPLE_RADIAL							= 6,

	MDATA_SETVALUE_VAL												= 2011, // VECTOR
	MDATA_SETVALUE_SYSTEM											= 2012, // LONG
		MDATA_SETVALUE_SYSTEM_OBJECT							= 0,
		MDATA_SETVALUE_SYSTEM_WORLD								= 1,
		MDATA_SETVALUE_SYSTEM_SCREEN							= 2,
	TEMP_MDATA_SETVALUE_VAL_X									= 2013, // REAL
	TEMP_MDATA_SETVALUE_VAL_Y									= 2014, // REAL
	TEMP_MDATA_SETVALUE_VAL_Z									= 2015, // REAL
	TEMP_MDATA_SETVALUE_SETALL								= 2007, // BOOL - only for user interface!

	MDATA_SETVALUE_INOUT											= 2018,	// BOOL
	MDATA_SETVALUE_SEED												= 2019, // LONG

	MDATA_SETVALUE_
};

#endif // TOOLSETVALUE_H__
