#ifndef TOOLFILLSELECTION_H__
#define TOOLFILLSELECTION_H__

enum
{
	MDATA_FILL_POLYGON_INDEX							= 1100, // LONG
	MDATA_FILL_SELECTION_TYPE							= 1110, // LONG (must be SELECTION_NEW, SELECTION_ADD or SELECTION_SUB)
	MDATA_FILL_SEL_POLYGON_OBJECT					= 1120, // LINK
};

#endif // TOOLFILLSELECTION_H__
