#ifndef TPBDCONSTRAINT_H__
#define TPBDCONSTRAINT_H__

enum
{
	PBD_CONSTRAINT_TAG_RADIUS = 5000,
	PBD_CONSTRAINT_TAG_SAME_OBJECT = 5001,
	PBD_CONSTRAINT_TAG_OTHER_OBJECTS = 5002,
	PBD_CONSTRAINT_TAG_GENERATE_LIVE = 5003,
	PBD_CONSTRAINT_TAG_CREATE = 5004,
	PBD_CONSTRAINT_TAG_CLEAR = 5005,
	PBD_CONSTRAINT_TAG_CREATEGROUP = 5006,
	PBD_CONSTRAINT_TAG_SETTINGS = 5007,
	PBD_CONSTRAINT_TAG_STRETCHINESS = 5008,
	PBD_CONSTRAINT_TAG_TARGETLENGTH = 5009,
	PBD_CONSTRAINT_TAG_TEAR = 5010,
	PBD_CONSTRAINT_TAG_TEARPAST = 5011,
	PBD_CONSTRAINT_TAG_ALWAYSDRAW = 5012,
	PBD_CONSTRAINT_TAG_EXCLUDE_OBJECTS = 5013,
	PBD_CONSTRAINT_TAG_POINTSELECTION = 5014,
	PBD_CONSTRAINT_TAG_MAXCONNECTIONS = 5015,
	PBD_CONSTRAINT_TAG_EXCLUSION_MODE	= 5016,
		PBD_CONSTRAINT_TAG_EXCLUSION_MODE_EXCLUDE = 0,
		PBD_CONSTRAINT_TAG_EXCLUSION_MODE_INCLUDE	= 1,
	PBD_CONSTRAINT_TAG_TEAR_MODE = 5017,
		PBD_CONSTRAINT_TAG_TEAR_MODE_RELATIVE = 0,
		PBD_CONSTRAINT_TAG_TEAR_MODE_ABSOLUTE = 1,
	PBD_CONSTRAINT_TAG_TEAR_ABSOLUTE_DISTANCE = 5018,
	//////////////////////////////////////////////////////////////////////////
	PBD_CONSTRAINT_TAG_DUMMY
};

#endif // TPBDCONSTRAINT_H__
