#ifndef TPOINTSELECTION_H__
#define TPOINTSELECTION_H__

enum
{
	POINTSELECTIONTAG_FIELDGROUP			= 2000,			// GROUP
	POINTSELECTIONTAG_FIELDS					= 2001,			// FIEDLIST
	POINTSELECTIONTAG_ENABLEFIELDS		= 2002,			// BOOL
	POINTSELECTIONTAG_FIELDTOLERANCE	= 2003,			// FLOAT
	POINTSELECTIONTAG_DEFORMEDSTATE		= 2004,			// BOOL
	POINTSELECTIONTAG_FIELDTAB = 2005,

	POINTSELECTIONTAG_COMMAND1 = 1000, // virtual ID
	POINTSELECTIONTAG_COMMAND2 = 1001,
	POINTSELECTIONTAG_COMMAND3 = 1002,
	POINTSELECTIONTAG_COMMAND4 = 1003,
	POINTSELECTIONTAG_COMMAND5 = 1004,
	POINTSELECTIONTAG_COMMAND6 = 1005,
	POINTSELECTIONTAG_COMMANDTAB= 1006,
	POINTSELECTIONTAG_UPDATE = 1007,
	POINTSELECTIONTAG_COUNT = 1008,
	POINTSELECTIONTAG_UNHIDEALL = 1009,
	POINTSELECTIONTAG_MODIFIERHINT = 1010
};

#endif // TPOINTSELECTION_H__
