#ifndef TSCULPTTAG_H__
#define TSCULPTTAG_H__

enum
{
	MDATA_SCULPTTAG_SHOWVERTEXCOLORS = 1005,
	MDATA_SCULPTTAG_MASK_COLOR = 1006,
	MDATA_SCULPTTAG_LAYERMANAGER = 1007,
	MDATA_SCULPTTAG_FREEZE = 1008,
	MDATA_SCULPTTAG_ALLOWDEFORM = 1009,
	MDATA_SCULPTTAG_SUBDIVIDE_UV = 1011,
		MDATA_SCULPTTAG_SUBDIVIDE_UV_STANDARD = 2001,
		MDATA_SCULPTTAG_SUBDIVIDE_UV_BOUNDARY = 2002,
		MDATA_SCULPTTAG_SUBDIVIDE_UV_EDGE     = 2003,
};

#endif // TSCULPTTAG_H__



