#ifndef TSUNEXPRESSION_H__
#define TSUNEXPRESSION_H__

enum
{
	SUNEXPRESSIONTAG_LATITUDE														= 1000,
	SUNEXPRESSIONTAG_DISTANCE														= 1003,
	SUNEXPRESSIONTAG_DATETIME														= 1004,
	SUNEXPRESSIONTAG_LONGITUDE													= 1005,
	SUNEXPRESSIONTAG_INTERPOLATE_TIME 									= 1006,
	SUNEXPRESSIONTAG_INTERPOLATE_DATE 									= 1007,
	SUNEXPRESSIONTAG_SETLIGHTCOLOR											= 1008,
	SUNEXPRESSIONTAG_POS_CITY_COMBO											= 1009,
	SUNEXPRESSIONTAG_POS_CITY                         	= 1010, // hidden string
	SUNEXPRESSIONTAG_POS_CONTINENT                    	= 1011, // hidden string
	SUNEXPRESSIONTAG_POS_COUNTRY                      	= 1012, // hidden string
	SUNEXPRESSIONTAG_POS_TIME_ZONE                    	= 1013, // real
	SUNEXPRESSIONTAG_POS_DST_TIME_ZONE                	= 1014, // real
	SUNEXPRESSIONTAG_POS_TIMEZONE                     	= 1015, // long
		SUNEXPRESSIONTAG_POS_TZ_OS                      	= 0,
		SUNEXPRESSIONTAG_POS_TZ_CUSTOM                  	= 1,
	SUNEXPRESSIONTAG_POS_DST_SETTINGS                 	= 1016, // long
		SUNEXPRESSIONTAG_POS_DST_LAST_MARCH_LAST_OCT    	= 0,
		SUNEXPRESSIONTAG_POS_DST_FIRST_APR_LAST_OCT     	= 1,
		SUNEXPRESSIONTAG_POS_DST_FIRST_OCT_LAST_MARCH   	= 2,
		SUNEXPRESSIONTAG_POS_DST_LAST_OCT_LAST_MARCH    	= 3,
		SUNEXPRESSIONTAG_POS_DST_SECOND_MARCH_FIRST_NOV 	= 4,
		SUNEXPRESSIONTAG_POS_DST_OFF                    	= 99,
	SUNEXPRESSIONTAG_TIME_NOW			                    	= 1017, // bool
	SUNEXPRESSIONTAG_DATE_TODAY		                    	= 1018, // bool
};

#endif // TSUNEXPRESSION_H__
