#ifndef TVERTEXCOLOR_H__
#define TVERTEXCOLOR_H__

enum
{
	ID_VERTEXCOLORFIELDSGROUP									= 1010,

	ID_VERTEXCOLOR_VERTEXCOLORMODE						= 1001,
		ID_VERTEXCOLOR_VERTEXCOLORMODE_VERTEX			= 0,
		ID_VERTEXCOLOR_VERTEXCOLORMODE_POLYGON		= 1,
	ID_VERTEXCOLOR_ALPHAMODE									= 1000,
	ID_VERTEXCOLOR_DRAWPOINTS									= 1038979,
	ID_VERTEXCOLOR_USEFIELDS									= 1002,
	ID_VERTEXCOLOR_FIELDS											=	1003,
	ID_VERTEXCOLOR_USEDEFORMEDPOINTS					=	1004,

	__ID_DUMMY_VERTEXCOLOR
};

#endif // TVERTEXCOLOR_H__

