#ifndef VPCOLORMAPPING_H__
#define VPCOLORMAPPING_H__

enum
{
	COLORMAPPING_EXPONENTIAL			= 1000,
	COLORMAPPING_HSV							= 1001,
	COLORMAPPING_DARKMULTIPLIER		= 1002,
	COLORMAPPING_BRIGHTMULTIPLIER	= 1003,
	COLORMAPPING_BACKGROUND				= 1004
};

#endif // VPCOLORMAPPING_H__
