#ifndef VPMAGICBULLETLOOKS_H__
#define VPMAGICBULLETLOOKS_H__

enum
{
	VP_MAGICBULLETLOOKS_LOOKSBUILDER				= 10000,		// BUTTON
	VP_MAGICBULLETLOOKS_LOOKNAME						= 10001,		// STATICTEXT
	VP_MAGICBULLETLOOKS_PREVIEWBEFORE				= 10002,		// BITMAPBUTTON - not used
	VP_MAGICBULLETLOOKS_PREVIEWAFTER				= 10003,		// BITMAPBUTTON
	VP_MAGICBULLETLOOKS_STRENGTH						= 10004,		// SLIDER
	VP_MAGICBULLETLOOKS_BAKED								= 10005,		// BOOL - not used
	VP_MAGICBULLETLOOKS_CLEARLOOK						= 10006,		// BUTTON - not used
	VP_MAGICBULLETLOOKS_SESSIONICON					= 10007,		// BITMAPBUTTON  - not used
	VP_MAGICBULLETLOOKS_GETVIEWPORTIMAGE		= 10008,		// BUTTON  - not used
	VP_MAGICBULLETLOOKS_SAVEPREVIEW					= 10009			// BOOL
};

#endif // VPMAGICBULLETLOOKS_H__
