#ifndef XAMBIENTOCCLUSION_H__
#define XAMBIENTOCCLUSION_H__

enum
{
	AMBIENTOCCLUSIONSHADER_MINLENGTH		= 1002,
	AMBIENTOCCLUSIONSHADER_MAXLENGTH		= 1003,
	AMBIENTOCCLUSIONSHADER_DISPERSION		= 1004,
	AMBIENTOCCLUSIONSHADER_MINSAMPLES		= 1005,
	AMBIENTOCCLUSIONSHADER_MAXSAMPLES		= 1006,
	AMBIENTOCCLUSIONSHADER_CONTRAST			= 1007,
	AMBIENTOCCLUSIONSHADER_ENVIRONMENT	= 1008,
	AMBIENTOCCLUSIONSHADER_ACCURACY			= 1009,
	AMBIENTOCCLUSIONSHADER_GRADIENT     = 1010,
	AMBIENTOCCLUSIONSHADER_TRANSPARENCY = 1011,
	AMBIENTOCCLUSIONSHADER_SELFTEST     = 1012,
	AMBIENTOCCLUSIONSHADER_REVERSE			= 1014,
};

#endif // XAMBIENTOCCLUSION_H__
