#ifndef XCYCLONE_H__
#define XCYCLONE_H__

enum
{
	CYCLONESHADER_FREQUENCY	= 1002,	// REAL
	CYCLONESHADER_ROTATION	= 1003, // REAL
	CYCLONESHADER_LEVEL			= 1004,	// REAL
	CYCLONESHADER_COLOR			= 1005  // GRADIENT
};

#endif // XCYCLONE_H__
