#ifndef XXMBSUBSURFACE_H__
#define XXMBSUBSURFACE_H__

enum
{
	//XMBSUBSURFACESHADER_POINTS 					= 9000, Legacy
	//XMBSUBSURFACESHADER_STEPS 					= 9001, Legacy
	XMBSUBSURFACESHADER_DEBUG_PREVIEW 				= 9002,
	XMBSUBSURFACESHADER_CACHE_ERROR 				= 9003,

	XMBSUBSURFACESHADER_STRENGTH 					= 9005,
	//XMBSUBSURFACESHADER_AUTO					= 9006,	Legacy
	XMBSUBSURFACESHADER_CACHE_SAMPLE_DENSITY			= 9007,
	XMBSUBSURFACESHADER_CACHE_SMOOTHING				= 9008,

	XMBSUBSURFACESHADER_DEBUG_SHOW_POINTS 				= 9010,
	XMBSUBSURFACESHADER_DEBUG_SHOW_COLOR 				= 9011,
	//XMBSUBSURFACESHADER_ACCURATE 					= 9012, Legacy

	XMBSUBSURFACESHADER_DIFFUSE 					= 9120,
	XMBSUBSURFACESHADER_SHADER					= 9121,
	XMBSUBSURFACESHADER_IOR 					= 9130,
	XMBSUBSURFACESHADER_FRESNEL					= 9132,
	XMBSUBSURFACESHADER_DITHER					= 9134,
	XMBSUBSURFACESHADER_CACHE_INTERPOLATION				= 9135,

	XMBSUBSURFACESHADER_LENGTH_R 					= 9140,
	XMBSUBSURFACESHADER_LENGTH_G 					= 9141,
	XMBSUBSURFACESHADER_LENGTH_B 					= 9142,
	XMBSUBSURFACESHADER_LENGTH 					= 9143,

	XMBSUBSURFACESHADER_MULTIPLE_ENABLED				= 9150,
	XMBSUBSURFACESHADER_MULTIPLE_MODE				= 9151,
		XMBSUBSURFACESHADER_MULTIPLE_MODE_CACHE			= 0,
		XMBSUBSURFACESHADER_MULTIPLE_MODE_DIRECT		= 1,
	XMBSUBSURFACESHADER_MULTIPLE_CUSTOM_ENABLED			= 9052,
	XMBSUBSURFACESHADER_MULTIPLE_CUSTOM_SAMPLING			= 9053,

	XMBSUBSURFACESHADER_DIRECT_RATIO				= 9160,
	//XMBSUBSURFACESHADER_DIRECT_ENABLED				= 9161, Legacy
	XMBSUBSURFACESHADER_DIRECT_SPLIT				= 9162,

	XMBSUBSURFACESHADER_SINGLE_ENABLED				= 9170,
	XMBSUBSURFACESHADER_SINGLE_TRACE				= 9171,
	XMBSUBSURFACESHADER_SINGLE_PHASE				= 9172,
	XMBSUBSURFACESHADER_SINGLE_SPLIT				= 9174,

	XMBSUBSURFACESHADER_SINGLE_CUSTOM_ENABLED			= 9175,
	XMBSUBSURFACESHADER_SINGLE_CUSTOM_SAMPLING			= 9173,

	XMBSUBSURFACESHADER_PRESET					= 9200,
		XMBSUBSURFACESHADER_PRESET_CUSTOM			= 0,
		XMBSUBSURFACESHADER_PRESET_APPLE			= 1,
		XMBSUBSURFACESHADER_PRESET_CHICKEN			= 2,
		XMBSUBSURFACESHADER_PRESET_CREAM			= 3,
		XMBSUBSURFACESHADER_PRESET_KETCHUP			= 4,
		XMBSUBSURFACESHADER_PRESET_MARBLE			= 5,
		XMBSUBSURFACESHADER_PRESET_MILK_SKIM			= 6,
		XMBSUBSURFACESHADER_PRESET_MILK_WHOLE			= 7,
		XMBSUBSURFACESHADER_PRESET_POTATO			= 8,
		XMBSUBSURFACESHADER_PRESET_SKIN_DARK			= 9,
		XMBSUBSURFACESHADER_PRESET_SKIN_LIGHT			= 10,
		XMBSUBSURFACESHADER_PRESET_SPECTRALON			= 11,

	XMBSUBSURFACESHADER_LIGHTS					= 9300,
	XMBSUBSURFACESHADER_LIGHTS_MODE					= 9301,
		XMBSUBSURFACESHADER_LIGHTS_MODE_INCLUDE			= 0,
		XMBSUBSURFACESHADER_LIGHTS_MODE_EXCLUDE			= 1,
	XMBSUBSURFACESHADER_LIGHTS_GI					= 9302,

	XMBSUBSURFACESHADER_GROUP_MAIN					= 9400,
	XMBSUBSURFACESHADER_GROUP_ADVANCED				= 9401,
	XMBSUBSURFACESHADER_GROUP_DEBUG					= 9402,
	XMBSUBSURFACESHADER_GROUP_LIGHTS				= 9403,
	XMBSUBSURFACESHADER_GROUP_MULTIPLE				= 9404,
	XMBSUBSURFACESHADER_GROUP_SINGLE				= 9405,
};

#endif // XXMBSUBSURFACE_H__
