CONTAINER OMMDModelManager {
	NAME OMMDModelManager;
	INCLUDE Obase;

	GROUP MODEL_INFO_GRP {
		DEFAULT 1;

		REAL PMX_VERSION {
			ANIM OFF;
			UNIT REAL;
			MIN 2.0;
			STEP 0.1;
			MAX 2.1;
		}

		STRING MODEL_NAME_LOCAL {
			ANIM OFF;
		}

		STRING MODEL_NAME_UNIVERSAL {
			ANIM OFF;
		}

		STRING COMMENTS_LOCAL {
			ANIM OFF;
			CUSTOMGUI MULTISTRING;
			SCALE_H;
			SCALE_V;
		}

		STRING COMMENTS_UNIVERSAL {
			ANIM OFF;
			CUSTOMGUI MULTISTRING;
			SCALE_H;
			SCALE_V;
		}

		LONG MODEL_MODE {
			CUSTOMGUI QUICKTABRADIO;
			ANIM OFF;
			FIT_H;
			SCALE_H;

			CYCLE {
				MODEL_MODE_EDIT;
				MODEL_MODE_ANIM;
				MODEL_MODE_VMD;
			}
		}
	}

	GROUP MODEL_ANIM_GRP {
		DEFAULT 1;
		COLUMNS 2;

		LONG MODEL_ANIM_LIST {
			ANIM OFF;
			SCALE_H;
			CYCLE {
				MODEL_ANIM_NONE;
			}
		}

		BUTTON MODEL_ANIM_DElETE_BUTTON {
			FIT_H;
			SCALE_H;
		}

		BUTTON MODEL_ANIM_LOAD_VMD_BUTTON {
			FIT_H;
			SCALE_H;
		}

		BUTTON MODEL_ANIM_MERGE_VMD_BUTTON {
			FIT_H;
			SCALE_H;
		}
	}

	GROUP MODEL_MATERIAL_GRP {
		DEFAULT 0;

			GROUP {
				COLUMNS 5;

				LONG MODEL_MATERIAL_LIST {
					ANIM OFF;
					SCALE_H;
					CYCLE {
						MODEL_MATERIAL_NONE;
					}
				}

				BUTTON MODEL_MATERIAL_MOVE_UP_BUTTON {
					FIT_H;
				}

				BUTTON MODEL_MATERIAL_MOVE_DOWN_BUTTON {
					FIT_H;
				}

				BUTTON MODEL_MATERIAL_DELETE_BUTTON {
					FIT_H;
				}

				BUTTON MODEL_MATERIAL_ADD_BUTTON {
					FIT_H;
				}
			}
		

		GROUP
		{
			DEFAULT 1;
			COLUMNS 2;

			STATICTEXT MODEL_MATERIAL_FACE_COUNT_TEXT {
				ANIM OFF;
			}

			STATICTEXT MODEL_MATERIAL_FACE_COUNT {
				ANIM OFF;
			}

		}
		
		STRING MODEL_MATERIAL_NAME_LOCAL {
			ANIM OFF;
		}

		STRING MODEL_MATERIAL_NAME_UNIVERSAL {
			ANIM OFF;
		}

		LINK MODEL_MATERIAL_MESH_LINK {
			ANIM OFF;
			ACCEPT { Obase; }
		}

		STRING MODEL_MATERIAL_SELECTION {
			ANIM OFF;
		}

		GROUP MODEL_MATERIAL_C4D_GRP 
		{
			LINK MODEL_MATERIAL_LINK {
				ANIM OFF;
				ACCEPT { Mbase; }
			}

			LONG MODEL_MATERIAL_CREATE_TYPE {
				ANIM OFF;
				CYCLE {
					MODEL_MATERIAL_CREATE_TYPE_STANDARD;
					MODEL_MATERIAL_CREATE_TYPE_REDSHIFT;
					MODEL_MATERIAL_CREATE_TYPE_OCTANE;
					MODEL_MATERIAL_CREATE_TYPE_CORONA;
				}
			}

			BUTTON MODEL_MATERIAL_CREATE_BUTTON {
				FIT_H;
				SCALE_H;
			}

			BUTTON MODEL_MATERIAL_SYNC_BUTTON {
				FIT_H;
				SCALE_H;
			}

			BUTTON MODEL_MATERIAL_REVERSE_SYNC_BUTTON {
				FIT_H;
				SCALE_H;
			}
		}

		GROUP MODEL_MATERIAL_COLOR_GRP {
			DEFAULT 1;
			COLUMNS 2;

			COLOR MODEL_MATERIAL_DIFFUSE_COLOR {
				ANIM OFF;
			}

			REAL MODEL_MATERIAL_DIFFUSE_ALPHA {
				ANIM OFF;
				MIN 0.0;
				MAX 1.0;
			}

			COLOR MODEL_MATERIAL_SPECULAR_COLOR {
				ANIM OFF;
			}

			REAL MODEL_MATERIAL_SPECULAR_POWER {
				ANIM OFF;
				MIN 0.0;
			}

			COLOR MODEL_MATERIAL_AMBIENT_COLOR {
				ANIM OFF;
			}
		}

		GROUP MODEL_MATERIAL_DRAW_GRP {
			DEFAULT 0;
			COLUMNS 2;

			BOOL MODEL_MATERIAL_DRAW_BOTH_FACE {
				ANIM OFF;
			}

			BOOL MODEL_MATERIAL_DRAW_GROUND_SHADOW {
				ANIM OFF;
			}

			BOOL MODEL_MATERIAL_DRAW_CAST_SELF_SHADOW {
				ANIM OFF;
			}

			BOOL MODEL_MATERIAL_DRAW_RECEIVE_SELF_SHADOW {
				ANIM OFF;
			}

			BOOL MODEL_MATERIAL_DRAW_VERTEX_COLOR {
				ANIM OFF;
			}
		}

		GROUP MODEL_MATERIAL_EDGE_GRP {
			DEFAULT 0;
			COLUMNS 2;

			BOOL MODEL_MATERIAL_EDGE_ENABLED {
				ANIM OFF;
			}

			REAL MODEL_MATERIAL_EDGE_SIZE {
				ANIM OFF;
				MIN 0.0;
			}

			COLOR MODEL_MATERIAL_EDGE_COLOR {
				ANIM OFF;
			}

			REAL MODEL_MATERIAL_EDGE_ALPHA {
				ANIM OFF;
				MIN 0.0;
				MAX 1.0;
			}
		}

		GROUP MODEL_MATERIAL_TEXTURE_GRP {
			DEFAULT 0;

			TEXTURE MODEL_MATERIAL_TEXTURE_PATH {
				ANIM OFF;
			}

			GROUP{		
				COLUMNS 2;	

				LONG MODEL_MATERIAL_SPHERE_MODE {
					ANIM OFF;
					CYCLE {
						MODEL_MATERIAL_SPHERE_MODE_NONE;
						MODEL_MATERIAL_SPHERE_MODE_MUL;
						MODEL_MATERIAL_SPHERE_MODE_ADD;
						MODEL_MATERIAL_SPHERE_MODE_SUBTEX;
					}
				}

				TEXTURE MODEL_MATERIAL_SPHERE_TEXTURE_PATH {
					ANIM OFF;
				}
			}

			GROUP{
				COLUMNS 2;
				LONG MODEL_MATERIAL_TOON_MODE {
					ANIM OFF;
					CYCLE {
						MODEL_MATERIAL_TOON_MODE_SEPARATE;
						MODEL_MATERIAL_TOON_MODE_COMMON;
					}
				}

				LONG MODEL_MATERIAL_TOON_TEXTURE_INDEX {
					ANIM OFF;
					CYCLE {
						MODEL_MATERIAL_TOON_01;
						MODEL_MATERIAL_TOON_02;
						MODEL_MATERIAL_TOON_03;
						MODEL_MATERIAL_TOON_04;
						MODEL_MATERIAL_TOON_05;
						MODEL_MATERIAL_TOON_06;
						MODEL_MATERIAL_TOON_07;
						MODEL_MATERIAL_TOON_08;
						MODEL_MATERIAL_TOON_09;
						MODEL_MATERIAL_TOON_10;
					}
				}
			}
			TEXTURE MODEL_MATERIAL_TOON_TEXTURE_PATH {
				ANIM OFF;
			}
		}

		STRING MODEL_MATERIAL_MEMO {
			ANIM OFF;
			CUSTOMGUI MULTISTRING;
			SCALE_H;
			SCALE_V;
		}
	}

	GROUP MODEL_MORPH_GRP {
		GROUP MODEL_MORPH_GROUP_GRP {
			STRING MODEL_MORPH_GROUP_ADD_NAME {
				FIT_H;
				SCALE_H;
				ANIM OFF;
			}

			BUTTON MODEL_MORPH_GROUP_ADD_BUTTON {
				FIT_H;
				SCALE_H;
			}
		}

		GROUP MODEL_MORPH_FLIP_GRP {
			STRING MODEL_MORPH_FLIP_ADD_NAME {
				FIT_H;
				SCALE_H;
				ANIM OFF;
			}

			BUTTON MODEL_MORPH_FLIP_ADD_BUTTON {
				FIT_H;
				SCALE_H;
			}
		}

		GROUP MODEL_MORPH_MESH_GRP {
		}

		GROUP MODEL_MORPH_UV_GRP {
		}

		GROUP MODEL_MORPH_BONE_GRP {
		}

		GROUP MODEL_MORPH_MATERIAL_GRP {
			STRING MODEL_MORPH_MATERIAL_ADD_NAME {
				FIT_H;
				SCALE_H;
				ANIM OFF;
			}

			BUTTON MODEL_MORPH_MATERIAL_ADD_BUTTON {
				FIT_H;
				SCALE_H;
			}
		}

		GROUP MODEL_MORPH_IMPULSE_GRP {
			STRING MODEL_MORPH_IMPULSE_ADD_NAME {
				FIT_H;
				SCALE_H;
				ANIM OFF;
			}

			BUTTON MODEL_MORPH_IMPULSE_ADD_BUTTON {
				FIT_H;
				SCALE_H;
			}
		}
	}

	GROUP MODEL_DISPLAY_FRAME_GRP {
		DEFAULT 1;

		GROUP {
			COLUMNS 2;

			LONG MODEL_DISPLAY_FRAME_LIST {
				ANIM OFF;
				SCALE_H;
				CYCLE {
					MODEL_DISPLAY_FRAME_NONE;
				}
			}

			BUTTON MODEL_DISPLAY_FRAME_DELETE_BUTTON {
				FIT_H;
			}
		}
		GROUP {
			COLUMNS 2;

			STRING MODEL_DISPLAY_FRAME_NEW_NAME {
				FIT_H;
				SCALE_H;
				ANIM OFF;
			}

			BUTTON MODEL_DISPLAY_FRAME_NEW_BUTTON {
				FIT_H;
			}
		}

		STRING MODEL_DISPLAY_FRAME_NAME_LOCAL {
			ANIM OFF;
		}

		STRING MODEL_DISPLAY_FRAME_NAME_UNIVERSAL {
			ANIM OFF;
		}

		GROUP {
			COLUMNS 3;

			LONG MODEL_DISPLAY_FRAME_ADD_TYPE {
				ANIM OFF;
				FIT_H;
				CYCLE {
					MODEL_DISPLAY_FRAME_ADD_TYPE_BONE;
					MODEL_DISPLAY_FRAME_ADD_TYPE_MORPH;
				}
			}

			LONG MODEL_DISPLAY_FRAME_ADD_TARGET {
				ANIM OFF;
				SCALE_H;
				CYCLE {
				}
			}

			BUTTON MODEL_DISPLAY_FRAME_ADD_BUTTON {
				FIT_H;
			}
		}

		GROUP MODEL_DISPLAY_FRAME_ENTRIES_GRP {
		}
	}

	GROUP MODEL_IK_GRP {
	}
}
