#ifndef _PMX_MODEL_MANAGER_H_
#define _PMX_MODEL_MANAGER_H_
enum
{
	MODEL_INFO_GRP = 1000,
	MODEL_NAME_LOCAL,
	MODEL_NAME_UNIVERSAL,
	COMMENTS_LOCAL,
	COMMENTS_UNIVERSAL,
	MODEL_MODE,
	PMX_VERSION,
	MODEL_IK_GRP,
	MODEL_MORPH_GRP,
		MODEL_MORPH_GROUP_GRP,
			MODEL_MORPH_GROUP_ADD_NAME,
			MODEL_MORPH_GROUP_ADD_BUTTON,
		MODEL_MORPH_FLIP_GRP,
			MODEL_MORPH_FLIP_ADD_NAME,
			MODEL_MORPH_FLIP_ADD_BUTTON,
		MODEL_MORPH_MESH_GRP,
		MODEL_MORPH_BONE_GRP,
	MODEL_ANIM_GRP,
		MODEL_ANIM_LIST,
		MODEL_ANIM_LOAD_VMD_BUTTON,
		MODEL_ANIM_MERGE_VMD_BUTTON,
		MODEL_ANIM_DElETE_BUTTON,
	MODEL_ANIM_NONE = -1,
	MODEL_MODE_EDIT = 0,
	MODEL_MODE_ANIM,
	MODEL_MODE_VMD
};
#endif // _PMX_MODEL_MANAGER_H_
