#include "module/core/cmt_old_sdk_stl_preload.h"
#include "mmd_redshift_material.h"
#include <c4d_symbols.h>
#include "module/core/cmt_marco.h"
#include "mmd_material_morph_binding.h"
#include "mmd_redshift_sphere_graph.hpp"
#include "plugin_resource.h"
#include "maxon/uuid.h"
#include "utils/cmt_specular_conversion.hpp"
#include <vector>
#include <string>

#if API_VERSION >= 2024000
#include "maxon/graph.h"
#include "maxon/graph_helper.h"
#include "maxon/nodesgraph.h"
#include "maxon/node_undo.h"

namespace
{
	constexpr auto ID_REDSHIFT_MATERIAL = 1036224;
	constexpr maxon::LiteralId g_redshiftId("com.redshift3d.redshift4c4d.class.nodespace");
	const maxon::Id k_standardMaterialAssetId("com.redshift3d.redshift4c4d.nodes.core.standardmaterial");
	const maxon::Id k_textureSamplerAssetId("com.redshift3d.redshift4c4d.nodes.core.texturesampler");
	const maxon::Id k_colorSplitterAssetId("com.redshift3d.redshift4c4d.nodes.core.rscolorsplitter");
	// Stable IDs identify only nodes generated by this adapter. Runtime updates
	// never search for and repurpose an arbitrary artist-created texture sampler.
	const maxon::Id k_diffuseTextureNodeId("cmt_diffuse_texture");
	const maxon::Id k_opacitySplitterNodeId("cmt_opacity_splitter");
	const char* const k_morphNodeIds[] = {"cmt_morph_diffuse", "cmt_morph_opacity", "cmt_morph_specular", "cmt_morph_roughness",
		"cmt_morph_texture_scale", "cmt_morph_texture_bias", "cmt_morph_texture_add",
		nullptr, nullptr, nullptr, nullptr, nullptr, nullptr,
		"cmt_morph_sphere_scale", "cmt_morph_sphere_bias", "cmt_morph_sphere_add"};

	// Graph transactions do not cover classic object User Data or material
	// containers. Roll these back too if allocating or committing the graph fails.
	struct BindingRollback
	{
		BaseMaterial* material;
		BaseObject* mesh;
		BaseContainer previous;
		Bool attributes_created = false;
		Bool committed = false;
		~BindingRollback()
		{
			if (committed) return;
			if (attributes_created) mmd_material_binding::RemoveUserData(mesh, mmd_material_binding::Metadata(material));
			material->GetDataInstance()->SetContainer(g_mmd_material_texture_morph_shader_id, previous);
		}
	};
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.standardmaterial.base_color", rs_base_color);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.standardmaterial.opacity_color", rs_opacity_color);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.texturesampler.tex0", rs_tex0);
	MAXON_INTERNED_ID_LOCAL("path", rs_tex0_path);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.texturesampler.outcolor", rs_tex_outcolor);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.texturesampler.color_multiplier", rs_tex_color_multiplier);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.texturesampler.alpha_multiplier", rs_tex_alpha_multiplier);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.texturesampler.alpha_is_luminance", rs_tex_alpha_is_luminance);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rscolorsplitter.input", rs_split_input);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rscolorsplitter.outa", rs_split_outalpha);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.standardmaterial.refl_color", rs_specular);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.standardmaterial.refl_roughness", rs_roughness);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsuserdatacolor.attribute", rs_color_attribute);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsuserdatacolor.default", rs_color_default);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsuserdatacolor.out", rs_color_out);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsuserdatascalar.attribute", rs_scalar_attribute);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsuserdatascalar.default", rs_scalar_default);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsuserdatascalar.out", rs_scalar_out);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsmathaddvector.input1", rs_add_first);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsmathaddvector.input2", rs_add_second);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsmathaddvector.out", rs_add_out);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsmathsaturatevector.input", rs_saturate_input);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsmathsaturatevector.out", rs_saturate_out);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsmathmulvector.input1", rs_mul_first);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsmathmulvector.input2", rs_mul_second);
	MAXON_INTERNED_ID_LOCAL("com.redshift3d.redshift4c4d.nodes.core.rsmathmulvector.out", rs_mul_out);

	struct TextureMathNode { const char* id; const char* asset; Int32 operation; };
	const TextureMathNode k_textureMathNodes[] = {
		{"cmt_texture_bias", "rsmathaddvector", 3},
		{"cmt_texture_clamp", "rsmathsaturatevector", 19},
		{"cmt_texture_add", "rsmathaddvector", 3},
		{"cmt_texture_diffuse", "rsmathmulvector", 5}
	};

	static Bool IsRedShiftMaterial(const BaseMaterial* mat)
	{
		if (!mat)
			return false;
		if (mat->GetType() == ID_REDSHIFT_MATERIAL)
			return true;
		auto* node_mat = static_cast<NodeMaterial*>(const_cast<BaseMaterial*>(mat));
		return node_mat->HasSpace(g_redshiftId);
	}

	static maxon::Result<maxon::GraphNode> FindStandardMaterialNode(const maxon::nodes::NodesGraphModelRef& graph)
	{
		iferr_scope;
		maxon::GraphNode matNode;
		Bool found = false;
		maxon::GraphModelHelper::FindNodesByAssetId(
			graph, k_standardMaterialAssetId, true,
			[&matNode, &found](const maxon::GraphNode& node) -> maxon::Result<Bool>
			{
				matNode = node;
				found = true;
				return false;
			}) iferr_return;
		if (!found)
			return maxon::GraphNode();
		return matNode;
	}

	template<typename T>
	static maxon::Result<void> SetPortValue(const maxon::GraphNode& node, const maxon::InternedId& portId, const T& value)
	{
		iferr_scope;
		const auto inputs = node.GetInputs() iferr_return;
		const auto port = inputs.FindChild(portId) iferr_return;
		if (!port.IsValid())
			return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
		port.SetPortValue(value) iferr_return;
		return maxon::OK;
	}

	static maxon::Result<void> ConnectOutputToInput(
		const maxon::GraphNode& srcNode, const maxon::InternedId& outputPortId,
		const maxon::GraphNode& dstNode, const maxon::InternedId& inputPortId)
	{
		iferr_scope;
		const auto srcOutputs = srcNode.GetOutputs() iferr_return;
		const auto srcPort = srcOutputs.FindChild(outputPortId) iferr_return;
		const auto dstInputs = dstNode.GetInputs() iferr_return;
		const auto dstPort = dstInputs.FindChild(inputPortId) iferr_return;
		if (!srcPort.IsValid() || !dstPort.IsValid())
			return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
		srcPort.Connect(dstPort) iferr_return;
		return maxon::OK;
	}

	template<typename T>
	static maxon::Result<maxon::Opt<const T&>> GetPortValue(const maxon::GraphNode& node, const maxon::InternedId& portId)
	{
		iferr_scope;
		const auto inputs = node.GetInputs() iferr_return;
		const auto port = inputs.FindChild(portId) iferr_return;
		if (!port.IsValid())
			return maxon::Opt<const T&>();
		auto result = port.GetPortValue<T>() iferr_return;
		return result;
	}

	static maxon::Result<maxon::GraphNode> FindImportedTextureNode(const maxon::nodes::NodesGraphModelRef& graph)
	{
		iferr_scope;
		// An absolute root lookup also works while a graph editor views a group.
		const maxon::GraphNode root = graph.GetNode(maxon::NodePath());
		const auto child = root.FindChild(k_diffuseTextureNodeId) iferr_return;
		return child;
	}

	static maxon::Result<Bool> HasInputConnection(const maxon::GraphNode& node,
		const maxon::InternedId& port_id)
	{
		iferr_scope;
		const auto inputs = node.GetInputs() iferr_return;
		const auto port = inputs.FindChild(port_id) iferr_return;
		if (!port.IsValid())
			return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
		Bool connected = false;
		maxon::GraphModelHelper::GetDirectPredecessors(port, maxon::NODE_KIND::NODE,
			[&connected](const maxon::GraphNode&) -> maxon::Result<Bool>
			{
				connected = true;
				return false;
			}) iferr_return;
		return connected;
	}

	static maxon::Color64 ToNodeColor(const Vector& color)
	{
		return maxon::Color64(color.x, color.y, color.z);
	}

	static maxon::Result<maxon::GraphTransaction> BeginMaterialTransaction(const maxon::nodes::NodesGraphModelRef& graph)
	{
		iferr_scope;
		// Authoring records the complete material with UNDOTYPE::CHANGE before
		// entering this transaction. A second, automatic graph undo splits batch
		// upgrades and redo across materials. Construction/playback need no undo.
		maxon::DataDictionary settings;
		settings.Set(maxon::nodes::UndoMode, maxon::nodes::UNDO_MODE::NONE) iferr_return;
		return graph.BeginTransaction(settings);
	}

	static maxon::Result<void> SetTextureCoefficients(const maxon::GraphNode& texture,
		const Vector& diffuse_rgb, const Float diffuse_alpha)
	{
		iferr_scope;
		SetPortValue(texture, rs_tex_color_multiplier, ToNodeColor(diffuse_rgb)) iferr_return;
		SetPortValue(texture, rs_tex_alpha_multiplier, static_cast<Float64>(diffuse_alpha)) iferr_return;
		return maxon::OK;
	}

	static maxon::Result<void> SetPlainDiffuse(const maxon::GraphNode& material_node,
		const Vector& diffuse_rgb, const Float diffuse_alpha)
	{
		iferr_scope;
		SetPortValue(material_node, rs_base_color, ToNodeColor(diffuse_rgb)) iferr_return;
		const Float64 alpha = static_cast<Float64>(diffuse_alpha);
		SetPortValue(material_node, rs_opacity_color, maxon::Color64(alpha, alpha, alpha)) iferr_return;
		return maxon::OK;
	}

	static maxon::Result<void> SetSpecular(const maxon::GraphNode& material_node,
		const MMDMaterialData& data)
	{
		iferr_scope;
		SetPortValue(material_node, rs_specular, ToNodeColor(data.specular)) iferr_return;
		SetPortValue(material_node, rs_roughness,
			static_cast<Float64>(cmt_material::RoughnessFromSpecularPower(data.specular_power))) iferr_return;
		return maxon::OK;
	}

	static maxon::Result<void> CreateDiffuseTextureGraph(const maxon::nodes::NodesGraphModelRef& graph,
		const maxon::GraphNode& material_node, const MMDMaterialData& data, const Bool connect_surface = true)
	{
		iferr_scope;
		const maxon::GraphNode texture = graph.AddChild(k_diffuseTextureNodeId, k_textureSamplerAssetId) iferr_return;
		const auto tex_inputs = texture.GetInputs() iferr_return;
		const auto tex_bundle = tex_inputs.FindChild(rs_tex0) iferr_return;
		if (!tex_bundle.IsValid())
			return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
		const auto path = tex_bundle.FindChild(rs_tex0_path) iferr_return;
		if (!path.IsValid())
			return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
		path.SetPortValue(MaxonConvert(Filename(data.texture_path), MAXONCONVERTMODE::READ)) iferr_return;
		SetTextureCoefficients(texture, data.diffuse_rgb, data.diffuse_alpha) iferr_return;
		SetPortValue(texture, rs_tex_alpha_is_luminance, false) iferr_return;
		if (connect_surface)
		{
			ConnectOutputToInput(texture, rs_tex_outcolor, material_node, rs_base_color) iferr_return;
		}

		// Redshift's Texture Sampler has one RGBA outcolor port. Extract A before
		// converting it to the opacity color; connecting outcolor directly uses RGB
		// as an unintended transparency mask. A texture without alpha outputs 1,
		// so the same graph correctly applies diffuse alpha to opaque image files.
		const maxon::GraphNode splitter = graph.AddChild(k_opacitySplitterNodeId, k_colorSplitterAssetId) iferr_return;
		ConnectOutputToInput(texture, rs_tex_outcolor, splitter, rs_split_input) iferr_return;
		if (connect_surface)
		{
			ConnectOutputToInput(splitter, rs_split_outalpha, material_node, rs_opacity_color) iferr_return;
		}
		return maxon::OK;
	}
	// Build and validate the same edge list. This covers internal math connections
	// as well as surface inputs, so a hand-edited branch is never silently driven.
	struct BindingWire
	{
		maxon::GraphNode source;
		maxon::GraphNode destination;
		std::vector<maxon::GraphNode> replaceable;
	};

	static maxon::Result<maxon::GraphNode> Port(const maxon::GraphNode& node,
		const maxon::InternedId& id, const Bool output)
	{
		iferr_scope;
		if (!node.IsValid()) return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
		const auto ports = (output ? node.GetOutputs() : node.GetInputs()) iferr_return;
		const auto port = ports.FindChild(id) iferr_return;
		if (!port.IsValid()) return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
		return port;
	}

	static maxon::Result<std::vector<BindingWire>> BindingWires(const maxon::nodes::NodesGraphModelRef& graph,
		const maxon::GraphNode& surface, const Bool textured, const BaseContainer& metadata)
	{
		iferr_scope;
		const auto root = graph.GetNode(maxon::NodePath());
		const auto texture = root.FindChild(k_diffuseTextureNodeId) iferr_return;
		const auto splitter = root.FindChild(k_opacitySplitterNodeId) iferr_return;
		std::vector<BindingWire> wires;
		maxon::GraphNode outputs[mmd_material_binding::FieldCount];
		for (Int32 field = 0; field < mmd_material_binding::FieldCount; ++field)
		{
			const auto reader = root.FindChild(maxon::Id(k_morphNodeIds[field])) iferr_return;
			outputs[field] = Port(reader, mmd_material_binding::IsColorField(field) ? rs_color_out : rs_scalar_out, true) iferr_return;
		}
		const auto diffuse_input = Port(surface, rs_base_color, false) iferr_return;
		const auto opacity_input = Port(surface, rs_opacity_color, false) iferr_return;
		const auto specular_input = Port(surface, rs_specular, false) iferr_return;
		const auto roughness_input = Port(surface, rs_roughness, false) iferr_return;
		wires.push_back({outputs[2], specular_input, {}});
		wires.push_back({outputs[3], roughness_input, {}});
		if (texture.IsValid())
		{
			const auto bias = root.FindChild(maxon::Id("cmt_texture_bias")) iferr_return;
			const auto saturate = root.FindChild(maxon::Id("cmt_texture_clamp")) iferr_return;
			const auto add = root.FindChild(maxon::Id("cmt_texture_add")) iferr_return;
			const auto diffuse = root.FindChild(maxon::Id("cmt_texture_diffuse")) iferr_return;
			const auto sample = Port(texture, rs_tex_outcolor, true) iferr_return;
			const auto alpha = Port(splitter, rs_split_outalpha, true) iferr_return;
			const auto bias_out = Port(bias, rs_add_out, true) iferr_return;
			const auto saturate_out = Port(saturate, rs_saturate_out, true) iferr_return;
			const auto add_out = Port(add, rs_add_out, true) iferr_return;
			const auto diffuse_out = Port(diffuse, rs_mul_out, true) iferr_return;
			const auto multiplier = Port(texture, rs_tex_color_multiplier, false) iferr_return;
			const auto alpha_multiplier = Port(texture, rs_tex_alpha_multiplier, false) iferr_return;
			const auto split_in = Port(splitter, rs_split_input, false) iferr_return;
			const auto bias_first = Port(bias, rs_add_first, false) iferr_return;
			const auto bias_second = Port(bias, rs_add_second, false) iferr_return;
			const auto saturate_in = Port(saturate, rs_saturate_input, false) iferr_return;
			const auto add_first = Port(add, rs_add_first, false) iferr_return;
			const auto add_second = Port(add, rs_add_second, false) iferr_return;
			const auto diffuse_first = Port(diffuse, rs_mul_first, false) iferr_return;
			const auto diffuse_second = Port(diffuse, rs_mul_second, false) iferr_return;
			wires.push_back({outputs[4], multiplier, {outputs[0]}}); // v1 used diffuse * combined factor here.
			wires.push_back({outputs[1], alpha_multiplier, {}});
			wires.push_back({sample, split_in, {}});
			wires.push_back({sample, bias_first, {}});
			wires.push_back({outputs[5], bias_second, {}});
			wires.push_back({bias_out, saturate_in, {}});
			wires.push_back({saturate_out, add_first, {}});
			wires.push_back({outputs[6], add_second, {}});
			wires.push_back({add_out, diffuse_first, {}});
			wires.push_back({outputs[0], diffuse_second, {}});
			wires.push_back({textured ? diffuse_out : outputs[0], diffuse_input, {sample, outputs[0], diffuse_out}});
			wires.push_back({textured ? alpha : outputs[1], opacity_input, {alpha, outputs[1]}});
		}
		else
		{
			if (textured) return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
			wires.push_back({outputs[0], diffuse_input, {}});
			wires.push_back({outputs[1], opacity_input, {}});
		}
		if (metadata.GetInt32(mmd_material_binding::Profile) == mmd_material_binding::StandardSphereProfile)
		{
			// Replace only the final Base Color wire. Alpha and the PBR reflection
			// inputs retain their independent contracts.
			maxon::GraphNode base;
			std::vector<maxon::GraphNode> previous;
			for (auto it = wires.begin(); it != wires.end(); ++it)
			{
				if (it->destination != diffuse_input) continue;
				base = it->source;
				previous = it->replaceable;
				wires.erase(it);
				break;
			}
			previous.push_back(outputs[0]);
			for (const auto& id : {"cmt_sphere_combine_mul", "cmt_sphere_combine_add"})
			{
				const auto node = mmd_rs_sphere::Node(graph, id) iferr_return;
				const auto output = mmd_rs::Output(node, mmd_rs::CoreId(std::strcmp(id, "cmt_sphere_combine_mul") == 0
					? "rsmathmulvector.out" : "rsmathaddvector.out")) iferr_return;
				previous.push_back(output);
			}
			const auto plain = root.FindChild(maxon::Id("cmt_plain_diffuse")) iferr_return;
			if (plain.IsValid())
			{
				const auto output = mmd_rs::Output(plain, mmd_rs::CoreId("rsuserdatacolor.out")) iferr_return;
				previous.push_back(output);
			}
			const auto sphere_wires = mmd_rs_sphere::Wires(graph, metadata, base, diffuse_input, true) iferr_return;
			for (const auto& wire : sphere_wires)
				wires.push_back({wire.source, wire.destination, previous});
		}
		return wires;
	}

	static maxon::Result<void> CheckOrConnectWires(const std::vector<BindingWire>& wires, const Bool connect)
	{
		iferr_scope;
		for (const auto& wire : wires)
		{
			std::vector<maxon::GraphNode> remove;
			Bool conflict = false;
			maxon::GraphModelHelper::GetDirectPredecessors(wire.destination, maxon::NODE_KIND::PORT_MASK,
				[&](const maxon::GraphNode& source) -> maxon::Result<Bool>
				{
					if (source == wire.source) return true;
					Bool permitted = false;
					if (connect) for (const auto& previous : wire.replaceable) if (source == previous) permitted = true;
					if (permitted) remove.push_back(source); else conflict = true;
					return true;
				}) iferr_return;
			if (conflict || (!connect && !maxon::GraphModelHelper::IsConnected(wire.source, wire.destination)))
				return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
			if (connect)
			{
				for (const auto& previous : remove)
				{
					previous.Connect(wire.destination, maxon::WIRE_MODE::REMOVE) iferr_return;
				}
				if (!maxon::GraphModelHelper::IsConnected(wire.source, wire.destination))
				{
					wire.source.Connect(wire.destination) iferr_return;
				}
			}
		}
		return maxon::OK;
	}

	static maxon::Result<void> PrepareTextureMath(const maxon::nodes::NodesGraphModelRef& graph,
		const Bool allow_existing)
	{
		iferr_scope;
		const auto root = graph.GetNode(maxon::NodePath());
		const auto texture = root.FindChild(k_diffuseTextureNodeId) iferr_return;
		if (!texture.IsValid()) return maxon::OK;
		for (const auto& definition : k_textureMathNodes)
		{
			auto node = root.FindChild(maxon::Id(definition.id)) iferr_return;
			if (node.IsValid() && !allow_existing) return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
			const std::string asset = std::string("com.redshift3d.redshift4c4d.nodes.core.") + definition.asset;
			if (!node.IsValid())
			{
				node = graph.AddChild(maxon::Id(definition.id), maxon::Id(asset.c_str())) iferr_return;
			}
			// Refuse edited operations. Do not turn an artist's changed Add into Mul.
			const auto inputs = node.GetInputs() iferr_return;
			const auto input = inputs.FindChild(maxon::Id((asset + ".math_op").c_str())) iferr_return;
			const auto operation = input.GetPortValue<Int64>() iferr_return;
			if (!operation || *operation != definition.operation) return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
		}
		return maxon::OK;
	}

	static maxon::Result<void> ValidateTextureMath(const maxon::nodes::NodesGraphModelRef& graph)
	{
		iferr_scope;
		const auto root = graph.GetNode(maxon::NodePath());
		const auto texture = root.FindChild(k_diffuseTextureNodeId) iferr_return;
		if (!texture.IsValid()) return maxon::OK;
		for (const auto& definition : k_textureMathNodes)
		{
			const auto node = root.FindChild(maxon::Id(definition.id)) iferr_return;
			if (!node.IsValid()) return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
			const std::string asset = std::string("com.redshift3d.redshift4c4d.nodes.core.") + definition.asset;
			const auto inputs = node.GetInputs() iferr_return;
			const auto input = inputs.FindChild(maxon::Id((asset + ".math_op").c_str())) iferr_return;
			const auto operation = input.GetPortValue<Int64>() iferr_return;
			if (!operation || *operation != definition.operation) return maxon::IllegalStateError(MAXON_SOURCE_LOCATION);
		}
		return maxon::OK;
	}

}
#endif

BaseMaterial* MMDRedShiftMaterialAdapter::CreateFromPMX(const libmmd::PMXMaterial& pmx_material,
	const maxon::BaseArray<Filename>& texture_paths, const maxon::String& material_name)
{
#if API_VERSION >= 2024000
	MMDMaterialData data;
	data.FromPMX(pmx_material);
	const Int32 texture_index = pmx_material.m_textureIndex;
	if (texture_index >= 0 && texture_index < texture_paths.GetCount())
		data.texture_path = texture_paths[texture_index].GetString();
	const Int32 sphere_index = pmx_material.m_sphereTextureIndex;
	if (sphere_index >= 0 && sphere_index < texture_paths.GetCount())
		data.sphere_texture_path = texture_paths[sphere_index].GetString();
	BaseMaterial* const material = CreateFromData(data);
	if (material)
		material->SetName(material_name);
	return material;
#else
	(void)pmx_material;
	(void)texture_paths;
	(void)material_name;
	return nullptr;
#endif
}

BaseMaterial* MMDRedShiftMaterialAdapter::CreateFromData(const MMDMaterialData& data)
{
#if API_VERSION >= 2024000
	BaseMaterial* material = BaseMaterial::Alloc(Mmaterial);
	if (!material)
		return nullptr;
	iferr_scope_handler
	{
		GePrint("[MMD] RS material error: "_s + err.GetMessage());
		BaseMaterial::Free(material);
		return nullptr;
	};

	auto* const node_material = static_cast<NodeMaterial*>(material);
	node_material->CreateDefaultGraph(g_redshiftId) iferr_return;
	const auto& graph = node_material->GetGraph(g_redshiftId) iferr_return;
	const auto material_node = FindStandardMaterialNode(graph) iferr_return;
	if (!material_node.IsValid())
	{
		GePrint("[MMD] Redshift default graph has no Standard Material node."_s);
		BaseMaterial::Free(material);
		return nullptr;
	}

	auto transaction = BeginMaterialTransaction(graph) iferr_return;
	const Filename texture_path(data.texture_path);
	if (texture_path.IsPopulated() && GeFExist(texture_path))
	{
		CreateDiffuseTextureGraph(graph, material_node, data) iferr_return;
	}
	else
	{
		SetPlainDiffuse(material_node, data.diffuse_rgb, data.diffuse_alpha) iferr_return;
	}
	SetSpecular(material_node, data) iferr_return;
	BaseContainer ownership;
	ownership.SetBool(mmd_material_binding::ImporterOwned, true);
	mmd_rs_sphere::Metadata(ownership, data);
	mmd_rs_sphere::Prepare(graph, data) iferr_return;
	maxon::GraphNode base;
	const auto texture = FindImportedTextureNode(graph) iferr_return;
	const auto surface_input = Port(material_node, rs_base_color, false) iferr_return;
	if (texture.IsValid())
	{
		base = Port(texture, rs_tex_outcolor, true) iferr_return;
		base.Connect(surface_input, maxon::WIRE_MODE::REMOVE) iferr_return;
	}
	else
	{
		const auto plain = graph.AddChild(maxon::Id("cmt_plain_diffuse"), mmd_rs::CoreId("rsuserdatacolor")) iferr_return;
		mmd_rs::Set(plain, "rsuserdatacolor.default", ToNodeColor(data.diffuse_rgb)) iferr_return;
		base = mmd_rs::Output(plain, mmd_rs::CoreId("rsuserdatacolor.out")) iferr_return;
	}
	const auto sphere_wires = mmd_rs_sphere::Wires(graph, ownership, base, surface_input, false) iferr_return;
	for (const auto& wire : sphere_wires)
	{
		wire.source.Connect(wire.destination) iferr_return;
	}
	transaction.Commit() iferr_return;
	material->SetName(data.name_local);
	material->GetDataInstance()->SetContainer(g_mmd_material_texture_morph_shader_id, ownership);
	return material;
#else
	(void)data;
	return nullptr;
#endif
}

Bool MMDRedShiftMaterialAdapter::PrepareMorphBinding(const MMDMaterialData& data, BaseMaterial* material,
	BaseObject* model, BaseObject* mesh, String& diagnostic)
{
	return BuildMorphBinding(data, material, model, mesh, false, diagnostic);
}

Bool MMDRedShiftMaterialAdapter::RepairMorphBinding(const MMDMaterialData& data, BaseMaterial* material,
	BaseObject* model, BaseObject* mesh, String& diagnostic)
{
	return BuildMorphBinding(data, material, model, mesh, true, diagnostic);
}

Bool MMDRedShiftMaterialAdapter::BuildMorphBinding(const MMDMaterialData& data, BaseMaterial* material,
	BaseObject* model, BaseObject* mesh, const Bool repair, String& diagnostic)
{
#if API_VERSION >= 2024000
	using namespace mmd_material_binding;
	if (!material || !model || !mesh || !GeIsMainThread() || !IsRedShiftMaterial(material)) return false;
	if (IsBound(material) && !repair) return ValidateMorphBinding(material, diagnostic);
	if (repair && !IsOwner(material, model, material->GetDocument())) return false;
	String preparation_stage = "surface lookup"_s;
	iferr_scope_handler
	{
		diagnostic = String("Redshift binding preparation failed at ") + preparation_stage + String(": ") + MaxonConvert(err.GetMessage());
		return false;
	};
	auto* node_material = static_cast<NodeMaterial*>(material);
	const auto graph = node_material->GetGraph(g_redshiftId) iferr_return;
	const auto surface = FindStandardMaterialNode(graph) iferr_return;
	const auto texture = FindImportedTextureNode(graph) iferr_return;
	if (!surface.IsValid()) return false;
	BaseContainer metadata = Metadata(material);
	// Only materials created by this importer may be upgraded. Imported texture
	// node IDs also recognize the previous implementation before metadata existed.
	if (!metadata.GetBool(ImporterOwned) && !texture.IsValid())
	{ diagnostic = "Redshift material has no recognized importer ownership"_s; return false; }
	if (repair && metadata.GetString(Surface) != MaxonConvert(surface.GetPath().ToString()))
	{ diagnostic = "Redshift surface was replaced; create an independent material"_s; return false; }
	if (!repair)
	{
		maxon::Uuid uuid;
		uuid.CreateId() iferr_return;
		metadata.SetString(Token, MaxonConvert(uuid.ToString()));
	}
	metadata.SetLink(Model, model);
	const Bool textured = repair && IsBound(material) ? metadata.GetBool(Texture) : texture.IsValid();
	metadata.SetBool(Texture, textured);
	metadata.SetString(Surface, MaxonConvert(surface.GetPath().ToString()));
	const auto state = MMDMaterialRuntimeState::FromBase(data);
	BindingRollback rollback{material, mesh, Metadata(material)};
	auto transaction = BeginMaterialTransaction(graph) iferr_return;
	preparation_stage = "Matcap settings"_s;
	if (metadata.GetInt32(Profile) != StandardSphereProfile)
	{
		mmd_rs_sphere::Prepare(graph, data) iferr_return;
		mmd_rs_sphere::Metadata(metadata, data);
	}
	else
	{
		mmd_rs_sphere::Validate(graph, metadata) iferr_return;
	}
	for (Int32 index = 0; index < ProfileFieldCount(metadata); ++index)
	{
		const Int32 field = ProfileFieldAt(metadata, index);
		const Bool color = IsColorField(field);
		const auto existing = graph.GetNode(maxon::NodePath()).FindChild(maxon::Id(k_morphNodeIds[field])) iferr_return;
		if (existing.IsValid() && !repair)
		{ diagnostic = "Material contains an unrecognized Morph node; explicit repair is required"_s; return false; }
		auto reader = existing;
		if (!reader.IsValid())
		{
			reader = graph.AddChild(maxon::Id(k_morphNodeIds[field]), maxon::Id(color
				? "com.redshift3d.redshift4c4d.nodes.core.rsuserdatacolor"
				: "com.redshift3d.redshift4c4d.nodes.core.rsuserdatascalar")) iferr_return;
		}
		const maxon::String name = MaxonConvert(AttributeName(metadata.GetString(Token), static_cast<Field>(field)));
		if (color)
		{
			SetPortValue(reader, rs_color_attribute, name) iferr_return;
			SetPortValue(reader, rs_color_default, ToNodeColor(Color(state, static_cast<Field>(field), textured))) iferr_return;
		}
		else
		{
			SetPortValue(reader, rs_scalar_attribute, name) iferr_return;
			SetPortValue(reader, rs_scalar_default, static_cast<Float64>(Scalar(state, static_cast<Field>(field), textured))) iferr_return;
		}
	}
	preparation_stage = "texture math and connections"_s;
	PrepareTextureMath(graph, repair && metadata.GetInt32(Version) == CurrentVersion) iferr_return;
	const auto wires = BindingWires(graph, surface, textured, metadata) iferr_return;
	CheckOrConnectWires(wires, true) iferr_return;

	metadata.SetInt32(Version, CurrentVersion);
	material->GetDataInstance()->SetContainer(g_mmd_material_texture_morph_shader_id, metadata);
	const Bool reuse_attributes = repair && rollback.previous.GetInt32(Version) == CurrentVersion
		&& rollback.previous.GetInt32(Profile) == metadata.GetInt32(Profile)
		&& PublishUserData(mesh, material, state);
	if (!reuse_attributes && !PrepareUserData(mesh, material, state))
	{
		diagnostic = "Could not prepare Redshift object attributes"_s;
		return false;
	}
	rollback.attributes_created = !reuse_attributes;
	transaction.Commit() iferr_return;
	if (repair && !reuse_attributes) RemoveUserData(mesh, rollback.previous);
	rollback.committed = true;
	diagnostic = "Redshift User Data binding ready"_s;
	return true;
#else
	diagnostic = "Redshift shader bindings require SDK 2024 or newer"_s;
	return false;
#endif
}

Bool MMDRedShiftMaterialAdapter::ValidateMorphBinding(BaseMaterial* material, String& diagnostic) const
{
#if API_VERSION >= 2024000
	using namespace mmd_material_binding;
	if (!mmd_material_binding::IsBound(material) || !IsRedShiftMaterial(material)) return false;
	iferr_scope_handler { diagnostic = "Redshift binding validation failed"_s; return false; };
	const auto graph = static_cast<NodeMaterial*>(material)->GetGraph(g_redshiftId) iferr_return;
	const auto root = graph.GetNode(maxon::NodePath());
	const BaseContainer metadata = Metadata(material);
	const auto surface = FindStandardMaterialNode(graph) iferr_return;
	const auto texture = FindImportedTextureNode(graph) iferr_return;
	if (!surface.IsValid() || MaxonConvert(surface.GetPath().ToString()) != metadata.GetString(Surface)
		|| (metadata.GetBool(Texture) && !texture.IsValid()))
	{ diagnostic = "Redshift material structure was changed; explicit repair is required"_s; return false; }
	if (metadata.GetInt32(Version) != CurrentVersion)
	{ diagnostic = "Texture Morph semantics changed; explicitly upgrade material Morph"_s; return false; }
	ValidateTextureMath(graph) iferr_return;
	if (metadata.GetInt32(Profile) == StandardSphereProfile)
	{
		mmd_rs_sphere::Validate(graph, metadata) iferr_return;
	}
	const auto wires = BindingWires(graph, surface, metadata.GetBool(Texture), metadata) iferr_return;
	CheckOrConnectWires(wires, false) iferr_return;
	for (Int32 index = 0; index < ProfileFieldCount(metadata); ++index)
	{
		const Int32 field = ProfileFieldAt(metadata, index);
		const auto reader = root.FindChild(maxon::Id(k_morphNodeIds[field])) iferr_return;
		const auto attribute = GetPortValue<maxon::String>(reader, IsColorField(field) ? rs_color_attribute : rs_scalar_attribute) iferr_return;
		const auto attribute_name = attribute.GetValue() iferr_return;
		if (attribute_name != MaxonConvert(AttributeName(metadata.GetString(Token), static_cast<Field>(field))))
		{ diagnostic = "Redshift attribute binding was changed; explicit repair is required"_s; return false; }
	}

	return true;
#else
	return false;
#endif
}

Bool MMDRedShiftMaterialAdapter::UpdateMorphTexture(const MMDMaterialData& previous,
	const String& path, BaseMaterial* material, String& diagnostic)
{
#if API_VERSION >= 2024000
	using namespace mmd_material_binding;
	if (!GeIsMainThread() || !ValidateMorphBinding(material, diagnostic)) return false;
	if (path.IsPopulated() && !GeFExist(Filename(path)))
	{ diagnostic = "Texture file does not exist; the current binding was preserved"_s; return false; }
	iferr_scope_handler { diagnostic = "Redshift texture edit failed; graph changes were rolled back"_s; return false; };
	const auto graph = static_cast<NodeMaterial*>(material)->GetGraph(g_redshiftId) iferr_return;
	const auto root = graph.GetNode(maxon::NodePath());
	const auto surface = FindStandardMaterialNode(graph) iferr_return;
	auto texture = FindImportedTextureNode(graph) iferr_return;
	auto splitter = root.FindChild(k_opacitySplitterNodeId) iferr_return;
	BaseContainer metadata = Metadata(material);
	const Bool had_texture = texture.IsValid();
	const Bool textured = path.IsPopulated();
	if (texture.IsValid())
	{
		const auto inputs = texture.GetInputs() iferr_return;
		const auto bundle = inputs.FindChild(rs_tex0) iferr_return;
		const auto texture_path = bundle.FindChild(rs_tex0_path) iferr_return;
		const auto current = texture_path.GetPortValue<maxon::Url>() iferr_return;
		const auto value = current.GetValue() iferr_return;
		if (MaxonConvert(value).GetString() != metadata.GetString(TexturePath, previous.texture_path) || !splitter.IsValid())
		{ diagnostic = "Retained Redshift texture was edited; create an independent material"_s; return false; }
	}
	else if (splitter.IsValid())
	{ diagnostic = "Reserved Redshift texture structure is occupied; create an independent material"_s; return false; }
	auto transaction = BeginMaterialTransaction(graph) iferr_return;
	if (textured)
	{
		if (!texture.IsValid())
		{
			MMDMaterialData candidate;
			candidate.texture_path = path;
			CreateDiffuseTextureGraph(graph, surface, candidate, false) iferr_return;
			texture = FindImportedTextureNode(graph) iferr_return;
			splitter = root.FindChild(k_opacitySplitterNodeId) iferr_return;
		}
		const auto inputs = texture.GetInputs() iferr_return;
		const auto bundle = inputs.FindChild(rs_tex0) iferr_return;
		const auto texture_path = bundle.FindChild(rs_tex0_path) iferr_return;
		texture_path.SetPortValue(MaxonConvert(Filename(path), MAXONCONVERTMODE::READ)) iferr_return;
	}
	PrepareTextureMath(graph, had_texture) iferr_return;
	const auto wires = BindingWires(graph, surface, textured, metadata) iferr_return;
	CheckOrConnectWires(wires, true) iferr_return;
	transaction.Commit() iferr_return;
	metadata.SetBool(Texture, textured);
	if (textured) metadata.SetString(TexturePath, path);
	else if (texture.IsValid() && metadata.GetString(TexturePath).IsEmpty()) metadata.SetString(TexturePath, previous.texture_path);
	material->GetDataInstance()->SetContainer(g_mmd_material_texture_morph_shader_id, metadata);
	diagnostic = "Material texture updated"_s;
	return true;
#else
	diagnostic = "Redshift shader bindings require SDK 2024 or newer"_s;
	return false;
#endif
}

Bool MMDRedShiftMaterialAdapter::UpdateSphereTexture(const MMDMaterialData& previous,
	const String& path, const Int32 mode, BaseMaterial* material, String& diagnostic)
{
#if API_VERSION >= 2024000
	using namespace mmd_material_binding;
	if (!GeIsMainThread() || mode < 0 || mode > 3 || !ValidateMorphBinding(material, diagnostic)) return false;
	BaseContainer metadata = Metadata(material);
	if (metadata.GetInt32(Profile) != StandardSphereProfile)
	{ diagnostic = "Legacy RS binding requires an explicit Morph upgrade"_s; return false; }
	if (path.IsPopulated())
	{
		AutoAlloc<BaseBitmap> bitmap;
		if (!bitmap || bitmap->Init(Filename(path)) != IMAGERESULT::OK)
		{ diagnostic = "Sphere texture cannot be decoded; RS binding was preserved"_s; return false; }
	}
	iferr_scope_handler { diagnostic = "RS Matcap edit failed; graph transaction was rolled back"_s; return false; };
	const auto graph = static_cast<NodeMaterial*>(material)->GetGraph(g_redshiftId) iferr_return;
	const auto surface = FindStandardMaterialNode(graph) iferr_return;
	const auto old_wires = BindingWires(graph, surface, metadata.GetBool(Texture), metadata) iferr_return;
	metadata.SetString(SphereTexturePath, path);
	metadata.SetInt32(SphereMode, mode);
	metadata.SetBool(SphereHasTexture, path.IsPopulated() && (mode == 1 || mode == 2));
	metadata.SetString(ProfileDiagnostic, mode == 3
		? "Sphere SubTexture (Additional UV) is not mapped"_s : "Matcap Sphere Multiply/Add supported"_s);
	const auto next_wires = BindingWires(graph, surface, metadata.GetBool(Texture), metadata) iferr_return;
	// Even an inactive combine input is artist-owned when it has an unknown
	// predecessor. The active graph's validation alone cannot protect that input.
	for (const auto& next : next_wires)
	{
		Bool conflict = false;
		maxon::GraphModelHelper::GetDirectPredecessors(next.destination, maxon::NODE_KIND::PORT_MASK,
			[&](const maxon::GraphNode& from) -> maxon::Result<Bool>
			{
				Bool owned = from == next.source;
				for (const auto& old : old_wires)
					if (old.destination == next.destination && old.source == from) owned = true;
				if (!owned) conflict = true;
				return true;
			}) iferr_return;
		if (conflict) { diagnostic = "Sphere input contains an artist connection; create an independent material"_s; return false; }
	}
	auto transaction = BeginMaterialTransaction(graph) iferr_return;
	const auto file = mmd_rs_sphere::Path(graph) iferr_return;
	file.SetPortValue(MaxonConvert(Filename(path), MAXONCONVERTMODE::READ)) iferr_return;
	for (const auto& old : old_wires)
	{
		Bool retained = false;
		for (const auto& next : next_wires)
			if (old.source == next.source && old.destination == next.destination) retained = true;
		if (!retained)
		{
			old.source.Connect(old.destination, maxon::WIRE_MODE::REMOVE) iferr_return;
		}
	}
	CheckOrConnectWires(next_wires, true) iferr_return;
	transaction.Commit() iferr_return;
	material->GetDataInstance()->SetContainer(g_mmd_material_texture_morph_shader_id, metadata);
	material->SetDirty(DIRTYFLAGS::DATA);
	material->Message(MSG_UPDATE);
	diagnostic = metadata.GetString(ProfileDiagnostic);
	return true;
#else
	return false;
#endif
}

void MMDRedShiftMaterialAdapter::SyncTo(const MMDMaterialData& data, BaseMaterial* material)
{
#if API_VERSION >= 2024000
	if (!IsRedShiftMaterial(material))
		return;
	if (mmd_material_binding::IsBound(material))
	{
		using namespace mmd_material_binding;
		String diagnostic;
		if (!GeIsMainThread() || !ValidateMorphBinding(material, diagnostic)) return;
		iferr_scope_handler
		{
			DebugOutput(maxon::OUTPUT::DIAGNOSTIC, "[CMT] Redshift authoring sync failed: @", err);
			return;
		};
		const auto graph = static_cast<NodeMaterial*>(material)->GetGraph(g_redshiftId) iferr_return;
		const auto root = graph.GetNode(maxon::NodePath());
		const auto state = MMDMaterialRuntimeState::FromBase(data);
		const BaseContainer metadata = Metadata(material);
		const Bool textured = metadata.GetBool(Texture);
		auto transaction = BeginMaterialTransaction(graph) iferr_return;
		// Object attributes carry the evaluated Morph state. Reader defaults
		// carry the edited base for previews that have no model mesh context.
		for (Int32 index = 0; index < ProfileFieldCount(metadata); ++index)
		{
			const Int32 field = ProfileFieldAt(metadata, index);
			const auto reader = root.FindChild(maxon::Id(k_morphNodeIds[field])) iferr_return;
			if (IsColorField(field))
			{
				SetPortValue(reader, rs_color_default, ToNodeColor(Color(state, static_cast<Field>(field), textured))) iferr_return;
			}
			else
			{
				SetPortValue(reader, rs_scalar_default, static_cast<Float64>(Scalar(state, static_cast<Field>(field), textured))) iferr_return;
			}
		}
		transaction.Commit() iferr_return;
		material->SetName(data.name_local);
		material->SetDirty(DIRTYFLAGS::DATA);
		material->Message(MSG_UPDATE);
		return;
	}
	iferr_scope_handler
	{
		DebugOutput(maxon::OUTPUT::DIAGNOSTIC, "[CMT] Redshift material sync failed: @", err);
		return;
	};
	material->SetName(data.name_local);
	auto* const node_material = static_cast<NodeMaterial*>(material);
	const auto& graph = node_material->GetGraph(g_redshiftId) iferr_return;
	const auto texture = FindImportedTextureNode(graph) iferr_return;
	const auto material_node = FindStandardMaterialNode(graph) iferr_return;
	if (!material_node.IsValid())
		return;

	auto transaction = BeginMaterialTransaction(graph) iferr_return;
	if (texture.IsValid())
	{
		SetTextureCoefficients(texture, data.diffuse_rgb, data.diffuse_alpha) iferr_return;
	}
	else
	{
		SetPlainDiffuse(material_node, data.diffuse_rgb, data.diffuse_alpha) iferr_return;
		const auto plain = graph.GetNode(maxon::NodePath()).FindChild(maxon::Id("cmt_plain_diffuse")) iferr_return;
		if (plain.IsValid())
		{
			mmd_rs::Set(plain, "rsuserdatacolor.default", ToNodeColor(data.diffuse_rgb)) iferr_return;
		}

	}
	SetSpecular(material_node, data) iferr_return;
	transaction.Commit() iferr_return;
#else
	(void)data;
	(void)material;
#endif
}

void MMDRedShiftMaterialAdapter::SyncRuntimeState(const MMDMaterialRuntimeState& state, BaseMaterial* material)
{
	if (mmd_material_binding::IsBound(material)) return;
#if API_VERSION >= 2024000
	if (!IsRedShiftMaterial(material))
		return;
	iferr_scope_handler
	{
		DebugOutput(maxon::OUTPUT::DIAGNOSTIC, "[CMT] Redshift texture coefficient sync failed: @", err);
		return;
	};
	const auto* const node_material = static_cast<const NodeMaterial*>(material);
	const auto& graph = node_material->GetGraph(g_redshiftId) iferr_return;
	const auto texture = FindImportedTextureNode(graph) iferr_return;
	if (!texture.IsValid())
		return;

	const Vector factor = state.texture.LegacyColor();
	const Vector color(state.diffuse_rgb.x * factor.x,
		state.diffuse_rgb.y * factor.y, state.diffuse_rgb.z * factor.z);
	auto transaction = BeginMaterialTransaction(graph) iferr_return;
	// Replace the complete effective coefficient. SyncTo() has already received
	// the effective diffuse value, so multiplying its stored node value here
	// would apply the material morph a second time and accumulate on each frame.
	SetTextureCoefficients(texture, color, state.diffuse_alpha * state.texture.LegacyAlpha()) iferr_return;
	transaction.Commit() iferr_return;
#else
	(void)state;
	(void)material;
#endif
}

void MMDRedShiftMaterialAdapter::ReadFrom(const BaseMaterial* material, MMDMaterialData& data)
{
	if (mmd_material_binding::IsBound(material)) return;
#if API_VERSION >= 2024000
	if (!IsRedShiftMaterial(material))
		return;
	iferr_scope_handler { return; };
	data.name_local = material->GetName();
	const auto* const node_material = static_cast<const NodeMaterial*>(material);
	const auto& graph = node_material->GetGraph(g_redshiftId) iferr_return;
	const auto material_node = FindStandardMaterialNode(graph) iferr_return;
	if (!material_node.IsValid())
		return;

	// Read these fields before the textured-material early return. Connected
	// inputs are evaluated shader outputs; their stored defaults are not base data.
	const Bool specular_connected = HasInputConnection(material_node, rs_specular) iferr_return;
	if (!specular_connected)
	{
		const auto specular = GetPortValue<maxon::Color64>(material_node, rs_specular) iferr_return;
		if (specular && std::isfinite(specular->r) && std::isfinite(specular->g) && std::isfinite(specular->b))
			data.specular = Vector(specular->r, specular->g, specular->b);
	}
	const Bool roughness_connected = HasInputConnection(material_node, rs_roughness) iferr_return;
	if (!roughness_connected)
	{
		const auto roughness = GetPortValue<Float64>(material_node, rs_roughness) iferr_return;
		double power = 0.0;
		if (roughness && cmt_material::TrySpecularPowerFromRoughness(*roughness, power))
			data.specular_power = static_cast<Float>(power);
	}

	const auto texture = FindImportedTextureNode(graph) iferr_return;
	if (texture.IsValid())
	{
		const auto color = GetPortValue<maxon::Color64>(texture, rs_tex_color_multiplier) iferr_return;
		if (color)
			data.diffuse_rgb = Vector(color->r, color->g, color->b);
		const auto alpha = GetPortValue<Float64>(texture, rs_tex_alpha_multiplier) iferr_return;
		if (alpha)
			data.diffuse_alpha = static_cast<Float>(*alpha);
		const auto inputs = texture.GetInputs() iferr_return;
		const auto bundle = inputs.FindChild(rs_tex0) iferr_return;
		if (bundle.IsValid())
		{
			const auto path = bundle.FindChild(rs_tex0_path) iferr_return;
			if (path.IsValid())
			{
				const auto url = path.GetPortValue<maxon::Url>() iferr_return;
				if (url)
					data.texture_path = MaxonConvert(*url).GetString();
			}
		}
		return;
	}

	const auto color = GetPortValue<maxon::Color64>(material_node, rs_base_color) iferr_return;
	if (color)
		data.diffuse_rgb = Vector(color->r, color->g, color->b);
	const auto opacity = GetPortValue<maxon::Color64>(material_node, rs_opacity_color) iferr_return;
	if (opacity)
		data.diffuse_alpha = static_cast<Float>(opacity->r);
#else
	(void)material;
	(void)data;
#endif
}
