CONTAINER PMX_Bone_Tag
{
	NAME PMX_Bone_Tag;
	INCLUDE Tbase;
	
	GROUP PMX_BONE_INFO_GRP{
		DEFAULT 1;
		STRING     BONE_NAME_LOCAL {ANIM OFF;}
		STRING     BONE_NAME_UNIVERSAL {ANIM OFF;}
		VECTOR     POSITION {ANIM OFF;}
		GROUP PMX_BONE_PARENT_BONE_GRP{
			DEFAULT 1;
			COLUMNS 2;

			LONG PARENT_BONE_INDEX {ANIM OFF;}
			LINK PARENT_BONE_LINK {ANIM OFF;}
		}
		GROUP PMX_BONE_FLAG_GRP{
			DEFAULT 1;
			COLUMNS 5;

			BOOL   ROTATABLE {ANIM OFF;}
			BOOL   TRANSLATABLE {ANIM OFF;}
			BOOL   VISIBLE {ANIM OFF;}
			BOOL   ENABLED {ANIM OFF;}
			BOOL   IS_IK {ANIM OFF;}
		}	
		GROUP PMX_BONE_DEFORM_LAYER_GRP{
			DEFAULT 1;
			COLUMNS 2;

			LONG LAYER {ANIM OFF;}
			BOOL PHYSICS_AFTER_DEFORM {ANIM OFF;}
		}
		GROUP PMX_BONE_END_OF_BONE_GRP{
			DEFAULT 1;
			LONG INDEXED_TAIL_POSITION{ANIM OFF;MIN 0;MAX 1;CYCLE{TAIL_IS_INDEX;TAIL_IS_POSITION;}}			
			LONG TAIL_INDEX{ANIM OFF;MIN -1;}			
			VECTOR TAIL_POSITION{ANIM OFF;}				
		}
	}
}