#ifndef CBNURBS_H__
#define CBNURBS_H__

enum
{
	NURBSCURVE_CLOSED								= 1101,
	NURBSCURVE_DEGREE								= 1102,
	NURBSCURVE_POINTCOUNT							= 1103,

	NURBSCURVE_POLYNOMIAL							= 1104,
	NURBSCURVE_PERIODICITY							= 1105,

	NURBSCURVE_TMIN									= 1106,
	NURBSCURVE_TMAX									= 1107
};

#endif // CBNURBS_H__
