#ifndef DCHARUPDATE_H__
#define DCHARUPDATE_H__

enum
{
	ID_CA_CHARACTER_UPDATE_ADJUST = 1000,
	ID_CA_CHARACTER_UPDATE_CONTROLLERS,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_CHARACTER_UPDATE_ADJUST_NONE = 0,
	ID_CA_CHARACTER_UPDATE_ADJUST_HANDLES,
	ID_CA_CHARACTER_UPDATE_ADJUST_MG,

	ID_CA_CHARACTER_UPDATE_CONTROLLERS_NONE = 0,
	ID_CA_CHARACTER_UPDATE_CONTROLLERS_SIZE,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_CHARACTER_UPDATE_DUMMY
};

#endif // DCHARUPDATE_H__
