#ifndef DSOUNDDATA_H__
#define DSOUNDDATA_H__

enum
{
	SOUNDDATASUBCHANNEL_GROUP										= 900,	// GROUP
	SOUNDDATASUBCHANNEL_PROBE_GROUP							= 901,	// GROUP

	SOUNDDATASUBCHANNEL_LOG											= 1000,	// Float
	SOUNDDATASUBCHANNEL_DIRECTION								= 1001, // Int
		SOUNDDATASUBCHANNEL_DIRECTION_VERT					= 0,
		SOUNDDATASUBCHANNEL_DIRECTION_HORIZ					= 1,
	SOUNDDATASUBCHANNEL_GRADIENT								= 1002, // Gradient
	SOUNDDATASUBCHANNEL_FREEEZE									= 1003,	// Bool

	SOUNDDATASUBCHANNEL_DUMMY_
};

#endif // DSOUNDDATA_H__
