#ifndef ETPARAMETER_H__
#define ETPARAMETER_H__

enum
{
	ETPARAMETERTAG_RESET									 = 1000,	// BUTTON
	ETPARAMETERTAG_MODE										 = 1001,	// Int Cycle
	ETPARAMETERTAG_MODE_ABSOLUTE					 = 0,
	ETPARAMETERTAG_MODE_RELATIVE					 = 1,
	ETPARAMETERTAG_HIDEUNUSED							 = 1002,	// Boolean
	ETPARAMETERTAG_STRENGTH								 = 1003,	// Float
	ETPARAMETERTAG_FIELDS									 = 1004,	// FieldList
	ETPARAMETERTAG_FIELDPOINT							 = 1005,	// Int Cycle
	ETPARAMETERTAG_FIELDPOINT_EXPRESSION	 = 0,
	ETPARAMETERTAG_FIELDPOINT_DOUBLE			 = 1,
	ETPARAMETERTAG_FIELDPOINT_NOEXPRESSION = 2,
	ETPARAMETERTAG_FIELDPOINT_GLOBALDOUBLE = 3,
	ETPARAMETERTAG_FIELDPOINT_FIXPOINT		 = 4,
	ETPARAMETERTAG_FIXPOSITION						 = 1006,	// Button
	ETPARAMETERTAG_OBJECT									 = 2000,	// Group
	ETPARAMETERTAG_FIELDGROUP							 = 910		// Group
};
#endif																						// ETPARAMETER_H__
