#ifndef FAIIMPORT_H__
#define FAIIMPORT_H__

enum
{
	AIIMPORTFILTER_SCALE					= 2000,
	AIIMPORTFILTER_GROUPSPLINES		= 2001,
	AIIMPORTFILTER_CONNECTSPLINES			= 2002,
	AIIMPORTFILTER_FORMAT 					= 2003,
		AIIMPORTFILTER_ILLUSTRATOR8			= 2004,
		AIIMPORTFILTER_ILLUSTRATORCC		= 2005,
		
	AIIMPORTFILTER_CREATE_VECTOROBJECT		= 3000,
	AIIMPORTFILTER_FORCE_PDF				= 3001,
	AIIMPORTFILTER_GREEDY_FILL				= 3002,
	
	AIIMPORTFILTER_FORMAT_STRING			= 3003
};

#endif // FAIIMPORT_H__
