#ifndef FBASE_H__
#define FBASE_H__

enum
{
	ID_FILTERPROPERTIES	= 1001023,

	/// Preset drop down (Int)
	PRESET_OPTIONS_GROUP_PRESETS = 500,
	PRESET_OPTIONS_PRESETS = 501,
		PRESET_OPTIONS_PRESETS_DEFAULT = 98,
		PRESET_OPTIONS_PRESETS_CUSTOM = 99,
		PRESET_OPTIONS_PRESETS_START = 100,
	PRESET_OPTIONS_PRESETS_CUSTOM_SAVEBUTTON = 502,
	PRESET_OPTIONS_PRESETS_CUSTOM_DELETEBUTTON = 503,

};

#endif	// FBASE_H__
