#ifndef _FORGERIO_SCENELOADER_H__
#define _FORGERIO_SCENELOADER_H__

enum 
{
	
	fforgerioloader = 10000,
	FORGERIO_SCALE_FACTOR_IMPORT,
	FORGERIO_IMPORT_UVW,
	FORGERIO_IMPORT_POLYPAINT,
	FORGERIO_IMPORT_POLYGROUP,
	FORGERIO_IMPORT_GROUP,
	FORGERIO_IMPORT_MATERIALS,
	FORGERIO_IMPORT_REPLACE_EXISTING,
	FORGERIO_IMPORT_MERGE

};

#endif

