#ifndef FLTIME_H__
#define FLTIME_H__

enum
{
	TIMEFIELDLAYER_SHAPE = 1000,	// Int Cycle
		TIMEFIELDLAYER_SHAPE_NONE = 0,
		TIMEFIELDLAYER_SHAPE_SINE = 1,
		TIMEFIELDLAYER_SHAPE_TRIANGLE = 2,
		TIMEFIELDLAYER_SHAPE_SAWTOOTH = 3,
		TIMEFIELDLAYER_SHAPE_SQUARE = 4,
	TIMEFIELDLAYER_SPEED = 1001,	// Time
	TIMEFIELDLAYER_BIAS = 1002,	// Float
	TIMEFIELDLAYER_OFFSET = 1003,	// Time
	TIMEFIELDLAYER_FIELDS = 1004,	// FieldList
	TIMEFIELDLAYER_FIELDS_GRP = 1005,	// Group
};
#endif // FTIME_H__
