#ifndef GVMATERIAL_H__
#define GVMATERIAL_H__

enum
{
	GV_MATERIAL_TYPE = 1000,
	GV_MATERIAL_EXCLUDE_ID,

	GV_MATERIAL_INPUT_START = 2000,
	GV_MATERIAL_INPUT_COUNT,
	GV_MATERIAL_OPERATOR_ON,

	GV_MATERIAL_OUTPUT_MATERIAL = 3000,
	GV_MATERIAL_OUTPUT_COUNT,

	GV_MATERIAL
};

#endif // GVMATERIAL_H__
