#ifndef GVOSCVECTOR2DCONTROLLER_H__
#define GVOSCVECTOR2DCONTROLLER_H__

enum
{
	OSC_VECTOR2D_VALUE_METHOD_NAME = 4000,
	OSC_VECTOR2D_VALUE_X = 4001,
	OSC_VECTOR2D_VALUE_Y = 4002,
	
	OSC_VECTOR2D_VALUE_PORT_X = 4003,
	OSC_VECTOR2D_VALUE_PORT_Y = 4004,
	
	OSC_VECTOR2D_VALUE_SET_METHOD_NAME = 4005
};

#endif // GVOSCVECTOR2DCONTROLLER_H__



