#ifndef GVOSCBOOLCONTROLLER_H__
#define GVOSCBOOLCONTROLLER_H__

enum
{
	OSC_BOOL_VALUE_METHOD_NAME = 4000,
	OSC_BOOL_VALUE = 4001,
	OSC_BOOL_VALUE_PORT = 4002,
	OSC_BOOL_VALUE_SET_METHOD_NAME = 4003
};

#endif // GVOSCBOOLCONTROLLER_H__



