#ifndef MGLINEARARRAY_H__
#define MGLINEARARRAY_H__

enum
{
	MG_LINEAR_COUNT						= 1270,
	MG_LINEAR_MODE						= 1271,
	MG_LINEAR_MODE_ALL				= 0,	//overall
	MG_LINEAR_MODE_STEP				= 1,	//per step
	MG_LINEAR_OBJECT_AMOUNT		= 1272,
	MG_LINEAR_OBJECT_POSITION = 1273,
	MG_LINEAR_OBJECT_ROTATION = 1274,
	MG_LINEAR_OBJECT_SCALE		= 1275,
	MG_LINEAR_JOINT_MODE			= 1276,
	MG_LINEAR_JOINT_MODE_ALL	= 0,
	MG_LINEAR_JOINT_MODE_STEP = 1,
	MG_LINEAR_JOINT_ROTATION	= 1277,
	MG_LINEAR_JOINT_SCALE			= 1278,
	MG_LINEAR_OFFSET					= 1279
};
#endif // MGLINEARARRAY_H__
