#ifndef MILLUM_H__
#define MILLUM_H__

enum
{
	ID_MATERIALGROUP_ILLUMINATION							= 820,
	MATERIAL_PAGE_ILLUMINATION								= 821,

	MATERIAL_GLOBALILLUM_GENERATE							= 1101,
	MATERIAL_GLOBALILLUM_GENERATE_STRENGTH		= 1112,
	MATERIAL_GLOBALILLUM_RECEIVE							= 1100,
	MATERIAL_GLOBALILLUM_RECEIVE_STRENGTH			= 1102,
	MATERIAL_GLOBALILLUM_SATURATION						= 1115,
	MATERIAL_GLOBALILLUM_GENERATE_SATURATION	= 1116,
	MATERIAL_GLOBALILLUM_AREA 								= 1180, // start at 80 to avoid future issues
	MATERIAL_GLOBALILLUM_PORTAL								= 1117,
	MATERIAL_GLOBALILLUM_SAMPLINGMODE_EX			= 1118,
		MATERIAL_GLOBALILLUM_SAMPLINGMODE_NONE						= 0,
		MATERIAL_GLOBALILLUM_SAMPLINGMODE_OVERSAMPLING		= 1,
		MATERIAL_GLOBALILLUM_SAMPLINGMODE_DIRECT					= 2,
		MATERIAL_GLOBALILLUM_SAMPLINGMODE_DIRECTPERPIXEL	= 3,
	MATERIAL_GLOBALILLUM_MAXSAMPLES_EX				= 1119,
	MATERIAL_GLOBALILLUM_ACCURACY_EX					= 1103, // 1120 is taken!
	MATERIAL_GLOBALILLUM_INTENSITY_EX 				= 1105,
	MATERIAL_GLOBALILLUM_PRECISE_EX 					= 1106,
	MATERIAL_GLOBALILLUM_SELFSHADOW_EX 				= 1107,

	MATERIAL_CAUSTICS_GENERATE								= 1109,
	MATERIAL_CAUSTICS_GENERATE_STRENGTH				= 1113,
	MATERIAL_CAUSTICS_RECEIVE									= 1108,
	MATERIAL_CAUSTICS_RECEIVE_STRENGTH				= 1114,
	MATERIAL_CAUSTICS_SAMPLERADIUS						= 1110,
	MATERIAL_CAUSTICS_SAMPLES									= 1111,
};

#endif // MILLUM_H__
