#ifndef OCACLUSTER_H__
#define OCACLUSTER_H__

enum
{
	ID_CA_CLUSTER_OBJECT_WEIGHT_GROUP = 5000,
	ID_CA_CLUSTER_OBJECT_OFFSET_GROUP,

	ID_CA_CLUSTER_OBJECT_LINK = 2000,
	ID_CA_CLUSTER_OBJECT_TARGET,
	ID_CA_CLUSTER_OBJECT_STRENGTH,
	ID_CA_CLUSTER_OBJECT_P_WEIGHT,
	ID_CA_CLUSTER_OBJECT_S_WEIGHT,
	ID_CA_CLUSTER_OBJECT_R_WEIGHT,
	ID_CA_CLUSTER_OBJECT_TRANSFORM,
	ID_CA_CLUSTER_OBJECT_MAINTAIN_OFFSET,
	ID_CA_CLUSTER_OBJECT_MAINTAIN_P_OFFSET,
	ID_CA_CLUSTER_OBJECT_MAINTAIN_S_OFFSET,
	ID_CA_CLUSTER_OBJECT_MAINTAIN_R_OFFSET,
	ID_CA_CLUSTER_FALLOFF_MODE,
	ID_CA_CLUSTER_EFFECTOR,
	ID_CA_CLUSTER_OBJECT_P_WEIGHT_MAP,
	ID_CA_CLUSTER_OBJECT_S_WEIGHT_MAP,
	ID_CA_CLUSTER_OBJECT_R_WEIGHT_MAP,
	ID_CA_CLUSTER_OBJECT_MATRIX,
	ID_CA_CLUSTER_OBJECT_TARGET_ADD,
	ID_CA_CLUSTER_FALLOFF_RADIUS,
	ID_CA_CLUSTER_FALLOFF,
	ID_CA_CLUSTER_WIDTH,
	ID_CA_CLUSTER_HARDNESS,
	ID_CA_CLUSTER_FALLOFF_CURVE,
	ID_CA_CLUSTER_OBJECT_ALIGN_AXIS,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_CLUSTER_OBJECT_TRANSFORM_LOCAL = 0,
	ID_CA_CLUSTER_OBJECT_TRANSFORM_WORLD,

	ID_CA_CLUSTER_FALLOFF_MODE_NONE = 0,
	ID_CA_CLUSTER_FALLOFF_MODE_WORLD,
	ID_CA_CLUSTER_FALLOFF_MODE_LOCAL,
	ID_CA_CLUSTER_FALLOFF_MODE_SURFACE,

	ID_CA_CLUSTER_OBJECT_MATRIX_OBJECT = 0,
	ID_CA_CLUSTER_OBJECT_MATRIX_POINT_CENTER,
	ID_CA_CLUSTER_OBJECT_MATRIX_POINT_ALIGN,

	ID_CA_CLUSTER_FALLOFF_NONE = 0,
	ID_CA_CLUSTER_FALLOFF_LINEAR,
	ID_CA_CLUSTER_FALLOFF_DOME,
	ID_CA_CLUSTER_FALLOFF_BELL,
	ID_CA_CLUSTER_FALLOFF_CIRCLE,
	ID_CA_CLUSTER_FALLOFF_NEEDLE,
	ID_CA_CLUSTER_FALLOFF_SPLINE,
	ID_CA_CLUSTER_FALLOFF_SIMPLE,

	ID_CA_CLUSTER_OBJECT_ALIGN_AXIS_X = 0,
	ID_CA_CLUSTER_OBJECT_ALIGN_AXIS_Y,
	ID_CA_CLUSTER_OBJECT_ALIGN_AXIS_Z,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_CLUSTER_OBJECT_DUMMY
};

#endif // OCACLUSTER_H__
