#ifndef OCASURFACEDEFORMER_H__
#define OCASURFACEDEFORMER_H__

enum
{
	ID_CA_SURFACE_DEFORMER_OBJECT_CAGE = 1000,
	ID_CA_SURFACE_DEFORMER_OBJECT_INITIAL,
	ID_CA_SURFACE_DEFORMER_OBJECT_RESTORE,
	ID_CA_SURFACE_DEFORMER_OBJECT_MEM,
	ID_CA_SURFACE_DEFORMER_OBJECT_STRENGTH,
	ID_CA_SURFACE_DEFORMER_OBJECT_TYPE,
	ID_CA_SURFACE_DEFORMER_OBJECT_MAP_U,
	ID_CA_SURFACE_DEFORMER_OBJECT_MAP_V,
	ID_CA_SURFACE_DEFORMER_OBJECT_MAP_SCALE,
	ID_CA_SURFACE_DEFORMER_OBJECT_OFFSET,
	ID_CA_SURFACE_DEFORMER_OBJECT_MAP_PLANE,
	ID_CA_SURFACE_DEFORMER_OBJECT_AREA,


	//////////////////////////////////////////////////////////////////////////

	ID_CA_SURFACE_DEFORMER_OBJECT_TYPE_PROJECTION = 0,
	ID_CA_SURFACE_DEFORMER_OBJECT_TYPE_MAPPING_UV,
	ID_CA_SURFACE_DEFORMER_OBJECT_TYPE_MAPPING_VU,

	ID_CA_SURFACE_DEFORMER_OBJECT_MAP_PLANE_XY = 0,
	ID_CA_SURFACE_DEFORMER_OBJECT_MAP_PLANE_YZ,
	ID_CA_SURFACE_DEFORMER_OBJECT_MAP_PLANE_XZ,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_SURFACE_DEFORMER_OBJECT_DUMMY
};

#endif // OCASURFACEDEFORMER_H__
