#ifndef OEDEFORMER_PANEL_H__
#define OEDEFORMER_PANEL_H__

enum
{
	ID_MG_EFFECTORDEFORMER_GROUP				= 5200,
	ID_MG_EFFECTORDEFORMER_MODE					= 5201,
	ID_MG_EFFECTORDEFORMER_MODE_OFF			= 0,
	ID_MG_EFFECTORDEFORMER_MODE_OBJECT	= 1,
	ID_MG_EFFECTORDEFORMER_MODE_POINT		= 2,
	ID_MG_EFFECTORDEFORMER_MODE_POLYGON = 3
};
#endif // OEDEFORMER_PANEL_H__
