#ifndef OMETABALL_H__
#define OMETABALL_H__

enum
{
	METABALLOBJECT_THRESHOLD				= 1000,	// REAL
	METABALLOBJECT_SUBEDITOR				= 1001, // REAL
	METABALLOBJECT_SUBRAY						= 1002, // REAL
	METABALLOBJECT_EXPONENTIAL			= 1003, // BOOL
	METABALLOBJECT_ACCURATENORMALS	= 1004  // BOOL
};

#endif // OMETABALL_H__
