#ifndef OMOGRAPH_TEXT_H__
#define OMOGRAPH_TEXT_H__

enum
{
	MGTEXTOBJECT_SPLINEISOPARM			= 1100, // these have to be higher or they clash with the text
	MGTEXTOBJECT_SPLINESUB					= 1101,
	MGTEXTOBJECT_SPLINEMOVE					= 1102,
	MGTEXTOBJECT_GROUPTRANSFORM_ALL = -300,
	MGTEXTOBJECT_GROUPTRANSFORM_LINE = -280,
	MGTEXTOBJECT_GROUPTRANSFORM_WORD = -260,
	MGTEXTOBJECT_GROUPTRANSFORM_CHAR = -240,
	MGTEXTOBJECT_GROUPEFFECTOR_ALL	= 5111,
	MGTEXTOBJECT_GROUPEFFECTOR_LINE = 5112,
	MGTEXTOBJECT_GROUPEFFECTOR_WORD = 5113,
	MGTEXTOBJECT_GROUPEFFECTOR_CHAR = 5114,
	MGTEXTOBJECT_EFFECTORLIST_ALL		= 5121,
	MGTEXTOBJECT_EFFECTORLIST_LINE	= 5132,
	MGTEXTOBJECT_EFFECTORLIST_WORD	= 5143,
	MGTEXTOBJECT_EFFECTORLIST_CHAR	= 5154,
	MGTEXTOBJECT_AXIS_ALL						= 5160,
	MGTEXTOBJECT_AXIS_LINE					= 5161,
	MGTEXTOBJECT_AXIS_WORD					= 5162,
	MGTEXTOBJECT_AXIS_CHAR					= 5163,
	MGTEXTOBJECT_GROUPALL						= 5170,
	MGTEXTOBJECT_GROUPLINE					= 5171,
	MGTEXTOBJECT_GROUPWORD					= 5172,
	MGTEXTOBJECT_GROUPCHAR					= 5173,
	MGTEXTOBJECT_AXIS_ALL_ALIGN			= 5180,
	MGTEXTOBJECT_AXIS_LINE_ALIGN		= 5181,
	MGTEXTOBJECT_AXIS_WORD_ALIGN		= 5182,
	MGTEXTOBJECT_AXIS_CHAR_ALIGN		= 5183,
	MGTEXTOBJECT_INDEXING						= 5190,
	MGTEXTOBJECT_LETTERINDEX				= 0,
	MGTEXTOBJECT_WORDINDEX					= 1,
	MGTEXTOBJECT_LINEINDEX					= 2,
	MGTEXTOBJECT_ALLINDEX						= 3
};
#endif // OMOGRAPH_TEXT_H__
