#ifndef OMOGRAPH_CLONER_H__
#define OMOGRAPH_CLONER_H__

enum
{
	MGCLONER_MODE					= 1020,
	MGCLONER_MODE_CLUSTER = 0,
	MGCLONER_MODE_ITERATE,
	MGCLONER_MODE_RANDOM,
	MGCLONER_MODE_BLEND,
	MGCLONER_MODE_SORT,
	MGCLONER_FIX_TEXTURE_OFF = 0,
	MGCLONER_FIX_TEXTURE_STRAIGHT,
	MGCLONER_FIX_TEXTURE_ALTX,
	MGCLONER_FIX_TEXTURE_ALTY,
	MGCLONER_ANIMATIONMODE_PLAY = 0,
	MGCLONER_ANIMATIONMODE_LOOP,
	MGCLONER_ANIMATIONMODE_FIXED,
	MGCLONER_ANIMATIONMODE_FIXEDLOOP,
	MGCLONER_FIX_CLONES					= 1021,
	MGCLONER_SEED								= 1022,
	MGCLONER_FIX_TEXTURE				= 1023,
	MGCLONER_ANIMATIONMODE			= 1024,
	MGCLONER_VOLUMEINSTANCES_MODE =	1025, // changed for an enum in R20
		MGCLONER_VOLUMEINSTANCES_MODE_NONE = 0,
		MGCLONER_VOLUMEINSTANCES_MODE_RENDERINSTANCE,
		MGCLONER_VOLUMEINSTANCES_MODE_RENDERMULTIINSTANCE,
	MGCLONER_MULTIINSTANCE_DRAW_MODE = 1026, // Added R20
		MGCLONER_MULTIINSTANCE_DRAW_MODE_NONE		= 0,
		MGCLONER_MULTIINSTANCE_DRAW_MODE_POINTS = 1,
		MGCLONER_MULTIINSTANCE_DRAW_MODE_FULL		= 2,
		MGCLONER_MULTIINSTANCE_DRAW_MODE_CUBE		= 3,
		MGCLONER_MULTIINSTANCE_DRAW_MODE_BBOX		= 4,
};
#endif // OMOGRAPH_CLONER_H__
