#ifndef ONOISEFALLOFF_H__
#define ONOISEFALLOFF_H__

enum
{
	ID_NOISEFALLOFF_VIEWPLANES_GROUP = 6000,
	ID_NOISEFALLOFF_VIEWPLANES_ACTIVEX = 6001,
	ID_NOISEFALLOFF_VIEWPLANES_ACTIVEY = 6002,
	ID_NOISEFALLOFF_VIEWPLANES_ACTIVEZ = 6003,
	ID_NOISEFALLOFF_VIEWPLANES = 6004,
	ID_NOISEFALLOFF_VIEWDENSITY = 6005,
	ID_NOISEFALLOFF_NOISE_GROUP = 6006,
	ID_NOISEFALLOFF_SCALE_GLOBAL = 6007,
	ID_NOISEFALLOFF_SCALE_LOCAL = 6008,
	ID_NOISEFALLOFF_NOISE_SEED = 6009,
	ID_NOISEFALLOFF_NOISE_ANIMATIONSPEED = 6010,
	ID_NOISEFALLOFF_NOISE_TYPE = 6011,
		ID_NOISEFALLOFF_NOISE_TYPE_BOX = 1,
		ID_NOISEFALLOFF_NOISE_TYPE_BLISTEREDTURBULENCE = 2,
		ID_NOISEFALLOFF_NOISE_TYPE_BUYA = 3,
		ID_NOISEFALLOFF_NOISE_TYPE_CELL = 4,
		ID_NOISEFALLOFF_NOISE_TYPE_CRANAL = 5,
		ID_NOISEFALLOFF_NOISE_TYPE_DENTS = 6,
		ID_NOISEFALLOFF_NOISE_TYPE_DISPLACEDTURBULENCE = 7,
		ID_NOISEFALLOFF_NOISE_TYPE_ELECTRIC = 8,
		ID_NOISEFALLOFF_NOISE_TYPE_FBM = 9,
		ID_NOISEFALLOFF_NOISE_TYPE_GASEOUS = 10,
		ID_NOISEFALLOFF_NOISE_TYPE_HAMA = 11,
		ID_NOISEFALLOFF_NOISE_TYPE_LUKA = 12,
		ID_NOISEFALLOFF_NOISE_TYPE_MODNOISE = 13,
		ID_NOISEFALLOFF_NOISE_TYPE_NAKI = 14,
		ID_NOISEFALLOFF_NOISE_TYPE_NUTOUS = 15,
		ID_NOISEFALLOFF_NOISE_TYPE_OBER = 16,
		ID_NOISEFALLOFF_NOISE_TYPE_PEZO = 17,
		ID_NOISEFALLOFF_NOISE_TYPE_POXO = 18,
		ID_NOISEFALLOFF_NOISE_TYPE_SEMA = 19,
		ID_NOISEFALLOFF_NOISE_TYPE_STUPL = 20,
		ID_NOISEFALLOFF_NOISE_TYPE_TURBULENCE = 21,
		ID_NOISEFALLOFF_NOISE_TYPE_VLNOISE = 22,
		ID_NOISEFALLOFF_NOISE_TYPE_WAVYTURBULENCE = 23,
		ID_NOISEFALLOFF_NOISE_TYPE_CELLVORONOI = 24,
		ID_NOISEFALLOFF_NOISE_TYPE_DISPLACEDVORONOI = 25,
		ID_NOISEFALLOFF_NOISE_TYPE_VORONOI1 = 26,
		ID_NOISEFALLOFF_NOISE_TYPE_VORONOI2 = 27,
		ID_NOISEFALLOFF_NOISE_TYPE_VORONOI3 = 28,
		ID_NOISEFALLOFF_NOISE_TYPE_ZADA = 29,
		ID_NOISEFALLOFF_NOISE_TYPE_PERLIN = 30,
		ID_NOISEFALLOFF_NOISE_TYPE_RIDGEDMULTIFRACTAL = 31,
	ID_NOISEFALLOFF_NOISE_LOW_CLIP = 6012,
	ID_NOISEFALLOFF_NOISE_HIGH_CLIP = 6013,
	//////////////////////////////////////////////////////////////////////////

	ID_CA_CAPSULEFALLOFF_OBJECT_DUMMY
};

#endif // ONOISEFALLOFF_H__
