#ifndef OPBDSCENE_H__
#define OPBDSCENE_H__

enum
{
	PBDSCENE_DEVICE = 1000,
		PBDSCENE_DEVICE_CPU = 0,
		PBDSCENE_DEVICE_GPU = 1,
	PBDSCENE_SUBSTEPS = 1001,
	PBDSCENE_ITERATIONS = 1002,
	PBDSCENE_COLLISIONPASSES = 1003,
	PBDSCENE_USEDOCUMENT_RANGE = 1004,
	PBDSCENE_SIMULATION_FROM = 1005,
	PBDSCENE_SIMULATION_TO = 1006,
	PBDSCENE_TAGS	= 1007,
	PBDSCENE_FORCES = 1008,
	PBDSCENE_USECCD = 1009,
	PBDSCENE_DAMPING = 1010,
	PBDSCENE_POSTCOLLISIONPASSES = 1011,
	PBDSCENE_POLISHITERATIONS = 1012,
	PBDSCENE_SMOOTHINGITERATIONS = 1013,
	PBDSCENE_CONSTRAINTSOLVER = 1014,
		PBDSCENE_CONSTRAINTSOLVER_JACOBI = 0,
		PBDSCENE_CONSTRAINTSOLVER_GAUSSSEIDEL = 1,
		PBDSCENE_CONSTRAINTSOLVER_GAUSSSEIDELVIVACE = 2,
	PBDSCENE_DEFAULTGRAVITY = 1015,
	PBDSCENE_SCENESCALE = 1016,
	PBDSCENE_EVALUATEBEFOREGENERATORS = 1017
};
#endif // OPBDSCENE_H__