#ifndef OPOLYREDUX_H__
#define OPOLYREDUX_H__

enum
{
	POLYREDUXOBJECT_STRENGTH							= 1000,
	POLYREDUXOBJECT_PRESERVE_3D_BOUNDARY	= 1001,
	POLYREDUXOBJECT_PRESERVE_UV_BOUNDARY	= 1002,
	POLYREDUXOBJECT_TRIANGLE_COUNT 				= 1003,
	POLYREDUXOBJECT_VERTEX_COUNT 					= 1004,
	POLYREDUXOBJECT_NO_REDUCTION					= 1005,
	POLYREDUXOBJECT_REDUCE_BOUNDARY_ANGLE	= 1006,
	POLYREDUXOBJECT_REDUCE_ALL_AS_ONE			= 1007,
	POLYREDUXOBJECT_REMAINING_EDGES_COUNT = 1050
};

#endif // OPOLYREDUX_H__
