#ifndef OSPLINERAIL_H__
#define OSPLINERAIL_H__

enum
{
	SPLINERAILOBJECT_SPLINE1            = 1000,
	SPLINERAILOBJECT_SPLINE2            = 1001,
	SPLINERAILOBJECT_SPLINE3            = 1002,
	SPLINERAILOBJECT_SPLINE4            = 1003,

	SPLINERAILOBJECT_SIZE               = 1004,
	SPLINERAILOBJECT_MODE               = 1008,
		SPLINERAILOBJECT_MODE_LIMIT					= 0,
		SPLINERAILOBJECT_MODE_BOX						= 1,
		SPLINERAILOBJECT_MODE_UNLIMITED			= 2,

	SPLINERAILOBJECT_SCALEBEFORESTART   = 1005,
	SPLINERAILOBJECT_SCALEAFTEREND      = 1006,
	SPLINERAILOBJECT_REFERENCE          = 1007
};

#endif // OSPLINERAIL_H__
