#ifndef OTRANSFORM_PANEL_H__
#define OTRANSFORM_PANEL_H__

enum
{
	// Transform panel starts at 5500
	ID_MG_TRANSFORM_GROUPTRANSFORM		= 5500,
	ID_MG_TRANSFORM_POSITION					= 5501,
	ID_MG_TRANSFORM_SCALE							= 5502,
	ID_MG_TRANSFORM_ROTATE						= 5503,
	ID_MG_TRANSFORM_COLOR							= 5504,
	ID_MG_TRANSFORM_WEIGHT						= 5505,
	ID_MG_TRANSFORM_TIME							= 5506,
	ID_MG_TRANSFORM_GROUPMAPING				= 5507,
	ID_MG_TRANSFORM_GROUPTIME					= 5509,
	ID_MG_TRANSFORM_DISPLAYMODE				= 5511,
	ID_MG_TRANSFORM_DISPLAYMODE_OFF		= 0,
	ID_MG_TRANSFORM_DISPLAYMODE_WEIGHT = 1,
	ID_MG_TRANSFORM_DISPLAYMODE_UV		= 2,
	ID_MG_TRANSFORM_DISPLAYMODE_COLOR = 3,
	ID_MG_TRANSFORM_DISPLAYMODE_INDEX = 4
};
#endif // OTRANSFORM_PANEL_H__
