#ifndef OTRIMMEDSURFACE_H__
#define OTRIMMEDSURFACE_H__

enum
{
	TRIMMEDSURFACE_TYPE								= 1001,
		TRIMMEDSURFACE_TYPE_UNKNOWN			= 0,
		TRIMMEDSURFACE_TYPE_STANDARD		= 1,

	TRIMMEDSURFACE_PRECISION						= 1010,

	ID_TRIMMEDSURFACEPROPERTIES						= 1090
};

#endif // OTRIMMEDSURFACE_H__
