#ifndef PREFSMATERIAL_H__
#define PREFSMATERIAL_H__

enum
{
	PREF_MM_MAIN_GROUP					= 999,
	PREF_MM_SIZE								= 1000,
		PREF_MM_SIZE_SMALL								= 1,
		PREF_MM_SIZE_MED									= 2,
		PREF_MM_SIZE_LARGE								= 3,
		PREF_MM_SIZE_HUGE									= 4,
	PREF_MM_SHSCENE							= 1001,
	PREF_MM_MATSCENE						= 1002,
	PREF_MM_FRATE								= 1003,
	PREF_MM_PREV								= 1004,
	PREF_MM_NODE_PREVIEW_SIZE								= 1005,
		PREF_MM_NODE_PREVIEW_SIZE_SMALL								= 1,
		PREF_MM_NODE_PREVIEW_SIZE_MED									= 2,
		PREF_MM_NODE_PREVIEW_SIZE_LARGE								= 3,
		PREF_MM_NODE_PREVIEW_SIZE_HUGE								= 4,
	PREF_MM_NODE_MAT_PREVIEW_SCENE					= 1007,
	PREF_MM_NODE_NODEPREVIEW__DEPRECATED__	= 1008,
	PREF_MM_NODE_PREVIEWNAME								= 1009,
	PREF_MM_DEFAULT_MATERIAL							= 1010,
	PREF_MM_VP_DEFAULT_SIZE						    = 1011,
		PREF_MM_VP_PREVIEWSIZE_64							  	= 6,
		PREF_MM_VP_PREVIEWSIZE_128								= 7,
		PREF_MM_VP_PREVIEWSIZE_256								= 8,
		PREF_MM_VP_PREVIEWSIZE_512								= 9,
		PREF_MM_VP_PREVIEWSIZE_1024								= 10,
		PREF_MM_VP_PREVIEWSIZE_2048								= 11,
		PREF_MM_VP_PREVIEWSIZE_4096								= 12,
		PREF_MM_VP_PREVIEWSIZE_8192								= 13,
		PREF_MM_VP_PREVIEWSIZE_16384							= 14,

	// Groups
	PREF_MM_MATPREVIEWGROUP					= 2000,
	PREF_MM_NODE_NODEEDITORGROUP		= 2001,
	PREF_MM_MATMANAGERGROUP					= 2002,
	PREF_MM_VIEWPORTGROUP					= 2003,

	PREF_MM_DUMMY
};

#endif // PREFSMATERIAL_H__
