#ifndef TALIGNTOSPLINE_H__
#define TALIGNTOSPLINE_H__

enum
{
	ALIGNTOSPLINETAG_TANGENTIAL				= 1000,
	ALIGNTOSPLINETAG_LINK							= 1001,
	ALIGNTOSPLINETAG_RAIL							= 1002,
	ALIGNTOSPLINETAG_POSITION					=	1003,
	ALIGNTOSPLINETAG_SEGMENT					= 1004,
	ALIGNTOSPLINETAG_AXIS							= 1007,
		ALIGNTOSPLINETAG_AXIS_X							= 0,
		ALIGNTOSPLINETAG_AXIS_Y							= 1,
		ALIGNTOSPLINETAG_AXIS_Z							= 2
};

#endif // TALIGNTOSPLINE_H__
