#ifndef TCAANIMATIONMODIFIER_H__
#define TCAANIMATIONMODIFIER_H__

enum
{
	ID_CA_ANIMATION_MODIFIER_TAG_HIERARCHY = 2001,
	ID_CA_ANIMATION_MODIFIER_TAG_OFFSET = 2002,
	
	ID_CA_ANIMATION_MODIFIER_TAG_POSTERIZE_TIME = 2003,
	ID_CA_ANIMATION_MODIFIER_TAG_POSTERIZE_STRENGTH = 2004,
	ID_CA_ANIMATION_MODIFIER_TAG_POSTERIZE_GROUP = 2005,
	ID_CA_ANIMATION_MODIFIER_TAG_POSTERIZE = 2006,
	
	ID_CA_ANIMATION_MODIFIER_TAG_SPRING_GROUP = 2010,
	ID_CA_ANIMATION_MODIFIER_TAG_SPRING_STRENGTH = 2011,
	ID_CA_ANIMATION_MODIFIER_TAG_SPRING_STIFFNESS = 2012,
	ID_CA_ANIMATION_MODIFIER_TAG_SPRING_DRAG = 2013,
	ID_CA_ANIMATION_MODIFIER_TAG_SPRING_ITERATIONS = 2014,
	ID_CA_ANIMATION_MODIFIER_TAG_SPRING = 2015,
	
	ID_CA_ANIMATION_MODIFIER_TAG_SMOOTH = 2020,
	ID_CA_ANIMATION_MODIFIER_TAG_SMOOTH_STRENGTH = 2021,
	
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE = 2030,
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE_SEED = 2031,
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE_STRENGTH = 2032,
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE_SPEED = 2033,
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE_POSITION = 2034,
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE_ROTATION = 2035,
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE_SCALE = 2036,
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE_ATTRIBUTES = 2037,
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE_USERDATA = 2038,
	ID_CA_ANIMATION_MODIFIER_TAG_NOISE_PLA = 2039,
	
	ID_CA_ANIMATION_MODIFIER_TAG_OUTLIER_REMOVAL = 2050,
	ID_CA_ANIMATION_MODIFIER_TAG_OUTLIER_REMOVAL_SIGMA = 2051,
	ID_CA_ANIMATION_MODIFIER_TAG_OUTLIER_REMOVAL_STRENGTH = 2052,
	
	ID_CA_ANIMATION_MODIFIER_TAG_EXCLUDE = 3000,
	ID_CA_ANIMATION_MODIFIER_TAG_ADD = 3001,
	ID_CA_ANIMATION_MODIFIER_TAG_REMOVE = 3002,
	ID_CA_ANIMATION_MODIFIER_TAG_LINK = 3003,
	ID_CA_ANIMATION_MODIFIER_TAG_TARGETS_GROUP = 3004,
	ID_CA_ANIMATION_MODIFIER_TAG_INCLUDE_TAGS = 3005,
	ID_CA_ANIMATION_MODIFIER_TAG_EXCLUSION_MODE = 3006,
	ID_CA_ANIMATION_MODIFIER_TAG_EXCLUSION_MODE_INCLUDE = 3007,
	ID_CA_ANIMATION_MODIFIER_TAG_EXCLUSION_MODE_EXCLUDE = 3008,
	ID_CA_ANIMATION_MODIFIER_TAG_EXCLUSION_MODE_TRACK = 3009,
	
	ID_CA_ANIMATION_MODIFIER_TAG_TIME_GROUP = 4000,
	ID_CA_ANIMATION_MODIFIER_TAG_TIME_STRETCH = 4001,
	ID_CA_ANIMATION_MODIFIER_TAG_MODE = 4002,
	ID_CA_ANIMATION_MODIFIER_TAG_CREATE_CACHE = 4003,
	ID_CA_ANIMATION_MODIFIER_TAG_CLEAR_CACHE = 4004,
	ID_CA_ANIMATION_MODIFIER_TAG_RANGE = 4005,
	ID_CA_ANIMATION_MODIFIER_TAG_RANGE_START = 4006,
	ID_CA_ANIMATION_MODIFIER_TAG_RANGE_END = 4007,
	ID_CA_ANIMATION_MODIFIER_TAG_CACHE = 4008,
	ID_CA_ANIMATION_MODIFIER_TAG_SMOOTH_SPLINE = 4009,
	ID_CA_ANIMATION_MODIFIER_TAG_SMOOTH_NEIGHBOR = 4010,
	ID_CA_ANIMATION_MODIFIER_TAG_SMOOTH_CACHE_UPDATE = 4011,
	
	ID_CA_ANIMATION_MODIFIER_TAG_CONTAINER = 6500,
	
	ID_CA_ANIMATION_MODIFIER_TAG_TARGET_COUNT = 10000,
	ID_CA_ANIMATION_MODIFIER_TAG_TARGET_END = 19999,
};

#endif // TCAANIMATIONMODIFIER_H__
