#ifndef TMORPH_TARGET_H__
#define TMORPH_TARGET_H__

enum
{
	MORPHTARGETTAG_STRENGTH						= 1000,
	MORPHTARGETTAG_EDITINGMODE				= 1001,
	MORPHTARGETTAG_STORE							= 1002,
	MORPHTARGETTAG_MODE								=	1103,
		MORPHTARGETTAG_MODE_ABSOLUTE			= 0,
		MORPHTARGETTAG_MODE_RELATIVE			= 1,
		MORPHTARGETTAG_MODE_ROTATION			=	2,
	MORPHTARGETTAG_XREF								=	1004,
	MORPHTARGETTAG_STOREPARAM					=	1005,
	MORPHTARGETTAG_STOREDELTA					=	1006,
	MORPHTARGETTAG_ROTPOS							=	1107,
	MORPHTARGETTAG_ROTDIR							=	1108,
	MORPHTARGETTAG_SETROT_FROMEDGE		=	1109,
	MORPHTARGETTAG_SETROT_FROMPOINTS	=	1110
};

#endif // TMORPH_TARGET_H__
