#ifndef TOOLSETSDSWEIGHT_H__
#define TOOLSETSDSWEIGHT_H__

enum
{
	MDATA_SDSWEIGHT_MODE										= 2129,
		MDATA_SDSWEIGHT_MODE_SET									= 0,
		MDATA_SDSWEIGHT_MODE_ADD									= 1,
		MDATA_SDSWEIGHT_MODE_SUB									= 2,
	MDATA_SDSWEIGHT_STRENGTH								= 2130,
	MDATA_SDSWEIGHT_INTERACTIVEMIN					=	2131,
	MDATA_SDSWEIGHT_INTERACTIVEMAX					=	2132,
	MDATA_SDSWEIGTH_SETSTRENGTH 						= 2133,

	MDATA_SDSWEIGHT													= 9999,

	MDATA_SDSWEIGHT_
};

#endif // TOOLSETSDSWEIGHT_H__
