#ifndef TOOLKNIFE_H__
#define TOOLKNIFE_H__

enum
{
	MDATA_KNIFE_MODE			= 1100,	// LONG
	MDATA_KNIFE_SINGLE			= 1101,	// BOOL
	MDATA_KNIFE_SELECTCUTS		= 1102,	// BOOL
	MDATA_KNIFE_NGONS			= 1103,	// BOOL
	MDATA_KNIFE_EDGES			= 1104,	// BOOL
	MDATA_KNIFE_VISIBLEONLY		= 1106, // BOOL
	MDATA_KNIFE_PLANE			= 1107,	// LONG
	MDATA_KNIFE_COORD			= 1108,	// LONG
	MDATA_KNIFE_PLANE_OFFSET	= 1110, // REAL
	MDATA_KNIFE_PLANE_CUTS		= 1111, // LONG
	MDATA_KNIFE_STICKYLOCK		= 1112, // BOOL
	MDATA_KNIFE_PLANE_SPACING	= 1113, // REAL
	MDATA_KNIFE_RESTRICT,
	MDATA_KNIFE_PLANE_SLICING,
	MDATA_KNIFE_CONSTRAIN,
	MDATA_KNIFE_CONSTRAIN_THETA,
	MDATA_KNIFE_LOOP_OFFSET,
	MDATA_GROUP_CUT,
	MDATA_GROUP_CUT_OPTIONS,

	//////////////////////////////////////////////////////////////////////////

	MDATA_KNIFE_MODE_SINGLE = 0,
	MDATA_KNIFE_MODE_MULTI,
	MDATA_KNIFE_MODE_LOOP,
	MDATA_KNIFE_MODE_PLANE,
	MDATA_KNIFE_MODE_PATH,

	MDATA_KNIFE_PLANE_XY = 0,
	MDATA_KNIFE_PLANE_YZ,
	MDATA_KNIFE_PLANE_XZ,

	MDATA_KNIFE_COORD_LOCAL = 0,
	MDATA_KNIFE_COORD_WORLD,
	MDATA_KNIFE_COORD_CAMERA,

	//////////////////////////////////////////////////////////////////////////

	MDATA_KNIFE_
};

#endif // TOOLKNIFE_H__
