#ifndef TOOLEDGESELECTION_H__
#define TOOLEDGESELECTION_H__

enum
{
	MDATA_MWS_OVERRIDE_PHONG = 1004, // Bool
	MDATA_MWS_PHONGGROUP = 1003,
	MDATA_MWS_ANGLE_THRESHOLD = 1000, // Real
	MDATA_MWS_USE_PHONGBREAKS = 1002, // Bool
	MDATA_MWS_EDGEMODE = 1001,  // LONG
	MDATA_MWS_EDGEMODE_LOOP = 1,
	MDATA_MWS_EDGEMODE_GUIDED = 2,
	MDATA_MWS_EDGEMODE_SHARP = 3,
	MDATA_MWS_EDGEMODE_LINE = 4,
	MDATA_MWS_EDGEMODE_LINE2 = 5,
	MDATA_MWS_SP_LENWEIGHT = 1006, // Real
	MDATA_MWS_SP_PHONGWEIGHT = 1010, // Real
	MDATA_MWS_SP_ANGLEWEIGHT = 1007, // Real
	MDATA_MWS_SP_QUADWEIGHT = 1008, // Real
	MDATA_MWS_ADD_TO_SEL = 1009, // Bool

	MWS_BTN_SELECT_ALL = 1011, //Button

	MWS_TAG_GROUP = 2000,
	MWS_TAG_LINK = 2001, // String
	MWS_TAG_SET_SEL = 2002, // Button
	MWS_TAG_ADD_SEL = 2003, // Button
	MWS_TAG_REM_SEL = 2004, // Button
	MWS_TAG_AUTO_SET_SEL = 2005 // Bool
};

#endif // TOOLEDGESELECTION_H__
