#ifndef TOOLEXTRUDE_H__
#define TOOLEXTRUDE_H__

enum
{
	MDATA_EXTRUDE_PRESERVEGROUPS							= 2032, // BOOL
	MDATA_EXTRUDE_OFFSET											= 2033, // REAL
	MDATA_EXTRUDE_VARIANCE										= 2035, // REAL
	MDATA_EXTRUDE_BEVEL												= 2169, // REAL
	MDATA_EXTRUDE_BEVEL_VARIANCE							= 2170, // REAL
	MDATA_EXTRUDE_ANGLE												= 2034, // REAL
	MDATA_EXTRUDE_EDGEANGLE										= 2136, //	REAL
	MDATA_EXTRUDE_EDGESNAP										= 2137, // BOOL
	MDATA_EXTRUDE_EDGESNAPVALUE								= 2138, // REAL
	MDATA_EXTRUDE_KEEPSEL											= 2139, // BOOL
	MDATA_EXTRUDE_SUBDIVISION                 = 2161, // LONG
	MDATA_EXTRUDE_CREATENGONS                 = 2168, // BOOL
	MDATA_EXTRUDE_CREATECAPS                  = 2171, // BOOL

	MDATA_EXTRUDE_POLYGON_GROUP               = 2172, // GROUP
	MDATA_EXTRUDE_EDGE_GROUP              		= 2173, // GROUP
	MDATA_EXTRUDE_POINT_GROUP               	= 2174, // GROUP

	MDATA_EXTRUDE_
};

#endif // TOOLEXTRUDE_H__
