#ifndef TOOL_AXISHELPER_H__
#define TOOL_AXISHELPER_H__

enum
{
	ID_MG_TOOLAXIS_GROUPAXIS		= 1199,
	ID_MG_TOOLAXIS_MODE					= 1200,
	ID_MG_TOOLAXIS_MODE_DISTANCE = 0,
	ID_MG_TOOLAXIS_MODE_AUTO		= 1,
	ID_MG_TOOLAXIS_MODE_OBJECT	= 2,
	ID_MG_TOOLAXIS_TARGETOBJECT = 1201	//LONG
};
#endif // TOOL_AXISHELPER_H__
