#ifndef TOOL_MGLINEAR_H__
#define TOOL_MGLINEAR_H__

enum
{
	MDATA_MGLINEARTOOL_START				= 1100, //VECTOR
	MDATA_MGLINEARTOOL_END					= 1101, //VECTOR
	MDATA_MGLINEARTOOL_COUNT				= 1102, //LONG

	MDATA_MGLINEARTOOL_MODE					= 1110,
	MDATA_MGLINEARTOOL_MODE_CLONE		= 0,
	MDATA_MGLINEARTOOL_MODE_INSTANCE = 1
};
#endif // TOOL_MGLINEAR_H__
