#ifndef TOOLBRIDGE_H__
#define TOOLBRIDGE_H__

enum
{
	MDATA_BRIDGE_MODE_SURFACE = 0,
	MDATA_BRIDGE_MODE_NORMAL = 1,
	MDATA_BRIDGE_MODE_SURFACE_AVERAGE = 2,
	MDATA_BRIDGE_MODE_NORMAL_AVERAGE = 3,

	MDATA_BRIDGE_ELEMENT1				= 1100, //LONG
	MDATA_BRIDGE_ELEMENT2				= 1101, //LONG
	MDATA_BRIDGE_ELEMENT3				= 1102, //LONG
	MDATA_BRIDGE_ELEMENT4				= 1103, //LONG
	MDATA_BRIDGE_OBJINDEX1			= 1104, //LINK
	MDATA_BRIDGE_OBJINDEX2			= 1105, //LINK
	MDATA_BRIDGE_OBJINDEX3			= 1106, //LINK
	MDATA_BRIDGE_OBJINDEX4			= 1107, //LINK
	MDATA_BRIDGE_DELETE					= 1108, //BOOL
	MDATA_BRIDGE_ISO						= 1109, //BOOL
	MDATA_BRIDGE_SUBDIVISION		= 1110, //LONG
	MDATA_BRIDGE_SPIN_STEPS			= 1111, //LONG
	MDATA_BRIDGE_USE_SMART_BRIDGE	= 1114, //BOOL
	MDATA_BRIDGE_FIRST_MODE         = 1116, //LONG
	MDATA_BRIDGE_SECOND_MODE        = 1117, //LONG
	MDATA_BRIDGE_FIRST_FLIP         = 1118, //BOOL
	MDATA_BRIDGE_SECOND_FLIP        = 1119, //BOOL
	MDATA_BRIDGE_TENSION            = 1120, //REAL
	MDATA_BRIDGE_REVERSE            = 1121, //BOOL
	MDATA_BRIDGE_SEPARATE_CONTROLS  = 1122, //BOOL
	MDATA_BRIDGE_RESTRICT 			= 1123, //BOOL
	MDATA_BRIDGE_KEEP_POLYGONS      = 1124, //BOOL
	MDATA_BRIDGE_BOTH_MODE          = 1125, //LONG
	MDATA_BRIDGE_BOTH_FLIP          = 1126, //LONG
	// needed to specify whether the start/end loop should be select only
	MDATA_BRIDGE_FIRST_SELECT_ONLY  = 1127, //BOOL
	MDATA_BRIDGE_SECOND_SELECT_ONLY = 1128, //BOOL
	MDATA_BRIDGE_ONE_SIDED_PATCH    = 1129, //BOOL
};

#endif // TOOLBRIDGE_H__
