#ifndef TOOLHAIRPUSH_H__
#define TOOLHAIRPUSH_H__

enum
{
	HAIR_TOOL_PUSH_DISTANCE = 1000,
	HAIR_TOOL_PUSH_CURVE,
	HAIR_TOOL_PUSH_USE_NORMAL,
	HAIR_TOOL_PUSH_SELECT,
	HAIR_TOOL_PUSH_SURFACE,
	HAIR_TOOL_PUSH_GUIDES,
	HAIR_TOOL_PUSH_GUIDES_DISTANCE,
	HAIR_TOOL_PUSH_GUIDES_RELAX,
	HAIR_TOOL_PUSH_GUIDES_CURVE,

	//////////////////////////////////////////////////////////////////////////

	HAIR_TOOL_PUSH_DUMMY
};

#endif // TOOLHAIRPUSH_H__
