#ifndef TPBDCONSTRAINT_H__
#define TPBDCONSTRAINT_H__

enum
{
	PBD_CONSTRAINT_TAG_RADIUS = 5000,
	PBD_CONSTRAINT_TAG_SAME_OBJECT,
	PBD_CONSTRAINT_TAG_OTHER_OBJECTS,
	PBD_CONSTRAINT_TAG_GENERATE_LIVE,
	PBD_CONSTRAINT_TAG_CREATE,
	PBD_CONSTRAINT_TAG_CLEAR,
	PBD_CONSTRAINT_TAG_CREATEGROUP,
	PBD_CONSTRAINT_TAG_SETTINGS,
	PBD_CONSTRAINT_TAG_STRETCHINESS,
	PBD_CONSTRAINT_TAG_TARGETLENGTH,
	PBD_CONSTRAINT_TAG_TEAR,
	PBD_CONSTRAINT_TAG_TEARPAST,
	PBD_CONSTRAINT_TAG_ALWAYSDRAW,
	PBD_CONSTRAINT_TAG_EXCLUDE_OBJECTS,
	PBD_CONSTRAINT_TAG_POINTSELECTION,
	PBD_CONSTRAINT_TAG_MAXCONNECTIONS,
	//////////////////////////////////////////////////////////////////////////
	PBD_CONSTRAINT_TAG_DUMMY
};

#endif // TPBDCONSTRAINT_H__
