#ifndef TPOLYGONSELECTION_H__
#define TPOLYGONSELECTION_H__

enum
{
	POLYGONSELECTIONTAG_FIELDGROUP			= 2000,			// GROUP
	POLYGONSELECTIONTAG_FIELDS					= 2001,			// FIEDLIST
	POLYGONSELECTIONTAG_ENABLEFIELDS		= 2002,			// BOOL
	POLYGONSELECTIONTAG_FIELDTOLERANCE	= 2003,			// FLOAT
	POLYGONSELECTIONTAG_DEFORMEDSTATE		= 2004,			// BOOL
	POLYGONSELECTIONTAG_FIELDTAB = 2005,

	POLYGONSELECTIONTAG_COMMAND1 = 1000, // virtual ID
	POLYGONSELECTIONTAG_COMMAND2 = 1001,
	POLYGONSELECTIONTAG_COMMAND3 = 1002,
	POLYGONSELECTIONTAG_COMMAND4 = 1003,
	POLYGONSELECTIONTAG_COMMAND5 = 1004,
	POLYGONSELECTIONTAG_COMMAND6 = 1005,
	POLYGONSELECTIONTAG_COMMANDTAB = 1006,
	POLYGONSELECTIONTAG_UPDATE = 1007,
	POLYGONSELECTIONTAG_COUNT = 1008,
	POLYGONSELECTIONTAG_UNHIDEALL = 1009,
	POLYGONSELECTIONTAG_MODIFIERHINT = 1010
	
};

#endif // TPOLYGONSELECTION_H__
