#ifndef TPROTECTION_H__
#define TPROTECTION_H__

enum
{
	PROTECTION_P = 1000,	// Only use SetParameter to change these
	PROTECTION_S,
	PROTECTION_R,

	PROTECTION_P_X,
	PROTECTION_P_Y,
	PROTECTION_P_Z,

	PROTECTION_S_X,
	PROTECTION_S_Y,
	PROTECTION_S_Z,

	PROTECTION_R_X,
	PROTECTION_R_Y,
	PROTECTION_R_Z,

	PROTECTION_P_MIN_X,
	PROTECTION_P_MIN_Y,
	PROTECTION_P_MIN_Z,

	PROTECTION_P_MAX_X,
	PROTECTION_P_MAX_Y,
	PROTECTION_P_MAX_Z,

	PROTECTION_S_MIN_X,
	PROTECTION_S_MIN_Y,
	PROTECTION_S_MIN_Z,

	PROTECTION_S_MAX_X,
	PROTECTION_S_MAX_Y,
	PROTECTION_S_MAX_Z,

	PROTECTION_R_MIN_X,
	PROTECTION_R_MIN_Y,
	PROTECTION_R_MIN_Z,

	PROTECTION_R_MAX_X,
	PROTECTION_R_MAX_Y,
	PROTECTION_R_MAX_Z,

	PROTECTION_ALLOW_EXPRESSIONS,
	PROTECTION_ALLOW_DUPLICATION,

	PROTECTION_ALL_LOCKED = 2000,	// Dummy ID for quickly testing if full PSR is locked

	PROTECTION_DISABLED,
	PROTECTION_EXPRESSIONS_ALLOWED,

	//////////////////////////////////////////////////////////////////////////

	PROTECTION_NONE = 0,
	PROTECTION_LOCK,
	PROTECTION_LIMIT,

	//////////////////////////////////////////////////////////////////////////
	PROTECTION_
};

#endif // TPROTECTION_H__



