#ifndef TVOLUMEBUILDER_H__
#define TVOLUMEBUILDER_H__

enum
{
	ID_VOLUMEBUILDER_OBJECTLINK = 7000,
	ID_VOLUMEBUILDER_TAGTYPE = 7001,
	ID_VOLUMEBUILDER_TAG_RADIUS = 7002,
	ID_VOLUMEBUILDER_TAG_VELOCITY_SCALE = 7003,
	ID_VOLUMEBUILDER_TAG_MAINTAB = 7004,
	ID_VOLUMEBUILDER_TAG_DENSITY = 7005,
	ID_VOLUMEBUILDER_IS_TP_GROUP = 7006,
	ID_VOLUMEBUILDER_LISTFLAGS = 7007,
	ID_VOLUMEBUILDER_ACTIVE = 7008,
	ID_VOLUMEBUILDER_TAG_USEPARTICLERADIUS = 7009,
	ID_VOLUMEBUILDER_TAG_INTERIOR_VOXEL_FALLOFF = 7011,
	ID_VOLUMEBUILDER_TAG_USEPOINTS = 7014,
	ID_VOLUMEBUILDER_TAG_ISO	= 7015,
	ID_VOLUMEBUILDER_TAG_CHILDMODE = 7016,
	ID_VOLUMEBUILDER_TAG_BBSIZE = 7017,
	ID_VOLUMEBUILDER_TAG_BBROTATION = 7018,
	ID_VOLUMEBUILDER_TAG_FIELD_CREATION_REF = 7019,
	ID_VOLUMEBUILDER_TAG_SOURCETYPE = 7020,
		ID_VOLUMEBUILDER_TAG_SOURCETYPE_PREVIOUS = 0,
		ID_VOLUMEBUILDER_TAG_SOURCETYPE_BOUNDINGBOX = 1,
		ID_VOLUMEBUILDER_TAG_SOURCETYPE_SHAPE = 2,
	ID_VOLUMEBUILDER_TAG_MESHRADIUS = 7021,
	ID_VOLUMEBUILDER_TAG_OPTIMIZEANDCLOSE = 7022,
	ID_VOLUMEBUILDER_TAG_INFINITEFALLOFF = 7023,
	ID_VOLUMEBUILDER_TAG_PERFECT_PRIMITIVE = 7024,
	ID_VOLUMEBUILDER_TAG_VECTOR_CONVERSION_MODE = 7025,
		ID_VOLUMEBUILDER_TAG_VECTOR_CONVERSION_MODE_SDF = 0,
		ID_VOLUMEBUILDER_TAG_VECTOR_CONVERSION_MODE_FOG = 1,
		ID_VOLUMEBUILDER_TAG_VECTOR_CONVERSION_MODE_UDF = 2,
	ID_VOLUMEBUILDER_TAG_HALF_BAND_MESH_INTERIOR = 7026,
	ID_VOLUMEBUILDER_TAG_HALF_BAND_MESH_EXTERIOR = 7027,
	ID_VOLUMEBUILDER_TAG_HALF_BAND_SPLINE = 7028,
	ID_VOLUMEBUILDER_TAG_HALF_BAND_PARTICLE = 7029,
	ID_VOLUMEBUILDER_TAG_SPLINERADIUS_SCALESPLINE = 7030,
	ID_VOLUMEBUILDER_TAG_SPLINERADIUS_PERSEGMENT = 7031,
	ID_VOLUMEBUILDER_TAG_BBPOSITION = 7032,
	ID_VOLUMEBUILDER_TAG_BB = 7033,
	ID_VOLUMEBUILDER_TAG_CREATE_CONTROLLER = 7034
};

#endif // TVOLUMEBUILDER_H__