#ifndef VP_DENOISING_H__
#define VP_DENOISING_H__

enum
{
	VP_DENOISER_ADDRAWLAYER           = 1000,
	VP_DENOISER_ADDRAWLAYER_INFO      = 1007,
	
	VP_DENOISER_PASSES_INFO		= 2001,
	VP_DENOISER_USE_PASSES		= 2002,
	
	VP_DENOISER_ALBEDO_TYPE									= 2100,
	VP_DENOISER_ALBEDO_TYPE_ALBEDO 				 	= 0,
	VP_DENOISER_ALBEDO_TYPE_MATERIAL_COLOR 	= 1,
	
	VP_DENOISER_GROUP    		= 3000,
	VP_DENOISER_INFO_GROUP    	= 3001
	
	
};

#endif // VP_DENOISING_H__
