#ifndef XBEVELTOOL_H__
#define XBEVELTOOL_H__

enum
{
	MDATA_BEVEL_GROUP_OPTION								= 1000,
	MDATA_BEVEL_GROUP_POLYGON								= 1100,
	MDATA_BEVEL_GROUP_SHAPING								= 1200,
	MDATA_BEVEL_GROUP_TOPOLOGY							= 1300,

	MDATA_BEVEL_MASTER_MODE									= 1100,
		MDATA_BEVEL_MASTER_MODE_CHAMFER				= 0,
		MDATA_BEVEL_MASTER_MODE_SOLID					= 1,

	MDATA_BEVEL_OFFSET_MODE									= 1001,
		MDATA_BEVEL_OFFSET_MODE_FIXED					= 0,
		MDATA_BEVEL_OFFSET_MODE_RADIAL				= 1,
		MDATA_BEVEL_OFFSET_MODE_PROPORTIONAL	= 2,

	MDATA_BEVEL_RADIUS											= 1002,
	MDATA_BEVEL_SUB													= 1003,
	MDATA_BEVEL_DEPTH												= 1004,
	MDATA_BEVEL_LIMIT												= 1005,

	MDATA_BEVEL_EXTRUSION										= 1101,
	MDATA_BEVEL_POLY_ANGLE									= 1102,
	MDATA_BEVEL_GROUP												= 1103,

	MDATA_BEVEL_SHAPING_MODE								= 1201,
		MDATA_BEVEL_SHAPING_MODE_ROUND				= 0,
		MDATA_BEVEL_SHAPING_MODE_USER					= 1,
		MDATA_BEVEL_SHAPING_MODE_PROFILE			= 2,

	MDATA_BEVEL_SHAPING_TENSION							= 1202,
	MDATA_BEVEL_SHAPING_SYMMETRY						= 1203,
	MDATA_BEVELL_SHAPING_CONSTANT						= 1204,
	MDATA_BEVEL_SHAPING_SPLINE							= 1205,
	MDATA_BEVEL_SHAPING_SPLINE_LINK					= 1206,

	MDATA_BEVEL_SHAPING_SPLINE_PLANE				= 1207,
		MDATA_BEVEL_SHAPING_SPLINE_PLANE_XY		= 0,
		MDATA_BEVEL_SHAPING_SPLINE_PLANE_XZ		= 1,
		MDATA_BEVEL_SHAPING_SPLINE_PLANE_ZY		= 2,

	MDATA_BEVEL_SHAPING_EXTR								= 1208,

	MDATA_BEVEL_MITERING										= 1301,
		MDATA_BEVEL_MITERING_DEFAULT					= 0,
		MDATA_BEVEL_MITERING_UNIFORM					= 1,
		MDATA_BEVEL_MITERING_RADIAL						= 3,
		MDATA_BEVEL_MITERING_PATCH						= 4,

	MDATA_BEVEL_CORNER_ENDING								= 1302,
		MDATA_BEVEL_CORNER_ENDING_DEFAULT			= 0,
		MDATA_BEVEL_CORNER_ENDING_EXTEND			= 1,
		MDATA_BEVEL_CORNER_ENDING_INSET				= 2,

	MDATA_BEVEL_PROUNDING_TYPE							= 1303,
		MDATA_BEVEL_PROUNDING_TYPE_FLAT				= 0,
		MDATA_BEVEL_PROUNDING_TYPE_FULL				= 1,
		MDATA_BEVEL_PROUNDING_TYPE_CONVEX			= 2,

	MDATA_BEVEL_CORNER_NGON									= 1304,
	MDATA_BEVEL_ROUNDING_NGON								= 1305,

	MDATA_BEVEL_SELECTION_PHONG_BREAK				= 1306,
	MDATA_BEVEL_SELECTION_PHONG_BREAK_M			= 1307,
};

#endif // XBEVELTOOL_H__

