#ifndef XOCIO_H__
#define XOCIO_H__

enum
{
	OCIOSHADER_COLOR												= 1000,
	OCIOSHADER_TEXTURE											= 1001,

	OCIOSHADER_CONFIG												= 1002,
	OCIOSHADER_INPUT_COLORSPACE							= 1003,
	OCIOSHADER_OUTPUT_COLORSPACE						= 1004,

	OCIOSHADER_TRANSFORM_COLOR							= 1005,
	OCIOSHADER_TRANSFORM_TEXTURE						= 1006,

	OCIOSHADER_MULTIPLIER										= 1007,
	OCIOSHADER_USE_DOCUMENT_SETTINGS				= 1008,
};

#endif // XOCIO_H__
