#ifndef XSTAR_H__
#define XSTAR_H__

enum
{
	STARSHADER_COLOR1				= 1000, // VECTOR
	STARSHADER_COLOR2 			= 1001, // VECTOR
	STARSHADER_STREAKS			= 1002,	// LONG
	STARSHADER_INNERRADIUS	= 1003,	// REAL
	STARSHADER_OUTERRADIUS	= 1004,	// REAL
	STARSHADER_DENSITY			= 1005	// LONG
};

#endif // XSTAR_H__
