#ifndef _VMD_CAM_OBJ_H_
#define _VMD_CAM_OBJ_H_
enum
{
	VMD_CAM_OBJ_GRP = 1000,
	FRAME_ON,
	CURVE_TYPE,	
		XCURVE = 0,
		YCURVE = 1,
		ZCURVE = 2,
		RCURVE = 3,
		DCURVE = 4,
		VCURVE = 5,
		ACURVE = 6,
	VMD_CAM_OBJ_SPLINE = 1003,
	INIT_CURVE_BUTTON,
	REGISTER_CURVE_BUTTON,
	UPDATE_CURVE_BUTTON,
	DELETE_CURVE_BUTTON,

};

#endif _VMD_CAM_OBJ_H_