VMD_CAM_IMPORT_SIZE: 8.5
VMD_CAM_IMPORT_OFFSET: 0
VMD_CAM_EXPORT_SIZE: 8.5
VMD_CAM_EXPORT_OFFSET: 0
VMD_CAM_EXPORT_USE_BAKE: true
VMD_CAM_EXPORT_ROTATION_TWEEN: 0
VMD_CAM_CONVER_DIS: 0
VMD_CAM_CONVER_ROTATION_TWEEN: 0
VMD_MOT_IMPORT_SIZE: 8.5
VMD_MOT_IMPORT_OFFSET: 0
VMD_MOT_EXPORT_ROTATION_TWEEN: 0
VMD_MOT_IMPORT_MOTION: true
VMD_MOT_IMPORT_MORPH: true
VMD_MOT_IMPORT_MODEL_INFO: true
VMD_MOT_IMPORT_DELETE_PREVIOUS_ANIMATION: true
VMD_MOT_IMPORT_DETAIL: false
VMD_MOT_EXPORT_SIZE: 8.5
VMD_MOT_EXPORT_OFFSET: 0
VMD_MOT_EXPORT_MOTION: true
VMD_MOT_EXPORT_MORPH: true
VMD_MOT_EXPORT_MODEL_INFO: true
VMD_MOT_EXPORT_USE_BAKE: true
PMX_MOD_IMPORT_SIZE: 8.5
PMX_MOD_IMPORT_POLYGON: true
PMX_MOD_IMPORT_NORMAL: true
PMX_MOD_IMPORT_UV: true
PMX_MOD_IMPORT_MATERIAL: true
PMX_MOD_IMPORT_BONE: true
PMX_MOD_IMPORT_WEIGHTS: true
PMX_MOD_IMPORT_IK: true
PMX_MOD_IMPORT_INHERIT: true
PMX_MOD_IMPORT_EXPRESSION: true
PMX_MOD_IMPORT_MULTIPART: true
PMX_MOD_IMPORT_ENGLISH: false
PMX_MOD_IMPORT_ENGLISH_CHECK: false