VMD_CAM_IMPORT_SIZE: 8.5
VMD_CAM_IMPORT_OFFSET: 0
VMD_CAM_EXPORT_SIZE: 8.5
VMD_CAM_EXPORT_OFFSET: 0
VMD_CAM_EXPORT_ROTATION_TWEEN: 0
VMD_CAM_CONVER_DIS: 0
VMD_CAM_CONVER_ROTATION_TWEEN: 0
VMD_MOT_IMPORT_SIZE: 8.5
VMD_MOT_IMPORT_OFFSET: 0
VMD_MOT_IMPORT_QUAT: true
VMD_MOT_IMPORT_DETAIL: false
VMD_MOT_IMPORT_BY_TAG: true
PMX_MOD_IMPORT_SIZE: 8.5
PMX_MOD_IMPORT_POLYGON: true
PMX_MOD_IMPORT_NORMAL: true
PMX_MOD_IMPORT_UV: true
PMX_MOD_IMPORT_MATERIAL: true
PMX_MOD_IMPORT_BONE: true
PMX_MOD_IMPORT_WEIGHTS: true
PMX_MOD_IMPORT_IK: true
PMX_MOD_IMPORT_INHERIT: true
PMX_MOD_IMPORT_EXPRESSION: true
PMX_MOD_IMPORT_MULTIPART: false
PMX_MOD_IMPORT_ENGLISH: false
PMX_MOD_IMPORT_ENGLISH_CHECK: false