#ifndef FAIEXPORT_H__
#define FAIEXPORT_H__

enum
{
	TUAIEXPORT_MAIN_GROUP = 999,
	TUAIEXPORT_OUTPUTSIZE = 1000,
	TUAIEXPORT_OUTPUTSIZE_WIDTH,
	TUAIEXPORT_OUTPUTSIZE_HEIGHT,
	TUAIEXPORT_SCALE,
	TUAIEXPORT_BACKFACECULL,
	TUAIEXPORT_POLYSUBDIV,
	TUAIEXPORT_POLYSUBDIV_LEVEL,
	TUAIEXPORT_EXPORTLINES,
	TUAIEXPORT_EXPORTSURFACE,
	TUAIEXPORT_ZSORT,
	TUAIEXPORT_SHADING,
	TUAIEXPORT_OVERFILL,
	TUAIEXPORT_LINEOPACITY,
	TUAIEXPORT_LINETHICKNESS,
	TUAIEXPORT_LINEPATTERNS,
	TUAIEXPORT_LINECONNECTIONS,
	TUAIEXPORT_GROUP,
	TUAIEXPORT_ANIMATION,
	TUAIEXPORT_FRAMES,
	TUAIEXPORT_FRAME_START,
	TUAIEXPORT_FRAME_END,
	TUAIEXPORT_ANIMTYPE,
	TUAIEXPORT_FRAME_RATE,
	TUAIEXPORT_LAYERS,

//
	TUAIEXPORT_ANIMTYPE_FILES = 0,
	TUAIEXPORT_ANIMTYPE_LAYERS,

	TUAIEXPORT_OUTPUTSIZE_RENDER = 0,
	TUAIEXPORT_OUTPUTSIZE_EDITOR,
	TUAIEXPORT_OUTPUTSIZE_CUSTOM,

	TUAIEXPORT_FRAMES_ALL = 0,
	TUAIEXPORT_FRAMES_RENDER,
	TUAIEXPORT_FRAMES_MANUAL,

	TUAIEXPORT_GROUP_OBJECT = 0,
	TUAIEXPORT_GROUP_MATERIAL,

	TUAIEXPORT_SHADING_OBJECTCOL = 0,
	TUAIEXPORT_SHADING_UNIFORM,
	TUAIEXPORT_SHADING_FACETTED,

	TUAIEXPORT_ZSORT_BACK = 0,
	TUAIEXPORT_ZSORT_CENTER,
	TUAIEXPORT_ZSORT_FRONT,

	TUAIEXPORT_GROUP_BASIC = 2000,
	TUAIEXPORT_GROUP_LINES,
	TUAIEXPORT_GROUP_SURFACE,
	TUAIEXPORT_GROUP_ANIMATION,
};

#endif // FAIEXPORT_H__



