#ifndef FALEMBICIMPORT_H__
#define FALEMBICIMPORT_H__

enum
{
	ABCIMPORT_GROUP				= 999,
	ABCIMPORT_STR_GENERAL = 1000,
	ABCIMPORT_VISIBILITY,
	ABCIMPORT_STR_OPTIONS,
	ABCIMPORT_NORMALS,
	ABCIMPORT_UVS,
	ABCIMPORT_FACESETS,
	ABCIMPORT_CAMERAS,
	ABCIMPORT_SUBD,
	ABCIMPORT_CURVES,
	ABCIMPORT_POINTS,
	ABCIMPORT_SCALE,
	ABCIMPORT_STR_ANIMATION,
	ABCIMPORT_FPS,
	ABCIMPORT_STARTFRAME,
	ABCIMPORT_NOSTARTFRAME,
	ABCIMPORT_CURVES_NONE,
	ABCIMPORT_CURVES_SPLINES,
	ABCIMPORT_CURVES_HAIR,
	ABCIMPORT_POINTS_NONE,
	ABCIMPORT_POINTS_TPARTICLES,
	ABCIMPORT_POINTS_GEOMETRY,
	ABCIMPORT_COLORMAPS,
	ABCIMPORT_SUBD_NO_SDS,
	ABCIMPORT_INTERPOLATION,
	ABCIMPORT_OTHERATTR,
	ABCIMPORT_SUBD_BOTH_WEIGHTS,
	ABCIMPORT_SUBD_NO_WEIGHTS
};

#endif // FALEMBICIMPORT_H__


