#ifndef FDXFIMPORT_H__
#define FDXFIMPORT_H__

enum
{
	DXFIMPORTFILTER_GROUP						= 999,
	DXFIMPORTFILTER_SCALE						= 2000,
	DXFIMPORTFILTER_FROZEN					= 2001,
	DXFIMPORTFILTER_ELEMENTS2D			= 2002,
	DXFIMPORTFILTER_ALIGN						= 2003,
	DXFIMPORTFILTER_TRIANGULATE			= 2004,
	DXFIMPORTFILTER_LAYER						= 2005,
		DXFIMPORTFILTER_LAYER_NONE				= 0,
		DXFIMPORTFILTER_LAYER_BYLAYER			= 1,
		DXFIMPORTFILTER_LAYER_BYCOLOR			= 2,
	DXFIMPORTFILTER_CIRCLESEGMENTS	= 2006
};

#endif // FDXFIMPORT_H__
