#ifndef FFBXEXPORT_H__
#define FFBXEXPORT_H__

enum
{
	FBXEXPORT_GROUP = 999,
	STR_QUALITY = 1000,

	STR_TEXTURE_EXPORT,

	FBXEXPORT_GRP_GENERAL,
	FBXEXPORT_SCALE,
	FBXEXPORT_TRACKS,
	FBXEXPORT_TEXTURES,

	FBXEXPORT_GRP_TEXTURES,
	FBXEXPORT_EMBED_TEXTURES,

	FBXEXPORT_GRP_DEBUG,
	FBXEXPORT_CLONE_OBJECTS,

	FBXEXPORT_GRP_GEOMETRY,
	FBXEXPORT_SAVE_NORMALS,
	FBXEXPORT_SAVE_VERTEX_MAPS_AS_COLORS,
	FBXEXPORT_TRIANGULATE,
	FBXEXPORT_SDS_SUBDIVISION,

	FBXEXPORT_ASCII,

	FBXEXPORT_GRP_ANIMATION,

	FBXEXPORT_BAKE_ALL_FRAMES,
	FBXEXPORT_PLA_TO_VERTEXCACHE,

	FBXEXPORT_LIGHTS,
	FBXEXPORT_CAMERAS,
	FBXEXPORT_SPLINES,

	FBXEXPORT_GRP_ADDITIONAL,

	FBXEXPORT_FBX_VERSION = 1023,
			FBX_EXPORTVERSION_NATIVE	= 0,	// momentarily 7.5
			FBX_EXPORTVERSION_6_1_0		= 1,	// version 6.1 to export old animation system
			FBX_EXPORTVERSION_7_1_0	  = 2,	// version 7.1
			FBX_EXPORTVERSION_7_2_0	  = 3,	// version 7.2
			FBX_EXPORTVERSION_7_3_0	  = 4,	// version 7.3
			FBX_EXPORTVERSION_7_4_0	  = 5,	// version 7.4

	FBXEXPORT_SAVE_VERTEX_COLORS = 1024,
	FBXEXPORT_SDS,

	FBXEXPORT_SUBSTANCES,
	FBXEXPORT_SELECTION_ONLY,
	FBXEXPORT_GLOBAL_MATRIX,
	FBXEXPORT_LOD_SUFFIX,
	
	FBXEXPORT_INSTANCES,
	
	FBXEXPORT_FLIP_Z_AXIS,
	
	FBXEXPORT_UP_AXIS,
			FBXEXPORT_UP_AXIS_Y,
			FBXEXPORT_UP_AXIS_X,
			FBXEXPORT_UP_AXIS_Z
};

#endif // FFBXEXPORT_H__


