#ifndef FFBXIMPORT_H__
#define FFBXIMPORT_H__

enum
{
	FBXIMPORT_GROUP				= 999,
	FBXIMPORT_GRP_GENERAL = 1000,
	FBXIMPORT_SCALE,
	FBXIMPORT_GEOMETRY,
	FBXIMPORT_LIGHTS,
	FBXIMPORT_CAMERAS,
	FBXIMPORT_MARKERS,
	FBXIMPORT_TRACKS,
	FBXIMPORT_TEXTURES,

	FBXIMPORT_GRP_GEOMETRY,
	FBXIMPORT_SHAPES,
	FBXIMPORT_NORMALS,
	FBXIMPORT_COLORS_AS_VERTEX_MAPS,

	FBXIMPORT_GRP_ADDITIONAL,
	FBXIMPORT_ACTIVATE_JOINTS,
	FBXIMPORT_KEEP_JOINT_REST_POSE,
	FBXIMPORT_USE_CURRENT_POSE,

	FBXIMPORT_CLEAN_TRACKS,
	FBXIMPORT_CONVERT_TO_PHONGTAG,
	FBXIMPORT_VERTEXCACHE_TO_PLA,
	FBXIMPORT_SINGLE_MAT_SELECTIONTAGS,

	FBXIMPORT_GRP_ANIMATION,

	FBXIMPORT_CURVES,

	FBXIMPORT_COLORS,
	FBXIMPORT_SDS,

	FBXIMPORT_SUBSTANCES,
	FBXIMPORT_INSTANCES,
	
	FBXIMPORT_FLIP_Z_AXIS,
	
	FBXIMPORT_UP_AXIS,
			FBXIMPORT_UP_AXIS_DEFAULT,
			FBXIMPORT_UP_AXIS_X,
			FBXIMPORT_UP_AXIS_Y,
			FBXIMPORT_UP_AXIS_Z
};

#endif // FFBXIMPORT_H__


