#ifndef FLGRADIENT_H__
#define FLGRADIENT_H__

enum
{
	FIELDLAYER_GRADIENT_SOURCE = 1000,	// INT CYCLE
	FIELDLAYER_GRADIENT_GRADIENT = 1001,	// GRADIENT
	FIELDLAYER_GRADIENT_CYCLE = 1002,	// BOOL
	FIELDLAYER_GRADIENT_OFFSET = 1003,	// REAL
	FIELDLAYER_GRADIENT_ANIMATIONSPEED = 1004,	// BASETIME
	FIELDLAYER_GRADIENT_SCALE = 1005,	// FLOAT

	FIELDLAYER_GRADIENT_SOURCE_VALUE = 0,
	FIELDLAYER_GRADIENT_SOURCE_COLOR = 1,
	FIELDLAYER_GRADIENT_SOURCE_DIRECTION = 2,

	FIELDLAYER_GRADIENT_DUMMY
};
#endif	// #FLGRADIENT_H__

