#ifndef FLSOLID_H__
#define FLSOLID_H__

enum
{
	FIELDLAYER_SOLID_VALUE = 1000,				// FLOAT
	FIELDLAYER_SOLID_COLOR = 1001,				// COLOR
	FIELDLAYER_SOLID_DIRECTION = 1002,		// VECTOR

	FIELDLAYER_SOLID_DUMMY
};
#endif	// #FLSOLID_H__

