#ifndef FTORUS_H__
#define FTORUS_H__

enum
{
	// Falloff controls
	FIELD_TORUS_RADIUS = 1000,	// Float
	FIELD_TORUS_THICKNESS = 1001,	// Float
	FIELD_TORUS_SLICE_DEPRECATED = 1002,	// Float
	FIELD_TORUS_CLIP = 1003,	// Boolean
	FIELD_TORUS_DIRECTION = 1005,	// Int Cycle

	// Need to keep all those to match with LINEAR_DIRECTION_XX
	FIELD_TORUS_DIRECTION_XP = 0,
	FIELD_TORUS_DIRECTION_XN = 1,
	FIELD_TORUS_DIRECTION_YP = 2,
	FIELD_TORUS_DIRECTION_YN = 3,
	FIELD_TORUS_DIRECTION_ZP = 4,
	FIELD_TORUS_DIRECTION_ZN = 5
};
#endif	// FTORUS_H__
