#ifndef FVRML2IMPORT_H__
#define FVRML2IMPORT_H__

enum
{
	VRML2IMPORTFILTER_GROUP							= 999,
	VRML2IMPORTFILTER_SCALE							= 2000,
	VRML2IMPORTFILTER_OPTIMIZE					= 2001,
	VRML2IMPORTFILTER_OPTIMIZESTRUCTURE	= 2002,
	VRML2IMPORTFILTER_USENORMALS				= 2003
};

#endif // FVRML2IMPORT_H__
