#ifndef MGRADIALARRAY_H__
#define MGRADIALARRAY_H__

enum
{
	MG_RADIAL_COUNT			= 1240,
	MG_RADIAL_STARTANGLE = 1241,
	MG_RADIAL_ENDANGLE	= 1242,
	MG_RADIAL_OFFSET		= 1243,
	MG_RADIAL_RANDOM		= 1244,
	MG_RADIAL_SEED			= 1245,
	MG_RADIAL_RADIUS		= 1246,
	MG_RADIAL_AXIS			= 1247,
	MG_RADIAL_AXIS_XY		= 0,
	MG_RADIAL_AXIS_ZY		= 1,
	MG_RADIAL_AXIS_XZ		= 2,
	MG_RADIAL_ORIENT		= 1248
};
#endif // MGRADIALARRAY_H__
