#ifndef OALEMBICGENERATOR_H__
#define OALEMBICGENERATOR_H__

enum
{
	ALEMBIC_PATH = 1000,
	ALEMBIC_IDENTIFIER,
	ALEMBIC_OVERRIDE_FOR_RENDERING,
	ALEMBIC_PATH_FOR_RENDERING,
	ALEMBIC_IDENTIFIER_FOR_RENDERING,

	ALEMBIC_ANIMATION_OFFSET,
	ALEMBIC_ANIMATION_RESET,

	ALEMBIC_UPDATE_XFORM,
	ALEMBIC_UPDATE_GEOMETRY,

	ALEMBIC_PATH_STATE,
	ALEMBIC_IDENT_STATE,
	ALEMBIC_PATH_STATE_RENDERING,
	ALEMBIC_IDENT_STATE_RENDERING,

	ALEMBIC_STR_RENDERING,
	ALEMBIC_STR_UPDATE,

	ALEMBIC_UNIT_SCALE,

	ALEMBIC_USE_VISIBILITY,
	ALEMBIC_USE_NORMALS,
	ALEMBIC_USE_UVS,
	ALEMBIC_USE_FACESETS,

	ALEMBIC_USE_ORIGINAL_PATH,
	ALEMBIC_USE_COLORMAPS,
	ALEMBIC_USE_SDSWEIGHTS,

	ALEMBIC_SDS_WEIGHT_SCALE,
	ALEMBIC_INTERPOLATION,

	ALEMBIC_USE_OTHERATTR,

	ALEMBIC_STR_ANIMATION,
	ALEMBIC_USE_ANIMATION,
	ALEMBIC_ANIMATION_SPEED,
	ALEMBIC_ANIMATION_CURVE,
	ALEMBIC_GRP_ANIMATION_REMAPPING,

	ALEMBIC_ANIMATION_FRAME,

	ALEMBIC_ANIMATION_MODE,
		ALEMBIC_ANIMATION_MODE_PLAY = 0,
		ALEMBIC_ANIMATION_MODE_LOOP = 1,
		ALEMBIC_ANIMATION_MODE_PINGPONG = 2
};

#endif // OALEMBICGENERATOR_H__



