#ifndef OCASTEP_H__
#define OCASTEP_H__

enum
{
	ID_CA_OBJECT_STEP_DISPLAY = 1000,
	ID_CA_OBJECT_STEP_HUB_LINK,
	ID_CA_OBJECT_STEP_TARGET_LINK,
	ID_CA_OBJECT_STEP_STEP,
	ID_CA_OBJECT_STEP_WIDTH,
	ID_CA_OBJECT_STEP_HEIGHT,
	ID_CA_OBJECT_STEP_DISPLAY_PLANE,
	ID_CA_OBJECT_STEP_STEP_MODE,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_OBJECT_STEP_DISPLAY_NONE = 0,
	ID_CA_OBJECT_STEP_DISPLAY_RECT,
	ID_CA_OBJECT_STEP_DISPLAY_CIRCLE,

	ID_CA_OBJECT_STEP_DISPLAY_PLANE_XY = 0,
	ID_CA_OBJECT_STEP_DISPLAY_PLANE_ZY,
	ID_CA_OBJECT_STEP_DISPLAY_PLANE_XZ,

	ID_CA_OBJECT_STEP_STEP_MODE_HOLDER = 0,
	ID_CA_OBJECT_STEP_STEP_MODE_STEPS,
	ID_CA_OBJECT_STEP_STEP_MODE_STEP,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_OBJECT_STEP_DUMMY
};

#endif // OCASTEP_H__
