#ifndef OERANDOMIZE_H__
#define OERANDOMIZE_H__

enum
{
	MGRANDOMEFFECTOR_SEED						= 1100,
	MGRANDOMEFFECTOR_MODE						= 1101,
	MGRANDOMEFFECTOR_MODE_RANDOM		= 0,
	MGRANDOMEFFECTOR_MODE_GAUSIAN		= 1,
	MGRANDOMEFFECTOR_MODE_NOISE			= 2,
	MGRANDOMEFFECTOR_MODE_TURBULENCE = 3,
	MGRANDOMEFFECTOR_MODE_SORT			= 4,
	MGRANDOMEFFECTOR_SYNC						= 1102,
	MGRANDOMEFFECTOR_SPACE					= 5000,
	MGRANDOMEFFECTOR_SPACE_GLOBAL		= 0,
	MGRANDOMEFFECTOR_SPACE_OBJECT		= 1,
	MGRANDOMEFFECTOR_SPEED					= 5501,
	MGRANDOMEFFECTOR_MODE_NOISE_GRP = 5502,
	MGRANDOMEFFECTOR_SCALE					= 5503,
	MGRANDOMEFFECTOR_INDEXED				= 5504
};
#endif // OERANDOMIZE_H__
