#ifndef OESOUNDDEPRECIATED_H__
#define OESOUNDDEPRECIATED_H__

enum
{
	MGSOUNDEFFECTOR_FILE					= 1100,
	MGSOUNDEFFECTOR_PLAY					= 1101,
	MGSOUNDEFFECTOR_START					= 1102,
	MGSOUNDEFFECTOR_FREQ					= 1103,
	MGSOUNDEFFECTOR_BANDWIDTH			= 1104,
	MGSOUNDEFFECTOR_FILTER				= 1105,
	MGSOUNDEFFECTOR_SCRUB					= 1106,
	MGSOUNDEFFECTOR_FILTERSHAPE		= 1107,
	MGSOUNDEFFECTOR_LCHANNEL			= 1108,
	MGSOUNDEFFECTOR_RCHANNEL			= 1109,
	MGSOUNDEFFECTOR_LOWERLIMIT		= 1110,
	MGSOUNDEFFECTOR_MODE					= 1111,
	MGSOUNDEFFECTOR_MODE_PEAK			= 0,
	MGSOUNDEFFECTOR_MODE_AVE			= 1,
	MGSOUNDEFFECTOR_MODE_COMP			= 2,
	MGSOUNDEFFECTOR_FALLOFF				= 1112,
	MGSOUNDEFFECTOR_GRAPH					= 1113,
	MGSOUNDEFFECTOR_MULTIPLIER		= 1114,
	MGSOUNDEFFECTOR_MGMODE				= 1115,
		MGSOUNDEFFECTOR_MGMODE_ALL	=	0,
		MGSOUNDEFFECTOR_MGMODE_STEP	= 1,
	MGSOUNDEFFECTOR_COLORGRADIENT = 1116,
	MGSOUNDEFFECTOR_CLAMP					= 1117
};
#endif // OESOUND_H__
