#ifndef OFRACTURE_H__
#define OFRACTURE_H__

enum
{
	FRACTURE_INPUT_POINTS = 1000,
	FRACTURE_STYLE,
	FRACTURE_GAP,
	FRACTURE_SHELL,
	FRACTURE_COLORIZE,
	FRACTURE_SHOWDELAUNAY,
	FRACTURE_SHOWVORONOI,
	FRACTURE_SHOWCLIPPED,
	FRACTURE_CREATENGONS,
	FRACTURE_CREATEPOINTS,
	FRACTURE_CREATEDPOINTAMOUNT,
	FRACTURE_VOXELRESSURF,
	FRACTURE_VOXELRESCELLS,
	FRACTURE_FILLINTERIOR,
	FRACTURE_MERGEPOINTS,
	FRACTURE_THREADCOUNT

};

#endif	// OFRACTURE_H__
