#ifndef OP_BLURP_H__
#define OP_BLURP_H__

#include "gvbase.h"

enum
{
	OP_BLURP_OBJECTS		= 1000,
	OP_BLURP_PHASE			= 1001,
	OP_BLURP_NOFRAG			= 1002,
	OP_BLURP_TYPE				= 1003,
	OP_BLURP_SANGLE			=	1004,
	OP_BLURP_SRAD				= 1005,
	OP_BLURP_FROMTO			= 1006,
	OP_BLURP_COUNT			= 1007,
	OP_BLURP_THICK			= 1008,
	OP_BLURP_RTYPE			= 1009,
	OP_BLURP_RTHICK			= 1010,
	OP_BLURP_INTANGENT	= 1011,
	OP_BLURP_OUTTANGENT	= 1012,
	OP_BLURP_STAY				= 1013,
	OP_BLURP_FRAG				= 1014,
	OP_BLURP_NEXT				= 1015,


	OP_BLURP_FROMTO_NZ_PZ = 0,
	OP_BLURP_FROMTO_PZ_NZ	= 1,
	OP_BLURP_FROMTO_NY_PY	= 2,
	OP_BLURP_FROMTO_PY_NY	= 3,
	OP_BLURP_FROMTO_NX_PX	= 4,
	OP_BLURP_FROMTO_PX_NX	= 5,

	OP_BLURP_TYPE_FACE		= 0,
	OP_BLURP_TYPE_SMOOTH	= 1,
	OP_BLURP_TYPE_COUNT		= 2,

	OP_BLURP_RTYPE_NONE		= 0,
	OP_BLURP_RTYPE_HOLLOW	= 1,
	OP_BLURP_RTYPE_SOLID	= 2,

	OP_BLURP_IN_ON							= 2000,
	OP_BLURP_IN_ATIME						= 2001,

	OP_BLURP_OUT_REMAINING			= 3000,
	OP_BLURP_OUT_REMAININGCOUNT	= 3001,
	OP_BLURP_OUT_REMAININGNUM		= 3002,
	OP_BLURP_OUT_FRAGMENT				= 3010,
	OP_BLURP_OUT_FRAGMENTCOUNT	= 3011,
	OP_BLURP_OUT_FRAGMENTNUM		= 3012
};




#endif // OP_BLURP_H__
