#ifndef OPOINTDISTRIBUTION_H__
#define OPOINTDISTRIBUTION_H__

enum
{
	POINT_DISTRIBUTION_GROUP_DEPRECATED = 5000,
	POINT_DISTRIBUTION_COUNT,
	POINT_DISTRIBUTION_MEMORY_DEPRECATED,
	POINT_DISTRIBUTION_CHANNEL_MODE,
	POINT_DISTRIBUTION_OFFSETX,
	POINT_DISTRIBUTION_OFFSETY,
	POINT_DISTRIBUTION_OFFSETZ,
	POINT_DISTRIBUTION_ENABLE,
	POINT_DISTRIBUTION_PRIORITY,
	POINT_DISTRIBUTION_UPDATE_DEPRECATED,
	POINT_DISTRIBUTION_ENABLESPARSE,
	POINT_DISTRIBUTION_ANGLE,

	POINT_DISTRIBUTION_CHANNEL_GROUP = 6000,

	POINT_DISTRIBUTION_DISTRIBUTION_GROUP = 7000,
	POINT_DISTRIBUTION_DISTRIBUTION_MODE,
	POINT_DISTRIBUTION_DISTRIBUTION_SUBGROUP,
	POINT_DISTRIBUTION_DISTRIBUTION_MODEID,
	POINT_DISTRIBUTION_DISTRIBUTION_CUSTOMIZE,

	POINT_DISTRIBUTION_REDISTRIBUTION_GROUP_DEPRECATED = 8000,
	POINT_DISTRIBUTION_REDISTRIBUTION_MODE_DEPRECATED,
	POINT_DISTRIBUTION_REDISTRIBUTION_SUBGROUP_DEPRECATED,
	POINT_DISTRIBUTION_REDISTRIBUTION_MODEID_DEPRECATED,
	POINT_DISTRIBUTION_REDISTRIBUTION_CUSTOMIZE_DEPRECATED,

	POINT_DISTRIBUTION_VARIOUS_GROUP = 9000,
	POINT_DISTRIBUTION_MEMORY,
	POINT_DISTRIBUTION_UPDATE,
	POINT_DISTRIBUTION_ALWAYS_UPDATE,


	// ENUMS

	POINT_DISTRIBUTION_CHANNEL_MODE_NONE = 0,
	POINT_DISTRIBUTION_CHANNEL_MODE_SIN,
	POINT_DISTRIBUTION_CHANNEL_MODE_TAN,
	POINT_DISTRIBUTION_CHANNEL_MODE_PARA,
	POINT_DISTRIBUTION_CHANNEL_MODE_LINE,
	POINT_DISTRIBUTION_CHANNEL_MODE_STEP,
	POINT_DISTRIBUTION_CHANNEL_MODE_GRID,
	POINT_DISTRIBUTION_CHANNEL_MODE_FLOWER,

	POINT_DISTRIBUTION_DISTRIBUTION_MODE_NONE = 0,
};

#endif // OPOINTDISTRIBUTION_H__
