#ifndef OVOLUMESET_H__
#define OVOLUMESET_H__

enum
{
	ID_VOLUMESET_PATH = 6000,
	ID_VOLUMESET_VOLUMESLIST = 6001,
	ID_VOLUMESET_STATS_STRING = 6002,
	ID_VOLUMESET_SAVE = 6003,
	ID_VOLUMESET_RELOAD = 6004,
	ID_VOLUMESET_FILELINK = 6005,
	ID_VOLUMESET_PATH_ABSOLUTE = 6006,
	ID_VOLUMESET_DETACH = 6007
};

#endif // OVOLUME_H__
