#ifndef PREFSBROWSER_H__
#define PREFSBROWSER_H__

enum
{
	PREF_BROWSER_MAIN_GROUP				= 999,
	PREF_BROWSER_HOME							= 1000,
	PREF_BROWSER_BASICGROUP				= 1001,
	PREF_BROWSER_SCAN							= 1002,
	PREF_BROWSER_SHOWFOLDER				= 1003,
	PREF_BROWSER_SORTRESULT				= 1004,
	PREF_BROWSER_PREVIEWTIMEOUT		= 1005,
	PREF_BROWSER_PREVIEWGROUP			= 1006,
	PREF_BROWSER_PREVIEWCOMP			= 1007,
		PREF_BROWSER_PREVIEWCOMP_LOW		= 1,
		PREF_BROWSER_PREVIEWCOMP_MED		= 2,
		PREF_BROWSER_PREVIEWCOMP_HIGH		= 3,
	PREF_BROWSER_PREVIEWRENDER		= 1008,
	PREF_BROWSER_PREVIEWDISPLAY		= 1009,
	PREF_BROWSER_HOMEBUTTON				= 1010,
	PREF_BROWSER_PREVIEWWIDTH			= 1011,
	PREF_BROWSER_PREVIEWHEIGHT		= 1012,

	PREF_BROWSER_SIZESTR					= 2001,
	PREF_BROWSER_SEKSTR						= 2002,

	PREFS_BROWSER_DUMMY
};

#endif // PREFSBROWSER_H__
