#ifndef PREFSVIEW_H__
#define PREFSVIEW_H__

enum
{
	PREFS_VIEW_GROUP							= 900,

	PREF_VIEW_REDRAWTIME					= 1000,
	PREF_VIEW_FULLANIMREDRAW			= 1001,
	PREF_VIEW_MONITORASPECT				= 1006,
	PREF_VIEW_COLORPROFILE				= 1007,
	PREF_VIEW_REALTIME						= 1008,
	PREF_VIEW_WARNING							= 1009,
	PREF_VIEW_REALTIME_MATERIAL		= 1010,

	PREF_VIEW_DUMMY
};

#endif // PREFSVIEW_H__
