#ifndef PREFSCOMMUNICATION_H__
#define PREFSCOMMUNICATION_H__

enum
{
	PREF_COMMUNICATION_MAINGROUP								= 999,
	PREF_COMMUNICATION_UPDATEGROUP							= 1012,
	PREF_COMMUNICATION_BUGREPORTS								= 1003,

	PREF_COMMUNICATION_UPDATE_AUTO							= 1000,
	PREF_COMMUNICATION_UPDATE_AUTO_DEVELOPER		= 1004,
	PREF_COMMUNICATION_UPDATE_BETASERVER				= 1999,

	PREF_COMMUNICATION_METRICS				= 1012,
	PREF_COMMUNICATION_METRICSGROUP				= 1013,
	PREF_COMMUNICATION_METRICS_HEADLINE			= 1014,
	PREF_COMMUNICATION_METRICS_DISABLE_CHECKBOX		= 1015,
	PREF_COMMUNICATION_METRICS_PREFSMETRICSPREFERENCES	= 1016,
	PREF_COMMUNICATION_METRICS_GOTO_PREFERENCE_DIRECTORY	= 1020,
	PREF_COMMUNICATION_METRICS_GOTO_SERVER_LOCATION		= 1021,

	PREF_COMMUNICATION_LIVELINK_ENABLED = 1022,
	PREF_COMMUNICATION_LIVELINK_PORT = 1023,
	PREF_COMMUNICATION_LIVELINK = 1024,
	PREF_COMMUNICATION_LIVELINKGROUP = 1025,

	PREF_COMMUNICATION_QUICKSTART_DIALOG = 1030,

	PREF_COMMUNICATION_DUMMY
};

#endif // PREFSCOMMUNICATION_H__
