#ifndef PREFSOPENGL_H__
#define PREFSOPENGL_H__

enum
{
	PREF_OPENGL_MAIN_GROUP							= 999,
	PREF_OPENGL_TEXTUREMODE							= 1000,
		PREF_OPENGL_TEXTUREMODE_NEAREST		= 0,
		PREF_OPENGL_TEXTUREMODE_LINEAR		= 1,
		PREF_OPENGL_TEXTUREMODE_MIPMAP		= 2,
	PREF_OPENGL_ANTIALIAS								= 1001,
	PREF_OPENGL_MAXTRANS								= 1003,
	PREF_OPENGL_MAXLIGHT								= 1004,
	PREF_OPENGL_MAXSHAD									= 1005,
	PREF_OPENGL_SHOWCAP									= 1006,
	PREF_OPENGL_USE_SHADER_CACHE				= 1008,
	PREF_OPENGL_VIEWPORT_DITHERING			= 1009,
	PREF_OPENGL_GROUP_MINIMAL_SETTINGS	= 1010,
	PREF_OPENGL_LOAD_PREVIOUS						= 1011,
	PREF_OPENGL_SAVE_AS_STARTUP					= 1012,
	PREF_OPENGL_UVEDITOR_ANTIALIAS			= 1013,

	PREF_OPENGL_WARNING									= 1999,

	PREF_OPENGL_DUMMY,
};

#endif // PREFSOPENGL_H__
