#ifndef SBPOLYNOM_H__
#define SBPOLYNOM_H__

enum
{
	POLYNOMSURFACE_UCLOSED								= 1101,
	POLYNOMSURFACE_VCLOSED								= 1102,
	POLYNOMSURFACE_UDEGREE								= 1103,
	POLYNOMSURFACE_VDEGREE								= 1104,
	POLYNOMSURFACE_UPOINTCOUNT							= 1105,
	POLYNOMSURFACE_VPOINTCOUNT							= 1106
};

#endif // SBPOLYNOM_H__
