#ifndef SCLIENT_H__
#define SCLIENT_H__

enum
{
	SCLIENT_MACHINEID = 1000,
	SCLIENT_IPADDRESS,
	SCLIENT_COMPUTER,
	SCLIENT_USER,
	SCLIENT_SERIALPACKAGE,
	SCLIENT_VERSION,
	SCLIENT_LASTLOGIN,
	SCLIENT_LASTSEEN,
	SCLIENT_VALIDUNTIL,
	SCLIENT_BLOCKED,
	SCLIENT_CONNECTIONS,
	SCLIENT_LOGINS,
	SCLIENT_TIMEDIFF,
	SCLIENT_GROUP,
	SCLIENT_NOTES
};

#endif // SCLIENT_H__
