#ifndef TOOLRANDOMIZE_H__
#define TOOLRANDOMIZE_H__

enum
{
	MDATA_RANDOMIZE_MOVE						= 1000,
	MDATA_RANDOMIZE_SCALE,
	MDATA_RANDOMIZE_ROTATE,
	MDATA_RANDOMIZE_SEED,

	MDATA_RANDOMIZE_
};

#endif // TOOLRANDOMIZE_H__
