#ifndef TOOLSCULPTBRUSHPROJECT_H__
#define TOOLSCULPTBRUSHPROJECT_H__

enum
{
	ToolSculptBrushProject_Start = 20000,
	MDATA_SCULPTBRUSH_PROJECT_OBJECTS = 20001,
	MDATA_SCULPTBRUSH_PROJECT_DIRMODE = 20002,
		MDATA_SCULPTBRUSH_PROJECT_DIRMODE_NORMAL = 0,
		MDATA_SCULPTBRUSH_PROJECT_DIRMODE_X = 1,
		MDATA_SCULPTBRUSH_PROJECT_DIRMODE_Y = 2,
		MDATA_SCULPTBRUSH_PROJECT_DIRMODE_Z = 3,
	MDATA_SCULPTBRUSH_PROJECT_FITNEAREST = 20003,
	MDATA_SCULPTBRUSH_PROJECT_FLOOD = 20004,
};

#endif	// TOOLSCULPTBRUSHPROJECT_H__
