#ifndef TOOLVW_H__
#define TOOLVW_H__

enum
{
	VW_OPTIONS			= 1000,
	VW_SCALE,
	VW_SPEEDS,
	VW_RECORD,
	VW_RECORD_WRITE_SPLINE,
	VW_RECORD_WRITE_CAMERA,
	VW_RECORD_CAMERA,
	VW_HUD_DISPLAY,
	VW_SHORTCUT_KEYS,

	/////
	VW_MODE			= 1010,
	VW_SCALE_MODE,
	VW_SCALE_RANGE,
	VW_ROTATION_MODE,
	VW_EYEHEIGHT,
	VW_STAIRS_THR_PERC,
	VW_FALLING_THR_PERC,
	VW_COLLISION_THR_PERC,
	VW_STAIRS_THR,
	VW_FALLING_THR,
	VW_COLLISION_THR,
	VW_ACCELERATION_POS,
	VW_ACCELERATION_ROT,
	VW_ACCELERATION_ZOOM,
	VW_MOVEMENT_SPEED,
	VW_MOUSE_SPEED,
	VW_TURN_SPEED,
	VW_BANK_SPEED,
	VW_HEADANGLE,
	VW_REFERENCE,
	VW_STOP_AT_WALLS,
	VW_STOP_AT_WALLS_LOW,
	VW_KEEP_EYE_LEVEL,
	VW_NO_COLLISIONS_WALLS,
	VW_NO_COLLISIONS_FLOOR,
	VW_COLLISIONS_BB,
	VW_MOMENTUM,
	VW_OPTIMIZED_MODE_START,
	VW_OPTIMIZED_MODE_STOP,
	VW_SET_EYE_LEVEL_GROUND,
	VW_SET_EYE_LEVEL_FLOOR,
	VW_RECORD_PROGRESS,
	VW_RECORD_SECOND_PASS,
	VW_RECORD_RESET,
	VW_RECORD_START,
	VW_RECORD_STOP,
	VW_WRITE_SPLINE_INTERVAL,
	VW_WRITE_SPLINE_CREATE,
	VW_WRITE_SPLINE_CAMERA_START,
	VW_WRITE_SPLINE_CAMERA_END,
	VW_WRITE_SPLINE_CAMERA_LINK,
	VW_WRITE_SPLINE_CAMERA_BUILD,
	VW_WRITE_CAMERA_INTERVAL,
	VW_WRITE_CAMERA_TIME,
	VW_WRITE_CAMERA_CREATE,
	VW_CAMERA_LINK,
	VW_CAMERA_PROGRESS,
	VW_CAMERA_FRAMES,
	VW_CAMERA_TIME,
	VW_CAMERA_START,
	VW_CAMERA_STOP,
	VW_KEY_PROFILE,

	/////
	VW_VERSION			= 1090,

	/////
	VW_DISPLAY_CROSS		= 1300,
	VW_DISPLAY_COLLISIONS,
	VW_DISPLAY_COMPASS,
	VW_DISPLAY_RECORDING,
	VW_DISPLAY_STAIRS,
	VW_DISPLAY_FALLING,
	VW_DISPLAY_COLLISION,

	//////
	VW_MODE_WALK			= 1400,
	VW_MODE_FLY,
	VW_MODE_TANK,

	/////
	VW_SCALE_MODE_RATIOS		= 1410,
	VW_SCALE_MODE_FIXED,

	/////
	VW_SCALE_01			= 1420,
	VW_SCALE_1,
	VW_SCALE_10,
	VW_SCALE_100,
	VW_SCALE_1000,

	/////
	VW_ROTATION_MODE_HEAD	= 1430,
	VW_ROTATION_MODE_BODY,

	/////
	VW_SPLINE_MODE_STOPED		= 1440,
	VW_SPLINE_MODE_START,
	VW_SPLINE_MODE_RECORD,

	/////
	VW_CAMERA_MODE_STOPED	= 1450,
	VW_CAMERA_MODE_RECORDING,

	/////
	VW_GIZMO_HIDDEN		= 1460,
	VW_GIZMO_EYE_LEVEL,
	VW_GIZMO_STAIR_THR,
	VW_GIZMO_FALLING_THR,
	VW_GIZMO_COLLISION_THR,

	/////
	VW_DISPLAY_GIZMO_NEVER	= 1470,
	VW_DISPLAY_GIZMO_ADJUSTED,
	VW_DISPLAY_GIZMO_ALWAYS,

	/////
	VW_KEY_MOVE_FORWARD		= 1500,
	VW_KEY_MOVE_BACKWARD,
	VW_KEY_MOVE_LEFT,
	VW_KEY_MOVE_RIGHT,
	VW_KEY_MOVE_UP,
	VW_KEY_MOVE_DOWN,
	VW_KEY_LOOK_TURN_LEFT,
	VW_KEY_LOOK_TURN_RIGHT,
	VW_KEY_BANK_LEFT,
	VW_KEY_BANK_RIGHT,
	VW_KEY_ZOOM_IN,
	VW_KEY_ZOOM_OUT,
	VW_KEY_SPEED_UP,
	VW_KEY_SLOW_DOWN,
	VW_KEY_RECORDING_START,
	VW_KEY_RECORDING_STOP,
	VW_KEY_KEEP_EYE_LEVEL,

	/////
	VW_KEY_A			= 1900,
	VW_KEY_B,
	VW_KEY_C,
	VW_KEY_D,
	VW_KEY_E,
	VW_KEY_F,
	VW_KEY_G,
	VW_KEY_H,
	VW_KEY_I,
	VW_KEY_J,
	VW_KEY_K,
	VW_KEY_L,
	VW_KEY_M,
	VW_KEY_N,
	VW_KEY_O,
	VW_KEY_P,
	VW_KEY_Q,
	VW_KEY_R,
	VW_KEY_S,
	VW_KEY_T,
	VW_KEY_U,
	VW_KEY_V,
	VW_KEY_W,
	VW_KEY_X,
	VW_KEY_Y,
	VW_KEY_Z,
	VW_KEY_UP,
	VW_KEY_DOWN,
	VW_KEY_RIGHT,
	VW_KEY_LEFT,
	VW_KEY_PGUP,
	VW_KEY_PGDOWN,
	VW_KEY_HOME,
	VW_KEY_END,
	VW_KEY_INSERT,
	VW_KEY_DELETE,
	VW_KEY_PLUS,
	VW_KEY_MINUS,

	/////
	VW_KEY_PROFILE_NONE		= 1980,
	VW_KEY_PROFILE_STANDARD,
	VW_KEY_PROFILE_ARROWS,

	/////
	VW_DUMMY
};

#endif // TOOLVW_H__
