#ifndef TOOLHAIRSELECTION_H__
#define TOOLHAIRSELECTION_H__

enum
{
	HAIR_SELECTION_MODE = 1000,
	HAIR_SELECTION_SELECT,
	HAIR_SELECTION_INVERT,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SELECTION_MODE_NEW = 0,
	HAIR_SELECTION_MODE_ADD,
	HAIR_SELECTION_MODE_REMOVE,

	HAIR_SELECTION_SELECT_UNROOTED = 0,
	HAIR_SELECTION_SELECT_INTERSECTING,
	HAIR_SELECTION_SELECT_ZERO,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SELECTION_DUMMY
};

#endif // TOOLHAIRSELECTION_H__
