#ifndef TOOLSMOOTHSHIFT_H__
#define TOOLSMOOTHSHIFT_H__

enum
{
	MDATA_SMOOTHSHIFT_ANGLE					= 1100,   // Real
	MDATA_SMOOTHSHIFT_OFFSET				= 1101,   // Real
	MDATA_SMOOTHSHIFT_VARIANCE			= 1102,   // Real
	MDATA_SMOOTHSHIFT_SUBDIVISION		= 1103,   // LONG
	MDATA_SMOOTHSHIFT_CREATENGONS		= 1104,   // Bool

	MDATA_SMOOTHSHIFT_
};

#endif // TOOLSMOOTHSHIFT_H__
