#ifndef TOOLHAIRSYMMETRY_H__
#define TOOLHAIRSYMMETRY_H__

enum
{
	HAIR_SYMMETRY = 1000,
	HAIR_SYMMETRY_PLANE,
	HAIR_SYMMETRY_SEARCH,
	HAIR_SYMMETRY_COORDS,
	HAIR_SYMMETRY_LINK,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SYMMETRY_PLANE_XY = 0,
	HAIR_SYMMETRY_PLANE_XZ,
	HAIR_SYMMETRY_PLANE_YZ,

	HAIR_SYMMETRY_COORDS_WORLD = 0,
	HAIR_SYMMETRY_COORDS_LOCAL,
	HAIR_SYMMETRY_COORDS_OBJECT,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SYMMETRY_DUMMY
};

#endif // TOOLHAIRSYMMETRY_H__
