#ifndef TOOLKNIFEPATH_H__
#define TOOLKNIFEPATH_H__

enum
{
	MDATA_KNIFEPATH_MODE = 4000,
	MDATA_KNIFEPATH_OFFSET_MODE,
	MDATA_KNIFEPATH_OFFSET,
	MDATA_KNIFEPATH_DISTANCE,
	MDATA_KNIFEPATH_CUT_NUMBER,

 	MDATA_KNIFEPATH_SELECTED,
	MDATA_KNIFEPATH_SELECT_CUT,
	MDATA_KNIFEPATH_CUTPOLYS,

	MDATA_KNIFEPATH_INTERACTION_GROUP,

	MDATA_KNIFEPATH_INTERACTION_STORE_LAYOUT,
	MDATA_KNIFEPATH_INTERACTION_BIDIRECTIONAL,
	MDATA_KNIFEPATH_INTERACTION_SYMETRY,
	MDATA_KNIFEPATH_INTERACTION_DIRECTION,
	MDATA_KNIFEPATH_INTERACTION_STOP_AT_NGON,
	MDATA_KNIFEPATH_INTERACTION_STOP_AT_POLE,

	MDATA_KNIFEPATH_QUANTIZE_EDGE_SUB,
	MDATA_KNIFEPATH_QUANTIZE_EDGE_SUB_NUMBER,
	MDATA_KNIFEPATH_LIMITED_RANGE,
	MDATA_KNIFEPATH_RANGE_NUMBER,

	MDATA_KNIFEPATH_SHAPING_GROUP,

	MDATA_KNIFEPATH_PRESERVE_CURVATURE,
	MDATA_KNIFEPATH_PRESERVE_CURVATURE_TENSION,

	MDATA_KNIFEPATH_SPLINE_USE,
	MDATA_KNIFEPATH_SPLINE_EXTRUSION,
	MDATA_KNIFEPATH_SPLINE,

	MDATA_KNIFEPATH_MODE_LOOP = 0,
	MDATA_KNIFEPATH_MODE_PATH,

	MDATA_KNIFEPATH_OFFSET_MODE_PROPORTIONAL = 0,
	MDATA_KNIFEPATH_OFFSET_MODE_EDGEDISTANCE,

	MDATA_KNIFEPATH_EDGEINDEX = 5000,			// Int32
	MDATA_KNIFEPATH_OBJ,									// Link
	MDATA_KNIFEPATH_EDGELENGTH,						// Float
	MDATA_KNIFEPATH_VA,										// Vector
	MDATA_KNIFEPATH_VB,										// Vector

	MDATA_KNIFEPATH_OFFSETS, 							// BASECONTAINER
	MDATA_KNIFEPATH_OFFSETS_COUNT = 900, 	// Int32 number of items
	MDATA_KNIFEPATH_OFFSETS_FIRST = 1000,	// Float start the actual float values
	MDATA_KNIFEPATH_
};

#endif // TOOLKNIFEPATH_H__
