#ifndef TOOLPOLYPEN_H__
#define TOOLPOLYPEN_H__

enum
{
	MDATA_POLYPEN_QUADSTRIP				= 1100,
	MDATA_POLYPEN_AUTOWELD				= 1102,
	MDATA_POLYPEN_REPROJECT				= 1105,
	MDATA_POLYPEN_POLYPAINTSIZE		= 1106,
	MDATA_POLYPEN_ARCSUBDIVISION	= 1107,
	MDATA_POLYPEN_ARCANGLE				=	1108,
	MDATA_POLYPEN_ALLOWEDGEDRAG		=	1109,
	MDATA_POLYPEN_CREATENGONS			=	1110,
	MDATA_POLYPEN_HALFCIRCLE			= 1111,
	MDATA_POLYPEN_CREATEEDGEEXTRUED		= 1112,
	MDATA_POLYPEN_EXCLUSIVEMODE		= 1113,
		MDATA_POLYPEN_EXCLUSIVEMODE_POINTEDGEPOLYS = 0,
		MDATA_POLYPEN_EXCLUSIVEMODE_POINT = 1,
		MDATA_POLYPEN_EXCLUSIVEMODE_EDGE = 2,
		MDATA_POLYPEN_EXCLUSIVEMODE_POLY = 3,
		MDATA_POLYPEN_EXCLUSIVEMODE_USEMODE = 4,

	MDATA_POLYPEN_DRAWMODE 				= 1120,
		MDATA_POLYPEN_DRAWMODE_POINTS = 0,
		MDATA_POLYPEN_DRAWMODE_EDGES = 1,
		MDATA_POLYPEN_DRAWMODE_POLYGONS = 2,
};

#endif // TOOLPOLYPEN_H__
