#ifndef TSUNEXPRESSION_H__
#define TSUNEXPRESSION_H__

enum
{
	SUNEXPRESSIONTAG_LATITUDE					= 1000,
	SUNEXPRESSIONTAG_DISTANCE					= 1003,
	SUNEXPRESSIONTAG_DATETIME					= 1004,
	SUNEXPRESSIONTAG_LONGITUDE				= 1005,
	SUNEXPRESSIONTAG_INTERPOLATE_TIME = 1006,
	SUNEXPRESSIONTAG_INTERPOLATE_DATE = 1007,
	SUNEXPRESSIONTAG_SETLIGHTCOLOR		= 1008
};

#endif // TSUNEXPRESSION_H__
