#ifndef TVERTEXMAP_H__
#define TVERTEXMAP_H__

enum
{
	// tag fields
	ID_TAGFIELDGROUP			= 804,
	ID_TAGFIELDS					= 805,
	ID_TAGFIELD_ENABLE		= 806,
	ID_TAGFIELD_DEFORMED	= 807
};

#endif // TVERTEXMAP_H__
