#ifndef VPNORMALPASS_H__
#define VPNORMALPASS_H__

enum
{
	VP_NORMALPASS_INFO											= 10000,		// STATICTEXT
	VP_NORMALPASS_FLIP											= 10001,		// LONG CYCLE
		VP_NORMALPASS_FLIP_RGB									= 1,				// CYCLE OPTION
		VP_NORMALPASS_FLIP_RBG									= 2,				// CYCLE OPTION
		VP_NORMALPASS_FLIP_GBR									= 3,				// CYCLE OPTION
		VP_NORMALPASS_FLIP_GRB									= 4,				// CYCLE OPTION
		VP_NORMALPASS_FLIP_BGR									= 5,				// CYCLE OPTION
		VP_NORMALPASS_FLIP_BRG									= 6,				// CYCLE OPTION
	VP_NORMALPASS_SPACE											= 10002,		// LONG CYCLE
		VP_NORMALPASS_SPACE_WORLD								= 1,				// CYCLE OPTION
		VP_NORMALPASS_SPACE_CAMERA							= 2,				// CYCLE OPTION
		VP_NORMALPASS_SPACE_OBJECT							= 3,				// CYCLE OPTION
	VP_NORMALPASS_INVERTZ										= 10003			// BOOL
};

#endif // VPNORMALPASS_H__
