#ifndef CKVALUE_H__
#define CKVALUE_H__

enum
{
	ID_VKEY_PROPERTIES		= 807,
	ID_VKEY_TIME					= 901,
	ID_VKEY_MUTE					= 902,

	ID_CKEY_VALUE					= 910,

	// values
	ID_CKEY_TIME_LEFT			= 911,
	ID_CKEY_TIME_RIGHT		= 912,

	ID_CKEY_VALUE_LEFT		= 913,
	ID_CKEY_VALUE_RIGHT		= 914,

	// value limits
	ID_CKEY_BREAK        = 915,

	ID_CKEY_LOCK_O				= 917,
	ID_CKEY_LOCK_L				= 918,

	// modes
	ID_CKEY_AUTO		   		= 919,

	//ID_CKEY_ZERO_O				= 921,
	//ID_CKEY_ZERO_L				= 922,

	ID_CKEY_CLAMP					= 923,

	ID_CKEY_INTER					= 924,
		ID_CKEY_SPLINE    = 1,
		ID_CKEY_LINEAR    = 2,
		ID_CKEY_STEP      = 3,


	ID_VKEY_LOCK_T				= 925,
	ID_CKEY_LOCK_V				= 926,

	ID_CKEY_KEEPVISUALANGLE = 927,

	ID_VKEY_BREAKDOWN     = 1234,
	ID_VKEY_BREAKDOWNCOLOR = 1235,

	ID_CKEY_AUTOMODE	= 1240,
		ID_CKEY_CLASSIC     = 1,
		ID_CKEY_FIXEDSLOPE  = 2,

	ID_CKEY_WEIGHTEDTANGENT	= 1244,
	ID_CKEY_REMOVEOVERSHOOT = 1245,
	ID_CKEY_AUTOWEIGHT = 1246,

	ID_CKEY_PRESET	= 1247,
		ID_CKEY_PRESET_CLASSICAUTO = 1,
		ID_CKEY_PRESET_NEWAUTO = 2,
		ID_CKEY_PRESET_NEWAUTOWEIGHTED = 3,
		ID_CKEY_PRESET__CUSTOM = 4,

	ID_CKEY_QUAT_INTER = 1248,
	  ID_CKEY_QUAT_SPLINE = 1,
		ID_CKEY_QUAT_LINEAR = 2,
		ID_CKEY_QUAT_CUBIC = 3,

	ID_CKEY_
};

#endif // CKVALUE_H__
