#ifndef CTBASE_H__
#define CTBASE_H__

enum
{
	ID_CTRACK_PROPERTIES			= 807,

	ID_CTRACK_NAME 						= 900,
	ID_CTRACK_FCURVE_COLOR 		= 901,
	ID_CTRACK_FCURVE_OFFSET 	= 902,
	ID_CTRACK_FCURVE_SCALE 		= 903,
	ID_CTRACK_ANIMOFF					= 904,
	ID_CTRACK_ANIMSOLO				= 905,
	ID_CTRACK_FCURVE_PAN	 		= 906,
	ID_CTRACK_FCURVE_ZOOM		 	= 907,

	ID_CTRACK_TIME            = 909,
	ID_CTRACK_BEFORE          = 910,
	ID_CTRACK_AFTER           = 911,
		ID_CTRACK_OFF          = 0,
		ID_CTRACK_CONSTANT     = 1,
		ID_CTRACK_CONTINUE     = 2,
		ID_CTRACK_REPEAT       = 3,
		ID_CTRACK_OFFSETREPEAT = 4,
		ID_CTRACK_OSCILLATE    = 5,

	ID_CTRACK_REGION_TIME1	 	= 912,
	ID_CTRACK_REGION_TIME2	 	= 913,
	ID_CTRACK_REGION_FC1	 	  = 914,
	ID_CTRACK_REGION_FC2	 	  = 915,

	ID_CTRACK_FCURVE_HLE_MIN  = 916,
	ID_CTRACK_FCURVE_HLE_MAX  = 917,

	ID_CTRACK_CONSTANTVELOCITY_V = 918, // use SetParameter!!!
	ID_CTRACK_USE_PREF			  = 919,
	ID_CTRACK_TIME_RELATIVE   = 920,
	ID_CTRACK_BEFORE_CNT      = 922,
	ID_CTRACK_AFTER_CNT       = 923,

	ID_CTRACK_
};

#endif // CTBASE_H__

