#ifndef FAIIMPORT_H__
#define FAIIMPORT_H__

enum
{
	AIIMPORTFILTER_GROUP					= 999,
	AIIMPORTFILTER_SCALE					= 2000,
	AIIMPORTFILTER_GROUPSPLINES		= 2001,
	AIIMPORTFILTER_CONNECTSPLINES	= 2002
};

#endif // FAIIMPORT_H__
