#ifndef FCOLLADA14EXPORT_H__
#define FCOLLADA14EXPORT_H__

enum
{
	COLLADA_EXPORT_GROUP				= 999,
	COLLADA_EXPORT_SCALE        = 2001,
	COLLADA_EXPORT_2D_GEOMETRY  = 2002,
	COLLADA_EXPORT_ANIMATION    = 2003,
	COLLADA_EXPORT_TRIANGLES    = 2004
};

#endif // FCOLLADA14EXPORT_H__
