#ifndef FLFORMULA_H__
#define FLFORMULA_H__

enum
{
	// Falloff controls
	FORMULAFIELDLAYER_STRING			= 1000,		// String
	FORMULAFIELDLAYER_GRP					= 1001,		// Group
	FORMULAFIELDLAYER_HELP01			= 1002,		// Statictext
	FORMULAFIELDLAYER_HELP02			= 1003,		// Statictext
	FORMULAFIELDLAYER_HELP03			= 1004,		// Statictext
	FORMULAFIELDLAYER_HELP04			= 1005,		// Statictext
	FORMULAFIELDLAYER_HELP06			= 1006,		// Statictext
	FORMULAFIELDLAYER_HELP07			= 1007,		// Statictext
	FORMULAFIELDLAYER_HELP08			= 1008,		// Statictext
	FORMULAFIELDLAYER_TIME				= 1009,		// Real
	FORMULAFIELDLAYER_FREQ				= 1010,		// Real
	FORMULAFIELDLAYER_HELP05			= 1011,		// Statictext
};
#endif // FLFORMULA_H__
