#ifndef FLWIMPORT_H__
#define FLWIMPORT_H__

enum
{
	LWIMPORTFILTER_GROUP						= 999,
	LWIMPORTFILTER_SCALE						= 2000,
	LWIMPORTFILTER_TEXTURES					= 2001,
	LWIMPORTFILTER_LIGHTS						= 2002,
	LWIMPORTFILTER_SPLITOBJECTS			= 2003
};

#endif // FLWIMPORT_H__
