#ifndef GVDYNSPRING_H__
#define GVDYNSPRING_H__

#include "gvdyninteraction.h"

enum
{
	SPRING_NODE_INPUT_LINEAR_PLASTIC_ELONGATION = 10151,
	SPRING_NODE_INPUT_ANGULAR_PLASTIC_ELONGATION = 10152,

	SPRING_NODE_OUTPUT_LINEAR_PLASTIC_ELONGATION = 10251,
	SPRING_NODE_OUTPUT_ANGULAR_PLASTIC_ELONGATION = 10252,
};

#endif // GVDYNSPRING_H__
