#ifndef OATOMARRAY_H__
#define OATOMARRAY_H__

enum
{
	ATOMARRAYOBJECT_CRAD		= 1000,
	ATOMARRAYOBJECT_SRAD		= 1001,
	ATOMARRAYOBJECT_SUB		= 1002,
	ATOMARRAYOBJECT_SINGLE	= 1003
};

#endif // OATOMARRAY_H__
