#ifndef OBASECURVE_H__
#define OBASECURVE_H__

#include "Fdwgobjectvalues.h"

enum
{
	BASECURVE_TYPE								= 1001,
		BASECURVE_TYPE_UNKNOWN				= 0,
		BASECURVE_TYPE_NURBS				= 1,
		BASECURVE_TYPE_POLYNOMIAL			= 2,
		BASECURVE_TYPE_LINE					= 3,
		BASECURVE_TYPE_CIRCULAR				= 4,
		BASECURVE_TYPE_CONIC				= 5,
		BASECURVE_TYPE_COMPOSITE			= 6,
	BASECURVE_OUTPUT				     		= 1002,
	BASECURVE_SUB					     		= 1003,
	BASECURVE_FLATNESS							= 1004,
		BASECURVE_PLANAR					= 0,
		BASECURVE_NONPLANAR					= 1,
		BASECURVE_MAKENURBS							= 1010,

		BASECURVE_TESTON							= 1080,
	BASECURVE_TESTPOINT							= 1081,

	ID_CURVEPROPERTIES							= 1090,
	ID_CURVETEST 								= 1099
};

#endif // OBASECURVE_H__
