#ifndef OEGROUP_H__
#define OEGROUP_H__

enum
{
	//Groups
	MGGROUPEFFECTOR_GROUPEFFECTOR = 991,

	//------------------------------
	//Effector controls
	MGGROUPEFFECTOR_STRENGTH			= 1000,
	MGGROUPEFFECTOR_EFFECTORLIST	= 1100,
	MGGROUPEFFECTOR_RETIME				= 1101,
	MGGROUPEFFECTOR_STARTTIME			= 1102,
	MGGROUPEFFECTOR_ENDTIME				= 1103,

	MGGROUPEFFECTOR_SELECTION			=	1021
};
#endif // OEGROUP_H__
