#ifndef OEXTRUDE_H__
#define OEXTRUDE_H__

enum
{
	EXTRUDEOBJECT_ISOPARM			= 1000,
	EXTRUDEOBJECT_SUB					= 1001,
	EXTRUDEOBJECT_MOVE				= 1002,
	EXTRUDEOBJECT_FLIPNORMALS	= 1003,
	EXTRUDEOBJECT_HIERARCHIC	= 1004
	//EXTRUDEOBJECT_QUADS				= 1005
};

#endif // OEXTRUDE_H__
