#ifndef OMORPHDEFORMER_H__
#define OMORPHDEFORMER_H__

enum
{
	MORPHDEFORMER_GROUPSTRENGTHS	=		990,
	MORPHDEFORMER_TARGETMORPH			=		1000,
	MORPHDEFORMER_STRENGTH				=		1001
};

#endif // OMORPHDEFORMER_H__
