#ifndef OVOLUMEGROUP_H__
#define OVOLUMEGROUP_H__

enum
{
	ID_VOLUMEGROUP_PATH = 6000,
	ID_VOLUMEGROUP_VOLUMESLIST = 6001,
	ID_VOLUMEGROUP_STATS_STRING = 6002,
	ID_VOLUMEGROUP_SAVE = 6003,
	ID_VOLUMEGROUP_RELOAD = 6004,
	ID_VOLUMEGROUP_FILELINK = 6005,
	ID_VOLUMEGROUP_PATH_ABSOLUTE = 6006,
	ID_VOLUMEGROUP_DETACH = 6007
};

#endif // OVOLUME_H__
