#ifndef OVOLUMETOMESH_H__
#define OVOLUMETOMESH_H__

enum
{
	ID_VOLUMETOMESH_ISO = 6000,
	ID_VOLUMETOMESH_ADAPTIVE_VALUE = 6002,
	ID_VOLUMETOMESH_THRESHOLD = 6003,
	ID_VOLUMETOMESH_USE_ISO = 6004,
};

#endif // OVOLUMETOMESH_H__
