#ifndef OVOLUMEFILTER_H__
#define OVOLUMEFILTER_H__

enum
{
	ID_VOLUMEFILTER_STENGTH = 1000,

	ID_VOLUMEFILTER_VOLUME_TYPE = 1001,
		ID_VOLUMEFILTER_VOLUME_TYPE_SDF = 0,
		ID_VOLUMEFILTER_VOLUME_TYPE_FOG = 1,

	ID_VOLUMEFILTER_SDF_SMOOTH_TYPE = 1002,
		ID_VOLUMEFILTER_SDF_TYPE_GAUSSIAN = 0,
		ID_VOLUMEFILTER_SDF_TYPE_MEANVALUE = 1,
		ID_VOLUMEFILTER_SDF_TYPE_MEDIANVALUE = 2,
		ID_VOLUMEFILTER_SDF_TYPE_MEANCURVATURE = 3,
		ID_VOLUMEFILTER_SDF_TYPE_LAPLACIANFLOW = 4,

	ID_VOLUMEFILTER_SDF_RESHAPE_TYPE = 1003,
		ID_VOLUMEFILTER_SDF_TYPE_DIALATE_ERODE = 0,
		ID_VOLUMEFILTER_SDF_TYPE_OPEN_CLOSE = 1,

	ID_VOLUMEFILTER_FOG_SMOOTH_TYPE = 1004,
		ID_VOLUMEFILTER_TYPE_GAUSSIAN = 0,
		ID_VOLUMEFILTER_TYPE_MEANVALUE = 1,
		ID_VOLUMEFILTER_TYPE_MEDIANVALUE = 2,

	ID_VOLUMEFILTER_FOG_RESHAPE_TYPE = 1005,
		ID_VOLUMEFILTER_TYPE_OFFSET = 0,
		ID_VOLUMEFILTER_TYPE_REMAP = 1,
		ID_VOLUMEFILTER_TYPE_SPLINEREMAP = 2,

	ID_VOLUMEFILTER_ITERATIONS = 1006,
	ID_VOLUMEFILTER_SDF_STENCILWIDTH = 1007,

	ID_VOLUMEFILTER_RESHAPE_OFFSET = 1009,
	ID_VOLUMEFILTER_SDF_REMAP_OLD_MIN = 1010,
	ID_VOLUMEFILTER_SDF_REMAP_OLD_MAX = 1011,
	ID_VOLUMEFILTER_SDF_REMAP_NEW_MIN = 1012,
	ID_VOLUMEFILTER_SDF_REMAP_NEW_MAX = 1013,

	ID_VOLUMEFILTER_SDF_OPTIONS = 1014,
	ID_VOLUMEFILTER_SDF_RESIZE = 1015,
	ID_VOLUMEFILTER_SDF_RESIZE_HALFBAND = 1016,
	ID_VOLUMEFILTER_SDF_FILTERACCURACY = 1017,
		ID_VOLUMEFILTER_SDF_FILTERACCURACY_FIRST_BIAS = 0,
		ID_VOLUMEFILTER_SDF_FILTERACCURACY_SECOND_BIAS = 1,
		ID_VOLUMEFILTER_SDF_FILTERACCURACY_THIRD_BIAS = 2,
		ID_VOLUMEFILTER_SDF_FILTERACCURACY_WENO5_BIAS = 3,
		ID_VOLUMEFILTER_SDF_FILTERACCURACY_HJWENO5_BIAS = 4,
	ID_VOLUMEFILTER_GLOBALFILTERTYPE = 1018,
		ID_VOLUMEFILTER_GLOBALFILTERTYPE_SMOOTH = 0,
		ID_VOLUMEFILTER_GLOBALFILTERTYPE_RESHAPE = 1,
	ID_VOLUMEFILTER_FIELDTAB = 1019,
	ID_VOLUMEFILTER_FIELDLIST = 1020,
	ID_VOLUMEFILTER_ASDEFORMER = 1021,
	ID_VOLUMEFILTER_MODETAB = 1022,
	ID_VOLUMEFILTER_FILTERTAB = 1023,
	ID_VOLUMEFILTER_REMAP_SPLINE = 1024,
	ID_VOLUMEFILTER_REDUCEDUI = 1025
};

#endif // OVOLUMEFILTER_H__
