#ifndef PREFSMETRICSPREFERENCES_H__
#define PREFSMETRICSPREFERENCES_H__

enum
{
	METRICSPREFERENCES_MAIN_GROUP  = 999,
	ENABLE_CHECKBOX,
	PREFSMETRICSPREFERENCES,
	UUID_EDITTEXT,
	OPT_OUT_BUTTON,
	ENABLE_COMMANDS_CHECKBOX,
	ENABLE_PREFERENCES_CHECKBOX,
	ENABLE_SYSTEM_INFO_CHECKBOX,
	GOTO_PREFERENCE_DIRECTORY,
	METRICSPREFERENCES_DUMMY
};

#endif // PREFSMETRICSPREFERENCES_H__
