#ifndef PREFSRENDERER_H__
#define PREFSRENDERER_H__

enum
{
	PREF_RENDERER_MAIN_GROUP				= 999,
	PREF_RENDERER_THREADCUSTOM			= 1000,
	PREF_RENDERER_THREADNUMBER			= 1001,
	PREF_RENDERER_THREADPRIORITY		= 1003,
	PREF_RENDERER_CREATELOG					= 1004,
	PREF_RENDERER_GLOBALILLUM				= 1005,
	PREF_RENDERER_RENDERQUEUELOG		= 1006,
	PREF_RENDERER_LOWERPROCESSPRIORITY = 1007,

	PREFS_RENDERER_DUMMY
};

#endif // PREFSRENDERER_H__
