#ifndef PREFSNAVIGATION_H__
#define PREFSNAVIGATION_H__

enum
{
	PREF_NAVIGATION_MAIN_GROUP			= 999,
	PREF_NAVIGATION_MOVE						= 1000,
	PREF_NAVIGATION_SCALE						= 1001,
	PREF_NAVIGATION_ROTATE					= 1002,
	PREF_NAVIGATION_CAMERA					= 1003,
		PREF_NAVIGATION_CAMERA_CTR			= 1,
		PREF_NAVIGATION_CAMERA_OBJ			= 2,
		PREF_NAVIGATION_CAMERA_CUR			= 3,
		PREF_NAVIGATION_CAMERA_CAM			= 4,
		PREF_NAVIGATION_CAMERA_CUSTOM		= 5,
		PREF_NAVIGATION_CAMERA_CAM_2D = 6, // 171122 Camera NavMode

	PREF_NAVIGATION_POI							= 1004,
		PREF_NAVIGATION_POI_CTR					= 1,
		PREF_NAVIGATION_POI_OBJ					= 2,
		PREF_NAVIGATION_POI_CAM					= 3,

	PREF_NAVIGATION_CURSOR					= 1005,
		PREF_NAVIGATION_CURSOR_OFF			= 1,
		PREF_NAVIGATION_CURSOR_SELECTED	= 2,
		PREF_NAVIGATION_CURSOR_CHILDREN	= 3,
		PREF_NAVIGATION_CURSOR_ALL			= 4,
	PREF_NAVIGATION_FIXEDDOLLY			= 1006,
	PREF_NAVIGATION_DEEPCURSOR			=	1007,

	PREF_NAVIGATION_CAMERAREVERSE		= 1008,
	PREF_NAVIGATION_DOLLY						= 1009,
		PREF_NAVIGATION_DOLLY_OFF				= 1,
		PREF_NAVIGATION_DOLLY_ORTHO			=	2,
		PREF_NAVIGATION_DOLLY_ALL				=	3,
	PREF_NAVIGATION_SYNCVIEWS				= 1010,
	PREF_NAVIGATION_GIMBALLINGAXIS	=	1011,
	PREF_NAVIGATION_VIEW_TRANSITION	=	1012,
	PREF_NAVIGATION_TRACKBALL				=	1013,

	PREF_NAVIGATION_GROUP						= 2000,
	PREF_NAVIGATION_DUMMY_STR				= 2001,

	PREF_NAVIGATION_DUMMY
};

#endif // PREFSNAVIGATION_H__
