#ifndef PREFSPHPREFS_H__
#define PREFSPHPREFS_H__

enum
{
	PREF_PHPREFS_MAIN_GROUP  = 999,
	PREF_PHPREFS_FOOTAGE_MEMORY_MAX_CACHE_SIZE_MB  = 1000,
	PREF_PHPREFS_FOOTAGE_SYS_MEMORY_SAFETY_RESERVE_MB,

	PREF_PHPREFS_DUMMY
};

#endif // PREFSPHPREFS_H__

