#ifndef PREFSMOUSE_H__
#define PREFSMOUSE_H__

enum
{
	PREF_MOUSE_MAIN_GROUP							= 999,
	PREF_MOUSE_CURSOR									= 1005,
	PREF_MOUSE_GRAPHICTABLET					= 1006,
	PREF_MOUSE_HIRESTABLET						= 1007,
	PREF_MOUSE_BASICCURSOR						= 1008,
	PREF_MOUSE_ACTIVATION							= 1009,
	PREF_MOUSE_RMB_EMULATION					= 1010,
	PREF_MOUSE_COMMANDER_AT_CURSOR		= 1011,
	PREF_MOUSE_DUMMYGRAPHICTABLET_STR	= 1012,
	PREF_MOUSE_DUMMYHIRESTABLET_STR		= 1013,
	PREF_MOUSE_TOUCHDEVICES						= 1014,

	PREF_MOUSE_GROUP					= 2000,
	PREF_MOUSE_DUMMY_STR			= 2001,

	PREF_MOUSE_DUMMY
};

#endif // PREFSMOUSE_H__
