#ifndef TANNOTATION_H__
#define TANNOTATION_H__

enum
{
	ANNOTATIONTAG_FIRST_ELEMENT = 10000,

	ANNOTATIONTAG_GROUPDISPLAY,			// group
	ANNOTATIONTAG_COLOR,						// vector
	ANNOTATIONTAG_COLORFROMLAYER,		// bool
	ANNOTATIONTAG_COLORICON,				// bool
	ANNOTATIONTAG_VIEWPORT_SHOW,		// bool
	ANNOTATIONTAG_VIEWPORT_ALL,			// bool
	ANNOTATIONTAG_SCALEFLAG,				// bool
	ANNOTATIONTAG_EXPORT,						// bool
	ANNOTATIONTAG_FOLD,							// bool
	ANNOTATIONTAG_SHOW_ALL,					// button
	ANNOTATIONTAG_HIDE_ALL,					// button
	ANNOTATIONTAG_HIDE_OTHERS,			// button
	ANNOTATIONTAG_GROUPSETTINGS,		// group
	ANNOTATIONTAG_TEXT,							// string
	ANNOTATIONTAG_URL,							// string
	ANNOTATIONTAG_URL_INFO,					// string
	ANNOTATIONTAG_URL_GO,						// button
	ANNOTATIONTAG_POI_CUSTOM,				// bool
	ANNOTATIONTAG_POI_OBJECTINDEX,	// long
	ANNOTATIONTAG_POI_POINTINDEX,		// long
	ANNOTATIONTAG_DRAGGED,					// bool
	ANNOTATIONTAG_DRAG_TAG_ID,			// UInt64
	ANNOTATIONTAG_DRAG_OBJ_ID,			// UInt64

	ANNOTATIONTAG_DUMMY = 0
};

#endif // TANNOTATION_H__
