#ifndef THAIRSPLINEDYNAMICS_H__
#define THAIRSPLINEDYNAMICS_H__

enum
{
	HAIR_SDYNAMICS_TAG_GROUP_ADVANCED = 3000,
	HAIR_SDYNAMICS_TAG_GROUP_PROPERTIES,
	HAIR_SDYNAMICS_TAG_GROUP_FORCES,
	HAIR_SDYNAMICS_TAG_GROUP_CACHE,

	HAIR_SDYNAMICS_TAG_ENABLE = 1000,
	HAIR_SDYNAMICS_TAG_COLLISIONS,
	HAIR_SDYNAMICS_TAG_AUTOTIME,
	HAIR_SDYNAMICS_TAG_START,
	HAIR_SDYNAMICS_TAG_STOP,
	HAIR_SDYNAMICS_TAG_DRAG,
	HAIR_SDYNAMICS_TAG_GRAVITY,
	HAIR_SDYNAMICS_TAG_STIFFNESS,
	HAIR_SDYNAMICS_TAG_EXTRA_STIFF,
	HAIR_SDYNAMICS_TAG_SUBDIV,
	HAIR_SDYNAMICS_TAG_ITERATIONS,
	HAIR_SDYNAMICS_TAG_RADIUS,

	HAIR_SDYNAMICS_TAG_MASS,
	HAIR_SDYNAMICS_TAG_SETMASS,
	HAIR_SDYNAMICS_TAG_SET_FIXED,
	HAIR_SDYNAMICS_TAG_RELEASE_FIXED,
	HAIR_SDYNAMICS_TAG_CLEAR_FIXED,
	HAIR_SDYNAMICS_TAG_DRAW_FIXED,

	HAIR_SDYNAMICS_TAG_RUBBER,
	HAIR_SDYNAMICS_TAG_SET_STATE,
	HAIR_SDYNAMICS_TAG_FIXED,

	HAIR_SDYNAMICS_TAG_FORCES_INCEXC,
	HAIR_SDYNAMICS_TAG_FORCES_INCLUDE,

	HAIR_SDYNAMICS_REST_MIX,
	HAIR_SDYNAMICS_REST_HOLD,
	HAIR_SDYNAMICS_ELASTIC_LIMIT,
	HAIR_SDYNAMICS_ELASTIC_DEFORM,

	HAIR_SDYNAMICS_CACHE_ENABLE,
	HAIR_SDYNAMICS_CACHE_CALCULATE,
	HAIR_SDYNAMICS_CACHE_COMPRESSED,
	HAIR_SDYNAMICS_CACHE_DELETE,
	HAIR_SDYNAMICS_CACHE_INFO2,
	HAIR_SDYNAMICS_CACHE_CACHE_FRAME,
	HAIR_SDYNAMICS_CACHE_CACHE_LOAD,
	HAIR_SDYNAMICS_CACHE_CACHE_SAVE,
	HAIR_SDYNAMICS_CACHE_CACHE_LIMIT,
	HAIR_SDYNAMICS_CACHE_TEXT_LIMIT,

	//	HAIR_CONSTRAINTS_TAG_SET_ANCHOR = 5000,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SDYNAMICS_TAG_INCEXC_INCLUDE = 0,
	HAIR_SDYNAMICS_TAG_INCEXC_EXCLUDE,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SDYNAMICS_TAG_DUMMY
};

#endif // THAIRSPLINEDYNAMICS_H__
