#ifndef THAIRLIGHT_H__
#define THAIRLIGHT_H__

enum
{
	HAIR_LIGHT_TAG_INCLUDE = 1000,
	HAIR_LIGHT_TAG_SHADOWS,
	HAIR_LIGHT_TAG_MAP_SIZE,
	HAIR_LIGHT_TAG_SHADOW_WIDTH,
	HAIR_LIGHT_TAG_SHADOW_SAMPLE_SIZE,
	HAIR_LIGHT_TAG_SHADOW_TRANS_ACCURACY,
	HAIR_LIGHT_TAG_SHADOW_AA,
	HAIR_LIGHT_TAG_SHADOW_DIST_ACCURACY,
	HAIR_LIGHT_TAG_SHADOWS_MAP,
	HAIR_LIGHT_TAG_SHADOWS_TYPE,
	HAIR_LIGHT_TAG_SHADOW_DENSITY,
	HAIR_LIGHT_TAG_CAST_SHADOW,
	HAIR_LIGHT_TAG_SHADOW_AA_LEVEL,
	HAIR_LIGHT_TAG_SHADOW_AA_USER_LEVEL,

	//////////////////////////////////////////////////////////////////////////

	HAIR_LIGHT_TAG_SHADOWS_NONE = 0,
	HAIR_LIGHT_TAG_SHADOWS_TRACED,
	HAIR_LIGHT_TAG_SHADOWS_SOFT,
	HAIR_LIGHT_TAG_SHADOWS_AUTO,

	HAIR_LIGHT_TAG_SHADOWS_MAP_250 = 0,
	HAIR_LIGHT_TAG_SHADOWS_MAP_500,
	HAIR_LIGHT_TAG_SHADOWS_MAP_750,
	HAIR_LIGHT_TAG_SHADOWS_MAP_1000,
	HAIR_LIGHT_TAG_SHADOWS_MAP_1250,
	HAIR_LIGHT_TAG_SHADOWS_MAP_1500,
	HAIR_LIGHT_TAG_SHADOWS_MAP_1750,
	HAIR_LIGHT_TAG_SHADOWS_MAP_2000,
	HAIR_LIGHT_TAG_SHADOWS_MAP_CUSTOM,

	HAIR_LIGHT_TAG_SHADOW_AA_NONE = 0,
	HAIR_LIGHT_TAG_SHADOW_AA_LOW,
	HAIR_LIGHT_TAG_SHADOW_AA_MED,
	HAIR_LIGHT_TAG_SHADOW_AA_HIGH,
	HAIR_LIGHT_TAG_SHADOW_AA_BEST,
	HAIR_LIGHT_TAG_SHADOW_AA_USER,

	//////////////////////////////////////////////////////////////////////////

	HAIRLIGHTTAG_DUMMY
};

#endif // THAIRLIGHT_H__
