#ifndef THAIRSELECTION_H__
#define THAIRSELECTION_H__

enum
{
	HAIR_SELECTION_TAG_RESTORE = 1000,
	HAIR_SELECTION_TAG_SET,
	HAIR_SELECTION_TAG_SELECT,
	HAIR_SELECTION_TAG_HIDE,
	HAIR_SELECTION_TAG_LOCK,
	HAIR_SELECTION_TAG_DESELECT,
	HAIR_SELECTION_TAG_UNLOCK,
	HAIR_SELECTION_TAG_SHOW,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SELECTION_TAG_DUMMY
};

#endif // THAIRSELECTION_H__
