#ifndef TOOLMESHTOVOLUME_H__
#define TOOLMESHTOVOLUME_H__

enum
{
	ID_TOOLMESHTOVOLUME_GRID_SIZE = 6000,
	ID_TOOLMESHTOVOLUME_HALF_BAND_INTERIOR = 6001,
	ID_TOOLMESHTOVOLUME_HALF_BAND_EXTERIOR = 6002,
	ID_TOOLMESHTOVOLUME_REMOVE_SOURCE = 6003
};

#endif // TOOLMESHTOVOLUME_H__