#ifndef TOOLCANAMING_H__
#define TOOLCANAMING_H__

enum
{
  ID_CA_JOINT_NAMING_RENAME = 5000,
  ID_CA_JOINT_NAMING_NAMES,

  ID_CA_JOINT_NAMING_TYPE = 2000,
  ID_CA_JOINT_NAMING_APPLY,
  ID_CA_JOINT_NAMING_STORE,
  ID_CA_JOINT_NAMING_PRE,
  ID_CA_JOINT_NAMING_POST,
  ID_CA_JOINT_NAMING_REPLACE_PRE,
  ID_CA_JOINT_NAMING_REPLACE_POST,
  ID_CA_JOINT_NAMING_REPLACE,
  ID_CA_JOINT_NAMING_REPLACE_APPLY,
  ID_CA_JOINT_NAMING_SET_NAME,
  ID_CA_JOINT_NAMING_REPLACE_WITH,
  ID_CA_JOINT_NAMING_CASE,
  ID_CA_JOINT_NAMING_LOAD,
  ID_CA_JOINT_NAMING_SAVE,
  ID_CA_JOINT_NAMING_REMOVE,

  ID_CA_JOINT_NAMING_NODETYPE,
    ID_CA_JOINT_NAMING_NODETYPE_OBJECT = 0,
    ID_CA_JOINT_NAMING_NODETYPE_TAG = 1,
    ID_CA_JOINT_NAMING_NODETYPE_MATERIAL = 2,
    ID_CA_JOINT_NAMING_NODETYPE_LAYER = 3,
    ID_CA_JOINT_NAMING_NODETYPE_TAKE = 4,

  //////////////////////////////////////////////////////////////////////////

  ID_CA_JOINT_NAMING_DUMMY
};

#endif // TOOLCANAMING_H__
