#ifndef TOOLWEIGHTBASE_H__
#define TOOLWEIGHTBASE_H__

enum
{
	ID_CA_TOOL_WEIGHT_BASE = 11000,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_WEIGHT_BASE_MODE_ADD = 0,
	ID_CA_WEIGHT_BASE_MODE_SUBTRACT,
	ID_CA_WEIGHT_BASE_MODE_ABS,
	ID_CA_WEIGHT_BASE_MODE_SMOOTH,
	ID_CA_WEIGHT_BASE_MODE_BLEED,
	ID_CA_WEIGHT_BASE_MODE_INTENSITY,
	ID_CA_WEIGHT_BASE_MODE_REMAP,
	ID_CA_WEIGHT_BASE_MODE_PRUNE,
	ID_CA_WEIGHT_BASE_MODE_SMOOTH_DIST,
	ID_CA_WEIGHT_BASE_MODE_DROPPER,
	ID_CA_WEIGHT_BASE_MODE_SPRAY,
	ID_CA_WEIGHT_BASE_MODE_ROUND,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_TOOL_WEIGHT_BASE_DUMMY
};

#endif // TOOLWEIGHTBASE_H__
