#ifndef TOOLLOOPSELECTION_H__
#define TOOLLOOPSELECTION_H__

enum
{
	MDATA_LOOP_SEL_STOP_AT_BOUNDS     = 1100, // BOOL
	MDATA_LOOP_SEL_SELECT_BOUNDS      = 1101, // BOOL
	MDATA_LOOP_SEL_GREEDY_SEARCH      = 1106, // BOOL

	MDATA_LOOP_LOOP_EDGE              = 1102, // LONG
	MDATA_LOOP_RING_EDGE              = 1103, // LONG (not needed if MDATA_LOOP_SELECTBOUNDARY is set)
	MDATA_LOOP_SKIP                   = 1104, // LONG
	MDATA_LOOP_SELECTION              = 1105, // LONG (must be SELECTION_NEW, SELECTION_ADD or SELECTION_SUB)

	MDATA_LOOP_SEL_
};

#endif // TOOLLOOPSELECTION_H__
