#ifndef TOOLADDPOINT_H__
#define TOOLADDPOINT_H__

enum
{
	MDATA_ADDPOINT_EDGE								= 1100, // REAL
	MDATA_ADDPOINT_CRTL               = 1101, //BOOL
	MDATA_ADDPOINT_SHIFT              = 1102, //BOOL
	MDATA_ADDPOINT_SPLINE             = 1103,//BOOL
	MDATA_ADDPOINT_OBJINDEX           = 1104,//LONG
	MDATA_ADDPOINT_POINT              = 1105,//VECTOR
	MDATA_ADDPOINT_TVAL               = 1106, //REAL
	MDATA_ADDPOINT_SNUM               = 1107, //LONG
	MDATA_ADDPOINT_POINTMODE          = 1108,//LONG
	MDATA_ADDPOINT_ELEMENTINDEX       = 1109, //LONG
	MDATA_ADDPOINT_EDGEPOINTF         = 1110, //LONG
	MDATA_ADDPOINT_EDGEPOINT1         = 1111, //LONG
	MDATA_ADDPOINT_EDGEPOINT2         = 1112, //LONG
	MDATA_ADDPOINT_POSITIONX					= 1113,
	MDATA_ADDPOINT_POSITIONY					= 1114,
	MDATA_ADDPOINT_POSITIONZ					= 1115,
	MDATA_ADDPOINT_TRI								= 1116, //Bool
	MDATA_ADDPOINT_
};

#endif // TOOLADDPOINT_H__
