#ifndef TPHCONSTRAINTPOS_H__
#define TPHCONSTRAINTPOS_H__

enum
{
	//==== Scene Calibration ====
	PH_CAL_GROUP_SCENE_CALIBRATION_POS = 45000,
	// Position
	PH_SCENE_CAL_POS,
	PH_SCENE_CAL_POS_MODE,
		PH_SCENE_CAL_POS_MODE_CAMERA_TO_POS,
		PH_SCENE_CAL_POS_MODE_SELECT_TO_POS,
	PH_SCENE_CAL_POS_FRAME_NUM,
	PH_SCENE_CAL_POS_SET_SELECT_DEPRECATED,
	PH_SCENE_CAL_POS_FORCE_EXPORT,
	PH_SCENE_CAL_POS_GET_SELECT_DEPRECATED,
	PH_SCENE_CAL_POS_X_COORD,
	PH_SCENE_CAL_POS_Y_COORD,
	PH_SCENE_CAL_POS_Z_COORD,

	PH_SCENE_CAL_POS_STR_TARGETS = 47000,
	PH_SCENE_CAL_POS_TARGETS,
	PH_SCENE_CAL_POS_TARGET_0,

};

#endif // TPHCONSTRAINTPOS_H__
