#ifndef VPPHLENSDISTORT_H__
#define VPPHLENSDISTORT_H__

enum
{
	// PHLENS Lens Distortion support - needed in all elements which support usage of lenses.
	PH_GROUP_LENS_DISTORTION = 100000,
	PH_LENS_PROFILE_FILENAME,
	PH_LENS_PROFILE_NAME,
	PH_LENS_PROFILE_TYPE,
	PH_LENS_PROFILE_PARAM_0 = 100100,
	PH_LENS_PROFILE_PARAM_1,
	PH_LENS_PROFILE_PARAM_2,
	PH_LENS_PROFILE_PARAM_3,
	PH_LENS_PROFILE_PARAM_4,

	PH_LENS_PARAM_RC_00 = 105000,
	PH_LENS_PARAM_RC_01,
	PH_LENS_PARAM_RC_02,
	PH_LENS_PARAM_RC_03,
	PH_LENS_PARAM_RC_04,
	PH_LENS_PARAM_RC_05,
	PH_LENS_PARAM_RC_10 = 105100,
	PH_LENS_PARAM_RC_11,
	PH_LENS_PARAM_RC_12,
	PH_LENS_PARAM_RC_13,
	PH_LENS_PARAM_RC_14,
	PH_LENS_PARAM_RC_15,
	PH_LENS_PARAM_RC_20 = 105200,
	PH_LENS_PARAM_RC_21,
	PH_LENS_PARAM_RC_22,
	PH_LENS_PARAM_RC_23,
	PH_LENS_PARAM_RC_24,
	PH_LENS_PARAM_RC_25,
	PH_LENS_PARAM_RC_30 = 105300,
	PH_LENS_PARAM_RC_31,
	PH_LENS_PARAM_RC_32,
	PH_LENS_PARAM_RC_33,
	PH_LENS_PARAM_RC_34,
	PH_LENS_PARAM_RC_35,
	PH_LENS_PARAM_RC_40 = 105400,
	PH_LENS_PARAM_RC_41,
	PH_LENS_PARAM_RC_42,
	PH_LENS_PARAM_RC_43,
	PH_LENS_PARAM_RC_44,
	PH_LENS_PARAM_RC_45,

	PH_IMAGE_VIEW_SCALE = 120000,
	PH_IMAGE_VIEW_OFFSET_X,
	PH_IMAGE_VIEW_OFFSET_Y
};

#endif // VPPHLENSDISTORT_H__

