#ifndef VPPREVIEWSOFTWARE_H__
#define VPPREVIEWSOFTWARE_H__

enum
{
	VP_PREVIEWSOFTWARE_ENHANCEDOPENGL								=	1000,
	VP_PREVIEWSOFTWARE_TRANSPARENCY  = 1001,
	VP_PREVIEWSOFTWARE_SHADOW				= 1002,
	VP_PREVIEWSOFTWARE_POSTEFFECT		= 1003,
	VP_PREVIEWSOFTWARE_NOISE					= 1004,
	VP_PREVIEWSOFTWARE_ANTIALIASING	= 1005,
		VP_PREVIEWSOFTWARE_ANTIALIASING_NONE	= 0,
	VP_PREVIEWSOFTWARE_TESSELLATION = 1006,
	VP_PREVIEWSOFTWARE_SSAO = 1007,
	VP_PREVIEWSOFTWARE_REFLECTIONS = 1008,
	
	VP_PREVIEWSOFTWARE_DUMMY
};

#endif // VPPREVIEWSOFTWARE_H__
