#ifndef VPPREVIEWHARDWARE_H__
#define VPPREVIEWHARDWARE_H__

enum
{
	VP_PREVIEWHARDWARE_ENHANCEDOPENGL								=	1000,
	VP_PREVIEWHARDWARE_TRANSPARENCY  = 1001,
	VP_PREVIEWHARDWARE_SHADOW				= 1002,
	VP_PREVIEWHARDWARE_POSTEFFECT		= 1003,
	VP_PREVIEWHARDWARE_NOISE					= 1004,
	VP_PREVIEWHARDWARE_ANTIALIASING	= 1005,
		VP_PREVIEWHARDWARE_ANTIALIASING_NONE	= 0,
	VP_PREVIEWHARDWARE_SUPERSAMPLING	= 1038207,
		VP_PREVIEWHARDWARE_SUPERSAMPLING_NONE	= 0,
		VP_PREVIEWHARDWARE_SUPERSAMPLING_2	= 1,
		VP_PREVIEWHARDWARE_SUPERSAMPLING_3	= 2,
		VP_PREVIEWHARDWARE_SUPERSAMPLING_4	= 3,
		VP_PREVIEWHARDWARE_SUPERSAMPLING_5	= 4,
		VP_PREVIEWHARDWARE_SUPERSAMPLING_6	= 5,
		VP_PREVIEWHARDWARE_SUPERSAMPLING_7	= 6,
		VP_PREVIEWHARDWARE_SUPERSAMPLING_8	= 7,
		VP_PREVIEWHARDWARE_SUPERSAMPLING_16	= 15,
	VP_PREVIEWHARDWARE_GEOMETRY_ONLY = 1038216,
	VP_PREVIEWHARDWARE_TESSELLATION = 1006,
	VP_PREVIEWHARDWARE_SSAO = 1007,
	VP_PREVIEWHARDWARE_REFLECTIONS = 1008,
	VP_PREVIEWHARDWARE_DEPTHOFFIELD = 1038944,
	VP_PREVIEWHARDWARE_ALTERNATIVESHADOWMAPPING = 1039900,

	VP_PREVIEWHARDWARE_DUMMY
};

#endif // VPPREVIEWHARDWARE_H__
