#ifndef BMBASE_H__
#define BMBASE_H__

enum
{
	MDATA_BRUSHMODIFIERBASE_GROUP = 20000,
	MDATA_BRUSHMODIFIERBASE_ENABLED = 20001, //Bool
	MDATA_BRUSHMODIFIERBASE_STRENGTH = 20002, //Float
};

#endif // BMBASE_H__
