#ifndef BPLAYERFILTERBRCO_H__
#define BPLAYERFILTERBRCO_H__

#include "bplayerfilterbase.h"

enum
{
	// object properties
	ID_PAINTLAYERFILTERBRCO_BRIGHTNESS	= 4000,
	ID_PAINTLAYERFILTERBRCO_CONTRAST,
	ID_PAINTLAYERFILTERBRCOD_END
};

#endif // BPLAYERFILTERBRCO_H__
