#ifndef BPSPLINE_H__
#define BPSPLINE_H__

#include "obaselist.h"

enum
{
	// object properties
	ID_PAINTSPLINE_GROUP									= 901,
	ID_PAINTSPLINE_INFO_GROUP							= 902,
	ID_PAINTSPLINE_GROUP_COORDS						= 903,

	ID_PAINTSPLINE_PREVIEW								= 1001,
	ID_PAINTSPLINE_POINTS									= 1002,
	ID_PAINTSPLINE_SEGMENTS 							= 1003,

	ID_PAINTSPLINE_POSITION								= 1004,
	ID_PAINTSPLINE_ROTATION								= 1005,
	ID_PAINTSPLINE_SCALE									= 1006,

	ID_PAINTSPLINE_END
};

#endif // BPSPLINE_H__
