#ifndef COLLIDERTAG_H__
#define COLLIDERTAG_H__

enum
{
	COLLIDER_BOUNCE    = 11010, // real
	COLLIDER_FRICTION    = 11011, // real

	COLLIDER_SET_EXCL   = 11012, // button
	COLLIDER_SHOW_EXCL  = 11013, // button
	COLLIDER_DRAW_EXCL  = 11014, // bool
	COLLIDER_TEXT_EXCL  = 11015, // group
	COLLIDER_CLEAR_EXCL = 11016, // button

	COLLIDER_USE        = 11017, // bool
	CLOTH_PBD_COLLIDER_SIDE = 11018, // Int Cycle
		CLOTH_PBD_COLLIDER_SIDE_NORMALS = 0,
		CLOTH_PBD_COLLIDER_SIDE_INVNORMALS = 1,
		CLOTH_PBD_COLLIDER_SIDE_BOTH = 2,
	COLLIDER_HOLLOW = 11019, // bool
	COLLIDER_STICKINESS = 11020, // real
	CONVEX_COLLIDER = 11021, // Int
				CONVEX_COLLIDER_TRIANGLE_MESH = 0,
				CONVEX_COLLIDER_CONVEX_HULLS = 1,
				CONVEX_COLLIDER_SPHERE = 2,
				CONVEX_COLLIDER_BOX = 3,
	CONVEX_COLLIDER_CONVEXDECOMPOSITION_ACCURACY = 11022,

	COLLIDER_SDF_VOXEL_SIZE_ABSOLUTE = 11023,
	COLLIDER_SDF_VOXEL_BAND_EXTERIOR_ABSOLUTE = 11024,
	COLLIDER_LIQUID_COLLISION_MODE = 11025, // Int
		COLLIDER_LIQUID_COLLISION_MODE_SURFACE = 0,
	  COLLIDER_LIQUID_COLLISION_MODE_VOLUME = 1,
		COLLIDER_LIQUID_COLLISION_MODE_OFF = 2,
	COLLIDER_SDF_VOXEL_BAND_INTERIOR_ABSOLUTE = 11026,
	COLLIDER_THICKNESS = 11027,
	COLLIDER_THICKNESS_POSITION = 11028,
	COLLIDER_PREPROCESS_IF_OPEN = 11029,
		COLLIDER_PREPROCESS_IF_OPEN_OFF = 0,
		COLLIDER_PREPROCESS_IF_OPEN_THICKEN = 1,
		COLLIDER_PREPROCESS_IF_OPEN_CLOSE = 2,
	COLLIDER_LIQUID_COLLISION_GROUP = 11030,
	COLLIDER_PREPROCESS_GROUP = 11031,
	COLLIDER_LIQUID_COLLISION_FROM = 11032,
		COLLIDER_LIQUID_COLLISION_FROM_OUTSIDE = 0,
		COLLIDER_LIQUID_COLLISION_FROM_INSIDE = 1,
		COLLIDER_LIQUID_COLLISION_FROM_BOTH = 2,
	COLLIDER_SDF_VOXEL_SIZE_MODE = 11033,
		COLLIDER_SDF_VOXEL_SIZE_MODE_RELATIVE = 0,
		COLLIDER_SDF_VOXEL_SIZE_MODE_ABSOLUTE = 1,
	COLLIDER_SDF_VOXEL_SIZE_RELATIVE = 11034,
	COLLIDER_SDF_VOXEL_BAND_INTERIOR_RELATIVE = 11035,
	COLLIDER_SDF_VOXEL_BAND_EXTERIOR_RELATIVE = 11036,

	COLLIDER_INFO_STRING0 = 20001,
	COLLIDER_INFO_STRING1 = 20002,

	COLLIDER_DUMMY
};

#endif // COLLIDERTAG_H__
