#ifndef DESC_FIELDBG_H__
#define DESC_FIELDBG_H__

enum
{
	ID_FIELDBG_GROUP = 900,		// GROUP

	ID_FIELDBG_VALUE = 1000,	// FLOAT
	ID_FIELDBG_COLOR = 1001,	// COLOR
	ID_FIELDBG_DIRECTION = 1002,	// VECTOR

	ID_FIELDBG_DUMMY
};
#endif	// DESC_FIELDBG_H__
