#ifndef DRSFILE_H__
#define DRSFILE_H__

enum
{
	REDSHIFT_FILE_PATH	= 1000,
	REDSHIFT_FILE_ANIMATION_MODE,
	REDSHIFT_FILE_ANIMATION_TIMING_MODE,

	REDSHIFT_FILE_ANIMATION_FRAME_START,
	REDSHIFT_FILE_ANIMATION_FRAME_END,
	REDSHIFT_FILE_ANIMATION_FRAME_RATE,
	REDSHIFT_FILE_ANIMATION_RANGE_START,
	REDSHIFT_FILE_ANIMATION_RANGE_END,
	REDSHIFT_FILE_ANIMATION_FRAME_OFFSET,
	REDSHIFT_FILE_ANIMATION_LOOP_COUNT,
	REDSHIFT_FILE_LAYER,
	REDSHIFT_FILE_COLORSPACE,

	REDSHIFT_FILE_ANIMATION_MODE_OFF = 0,
	REDSHIFT_FILE_ANIMATION_MODE_SIMPLE,
	REDSHIFT_FILE_ANIMATION_MODE_LOOP,
	REDSHIFT_FILE_ANIMATION_MODE_PINGPONG,

	REDSHIFT_FILE_ANIMATION_TIMING_MODE_FRAME = 0,
	REDSHIFT_FILE_ANIMATION_TIMING_MODE_TIME,
	REDSHIFT_FILE_ANIMATION_TIMING_MODE_RANGE,
};

#endif // DRSFILE_H__
