#ifndef DSOUNDPROBE_H__
#define DSOUNDPROBE_H__

enum
{
	SOUNDPROBESUBCHANNEL_PROBE_GROUP						= 900,	// GROUP

	SOUNDPROBESUBCHANNEL_LEFT										= 1000,	// Float
	SOUNDPROBESUBCHANNEL_RIGHT									= 1001,	// Float
	SOUNDPROBESUBCHANNEL_TOP										= 1002,	// Float
	SOUNDPROBESUBCHANNEL_BOTTOM									= 1003, // Float
	SOUNDPROBESUBCHANNEL_GRADIENT								= 1004, // Gradient
	SOUNDPROBESUBCHANNEL_COLOR_MODE							= 1005, // INT CYCLE
		SOUNDPROBESUBCHANNEL_COLOR_MODE_OFF					= 0,
		SOUNDPROBESUBCHANNEL_COLOR_MODE_SOLID				= 1,
		SOUNDPROBESUBCHANNEL_COLOR_MODE_HORIZONTAL	= 2,
		SOUNDPROBESUBCHANNEL_COLOR_MODE_VERTICAL		= 3,
	SOUNDPROBESUBCHANNEL_HOLD										= 1007, // BOOL
	SOUNDPROBESUBCHANNEL_MOVE_UP								= 1008, // BUTTON
	SOUNDPROBESUBCHANNEL_MOVE_DOWN							= 1009, // BUTTON
	SOUNDPROBESUBCHANNEL_COLOR									= 1010, // COLOR

	SOUNDPROBESUBCHANNEL_DUMMY_
};

#endif // DSOUNDPROBE_H__
