#ifndef DYNFORCE_H__
#define DYNFORCE_H__

enum
{
	FORCE_STRENGTH = 13001,
	FORCE_DAMPING = 13002,
	FORCE_RESPECT_MASS = 13003,

	FORCE_FALLOFF = 13011,
	FORCE_FALLOFF_LINEAR = 0,
	FORCE_FALLOFF_INV = 1,
	FORCE_FALLOFF_INV_SQR = 2,
	FORCE_FALLOFF_INV_CUBIC = 3,
	FORCE_FALLOFF_STEP = 4,

	FORCE_INNER_DISTANCE = 13012,
	FORCE_OUTER_DISTANCE = 13013,
	FORCE_DUMMY
};

#endif // DYNFORCE_H__
