#ifndef FAIIMPORT_H__
#define FAIIMPORT_H__

enum
{
	AIIMPORTFILTER_SCALE					= 2000,
	AIIMPORTFILTER_GROUPSPLINES		= 2001,
	AIIMPORTFILTER_CONNECTSPLINES			= 2002,
	
	AIIMPORTFILTER_FORMAT_STRING			= 3003
};

#endif // FAIIMPORT_H__
