#ifndef FCADIMPORT_H__
#define FCADIMPORT_H__

enum
{
	CADIMPORT_GROUP				= 999,

	CADIMPORT_GRP_GENERAL = 1000,
	CADIMPORT_ORIGINAL_UNITS,
	CADIMPORT_SCALE,
	CADIMPORT_GEOMETRY,
	CADIMPORT_SPLINES,
	CADIMPORT_INSTANCES,
		CADIMPORT_INSTANCES_NONE = 0,
		CADIMPORT_INSTANCES_INSTANCE = 1,
		CADIMPORT_INSTANCES_RENDERINSTANCE = 2,
	CADIMPORT_HELPER = 1006,
	CADIMPORT_LOAD_HIDDEN,
	CADIMPORT_SWAP_YZAXIS,

	CADIMPORT_GRP_OPTIONAL,

	CADIMPORT_VISIBILITY,
	CADIMPORT_NORMALS,
		CADIMPORT_NORMALS_NONE,
		CADIMPORT_NORMALS_NORMALTAG,
		CADIMPORT_NORMALS_PHONGTAG,
	CADIMPORT_UVS,
	CADIMPORT_DISPLAY_COLORS,
		CADIMPORT_DISPLAY_COLORS_NONE,
		CADIMPORT_DISPLAY_COLORS_ORIGINAL,
		CADIMPORT_DISPLAY_COLORS_RANDOM,
	CADIMPORT_LAYERS,
	CADIMPORT_MATERIALS,
		CADIMPORT_MATERIALS_NONE,
		CADIMPORT_MATERIALS_ORIGINAL,
		CADIMPORT_MATERIALS_DISPLAY_COLORS,
		CADIMPORT_MATERIALS_RANDOM,

	CADIMPORT_GRP_MODIFICATIONS,

	CADIMPORT_HEAL,
	CADIMPORT_STITCH_COUNT,
	CADIMPORT_SEW,
		CADIMPORT_SEW_NONE,
		CADIMPORT_SEW_KEEP_ORIGINAL_BODIES,
		CADIMPORT_SEW_CREATE_BODIES_BY_TOPOLOGY,
		CADIMPORT_SEW_CREATE_BODIES_BY_COLOR,
		CADIMPORT_SEW_CREATE_BODIES_BY_LAYER,

	CADIMPORT_GRP_TESSELATION,
	CADIMPORT_OPTIMIZE_HIERARCHY,
	CADIMPORT_SOURCE_MESH,
	CADIMPORT_LOD,
	CADIMPORT_DETAILING,
		CADIMPORT_DETAILING_ORIGINAL,
		CADIMPORT_DETAILING_CUSTOM,
		CADIMPORT_DETAILING_LOW,
		CADIMPORT_DETAILING_MEDIUM,
		CADIMPORT_DETAILING_HIGH,
	CADIMPORT_MAX_SAG,
	CADIMPORT_MAX_LENGTH,
	CADIMPORT_MAX_ANGLE,

	DELME_CADIMPORT_LOD_STATICTEXT,

	CADIMPORT_SCALEBASEDTESSELATION,
	CADIMPORT_SCALEBASEDTESSELATION_RANGE,
	CADIMPORT_SCALEBASEDTESSELATION_INTERPOLATION,
	CADIMPORT_SCALEBASEDTESSELATION_GROUP,
	CADIMPORT_LOW_MAX_SAG,
	CADIMPORT_LOW_MAX_LENGTH,
	CADIMPORT_LOW_MAX_ANGLE,
	CADIMPORT_MEDIUM_MAX_SAG,
	CADIMPORT_MEDIUM_MAX_LENGTH,
	CADIMPORT_MEDIUM_MAX_ANGLE,
	CADIMPORT_HIGH_MAX_SAG,
	CADIMPORT_HIGH_MAX_LENGTH,
	CADIMPORT_HIGH_MAX_ANGLE,
	CADIMPORT_DETAILING_GROUP,
	CADIMPORT_SCALEBASEDTESSELATION_RANGE_LOWMEDIUM_VIRTUAL,
	CADIMPORT_SCALEBASEDTESSELATION_RANGE_MEDIUMHIGH_VIRTUAL,

	CADIMPORT_LAYERS_NONE,
	CADIMPORT_LAYERS_ORIGINAL,
	CADIMPORT_LAYERS_SBT,

	DELME_CADIMPORT_SOURCE_MESH_STATICTEXT,

	CADIMPORT_CUSTOM_MAX_SAG,
	CADIMPORT_CUSTOM_MAX_ANGLE
};

#endif // FCADIMPORT_H__
