#ifndef FLBASE_H__
#define FLBASE_H__

enum
{
	// GROUPS
	ID_FIELDLAYER_FIELDINFO											= 440000335,				// SUBCONTAINER GROUP
	ID_FIELDLAYER_BASICGROUP										= 805,							// GROUP

	// PARAMETERS
	ID_FIELDLAYER_STRENGTH											= 440000260,				// FLOAT
	ID_FIELDLAYER_BLENDINGMODE									= 440000261,				// INT CYCLE
		ID_FIELDLAYER_BLENDINGMODE_LIGHTEN					= 0,
		ID_FIELDLAYER_BLENDINGMODE_DARKEN						= 1,
		ID_FIELDLAYER_BLENDINGMODE_MULTIPLY					= 2,
		ID_FIELDLAYER_BLENDINGMODE_AVERAGE					= 3,
		ID_FIELDLAYER_BLENDINGMODE_ADD							= 4,
		ID_FIELDLAYER_BLENDINGMODE_SUBTRACT					= 5,
		ID_FIELDLAYER_BLENDINGMODE_DIFFERENCE				= 6,
		ID_FIELDLAYER_BLENDINGMODE_NEGATION					= 7,
		ID_FIELDLAYER_BLENDINGMODE_SCREEN						= 8,
		ID_FIELDLAYER_BLENDINGMODE_EXCLUSION				= 9,
		ID_FIELDLAYER_BLENDINGMODE_LEGACYOVERLAY		= 10,
		ID_FIELDLAYER_BLENDINGMODE_SOFTLIGHT				= 11,
		ID_FIELDLAYER_BLENDINGMODE_HARDLIGHT				= 12,
		ID_FIELDLAYER_BLENDINGMODE_COLORDODGE				= 13,
		ID_FIELDLAYER_BLENDINGMODE_COLORBURN				= 14,
		ID_FIELDLAYER_BLENDINGMODE_LINEARDODGE			= 15,
		ID_FIELDLAYER_BLENDINGMODE_LINEARBURN				= 16,
		ID_FIELDLAYER_BLENDINGMODE_LINEARLIGHT			= 17,
		ID_FIELDLAYER_BLENDINGMODE_VIVIDLIGHT				= 18,
		ID_FIELDLAYER_BLENDINGMODE_PINLIGHT					= 19,
		ID_FIELDLAYER_BLENDINGMODE_HARDMIX					= 20,
		ID_FIELDLAYER_BLENDINGMODE_REFLECT					= 21,
		ID_FIELDLAYER_BLENDINGMODE_GLOW							= 22,
		ID_FIELDLAYER_BLENDINGMODE_PHOENIX					= 23,
		ID_FIELDLAYER_BLENDINGMODE_LEVR							= 24,
		ID_FIELDLAYER_BLENDINGMODE_COLOR						= 25,
		ID_FIELDLAYER_BLENDINGMODE_COLOR_INV				= 26,
		ID_FIELDLAYER_BLENDINGMODE_NORMAL						= 27,
		ID_FIELDLAYER_BLENDINGMODE_LAYERMASK				= 28,
		ID_FIELDLAYER_BLENDINGMODE_ABSLIGHTEN				= 29,
		ID_FIELDLAYER_BLENDINGMODE_ABSDARKEN				= 30,
		ID_FIELDLAYER_BLENDINGMODE_ABSOVERLAY				= 31,
		ID_FIELDLAYER_BLENDINGMODE_TRUESUBTRACT			= 32,
		ID_FIELDLAYER_BLENDINGMODE_OVERLAY					= 33,
	ID_FIELDLAYER_ENABLED												= 440000265,				// BOOLEAN
	ID_FIELDLAYER_ENABLE_VALUE									= 440000306,				// BOOLEAN / SUB ID_FIELDLAYER_ENABLED
	ID_FIELDLAYER_ENABLE_COLOR									= 440000307,				// BOOLEAN / SUB ID_FIELDLAYER_ENABLED
	ID_FIELDLAYER_ENABLE_DIRECTION							= 440000308,				// BOOLEAN / SUB ID_FIELDLAYER_ENABLED
	ID_FIELDLAYER_ENABLE_ROTATION								= 440000309,				// BOOLEAN / SUB ID_FIELDLAYER_ENABLED
	
	ID_FIELDLAYER_DUMMY__
};

#endif	// FLBASE_H__
