#ifndef GVCOFFEE_H__
#define GVCOFFEE_H__

#include "gvdynamic.h"

enum
{
	GV_COFFEE_CODE						= 1000,
	GV_COFFEE_ON							= 1003,
	GV_COFFEE_UNLOCK					= 1005,

	GV_COFFEE_REAL_INPUT			= 2000,
	GV_COFFEE_LONG_INPUT,
	GV_COFFEE_BOOL_INPUT,
	GV_COFFEE_VECTOR_INPUT,
	GV_COFFEE_STRING_INPUT,
	GV_COFFEE_TIME_INPUT,
	GV_COFFEE_MATRIX_INPUT,
	GV_COFFEE_LINK_INPUT,
	GV_COFFEE_FILENAME_INPUT,

	GV_COFFEE_REAL_OUTPUT			= 3000,
	GV_COFFEE_LONG_OUTPUT,
	GV_COFFEE_BOOL_OUTPUT,
	GV_COFFEE_VECTOR_OUTPUT,
	GV_COFFEE_STRING_OUTPUT,
	GV_COFFEE_TIME_OUTPUT,
	GV_COFFEE_MATRIX_OUTPUT,
	GV_COFFEE_LINK_OUTPUT,
	GV_COFFEE_FILENAME_OUTPUT,

	GV_COFFEE_
};

#endif // GVCOFFEE_H__
