#ifndef GVHAIR_COLLISION_H__
#define GVHAIR_COLLISION_H__

#include "gvbase.h"

enum
{
	GV_HAIR_COLLISION_OBJECT						= 1901,

	GV_HAIR_COLLISION_INPUT_OBJECT			=	2000,
	GV_HAIR_COLLISION_INPUT_NUM					=	2001,

	GV_HAIR_COLLISION_OUTPUT_COUNT			= 3000,
	GV_HAIR_COLLISION_OUTPUT_GID				= 3001,
	GV_HAIR_COLLISION_OUTPUT_SID				= 3002,
	GV_HAIR_COLLISION_OUTPUT_SEG_DELTA	= 3003,
	GV_HAIR_COLLISION_OUTPUT_POLYINDEX	= 3004,
	GV_HAIR_COLLISION_OUTPUT_HITPOINT		= 3005,
	GV_HAIR_COLLISION_OUTPUT_VELOCITY_IN	= 3006,
	GV_HAIR_COLLISION_OUTPUT_VELOCITY_OUT	= 3007,
	GV_HAIR_COLLISION_OUTPUT_FRAME_DELTA	= 3008,
	GV_HAIR_COLLISION_OUTPUT_OBJECT				= 3009,

	GV_HAIR_COLLISION
};

#endif // GVHAIR_COLLISION_H__
