#ifndef GVHAIR_H__
#define GVHAIR_H__

#include "gvbase.h"

enum
{
	GV_HAIR_OBJECT								= 1901,

	GV_HAIR_INPUT_OBJECT					= 2000,
	GV_HAIR_OBJECT_MODE						= 2001,

		GV_HAIR_OBJECT_MODE_GUIDE = 2,
		GV_HAIR_OBJECT_MODE_DYNAMIC_GUIDE = 3,
		GV_HAIR_OBJECT_MODE_HAIR = 4,

	GV_HAIR_OUTPUT_GUIDE_COUNT		= 3003,
	GV_HAIR_OUTPUT_GUIDE_SEGMENTS	= 3004,

	GV_HAIR_
};

#endif // GVHAIR_H__
