#ifndef GVMATRIXMULVECT_H__
#define GVMATRIXMULVECT_H__

#include "gvbase.h"

enum
{
	GV_MATRIXMULVECT_NORMAL = 1000,

	GV_MATRIXMULVECT_INPUT1 = 2000,
	GV_MATRIXMULVECT_INPUT2,

	GV_MATRIXMULVECT_OUTPUT	= 3000,

	GV_MATRIXMULVECT_
};

#endif // GVMATRIXMULVECT_H__
