#ifndef GVMATH_H__
#define GVMATH_H__

#include "gvdynamic.h"

enum
{
	GV_MATH_FUNCTION_ID			= 1000,
		GV_ADD_NODE_FUNCTION		= 0,
		GV_SUB_NODE_FUNCTION,
		GV_MUL_NODE_FUNCTION,
		GV_DIV_NODE_FUNCTION,
		GV_MOD_NODE_FUNCTION,

	GV_MATH_INPUT						= 2000,
	GV_MATH_OUTPUT					= 3000,

	GV_MATH_
};

#endif // GVMATH_H__
