#ifndef GVNEARESTPOINT_H__
#define GVNEARESTPOINT_H__

#include "gvbase.h"

enum
{
  GV_NEARESTPOINT_INPUT_SOURCEOBJECT			= 2000,
  GV_NEARESTPOINT_INPUT_GLOBALPOSITION		= 2001,

  GV_NEARESTPOINT_OUTPUT_POINTINDEX				= 3000,
  GV_NEARESTPOINT_OUTPUT_POINT            = 3001,
  GV_NEARESTPOINT_OUTPUT_DISTANCE					= 3002,
  GV_NEARESTPOINT_OUTPUT_DIFVECTOR				= 3003,

  GV_NEARESTPOINT_
};

#endif // GVNEARESTPOINT_H__
