#ifndef GVWEIGHTMAP_H__
#define GVWEIGHTMAP_H__

enum
{
	GV_WEIGHTMAP_INPUT_TAG = 2000,
	GV_WEIGHTMAP_INPUT_INDEX,
	GV_WEIGHTMAP_INPUT_VALUE,

	GV_WEIGHTMAP_OUTPUT_VALUE = 3000,
	GV_WEIGHTMAP_OUTPUT_COUNT,

	GV_WEIGHTMAP_
};

#endif // GVWEIGHTMAP_H__
