#ifndef MBASE_H__
#define MBASE_H__

enum
{
	ID_MATERIALPROPERTIES	= 806,
	MATERIAL_PAGE_PROPERTIES = 823,
	ID_MATERIALGROUP_MATERIALEDITOR = 824,
	ID_MATERIALGROUP_CUSTOM = 200000182,
	MATERIAL_CUSTOM_ADDCHANNEL = 8030,
	ID_MATERIALGROUP_EX = 200000024,

	CINEWARE_MATERIAL_STANDARD_SURFACE					= 1000,
	CINEWARE_MATERIAL_STANDARD_SURFACE_NAME			= 0,
	CINEWARE_MATERIAL_STANDARD_SURFACE_VALUE		= 1,
	CINEWARE_MATERIAL_STANDARD_SURFACE_EXTENT		= 2,
	CINEWARE_MATERIAL_STANDARD_SURFACE_TEXTURE	= 3
};

#endif // MBASE_H__
