#ifndef MGPARTICLE_H__
#define MGPARTICLE_H__

enum
{
	MG_PARTICLE_STRETCH = 1040,
	MG_PARTICLE_SCALE		= 1041,
	MG_PARTICLE_USE_AGE = 1042,
	MG_PARTICLE_USE_DISTANCE = 1043,
	MG_PARTICLE_MAPPING = 1044,
	MG_PARTICLE_DISTANCE_SCALE = 1045,
};

#endif // MGPARTICLE_H__
