#ifndef NETPREFS_H__
#define NETPREFS_H__

enum
{
	PREF_NAME = 1000,
	PREF_SHARE,
	PREF_THREADCUSTOM,
	PREF_RENDERTHREADS,
	PREF_SECURITYTOKEN,
	PREF_SERVICEPORTNUMBER,
	PREF_SERVICEREPOSITORYPATH,
	PREF_ALLOWRESTARTOFC4D,
	PREF_USEBONJOUR,
	PREF_USEENCRYPTION,
	PREF_HANDLEWARNINGASERROR,
	PREF_ABORTRENDERINGONCLIENTERROR,
	PREF_PEERTOPEERASSETDISTRIBUTION,
	PREF_REQUESTONDEMAND,
	PREF_EXCLUDECLIENTONLOADINGERROR,
	PREF_RENDERINGTIMEOUT,
	PREF_ENABLETEAMRENDER,
	PREF_WEBSERVERPORT,
	PREF_USEBONJOUR_BLOCKED,
	PREF_USEBONJOUR_BLOCKED_JS,
	PREF_TEAMRENDERGROUP,
	PREF_ENABLERENDERINGTIMEOUT,
	PREF_FETCHASSETSALWAYSFROMSERVER,
	PREF_ASSETCHUNKSIZE, // only on server
	PREF_SEP_CLIENT, // GUI separator
	PREF_SEP_LOCAL, // GUI separator
	PREF_SEP_PATHS, // GUI separator
	PREF_SEP_1, // GUI separator
	PREF_SEP_2, // GUI separator
	PREF_WAKEONLANFOROFFLINEMACHINES,
	PREF_KEEPB3DFILESAFTERASSEMBLING,
	PREF_USERMANAGEMENTENABLED,
	PREF_DOWNLOADASSETINPARTS,
	PREF_STOPJOBONSWAPPINGENABLED,
	PREF_STOPJOBONSWAPPINGAUTO,
	PREF_STOPJOBONSWAPPINGVALUE,
	PREF_RESTARTJOBSAFTERUNEXPECTEDSERVERTERMINATION,
	PREF_USEDISCOVERY,

	PREF_MYPREFS_DUMMY
};

#endif // NETPREFS_H__
