#ifndef OBASEGROUP_H__
#define OBASEGROUP_H__

enum
{
	BASEGROUP_SUBFACTOR_CURVE = 1001,
	BASEGROUP_SUBFACTOR_CURVE_REAL = 1002,
	BASEGROUP_SUBFACTOR_CURVE_SLIDER = 1003,
	BASEGROUP_SUBFACTOR_SURFACE_U = 1006,
	BASEGROUP_SUBFACTOR_SURFACE_U_REAL = 1007,
	BASEGROUP_SUBFACTOR_SURFACE_U_SLIDER = 1008,
	BASEGROUP_SUBFACTOR_SURFACE_V = 1011,
	BASEGROUP_SUBFACTOR_SURFACE_V_REAL = 1012,
	BASEGROUP_SUBFACTOR_SURFACE_V_SLIDER = 1013,

	BASEGROUP_SUBFACTOR_BUTTON = 1019,

	BASEGROUP_SELECT_TYPE = 1021,
	BASEGROUP_SELECT_SUBTYPE = 1022,

	BASEGROUP_DESELECT_BUTTON = 1027,
	BASEGROUP_SELECT_BUTTON = 1028,
	BASEGROUP_SELECTONLY_BUTTON = 1029,

	BASEGROUP_CONVERT_TOPOLYS = 1031,
	BASEGROUP_CONVERT_TOGROUPS = 1032,
	BASEGROUP_CONVERT_TOONE = 1033,

	ID_BASEGROUP_SUBFACTOR = 1100,
	ID_BASEGROUP_SELECT = 1101,
	ID_BASEGROUP_CONVERT = 1103
};

#endif // OBASEGROUP_H__
