#ifndef OBEZIER_H__
#define OBEZIER_H__

enum
{
	BEZIEROBJECT_SUBRX			= 1000,
	BEZIEROBJECT_SUBRY			= 1001,
	BEZIEROBJECT_SUBX				= 1002,
	BEZIEROBJECT_SUBY				= 1003,
	BEZIEROBJECT_CLOSEX			= 1004,
	BEZIEROBJECT_CLOSEY			= 1005
};

#endif // OBEZIER_H__
