#ifndef OCACHE_H__
#define OCACHE_H__

enum
{
	SIMULATION_CACHE_GROUP = 50000,
	SIMULATION_CACHE_ENABLED = 50001,
	SIMULATION_CACHE_LOCATION = 50002,
	  SIMULATION_CACHE_EXTERNAL = 0,
	  SIMULATION_CACHE_INTERNAL = 1,
	SIMULATION_CACHE_EXTERNAL_PATH = 50003,
	SIMULATION_CACHE_EXTERNAL_IDENTIFIER = 50004,
	SIMULATION_CACHE_EXTERNAL_LINK = 50005,
	SIMULATION_CACHE_START = 50006,
	SIMULATION_DO_CALCULATE = 50007,
	SIMULATION_DO_CALCULATE_ALL = 50008,
	SIMULATION_DELCACHE = 50009,
	SIMULATION_DELCACHE_ALL = 50010,
	SIMULATION_SPEED = 50011,
	SIMULATION_REPLAY_MODE = 50012,
	  SIMULATION_REPLAY_MODE_PLAY = 0,
		SIMULATION_REPLAY_MODE_LOOP = 1,
		SIMULATION_REPLAY_MODE_PINGPONG = 2,
	SIMULATION_DO_CONVERT_CACHE = 50013,
	SIMULATION_CONVERTING_CACHE = 50014, // internal
	SIMULATION_DO_CONVERT_CACHE_ALL = 50015,
	SIMULATION_ANIMATION_ENABLED = 50016,
	SIMULATION_ANIMATION_FRAME = 50017,
	SIMULATION_ANIMATION_CURVE = 50018,
	SIMULATION_EXPORT_MAPS = 50019,
	SIMULATION_EXPORT_UVS = 50020,
	SIMULATION_EXPORT_NORMALS = 50021,
	SIMULATION_ANIMATION_CURVE_GROUP = 50022,
	SIMULATION_IMPORT_UNIT_SCALE = 50023,

	SIMULATION_CACHE_RUNNING = 40000,
	SIMULATION_CACHE_CUSTOM_SEPARATOR = 50099,
	SIMULATION_CACHE_CUSTOM_GROUP = 50100, // this group can be used to add custom export settings
	//////////////////////////////////////////////////////////////////////////
	SIMULATION_CACHE_DUMMY
};

#endif // OCACHE_H__
