#ifndef OCLOUDGROUP_H__
#define OCLOUDGROUP_H__

enum
{
	SKY_CLOUD_GROUP_FALLOFF_MIN   = 2000, // real
	SKY_CLOUD_GROUP_FALLOFF_MAX   = 2001, // real
	SKY_CLOUD_GROUP_LUM_FALLOFF_MIN = 2003, // real
	SKY_CLOUD_GROUP_LUM_FALLOFF_MAX = 2004, // real
	SKY_CLOUD_GROUP_COLOR_1       = 2005, // vector
	SKY_CLOUD_GROUP_COLOR_2       = 2006, // vector
	SKY_CLOUD_GROUP_TRANS_FALLOFF_MIN = 2007, // real
	SKY_CLOUD_GROUP_TRANS_FALLOFF_MAX = 2008, // real
	SKY_CLOUD_GROUP_ALTITUDE_MIN  = 2009, // real
	SKY_CLOUD_GROUP_ALTITUDE_MAX  = 2010, // real

	SKY_CLOUD_GROUP_DUMMY
};

#endif // OCLOUDGROUP_H__
