#ifndef OEXPLOSION_H__
#define OEXPLOSION_H__

enum
{
	EXPLOSIONOBJECT_PSPEED	 = 1000,
	EXPLOSIONOBJECT_ASPEED	 = 1001,
	EXPLOSIONOBJECT_ENDSIZE  = 1002,
	EXPLOSIONOBJECT_RANDOM   = 1003,
	EXPLOSIONOBJECT_STRENGTH = 1004
};

#endif // OEXPLOSION_H__
