#ifndef OEXTRUDELEGACY_H__
#define OEXTRUDELEGACY_H__

enum
{
	EXTRUDEOBJECT_ISOPARM			= 1000,
	EXTRUDEOBJECT_SUB					= 1001,
	EXTRUDEOBJECT_MOVE				= 1002,
	EXTRUDEOBJECT_FLIPNORMALS	= 1003,
	EXTRUDEOBJECT_HIERARCHIC	= 1004
};

#endif // OEXTRUDELEGACY_H__
