#ifndef OFPCOLLIDE_H__
#define OFPCOLLIDE_H__

enum
{
	FP_COLLIDE_OBJECT_GROUP = 2000,
	FP_COLLIDE_OBJECT_BEHAVIOUR = 2001,
	  FP_COLLIDE_OBJECT_BEHAVIOUR_COLLIDE = 0,
		FP_COLLIDE_OBJECT_BEHAVIOUR_KILL = 1,
		FP_COLLIDE_OBJECT_BEHAVIOUR_AVOID = 2,
		FP_COLLIDE_OBJECT_BEHAVIOUR_STICK = 3,
		// FP_COLLIDE_OBJECT_BEHAVIOUR_ATTRACT = 3,
		// FP_COLLIDE_OBJECT_BEHAVIOUR_CHANGE_GROUP = 4,
		// FP_COLLIDE_OBJECT_BEHAVIOUR_INHERIT = 5,
	FP_COLLIDE_OBJECT_RADIUS = 2002,
	FP_COLLIDE_OBJECT_ELASTICITY = 2003,
	FP_COLLIDE_OBJECT_ELEMENTS = 2004,
	FP_COLLIDE_OBJECT_ELEMENTS_INEXMODE = 2005,
		FP_COLLIDE_OBJECT_ELEMENTS_INEXMODE_INCLUDE = 0,
		FP_COLLIDE_OBJECT_ELEMENTS_INEXMODE_EXCLUDE = 1,
	FP_COLLIDE_OBJECT_TARGET_GROUP = 2006,
	FP_COLLIDE_OBJECT_BEHAVIOUR_PROXIMITY = 2007,
		FP_COLLIDE_OBJECT_BEHAVIOUR_PROXIMITY_RAY = 0,
		FP_COLLIDE_OBJECT_BEHAVIOUR_PROXIMITY_CLOSEST = 1,
		FP_COLLIDE_OBJECT_BEHAVIOUR_PROXIMITY_BOTH = 2,
	FP_COLLIDE_OBJECT_COLLISION_ANGLE = 2008,
	FP_COLLIDE_OBJECT_COLLISION_ANGLE_VARIATION = 2009,
	FP_COLLIDE_OBJECT_SELECT_GEOMETRY = 2010,
	FP_COLLIDE_OBJECT_TARGET_GROUP_CREATE = 2011,
	FP_COLLIDE_OBJECT_COLLISION_ITERATIONS = 2012,
	FP_COLLIDE_OBJECT_CONTACTBEHAVIOUR_SWITCHGROUP = 2013,

	FP_COLLIDE_OBJECT_OUTPUT = 3000,
	FP_COLLIDE_OBJECT_OUTPUT_COUNTCOLLISIONS = 3001,
	FP_COLLIDE_OBJECT_OUTPUT_COUNTCOLLISIONS_ATTRIBUTE_NAME = 3002,
	FP_COLLIDE_OBJECT_OUTPUT_COUNTCOLLISIONS_ATTRIBUTE_POPUP = 3003,
	FP_COLLIDE_OBJECT_OUTPUT_COUNTCOLLISIONS_ATTRIBUTE_CREATE = 3004,
	FP_COLLIDE_OBJECT_OUTPUT_COLLISIONSPEED = 3005,
	FP_COLLIDE_OBJECT_OUTPUT_COLLISIONSPEED_ATTRIBUTE_NAME = 3006,
	FP_COLLIDE_OBJECT_OUTPUT_COLLISIONSPEED_ATTRIBUTE_POPUP = 3007,
	FP_COLLIDE_OBJECT_OUTPUT_COLLISIONSPEED_ATTRIBUTE_CREATE = 3008,
	FP_COLLIDE_OBJECT_OUTPUT_COLLIDED = 3009,
	FP_COLLIDE_OBJECT_OUTPUT_COLLIDED_ATTRIBUTE_NAME = 3010,
	FP_COLLIDE_OBJECT_OUTPUT_COLLIDED_ATTRIBUTE_POPUP = 3011,
	FP_COLLIDE_OBJECT_OUTPUT_COLLIDED_ATTRIBUTE_CREATE = 3012,
	FP_COLLIDE_OBJECT_OBJECT_OUTPUT_UVW = 3013,
	FP_COLLIDE_OBJECT_OBJECT_OUTPUT_UVW_ATTRIBUTE_NAME = 3014,
	FP_COLLIDE_OBJECT_OBJECT_OUTPUT_UVW_ATTRIBUTE_POPUP = 3015,
	FP_COLLIDE_OBJECT_OBJECT_OUTPUT_UVW_ATTRIBUTE_CREATE = 3016,
	FP_COLLIDE_OBJECT_OBJECT_OUTPUT_NORMAL = 3017,
	FP_COLLIDE_OBJECT_OBJECT_OUTPUT_NORMAL_ATTRIBUTE_NAME = 3018,
	FP_COLLIDE_OBJECT_OBJECT_OUTPUT_NORMAL_ATTRIBUTE_POPUP = 3019,
	FP_COLLIDE_OBJECT_OBJECT_OUTPUT_NORMAL_ATTRIBUTE_CREATE = 3020,

	FP_COLLIDE_OBJECT_DUMMY
};

#endif // OFPCOLLIDE_H__