#ifndef OFPCOLLIDE_H__
#define OFPCOLLIDE_H__

enum
{
	FP_COLLIDE_OBJECT_GROUP = 2000,
	FP_COLLIDE_OBJECT_BEHAVIOUR = 2001,
	  FP_COLLIDE_OBJECT_BEHAVIOUR_COLLIDE = 0,
		FP_COLLIDE_OBJECT_BEHAVIOUR_KILL = 1,
		FP_COLLIDE_OBJECT_BEHAVIOUR_AVOID = 2,
		FP_COLLIDE_OBJECT_BEHAVIOUR_STICK = 3,
		// FP_COLLIDE_OBJECT_BEHAVIOUR_ATTRACT = 3,
		// FP_COLLIDE_OBJECT_BEHAVIOUR_CHANGE_GROUP = 4,
		// FP_COLLIDE_OBJECT_BEHAVIOUR_INHERIT = 5,
	FP_COLLIDE_OBJECT_RADIUS = 2002,
	FP_COLLIDE_OBJECT_ELASTICITY = 2003,
	FP_COLLIDE_OBJECT_ELEMENTS = 2004,
	FP_COLLIDE_OBJECT_ELEMENTS_INEXMODE = 2005,
		FP_COLLIDE_OBJECT_ELEMENTS_INEXMODE_INCLUDE = 0,
		FP_COLLIDE_OBJECT_ELEMENTS_INEXMODE_EXCLUDE = 1,
	FP_COLLIDE_OBJECT_TARGET_GROUP = 2006,
	FP_COLLIDE_OBJECT_BEHAVIOUR_PROXIMITY = 2007,
		FP_COLLIDE_OBJECT_BEHAVIOUR_PROXIMITY_RAY = 0,
		FP_COLLIDE_OBJECT_BEHAVIOUR_PROXIMITY_CLOSEST = 1,
		FP_COLLIDE_OBJECT_BEHAVIOUR_PROXIMITY_BOTH = 2,
	FP_COLLIDE_OBJECT_COLLISION_ANGLE = 2008,
	FP_COLLIDE_OBJECT_COLLISION_ANGLE_VARIATION = 2009,
	FP_COLLIDE_OBJECT_SELECT_GEOMETRY = 2010,
	FP_COLLIDE_OBJECT_TARGET_GROUP_CREATE = 2011,
	FP_COLLIDE_OBJECT_COLLISION_ITERATIONS = 2012,
	FP_COLLIDE_OBJECT_CONTACTBEHAVIOUR_SWITCHGROUP = 2013,

	FP_COLLIDE_OBJECT_DUMMY
};

#endif // OFPCOLLIDE_H__