#ifndef OFPCOLORMAPPER_H__
#define OFPCOLORMAPPER_H__

enum
{
	FP_COLORMAPPER_GROUP = 2000,
	FP_COLORMAPPER_GRADIENT = 2003,
	FP_COLORMAPPER_MINFLOAT = 2007,
	FP_COLORMAPPER_MAXFLOAT = 2008,
	FP_COLORMAPPER_REPEAT = 2009,
	FP_COLORMAPPER_ALPHAONLY = 2010,
	FP_COLORMAPPER_FIELDLIST = 2013,
	FP_COLORMAPPER_SOURCE_MODE = 2014,
		FP_COLORMAPPER_SOURCE_MODE_PROPERTY = 0,
		FP_COLORMAPPER_SOURCE_MODE_FIELD = 1,
		FP_COLORMAPPER_SOURCE_MODE_RANDOM = 3,
	FP_COLORMAPPER_DRAW_DISTANCE = 2015,
	FP_COLORMAPPER_MIX = 2016,
	FP_COORMAPPER_DUMMY
};

#endif // OFPCOLORMAPPER_H__
