#ifndef OFPDATAMAPPER_H__
#define OFPDATAMAPPER_H__

enum
{
	FP_DATAMAPPER_GROUP = 2000,
	FP_DATAMAPPER_SPLINE = 2003,
	FP_DATAMAPPER_MINFLOAT = 2007,
	FP_DATAMAPPER_MAXFLOAT = 2008,
	FP_DATAMAPPER_MODE = 2009,
		FP_DATAMAPPER_MODE_CLAMPED = 0,
	  FP_DATAMAPPER_MODE_REPEAT = 1,
		FP_DATAMAPPER_MODE_UNCLAMPED = 2,
	FP_DATAMAPPER_ATTRIBUTE_OUT = 2013,
	FP_DATAMAPPER_VECTOR_EXTRACT_OUT = 2014,
	FP_DATAMAPPER_MINFLOAT_OUT = 2015,
	FP_DATAMAPPER_MAXFLOAT_OUT = 2016,
	FP_DATAMAPPER_TARGET_GROUP = 2019,
	FP_DATAMAPPER_GROUP_THRESHOLD = 2020,
	FP_DATAMAPPER_FIELDLIST = 2021,
	FP_DATAMAPPER_SOURCE_MODE = 2022,
	  FP_DATAMAPPER_SOURCE_MODE_PROPERTY = 0,
	  FP_DATAMAPPER_SOURCE_MODE_FIELD = 1,
	  FP_DATAMAPPER_SOURCE_MODE_RANDOM = 3,
	FP_DATAMAPPER_COLOR_EXTRACT_OUT = 2023,
	FP_DATAMAPPER_DRAW_DISTANCE = 2024,
	FP_DATAMAPPER_MIX = 2025,
	FP_DATAMAPPER_CUSTOMATTRIBUTE_OUT_NAME = 2026,
	FP_DATAMAPPER_CUSTOMATTRIBUTE_OUT_POPUP = 2027,
	FP_DATAMAPPER_MININT = 2028,
	FP_DATAMAPPER_MAXINT = 2029,
	FP_DATAMAPPER_MININT_OUT = 2030,
	FP_DATAMAPPER_MAXINT_OUT = 2031,
	FP_DATAMAPPER_NOISE_SAMPLEUSING = 2032,
		FP_DATAMAPPER_NOISE_SAMPLEUSING_POSITION = 0,
		FP_DATAMAPPER_NOISE_SAMPLEUSING_CUSTOM = 1,
	FP_DATAMAPPER_NOISE_CUSTOM_NAME = 2033,
	FP_DATAMAPPER_NOISE_CUSTOM_POPUP = 2034,
	FP_DATAMAPPER_DUMMY
};

#endif // OFPDATAMAPPER_H__
