#ifndef OFPEMITTEREMISSION_H__
#define OFPEMITTEREMISSION_H__

enum
{
	// Emission
	FP_EMITTER_EMISSION = 10000,
	FP_EMITTER_EMISSION_ENABLED = 100001,
	FP_EMITTER_EMISSION_MODE = 10002,
		FP_EMITTER_EMISSION_MODE_SHOT = 0,
		FP_EMITTER_EMISSION_MODE_CONSTANT = 1,
		FP_EMITTER_EMISSION_MODE_PULSE = 2,
	FP_EMITTER_EMISSION_SHOT_COUNT = 10003,
	FP_EMITTER_EMISSION_CONSTANT_RATE = 10004,
	FP_EMITTER_EMISSION_CONSTANT_RATE_UNIT = 10005,
		FP_EMITTER_EMISSION_CONSTANT_RATE_UNIT_PERFRAME = 0,
		FP_EMITTER_EMISSION_CONSTANT_RATE_UNIT_PERSECOND = 1,
	FP_EMITTER_EMISSION_CONSTANT_RANGE = 10006,
	FP_EMITTER_EMISSION_START = 10007,
	FP_EMITTER_EMISSION_CONSTANT_RANGE_DURATION = 10008,
	FP_EMITTER_EMISSION_PULSE_COUNT = 10009,
	FP_EMITTER_EMISSION_PULSE_DURATION = 10010,
	FP_EMITTER_EMISSION_PULSE_GAP = 10011,
	FP_EMITTER_EMISSION_PULSE_DISTRIBUTION = 10012,
	FP_EMITTER_EMISSION_CONTINUOUS = 10013,
	FP_EMITTER_EMISSION_SEED = 10014,

	FP_EMITTER_EMISSION_DUMMY
};

#endif // OFPEMITTEREMISSION_H__
