#ifndef OFPFLOCK_H__
#define OFPFLOCK_H__

enum
{
	FP_FLOCK_OBJECT_GROUP = 2000,
	FP_FLOCK_OBJECT_GLOBAL_STRENGTH = 2001,
	FP_FLOCK_OBJECT_BEHAVIOUR = 2002,
	  FP_FLOCK_OBJECT_BEHAVIOUR_GROUPING = 0,
	  FP_FLOCK_OBJECT_BEHAVIOUR_SEPARATION = 1,
		FP_FLOCK_OBJECT_BEHAVIOUR_ALIGNMENT = 2,
	FP_FLOCK_OBJECT_STRENGTH_GROUPING = 2003,
	FP_FLOCK_OBJECT_RADIUS_GROUPING = 2004,
	FP_FLOCK_OBJECT_STRENGTH_SEPARATION = 2005,
	FP_FLOCK_OBJECT_RADIUS_SEPARATION = 2006,
	FP_FLOCK_OBJECT_STRENGTH_ALIGNMENT = 2007,
	FP_FLOCK_OBJECT_RADIUS_ALIGNMENT = 2008,
	FP_FLOCK_OBJECT_RANDOM_STRENGTH = 2009,
	FP_FLOCK_OBJECT_RANDOM_SCALE = 2010,
	FP_FLOCK_OBJECT_RANDOM_FREQUENCY = 2011,
	FP_FLOCK_OBJECT_FIELD_OF_VIEW = 2012,
	FP_FLOCK_OBJECT_RANDOM_GROUP = 2013,
	FP_FLOCK_OBJECT_MAXIMUM_SPEED = 2014,
	FP_FLOCK_OBJECT_FIELD_OF_VIEW_FALLOFF = 2015,
	FP_FLOCK_OBJECT_FIELD_OF_VIEW_GROUP = 2016,
	FP_FLOCK_OBJECT_GROUPING_GROUP = 2017,
	FP_FLOCK_OBJECT_SEPARATION_GROUP = 2018,
	FP_FLOCK_OBJECT_ALIGNMENT_GROUP = 2019,
	FP_FLOCK_OBJECT_FIELD_OF_VIEW_VIEWDIRECTION = 2020,
		FP_FLOCK_OBJECT_FIELD_OF_VIEW_VIEWDIRECTION_VELOCITY = 0,
		FP_FLOCK_OBJECT_FIELD_OF_VIEW_VIEWDIRECTION_ALIGNMENTFORWARD = 1,
	FP_FLOCK_OBJECT_EXCLUDED_GROUP = 2021,
	FP_FLOCK_OBJECT_EXCLUDED_GROUP_CREATE = 2022,

	FP_FLOCK_OBJECT_DUMMY
};

#endif // OFPFLOCK_H__
