#ifndef OFPFIELDCONDITION_H__
#define OFPFIELDCONDITION_H__

enum
{
	FP_FIELDCONDITION_BYPASS = 1000,
	FP_FIELDCONDITION_GROUP = 2000,
	FP_FIELDCONDITION_COMBINE_MODE = 2001,
		FP_FIELDCONDITION_COMBINE_MODE_AND = 0,
		FP_FIELDCONDITION_COMBINE_MODE_OR = 1,
		FP_FIELDCONDITION_COMBINE_MODE_XOR = 2,
	FP_FIELDCONDITION_THRESHOLD = 2002,
	FP_FIELDCONDITION_FIELD = 2003,
	FP_FIELDCONDITION_OBJECT_DUMMY
};

#endif // OFPFIELDCONDITION_H__
