#ifndef OFPFOLLOWSPLINE_H__
#define OFPFOLLOWSPLINE_H__

enum
{
	FP_FOLLOWSPLINE_OBJECT_GROUP = 2000,
	FP_FOLLOWSPLINE_OBJECT_BEHAVIOUR = 2001,
		FP_FOLLOWSPLINE_OBJECT_BEHAVIOUR_FORCE = 0,
		FP_FOLLOWSPLINE_OBJECT_BEHAVIOUR_GUIDE = 1,
		FP_FOLLOWSPLINE_OBJECT_BEHAVIOUR_RAIL = 2,
	FP_FOLLOWSPLINE_OBJECT_RADIUS = 2002,
	FP_FOLLOWSPLINE_OBJECT_MAP_QUANTITY = 2003,
		FP_FOLLOWSPLINE_OBJECT_MAP_QUANTITY_AGE = 0,
		FP_FOLLOWSPLINE_OBJECT_MAP_QUANTITY_DISTANCE = 1,
		FP_FOLLOWSPLINE_OBJECT_MAP_QUANTITY_CLOSEST = 2,
		FP_FOLLOWSPLINE_OBJECT_MAP_QUANTITY_AGE_PERCENTAGE = 3,
	FP_FOLLOWSPLINE_OBJECT_EXITBEHAVIOUR = 2004,
		FP_FOLLOWSPLINE_OBJECT_EXITBEHAVIOUR_CONTINUE = 0,
		FP_FOLLOWSPLINE_OBJECT_EXITBEHAVIOUR_TURNAROUND = 1,
		FP_FOLLOWSPLINE_OBJECT_EXITBEHAVIOUR_BEGINNING = 2,
		FP_FOLLOWSPLINE_OBJECT_EXITBEHAVIOUR_KILL = 3,
		FP_FOLLOWSPLINE_OBJECT_EXITBEHAVIOUR_SWITCH_GROUP = 4,
	FP_FOLLOWSPLINE_OBJECT_LINK = 2005,
	FP_FOLLOWSPLINE_OBJECT_ATTRACT_STRENGTH = 2006,
	FP_FOLLOWSPLINE_OBJECT_FOLLOW_STRENGTH = 2007,
	FP_FOLLOWSPLINE_OBJECT_ATTRACT_STRENGTH_MAP = 2008,
	FP_FOLLOWSPLINE_OBJECT_FOLLOW_STRENGTH_MAP = 2009,
	FP_FOLLOWSPLINE_OBJECT_MAP_QUANTITY_SCALE = 2010,
	FP_FOLLOWSPLINE_OBJECT_TARGET_GROUP = 2011,
	FP_FOLLOWSPLINE_OBJECT_LINK_RAIL = 2012,
	FP_FOLLOWSPLINE_OBJECT_FALLOFF_ATTRACT_RADIUS = 2013,
	FP_FOLLOWSPLINE_OBJECT_FALLOFF_FOLLOW_RADIUS = 2014,
	FP_FOLLOWSPLINE_OBJECT_MIX_FACTOR = 2015,
	FP_FOLLOWSPLINE_OBJECT_INVERTDIR = 2016,
	FP_FOLLOWSPLINE_OBJECT_INVERTDIR_RAIL = 2017,
	FP_FOLLOWSPLINE_OBJECT_ALIGN_MIX = 2018,
	FP_FOLLOWSPLINE_OBJECT_MULTI_SEGMENT_MODE = 2019,
		FP_FOLLOWSPLINE_OBJECT_MULTI_SEGMENT_MODE_CLOSEST = 0,
		FP_FOLLOWSPLINE_OBJECT_MULTI_SEGMENT_MODE_SPECIFIC = 1,
		FP_FOLLOWSPLINE_OBJECT_MULTI_SEGMENT_MODE_RANDOM = 2,
	FP_FOLLOWSPLINE_OBJECT_RAIL_CLOSEST = 2020,
	FP_FOLLOWSPLINE_OBJECT_EXITBEHAVIOUR_CLOSEST = 2021,
	FP_FOLLOWSPLINE_OBJECT_MULTI_SEGMENT_CHOICE = 2022,
	FP_FOLLOWSPLINE_OBJECT_CREATEGROUP = 2023,

	FP_FOLLOWSPLINE_OBJECT_DUMMY
};

#endif // OFPFOLLOWSPLINE_H__