#ifndef OFPGEOMETRYSOURCE_H__
#define OFPGEOMETRYSOURCE_H__

enum
{
	// Source
	FP_GEOMETRY_SOURCE = 20000,
	FP_GEOMETRY_SOURCE_LINK = 20001,
	
	FP_GEOMETRY_SOURCE_DUMMY
};

#endif // OFPGEOMETRYSOURCE_H__
