#ifndef OFPGEOMETRYMAPS_H__
#define OFPGEOMETRYMAPS_H__

enum
{
	// Attribute Maps
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS = 20100,
	// Velocity
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_VELOCITY= 20200,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_VELOCITY_DIRECTION_MAP = 20201,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_VELOCITY_DIRECTION_MIX = 20202,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_VELOCITY_SPEED_MAP = 20203,
	// Alignment
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_ALIGNMENT= 20300,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_ALIGNMENT_FORWARD_MAP = 20301,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_ALIGNMENT_FORWARD_MIX = 20302,
	// Angular Velocity
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_ANGULARVELOCITY = 20400,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_ANGULARVELOCITY_SPINVECTOR_MAP = 20401,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_ANGULARVELOCITY_SPINVECTOR_MIX = 20402,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_ANGULARVELOCITY_SPINSPEED_MAP = 20403,
	// Colors
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_COLOR = 20500,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_COLOR_MAP = 20501,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_COLOR_MIX = 20502,
	// Radius
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_RADIUS = 20600,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_RADIUS_MAP = 20601,
	// Lifetime
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_LIFETIME = 20700,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_LIFETIME_EXPECTATION_MAP = 20701,
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_LIFETIME_VARIANCE_MAP = 20702,
	
	FP_GEOMETRYMAPS_DUMMY
};

#endif // OFPGEOMETRYMAPS_H__
