#ifndef OFPGEOMETRYMAPS_H__
#define OFPGEOMETRYMAPS_H__

enum
{
	// Attribute Maps
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS = 20100,
	// Velocity
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_VELOCITY = 20200,
	// Alignment
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_ALIGNMENT = 20300,
	// Angular Velocity
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_ANGULARVELOCITY = 20400,
	// Colors
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_COLOR = 20500,
	// Radius
	// Lifetime
	FP_GEOMETRYMAPS_ATTRIBUTEMAPS_LIFETIME = 20700,

	FP_GEOMETRYMAPS_DUMMY
};

#endif // OFPGEOMETRYMAPS_H__
