#ifndef OFPGROUP_H__
#define OFPGROUP_H__

enum
{
	FP_GROUP_OBJECT_GROUP = 2000,
	
	FP_GROUP_COLOR_OVERRIDE_GROUP = 3000,
	FP_GROUP_COLOR_OVERRIDE_MODE = 3001,
		FP_GROUP_COLOR_OVERRIDE_MODE_NONE = 0,
		FP_GROUP_COLOR_OVERRIDE_MODE_CONSTANT = 1,
		FP_GROUP_COLOR_OVERRIDE_MODE_DIRECTION = 2,
	FP_GROUP_COLOR_OVERRIDE_CONSTANT = 3002,

	FP_GROUP_DRAW_GROUP = 3003,
	FP_GROUP_DRAW_PARTICLES_MODE = 3004,
	  FP_GROUP_DRAW_PARTICLES_MODE_DOTS = 1,
	  FP_GROUP_DRAW_PARTICLES_MODE_ARROWS = 2,
	  FP_GROUP_DRAW_PARTICLES_MODE_TICKS = 4,
	  FP_GROUP_DRAW_PARTICLES_MODE_LINES = 16,
	  FP_GROUP_DRAW_PARTICLES_MODE_HANDLES = 32,
	FP_GROUP_DRAW_PARTICLES_SIZE = 3005,
	FP_GROUP_DRAW_PARTICLES_RADIUS = 3006,

	FP_GROUP_SCENE_GROUP = 4000,
	FP_GROUP_SCENE_LINK = 4001,
	FP_GROUP_SCENE_LINK_TO_DEFAULT = 4002,
	FP_GROUP_OBJECT_DUMMY
};

#endif // OFPGROUP_H__
