#ifndef OFPLOOK_H__
#define OFPLOOK_H__

enum
{
	FP_LOOK_GROUP = 13000,
	FP_LOOK_FORWARD_MODE = 13001,
		FP_LOOK_FORWARD_MODE_AXIS = 0,
		FP_LOOK_FORWARD_MODE_VELOCITYDIRECTION = 1,
		FP_LOOK_FORWARD_MODE_RANDOM = 2,
		FP_LOOK_FORWARD_MODE_MAP = 3, // Unused but important to keep for easy translation from ID to enum
		FP_LOOK_FORWARD_MODE_VECTOR = 4,
		FP_LOOK_FORWARD_MODE_OBJECT = 5,
	FP_LOOK_FORWARD_AXIS = 13002,
		FP_LOOK_FORWARD_AXIS_POSX = 0,
		FP_LOOK_FORWARD_AXIS_NEGX = 1,
		FP_LOOK_FORWARD_AXIS_POSY = 2,
		FP_LOOK_FORWARD_AXIS_NEGY = 3,
		FP_LOOK_FORWARD_AXIS_POSZ = 4,
		FP_LOOK_FORWARD_AXIS_NEGZ = 5,
	FP_LOOK_FORWARD_VECTOR = 13003,
	FP_LOOK_FORWARD_OBJECT_LINK = 13004,
	FP_LOOK_FORWARD_FOV = 13005,
	FP_LOOK_FORWARD_FOVFALLOFF = 13006,
	FP_LOOK_UP_DIRECTION = 13007,
		FP_LOOK_UP_DIRECTION_ALIGNMENT = 0,
		FP_LOOK_UP_DIRECTION_VECTOR = 1,
		FP_LOOK_UP_DIRECTION_SURFACE_NORMAL = 2,
	FP_LOOK_UP_VECTOR = 13008,
	FP_LOOK_RATELEGACY = 13009,
	FP_LOOK_SEED = 13010,
	FP_LOOK_MODE = 13011,
		FP_LOOK_MODE_SET = 0,
		FP_LOOK_MODE_TURN = 1,
	FP_LOOK_TURN_ANGLE = 13012,
	FP_LOOK_TURN_RATE_UNIT = 13013,
		FP_LOOK_TURN_RATE_UNIT_PERFRAME = 0,
		FP_LOOK_TURN_RATE_UNIT_PERSECOND = 1,
	FP_LOOK_MIX = 13014,
	FP_LOOK_END
};

#endif // OFPLOOK_H__
