#ifndef OFPMESHEMITTER_H__
#define OFPMESHEMITTER_H__

enum
{
	// Source
	FP_MESHEMITTER_MESH = 1000,
	FP_MESHEMITTER_MESH_MODE = 1001,
		FP_MESHEMITTER_MESH_MODE_POINTS = 0,
		FP_MESHEMITTER_MESH_MODE_VOLUME = 1,
		FP_MESHEMITTER_MESH_MODE_SURFACE = 2,
	FP_MESHEMITTER_MESH_VOXELSIZE = 1002,
	FP_MESHEMITTER_MESH_RESTRICTION = 1003,
	FP_MESHEMITTER_MESH_SCATTER = 1004,
		FP_MESHEMITTER_MESH_SCATTER_GRID = 0,
		FP_MESHEMITTER_MESH_SCATTER_RANDOM = 1,
		FP_MESHEMITTER_MESH_SCATTER_SPHEREPACKING = 2,
	// Draw
	FP_MESHEMITTER_DRAW = 2000,
	FP_MESHEMITTER_DRAW_GEOMETRY = 2001,
	// Output
	FP_MESHEMITTER_OUTPUT = 3000,
	FP_MESHEMITTER_OUTPUT_POINTINDEX = 3001,
	FP_MESHEMITTER_OUTPUT_POINTINDEX_ATTRIBUTE_NAME = 3002,
	FP_MESHEMITTER_OUTPUT_POINTINDEX_ATTRIBUTE_POPUP = 3003,
	FP_MESHEMITTER_OUTPUT_POINTINDEX_ATTRIBUTE_CREATE = 3004,
	FP_MESHEMITTER_OUTPUT_UVW = 3005,
	FP_MESHEMITTER_OUTPUT_UVW_ATTRIBUTE_NAME = 3006,
	FP_MESHEMITTER_OUTPUT_UVW_ATTRIBUTE_POPUP = 3007,
	FP_MESHEMITTER_OUTPUT_UVW_ATTRIBUTE_CREATE = 3008,
	FP_MESHEMITTER_OUTPUT_NORMAL = 3009,
	FP_MESHEMITTER_OUTPUT_NORMAL_ATTRIBUTE_NAME = 3010,
	FP_MESHEMITTER_OUTPUT_NORMAL_ATTRIBUTE_POPUP = 3011,
	FP_MESHEMITTER_OUTPUT_NORMAL_ATTRIBUTE_CREATE = 3012,
	FP_MESHEMITTER_OUTPUT_BORN = 3013,
	FP_MESHEMITTER_OUTPUT_BORN_ATTRIBUTE_NAME = 3014,
	FP_MESHEMITTER_OUTPUT_BORN_ATTRIBUTE_POPUP = 3015,
	FP_MESHEMITTER_OUTPUT_BORN_ATTRIBUTE_CREATE = 3016,
	FP_MESHEMITTER_OUTPUT_BARYCENTRICCOORDINATE = 3017,
	FP_MESHEMITTER_OUTPUT_BARYCENTRICCOORDINATE_ATTRIBUTE_NAME = 3018,
	FP_MESHEMITTER_OUTPUT_BARYCENTRICCOORDINATE_ATTRIBUTE_POPUP = 3019,
	FP_MESHEMITTER_OUTPUT_BARYCENTRICCOORDINATE_ATTRIBUTE_CREATE = 3020,
	FP_MESHEMITTER_DUMMY
};

#endif // OFPMESHEMITTER_H__
