#ifndef OFPMESHEMITTER_H__
#define OFPMESHEMITTER_H__

enum
{
	// Source
	FP_MESHEMITTER_MESH = 1000,
	FP_MESHEMITTER_MESH_MODE = 1001,
		FP_MESHEMITTER_MESH_MODE_POINTS = 0,
		FP_MESHEMITTER_MESH_MODE_VOLUME = 1,
		FP_MESHEMITTER_MESH_MODE_SURFACE = 2,
	FP_MESHEMITTER_MESH_VOXELSIZE = 1002,
	FP_MESHEMITTER_MESH_RESTRICTION = 1003,
	FP_MESHEMITTER_MESH_SCATTER = 1004,
		FP_MESHEMITTER_MESH_SCATTER_GRID = 0,
		FP_MESHEMITTER_MESH_SCATTER_RANDOM = 1,
	// Draw
	FP_MESHEMITTER_DRAW = 2000,
	FP_MESHEMITTER_DRAW_GEOMETRY = 2001,
	FP_MESHEMITTER_DUMMY
};

#endif // OFPMESHEMITTER_H__
