#ifndef OFPPYRO_H__
#define OFPPYRO_H__

enum
{
	FP_PYRO_OBJECT_GROUP = 2000,
	FP_PYRO_OBJECT_VELOCITY_BEHAVIOUR = 2001,
	  FP_PYRO_OBJECT_BEHAVIOUR_ADD = 0,
	  FP_PYRO_OBJECT_BEHAVIOUR_SET = 1,
		FP_PYRO_OBJECT_BEHAVIOUR_CHANGE = 2,
		FP_PYRO_OBJECT_BEHAVIOUR_NONE = 3,
	FP_PYRO_OBJECT_VELOCITY_STRENGTH = 2002,
	FP_PYRO_OBJECT_GRID_MASK = 2003,
		FP_PYRO_OBJECT_GRID_MASK_NONE = 0,
		FP_PYRO_OBJECT_GRID_MASK_DENSITY = 1,
		FP_PYRO_OBJECT_GRID_MASK_TEMPERATURE = 2,
		FP_PYRO_OBJECT_GRID_MASK_BOTH = 3,
		FP_PYRO_OBJECT_GRID_MASK_FUEL = 4,	
		FP_PYRO_OBJECT_GRID_MASK_ALL = 5,	
	FP_PYRO_OBJECT_PYRO_LINK = 2004, // internal for cached pyro
	FP_PYRO_OBJECT_COLOR_FROM = 2005,
		FP_PYRO_OBJECT_COLOR_FROM_NONE = 0,
		FP_PYRO_OBJECT_COLOR_FROM_COLOR = 1,
		FP_PYRO_OBJECT_COLOR_FROM_TEMPERATURE = 2,
	FP_PYRO_OBJECT_COLOR_STRENGTH = 2006,
	FP_PYRO_OBJECT_SPIN_BEHAVIOUR = 2007,
		FP_PYRO_OBJECT_SPIN_NONE = 0,
		FP_PYRO_OBJECT_SPIN_SET = 1,
		FP_PYRO_OBJECT_SPIN_ADD = 2,
	FP_PYRO_OBJECT_SPIN_STRENGTH = 2008,
	FP_PYRO_OBJECT_COLOR_TEMPERATURE_INTENSITY = 2009,
	FP_PYRO_OBJECT_ALIGNMENT_GRID = 2010,
		FP_PYRO_OBJECT_ALIGNMENT_NONE = 0,
		FP_PYRO_OBJECT_ALIGNMENT_DENSITY = 1,
		FP_PYRO_OBJECT_ALIGNMENT_TEMPERATURE = 2,
		FP_PYRO_OBJECT_ALIGNMENT_FUEL = 3,
	FP_PYRO_OBJECT_ALIGNMENT_STRENGTH = 2011,
	FP_PYRO_OBJECT_COLOR_MIX = 2012,

	FP_PYRO_OBJECT_DUMMY
};

#endif // OFPPYRO_H__