#ifndef OFPREPRODUCE_H__
#define OFPREPRODUCE_H__

enum
{
	// Emission
	FP_REPRODUCE_REPRODUCTION = 4001,
	FP_REPRODUCE_REPRODUCTION_ENABLED = 4002,
	FP_REPRODUCE_REPRODUCTION_COUNT = 4003,
	FP_REPRODUCE_REPRODUCTION_MODE = 4004,
		FP_REPRODUCE_REPRODUCTION_MODE_PERPARTICLE = 0,
		FP_REPRODUCE_REPRODUCTION_MODE_DISTRIBUTE = 1,
	FP_REPRODUCE_REPRODUCTION_KILLSOURCE = 4005,
	FP_REPRODUCE_REPRODUCTION_ONCE = 4006,
		FP_REPRODUCE_REPRODUCTION_ONCE_ON = 0,
		FP_REPRODUCE_REPRODUCTION_ONCE_OFF = 1,
	FP_REPRODUCE_REPRODUCTION_CONTINUOUS = 4007,
	FP_REPRODUCE_REPRODUCTION_OFFSET = 4008,
	FP_REPRODUCE_REPRODUCTION_OFFSET_VARIANCE = 4009,
	FP_REPRODUCE_REPRODUCTION_SEED = 4010,
	FP_REPRODUCE_REPRODUCTION_COUNT_VARIANCE = 4011,
	// Velocity
	FP_REPRODUCE_VELOCITY = 7000,
	FP_REPRODUCE_VELOCITY_SPEED = 7001,
	FP_REPRODUCE_VELOCITY_SPEED_INHERITANCE = 7002,
	FP_REPRODUCE_VELOCITY_DIRECTION_MODE = 7003,
		FP_REPRODUCE_VELOCITY_DIRECTION_MODE_AXIS = 0,
		FP_REPRODUCE_VELOCITY_DIRECTION_MODE_MAP = 1, // Unused but important to keep for easy translation from ID to enum
		FP_REPRODUCE_VELOCITY_DIRECTION_MODE_NORMAL = 2, // Unused but important to keep for easy translation from ID to enum
		FP_REPRODUCE_VELOCITY_DIRECTION_MODE_RADIAL = 3,
		FP_REPRODUCE_VELOCITY_DIRECTION_MODE_RANDOM = 4,
		FP_REPRODUCE_VELOCITY_DIRECTION_MODE_VECTOR = 5,
		FP_REPRODUCE_VELOCITY_DIRECTION_MODE_TARGET = 6,
	FP_REPRODUCE_VELOCITY_DIRECTION_INHERITANCE = 7004,
	FP_REPRODUCE_VELOCITY_DIRECTION_AXIS = 7005,
		FP_REPRODUCE_DIRECTION_POSX = 0,
		FP_REPRODUCE_DIRECTION_NEGX = 1,
		FP_REPRODUCE_DIRECTION_POSY = 2,
		FP_REPRODUCE_DIRECTION_NEGY = 3,
		FP_REPRODUCE_DIRECTION_POSZ = 4,
		FP_REPRODUCE_DIRECTION_NEGZ = 5,
	FP_REPRODUCE_VELOCITY_DIRECTION_VECTOR = 7006,
	FP_REPRODUCE_VELOCITY_DIRECTION_TARGET_LINK = 7007,
	FP_REPRODUCE_VELOCITY_DIRECTION_SPACE = 7008,
		FP_REPRODUCE_VELOCITY_DIRECTION_SPACE_GLOBAL = 0,
		FP_REPRODUCE_VELOCITY_DIRECTION_SPACE_LOCAL = 1,
	FP_REPRODUCE_VELOCITY_DIRECTION_FOV = 7009,
	FP_REPRODUCE_VELOCITY_DIRECTION_FOVFALLOFF = 7010,
	FP_REPRODUCE_VELOCITY_SPEED_VARIANCE = 7011,
	// Alignment
	FP_REPRODUCE_ALIGNMENT = 13000,
	FP_REPRODUCE_ALIGNMENT_FORWARD_MODE = 13001,
		FP_REPRODUCE_ALIGNMENT_FORWARD_MODE_AXIS = 0,
		FP_REPRODUCE_ALIGNMENT_FORWARD_MODE_VELOCITYDIRECTION = 1,
		FP_REPRODUCE_ALIGNMENT_FORWARD_MODE_RANDOM = 2,
		FP_REPRODUCE_ALIGNMENT_FORWARD_MODE_MAP = 3, // Unused but important to keep for easy translation from ID to enum
		FP_REPRODUCE_ALIGNMENT_FORWARD_MODE_VECTOR = 4,
		FP_REPRODUCE_ALIGNMENT_FORWARD_MODE_OBJECT = 5,
		FP_REPRODUCE_ALIGNMENT_FORWARD_MODE_NORMAL = 6, // ditto
		FP_REPRODUCE_ALIGNMENT_FORWARD_MODE_RADIAL = 7,
		FP_REPRODUCE_ALIGNMENT_FORWARD_MODE_TANGENTIAL = 8, // ditto
	FP_REPRODUCE_ALIGNMENT_FORWARD_AXIS = 13002,
	FP_REPRODUCE_ALIGNMENT_FORWARD_AXIS_SPACE = 13003,
		FP_REPRODUCE_ALIGNMENT_FORWARD_AXIS_SPACE_GLOBAL = 0,
		FP_REPRODUCE_ALIGNMENT_FORWARD_AXIS_SPACE_LOCAL = 1,
	FP_REPRODUCE_ALIGNMENT_FORWARD_VECTOR = 13005,
	FP_REPRODUCE_ALIGNMENT_FORWARD_OBJECT_LINK = 13006,
	FP_REPRODUCE_ALIGNMENT_FORWARD_FOV = 13007,
	FP_REPRODUCE_ALIGNMENT_FORWARD_FOVFALLOFF = 13008,
	FP_REPRODUCE_ALIGNMENT_UP = 13009,
	FP_REPRODUCE_ALIGNMENT_INHERITANCE = 13010,
	// Angular Velocity
	FP_REPRODUCE_ANGULARVELOCITY = 14000,
	FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE = 14001,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE_AXIS = 0,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE_VELOCITYDIRECTION = 1,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE_RANDOM = 2,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE_MAP = 3, // Unused but important to keep for easy translation from ID to enum
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE_VECTOR = 4,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE_OBJECT = 5,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE_NORMAL = 6, // ditto
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE_RADIAL = 7,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_MODE_TANGENTIAL = 8, // ditto
	FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_AXIS = 14002,
	FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_VECTOR = 14004,
	FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_SPACE = 14005,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_SPACE_GLOBAL = 0,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_SPACE_LOCAL = 1,
		FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_SPACE_ALIGNMENT = 2,
	FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_FOV = 14006,
	FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_FOVFALLOFF = 14007,
	FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_OBJECT_LINK = 14008,
	FP_REPRODUCE_ANGULARVELOCITY_SPINVECTOR_INHERITANCE = 14009,
	FP_REPRODUCE_ANGULARVELOCITY_SPINSPEED = 14010,
	FP_REPRODUCE_ANGULARVELOCITY_SPINSPEED_VARIANCE = 14011,
	FP_REPRODUCE_ANGULARVELOCITY_SPINSPEED_INHERITANCE = 14012,
	// Colors
	FP_REPRODUCE_COLOR = 8000,
	FP_REPRODUCE_COLOR_COLOR = 8002,
	FP_REPRODUCE_COLOR_INHERITANCE = 8003,
	FP_REPRODUCE_COLOR_GRADIENT = 8004,
	FP_REPRODUCE_COLOR_MODE = 8005,
		FP_REPRODUCE_COLOR_MODE_NOISE = 0,
		FP_REPRODUCE_COLOR_MODE_ALONGSPLINE = 1,
		FP_REPRODUCE_COLOR_MODE_RANDOM = 2,
		FP_REPRODUCE_COLOR_MODE_CONSTANT = 3,
	FP_REPRODUCE_COLOR_COLOR_ALPHA = 8006,
	// Radius
	FP_REPRODUCE_RADIUS = 9000,
	FP_REPRODUCE_RADIUS_RADIUS = 9001,
	FP_REPRODUCE_RADIUS_VARIANCE = 9002,
	FP_REPRODUCE_RADIUS_INHERITANCE = 9003,
	// Lifetime
	FP_REPRODUCE_LIFETIME = 10000,
	FP_REPRODUCE_LIFETIME_EXPECTATION = 10001,
	FP_REPRODUCE_LIFETIME_VARIANCE = 10002,
	FP_REPRODUCE_LIFETIME_INHERITANCE = 10003,
	FP_REPRODUCE_LIFETIME_INFINITE = 10004,
	// Attribute
	FP_REPRODUCE_ATTRIBUTES = 11000,
	// Group
	FP_REPRODUCE_GROUP = 12000,
	FP_REPRODUCE_GROUP_INHERITANCE = 12001,
	FP_REPRODUCE_GROUP_GROUP = 12002,
	FP_REPRODUCE_GROUP_CREATE = 12003,
	//////////////////////////////////////////////////////////////////////////
	FP_REPRODUCE_TAG_DUMMY
};

#endif // OFPREPRODUCE_H__
