#ifndef OFPSPLINEEMITTER_H__
#define OFPSPLINEEMITTER_H__

enum
{
	// Emission
	FP_SPLINEEMITTER_SPLINE = 1000,
	FP_SPLINEEMITTER_SPLINE_MODE = 1001,
		FP_SPLINEEMITTER_SPLINE_MODE_POINTS = 0,
		FP_SPLINEEMITTER_SPLINE_MODE_EDGES = 2,
	FP_SPLINEEMITTER_SPLINE_RESTRICTION = 1002,
	FP_SPLINEEMITTER_SPLINE_RESTRICTION_THRESHOLD = 1003,
	FP_SPLINEEMITTER_SPLINE_SCATTER = 1004,
		FP_SPLINEEMITTER_SPLINE_SCATTER_INTERVAL = 0,
		FP_SPLINEEMITTER_SPLINE_SCATTER_RANDOM = 1,
	FP_SPLINEEMITTER_SPLINE_INTERVAL = 1005,
	FP_SPLINEEMITTER_SPLINE_OFFSET = 1006,
	FP_SPLINEEMITTER_SPLINE_OFFSET_VARIANCE = 1007,
	FP_SPLINEEMITTER_DUMMY
};

#endif // OFPSPLINEEMITTER_H__
