#ifndef OFPSTANDARDEMITTER_H__
#define OFPSTANDARDEMITTER_H__

enum
{
	// SOURCE
	FP_STANDARDEMITTER_SOURCE = 1000,
	FP_STANDARDEMITTER_SOURCE_SHAPE = 1001,
		FP_STANDARDEMITTER_SOURCE_SHAPE_SQUARE = 0,
		FP_STANDARDEMITTER_SOURCE_SHAPE_CIRCLE = 1,
		FP_STANDARDEMITTER_SOURCE_SHAPE_CUBE = 2,
		FP_STANDARDEMITTER_SOURCE_SHAPE_SPHERE = 3,
		FP_STANDARDEMITTER_SOURCE_SHAPE_POINT = 4,
	FP_STANDARDEMITTER_SOURCE_SHAPE_SIZE = 1002,
	FP_STANDARDEMITTER_OUTPUT = 2000,
	FP_STANDARDEMITTER_OUTPUT_UVW = 2001,
	FP_STANDARDEMITTER_OUTPUT_UVW_ATTRIBUTE_NAME = 2002,
	FP_STANDARDEMITTER_OUTPUT_UVW_ATTRIBUTE_POPUP = 2003,
	FP_STANDARDEMITTER_OUTPUT_UVW_ATTRIBUTE_CREATE = 2004,
	FP_STANDARDEMITTER_OUTPUT_BORN = 2006,
	FP_STANDARDEMITTER_OUTPUT_BORN_ATTRIBUTE_NAME = 2007,
	FP_STANDARDEMITTER_OUTPUT_BORN_ATTRIBUTE_POPUP = 2008,
	FP_STANDARDEMITTER_OUTPUT_BORN_ATTRIBUTE_CREATE = 2009,
	
	FP_STANDARDEMITTER_DUMMY
};

#endif // OFPSTANDARDEMITTER_H__
