#ifndef OFPSTICK_H__
#define OFPSTICK_H__

enum
{
	FP_STICK_OBJECT_GROUP = 2000,
	FP_STICK_OBJECT_RADIUS = 2001,
	FP_STICK_OBJECT_STRENGTH = 2002,
	FP_STICK_OBJECT_ELEMENTS = 2003,
	FP_STICK_OBJECT_ELEMENTS_INEXMODE = 2004,
		FP_STICK_OBJECT_ELEMENTS_INEXMODE_INCLUDE = 0,
		FP_STICK_OBJECT_ELEMENTS_INEXMODE_EXCLUDE = 1,
	FP_STICK_OBJECT_TARGET_GROUP = 2005,
	FP_STICK_OBJECT_BEHAVIOUR_PROXIMITY = 2006,
		FP_STICK_OBJECT_BEHAVIOUR_PROXIMITY_RAY = 0,
		FP_STICK_OBJECT_BEHAVIOUR_PROXIMITY_CLOSEST = 1,
		FP_STICK_OBJECT_BEHAVIOUR_PROXIMITY_BOTH = 2,
	FP_STICK_OBJECT_BEHAVIOUR = 2007,
	  FP_STICK_OBJECT_BEHAVIOUR_CHANGE_STRENGTH = 0,
		FP_STICK_OBJECT_BEHAVIOUR_UNSET = 1,
		FP_STICK_OBJECT_BEHAVIOUR_SET = 2,
	FP_STICK_OBJECT_SELECT_GEOMETRY = 2008,
	FP_STICK_OBJECT_CONSIDER_PARTICLERADIUS = 2009,
	FP_STICK_OBJECT_TARGET_GROUP_CREATE = 2010,
	FP_STICK_OBJECT_CONTACTBEHAVIOUR_SWITCHGROUP = 2011,
	
	FP_STICK_OBJECT_OUTPUT = 3000,
	FP_STICK_OBJECT_OUTPUT_ISSTUCK = 3001,
	FP_STICK_OBJECT_OUTPUT_ISSTUCK_ATTRIBUTE_NAME = 3002,
	FP_STICK_OBJECT_OUTPUT_ISSTUCK_ATTRIBUTE_POPUP = 3003,
	FP_STICK_OBJECT_OUTPUT_ISSTUCK_ATTRIBUTE_CREATE = 3004,

	FP_STICK_OBJECT_DUMMY
};

#endif // OFPSTICK_H__