#ifndef OFPSPLINEEMITTER_H__
#define OFPSPLINEEMITTER_H__

enum
{
	// Emission
	FP_SPLINEEMITTER_SPLINE = 1000,
	FP_SPLINEEMITTER_SPLINE_MODE = 1001,
		FP_SPLINEEMITTER_SPLINE_MODE_POINTS = 0,
		FP_SPLINEEMITTER_SPLINE_MODE_EDGES = 2,
	FP_SPLINEEMITTER_SPLINE_RESTRICTION = 1002,
	FP_SPLINEEMITTER_SPLINE_RESTRICTION_THRESHOLD = 1003,
	FP_SPLINEEMITTER_SPLINE_SCATTER = 1004,
		FP_SPLINEEMITTER_SPLINE_SCATTER_INTERVAL = 0,
		FP_SPLINEEMITTER_SPLINE_SCATTER_RANDOM = 1,
	FP_SPLINEEMITTER_SPLINE_INTERVAL = 1005,
	FP_SPLINEEMITTER_SPLINE_OFFSET = 1006,
	FP_SPLINEEMITTER_SPLINE_OFFSET_VARIANCE = 1007,
	FP_SPLINEEMITTER_OUTPUT = 2000,
	FP_SPLINEEMITTER_OUTPUT_TVALUE = 2001,
	FP_SPLINEEMITTER_OUTPUT_TVALUE_ATTRIBUTE_NAME = 2002,
	FP_SPLINEEMITTER_OUTPUT_TVALUE_ATTRIBUTE_POPUP = 2003,
	FP_SPLINEEMITTER_OUTPUT_TVALUE_ATTRIBUTE_CREATE = 2004,
	FP_SPLINEEMITTER_OUTPUT_BORN = 2005,
	FP_SPLINEEMITTER_OUTPUT_BORN_ATTRIBUTE_NAME = 2006,
	FP_SPLINEEMITTER_OUTPUT_BORN_ATTRIBUTE_POPUP = 2007,
	FP_SPLINEEMITTER_OUTPUT_BORN_ATTRIBUTE_CREATE = 2008,
	FP_SPLINEEMITTER_OUTPUT_SEGMENTTVALUE = 2009,
	FP_SPLINEEMITTER_OUTPUT_SEGMENTTVALUE_ATTRIBUTE_NAME = 2010,
	FP_SPLINEEMITTER_OUTPUT_SEGMENTTVALUE_ATTRIBUTE_POPUP = 2011,
	FP_SPLINEEMITTER_OUTPUT_SEGMENTTVALUE_ATTRIBUTE_CREATE = 2012,
	FP_SPLINEEMITTER_OUTPUT_SEGMENTINDEX = 2013,
	FP_SPLINEEMITTER_OUTPUT_SEGMENTINDEX_ATTRIBUTE_NAME = 2014,
	FP_SPLINEEMITTER_OUTPUT_SEGMENTINDEX_ATTRIBUTE_POPUP = 2015,
	FP_SPLINEEMITTER_OUTPUT_SEGMENTINDEX_ATTRIBUTE_CREATE = 2016,
	FP_SPLINEEMITTER_DUMMY
};

#endif // OFPSPLINEEMITTER_H__
