#ifndef OFPSURFACEATTRACT_H__
#define OFPSURFACEATTRACT_H__

enum
{
	FP_SURFACEATTRACT_OBJECT_GROUP = 2000,
	FP_SURFACEATTRACT_OBJECT_BEHAVIOUR = 2001,
		FP_SURFACEATTRACT_OBJECT_BEHAVIOUR_FOLLOW = 0,
		FP_SURFACEATTRACT_OBJECT_BEHAVIOUR_ATTRACT = 1,
		FP_SURFACEATTRACT_OBJECT_BEHAVIOUR_LAND = 2,
	FP_SURFACEATTRACT_OBJECT_RADIUS = 2002,
	FP_SURFACEATTRACT_OBJECT_STRENGTH = 2003,
	FP_SURFACEATTRACT_OBJECT_ELEMENTS = 2004,
	FP_SURFACEATTRACT_OBJECT_ELEMENTS_INEXMODE = 2005,
		FP_SURFACEATTRACT_OBJECT_ELEMENTS_INEXMODE_INCLUDE = 0,
		FP_SURFACEATTRACT_OBJECT_ELEMENTS_INEXMODE_EXCLUDE = 1,
	FP_SURFACEATTRACT_OBJECT_TARGET_GROUP = 2006,
	FP_SURFACEATTRACT_OBJECT_DAMPING = 2007,
	FP_SURFACEATTRACT_OBJECT_RANDOMIZE_TARGET = 2008,
	FP_SURFACEATTRACT_OBJECT_APPLY_VELOCITY = 2009,
	FP_SURFACEATTRACT_OBJECT_SELECT_GEOMETRY = 2010,
	FP_SURFACEATTRACT_OBJECT_TARGET_GROUP_CREATE = 2011,
	FP_SURFACEATTRACT_OBJECT_ALIGN_UP_TO_NORMAL = 2012,
	FP_SURFACEATTRACT_OBJECT_STRENGTH_ATTRACT = 2013,
	FP_SURFACEATTRACT_OBJECT_STRENGTH_FOLLOW = 2014,
	FP_SURFACEATTRACT_OBJECT_STRENGTH_APPLY_VELOCITY = 2015,
	FP_SURFACEATTRACT_OBJECT_CONTACTBEHAVIOUR_SWITCHGROUP = 2016,

	FP_SURFACEATTRACT_OBJECT_DUMMY
};

#endif // OFPSURFACEATTRACT_H__