#ifndef OFPSWITCHGROUP_H__
#define OFPSWITCHGROUP_H__

enum
{
	FP_SWITCHGROUP_OBJECT_GROUP = 2000,
	FP_SWITCHGROUP_LINK = 2001,
	FP_SWITCHGROUP_CREATE = 2002,

	FP_SWITCHGROUP_OBJECT_DUMMY
};

#endif // OFPSWITCHGROUP_H__