#ifndef OFPSTANDARDEMITTER_H__
#define OFPSTANDARDEMITTER_H__

enum
{
	// SOURCE
	FP_STANDARDEMITTER_SOURCE = 1000,
	FP_STANDARDEMITTER_SOURCE_SHAPE = 1001,
		FP_STANDARDEMITTER_SOURCE_SHAPE_SQUARE = 0,
		FP_STANDARDEMITTER_SOURCE_SHAPE_CIRCLE = 1,
		FP_STANDARDEMITTER_SOURCE_SHAPE_CUBE = 2,
		FP_STANDARDEMITTER_SOURCE_SHAPE_SPHERE = 3,
		FP_STANDARDEMITTER_SOURCE_SHAPE_POINT = 4,
	FP_STANDARDEMITTER_SOURCE_SHAPE_SIZE = 1002,
	
	FP_STANDARDEMITTER_DUMMY
};

#endif // OFPSTANDARDEMITTER_H__
