#ifndef OFPSPIN_H__
#define OFPSPIN_H__

enum
{
	FP_SPIN_GROUP = 1000,
	FP_SPIN_MODE_LEGACY = 1001, // Deprecated in 2025.0
		FP_SPIN_MODE_ADDSPEED_LEGACY = 0, 
        FP_SPIN_MODE_SETSPEED_LEGACY = 1, 
		FP_SPIN_MODE_SETSPEEDVECTOR_LEGACY = 2,
	FP_SPIN_SPINSPEED = 1002,
	FP_SPIN_SPINSPEED_VARIANCE = 1003,
	FP_SPIN_SPINVECTOR_MODE = 1004,
		FP_SPIN_SPINVECTOR_MODE_AXIS = 0,
		FP_SPIN_SPINVECTOR_MODE_VELOCITYDIRECTION = 1,
		FP_SPIN_SPINVECTOR_MODE_RANDOM = 2,
		FP_SPIN_SPINVECTOR_MODE_MAP = 3, // Unused but important to keep for easy translation from ID to enum
		FP_SPIN_SPINVECTOR_MODE_VECTOR = 4,
		FP_SPIN_SPINVECTOR_MODE_OBJECT = 5,
	FP_SPIN_SPINVECTOR_AXIS = 1005,
		FP_SPIN_SPINVECTOR_AXIS_POSX = 0,
		FP_SPIN_SPINVECTOR_AXIS_NEGX = 1,
		FP_SPIN_SPINVECTOR_AXIS_POSY = 2,
		FP_SPIN_SPINVECTOR_AXIS_NEGY = 3,
		FP_SPIN_SPINVECTOR_AXIS_POSZ = 4,
		FP_SPIN_SPINVECTOR_AXIS_NEGZ = 5,
	FP_SPIN_SPINVECTOR_VECTOR = 1006,
	FP_SPIN_SPINVECTOR_OBJECT_LINK = 1007,
	FP_SPIN_SPINVECTOR_SPACE = 1008,
		FP_SPIN_SPINVECTOR_SPACE_GLOBAL = 0,
		FP_SPIN_SPINVECTOR_SPACE_LOCAL = 1, // Unused but important to keep for easy translation from ID to enum
		FP_SPIN_SPINVECTOR_SPACE_ALIGNMENT = 2,
	FP_SPIN_SPINVECTOR_FOV = 1009,
	FP_SPIN_SPINVECTOR_FOVFALLOFF = 1010,
	FP_SPIN_RATELEGACY = 1011,
	FP_SPIN_SEED = 1012,
	FP_SPIN_MODE = 1013,
		FP_SPIN_MODE_SET = 0,
		FP_SPIN_MODE_TURN = 1,
	FP_SPIN_SET = 1014,
		FP_SPIN_SET_SPEED = 0,
		FP_SPIN_SET_VECTOR = 1,
	FP_SPIN_TURN_ANGLE = 1015,
	FP_SPIN_TURN_RATE_UNIT = 1016,
		FP_SPIN_TURN_RATE_UNIT_PERFRAME = 0,
		FP_SPIN_TURN_RATE_UNIT_PERSECOND = 1,
	FP_SPIN_LEGACY = 1017,
	FP_SPIN_CONVERT = 1018,
	FP_SPIN_MIX = 1019,
	FP_SPIN_END
};

#endif // OFPSPIN_H__
