#ifndef OGRAVITATION_H__
#define OGRAVITATION_H__

enum
{
	GRAVITATIONOBJECT_LEGACY_STRENGTH	= 1000,
	GRAVITATIONOBJECT_SIZE			= 1001,
	GRAVITATIONOBJECT_STRENGTH	= 1002
};

#endif // OGRAVITATION_H__
