#ifndef OGUIDE_H__
#define OGUIDE_H__

enum
{
	GUIDEOBJECT_TYPE = 1000,
		GUIDEOBJECT_TYPE_LINE = 0,
		GUIDEOBJECT_TYPE_PLANE = 1,

	GUIDEOBJECT_LINE_MODE = 1001,
		GUIDEOBJECT_LINE_MODE_INFINITE	= 0,
		GUIDEOBJECT_LINE_MODE_HALFLINE	= 1,
		GUIDEOBJECT_LINE_MODE_SEGMENT	= 2,

	GUIDEOBJECT_SPATIAL_MODE = 1002,

	GUIDEOBJECT_PLANE_CENTERAXIS = 1003,
	GUIDEOBJECT_SIZE_X = 1004,
	GUIDEOBJECT_SIZE_Z = 1005,
};

#endif // OGUIDE_H__
