#ifndef OLAYER_H__
#define OLAYER_H__

enum
{
	ID_LAYER_SOLO = 1000,
	ID_LAYER_VIEW,
	ID_LAYER_RENDER,
	ID_LAYER_MANAGER,
	ID_LAYER_LOCKED,
	ID_LAYER_GENERATORS,
	ID_LAYER_DEFORMERS,
	ID_LAYER_EXPRESSIONS,
	ID_LAYER_ANIMATION,
	ID_LAYER_COLOR,
	ID_LAYER_XREF
};

#endif // OLAYER_H__
