#ifndef OSPLINERECTANGLE_H__
#define OSPLINERECTANGLE_H__

enum
{
	PRIM_RECTANGLE_WIDTH			= 2060,	// REAL - Width [>=0.0]
	PRIM_RECTANGLE_HEIGHT			= 2061,	// REAL - Height[>=0.0]
	PRIM_RECTANGLE_ROUNDING		= 2062,	// BOOL - Rounding
	PRIM_RECTANGLE_RADIUS			= 2063	// REAL - Rounding Radius [>=0.0]
};

#endif // OSPLINERECTANGLE_H__
