#ifndef OTURBULENCE_H__
#define OTURBULENCE_H__

enum
{
	TURBULENCEOBJECT_STRENGTH		= 1000,	// Real
	TURBULENCEOBJECT_SIZE				= 1001,	// Vector
	TURBULENCEOBJECT_SCALE			=	1002,	// Real
	TURBULENCEOBJECT_FREQUENCY	=	1003	// Real
};

#endif // OTURBULENCE_H__
