#ifndef OVOLUMECACHELAYER_H__
#define OVOLUMECACHELAYER_H__

enum
{
	ID_VOLUMECACHELAYER_ANIMATION = 1000,
	ID_VOLUMECACHELAYER_FROM = 1001,
	ID_VOLUMECACHELAYER_TO = 1002,
	ID_VOLUMECACHELAYER_BUTTON_CACHE = 1003,
	ID_VOLUMECACHELAYER_BUTTON_REFRESH = 1004,
	ID_VOLUMECACHELAYER_BUTTON_CLEAR = 1005,
	ID_VOLUMECACHELAYER_STATS_TYPE = 1006,
	ID_VOLUMECACHELAYER_STATS_SIZE = 1007,
	ID_VOLUMECACHELAYER_LAYERPROPERTIES = 1008
};

#endif // OVOLUMECACHELAYER_H__
