#ifndef OWIND_H__
#define OWIND_H__

enum
{
	WINDOBJECT_STRENGTH							= 1000,	// Real
	WINDOBJECT_SIZE									= 1001,	// Vector
	WINDOBJECT_TURBULENCE						=	1002,	// Real
	WINDOBJECT_TURBULENCE_SCALE			=	1003,	// Real
	WINDOBJECT_TURBULENCE_FREQUENCY	= 1004	// Real
};

#endif // OWIND_H__
