#ifndef PREFS_H__
#define PREFS_H__

enum
{
	PREFS_GROUP  = 999,
	PREFS_STATIC_PORT,
	PREFS_IPADDRESS,				// Obsolete starting with R24
	PREFS_SERVICE,
	PREFS_FOLDER,
	PREFS_ASSIGN_PORT_DYNAMICALLY,
	PREFS_DYNAMIC_PORT,
	PREFS_SHAREUSERNAME,
	PREFS_SHAREUSERNAME_CONFIRMED,
	PREFS_RESET_DEFAULT_FOLDER,
	PREFS_OSC_ASSIGN_PORT_DYNAMICALLY,		// Assign OSC Port Dynamically
	PREFS_OSC_STATIC_PORT									// OSC Port
};

#endif // PREFS_H__
