#ifndef PREFSIMEXPORT_H__
#define PREFSIMEXPORT_H__

enum
{
	PREF_IMEXPORT_MAIN_GROUP = 999,
	PREF_IMEXPORT_SHOW_IMPORT_DLG,
	PREF_IMEXPORT_SHOW_EXPORT_DLG,
	PREF_IMEXPORT_MERGE_ON_DD,
	PREF_IMEXPORT_VERIFY_SCRIPT, 
		PREF_IMEXPORT_VERIFY_SCRIPT_NEVER = 0,
		PREF_IMEXPORT_VERIFY_SCRIPT_ONCE,
		PREF_IMEXPORT_VERIFY_SCRIPT_ALWAYS,
	PREF_IMEXPORT_VERIFY_SCRIPT_FLUSH = 1004,
	PREF_IMEXPORT_IMPORT_GROUP,
	PREF_IMEXPORT_NODESPACE,
	PREF_IMEXPORT_EXPORT_GROUP,
	PREF_IMEXPORT_INFOTEXT,
	PREF_IMEXPORT_OCIO_IMPORT_MODE,
	PREF_IMEXPORT_OCIO_EXPORT_MODE,
	PREF_IMEXPORT_DUMMY
};

#endif // PREFSIMEXPORT_H__
