#ifndef PREFSTAKE_H__
#define PREFSTAKE_H__

enum
{
	PREF_TAKE_MAIN_GROUP              = 999,

  PREF_TAKE_BASIC_GROUP             = 1000,
  PREF_TAKE_MAIN_AUTOTAKE           = 1001,

  PREF_TAKE_MANAGER_GROUP           = 2000,
  PREF_TAKE_MANAGER_SHOWATTRIBUTES  = 2001,
  PREF_TAKE_MANAGER_SIDEATTIBUTE    = 2002,
  PREF_TAKE_MANAGER_TREEMODE        = 2003,
    PREF_TAKE_MANAGER_TREEMODE_TAKE    = 0,
    PREF_TAKE_MANAGER_TREEMODE_OVER    = 1,
    PREF_TAKE_MANAGER_TREEMODE_DUAL    = 2,

  PREF_TAKE_DEFAULT_FILETR_GROUP    = 3001,
  PREF_TAKE_DEFAULT_FILETR_OBJ      = 3002,
  PREF_TAKE_DEFAULT_FILETR_TAG      = 3003,
  PREF_TAKE_DEFAULT_FILETR_MAT      = 3004,
  PREF_TAKE_DEFAULT_FILETR_SHD      = 3005,
  PREF_TAKE_DEFAULT_FILETR_LAY      = 3006,
  PREF_TAKE_DEFAULT_FILETR_OTH      = 3007,
  PREF_TAKE_DEFAULT_FILETR_VIS      = 3008,
  PREF_TAKE_DEFAULT_FILETR_TRN      = 3009,
  PREF_TAKE_DEFAULT_FILETR_PRM      = 3010,
  PREF_TAKE_DEFAULT_FILETR_CAM      = 3011,
  PREF_TAKE_DEFAULT_FILETR_RS       = 3012,

	PREF_PM_DUMMY
};

#endif // PREFSTAKE_H__
