#ifndef PREFSMEMORY_H__
#define PREFSMEMORY_H__

enum
{
	PREF_MEMORY_MAIN_GROUP		= 999,
	PREF_MEMORY_UNDO					= 1000,
	PREF_MEMORY_PVUSEAGE			= 1001,
	PREF_MEMORY_PVHARDUSAGE		= 1002,
	PREF_MEMORY_PVHARDUNLIMIT	= 1003,
	PREF_MEMORY_PVHARDFOLDER	= 1004,
	PREF_MEMORY_RENDERER			= 1005,
	PREF_MEMORY_MATERIAL			= 1006,
	PREF_MEMORY_BP						= 1007,
	PREF_MEMORY_BPUNDO				= 1008,
	PREF_MEMORY_SCULPTUSAGE		= 1009,
	PREF_MEMORY_PHFOOTAGEMAXCACHEMB = 1010,
	PREF_MEMORY_PHFOOTAGESYSRESERVEMB = 1011,

	//groups
	PREFS_MEMORY_PVGROUP					= 2000,
	PREFS_MEMORY_RENDGROUP				= 2001,
	PREFS_MEMORY_BPGROUP					= 2003,
	PREFS_MEMORY_DOCGROUP					= 2004,
	PREFS_MEMORY_SCULPTGROUP			= 2005,
	PREFS_MEMORY_PHGROUP					= 2006,

	PREFS_MEMORY_DUMMY
};

#endif // PREFSMEMORY_H__
