#ifndef PREFSCOLOR_H__
#define PREFSCOLOR_H__

enum
{
	PREF_COLOR_MAIN_GROUP = 999,
	PREF_COLOR_COLORS	= 1000,
	PREF_COLOR_LIST		= 1001,
	PREF_COLOR_RESET	= 1002,

	PREF_COLOR_DUMMY
};

#endif // PREFSCOLOR_H__
