#ifndef PREFSFILES_H__
#define PREFSFILES_H__

enum
{
	PREF_FILE_MAIN_GROUP				= 999,
	PREF_FILE_BACKUP						= 1001,
	PREF_FILE_AUTOEVERY					= 1003,
	PREF_FILE_AUTOMIN						= 1004,
	PREF_FILE_AUTOLIMIT					= 1005,
	PREF_FILE_AUTOCOPIES				= 1006,
	PREF_FILE_AUTOSAVETO				= 1007,
			PREF_FILE_AUTOSAVE_PRJ				= 0,
			PREF_FILE_AUTOSAVE_CST				= 1,
			PREF_FILE_AUTOSAVE_USR				= 2,

	PREF_FILE_AUTOSAVEDIR				= 1008,

	PREF_FILE_RECENT						= 1020,
	PREF_FILE_HELP							= 1021,

	ID_FILES_XREFPREFS_DEFERRED_LOAD	= 1024,
	ID_FILES_XREFPREFS_REDUCED_SAVE		= 1025,
	PREF_FILE_ASSETS_LINK							= 1027,
			PREF_FILE_ASSETS_LINK_RELATIVE		= 0,
			PREF_FILE_ASSETS_LINK_ABSOLUTE		= 1,
			PREF_FILE_ASSETS_LINK_ASK					= 2,

	PREF_FILE_TEXPATHS								= 1028,

	PREF_FILE_RENDER_OVERWRITE_DEFAULT = 1029,
		PREF_FILE_RENDER_OVERWRITE_DEFAULT_ASK = 0,
		PREF_FILE_RENDER_OVERWRITE_DEFAULT_OVERWRITE = 1,
		PREF_FILE_RENDER_OVERWRITE_DEFAULT_NEVEROVERWRITE = 2,
		PREF_FILE_RENDER_OVERWRITE_DEFAULT_SKIP = 3,

	PREF_WATCHFOLDER_AUTOMOUNT_SEARCHPATHS = 1030,

	PREF_DEFAULT_SCENE						 = 1031,
		PREF_DEFAULT_SCENE_BLANK		 	= 0,
		PREF_DEFAULT_SCENE_CUSTOM			= 1,
		PREF_DEFAULT_SCENE_EXAMPLE1		= 2,
	PREF_DEFAULT_SCENE_CUSTOM_FILE = 1032,
	
	PREF_FILE_LBWLIRARYPATH				= 1033,

	//groups
	PREFS_FILE_AUTOSAVE					= 2000,
	PREFS_FILE_BASIC						= 2002,
	ID_FILES_GROUP_XREF					= 2003,
	PREF_FILE_ASSETS						= 2004,
	PREF_FILE_STARTUP						= 2005,

	PREFS_FILE_DUMMY
};

#endif // PREFSFILES_H__
