#ifndef SCULPTPREFS_H__
#define SCULPTPREFS_H__

enum
{
	PREF_SCULPTPREF_MAIN_GROUP  = 999,

	PREF_MODELING_DISCONNECTED_POINTS_ON_DELETE					= 1031,
	PREF_MODELING_DISCONNECTED_POINTS_ON_DELETE_REMOVE	= 0,
	PREF_MODELING_DISCONNECTED_POINTS_ON_DELETE_KEEP		= 1,

	PREF_SCULPTPREF_MODELING_GROUP	= 1100,
	PREF_SCULPTPREF_SCULPTING_GROUP	= 1101,

	PREF_SCULPTPREF_BRUSH_STAMP_GROUP = 1200,
	PREF_SCULPTPREF_BRUSH_STAMP_GREYVALUE_DEFAULT = 1201,
	PREF_SCULPTPREF_BRUSH_STAMP_GREYVALUE_TOPLEFTPIXEL = 1202,
	PREF_SCULPTPREF_BRUSH_STAMP_MATERIAL_SAMPLERES = 1203,

	PREF_SCULPTPREF_BRUSH_STENCIL_GROUP = 1300,
	PREF_SCULPTPREF_BRUSH_STENCIL_GREYVALUE_DEFAULT = 1301,
	PREF_SCULPTPREF_BRUSH_STENCIL_GREYVALUE_TOPLEFTPIXEL = 1302,
	PREF_SCULPTPREF_BRUSH_STENCIL_MATERIAL_SAMPLERES = 1303,

	PREF_SCULPTPREF_OTHER_GROUP = 1400,
	PREF_SCULPTPREF_ALWAYS_UPDATE = 1401,
	PREF_SCULPTPREF_ALWAYS_UPDATE_THRESHOLD = 1402,

	PREF_SCULPTPREF_POLYGONOBJECT_GROUP = 1500,
	PREF_SCULPTPREF_DISPLAY_POLYGONOBJECT_NORMALS_THRESHOLD = 1502,

	PREF_SCULPTPREF_RESPECT_SELECTIONS = 1600,

	PREF_SCULPTPREF_DUMMY
};

#endif // SCULPTPREFS_H__
