#ifndef TJOINT_H__
#define TJOINT_H__

enum
{
	JOINT_OBJECTLINK = 7000,
	JOINT_ACTIVE = 7001,
	JOINT_TAG_MAINTAB = 7002,
	JOINT_TYPE = 7003,
	JOINT_OBJECT = 7011,

	JOINT_REFERENCE_X = 0,
	JOINT_REFERENCE_Y = 1,
	JOINT_REFERENCE_Z = 2,
	JOINT_REFERENCE_DIRECTION = 3,
	JOINT_REFERENCE = 7012,

	JOINT_APPLICATION_COM = 0,
	JOINT_APPLICATION_POLYPOINT = 2,
	JOINT_APPLICATION_POINT_SELECTION = 3,
	JOINT_APPLICATION = 7013,

	JOINT_POINT = 7014,
	JOINT_POINT_SELECTION = 7015,
	JOINT_POINT_SELECTION_SHAPE_CONSERVATION = 7016,
	JOINT_POINT_SELECTION_SHAPE_CONSERVATION_DAMPING = 7017,
	JOINT_REGION = 7019,

	JOINT_MOGRAPH_SELECTION_CONNECT = 7020,
	JOINT_MOGRAPH_SELECTION_PIN = 7021,

	JOINT_PIN_TO_WORLD = 7022,

	JOINT_OBJECT_HASH = 7023,
};

#endif // TVOLUMEBUILDER_H__