#ifndef TLOOKATCAMERA_H__
#define TLOOKATCAMERA_H__

enum
{
	LOOKATCAMERA_PITCH = 1000,
	LOOKATCAMERA_BANK = 1001,
	LOOKATCAMERA_MODE = 1002,
		LOOKATCAMERA_MODE_FACE = 0,
		LOOKATCAMERA_MODE_ALIGN = 1,
	LOOKATCAMERA_INVERT = 1003
};

#endif // TLOOKATCAMERA_H__