#ifndef TOOLUDIMMOVETOTILE_H__
#define TOOLUDIMMOVETOTILE_H__

enum
{
	MDATA_TOOLUDIMMOVETOTILE_IDXU = 1100, // long
	MDATA_TOOLUDIMMOVETOTILE_IDXV = 1101, // long
	MDATA_TOOLUDIMMOVETOTILE_
};

#endif // TOOLUDIMMOVETOTILE_H__
