#ifndef TOOLCAPAINT_H__
#define TOOLCAPAINT_H__

enum
{
	ID_CA_PAINT_TOOL_DISPLAY_GROUP = 15000,
	ID_CA_PAINT_TOOL_PAINT_GROUP,
	ID_CA_PAINT_TOOL_SYMMETRY_GROUP,

	ID_CA_PAINT_TOOL_DISPLAY_LOWER = 12000,
	ID_CA_PAINT_TOOL_DISPLAY_UPPER,
	ID_CA_PAINT_TOOL_DISPLAY_COLOR,
	ID_CA_PAINT_TOOL_DISPLAY_CURSOR_COLOR,
	ID_CA_PAINT_TOOL_DISPLAY_COLOR_CUSTOM,

	ID_CA_PAINT_TOOL_SMOOTH,
	ID_CA_PAINT_TOOL_SPLINE,
	ID_CA_PAINT_TOOL_APPLY_ALL,
	ID_CA_PAINT_TOOL_APPLY_SELECTED,

	ID_CA_PAINT_TOOL_MODE,
	ID_CA_PAINT_TOOL_SYMMETRY,
	ID_CA_PAINT_TOOL_SYMMETRY_RAD,
	ID_CA_PAINT_TOOL_SYMMETRY_COORD,
	ID_CA_PAINT_TOOL_SYMMETRY_MIRROR,
	ID_CA_PAINT_TOOL_SYMMETRY_COORD_CUSTOM_OBJECT,

	ID_CA_PAINT_TOOL_MAINMODE,
	ID_CA_PAINT_TOOL_VERTEXCOLOR,

	ID_CA_PAINT_TOOL_COLORMODE,
	ID_CA_PAINT_TOOL_OPACITY,
	ID_CA_PAINT_TOOL_VERTEXCOLOR_APLHAVALUE,
	ID_CA_PAINT_TOOL_VERTEXCOLOR_GROUP,

	ID_CA_PAINT_TOOL_MAINMODE_VERTEXMAP = 0,
	ID_CA_PAINT_TOOL_MAINMODE_VERTEXCOLOR,
	ID_CA_PAINT_TOOL_MAINMODE_VERTEXCOLOR_ALPHA,
	ID_CA_PAINT_TOOL_MAINMODE_VERTEXALPHA,

	ID_CA_PAINT_TOOL_MODE_ADD = 0,
	ID_CA_PAINT_TOOL_MODE_SUBTRACT,
	ID_CA_PAINT_TOOL_MODE_ABS,
	ID_CA_PAINT_TOOL_MODE_SMOOTH,
	ID_CA_PAINT_TOOL_MODE_BLEED,
	ID_CA_PAINT_TOOL_MODE_INTENSITY,
	ID_CA_PAINT_TOOL_MODE_REMAP,
	ID_CA_PAINT_TOOL_MODE_PRUNE,
	ID_CA_PAINT_TOOL_MODE_AVERAGE,

	ID_CA_PAINT_TOOL_COLORMODE_NORMAL = 0,
	ID_CA_PAINT_TOOL_COLORMODE_ADD,
	ID_CA_PAINT_TOOL_COLORMODE_SUB,
	ID_CA_PAINT_TOOL_COLORMODE_MUL,
	ID_CA_PAINT_TOOL_COLORMODE_LIG,
	ID_CA_PAINT_TOOL_COLORMODE_DARK,
	ID_CA_PAINT_TOOL_COLORMODE_SMOOTH,
	ID_CA_PAINT_TOOL_COLORMODE_BLEED,
	ID_CA_PAINT_TOOL_COLORMODE_INTENSITY,
	ID_CA_PAINT_TOOL_COLORMODE_REMAP,
	ID_CA_PAINT_TOOL_COLORMODE_AVERAGE,

	ID_CA_PAINT_TOOL_SYMMETRY_COORD_LOCAL = 0,
	ID_CA_PAINT_TOOL_SYMMETRY_COORD_WORLD,
	ID_CA_PAINT_TOOL_SYMMETRY_COORD_CUSTOM,

	ID_CA_PAINT_TOOL_SYMMETRY_MIRROR_XY = 0,
	ID_CA_PAINT_TOOL_SYMMETRY_MIRROR_YZ,
	ID_CA_PAINT_TOOL_SYMMETRY_MIRROR_XZ,

	ID_CA_PAINT_TOOL_DUMMY
};

#endif // TOOLCAPAINT_H__
