#ifndef TOOLRAYPLACEMENT_H__
#define TOOLRAYPLACEMENT_H__

enum
{
	ID_RAYPLACEMENT_REFERENCE_TYPE = 1000,
  	ID_RAYPLACEMENT_AXIS = 0,
  	ID_RAYPLACEMENT_BOUNDINGBOX = 1,
  ID_RAYPLACEMENT_OFFSET = 1001,
	ID_RAYPLACEMENT_COLLISION = 1002
};

#endif // TOOLRAYPLACEMENT_H__