#ifndef TOOLARRANGE_H__
#define TOOLARRANGE_H__

enum
{
	ID_GROUP_SCALE												= 1000,
	ID_GROUP_ROTATION											,
	ID_GROUP_POSITION											,
	ID_GROUP_LOCKING											,

	MDATA_ARRANGE_MODE										= 1100,
		MDATA_ARRANGE_MODE_SELECTMODE					= 0,
		MDATA_ARRANGE_MODE_LINEAR							= 1,
		MDATA_ARRANGE_MODE_CIRCLE							= 2,
		MDATA_ARRANGE_MODE_ALONGSPLINE				= 3,

	MDATA_ARRANGE_LINEAR_MOVE							= 2000,
	MDATA_ARRANGE_LINEAR_SCALE						,
	MDATA_ARRANGE_LINEAR_ROTATION					,
	MDATA_ARRANGE_LINEAR_PERSTEP					,
	MDATA_ARRANGE_LINEAR_USE_MOVE_X				,
	MDATA_ARRANGE_LINEAR_USE_MOVE_Y				,
	MDATA_ARRANGE_LINEAR_USE_MOVE_Z				,
	MDATA_ARRANGE_LINEAR_USE_ROTATION			,
	MDATA_ARRANGE_LINEAR_USE_SCALE				,
	MDATA_ARRANGE_LINEAR_USE_MOVE					,

	MDATA_ARRANGE_CIRCLE_START						= 3000,
	MDATA_ARRANGE_CIRCLE_END							,
	MDATA_ARRANGE_CIRCLE_RADIUS						,
	MDATA_ARRANGE_CIRCLE_ALIGNTANGENTIAL	,
	MDATA_ARRANGE_CIRCLE_MOVE							,
	MDATA_ARRANGE_CIRCLE_SCALE						,
	MDATA_ARRANGE_CIRCLE_ROTATION					,
	MDATA_ARRANGE_CIRCLE_PERSTEP					,
	MDATA_ARRANGE_CIRCLE_USE_MOVE_X				,
	MDATA_ARRANGE_CIRCLE_USE_MOVE_Y				,
	MDATA_ARRANGE_CIRCLE_USE_MOVE_Z				,
	MDATA_ARRANGE_CIRCLE_USE_ROTATION			,
	MDATA_ARRANGE_CIRCLE_USE_SCALE				,
	MDATA_ARRANGE_CIRCLE_USE_MOVE					,

	MDATA_ARRANGE_SPLINE_LINK 						= 4000,
	MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL	,
		MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_X		= 1,
		MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_XN		= 2,
		MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_Y		= 3,
		MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_YN		= 4,
		MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_Z		= 5,
		MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_ZN		= 6,
	MDATA_ARRANGE_SPLINE_FLIP							,
	MDATA_ARRANGE_SPLINE_SCALE						,
	MDATA_ARRANGE_SPLINE_ROTATION					,
	MDATA_ARRANGE_SPLINE_PERSTEP					,
	MDATA_ARRANGE_SPLINE_USE_MOVE_X				,
	MDATA_ARRANGE_SPLINE_USE_MOVE_Y				,
	MDATA_ARRANGE_SPLINE_USE_MOVE_Z				,
	MDATA_ARRANGE_SPLINE_USE_ROTATION			,
	MDATA_ARRANGE_SPLINE_USE_SCALE				,
	MDATA_ARRANGE_SPLINE_USE_MOVE					,
	MDATA_ARRANGE_SPLINE_RAIL							,
	MDATA_ARRANGE_SPLINE_STARTPOS					,
	MDATA_ARRANGE_SPLINE_ENDPOS						,

	MDATA_ARRANGE_
};

#endif // TOOLARRANGE_H__
