#ifndef TOOLSETEDGESLINEAR_H__
#define TOOLSETEDGESLINEAR_H__

enum
{
	MDATA_SETEDGESLINEAR_EQUALSPACING   = 1100, //BOOL
	MDATA_SETEDGESLINEAR_WEIGHT         = 1101, //REAL
};

#endif // TOOLSETEDGESLINEAR_H__
