#ifndef TOOLSPLINESKETCH_H__
#define TOOLSPLINESKETCH_H__

enum
{
	MDATA_SPLINESKETCH_SMOOTHING	 = 1100,	// Real
	MDATA_SPLINESKETCH_AUTOSHAPE	 = 1101,	// Boolean
	MDATA_SPLINESKETCH_AUTOSHAPE3D = 1102,	// Boolean
	MDATA_SPLINESKETCH_TRANSFORM	 = 1103,	// Boolean
	MDATA_SPLINESKETCH_RADIUS			 = 1104,	// Float
	MDATA_SPLINESKETCH_BLEND			 = 1105,	// Float
	MDATA_SPLINESKETCH_SMOOTH			 = 1106,	// Boolean
	MDATA_SPLINESKETCH_NEWSPLINE	 = 1107,	// Boolean
	MDATA_SPLINESKETCH_DUMMY__
};

#endif	// TOOLSPLINESKETCH_H__
