#ifndef TOOLSPLINESMOOTH_H__
#define TOOLSPLINESMOOTH_H__

enum
{
	MDATA_SPLINESMOOTH_RADIUS			= 1100,	// Float
	MDATA_SPLINESMOOTH_STRENGTH		=	1101,	// Float
	MDATA_SPLINESMOOTH_SMOOTH			= 1102,	// Float
	MDATA_SPLINESMOOTH_SMOOTH_ON	= 1103,	// Boolean
	MDATA_SPLINESMOOTH_FLATTEN		= 1104,	// Float
	MDATA_SPLINESMOOTH_FLATTEN_ON	= 1105,	// Float
	MDATA_SPLINESMOOTH_RANDOM			=	1106,	// Float
	MDATA_SPLINESMOOTH_RANDOM_ON	=	1107,	// Float
	MDATA_SPLINESMOOTH_PULL				=	1108,	// Float
	MDATA_SPLINESMOOTH_PULL_ON		=	1109,	// Float
	MDATA_SPLINESMOOTH_SPIRAL			= 1110,	// Float
	MDATA_SPLINESMOOTH_SPIRAL_ON	= 1111,	// Float
	MDATA_SPLINESMOOTH_INFLATE		=	1112,	// Float
	MDATA_SPLINESMOOTH_INFLATE_ON	=	1113,	// Float
	MDATA_SPLINESMOOTH_PROJECT		= 1114,	// Float
	MDATA_SPLINESMOOTH_PROJECT_ON	= 1115,	// Float

	MDATA_SPLINESMOOTH_DUMMY__
};

#endif	// TOOLSPLINESMOOTH_H__
