#ifndef TOOLSCULPTBRUSHGRAB_H__
#define TOOLSCULPTBRUSHGRAB_H__

enum
{
	MDATA_TOOLSCULPTBRUSHGRAB_START = 3000,
	MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE,
		MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_MOUSEDIR,
		MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_NORMAL,
		MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_X,
		MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_Y,
		MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_Z,
};

#endif // TOOLSCULPTBRUSHGRAB_H__
