#ifndef TOOLEDGESMOOTH_H__
#define TOOLEDGESMOOTH_H__

enum
{
	MDATA_EDGESMOOTH_STEPS					= 1100, //LONG
	MDATA_EDGESMOOTH_SELECTOUTLINE	= 1101, //BOOL
	MDATA_EDGESMOOTH_KEEPSPACING		= 1102, //BOOL
};

#endif // TOOLEDGESMOOTH_H__
