#ifndef TOOLSETOBJECT_H__
#define TOOLSETOBJECT_H__

enum
{
	ID_MAIN_GROUP          = 1000,

	SETOBJECT_OBJ          = 10000,
	SETOBJECT_AZIMUTH      = 10001,
	SETOBJECT_ALTTUDE      = 10002,
	SETOBJECT_FILENAME     = 10003,

	SETOBJECT_
};

#endif // TOOLSETOBJECT_H__
