#ifndef TOSCCONTROLLER_H__
#define TOSCCONTROLLER_H__

enum
{
	OSC_TRANSFORM_SMOOTHNESS = 4000,
	OSC_TRANSFORM_XY_MOVEMENT_METHOD_NAME = 4001,
	OSC_TRANSFORM_Z_MOVEMENT_METHOD_NAME = 4002,
	OSC_TRANSFORM_TOUCH_METHOD_NAME = 4003,
	OSC_TRANSFORM_SET_XY_MOVEMENT_METHOD_NAME = 4004,
	OSC_TRANSFORM_SET_Z_MOVEMENT_METHOD_NAME = 4005,
	OSC_TRANSFORM_SET_TOUCH_METHOD_NAME = 4006,
	OSC_TRANSFORM_MOVEMENT_SPEED = 4007
};

#endif // TOSCCONTROLLER_H__



