#ifndef TPBDLIQUID_H__
#define TPBDLIQUID_H__

enum
{
	// Base params
	PBD_LIQUID_USE = 1000,
	PBD_LIQUID_SIMULATION_PRIORITY = 1001,

	// Main Params
	PBD_LIQUID_TAG_GROUP = 2000,

	// Radius
	PBD_LIQUID_RADIUS_GROUP       = 2100,
	PBD_LIQUID_RADIUS_USE_DEFAULT = 2101,

	// Constraints
	PBD_LIQUID_CONSTRAINTS_GROUP           = 2200,
	PBD_LIQUID_CONSTRAINTS_MASSDENSITY     = 2201,
	PBD_LIQUID_CONSTRAINTS_VISCOSITY       = 2202,
	PBD_LIQUID_CONSTRAINTS_SURFACE_TENSION = 2203,
	PBD_LIQUID_CONSTRAINTS_MIXTURE         = 2204,
	PBD_LIQUID_CONSTRAINTS_EASEIN          = 2205,

	// Collisions
	PBD_LIQUID_COLLISIONS_GROUP      = 2300,
	PBD_LIQUID_COLLISIONS_FRICTION   = 2301,
	PBD_LIQUID_COLLISIONS_STICKINESS = 2302,

	// Damping
	PBD_LIQUID_DAMPING_GROUP = 2400,
	PBD_LIQUID_DAMPING_OVERRIDE = 2401,
	PBD_LIQUID_DAMPING_STRENGTH = 2402,

	// Simulate
	PBD_LIQUID_SIMULATE = 2501,

	PBD_LIQUID_TAG_DUMMY
};

#endif // TPBDLIQUID_H__
