#ifndef TPBDLIQUID_H__
#define TPBDLIQUID_H__

enum
{
	// Base params
	PBD_LIQUID_USE = 1000,
	PBD_LIQUID_SIMULATION_PRIORITY = 1001,

	// Main Params
	PBD_LIQUID_TAG_GROUP = 2000,
	PBD_LIQUID_MASS = 2001,
	PBD_LIQUID_RADIUS = 2002,
	PBD_LIQUID_FRICTION = 2003,
	PBD_LIQUID_BOUNCINESS = 2004,
	PBD_LIQUID_STICKINESS = 2005,

	PBD_LIQUID_TAG_DUMMY
};

#endif // TPBDLIQUID_H__
