#ifndef TANIMWAYPOINT_H__
#define TANIMWAYPOINT_H__

enum
{
	ID_ANIM_WAYPOINT_LIST_GROUP = 1000,
	ID_ANIM_WAYPOINT_LIST = 1001,

	ID_ANIM_WAYPOINT_SETTINGS_GROUP = 1100,
	ID_ANIM_WAYPOINT_SETTINGS_START_TIME = 1101,
	ID_ANIM_WAYPOINT_SETTINGS_END_TIME = 1102,

	ID_ANIM_WAYPOINT_SETTINGS_INTERPOLATION = 1103,
	ID_ANIM_WAYPOINT_SETTINGS_INTERPOLATION_LINEAR = 1,
	ID_ANIM_WAYPOINT_SETTINGS_INTERPOLATION_SQUARE = 2,
	ID_ANIM_WAYPOINT_SETTINGS_INTERPOLATION_CUBIC = 3,
	ID_ANIM_WAYPOINT_SETTINGS_INTERPOLATION_CUBIC_MONOTONE = 4,

	ID_ANIM_WAYPOINT_SETTINGS_TIME_INTERPOLATION = 1104,
	ID_ANIM_WAYPOINT_SETTINGS_TIME_INTERPOLATION_DEFAULT = (0 << 0),
	ID_ANIM_WAYPOINT_SETTINGS_TIME_INTERPOLATION_EASYEASE = (1 << 0 | 1 << 1),
	ID_ANIM_WAYPOINT_SETTINGS_TIME_INTERPOLATION_EASEIN = (1 << 0),
	ID_ANIM_WAYPOINT_SETTINGS_TIME_INTERPOLATION_EASEOUT = (1 << 1),

	ID_ANIM_WAYPOINT_SETTINGS_QUATERNION = 1105,
	ID_ANIM_WAYPOINT_SETTINGS_TIME_INTERPOLATION_FACTOR = 1106,
	ID_ANIM_WAYPOINT_SETTINGS_NORMALISE_DISTANCE = 1110,
	ID_ANIM_WAYPOINT_SETTINGS_DRAW_PATH = 1111,
	ID_ANIM_WAYPOINT_SETTINGS_REVERSE_DIRECTION = 1112,

	ID_ANIM_WAYPOINT_SETTINGS_ROTATION = 1200,
	ID_ANIM_WAYPOINT_SETTINGS_ROTATION_SLERP = 0,
	ID_ANIM_WAYPOINT_SETTINGS_ROTATION_LERP = 1,
	ID_ANIM_WAYPOINT_SETTINGS_ROTATION_SPLINE = 2,
};

#endif