#ifndef VPAMBIENTOCCLUSION_H__
#define VPAMBIENTOCCLUSION_H__

enum
{
	VPAMBIENTOCCLUSION_MINLENGTH		= 1002,
	VPAMBIENTOCCLUSION_MAXLENGTH		= 1003,
	VPAMBIENTOCCLUSION_DISPERSION		= 1004,
	VPAMBIENTOCCLUSION_MINSAMPLES		= 1005,
	VPAMBIENTOCCLUSION_MAXSAMPLES		= 1006,
	VPAMBIENTOCCLUSION_CONTRAST		= 1007,
	VPAMBIENTOCCLUSION_ENVIRONMENT		= 1008,
	VPAMBIENTOCCLUSION_ACCURACY		= 1009,
	VPAMBIENTOCCLUSION_GRADIENT    		= 1010,
	VPAMBIENTOCCLUSION_TRANSPARENCY 	= 1011,
	VPAMBIENTOCCLUSION_SELFTEST     	= 1012,
	VPAMBIENTOCCLUSION_APPLYTOSCENE 	= 1013,
	VPAMBIENTOCCLUSION_REVERSE				= 1014,

	// --- Cache
	VPAMBIENTOCCLUSION_CACHE_ENABLE		= 2000,
	VPAMBIENTOCCLUSION_CACHE_SAMPLES,
	// ---
	VPAMBIENTOCCLUSION_CACHE_QUALITY	= 2100,
	VPAMBIENTOCCLUSION_CACHE_RATE_MIN,
	VPAMBIENTOCCLUSION_CACHE_RATE_MAX,
	VPAMBIENTOCCLUSION_CACHE_DENSITY,
	VPAMBIENTOCCLUSION_CACHE_DETAILS,
	VPAMBIENTOCCLUSION_CACHE_MAX_LIMIT,
	VPAMBIENTOCCLUSION_CACHE_SMOOTHING,
	VPAMBIENTOCCLUSION_CACHE_SCALE,

	// --- Files
	VPAMBIENTOCCLUSION_CACHE_FILE_FLUSH 	= 2200,
	VPAMBIENTOCCLUSION_CACHE_FILE_SIZE,
	VPAMBIENTOCCLUSION_CACHE_FILE_LOCK,
	VPAMBIENTOCCLUSION_CACHE_FILE_AUTOLOAD,
	VPAMBIENTOCCLUSION_CACHE_FILE_AUTOSAVE,
	VPAMBIENTOCCLUSION_CACHE_FILE_PATH_ENABLED,
	VPAMBIENTOCCLUSION_CACHE_FILE_PATH,
	VPAMBIENTOCCLUSION_CACHE_FILE_ANIMATION,

	// ---
	VPAMBIENTOCCLUSION_GROUP_CACHE		= 2900,
	VPAMBIENTOCCLUSION_GROUP_CACHE_FILE,
	VPAMBIENTOCCLUSION_GROUP_CACHE_LOCATION,

	// ---
	VPAMBIENTOCCLUSION_CACHE_QUALITY_CUSTOM	= 0,
	VPAMBIENTOCCLUSION_CACHE_QUALITY_PREVIEW,
	VPAMBIENTOCCLUSION_CACHE_QUALITY_LOW,
	VPAMBIENTOCCLUSION_CACHE_QUALITY_MEDIUM,
	VPAMBIENTOCCLUSION_CACHE_QUALITY_HIGH,

};

#endif // VPAMBIENTOCCLUSION_H__
