#ifndef XFIRE_H__
#define XFIRE_H__

enum
{
	FIRESHADER_SCALEX			= 1000, // REAL
	FIRESHADER_SCALEY 		= 1001, // REAL
	FIRESHADER_TURBULENCE	= 1002,	// REAL
	FIRESHADER_FREQUENCY	= 1003, // REAL
	FIRESHADER_COLOR			= 1004	// GRADIENT
};

#endif // XFIRE_H__
