#ifndef XPAVEMENT_H__
#define XPAVEMENT_H__

enum
{
	PAVEMENT_GROUP_DIMENSIONS							= 10000,		// GROUP
	PAVEMENT_SCALE												= 10001,		// REAL
	PAVEMENT_SEED													= 10002,		// LONG

	PAVEMENT_GROUP_GAPS										= 10010,		// GROUP
	PAVEMENT_GAP_SIZE											= 10011,		// REAL
	PAVEMENT_GAP_BLUR											= 10012,		// REAL
	PAVEMENT_GAP_CROOKED_INTENSITY				= 10013,		// REAL
	PAVEMENT_GAP_CROOKED_SCALE						= 10014,		// REAL

	PAVEMENT_GROUP_COLOR									= 10020,		// GROUP
	PAVEMENT_COL_STONE										= 10021,		// GRADIENT
	PAVEMENT_COL_STONE_STRUCT1						= 10028,		// REAL
	PAVEMENT_COL_STONE_STRUCT2						= 10029,		// REAL
	PAVEMENT_COL_GAP											= 10022,		// GRADIENT
	PAVEMENT_COL_GRAINYGAPS								= 10026,		// REAL
	PAVEMENT_COL_GRAINYGAPS_MODE					= 10027,		// BOOL
	PAVEMENT_COL_SMUDGE										= 10025,		// GRADIENT
	PAVEMENT_COL_SMUDGYEDGES							= 10023,		// REAL
	PAVEMENT_COL_SMUDGYEDGES_SIZE					= 10024			// REAL
};
#endif // XPAVEMENT_H__
