#ifndef XSLIDETOOL_H__
#define XSLIDETOOL_H__

enum
{
	MDTA_SLIDE_OFFSET				= 1000,
	MDTA_SLIDE_SHIFT				= 1001,
	MDTA_SLIDE_OFFSET_MODE	= 1002,
		MDTA_SLIDE_OFFSET_MODE_FIXED = 0,
		MDTA_SLIDE_OFFSET_MODE_PROPORTIONAL = 1,
	MDTA_SLIDE_OFFSET_LIMIT = 1003,
	MDTA_SLIDE_CURVATURE    = 1004,
	MDTA_SLIDE_CLONE				= 1005,
	MDTA_SLIDE_TEMP_CLONE		= 1006,
	MDTA_SLIDE_TARGET_OBJ_IDX = 1007,
	MDTA_SLIDE_TARGET_EDGE_IDX_1   = 1008,
	MDTA_SLIDE_TARGET_EDGE_IDX_2   = 1009
};

#endif // XSLIDETOOL_H__
