#ifndef XSPOTSHADER_H__
#define XSPOTSHADER_H__

enum
{
	SPOTSHADER_SHADOW = 10000,
	SPOTSHADER_DIFFUSE,
	SPOTSHADER_SPEC,
	SPOTSHADER_CAMERA,
	SPOTSHADER_LIGHTS,
	SPOTSHADER_ILLUMINATION,
	SPOTSHADER_SHADOWS,

	SPOTSHADER_DUMMY,

	SPOTSHADER_INVERT,
	SPOTSHADER_ILLUM,
	SPOTSHADER_SPECULAR,
	SPOTSHADER_GAP_COLOR,
	SPOTSHADER_CIRCLE_COLOR,
	SPOTSHADER_SCALE,
	SPOTSHADER_SCALE_U,
	SPOTSHADER_SCALE_V,
	SPOTSHADER_GAP_SHAPE,
	SPOTSHADER_GAP_TEXTURE,

	SPOTSHADER_ROTATE,

	SPOTSHADER_INCEXC,
	SPOTSHADER_INCEXC_LIGHTS,

	//

	SPOTSHADER_INCEXC_INCLUDE = 0,
	SPOTSHADER_INCEXC_EXCLUDE,

	SPOTSHADER_GAP_SHAPE_CIRCLE = 0,
	SPOTSHADER_GAP_SHAPE_DIAMOND,
	SPOTSHADER_GAP_SHAPE_CHECKER,
	SPOTSHADER_GAP_SHAPE_SQUARE,
	SPOTSHADER_GAP_SHAPE_ULINES,
	SPOTSHADER_GAP_SHAPE_VLINES,
	SPOTSHADER_GAP_SHAPE_GRID,
	SPOTSHADER_GAP_SHAPE_TEXTURE
};

#endif // XSPOTSHADER_H__
