#ifndef XSSS_H__
#define XSSS_H__

enum
{
	SSSSHADER_STRENGTH					= 1001,	// REAL
	SSSSHADER_DENSITY						= 1002,	// REAL
	SSSSHADER_SAMPLES						= 1003,	// LONG
	SSSSHADER_MINTHICKNESS			= 1004,	// REAL
	SSSSHADER_SCATTERINGLENGTH	= 1005,	// REAL
	SSSSHADER_USE_NORMALS				= 1006, // BOOL
	SSSSHADER_GRADIENT					= 1007, // GRADIENT
	SSSSHADER_COLORDENSITY			= 1008	// REAL
};

#endif // XSSS_H__
