#ifndef XTHINFILM_H__
#define XTHINFILM_H__

enum
{
	THINFILMSHADER_LAYERCOLOR									= 1000,		// VECTOR
	THINFILMSHADER_LAYERCOLOR_TEX_LINK				= 1001,		// SHADERLINK
	THINFILMSHADER_LAYERMIXSTRENGTH						= 1002,		// REAL
		
	THINFILMSHADER_RELATIVETHICKNESS					= 1010,		// REAL
	THINFILMSHADER_RELATIVECHANGE_TEX_LINK		= 1011,		// SHADERLINK
	THINFILMSHADER_AVERAGETHICKNESS						= 1012,		// REAL

	THINFILMSHADER_IOR												= 1013,		// REAL
	THINFILMSHADER_NUMSPECTRALSAMPLE					= 1014,		// LONG

	THINFILMSHADER_IOR_PRESET									= 2000,
		THINFILMSHADER_IOR_PRESET_CUSTOM				= 0,
		THINFILMSHADER_IOR_PRESET_BEER					= 1,
		THINFILMSHADER_IOR_PRESET_DIAMOND				= 2,
		THINFILMSHADER_IOR_PRESET_EMERALD				= 3,
		THINFILMSHADER_IOR_PRESET_ETHANOL				= 4,
		THINFILMSHADER_IOR_PRESET_GLASS					= 5,
		THINFILMSHADER_IOR_PRESET_JADE					= 6,
		THINFILMSHADER_IOR_PRESET_MILK					= 7,
		THINFILMSHADER_IOR_PRESET_OIL_VEGETABLE	= 8,
		THINFILMSHADER_IOR_PRESET_PEARL					= 9,
		THINFILMSHADER_IOR_PRESET_PET						= 10,
		THINFILMSHADER_IOR_PRESET_PLEXIGLASS		= 11,
		THINFILMSHADER_IOR_PRESET_RUBY					= 12,
		THINFILMSHADER_IOR_PRESET_SAPPHIRE			= 13,
		THINFILMSHADER_IOR_PRESET_WATER					= 14,
		THINFILMSHADER_IOR_PRESET_WATER_ICE			= 15,
		THINFILMSHADER_IOR_PRESET_WHISKEY				= 16
};

#endif // XTHINFILM_H__
