#ifndef XTURBULENCE_H__
#define XTURBULENCE_H__

enum
{
	TURBULENCESHADER_SCALEX		= 1002,	 // REAL
	TURBULENCESHADER_SCALEY		= 1003,	 // REAL
	TURBULENCESHADER_OCTAVES	= 1004,	 // REAL
	TURBULENCESHADER_COLOR 		= 1005   // GRADIENT
};

#endif // XTURBULENCE_H__
