#ifndef XUVPEELERTOOL_H__
#define XUVPEELERTOOL_H__

enum
{
	MDATA_UVPEELER_GROUP_OPTIONS				= 1000,
	MDATA_UVPEELER_MIN_U								= 1001,
	MDATA_UVPEELER_MIN_V								= 1002,
	MDATA_UVPEELER_MAX_U								= 1003,
	MDATA_UVPEELER_MAX_V								= 1004,
	MDATA_UVPEELER_U_UNIFORMITY					= 1005,
	MDATA_UVPEELER_INFOS_SEAMS					= 1006,
	MDATA_UVPEELER_INFOS_INVALID				= 1007,		// ignored but kept to prevent breaking existing test scenes
	MDATA_UVPEELER_GROUP_COMMANDGROUP		= 1008,
	MDATA_UVPEELER_APPLY								= 1009,
	MDATA_UVPEELER_U_CENTER							= 1010,
	MDATA_UVPEELER_V_CENTER							= 1011,
	MDATA_UVPEELER_U_INVERT							= 1012,
	MDATA_UVPEELER_V_INVERT							= 1013,
	MDATA_UVPEELER_EQUIDISTANT_UNIFORMITY	= 1014,
	MDATA_UVPEELER_V_UNIFORMITY					= 1015,
	MDATA_UVPEELER_UV_ISLAND_STORAGE		= 1016,
	MDATA_UVPEELER_FIXED_RING_LENGTHS		= 1017,
	MDATA_UVPEELER_SINGLE_UV_TILE				= 1,
	MDATA_UVPEELER_MULTIPLE_UV_TILES		= 2,
	MDATA_UVPEELER_GROUP_ADVANCED				= 1018,
	MDATA_UVPEELER_AUTO_FIT_TO_SCREEN		= 1019,
	MDATA_UVPEELER_RESTRICT_TO_TILES		= 1020,
	MDATA_UVPEELER_INTERACTIVE					= 1021,
	MDATA_UVPEELER_RESET								= 702
};

#endif // XUVPEELERTOOL_H__

