#ifndef XWATER_H__
#define XWATER_H__

enum
{
	WATERSHADER_SCALEX		= 1000,	 // REAL
	WATERSHADER_SCALEY		= 1001,	 // REAL
	WATERSHADER_FREQUENCY	= 1002,	 // REAL
	WATERSHADER_WIND			= 1003,	 // REAL
	WATERSHADER_COLOR 		= 1006   // GRADIENT
};

#endif // XWATER_H__
