#ifndef ZMULTIPASS_H__
#define ZMULTIPASS_H__

enum
{
	MULTIPASSOBJECT_TYPE						=	1000,
	MULTIPASSOBJECT_BLENDDATA				= 1001, // BaseContainer
	MULTIPASSOBJECT_OBJECTBUFFER		= 1002,
	MULTIPASSOBJECT_REFLECTIONDATA	= 1003,
	MULTIPASSOBJECT_SPECULARDATA		= 1004,
	MULTIPASSOBJECT_AOVBUFFER				= 1005,

	MULTIPASSOBJECT_AMBIENT					= 2000,
	MULTIPASSOBJECT_DIFFUSE					= 2001,
	MULTIPASSOBJECT_SPECULAR				= 2002,
	MULTIPASSOBJECT_SHADOW					= 2003,
	MULTIPASSOBJECT_REFLECTION			= 2004,
	MULTIPASSOBJECT_TRANSPARENCY		= 2005,
	MULTIPASSOBJECT_RADIOSITY				= 2006,
	MULTIPASSOBJECT_CAUSTICS				= 2007,
	MULTIPASSOBJECT_ATMOSPHERE			= 2008,
	MULTIPASSOBJECT_ATMOSPHERE_MUL	= 2009,
	MULTIPASSOBJECT_ALLPOSTEFFECTS	= 2010,

	MULTIPASSOBJECT_REFLECTION_MATERIALS						= 3000,
		MULTIPASSOBJECT_REFLECTION_SEPARATE_NONE			= 0,
		MULTIPASSOBJECT_REFLECTION_SEPARATE_ALL				= 1,
		MULTIPASSOBJECT_REFLECTION_SEPARATE_SELECTED	= 2,
	MULTIPASSOBJECT_REFLECTION_LAYERS								= 3001,
		MULTIPASSOBJECT_REFLECTION_LAYERS_NONE				= 0,
		MULTIPASSOBJECT_REFLECTION_LAYERS_ALL					= 1,
		MULTIPASSOBJECT_REFLECTION_LAYERS_SELECTED		= 2,
	MULTIPASSOBJECT_REFLECTION_MODE									= 3002,
		MULTIPASSOBJECT_REFLECTION_MODE_NORMAL				= 0,
		MULTIPASSOBJECT_REFLECTION_MODE_RAW						= 1,
		MULTIPASSOBJECT_REFLECTION_MODE_COMBINED			= 2,

	MULTIPASSOBJECT_SPECULAR_MATERIALS							= 3010,
		MULTIPASSOBJECT_SPECULAR_SEPARATE_NONE				= 0,
		MULTIPASSOBJECT_SPECULAR_SEPARATE_ALL					= 1,
		MULTIPASSOBJECT_SPECULAR_SEPARATE_SELECTED		= 2,
	MULTIPASSOBJECT_SPECULAR_LAYERS									= 3011,
		MULTIPASSOBJECT_SPECULAR_LAYERS_NONE					= 0,
		MULTIPASSOBJECT_SPECULAR_LAYERS_ALL						= 1,
		MULTIPASSOBJECT_SPECULAR_LAYERS_SELECTED			= 2,
	MULTIPASSOBJECT_SPECULAR_MODE										= 3012,
		MULTIPASSOBJECT_SPECULAR_MODE_NORMAL					= 0,
		MULTIPASSOBJECT_SPECULAR_MODE_RAW							= 1,
		MULTIPASSOBJECT_SPECULAR_MODE_COMBINED				= 2,

	MULTIPASSOBJECT_DUMMY
};

#endif // ZMULTIPASS_H__
