#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__
enum
{
	// string table definitions
	IDS_MES_OPENFILE = 10000,
	IDS_MES_SAVEFILE,
	IDS_MES_SELECT_ERR,
	IDS_MES_MEM_ERR,
	IDS_MES_OPEN_FILE_ERR,

	IDS_MES_IMPORT_ERR,
	IDS_MES_IMPORT_TYPE_ERR,
	IDS_MES_IMPORT_READ_ERR,
	IDS_MES_IMPORT_CAM_ERR,
	IDS_MES_IMPORT_OK,

	IDS_MES_EXPORT_ERR,
	IDS_MES_EXPORT_TYPE_ERR,
	IDS_MES_EXPORT_TRACK_ERR,
	IDS_MES_EXPORT_WRITE_ERR,
	IDS_MES_EXPORT_OK,

	IDS_VMD_TOOL_TITLE,
	IDS_VMD_CAM_TOOL_TITLE,

	IDS_VMD_CAM_IMPORT_TITLE,
	IDS_VMD_CAM_IMPORT_SIZE_NAME,
	IDS_VMD_CAM_IMPORT_OFFSET_NAME,
	IDS_VMD_CAM_IMPORT_BUTTON,

	IDS_VMD_CAM_EXPORT_TITLE,
	IDS_VMD_CAM_EXPORT_SIZE_NAME,
	IDS_VMD_CAM_EXPORT_OFFSET_NAME,
	IDS_VMD_CAM_EXPORT_BUTTON,

	IDS_VMD_MOT_TOOL_TITLE,

	IDS_VMD_MOT_IMPORT_TITLE,
	IDS_VMD_MOT_IMPORT_SIZE_NAME,
	IDS_VMD_MOT_IMPORT_OFFSET_NAME,
	IDS_VMD_MOT_IMPORT_QUAT_NAME,
	IDS_VMD_MOT_IMPORT_BUTTON,

	IDS_PMX_MOD_TOOL_TITLE,

	IDS_PMX_MOD_IMPORT_TITLE,
	IDS_PMX_MOD_IMPORT_SIZE_NAME,
	IDS_PMX_MOD_IMPORT_MULTIPART_NAME,
	IDS_PMX_MOD_IMPORT_BUTTON,

  // End of symbol definition
};
#endif // C4D_SYMBOLS_H__

