#ifndef MEDIASESSION_IMAGE_EXPORT_PNG_H__
#define MEDIASESSION_IMAGE_EXPORT_PNG_H__


#include "maxon/mediasession_image_export.h"

#if defined(PRIVATE_MAXON_REGISTRATION_UNIT)
	// TODO: (Seb) don't know why
	#include "maxon/fileformat_handler.h"
#endif

//----------------------------------------------------------------------------------------
// BEGIN - auto generated code, do not edit
//----------------------------------------------------------------------------------------
namespace maxon
{
namespace MEDIASESSION
{
	namespace PNG
	{
		namespace EXPORT
		{
			MAXON_RESOURCE_DATABASE_SCOPE("net.maxon.mediasession.png.export");

			/// Save in interlaced mode.
			MAXON_ATTRIBUTE(maxon::Bool, INTERLACED, "net.maxon.mediasession.png.export.interlaced");
		}
	}
}
}
//----------------------------------------------------------------------------------------
// END - auto generated code, do not edit
//----------------------------------------------------------------------------------------

namespace maxon
{

// include autogenerated headerfile here
#include "mediasession_image_export_png1.hxx"

namespace ImageSaverClasses
{
	MAXON_DECLARATION(ImageSaverClasses::EntryType, Png, MEDIASESSION::PNG::EXPORT::GetId());	///< Png image saver.
}

// include autogenerated headerfile here
#include "mediasession_image_export_png2.hxx"


} // namespace maxon


#endif // MEDIASESSION_IMAGE_EXPORT_PNG_H__
