#ifndef MEDIASESSION_IMAGE_EXPORT_DDS_H__
#define MEDIASESSION_IMAGE_EXPORT_DDS_H__

#include "maxon/mediasession_image_export.h"

#if defined(PRIVATE_MAXON_REGISTRATION_UNIT)
	// TODO: (Seb) don't know why
	#include "maxon/fileformat_handler.h"
#endif

#undef COMPRESSION

//----------------------------------------------------------------------------------------
// BEGIN - auto generated code, do not edit
//----------------------------------------------------------------------------------------
namespace maxon
{
namespace MEDIASESSION
{
	namespace DDS
	{
		namespace EXPORT
		{
			MAXON_RESOURCE_DATABASE_SCOPE("net.maxon.mediasession.dds.export");

			// supports MAXON::MEDIASESSION::EXPORT::DISABLESRGBCONVERSION

			MAXON_ATTRIBUTE(maxon::Id, COMPRESSION, "net.maxon.mediasession.dds.export.compression",
				RESOURCE_DEFINE(ENUM_NONE, maxon::Id("no_compression"))
				RESOURCE_DEFINE(ENUM_DTX1, maxon::Id("bc1_dtx1"))
				RESOURCE_DEFINE(ENUM_DTX3, maxon::Id("bc2_dtx3"))
				RESOURCE_DEFINE(ENUM_DTX5, maxon::Id("bc3_dtx5")));

			MAXON_ATTRIBUTE(maxon::Bool, MIPMAPS, "net.maxon.mediasession.dds.export.mipmaps");
		}
	}
}
}
//----------------------------------------------------------------------------------------
// END - auto generated code, do not edit
//----------------------------------------------------------------------------------------



namespace maxon
{


// include autogenerated headerfile here
#include "mediasession_image_export_dds1.hxx"

namespace ImageSaverClasses
{
	MAXON_DECLARATION(ImageSaverClasses::EntryType, Dds, MEDIASESSION::DDS::EXPORT::GetId());	///< DDS image saver.
}

// include autogenerated headerfile here
#include "mediasession_image_export_dds2.hxx"


} // namespace maxon


#endif // MEDIASESSION_IMAGE_EXPORT_DDS_H__
