#ifndef MEDIASESSION_IMAGE_EXPORT_JPG_H__
#define MEDIASESSION_IMAGE_EXPORT_JPG_H__


#include "maxon/mediasession_image_export.h"

#if defined(PRIVATE_MAXON_REGISTRATION_UNIT)
	// TODO: (Seb) don't know why
	#include "maxon/fileformat_handler.h"
#endif

//----------------------------------------------------------------------------------------
// BEGIN - auto generated code, do not edit
//----------------------------------------------------------------------------------------
namespace maxon
{
namespace MEDIASESSION
{
	namespace JPG
	{
		namespace EXPORT
		{
			MAXON_RESOURCE_DATABASE_SCOPE("net.maxon.mediasession.jpg.export");

			// supports MAXON::MEDIASESSION::EXPORT::QUALITY

			/// Force baseline mode.
			/// Don't make this public because i see no difference in the binary image with on/off
			MAXON_ATTRIBUTE(maxon::Bool, BASELINE, "net.maxon.mediasession.jpg.export.baseline");
		}
	}
}
}
//----------------------------------------------------------------------------------------
// END - auto generated code, do not edit
//----------------------------------------------------------------------------------------

namespace maxon
{

// include autogenerated headerfile here
#include "mediasession_image_export_jpg1.hxx"

namespace ImageSaverClasses
{
	MAXON_DECLARATION(ImageSaverClasses::EntryType, Jpg, MEDIASESSION::JPG::EXPORT::GetId());	///< JPG image saver.
}

// include autogenerated headerfile here
#include "mediasession_image_export_jpg2.hxx"


} // namespace maxon


#endif // MEDIASESSION_IMAGE_EXPORT_JPG_H__
