#ifndef MEDIASESSION_IMAGE_EXPORT_BMP_H__
#define MEDIASESSION_IMAGE_EXPORT_BMP_H__

#include "maxon/mediasession_image_export.h"

#if defined(PRIVATE_MAXON_REGISTRATION_UNIT)
	// TODO: (Seb) don't know why
	#include "maxon/fileformat_handler.h"
#endif

//----------------------------------------------------------------------------------------
// BEGIN - auto generated code, do not edit
//----------------------------------------------------------------------------------------
namespace maxon
{
namespace MEDIASESSION
{
	namespace BMP
	{
		namespace EXPORT
		{
			MAXON_RESOURCE_DATABASE_SCOPE("net.maxon.mediasession.bmp.export");

			// supports MAXON::MEDIASESSION::EXPORT::DISABLESRGBCONVERSION

			/// BitmapInfo header version. V3 - supports no alpha, V4 - supports alpha, V5 - supports colorprofile
			MAXON_ATTRIBUTE(maxon::Id, BITMAPINFOHEADER, "net.maxon.mediasession.bmp.export.bitmapinfoheader",
				RESOURCE_DEFINE(ENUM_V3, maxon::Id("V3"))
				RESOURCE_DEFINE(ENUM_V4, maxon::Id("V4"))
				RESOURCE_DEFINE(ENUM_V5, maxon::Id("V5")));
		}
	}
}
}
//----------------------------------------------------------------------------------------
// END - auto generated code, do not edit
//----------------------------------------------------------------------------------------


namespace maxon
{

// include autogenerated headerfile here
#include "mediasession_image_export_bmp1.hxx"

namespace ImageSaverClasses
{
	MAXON_DECLARATION(ImageSaverClasses::EntryType, Bmp, MEDIASESSION::BMP::EXPORT::GetId());	///< BMP image saver.
}

// include autogenerated headerfile here
#include "mediasession_image_export_bmp2.hxx"


} // namespace maxon


#endif // MEDIASESSION_IMAGE_EXPORT_BMP_H__
