CONTAINER VMD_Cam_Obj
{
	NAME VMD_Cam_Obj;
	INCLUDE Obase;

	GROUP VMD_CAM_OBJ_GRP{
		DEFAULT 1;
		LONG	FRAME_ON{}
		LONG	CURVE_TYPE{ANIM OFF;MIN 0;MAX 5;CYCLE{XCURVE;YCURVE;ZCURVE;RCURVE;DCURVE;VCURVE;ACURVE;}}	
		GROUP{				
			SPLINE	VMD_CAM_OBJ_SPLINE{ANIM OFF; SHOWGRID_H; SHOWGRID_V; MINSIZE_H 350; MINSIZE_V 350; SQUARE;}
			GROUP{	
			COLUMNS 4;	 
			BUTTON	INIT_CURVE_BUTTON{}
			BUTTON	REGISTER_CURVE_BUTTON{}
			BUTTON	DELETE_CURVE_BUTTON{}
			BUTTON	UPDATE_CURVE_BUTTON{}
			}
		}
	}
}