#ifndef _O_MMD_RIGID_ROOT_H_
#define _O_MMD_RIGID_ROOT_H_
enum
{
	RIGID_ROOT_GRP = 1000,
	RIGID_DISPLAY_TYPE,
	RIGID_MODE,
	ADD_RIGID_BUTTON,

	RIGID_DISPLAY_TYPE_OFF = 0,
	RIGID_DISPLAY_TYPE_ON,
	RIGID_DISPLAY_TYPE_WIRE,

	RIGID_MODE_ANIM = 0,
	RIGID_MODE_EDIT
};
#endif //_O_MMD_RIGID_ROOT_H_
