#ifndef _O_MMD_JOINT_MANAGER_H_
#define _O_MMD_JOINT_MANAGER_H_
enum
{
	JOINT_MANAGER_GRP = 1000,
	JOINT_DISPLAY_TYPE,
	JOINT_MODE,
	ADD_JOINT_BUTTON,

	JOINT_DISPLAY_TYPE_OFF = 0,
	JOINT_DISPLAY_TYPE_ON,
	JOINT_DISPLAY_TYPE_WIRE,

	JOINT_MODE_EDIT = 0,
	JOINT_MODE_ANIM,
	JOINT_MODE_VMD
};
#endif //_O_MMD_JOINT_MANAGER_H_
