#ifndef _O_MMD_BONE_ROOT_H_
#define _O_MMD_BONE_ROOT_H_
enum
{
	BONE_ROOT_GRP = 1000,
	BONE_DISPLAY_TYPE,
	ADD_BONE_BUTTON,

	BONE_DISPLAY_TYPE_ON = 0,
	BONE_DISPLAY_TYPE_OFF,
	BONE_DISPLAY_TYPE_MOVABLE,
	BONE_DISPLAY_TYPE_ROTATABLE,
	BONE_DISPLAY_TYPE_VISIBLE,
	BONE_DISPLAY_TYPE_ENABLED,
	BONE_DISPLAY_TYPE_IK
};
#endif //_O_MMD_BONE_ROOT_H_
