#ifndef _O_MMD_BONE_MANAGER_H_
#define _O_MMD_BONE_MANAGER_H_
enum
{
	BONE_MANAGER_GRP = 1000,
	BONE_DISPLAY_TYPE,
	BONE_MODE,
	ADD_BONE_BUTTON,

	BONE_DISPLAY_TYPE_ON = 0,
	BONE_DISPLAY_TYPE_OFF,
	BONE_DISPLAY_TYPE_MOVABLE,
	BONE_DISPLAY_TYPE_ROTATABLE,
	BONE_DISPLAY_TYPE_VISIBLE,
	BONE_DISPLAY_TYPE_ENABLED,
	BONE_DISPLAY_TYPE_IK,
	BONE_MODE_EDIT = 0,
	BONE_MODE_ANIM
};
#endif //_O_MMD_BONE_MANAGER_H_
