#ifndef _PMX_JOINT_OBJ_H_
#define _PMX_JOINT_OBJ_H_

enum
{
	OMMDJoint_GRP = 1000,
	JOINT_INDEX,
	JOINT_NAME_LOCAL,
	JOINT_NAME_UNIVERSAL,
	JOINT_NAME_IS,
	JOINT_TYPE,

	JOINT_LINK_RIGID_GRP,
	JOINT_LINK_RIGID_A_INDEX,
	JOINT_LINK_RIGID_B_INDEX,
	JOINT_LINK_RIGID_SET_NAME_BUTTON,

	JOINT_ATTITUDE_GRP,
	JOINT_ATTITUDE_POSITION,
	JOINT_ATTITUDE_POSITION_X,
	JOINT_ATTITUDE_POSITION_Y,
	JOINT_ATTITUDE_POSITION_Z,
	JOINT_ATTITUDE_ROTATION,
	JOINT_ATTITUDE_ROTATION_X,
	JOINT_ATTITUDE_ROTATION_Y,
	JOINT_ATTITUDE_ROTATION_Z,
	JOINT_ATTITUDE_USE_BONE_INDEX,
	JOINT_ATTITUDE_USE_BONE_BUTTON,

	JOINT_PARAMETER_GRP,
	JOINT_PARAMETER_POSITION,
	JOINT_PARAMETER_POSITION_X_MIN,
	JOINT_PARAMETER_POSITION_X_MAX,
	JOINT_PARAMETER_POSITION_Y_MIN,
	JOINT_PARAMETER_POSITION_Y_MAX,
	JOINT_PARAMETER_POSITION_Z_MIN,
	JOINT_PARAMETER_POSITION_Z_MAX,
	JOINT_PARAMETER_ROTATION,
	JOINT_PARAMETER_ROTATION_X_MIN,
	JOINT_PARAMETER_ROTATION_X_MAX,
	JOINT_PARAMETER_ROTATION_Y_MIN,
	JOINT_PARAMETER_ROTATION_Y_MAX,
	JOINT_PARAMETER_ROTATION_Z_MIN,
	JOINT_PARAMETER_ROTATION_Z_MAX,
	JOINT_PARAMETER_RESET_BUTTON,

	JOINT_SPRING_GRP,
	JOINT_SPRING_POSITION,
	JOINT_SPRING_POSITION_X,
	JOINT_SPRING_POSITION_Y,
	JOINT_SPRING_POSITION_Z,
	JOINT_SPRING_ROTATION,
	JOINT_SPRING_ROTATION_X,
	JOINT_SPRING_ROTATION_Y,
	JOINT_SPRING_ROTATION_Z,
	JOINT_SPRING_RESET_BUTTON,

	JOINT_NAME_IS_LOCAL = 0,
	JOINT_NAME_IS_UNIVERSAL,

	SpringDOF6 = 0,
	DOF6,
	P2P,
	ConeTwist,
	Slider,
	Hinge,

	JOINT_RIGID_NONE = -1,
	JOINT_BONE_NONE = -1,
};
#endif
