#ifndef _O_MMD_CAM_H_
#define _O_MMD_CAM_H_
enum 
{
	VMD_CAM_OBJ_ANIMATION_GRP = 1000,
	VMD_CAM_OBJ_FRAME_AT,
	VMD_CAM_OBJ_FRAME_AT_STR,
	VMD_CAM_OBJ_CURVE_TYPE,	

	VMD_CAM_OBJ_SPLINE,
	VMD_CAM_OBJ_INIT_CURVE_BUTTON,
	VMD_CAM_OBJ_REGISTER_CURVE_BUTTON,
	VMD_CAM_OBJ_UPDATE_CURVE_BUTTON,
	VMD_CAM_OBJ_DELETE_CURVE_BUTTON,
	VMD_CAM_OBJ_DELETE_ALL_CURVE_BUTTON,
	
	VMD_CAM_OBJ_INTERPOLATOR_POSITION_X = 0,
	VMD_CAM_OBJ_INTERPOLATOR_POSITION_Y,
	VMD_CAM_OBJ_INTERPOLATOR_POSITION_Z,
	VMD_CAM_OBJ_INTERPOLATOR_ROTATION,
	VMD_CAM_OBJ_INTERPOLATOR_DISTANCE,
	VMD_CAM_OBJ_INTERPOLATOR_AOV,
	VMD_CAM_OBJ_INTERPOLATOR_ALL,
	VMD_CAM_OBJ_INTERPOLATOR_NUM

};

#endif _O_MMD_CAM_H_
