#ifndef _PMX_BONE_TAG_H_
#define _PMX_BONE_TAG_H_

enum
{
	PMX_BONE_INFO_GRP = 10000,
	PMX_BONE_INDEX,
	PMX_BONE_NAME_LOCAL,//骨骼本地名称
	PMX_BONE_NAME_UNIVERSAL,//骨骼通用名称
	PMX_BONE_NAME_IS,//骨骼显示名称	


	PMX_BONE_POSITION,//位置

	PMX_BONE_PARENT_BONE_TEXT,
	PMX_BONE_PARENT_BONE_INDEX,//亲骨索引
	PMX_BONE_PARENT_BONE_NAME,//亲骨名称

	PMX_BONE_FLAG_GRP,//骨骼特征组
	PMX_BONE_ROTATABLE,//启用旋转
	PMX_BONE_TRANSLATABLE,//启用移动
	PMX_BONE_VISIBLE,//启用显示
	PMX_BONE_ENABLED,//启用操作
	PMX_BONE_IS_IK,//启用IK骨

	PMX_BONE_DEFORM_LAYER_GRP,//变形阶层组
	PMX_BONE_LAYER,//变形阶层
	PMX_BONE_PHYSICS_AFTER_DEFORM,//先变形，后算物理

	PMX_BONE_END_OF_BONE_GRP,//骨骼末端
	PMX_BONE_INDEXED_TAIL_POSITION,//骨骼尾部(尖端)位置

	PMX_BONE_TAIL_INDEX,//子骨骼索引
	PMX_BONE_TAIL_POSITION,//相对位置

	PMX_BONE_INHERIT_GRP,//骨骼继承组
	PMX_BONE_INHERIT_ROTATION,//启用继承亲骨的旋转
	PMX_BONE_INHERIT_TRANSLATION,//启用继承亲骨的移动
	PMX_BONE_INHERIT_BONE_PARENT_INDEX,//骨骼继承-亲骨索引
	PMX_BONE_INHERIT_BONE_PARENT_INFLUENCE,//骨骼继承-影响权重
	PMX_BONE_INHERIT_BONE_PARENT_LINK,//骨骼继承-亲骨

	PMX_BONE_FIXED_AXIS_GRP,//轴限制
	PMX_BONE_IS_FIXED_AXIS,//启用轴限制
	PMX_BONE_FIXED_AXIS,//骨骼固定轴-轴方向

	PMX_BONE_LOCAL_COORDINATE_GRP,//Local轴
	PMX_BONE_LOCAL_IS_COORDINATE,//启用Local轴
	PMX_BONE_LOCAL_X,//骨骼Local坐标-X矢量
	PMX_BONE_LOCAL_Z,//骨骼Local坐标-Z矢量
	
	PMX_BONE_TAG_ANIMATION_GRP,
	PMX_BONE_TAG_FRAME_ON,
	PMX_BONE_TAG_CURVE_TYPE,
	PMX_BONE_TAG_SPLINE,
	PMX_BONE_TAG_INIT_CURVE_BUTTON,
	PMX_BONE_TAG_REGISTER_CURVE_BUTTON,
	PMX_BONE_TAG_UPDATE_CURVE_BUTTON,
	PMX_BONE_TAG_DELETE_CURVE_BUTTON,
	PMX_BONE_TAG_DELETE_ALL_CURVE_BUTTON,

	PMX_BONE_MORPH_GRP,
	PMX_BONE_MORPH_ADD_NAME,
	PMX_BONE_MORPH_ADD_BUTTON,

	PMX_BONE_INDEX_TEXT,

	PMX_BONE_TAG_XCURVE = 0,
	PMX_BONE_TAG_YCURVE = 1,
	PMX_BONE_TAG_ZCURVE = 2,
	PMX_BONE_TAG_RCURVE = 3,
	PMX_BONE_TAG_ACURVE = 4,

	PMX_BONE_NAME_IS_LOCAL = 0,//骨骼使用本地名称
	PMX_BONE_NAME_IS_UNIVERSAL = 1,//骨骼使用通用名称

	PMX_BONE_TAIL_IS_POSITION = 0,//是连接子骨骼
	PMX_BONE_TAIL_IS_INDEX = 1,//是连接相对位置

};
#endif _PMX_BONE_TAG_H_
