#ifndef _XMMDMATERIALMORPHSHADER_H_
#define _XMMDMATERIALMORPHSHADER_H_
enum
{
	MMDMATERIALMORPHSHADER_FACTOR_COLOR = 1000,
	MMDMATERIALMORPHSHADER_FACTOR_ALPHA,
};
#endif // _XMMDMATERIALMORPHSHADER_H_
