#ifndef _XMMDMATERIALMORPHSHADER_H_
#define _XMMDMATERIALMORPHSHADER_H_
enum
{
	MMDMATERIALMORPHSHADER_FACTOR_COLOR = 1000,
	MMDMATERIALMORPHSHADER_FACTOR_ALPHA,
	MMDMATERIALMORPHSHADER_OUTPUT = 2000,
	MMDMATERIALMORPHSHADER_FIELD,
	MMDMATERIALMORPHSHADER_MODEL,
	MMDMATERIALMORPHSHADER_MATERIAL,
	MMDMATERIALMORPHSHADER_TEXTURED,
	MMDMATERIALMORPHSHADER_SPHERE_SHADER,
	MMDMATERIALMORPHSHADER_SPHERE_MODE,
};
#endif // _XMMDMATERIALMORPHSHADER_H_
