CONTAINER Xmmdmaterialmorphshader
{
	NAME Xmmdmaterialmorphshader;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		COLOR MMDMATERIALMORPHSHADER_FACTOR_COLOR { }
		REAL MMDMATERIALMORPHSHADER_FACTOR_ALPHA { MIN 0.0; }
	}
}
