#ifndef CACHETOOL_H__
#define CACHETOOL_H__

enum
{
	CACHE_TOOL_FALLOFF_STRENGTH = 2001,
	CACHE_TOOL_FALLOFF_RADIUS,
	CACHE_TOOL_FALLOFF_WIDTH,
	CACHE_TOOL_MODE,
	CACHE_TOOL_FALLOFF,
	CACHE_TOOL_FALLOFF_MODE,
	CACHE_TOOL_SHOW_RADIUS,

	//////////////////////////////////////////////////////////////////////////

	CACHE_TOOL_MODE_CONSTANT = 0,
	CACHE_TOOL_MODE_LINEAR,
	CACHE_TOOL_MODE_DOME,
	CACHE_TOOL_MODE_BELL,
	CACHE_TOOL_MODE_CIRCLE,
	CACHE_TOOL_MODE_NEEDLE,
	CACHE_TOOL_MODE_USER,

	CACHE_TOOL_MODE_SMEAR = 0,
	CACHE_TOOL_MODE_SMOOTH,



	CACHE_TOOL_DUMMY
};

#endif // CACHETOOL_H__
