#ifndef _FORGERIO_SAVER_RESSOURCE_H__
#define _FORGERIO_SAVER_RESSOURCE_H__


enum
{

	fforgeriosaver = 10000,
	FORGERIO_SCALE_FACTOR_EXPORT,
	FORGERIO_EXPORT_UVW,
	FORGERIO_EXPORT_POLYPAINT,
	FORGERIO_EXPORT_POLYGROUP,
	FORGERIO_EXPORT_CONNECTWITHCHILDREN,
	FORGERIO_EXPORT_GROUP,
	FORGERIO_EXPORT_MATERIALS,
	FORGERIO_EXPORT_WARNING
};

#endif