#ifndef FLCLAMP_H__
#define FLCLAMP_H__

enum
{
	FIELDLAYER_CLAMP_MIN_VALUE	 = 1000,	// FLOAT
	FIELDLAYER_CLAMP_MIN_ENABLED = 1001,	// BOOL
	FIELDLAYER_CLAMP_MAX_VALUE	 = 1002,	// FLOAT
	FIELDLAYER_CLAMP_MAX_ENABLED = 1003,	// BOOL

	FIELDLAYER_CLAMP_DUMMY
};
#endif	// #FLCLAMP_H__

