#ifndef FLCURVE_H__
#define FLCURVE_H__

enum
{
	FIELDLAYER_CURVE_SPLINE					= 1000,	// SPLINE
	FIELDLAYER_CURVE_OFFSET					= 1001,	// FLOAT
	FIELDLAYER_CURVE_ANIMATIONSPEED	= 1002,	// TIME
	FIELDLAYER_CURVE_PREMODE				= 1003,	// INT CYCLE
	FIELDLAYER_CURVE_POSTMODE				= 1004,	// INT CYCLE
	FIELDLAYER_CURVE_MODE_CLAMP			= 0,
	FIELDLAYER_CURVE_MODE_VELOCITY	= 1,
	FIELDLAYER_CURVE_MODE_CURVE			= 2,
	FIELDLAYER_CURVE_MODE_LOOP			= 3,
	FIELDLAYER_CURVE_MODE_PINGPONG	= 4,

	FIELDLAYER_CURVE_DUMMY
};
#endif	// #FLCURVE_H__

