#ifndef FLPARTICLEOBJECT_H__
#define FLPARTICLEOBJECT_H__

enum
{
	FIELDLAYER_PARTICLE_OBJECT								= 1000, // Baselink
	FIELDLAYER_PARTICLE_DISTANCE							= 1001, // Real
	FIELDLAYER_PARTICLE_CLIP									= 1002, // Bool
	FIELDLAYER_PARTICLE_COLOR_ALPHA						= 1003, // Long cycle
	FIELDLAYER_PARTICLE_COLOR_ALPHA_NONE			= 0,
	FIELDLAYER_PARTICLE_COLOR_ALPHA_VALUE			= 1
};

#endif // FLPARTICLEOBJECT_H__
