#ifndef FLPOLYGONOBJECT_H__
#define FLPOLYGONOBJECT_H__

enum
{
	FIELDLAYER_POLYGON_OBJECT									= 1000, // Baselink
	FIELDLAYER_POLYGON_MODE										= 1001, // Int Cycle
		FIELDLAYER_POLYGON_MODE_VOLUME					= 0,
		FIELDLAYER_POLYGON_MODE_SURFACE					= 1,
		FIELDLAYER_POLYGON_MODE_POINTS					= 2,
		FIELDLAYER_POLYGON_MODE_CURVATURE				= 3,
	FIELDLAYER_POLYGON_DISTANCE								= 1002, // Real
	FIELDLAYER_POLYGON_VOLUME_CLIP						= 1003,	// Int Cycle
		FIELDLAYER_POLYGON_VOLUME_CLIP_NONE			= 0,
		FIELDLAYER_POLYGON_VOLUME_CLIP_INSIDE		= 1,
		FIELDLAYER_POLYGON_VOLUME_CLIP_OUTSIDE	= 2,
		FIELDLAYER_POLYGON_VOLUME_CLIP_INSIDE_INVERT = 3,
	FIELDLAYER_POLYGON_CLIP										= 1004, // Bool
	FIELDLAYER_POLYGON_CURVATURE_MODE = 1005, // Int Cycle
		FIELDLAYER_POLYGON_CURVATURE_MODE_DIRECT = 0,
		FIELDLAYER_POLYGON_CURVATURE_MODE_CONVEX = 1,
		FIELDLAYER_POLYGON_CURVATURE_MODE_CONCAVE = 2,
		FIELDLAYER_POLYGON_CURVATURE_MODE_BOTH = 3,
	FIELDLAYER_POLYGON_CURVATURE_RADIUS = 1006, // Real
	FIELDLAYER_POLYGON_CURVATURE_DERIVATIVE = 1007, // Bool
	FIELDLAYER_POLYGON_CURVATURE_CONTOUR = 1008, // Int Cycle
		FIELDLAYER_POLYGON_CURVATURE_CONTOUR_PRIMARY		= 0,
		FIELDLAYER_POLYGON_CURVATURE_CONTOUR_SECONDARY	= 1,
	FIELDLAYER_POLYGON_CURVATURE_USEUV = 1009, // Bool
	FIELDLAYER_POLYGON_USEDEFORMED = 1011,
};

#endif // FLPOLYGONOBJECT_H__
