#ifndef _GOZ_DESCRIPTION_POLYGROUP_SELECTION_TOOL_H__
#define _GOZ_DESCRIPTION_POLYGROUP_SELECTION_TOOL_H__
enum {

    POLYGROUP_SELECTION_TOOL_GROUP = 1000,
    POLYGROUP_SELECTION_TOOL_OPERATION,
    POLYGROUP_SELECTION_TOOL_OPERATION_NEW,
	  POLYGROUP_SELECTION_TOOL_OPERATION_ADD,
  	POLYGROUP_SELECTION_TOOL_OPERATION_REMOVE,

    
    POLYGROUP_SELECTION_TOOL_DUMMY
};

#endif