#ifndef GVCMP_H__
#define GVCMP_H__

#include "gvdynamic.h"

enum
{
	GV_CMP_FUNCTION				= 1000,
		GV_EQU_NODE_FUNCTION = 0,
		GV_LESS_NODE_FUNCTION,
		GV_LESSEQU_NODE_FUNCTION,
		GV_GREATER_NODE_FUNCTION,
		GV_GREATEREQU_NODE_FUNCTION,
		GV_NOT_EQU_NODE_FUNCTION,

	GV_CMP_INPUT1					= 2000,
	GV_CMP_INPUT2					= 2001,

	GV_CMP_OUTPUT					= 3000,

	GV_CMP_
};

#endif // GVCMP_H__
