#ifndef GVOSCFLOATCONTROLLER_H__
#define GVOSCFLOATCONTROLLER_H__

enum
{
	OSC_FLOAT_VALUE_METHOD_NAME = 4000,
	OSC_FLOAT_VALUE = 4001,
	OSC_FLOAT_VALUE_PORT = 4002,
	OSC_FLOAT_VALUE_SET_METHOD_NAME = 4003
};

#endif // GVOSCFLOATCONTROLLER_H__



