#ifndef GVTIME_H__
#define GVTIME_H__

enum
{
	GV_TIME_OPERATOR_OUTPUT_TIME 				= 1000,
	GV_TIME_OPERATOR_OUTPUT_REAL				= 1001,
	GV_TIME_OPERATOR_OUTPUT_FRAME				= 1002,
	GV_TIME_OPERATOR_OUTPUT_FPS					= 1003,
	GV_TIME_OPERATOR_OUTPUT_START				= 1004,
	GV_TIME_OPERATOR_OUTPUT_END					= 1005,
	GV_TIME_OPERATOR_OUTPUT_LOOP_START	= 1006,
	GV_TIME_OPERATOR_OUTPUT_LOOP_END		= 1007,
	GV_TIME_OPERATOR_OUTPUT_DELTA				= 1008,
	GV_TIME_OPERATOR_OUTPUT_PREVIOUS		= 1009,
	GV_TIME_
};

#endif // GVTIME_H__
