#ifndef IN_INTERACT_H__
#define IN_INTERACT_H__

#include "gvbase.h"

enum
{
	INT_VERSION		= 1000,
	INT_GROUPA		= 1001,
	INT_GROUPB		= 1002,
	INT_DISTANCE	= 1003,
	INT_DTYPE			= 1004,

	INTERACT_DTYPE_NONE			= 0,
	INTERACT_DTYPE_INSIDE		= 1,
	INTERACT_DTYPE_OUTSIDE	= 2,

//Ports
	OUT_INTERACT_PARTICLE_A				= 3000,
	OUT_INTERACT_PARTICLE_B				= 3001,
	OUT_INTERACT_PARTICLECOUNT_A	= 3002,
	OUT_INTERACT_PARTICLECOUNT_B	= 3003,
	OUT_INTERACT_POSITION_A				= 3004,
	OUT_INTERACT_POSITION_B				= 3005,
	OUT_INTERACT_DISTANCE_AB			= 3006,
	OUT_INTERACT_VECTOR_AB				= 3007
};



#endif // IN_INTERACT_H__
