#ifndef MFOG_H__
#define MFOG_H__

enum
{
	FOGSHADER_COLOR				= 1000,	// VECTOR
	FOGSHADER_SCALE				= 1001,	// REAL
	FOGSHADER_AMPLITUDE		= 1002,	// REAL
	FOGSHADER_FREQUENCY		= 1003,	// REAL
	FOGSHADER_SAMPLES			= 1004,	// LONG
	FOGSHADER_VOLUMETRIC	= 1005,	// BOOL
	FOGSHADER_TURBULENCE	= 1006,	// REAL
	FOGSHADER_DECREASE		= 1007,	// REAL
	FOGSHADER_THICKNESS		= 1008,	// REAL
	FOGSHADER_TYPE				= 1009,	// LONG
		FOGSHADER_TYPE_LINEAR				= 0,
		FOGSHADER_TYPE_EXPONENTIAL	= 1,
		FOGSHADER_TYPE_NODECREASE		= 2
};

#endif // MFOG_H__
