#ifndef MT_TAG_H__
#define MT_TAG_H__

enum
{
	ID_MT_TAG_SHOWGHOSTS	= 1001,
	ID_MT_TAG_OPENINTL		= 1002,
	ID_MT_TAG_GROUP				= 1003,
	ID_MT_TAG_COUNTER			= 1004,

	ID_MT_TAG_ADD         = 1006,
	ID_MT_TAG_DEL         = 1007,
	ID_MT_TAG_DUPLICATE   = 1008,
	ID_MT_TAG_COLLAPSE    = 1009,
	ID_MT_TAG_ZERO        = 1010,

	ID_MT_TAG_SHOWPATH    = 1011,
	ID_MT_TAG_RENAME			= 1012,

	ID_MT_TAG_RMIXING     = 1013,
		ID_MT_TAG_MIX_AUTO    = 0,
		ID_MT_TAG_MIX_HPB     = 1,
		ID_MT_TAG_MIX_QUAT    = 2,


	ID_MT_TAG_
};

#endif // MT_TAG_H__



