#ifndef OBODYCAPTURE_H__
#define OBODYCAPTURE_H__

enum
{
	BODYCAPTURE_FILENAME  = 1000,
	BODYCAPTURE_UID,
	BODYCAPTURE_CAMERA,
	BODYCAPTURE_FRAMECOUNT,
	BODYCAPTURE_SETTIMELINE,	
	BODYCAPTURE_ADDCAMERA,
	
	BODYCAPTURE_POSE,
	BODYCAPTURE_POSE_CAPTURE,
	BODYCAPTURE_POSE_T,
	
	BODYCAPTURE_TRANSFORMS,
	BODYCAPTURE_TRANSFORMS_LOCAL,
	BODYCAPTURE_TRANSFORMS_MODEL,
	
	BODYCAPTURE_LOCKED,
	
	BODYCAPTURE_STARTFRAME,
	BODYCAPTURE_RANGELENGTH,
	
	BODYCAPTURE_ROTATION,	
	BODYCAPTURE_OFFSET,
	
	BODYCAPTURE_SETNEUTRALFRAME,
	BODYCAPTURE_CLEARNEUTRALFRAME,
		
	BODYCAPTURE_MATRICES,
	BODYCAPTURE_MATRIX_BODY,
	BODYCAPTURE_MATRIX_CAMERA,
	BODYCAPTURE_MATRIX_NEUTRALFRAME,
		
	BODYCAPTURE_BODY_LINK,
	BODYCAPTURE_BODY_ADD,
	
	BODYCAPTURE_BAKE,
	
	BODYCAPTURE_LOOP,
	BODYCAPTURE_CREATEMOTIONCLIP,
			
	BODYCAPTURE_MATRIX_BODY_GROUP = 1100,
	BODYCAPTURE_MATRIX_BODY_POSITION,
	BODYCAPTURE_MATRIX_BODY_ROTATION,
	BODYCAPTURE_MATRIX_CAMERA_GROUP,
	BODYCAPTURE_MATRIX_CAMERA_POSITION,
	BODYCAPTURE_MATRIX_CAMERA_ROTATION,
	BODYCAPTURE_MATRIX_NEUTRALFRAME_GROUP,
	BODYCAPTURE_MATRIX_NEUTRALFRAME_POSITION,
  BODYCAPTURE_MATRIX_NEUTRALFRAME_ROTATION,
	
	BODYCAPTURE_ORIENTATION = 1200,
	BODYCAPTURE_ORIENTATION_Z_POS = 0,
	BODYCAPTURE_ORIENTATION_Z_NEG = 1,
	
	BODYCAPTURE_LOSTFRAME = 1300,
	BODYCAPTURE_LOSTFRAME_HOLD,
	BODYCAPTURE_LOSTFRAME_BLEND,
	BODYCAPTURE_LOSTFRAME_HIDE,
};

#endif // OBODYCAPTURE_H__
