#ifndef OCACORRECTIONDEFORMER_H__
#define OCACORRECTIONDEFORMER_H__

enum
{
	ID_CA_CORRECTION_DEFORMER_OBJECT_STRENGTH = 1000,
	ID_CA_CORRECTION_DEFORMER_OBJECT_LOCK,
	ID_CA_CORRECTION_DEFORMER_OBJECT_SCALE,
	ID_CA_CORRECTION_DEFORMER_OBJECT_UPDATE,
	ID_CA_CORRECTION_DEFORMER_OBJECT_FREEZE,
	ID_CA_CORRECTION_DEFORMER_OBJECT_RESET,
	ID_CA_CORRECTION_DEFORMER_OBJECT_MAP,
	ID_CA_CORRECTION_DEFORMER_OBJECT_UV,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_CORRECTION_DEFORMER_OBJECT_MAP_UV = 0,
	ID_CA_CORRECTION_DEFORMER_OBJECT_MAP_NEAREST,
	ID_CA_CORRECTION_DEFORMER_OBJECT_MAP_NORMAL,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_CORRECTION_DEFORMER_OBJECT_DUMMY
};

#endif // OCACORRECTIONDEFORMER_H__
