#ifndef OCACAMDEFORMER_H__
#define OCACAMDEFORMER_H__

enum
{
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_GRID_X = 2000,
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_GRID_Y,
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_STRENGTH,
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_CAMERA,
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_PRIORITY,
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_RESET,
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_DRAW,
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_SAFEFRAME,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_CAMERASPACE_DEFORMER_OBJECT_DRAW_ALWAYS = 0,
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_DRAW_ACTIVE,
	ID_CA_CAMERASPACE_DEFORMER_OBJECT_DRAW_MESH,

	ID_CA_CAMERASPACE_DEFORMER_OBJECT_DUMMY
};

#endif // OCACAMDEFORMER_H__
