#ifndef OCAMESHDEFORMER_H__
#define OCAMESHDEFORMER_H__

enum
{
	ID_CA_MESH_DEFORMER_GROUP_ADVANCED = 2000,

	ID_CA_MESH_DEFORMER_OBJECT_INITIAL = 1001,
	ID_CA_MESH_DEFORMER_OBJECT_RESTORE,
	ID_CA_MESH_DEFORMER_OBJECT_MEM,
	ID_CA_MESH_DEFORMER_OBJECT_STRENGTH,
	ID_CA_MESH_DEFORMER_OBJECT_ACCURACY,
	ID_CA_MESH_DEFORMER_OBJECT_EXTERNAL,
	ID_CA_MESH_DEFORMER_OBJECT_FIT,
	ID_CA_MESH_DEFORMER_OBJECT_CAGE_INCLUDE,
	ID_CA_MESH_DEFORMER_OBJECT_AUTO,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_MESH_DEFORMER_OBJECT_EXTERNAL_IGNORE = 0,
	ID_CA_MESH_DEFORMER_OBJECT_EXTERNAL_SURFACE,
	ID_CA_MESH_DEFORMER_OBJECT_EXTERNAL_SURFACE_AREA,

	ID_CA_MESH_DEFORMER_OBJECT_DUMMY
};

#endif // OCAMESHDEFORMER_H__
