#ifndef ODENSESMOKESIMULATION_H__
#define ODENSESMOKESIMULATION_H__
enum
{
	VIEWPORT_SELECTED_TEXTURE = 1001,
	VIEWPORT_CURR_MG_DEPTH,
	VIEWPORT_ITERATIONS_CG,
	VIEWPORT_ITERATIONS_FINAL,
	VIEWPORT_SMOOTHING_ITERATIONS,
	VIEWPORT_SOLVERTYPE,
	VIEWPORT_GRID_RESOLUTION,
	VIEWPORT_DENSITY_BUOYANCYFACTOR,
	VIEWPORT_TEMPERATURE_BUOYANCYFACTOR,
	VIEWPORT_GRID_RENDER_SCALING
};

#endif // ODENSESMOKESIMULATION_H__