#ifndef OEDELAY_H__
#define OEDELAY_H__

enum
{
	//groups
	MGDELAYEFFECTOR_GROUPPARAMETER	= 990,
	MGDELAYEFFECTOR_GROUPEFFECTOR		= 991,

	//subgroups
	MGDELAYEFFECTOR_GROUPTRANSFORM	= 995,

	//------------------------------
	//Effector controls
	MGDELAYEFFECTOR_STRENGTH				= 1000,

	MGDELAYEFFECTOR_SELECTION				=	1021,

	//-------------------------------
	//Parameter controls
	MGDELAYEFFECTOR_POSITION_ACTIVE = 1060,
	MGDELAYEFFECTOR_SCALE_ACTIVE		= 1061,
	MGDELAYEFFECTOR_ROTATION_ACTIVE = 1062,
	MGDELAYEFFECTOR_MODE						= 1102,
	MGDELAYEFFECTOR_MODE_BLEND			= 0,
	MGDELAYEFFECTOR_MODE_SPRING			= 1,
	MGDELAYEFFECTOR_MODE_EVEN				= 2
};
#endif // OEDELAY_H__
