#ifndef OEPUSHAPART_H__
#define OEPUSHAPART_H__

enum
{
	//groups
	MGPUSHAPARTEFFECTOR_GROUPEFFECTOR				= 991,

	//------------------------------
	//Effector controls
	MGPUSHAPARTEFFECTOR_STRENGTH						= 1000,
	MGPUSHAPARTEFFECTOR_MODE								= 1102,
		MGPUSHAPARTEFFECTOR_MODE_HIDE						= 0,
		MGPUSHAPARTEFFECTOR_MODE_PUSHAPART			= 1,
		MGPUSHAPARTEFFECTOR_MODE_SCALEAPART			= 2,
		MGPUSHAPARTEFFECTOR_MODE_ALONGX					= 3,
		MGPUSHAPARTEFFECTOR_MODE_ALONGY					= 4,
		MGPUSHAPARTEFFECTOR_MODE_ALONGZ					= 5,
	MGPUSHAPARTEFFECTOR_RADIUS							= 1103,
	MGPUSHAPARTEFFECTOR_ITERATIONS					= 1104,

	MGPUSHAPARTEFFECTOR_SELECTION						=	1021
};
#endif // OEPUSHAPART_H__
