#ifndef OETARGET_H__
#define OETARGET_H__

enum
{
	MGTARGETEFFECTOR_PRIMITIVEAXIS_XP		= 0,
	MGTARGETEFFECTOR_PRIMITIVEAXIS_XN,
	MGTARGETEFFECTOR_PRIMITIVEAXIS_YP,
	MGTARGETEFFECTOR_PRIMITIVEAXIS_YN,
	MGTARGETEFFECTOR_PRIMITIVEAXIS_ZP,
	MGTARGETEFFECTOR_PRIMITIVEAXIS_ZN,
	MGTARGETEFFECTOR_PRIMITIVEAXIS_LINK,
	MGTARGETEFFECTOR_PRIMITIVEAXIS_NONE,

	//groups
	MGTARGETEFFECTOR_GROUPEFFECTOR			= 991,

	//------------------------------
	//Effector controls
	MGTARGETEFFECTOR_STRENGTH						= 1000,
	MGTARGETEFFECTOR_OBJECT							= 1100,
	MGTARGETEFFECTOR_PITCH							= 1120,
	MGTARGETEFFECTOR_MODE								= 1102,
		MGTARGETEFFECTOR_MODE_OBJECT				= 0,
		MGTARGETEFFECTOR_MODE_NEXT					= 1,
		MGTARGETEFFECTOR_MODE_PREV					= 2,
		MGTARGETEFFECTOR_MODE_CAMERA				= 3,
		MGTARGETEFFECTOR_MODE_FIELDS				= 4,
	MGTARGETEFFECTOR_REACT							= 1103,
	MGTARGETEFFECTOR_RANGE							= 1104,
	ETARG_RANGE_STRENGTH								= 1105,
	MGTARGETEFFECTOR_UP									= 1106,
	MGTARGETEFFECTOR_PRIMITIVEAXIS			= 1108,
	MGTARGETEFFECTOR_GROUPUP						= 1109,
	MGTARGETEFFECTOR_REVERSEVECTOR			= 1110,
	MGTARGETEFFECTOR_SETWEIGHT					= 1111,

	MGTARGETEFFECTOR_SELECTION					=	1021
};
#endif // OETARGET_H__
