#ifndef OLOD_H__
#define OLOD_H__

enum
{
	LOD_MODE = 1000,
	LOD_CRITERIA,
	LOD_BAR,
	LOD_CURRENT_LEVEL,
	LOD_PROGRESIVE,
	LOD_CAMERA_MINDIST,
	LOD_CAMERA_MAXDIST,
	LOD_LEVEL_COUNT_DYN,
	LOD_CAMERA_CLIP,
	LOD_CAMERA_CLIP_SAFEDISTANCE,
	LOD_CAMERA_CLIP_SAFESPHERE,
	LOD_CAMERA_CLIP_AFFECTRENDER,
	LOD_OPTIONS_GROUP,
	LOD_VIEWPORT_ONLY,
	LOD_RENDER_INCREMENT,
	LOD_SHOW_UNASSIGNED,
	LOD_POLYGONIZE,

	LOD_MODE_CHILD = 0,
	LOD_MODE_MANUAL_GROUPS,
	LOD_MODE_SIMPLIFY,

	LOD_CRITERIA_MANUAL = 0,
	LOD_CRITERIA_MANUAL_SLIDER = 1,
	LOD_CRITERIA_SCREEN_H = 2,
	LOD_CRITERIA_SCREEN_V = 3,
	LOD_CRITERIA_SCREEN_SURFACE = 4,
	LOD_CRITERIA_CAMERA_DIST = 5,
	LOD_CRITERIA_GLOBAL = 6,

	LOD_SIMPLIFY_FULL = 0,
	LOD_SIMPLIFY_DECIMATE,
	LOD_SIMPLIFY_CONVEXHULL,
	LOD_SIMPLIFY_BB,
	LOD_SIMPLIFY_NULL,
};

#endif // OLOD_H__
