#ifndef OMOGRAPH_FRACTURE_H__
#define OMOGRAPH_FRACTURE_H__

enum
{
	MGFRACTUREOBJECT_MODE						= 1020,
	MGFRACTUREOBJECT_MODE_NONE			= 0,
	MGFRACTUREOBJECT_MODE_EXPLODE		= 1,
	MGFRACTUREOBJECT_MODE_EXCONNECT = 2
};
#endif // OMOGRAPH_FRACTURE_H__
