#ifndef OMOGRAPH_SPLINEMASK_H__
#define OMOGRAPH_SPLINEMASK_H__

enum
{
	MGSPLINEMASKOBJECT_AXIS							= 1100,
	MGSPLINEMASKOBJECT_AXIS_XY					= 0,
	MGSPLINEMASKOBJECT_AXIS_ZY					= 1,
	MGSPLINEMASKOBJECT_AXIS_XZ					= 2,
	MGSPLINEMASKOBJECT_AXIS_SCREEN			= 3,
	MGSPLINEMASKOBJECT_MODE							= 1101,
	MGSPLINEMASKOBJECT_MODE_AUNIONB			= 0,
	MGSPLINEMASKOBJECT_MODE_AMINUSB			= 1,
	MGSPLINEMASKOBJECT_MODE_BMINUSA			= 2,
	MGSPLINEMASKOBJECT_MODE_AND					= 3,
	MGSPLINEMASKOBJECT_MODE_OR					= 4,
	MGSPLINEMASKOBJECT_MODE_INTERSECTION = 5,
	MGSPLINEMASKOBJECT_CREATECAP				= 1102

};
#endif // OMOGRAPH_SPLINEMASK_H__
