#ifndef OMOGRAPH_POLYFX_H__
#define OMOGRAPH_POLYFX_H__

enum
{
	MGPOLYFX_MODE						=	1000,
	MGPOLYFX_PRESERVE_PHONG	=	1001,
		MGPOLYFX_MODE_FULL			=	0,
		MGPOLYFX_MODE_PART			=	1
};
#endif // OMOGRAPH_POLYFX_H__
