#ifndef ONURBSCAPS_H__
#define ONURBSCAPS_H__

enum
{
	ID_CAPSANDBEVELS																		= 42, // Unique, verified

	CAPSANDBEVELS_CAP_ENABLE_START											= 2999,
	CAPSANDBEVELS_CAP_ENABLE_END												= 3000,

	CAPSANDBEVELS_CAP_GROUP															= 3001,
	CAPSANDBEVELS_CAP_TYPE															= 3002,
	CAPSANDBEVELS_CAP_TYPE_TRI													= 0,
	CAPSANDBEVELS_CAP_TYPE_QUAD													= 1,
	CAPSANDBEVELS_CAP_TYPE_NGON													= 2,
	CAPSANDBEVELS_CAP_TYPE_DELAUNAY											= 3,
	CAPSANDBEVELS_CAP_TYPE_REGULAR											= 4,

	CAPSANDBEVELS_CAP_REGULAR_SIZE											= 3004,
	CAPSANDBEVELS_CAP_DELAUNAY_GRAD											= 3005,
	CAPSANDBEVELS_CAP_DELAUNAY_SIZE_FACTOR							= 3006,
	CAPSANDBEVELS_CAP_DELAUNAY_QUAD											= 3007,

	CAPSANDBEVELS_BEVEL_SEPARATE												= 3008,

	CAPSANDBEVELS_BEVEL_GROUP														= 3010,

	CAPSANDBEVELS_BEVEL_TYPE_ROUND											= 0,
	CAPSANDBEVELS_BEVEL_TYPE_SOLID											= 1,
	CAPSANDBEVELS_BEVEL_TYPE_CURVE											= 2,
	CAPSANDBEVELS_BEVEL_TYPE_STEP												= 3,

	CAPSANDBEVELS_STARTBEVEL_GROUP												= 3015,
	CAPSANDBEVELS_STARTBEVEL_MODE													= 3016,
	CAPSANDBEVELS_BEVEL_MODE_COSTRAINED									= 0,
	CAPSANDBEVELS_BEVEL_MODE_EXTENDED										= 1,

	CAPSANDBEVELS_STARTBEVEL_TYPE													= 3017,

	CAPSANDBEVELS_STARTBEVEL_DEPTH												= 3018,
	CAPSANDBEVELS_STARTBEVEL_HEIGHT												= 3019,
	CAPSANDBEVELS_STARTBEVEL_CURVE												= 3020,
	CAPSANDBEVELS_STARTBEVEL_OFFSET												= 3021,
	CAPSANDBEVELS_STARTBEVEL_SEGMENTS											= 3022,
	CAPSANDBEVELS_STARTBEVEL_ALONGNORMALS									= 3023,
	CAPSANDBEVELS_STARTBEVEL_ABSOLUTE											= 3024,
	CAPSANDBEVELS_STARTBEVEL_ABSOLUTEDEPTH								= 3025,

	CAPSANDBEVELS_ENDBEVEL_GROUP													= 3029,
	CAPSANDBEVELS_ENDBEVEL_MODE														= 3030,
	CAPSANDBEVELS_ENDBEVEL_TYPE														= 3031,

	CAPSANDBEVELS_ENDBEVEL_DEPTH													= 3032,
	CAPSANDBEVELS_ENDBEVEL_HEIGHT													= 3033,
	CAPSANDBEVELS_ENDBEVEL_CURVE													= 3034,
	CAPSANDBEVELS_ENDBEVEL_OFFSET													= 3035,
	CAPSANDBEVELS_ENDBEVEL_SEGMENTS												= 3036,
	CAPSANDBEVELS_ENDBEVEL_ALONGNORMALS										= 3037,
	CAPSANDBEVELS_ENDBEVEL_ABSOLUTE												= 3038,
	CAPSANDBEVELS_ENDBEVEL_ABSOLUTEDEPTH									= 3039,

	CAPSANDBEVELS_BEVEL_OUTSIDE														= 3040,
	CAPSANDBEVELS_PHONGBREAKROUNDING											= 3041,
	CAPSANDBEVELS_AVOIDINTERSECTION												= 3042,

	CAPSANDBEVELS_STARTBEVEL_LOADPRESET										= 3050,
	CAPSANDBEVELS_STARTBEVEL_SAVEPRESET										= 3051,
	CAPSANDBEVELS_ENDBEVEL_LOADPRESET											= 3052,
	CAPSANDBEVELS_ENDBEVEL_SAVEPRESET											= 3053,

	CAPSANDBEVELS_USE_NEW_VERSION													= 5000,
};

#endif // ONURBSCAPS_H__
