#ifndef OPBDSIMULATIONS_H__
#define OPBDSIMULATIONS_H__

enum
{
	MESHDENOISERDEFORMER_ITERATIONS = 1000,
	MESHDENOISERDEFORMER_RECOMPUTENEIGHBORS = 1001,
	PBD_SIMULATIONS_RECOMPILE_SHADERS = 1002,
	PBD_SIMULATIONS_MODE = 1003,	
		PBD_SIMULATIONS_SPIRV_CROSS_ID = 0,
		PBD_SIMULATIONS_FVP_ID = 1,
		PBD_SIMULATIONS_FVP_CPU_XPBD_GS_ID = 2,
		PBD_SIMULATIONS_FVP_CPU_XPBD_JACOBI_ID = 3,
		PBD_SIMULATIONS_FVP_GPU_XPBD_JACOBI_ID = 4,
		PBD_SIMULATIONS_XPBD_JACOBI_CPU_ID = 5,
		PBD_SIMULATIONS_SIMULATIONSCENE_FVP_CPU_XPBD_JACOBI_ID = 6,
		PBD_SIMULATIONS_SIMULATIONSCENE_FVP_GPU_XPBD_JACOBI_ID = 7,
	PBD_SIMULATIONS_ITERCOUNT = 1004,
	PBD_SIMULATIONS_SUBSTEPS = 1005,
	PBD_SIMULATIONS_DELTAT = 1006,
	PBD_SIMULATIONS_CONTACT_DAMP = 1007,
	PBD_SIMULATIONS_STRETCH_BEND_DAMP = 1008,
	PBD_SIMULATIONS_CLOTH_THICKNESS = 1009,
	PBD_SIMULATIONS_ELASTIC_STIFFNESS = 1010,
	PBD_SIMULATIONS_BEND_STIFFNESS = 1011,
	PBD_SIMULATIONS_TOTAL_MASS = 1012,
	PBD_SIMULATIONS_PRESTAB_ITER_COUNT = 1013,
	PBD_SIMULATIONS_AERODYNAMICS_ACTIVE = 1014,
	PBD_SIMULATIONS_FLUID_DENSITY = 1015,
	PBD_SIMULATIONS_FLUID_VELOCITY = 1016,
	PBD_SIMULATIONS_AERODYNAMIC_DRAG_COEFFICIENT = 1017,
	PBD_SIMULATIONS_AERODYNAMIC_LIFT_COEFFICIENT = 1018,
	PBD_SIMULATIONS_STATIC_FRICTION = 1019,
	PBD_SIMULATIONS_DYNAMIC_FRICTION = 1020,
	PBD_SIMULATIONS_RECOMPUTE_CONTACTS = 1021,
	PBD_SIMULATIONS_PART_PART_CCD = 1022,
	PBD_SIMULATIONS_ADDITIONAL_OBJECTS = 1024
};

#endif // OPBDSIMULATIONS_H__
