#ifndef OSCULPTDISPLACEMENT_H__
#define OSCULPTDISPLACEMENT_H__

enum
{
	MDATA_DISPLACEMENT_LEVEL = 1000, //LONG
	MDATA_DISPLACEMENT_BAKE,	//Bool
	MDATA_DISPLACEMENT_ISTARGET,	//Bool
};

#endif // OSCULPTDISPLACEMENT_H__
