#ifndef OWINDDEFORM_H__
#define OWINDDEFORM_H__

enum
{
	WINDDEFORMOBJECT_AMPLITUDE	= 1000,
	WINDDEFORMOBJECT_FREQUENCY	= 1001,
	WINDDEFORMOBJECT_TURBULENCE	= 1002,
	WINDDEFORMOBJECT_FX					= 1003,
	WINDDEFORMOBJECT_FY					= 1004,
	WINDDEFORMOBJECT_FLAG				= 1005,
	WINDDEFORMOBJECT_SIZE				= 1006
};

#endif // OWINDDEFORM_H__
