#ifndef PREFSTHEME_H__
#define PREFSTHEME_H__

enum
{
	PREF_THEME_MAIN_GROUP		= 999,
	PREF_THEME_LIST					= 1000,
	PREF_THEME_COLORS				= 1001,
	PREF_THEME_LIVE					= 1002,
	PREF_THEME_TYPE					= 1003,
		PREF_THEME_TYPERGB		= 1,
		PREF_THEME_TYPEBMP		= 2,
		PREF_THEME_TYPEREF		= 3,
	PREF_THEME_BMP					= 1004,
	PREF_THEME_REF					= 1005,
	PREF_THEME_BMPPIC				= 1006,
	PREF_THEME_RESET				= 1007,
	PREF_THEME_DUMMY
};

#endif // PREFSTHEME_H__
