#ifndef PREFSNODEEDITOR_H__
#define PREFSNODEEDITOR_H__

enum
{
	PREF_NODE_EDITOR_MAIN_GROUP				= 999,
	PREF_NODE_EDITOR_PREVIEW					= 1000,
	PREF_NODE_EDITOR_GRID							= 1001,
	PREF_NODE_EDITOR_NAVIGATOR				= 1002,
	PREF_NODE_EDITOR_ERRORS						= 1003,
	PREF_NODE_EDITOR_INFO     				= 1005,
	PREF_NODE_EDITOR_IDS  	    			= 1006,

	PREF_NODE_EDITOR_DUMMY
};

#endif // PREFSNODEEDITOR_H__
