#ifndef SEBASE_H__
#define SEBASE_H__

enum
{
	ID_SEQPROPERTIES			= 807,
	ID_BASESEQ_NAME				= 900,
	ID_BASESEQ_T1         = 901,
	ID_BASESEQ_T2         = 902,
	ID_BASESEQ_T3         = 903,
	ID_BASESEQ_SOFT       = 904,
	ID_BASESEQ_LEFTI      = 905,
	ID_BASESEQ_RIGHTI     = 906,
	ID_BASESEQ_TIME       = 907,
	ID_BASESEQ_LOOPS      = 908,
	ID_BASESEQ_TIME_EXLOOP = 909

};

#endif // SEBASE_H__

