#ifndef _TGOZPOLYGROUP_H__
#define _TGOZPOLYGROUP_H__

enum
{
	ID_ADDPOLYGROUP = 2000,
	ID_GOZ_POLYGROUP,
	ID_ACTIVATEPOLYGROUPSELECTION,
	ID_OPERATION,
	ID_OPERATION_NEW,
	ID_OPERATION_ADD,
	ID_OPERATION_REMOVE,
	ID_SELECTION_TAB
};

#endif // _TGOZPOLYGROUP_H__