#ifndef TGROUPPRIORITYTAG_H__
#define TGROUPPRIORITYTAG_H__

enum
{
	GROUPPRIORITYTAG_PRIORITY				= 1000,
	GROUPPRIORITYTAG_EXCLUDELIST		= 1001,
	GROUPPRIORITYTAG_EXCLUSION_MODE = 1002,
		GROUPPRIORITYTAG_EXCLUSION_INCLUDE = 0,
		GROUPPRIORITYTAG_EXCLUSION_EXCLUDE = 1,
};

#endif // TGROUPPRIORITYTAG_H__



