#ifndef TMOTIONBLUR_H__
#define TMOTIONBLUR_H__

enum
{
	MOTIONBLURTAG_STRENGTH 		= 1000, // Real

	MOTIONBLURTAG_MODE		= 1010, // LONG
		MOTIONBLURTAG_MODE_FULL		= 0,
		MOTIONBLURTAG_MODE_MOTION	= 1,
		MOTIONBLURTAG_MODE_NONE		= 2
};

#endif // TMOTIONBLUR_H__
