#ifndef TOOLHAIRCURL_H__
#define TOOLHAIRCURL_H__

enum
{
	HAIR_TOOL_CURL_AMP_X = 1000,
	HAIR_TOOL_CURL_AMP_Y,
	HAIR_TOOL_CURL_PERIOD_X,
	HAIR_TOOL_CURL_PERIOD_Y,
	HAIR_TOOL_CURL_X,
	HAIR_TOOL_CURL_Y,
	HAIR_TOOL_CURL_STRENGTH,
	HAIR_TOOL_CURL_STRENGTH_X,
	HAIR_TOOL_CURL_STRENGTH_Y,
	HAIR_TOOL_CURL_ANGLE,
	HAIR_TOOL_CURL_TIGHTNESS,
	HAIR_TOOL_CURL_TIGHTEN,

	HAIR_TOOL_CURL_GROUP_CURLING = 4000,
	HAIR_TOOL_CURL_GROUP_STRENGTH,
	HAIR_TOOL_CURL_GROUP_TIGHTEN,

	//////////////////////////////////////////////////////////////////////////

	HAIR_TOOL_CURL_DUMMY
};

#endif // TOOLHAIRCURL_H__
