#ifndef TOOLCENTER_H__
#define TOOLCENTER_H__

enum
{
	MDATA_CENTER_XAXIS				= 1000,
	MDATA_CENTER_YAXIS				= 1001,
	MDATA_CENTER_ZAXIS				= 1002,
		MDATA_CENTER_NONE					= 0,
		MDATA_CENTER_NEG					= 1,
		MDATA_CENTER_POS					= 2,
		MDATA_CENTER_CENTER				= 3,

	MDATA_CENTER_
};

#endif // TOOLCENTER_H__
