#ifndef TOOLSOFTSELECTION_H__
#define TOOLSOFTSELECTION_H__

enum
{
	MDATA_SOFT_FALLOFF                    	= 2201,
		MDATA_SOFT_FALLOFF_LINEAR									= 0,
		MDATA_SOFT_FALLOFF_DOME										= 1,
		MDATA_SOFT_FALLOFF_BELL										= 2,
		MDATA_SOFT_FALLOFF_CIRCLE									= 3,
		MDATA_SOFT_FALLOFF_NEEDLE									= 4,
		MDATA_SOFT_FALLOFF_VMAP										= 5,
		MDATA_SOFT_FALLOFF_SPLINE									= 6,

	MDATA_SOFT_RADIUS                    		= 2202,
	MDATA_SOFT_STRENGTH											= 2203,
	MDATA_SOFT_MODE												= 2204,
		MDATA_SOFT_MODE_GROUPS = 0,
		MDATA_SOFT_MODE_CENTER = 1,
		MDATA_SOFT_MODE_ALL = 2,
	MDATA_SOFT_RUBBER												= 2205,
	MDATA_SOFT_SURFACE											= 2206,
	MDATA_SOFT_WIDTH	                      = 2207,
	MDATA_SOFT_SPLINE												= 2208,
	MDATA_SOFT_PREVIEW							= 2209,
	MDATA_SOFT_ENABLE							= 2210,
	MDATA_SOFT_RESTRICT							= 2211,

	MDATA_SOFT_END,

	MDATA_SOFTSELECTION				= 9998,

	MDATA_SELECTSOFT_
};

#endif // TOOLSOFTSELECTION_H__
