#ifndef TOOLSETEDGEFLOW_H__
#define TOOLSETEDGEFLOW_H__

enum
{
    MDATA_SETEDGEFLOW_FALLBACKMODE_NONE   = 0,
    MDATA_SETEDGEFLOW_FALLBACKMODE_EDGE   = 1,
    MDATA_SETEDGEFLOW_FALLBACKMODE_NORMAL = 2,
    MDATA_SETEDGEFLOW_TENSION             = 1100, //LONG
    MDATA_SETEDGEFLOW_ANGLELIMIT          = 1101, //LONG
    MDATA_SETEDGEFLOW_EQUALSPACING        = 1102, //BOOL
    MDATA_SETEDGEFLOW_LINEAR              = 1103, //BOOL
    MDATA_SETEDGEFLOW_FALLBACKMODE        = 1104  //LONG
};

#endif // TOOLSETEDGEFLOW_H__
