#ifndef TOOLKNIFEPLANE_H__
#define TOOLKNIFEPLANE_H__

enum
{
	MDATA_KNIFEPLANE_MODE	= 2003,							// LONG CYCLE
	MDATA_KNIFEPLANE_PLANE_MODE, 							// LONG CYCLE
	MDATA_KNIFEPLANE_PLANE,										// LONG CYCLE
	MDATA_KNIFEPLANE_PIVOT_POSITION,					// VECTOR
	MDATA_KNIFEPLANE_PIVOT_ROTATION,					// VECTOR
	MDATA_KNIFEPLANE_OFFSET, 									// FLOAT
	MDATA_KNIFEPLANE_CONUT,										// INT
	MDATA_KNIFEPLANE_DIST,										// FLOAT

	MDATA_KNIFEPLANE_SELECTED,								// BOOL
	MDATA_KNIFEPLANE_SELECT_CUT,							// BOOL
	MDATA_KNIFEPLANE_CUTPOLYS,								// BOOL
	MDATA_KNIFEPLANE_AUTOSNAP,								// BOOL

	MDATA_KNIFEPLANE_ANGLE_CONSTRAINT,				// BOOL
	MDATA_KNIFEPLANE_ANGLE_CONSTRAINT_VALUE,	// FLOAT
	MDATA_KNIFEPLANE_PLANE_PRESET,						// LONG CYCLE
	MDATA_KNIFEPLANE_NGON_CURVATURE,					// BOOL
	MDATA_KNIFEPLANE_REALTIME,								// BOOL
	MDATA_KNIFEPLANE_REGULARSLICE,						// BOOL

		MDATA_KNIFEPLANE_MODE_ALL= 0,
		MDATA_KNIFEPLANE_MODE_SPLIT,
		MDATA_KNIFEPLANE_MODE_REGION_A,
		MDATA_KNIFEPLANE_MODE_REGION_B,

		MDATA_KNIFEPLANE_PLANE_MODE_FREE = 0,
		MDATA_KNIFEPLANE_PLANE_MODE_LOCAL,
		MDATA_KNIFEPLANE_PLANE_MODE_WORLD,
		MDATA_KNIFEPLANE_PLANE_MODE_CAMERA,

		MDATA_KNIFEPLANE_PLANE_XY = 0,
		MDATA_KNIFEPLANE_PLANE_YZ,
		MDATA_KNIFEPLANE_PLANE_XZ,

		MDATA_KNIFEPLANE_PLANE_PRESET_X = 0,
		MDATA_KNIFEPLANE_PLANE_PRESET_X2,
		MDATA_KNIFEPLANE_PLANE_PRESET_Y,
		MDATA_KNIFEPLANE_PLANE_PRESET_Y2,
		MDATA_KNIFEPLANE_PLANE_PRESET_Z,
		MDATA_KNIFEPLANE_PLANE_PRESET_Z2,
		MDATA_KNIFEPLANE_PLANE_PRESET_CUSTOM,

	MDATA_KNIFEPLANE_MATRIX = 5000, 		// MATRIX
	MDATA_KNIFEPLANE_
};

#endif // TOOLKNIFEPLANE_H__
