#ifndef TOOLHAIRCOMB_H__
#define TOOLHAIRCOMB_H__

enum
{
	HAIR_TOOL_COMB_DIRECTION = 1000,
	HAIR_TOOL_COMB_STRENGTH,
	HAIR_TOOL_COMB_CURVE,
	HAIR_TOOL_COMB_DELETED_1,
	HAIR_TOOL_COMB_FROMROOT,
	HAIR_TOOL_COMB_WEIGHTED,
	HAIR_TOOL_COMB_LIMIT_DISTANCE,
	HAIR_TOOL_COMB_DISTANCE,
	HAIR_TOOL_COMB_WEIGHT,
	HAIR_TOOL_COMB_INTERSECT,
	HAIR_TOOL_COMB_SPLINE,
	HAIR_TOOL_COMB_SHADER,

	//////////////////////////////////////////////////////////////////////////

	HAIR_TOOL_COMB_DIRECTION_CAMERA_X = 0,
	HAIR_TOOL_COMB_DIRECTION_CAMERA_Y,
	HAIR_TOOL_COMB_DIRECTION_CAMERA_Z,
	HAIR_TOOL_COMB_DIRECTION_WORLD_X,
	HAIR_TOOL_COMB_DIRECTION_WORLD_Y,
	HAIR_TOOL_COMB_DIRECTION_WORLD_Z,
	HAIR_TOOL_COMB_DIRECTION_LOCAL_X,
	HAIR_TOOL_COMB_DIRECTION_LOCAL_Y,
	HAIR_TOOL_COMB_DIRECTION_LOCAL_Z,
	HAIR_TOOL_COMB_DIRECTION_SPLINE,
	HAIR_TOOL_COMB_DIRECTION_SHADER,

	//////////////////////////////////////////////////////////////////////////

	HAIR_TOOL_COMB_DUMMY
};

#endif // TOOLHAIRCOMB_H__
