#ifndef TOOLFLATTEN_H__
#define TOOLFLATTEN_H__

enum
{
	MDATA_FLATTEN_METHOD_BESTFIT = 1,
	MDATA_FLATTEN_METHOD_VIEW = 2,
	MDATA_FLATTEN_METHOD_NORMAL = 3,
	MDATA_FLATTEN_METHOD_AXIS = 4,
	MDATA_FLATTEN_METHOD_WORLD = 5,

	MDATA_FLATTEN_AXIS_X = 11,
	MDATA_FLATTEN_AXIS_Y = 12,
	MDATA_FLATTEN_AXIS_Z = 13,
	
	MDATA_FLATTEN_WEIGHT                = 1101, //REAL
	MDATA_FLATTEN_METHOD                = 1102, //LONG
	MDATA_FLATTEN_PLANEPOSITION         = 1103, //REAL
	MDATA_FLATTEN_INDIVIDUALISLANDS     = 1104, //BOOL
	MDATA_FLATTEN_OUTLINEONLY           = 1105, //BOOL
	MDATA_FLATTEN_AXIS                  = 1106, //LONG
	MDATA_FLATTEN_
};

#endif // TOOLFLATTEN_H__
