#ifndef XEARTH_H__
#define XEARTH_H__

enum
{
	EARTHSHADER_SEA				= 1000, // VECTOR
	EARTHSHADER_LAND			= 1001, // VECTOR
	EARTHSHADER_MOUNTAIN	= 1002, // VECTOR
	EARTHSHADER_FREQUENCY	= 1003,	// REAL
	EARTHSHADER_LEVEL			= 1004	// REAL
};

#endif // XEARTH_H__
