#ifndef XMARBLE_H__
#define XMARBLE_H__

enum
{
	MARBLESHADER_SCALE			= 1002,	 // VECTOR
	MARBLESHADER_TURBULENCE	= 1003,	 // REAL
	MARBLESHADER_COLOR			= 1006   // GRADIENT
};

#endif // XMARBLE_H__
