#ifndef XPLANET_H__
#define XPLANET_H__

enum
{
	PLANETSHADER_TYPE			= 1000,  // LONG
		PLANETSHADER_TYPE_URANUS			= 0,
		PLANETSHADER_TYPE_NEPTUNE			= 1,
		PLANETSHADER_TYPE_SATURN			= 2,
		PLANETSHADER_TYPE_SATURNRING	= 3
};

#endif // XPLANET_H__
