#ifndef FLCOLORIZE_H__
#define FLCOLORIZE_H__

enum
{
	FIELDLAYER_COLORIZE_SOURCE								= 1000,	// INT CYCLE
		FIELDLAYER_COLORIZE_SOURCE_VALUE					= 0,
		FIELDLAYER_COLORIZE_SOURCE_COLOR					= 1,
	FIELDLAYER_COLORIZE_MODE									= 1001,	// INT CYCLE
		FIELDLAYER_COLORIZE_MODE_MONOCHROME				= 0,
		FIELDLAYER_COLORIZE_MODE_DUOTONE					= 1,
	FIELDLAYER_COLORIZE_COLORBASE							= 1002,	// COLOR
	FIELDLAYER_COLORIZE_COLORBASE_DENSITY			= 1003,	// REAL
	FIELDLAYER_COLORIZE_COLORTOP							= 1004,	// COLOR
	FIELDLAYER_COLORIZE_COLORTOP_DENSITY			= 1005,	// REAL
	FIELDLAYER_COLORIZE_COLORTOP_MODE					= 1006,	// INT CYCLE
		FIELDLAYER_COLORIZE_COLORTOP_MODE_PIGMENT	= 0,
		FIELDLAYER_COLORIZE_COLORTOP_MODE_DYE			= 1,
	FIELDLAYER_COLORIZE_CLIP									= 1007, // BOOL
	FIELDLAYER_COLORIZE_DUMMY
};
#endif	// #FLCOLORIZE_H__

