#ifndef FLPYTHON_H__
#define FLPYTHON_H__

enum
{
	FIELDLAYER_PYTHON_FRAME = 1000,								// Bool
	FIELDLAYER_PYTHON_CODE = 1001,								// String
	FIELDLAYER_PYTHON_RESETFRAME0 = 1002,					// Bool
	FIELDLAYER_PYTHON_OPENEDITOR = 1003,					// Button
};
#endif	// FLPYTHON_H__
