#ifndef MGPOLYVOLUME_H__
#define MGPOLYVOLUME_H__

enum
{
	MG_POLYVOLUME_COUNT	= 1140,
	MG_POLYVOLUME_SEED	= 1141,
	MG_POLYVOLUME_MODE	= 1142,
		MG_POLYVOLUME_MODE_RANDOM	= 0,
		MG_POLYVOLUME_MODE_SURFACE = 1
};
#endif // MGPOLYVOLUME_H__
