#ifndef NEUTRONGENERATOR_H__
#define NEUTRONGENERATOR_H__

enum
{
	NEUTRON_GENERATOR_GROUP = 11000,

	NEUTRON_GENERATOR_INSTANCE_MODE =	12000,
		NEUTRON_GENERATOR_INSTANCE_MODE_NONE = 0,
		NEUTRON_GENERATOR_INSTANCE_MODE_RENDERINSTANCE,
		NEUTRON_GENERATOR_INSTANCE_MODE_MULTIINSTANCE,

	NEUTRONGENERATOR_DUMMY
};

#endif // NEUTRONGENERATOR_H__
