#ifndef OCAJIGGLE_H__
#define OCAJIGGLE_H__

enum
{
	ID_CA_JIGGLE_OBJECT_CACHE_GROUP = 5000,
	ID_CA_JIGGLE_OBJECT_FORCES_GROUP,
	ID_CA_JIGGLE_OBJECT_CACHE_ADVANCED,
	ID_CA_JIGGLE_OBJECT_RESTRICTION_GROUP,

	ID_CA_JIGGLE_OBJECT_SOURCE = 2000,
	ID_CA_JIGGLE_OBJECT_STRENGTH,
	ID_CA_JIGGLE_OBJECT_STIFFNESS,
	ID_CA_JIGGLE_OBJECT_SPRINGS,
	ID_CA_JIGGLE_OBJECT_DRAG,
	ID_CA_JIGGLE_OBJECT_ONSTOP,
	ID_CA_JIGGLE_OBJECT_LOCAL,
	ID_CA_JIGGLE_OBJECT_GRAVITY,
	ID_CA_JIGGLE_OBJECT_FORCES,
	ID_CA_JIGGLE_OBJECT_STIFFNESS_MAP,
	ID_CA_JIGGLE_OBJECT_DRAG_MAP,
	ID_CA_JIGGLE_OBJECT_FORCES_MAP,
	ID_CA_JIGGLE_OBJECT_ITERATIONS,

	ID_CA_JIGGLE_OBJECT_CACHE_ENABLE,
	ID_CA_JIGGLE_OBJECT_CACHE_CALCULATE,
	ID_CA_JIGGLE_OBJECT_CACHE_COMPRESSED,
	ID_CA_JIGGLE_OBJECT_CACHE_DELETE,
	ID_CA_JIGGLE_OBJECT_CACHE_INFO1,
	ID_CA_JIGGLE_OBJECT_CACHE_INFO2,
	ID_CA_JIGGLE_OBJECT_CACHE_CACHE_LOAD,
	ID_CA_JIGGLE_OBJECT_CACHE_CACHE_SAVE,
	ID_CA_JIGGLE_OBJECT_CACHE_CACHE_LIMIT,
	ID_CA_JIGGLE_OBJECT_CACHE_TEXT_LIMIT,

	ID_CA_JIGGLE_OBJECT_MOTION_SCALE,
	ID_CA_JIGGLE_OBJECT_STRUCTUAL_STIFFNESS,
	ID_CA_JIGGLE_OBJECT_STRUCTUAL_STIFFNESS_MAP,

	ID_CA_JIGGLE_OBJECT_CACHE_UPDATE,
	ID_CA_JIGGLE_OBJECT_CACHE_AUTOTIME,
	ID_CA_JIGGLE_OBJECT_CACHE_START,
	ID_CA_JIGGLE_OBJECT_CACHE_STOP,
	ID_CA_JIGGLE_OBJECT_CACHE_OFFSET,
	ID_CA_JIGGLE_OBJECT_CACHE_TIMESCALE,

	ID_CA_JIGGLE_OBJECT_RESTRICT,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_JIGGLE_OBJECT_DUMMY
};

#endif // OCAJIGGLE_H__
