#ifndef OCONNECTOR_H__
#define OCONNECTOR_H__

enum
{
	CONNECTOBJECT_WELD		= 1000,
	CONNECTOBJECT_TOLERANCE,
	CONNECTOBJECT_PHONG_MODE,
	CONNECTOBJECT_TEXTURES,
	CONNECTOBJECT_CENTERAXIS,
	CONNECTOBJECT_LINK,

	//

	CONNECTOBJECT_PHONG_MODE_MANUAL = 0,
	CONNECTOBJECT_PHONG_MODE_AVERAGE,
	CONNECTOBJECT_PHONG_MODE_LOW,
	CONNECTOBJECT_PHONG_MODE_HIGH,
	CONNECTOBJECT_PHONG_MODE_TOBREAKS,
};

#endif // OCONNECTOR_H__
