#ifndef OEPYTHON_H__
#define OEPYTHON_H__

enum
{
	OEPYTHON_STRING							=	1100,
	OEPYTHON_OPENEDITOR					=	1101,
	OEPYTHON_MODE								=	1102,
		OEPYTHON_MODE_PARAMETERS		= 0,
		OEPYTHON_MODE_FULLCONTROL		=	1,
	OEPYTHON_RESET							= 1103,
	OEPYTHON_FRAME							= 1104,
	OEPYTHONDUMMY
};
#endif // OEPYTHON_H__
