#ifndef ONURBSSELECTION_H__
#define ONURBSSELECTION_H__

enum
{
	ID_GENERATOR_SELECTION_POLYGONS								= 4000,
	GENERATOR_SELECTION_POLYGON_SHELL							= 4001,
	GENERATOR_SELECTION_POLYGON_CAP_START					= 4002,
	GENERATOR_SELECTION_POLYGON_CAP_END						= 4003,
	GENERATOR_SELECTION_POLYGON_BEVEL_START				= 4004,
	GENERATOR_SELECTION_POLYGON_BEVEL_END					= 4005,

	ID_GENERATOR_SELECTION_EDGES									= 4010,
	GENERATOR_SELECTION_EDGE_SHELL_START					= 4011,
	GENERATOR_SELECTION_EDGE_SHELL_END						= 4012,
	GENERATOR_SELECTION_EDGE_CAP_START						= 4013,
	GENERATOR_SELECTION_EDGE_CAP_END							= 4014,
	GENERATOR_SELECTION_EDGE_STEP_START						= 4015,
	GENERATOR_SELECTION_EDGE_STEP_END							= 4016,

	GENERATOR_SELECTION_NAME_POLYGON_SHELL				= 4101,
	GENERATOR_SELECTION_NAME_POLYGON_CAP_START		= 4102,
	GENERATOR_SELECTION_NAME_POLYGON_CAP_END			= 4103,
	GENERATOR_SELECTION_NAME_POLYGON_BEVEL_START	= 4104,
	GENERATOR_SELECTION_NAME_POLYGON_BEVEL_END		= 4105,
	GENERATOR_SELECTION_NAME_EDGE_SHELL_START			= 4111,
	GENERATOR_SELECTION_NAME_EDGE_SHELL_END				= 4112,
	GENERATOR_SELECTION_NAME_EDGE_CAP_START				= 4113,
	GENERATOR_SELECTION_NAME_EDGE_CAP_END					= 4114,
	GENERATOR_SELECTION_NAME_EDGE_STEP_START			= 4115,
	GENERATOR_SELECTION_NAME_EDGE_STEP_END				= 4116
};

#endif // ONURBSSELECTION_H__

