#ifndef OP_BORN_H__
#define OP_BORN_H__

#include "gvbase.h"

enum
{
	OP_BORN_BTYPE			= 1000,
	OP_BORN_COUNT			= 1001,
	OP_BORN_RATE			= 1002,
	OP_BORN_SHOT			= 1003,
	OP_BORN_LIFE			= 1004,
	OP_BORN_LIFEVAR		= 1005,
	OP_BORN_SEED			= 1006,

	OP_BORN_IN_ON							= 2000,
	OP_BORN_IN_ATIME					= 2001,
	OP_BORN_OUT_PARTICLE			= 3000,
	OP_BORN_OUT_PARTICLECOUNT	= 3001,
	OP_BORN_OUT_PARTICLENUM		= 3002,

	OP_BORN_BTYPE_COUNT		= 0,
	OP_BORN_BTYPE_RATE		= 1,
	OP_BORN_BTYPE_SHOT		= 2
};





#endif // OP_BORN_H__
