#ifndef OP_MATTERWAVES_H__
#define OP_MATTERWAVES_H__

#include "gvbase.h"

enum
{
	OP_MATTERWAVES_SEED				= 1000,

	OP_MATTERWAVES_BTYPE			= 1001,
	OP_MATTERWAVES_COUNT			= 1002,
	OP_MATTERWAVES_RATE				= 1003,
	OP_MATTERWAVES_SHOT				= 1004,

	OP_MATTERWAVES_LIFE				= 1005,
	OP_MATTERWAVES_LIFEVAR		= 1006,

	OP_MATTERWAVES_SPEED			= 1007,
	OP_MATTERWAVES_SPEEDVAR		= 1008,

	OP_MATTERWAVES_DISTANCE		= 1009,
	OP_MATTERWAVES_DISTVAR		= 1010,

	OP_MATTERWAVES_OBJECT			= 1011,
	OP_MATTERWAVES_SELECTION	= 1012,
	OP_MATTERWAVES_UVW				= 1013,
	OP_MATTERWAVES_UVWTYPE		= 1014,

	OP_MATTERWAVES_BIRTHTYPE	= 1015,
	OP_MATTERWAVES_BIRTHTEX		= 1016,
	OP_MATTERWAVES_BIRTHGRAD	= 1017,

	OP_MATTERWAVES_LIFETYPE		= 1018,
	OP_MATTERWAVES_LIFETEX		= 1019,
	OP_MATTERWAVES_LIFEGRAD		= 1020,

	OP_MATTERWAVES_SPEEDTYPE	= 1021,
	OP_MATTERWAVES_SPEEDTEX		= 1022,
	OP_MATTERWAVES_SPEEDGRAD	= 1023,

	OP_MATTERWAVES_DISTTYPE		= 1024,
	OP_MATTERWAVES_DISTTEX		= 1025,
	OP_MATTERWAVES_DISTGRAD		= 1026,

	OP_MATTERWAVES_DIRTYPE		= 1027,
	OP_MATTERWAVES_DIRTEX			= 1028,
	OP_MATTERWAVES_DIRGRAD		= 1029,

	OP_MATTERWAVES_LIGHTLIST	= 1030,

	OP_MATTERWAVES_DIRINTENS	= 1031,
	OP_MATTERWAVES_DIRVAR			= 1032,

	OP_MATTERWAVES_SIZE				= 1033,
	OP_MATTERWAVES_SIZEVAR		= 1034,
	OP_MATTERWAVES_SIZETYPE		= 1035,
	OP_MATTERWAVES_SIZETEX		= 1036,
	OP_MATTERWAVES_SIZEGRAD		= 1037,



	OP_MATTERWAVES_IN_ON							= 2000,
	OP_MATTERWAVES_IN_ATIME						= 2001,
	OP_MATTERWAVES_IN_PARTICLE				= 2002,
	OP_MATTERWAVES_OUT_PARTICLE				= 3000,
	OP_MATTERWAVES_OUT_PARTICLECOUNT	= 3001,
	OP_MATTERWAVES_OUT_PARTICLENUM		= 3002,
	OP_MATTERWAVES_OUT_UVW						= 3003,

	OP_MATTERWAVES_BTYPE_COUNT	= 0,
	OP_MATTERWAVES_BTYPE_RATE		= 1,
	OP_MATTERWAVES_BTYPE_SHOT		= 2,

	OP_MATTERWAVES_UVWTYPE_UNCLAMP = 0,
	OP_MATTERWAVES_UVWTYPE_CLAMP	 = 1,

	OP_MATTERWAVES_BIRTHTYPE_CONSTANT = 0,
	OP_MATTERWAVES_BIRTHTYPE_MAP	    = 1,
	OP_MATTERWAVES_BIRTHTYPE_LIGHT	  = 2,
	OP_MATTERWAVES_BIRTHTYPE_MAPLIGHT = 3,

	OP_MATTERWAVES_LIFETYPE_CONSTANT = 0,
	OP_MATTERWAVES_LIFETYPE_MAP	     = 1,
	OP_MATTERWAVES_LIFETYPE_LIGHT	   = 2,
	OP_MATTERWAVES_LIFETYPE_MAPLIGHT = 3,

	OP_MATTERWAVES_SPEEDTYPE_CONSTANT = 0,
	OP_MATTERWAVES_SPEEDTYPE_MAP	    = 1,
	OP_MATTERWAVES_SPEEDTYPE_LIGHT	  = 2,
	OP_MATTERWAVES_SPEEDTYPE_MAPLIGHT = 3,

	OP_MATTERWAVES_SIZETYPE_CONSTANT = 0,
	OP_MATTERWAVES_SIZETYPE_MAP			 = 1,
	OP_MATTERWAVES_SIZETYPE_LIGHT		 = 2,
	OP_MATTERWAVES_SIZETYPE_MAPLIGHT = 3,

	OP_MATTERWAVES_DISTTYPE_CONSTANT = 0,
	OP_MATTERWAVES_DISTTYPE_MAP	     = 1,
	OP_MATTERWAVES_DISTTYPE_LIGHT	   = 2,
	OP_MATTERWAVES_DISTTYPE_MAPLIGHT = 3,

	OP_MATTERWAVES_DIRTYPE_NORMAL		= 0,
	OP_MATTERWAVES_DIRTYPE_MAP			= 1,
	OP_MATTERWAVES_DIRTYPE_LIGHTDIR	= 2,
	OP_MATTERWAVES_DIRTYPE_LIGHTREF	= 3
};





#endif // OP_MATTERWAVES_H__
