#ifndef OSCATTERPLACEMENT_H__
#define OSCATTERPLACEMENT_H__

enum
{
  ID_SCATTERPLACEMENT_ALL_OBJECT_LIST = 1003,
  OBJ_HIDE_IN_OM = 1800,
  OBJ_ALLOW_SELECTION,
  OScatterPlacement         = 2000,
};

#endif // OSCATTERPLACEMENT_H__
