#ifndef OSTAGE_H__
#define OSTAGE_H__

enum
{
	STAGEOBJECT_CLINK			= 1100,
	STAGEOBJECT_SLINK			= 1101,
	STAGEOBJECT_FLINK			= 1102,
	STAGEOBJECT_BLINK			= 1103,
	STAGEOBJECT_ELINK			= 1104
};

#endif // OSTAGE_H__
