#ifndef OSYMMETRY_H__
#define OSYMMETRY_H__

enum
{
	SYMMETRYOBJECT_PLANE						= 1000,		//Int
		SYMMETRYOBJECT_PLANE_XY					= 0,
		SYMMETRYOBJECT_PLANE_YZ					= 1,
		SYMMETRYOBJECT_PLANE_XZ					= 2,
	SYMMETRYOBJECT_WELD							= 1001,		//Bool
	SYMMETRYOBJECT_TOLERANCE				= 1002,		//Float
	SYMMETRYOBJECT_ONPLANE					= 1003,		//Bool
	SYMMETRYOBJECT_GROUP_MODELING		=	1004,
	SYMMETRYOBJECT_CLAMPPOINTS			=	1005,		//Bool
	SYMMETRYOBJECT_DELETEPOLYGONS		=	1006,		//Bool
	SYMMETRYOBJECT_AUTOFLIP					=	1007,		//Bool
	SYMMETRYOBJECT_FLIP							= 1008		//Button
};

#endif // OSYMMETRY_H__
