#ifndef PREFSLIVELINK_H__
#define PREFSLIVELINK_H__

enum
{
	PREF_COMMUNICATION_LIVELINK_ENABLED = 1022,
	PREF_COMMUNICATION_LIVELINK_PORT = 1023,
	PREF_COMMUNICATION_LIVELINK = 1024,
	PREF_COMMUNICATION_LIVELINKGROUP = 1025,
};

#endif // PREFSLIVELINK_H__