#ifndef PREFSVIEW_H__
#define PREFSVIEW_H__

enum
{
	// Groups
	PREFS_VIEW_GROUP								= 900,
	PREFS_VIEW_PERFORMANCE_GROUP		= 901,
	PREFS_VIEW_SYSTEM_GROUP					= 902,
	PREFS_VIEW_HANDLES_GROUP				= 903,
	PREFS_VIEW_VP_ELEMENTS_GROUP		= 904,
	PREFS_VIEW_OBJ_SELECTION_GROUP	= 905,

	PREF_VIEW_FULLANIMREDRAW			= 1001,
	PREF_VIEW_MONITORASPECT				= 1006,
	PREF_VIEW_COLORPROFILE				= 1007,
	PREF_VIEW_REALTIME						= 1008,
	PREF_VIEW_WARNING							= 1009,
	PREF_VIEW_REALTIME_MATERIAL		= 1010,

	PREF_VIEW_LINEAR_WORKFLOW											= 1011, // BASEDRAW_DATA_ENABLE_LWF
	PREF_VIEW_OBJECTAXIS_SCALE										= 1012, // BASEDRAW_DATA_OBJECTAXIS_SCALE
	PREF_VIEW_ROTATION_CIRCLE											= 1013, // BASEDRAW_DATA_ROTATION_CIRCLE
	PREF_VIEW_ROTATION_BANDS											= 1014, // BASEDRAW_DATA_ROTATION_BANDS
	PREF_VIEW_ROTBAND_SCALE												= 1015, // BASEDRAW_DATA_ROTBAND_SCALE
	PREF_VIEW_POINT_SELECTED_SIZE									= 1016, // BASEDRAW_DATA_POINT_SELECTED_SIZE
	PREF_VIEW_POINT_HANDLE_SIZE										= 1017, // BASEDRAW_DATA_POINT_HANDLE_SIZE
	PREF_VIEW_EDGE_SELECTED_SIZE									= 1018, // BASEDRAW_DATA_EDGE_SELECTED_SIZE
	PREF_VIEW_EDGE_UNSELECTED_SIZE								= 1019, // BASEDRAW_DATA_EDGE_UNSELECTED_SIZE
	PREF_VIEW_SPLINE_WIDTH												= 1020, // BASEDRAW_DATA_SPLINE_WIDTH
	PREF_VIEW_NORMALS_SCALE												= 1021, // BASEDRAW_DATA_NORMALS_SCALE
	PREF_VIEW_EDGE_POINTS													= 1022, // BASEDRAW_DATA_EDGE_POINTS
	PREF_VIEW_EDITOR_AXIS_POS											= 1023, // BASEDRAW_DATA_EDITOR_AXIS_POS
		PREF_VIEW_AXIS_POS_OFF												= 0, // BASEDRAW_AXIS_POS_OFF
		PREF_VIEW_AXIS_POS_BL													= 1, // BASEDRAW_AXIS_POS_BL
		PREF_VIEW_AXIS_POS_TL													= 2, // BASEDRAW_AXIS_POS_TL
		PREF_VIEW_AXIS_POS_TR													= 3, // BASEDRAW_AXIS_POS_TR
		PREF_VIEW_AXIS_POS_BR													= 4, // BASEDRAW_AXIS_POS_BR
	PREF_VIEW_EDITOR_AXIS_TYPE										= 1024, // BASEDRAW_DATA_EDITOR_AXIS_TYPE
		PREF_VIEW_AXIS_TYPE_WORLD											= 0, // BASEDRAW_AXIS_TYPE_WORLD
		PREF_VIEW_AXIS_TYPE_OBJECT										= 1, // BASEDRAW_AXIS_TYPE_OBJECT
	PREF_VIEW_EDIT_AXIS_SCALE											= 1025, // BASEDRAW_DATA_EDIT_AXIS_SCALE
	PREF_VIEW_EDIT_AXIS_TEXT											= 1026, // BASEDRAW_DATA_EDIT_AXIS_TEXT
	PREF_VIEW_OUTLINES														= 1027, // BASEDRAW_DATA_OUTLINE
	PREF_VIEW_OUTLINE_WIDTH												= 1028, // BASEDRAW_DATA_OUTLINE_WIDTH
	PREF_VIEW_SEL_BOUNDINGBOXSELECTION						= 1029, // BASEDRAW_DATA_BOUNDINGBOXSELECTION
	PREF_VIEW_SEL_BOUNDINGBOXSELECTION_CHILDREN		= 1030, // BASEDRAW_DATA_BOUNDINGBOXSELECTION_CHILDREN
	PREF_VIEW_SEL_WIREFRAMESELECTION							= 1031, // BASEDRAW_DATA_WIREFRAMESELECTION
	PREF_VIEW_SEL_WIREFRAMESELECTION_CHILDREN			= 1032, // BASEDRAW_DATA_WIREFRAMESELECTION_CHILDREN
	PREF_VIEW_DISPLAYFILTER_GRADIENT							= 1033, // BASEDRAW_DISPLAYFILTER_GRADIENT
	PREF_VIEW_DISPLAYFILTER_HANDLEBANDS						= 1034, // BASEDRAW_DISPLAYFILTER_HANDLEBANDS

	PREF_VIEW_DUMMY
};

#endif // PREFSVIEW_H__
