#ifndef PREFSTIMELINE_H__
#define PREFSTIMELINE_H__

enum
{
	PREF_TL_MAIN_GROUP						= 999,
	PREF_TL_HIGHLIGHT							= 1000,
	PREF_TL_HIGHLIGHTCURVE				= 1001,
	PREF_TL_INDICATOR							= 1003,
	PREF_TL_SUMMARY								= 1004,
	PREF_TL_LAYERCOL							= 1006,
	PREF_TL_TRACKSTARTEND					= 1007,
	PREF_TL_INTERACTIVE						= 1008,
	PREF_TL_DOPESHEET							= 1009,
	PREF_TL_KEYWIDTHVALUE					= 1011,
	PREF_TL_TRACKCOL							= 1012,
		PREF_TL_TRACKCOL_COL						= 0,
		PREF_TL_TRACKCOL_PSR						= 1,
		PREF_TL_TRACKCOL_NO							= 2,
	PREF_TL_RMREDUCTION						= 1013,
	PREF_TL_MOTION								= 1014,
	PREF_TL_KEYSYMBOLS						= 1015,
	PREF_TL_SHOWBRANCHES					= 1016,
	PREF_TL_SHOWVECTOR						= 1017,
	PREF_TL_KEYFRAMEDOTS					=	1018,
	PREF_TL_DOTSKILLTRACKS				=	1019,
	PREF_TL_LINKKEYFCSELECTION		=	1020,
	PREF_TL_LINKOMSELECTONLY			= 1021,

	PREF_TL_LINKOMSELECTONLYBUTTAGS = 1023,
	PREF_TL_FCLISTVIEW						= 1024,
	PREF_TL_FCLISTVIEW_HIERARCHICAL	= 1025,

	PREF_TL_KEYGROUP							= 2000,
	PREF_TL_FCGROUP								= 2001,
	PREF_TL_MOTIONGROUP						= 2002,
	PREF_TL_DISPLAYGROUP					= 2003,
	PREF_TL_OBJECTGROUP						= 2004,
	PREF_TL_AMGROUP								=	2005,
	PREF_TL_LINKGROUP							= 2006,

	PREF_TL_DUMMY
};

#endif // PREFSTIMELINE_H__
