#ifndef SBNURBS_H__
#define SBNURBS_H__

enum
{
	NURBSSURFACE_UCLOSED								= 1101,
	NURBSSURFACE_VCLOSED								= 1102,
	NURBSSURFACE_UDEGREE								= 1103,
	NURBSSURFACE_VDEGREE								= 1104,
	NURBSSURFACE_UPOINTCOUNT							= 1105,
	NURBSSURFACE_VPOINTCOUNT							= 1106,

	NURBSSURFACE_POLYNOMIAL								= 1110,
	NURBSSURFACE_UPERIODICITY							= 1111,
	NURBSSURFACE_VPERIODICITY							= 1112,

	NURBSSURFACE_UMIN									= 1120,
	NURBSSURFACE_UMAX									= 1121,
	NURBSSURFACE_VMIN									= 1122,
	NURBSSURFACE_VMAX									= 1123
};

#endif // SBNURBS_H__
