#ifndef TSIMULATIONSCENETAG_H__
#define TSIMULATIONSCENETAG_H__

enum
{
	SIMULATIONSCENE_DYNAMIC      = 2000,
	SIMULATIONSCENE_BLOBGEOMETRY = 2001,
	SIMULATIONSCENE_GRAVITY      = 2003,
	SIMULATIONSCENE_DENSITY      = 2004,
	SIMULATIONSCENE_LINEAR_DAMPING      = 2005,
	SIMULATIONSCENE_ANGULAR_DAMPING     = 2006,
	_SIMULATIONSCENETAG_END_
};

#endif // TSIMULATIONSCENETAG_H__
