#ifndef TCAVS_H__
#define TCAVS_H__

enum
{
	ID_CA_TAG_VS_GROUP_SETUP = 5000,
	ID_CA_TAG_VS_GROUP_TOOLS,
	ID_CA_TAG_VS_GROUP_HOTSPOT,
	ID_CA_TAG_VS_GROUP_IMAGE,
	ID_CA_TAG_VS_GROUP_COORDS,
	ID_CA_TAG_VS_GROUP_USERDATA,

	ID_CA_TAG_VS_IMAGE = 1000,
	ID_CA_TAG_VS_HOTSPOTS,
	ID_CA_TAG_VS_IMAGE_NAME,
	ID_CA_TAG_VS_ZOOM,
	ID_CA_TAG_VS_LEFT,
	ID_CA_TAG_VS_TOP,
	ID_CA_TAG_VS_RIGHT,
	ID_CA_TAG_VS_BOTTOM,
	ID_CA_TAG_VS_TRANS,
	ID_CA_TAG_VS_COL,
	ID_CA_TAG_VS_ADD_VIEW,
	ID_CA_TAG_VS_ADD_HOTSPOT,
	ID_CA_TAG_VS_MODE,
	ID_CA_TAG_VS_LINK,
	ID_CA_TAG_VS_ACTION,
	ID_CA_TAG_VS_COMMAND,
	ID_CA_TAG_VS_PYTHON,
	ID_CA_TAG_VS_BRUSH,
	ID_CA_TAG_VS_HIGHLIGHT_TRANS,
	ID_CA_TAG_VS_SELECT_TRANS,
	ID_CA_TAG_VS_HIGHLIGHT_COL,
	ID_CA_TAG_VS_SELECT_COL,
	ID_CA_TAG_VS_REMOVE,
	ID_CA_TAG_VS_COORDS_CONTAINER,
	ID_CA_TAG_VS_USERDATA_CONTAINER,
	ID_CA_TAG_VS_VIEW,
	ID_CA_TAG_VS_LASSO,
	ID_CA_TAG_VS_SHAPE,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_TAG_VS_MODE_EDIT = 0,
	ID_CA_TAG_VS_MODE_ANIMATE,

	ID_CA_TAG_VS_ACTION_MOVE = 0,
	ID_CA_TAG_VS_ACTION_SCALE,
	ID_CA_TAG_VS_ACTION_ROTATE,
	ID_CA_TAG_VS_ACTION_COMMAND,
	ID_CA_TAG_VS_ACTION_SCRIPT,
	ID_CA_TAG_VS_ACTION_VIEW,
	ID_CA_TAG_VS_ACTION_NONE,

	ID_CA_TAG_VS_LASSO_FREE = 0,
	ID_CA_TAG_VS_LASSO_POLY,
	ID_CA_TAG_VS_LASSO_RECT,

	ID_CA_TAG_VS_SHAPE_RECT = 0,
	ID_CA_TAG_VS_SHAPE_ELLIPSE,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_TAG_VS_DUMMY
};

#endif // TCAVS_H__
