#ifndef TCVARTSMART_H__
#define TCVARTSMART_H__

enum
{
	AI_ART_TAG_CHECKSUM			= 8000,
	AI_ART_TAG_STROKED			= 8001,
	AI_ART_TAG_FILLED			= 8002,
	AI_ART_TAG_STROKECOLOR			= 8003,
	AI_ART_TAG_FILLCOLOR			= 8004,
	AI_ART_TAG_STROKEWIDTH			= 8005,
	AI_ART_TAG_AUTOCLOSE			= 8006,
};

#endif // TCVARTSMART_H__
