#ifndef THAIRCOLLIDER_H__
#define THAIRCOLLIDER_H__

enum
{
	HAIR_COLLIDER_FRICTION = 1000,
	HAIR_COLLIDER_BOUNCE,
	HAIR_COLLIDER_LINK,
	HAIR_COLLIDER_COLLISIONS,
	HAIR_COLLIDER_FORCES,
	HAIR_COLLIDER_FORCE_STRENGTH,
	HAIR_COLLIDER_FORCE_STRENGTH_LINK,

	HAIR_COLLIDER_FORCES_OBJECTS,
	HAIR_COLLIDER_FORCES_OBJECTS_RADIUS,
	HAIR_COLLIDER_FORCES_OBJECTS_MAXSTRENGTH,
	HAIR_COLLIDER_FORCES_OBJECTS_FALLOFF,
	HAIR_COLLIDER_FORCES_OBJECTS_FALLOFF_SPLINE,

	//////////////////////////////////////////////////////////////////////////

	HAIR_COLLIDER_FORCES_FALLOFF_CONSTANT = 0,
	HAIR_COLLIDER_FORCES_FALLOFF_LINEAR,
	HAIR_COLLIDER_FORCES_FALLOFF_SQUARE,
	HAIR_COLLIDER_FORCES_FALLOFF_CUBIC,
	HAIR_COLLIDER_FORCES_FALLOFF_CUSTOM,

	//////////////////////////////////////////////////////////////////////////

	HAIR_COLLIDER_TAG_DUMMY
};

#endif // THAIRCOLLIDER_H__
