#ifndef THAIRPREFS_H__
#define THAIRPREFS_H__

enum
{
	HAIR_PREFS_MAIN_GROUP = 999,
	HAIR_PREFS_GROUP_MAIN = 2000,

	HAIR_PREFS_SETUP_AUTOVP = 1000,
	HAIR_PREFS_SETUP_AUTO_MATERIAL,
	HAIR_PREFS_COLORS,
	HAIR_PREFS_COLOR,
	HAIR_PREFS_PREVIEW,
	HAIR_PREFS_CUSTOMPREVIEW,
	HAIR_PREFS_SETUP_AUTO_LINK,
	HAIR_PREFS_SETUP_TOCHILD,
	HAIR_PREFS_SHOW_CURSOR,
	HAIR_PREFS_HIGHLIGHTING,
	HAIR_PREFS_OBJECT_UNDO,
	HAIR_PREFS_DYNAMICS_UNDO,
	HAIR_PREFS_DELETED_1,
	HAIR_PREFS_UNROOTED,

	//////////////////////////////////////////////////////////////////////////

	HAIR_PREFS_PREVIEW_STANDARD = 0,
	HAIR_PREFS_PREVIEW_CUBE,
	HAIR_PREFS_PREVIEW_ROUNDCUBE,
	HAIR_PREFS_PREVIEW_PLANE,
	HAIR_PREFS_PREVIEW_CYLINDER,
	HAIR_PREFS_PREVIEW_TORUS,
	HAIR_PREFS_PREVIEW_PLANEBACK,
	HAIR_PREFS_PREVIEW_SPHERE,
	HAIR_PREFS_PREVIEW_DOUBLETORUS,
	HAIR_PREFS_PREVIEW_KNOT,
	HAIR_PREFS_PREVIEW_STRAND,
	HAIR_PREFS_PREVIEW_CUSTOM,

	HAIR_PREFS_SHOW_CURSOR_OFF = 0,
	HAIR_PREFS_SHOW_CURSOR_ALWAYS,
	HAIR_PREFS_SHOW_CURSOR_DRAG,

	//////////////////////////////////////////////////////////////////////////

	HAIR_PREFS_TAG_DUMMY
};

#endif // THAIRPREFS_H__
