#ifndef TMWEIGHT_H__
#define TMWEIGHT_H__

enum
{
	MGWEIGHTTAG_CLEAR					= 1000,		// BUTTON
	MGWEIGHTTAG_INVERT				= 1001,		// BUTTON
	MGWEIGHTTAG_USEFIELDS			= 1002,		// BOOL
	MGWEIGHTTAG_FIELDS				= 1003,		// FIELDLIST
	MGWEIGHTTAG_GROUP_FIELDS	= 1004,		// GROUP
	MGWEIGHTTAG_FIELDDEFORM		= 1005,		// BOOL

	MGWEIGHTTAG_DUMMY__
};
#endif // TMWEIGHT_H__
