#ifndef TOOLEXTRUDEINNER_H__
#define TOOLEXTRUDEINNER_H__

enum
{
	MDATA_EXTRUDEINNER_PRESERVEGROUPS					= 2036, //	BOOL
	MDATA_EXTRUDEINNER_OFFSET									= 2037, //	REAL
	MDATA_EXTRUDEINNER_ANGLE									= 2038, // REAL
	MDATA_EXTRUDEINNER_VARIANCE								= 2039, // REAL
	MDATA_EXTRUDEINNER_SUBDIVISION						= 2170, // LONG
	MDATA_EXTRUDEINNER_CREATENGONS						= 2171, // BOOL

	MDATA_EXTRUDEINNER_
};

#endif // TOOLEXTRUDEINNER_H__
