#ifndef TOOLHAIRADDROOT_H__
#define TOOLHAIRADDROOT_H__

enum
{
	HAIR_TOOL_ADDROOT_RADIUS = 1000,
	HAIR_TOOL_ADDROOT_COUNT,
	HAIR_TOOL_ADDROOT_STEP,
	HAIR_TOOL_ADDROOT_INTERPOLATE,
	HAIR_TOOL_ADDROOT_LENGTH,
	HAIR_TOOL_ADDROOT_MINSPACING,
	HAIR_TOOL_ADDROOT_PEN,
	HAIR_TOOL_ADDROOT_INTERPOLATE_STRENGTH,

	//////////////////////////////////////////////////////////////////////////

	HAIR_TOOL_ADDROOT_PEN_NONE = 0,
	HAIR_TOOL_ADDROOT_PEN_RADIUS,
	HAIR_TOOL_ADDROOT_PEN_LENGTH,
	HAIR_TOOL_ADDROOT_PEN_COUNT,

	HAIR_TOOL_ADDROOT_DUMMY
};

#endif // TOOLHAIRADDROOT_H__
