#ifndef TOOLEDGECUT_H__
#define TOOLEDGECUT_H__

enum
{
	MDATA_EDGECUT_SUBDIV				= 2133,
	MDATA_EDGECUT_OFFSET				= 2166,
	MDATA_EDGECUT_SCALE					= 2165,
	MDATA_EDGECUT_CREATENGONS 	= 2167,
	MDATA_EDGECUT_NGONMODE			= 2168,
		MDATA_EDGECUT_NGONMODE_NONE	= 0,
		MDATA_EDGECUT_NGONMODE_ALL	= 1,
		MDATA_EDGECUT_NGONMODE_CORNER	= 2,

};

#endif // TOOLEDGECUT_H__
