#ifndef TOOLARRAY_H__
#define TOOLARRAY_H__

enum
{
	MDATA_ARRAY_XCNT													= 2046, // LONG
	MDATA_ARRAY_YCNT													= 2047, // LONG
	MDATA_ARRAY_ZCNT													= 2048, // LONG
	MDATA_ARRAY_HOLES													= 2049, // REAL
	MDATA_ARRAY_OFFSET												= 2050, // VECTOR
	MDATA_ARRAY_LOCALMOVE											= 2051, // VECTOR
	MDATA_ARRAY_LOCALSCALE										= 2052, // VECTOR
	MDATA_ARRAY_LOCALROTATE										= 2053, // VECTOR
	MDATA_ARRAY_KEEPFORM											= 2054, // BOOL

	MDATA_ARRAY_
};

#endif // TOOLARRAY_H__
