#ifndef TOOLDOODLE_H__
#define TOOLDOODLE_H__

enum
{
	MDATA_DOODLE_COLOR								= 1100, //COLOR
	MDATA_DOODLE_SIZE								  = 1101, //REAL
	MDATA_DOODLE_OPACITY              = 1102, //REAL
	MDATA_DOODLE_HARDNESS							=	1103, //REAL
	MDATA_DOODLE_SPACING							=	1104, //REAL
	MDATA_DOODLE_SIPRESSURE           = 1105,	//BOOL
	MDATA_DOODLE_OPPRESSURE           = 1106,	//BOOL
	MDATA_DOODLE_HAPRESSURE           = 1107,	//BOOL
	MDATA_DOODLE_AUTOFRAME						=	1108, //BOOL
	MDATA_DOODLE_
};

#endif // TOOLDOODLE_H__
