#ifndef _O_MMD_MESH_ROOT_H_
#define _O_MMD_MESH_ROOT_H_
enum
{
	MESH_ROOT_GRP = 1000,
	MESH_DISPLAY_TYPE,

	MESH_DISPLAY_TYPE_ON = 0,
	MESH_DISPLAY_TYPE_OFF,
	MESH_DISPLAY_TYPE_ON_WIRE,
	MESH_DISPLAY_TYPE_QUICK,
	MESH_DISPLAY_TYPE_QUICK_WIRE,
	MESH_DISPLAY_TYPE_HIDDENLINE,
	MESH_DISPLAY_TYPE_WIRE,
};
#endif //_O_MMD_MESH_ROOT_H_
