#ifndef STACKALLOC_H__
#define STACKALLOC_H__

// include api base first to disable alloca redefinition
#include "maxon/apibase.h"
#undef alloca
#if defined(MAXON_COMPILER_CLANG) || defined(MAXON_COMPILER_GCC)
	#define alloca(...) __builtin_alloca(__VA_ARGS__)
#elif defined(MAXON_COMPILER_MSVC)
	#define alloca(...) _alloca(__VA_ARGS__)
#endif

#include "maxon/defaultallocator.h"
#include "maxon/threadservices.h"

#ifdef MAXON_COMPILER_MSVC
	#include <intrin.h>
#endif

#if defined(MAXON_TARGET_MACOS) || defined(MAXON_TARGET_LINUX) || defined(MAXON_TARGET_IOS)
	#ifdef MAXON_TARGET_CPU_X86
		#ifdef MAXON_TARGET_64BIT
			#define	PRIVATE_MAXON_GetCurrentStackPointer(spp) { asm ("movq	%%rsp, %0\t\n" : "=r" (*spp) : : "cc"); }
		#else
			#define	PRIVATE_MAXON_GetCurrentStackPointer(spp) { asm ("movl	%%esp, %0\t\n" : "=r" (*spp) : : "cc"); }
		#endif
	#endif
#endif

namespace maxon
{

static MAXON_ATTRIBUTE_NO_INLINE inline void* GetStackPointer()
{
#if defined(MAXON_COMPILER_CLANG) || defined(MAXON_COMPILER_GCC)
	return __builtin_frame_address(0);
#else
	#ifdef MAXON_TARGET_WINDOWS
		return (void*)(UInt(_AddressOfReturnAddress()) + sizeof(void*));
	#elif defined(PRIVATE_MAXON_GetCurrentStackPointer)
		Int	sp;

		PRIVATE_MAXON_GetCurrentStackPointer(&sp);
		sp += 0x10;	// assume this was not inlined (debug)

		return (void*) sp;
	#else
		return nullptr;
	#endif
#endif
}

static MAXON_ATTRIBUTE_NO_INLINE inline void* GetProgramCounter()
{
#ifdef MAXON_COMPILER_MSVC
	return _ReturnAddress();
#else
	return __builtin_return_address(0);
#endif
}

static MAXON_ATTRIBUTE_NO_INLINE inline void* GetFramePointer()
{
	// It is intended to get the callers stack frame, therefore disable the warning.
#if defined(MAXON_COMPILER_CLANG) || defined(MAXON_COMPILER_GCC)
	MAXON_WARNING_PUSH
	#ifdef MAXON_COMPILER_CLANG
		_Pragma("clang diagnostic ignored \"-Wframe-address\"") 
	#endif
	return __builtin_frame_address(1);
	MAXON_WARNING_POP
#else
	return nullptr;	// assume no frame generated by compiler
#endif
}

class StackAllocUtilities
{
public:
	template <typename T> static Bool StackHasEnoughSpace(T size)
	{
		return (size < 8192 && maxon::UInt(maxon::GetStackPointer()) + 16384 > maxon::UInt(maxon::ThreadServices::GetStackEnd()));
	}
};

#define StackAlloc(onStack, cnt, TYPE) (StackAllocUtilities::StackHasEnoughSpace(cnt * sizeof(TYPE)) ? (onStack = true, (TYPE*) alloca(cnt * sizeof(TYPE))) : (onStack = false, NewMem(TYPE, cnt)))
#define StackFree(ptr, onStack)	if (onStack == false) DeleteMem(ptr)

}

#endif // STACKALLOC_H__
