#ifndef _DELTA_MUSH_BASE_H__
#define _DELTA_MUSH_BASE_H__

enum {
    ID_DELTAMUSH_BASE_WEIGHT = 1000,
    ID_DELTAMUSH_BASE_SMOOTHVIEW,
    ID_DELTAMUSH_BASE_PIN_CORNER,
    ID_DELTAMUSH_BASE_GROUP_SEPARATOR,
    ID_DELTAMUSH_BASE_SMOOTHTYPE,
    ID_DELTAMUSH_BASE_SMOOTHTYPE_FIX,
    ID_DELTAMUSH_BASE_SMOOTHTYPE_PROPORTIONAL,
    ID_DELTAMUSH_BASE_SMOOTH_ITERATION,
    ID_DELTAMUSH_BASE_INITIAL,
    ID_DELTAMUSH_BASE_RESTORE,
    ID_DELTAMUSH_BASE_MEM,
    __DELTAMUSH_BASE_DUMMY__
        
};

#endif // _DELTA_MUSH_BASE_H__