#ifndef DESC_FALLOFFENTRY_H__
#define DESC_FALLOFFENTRY_H__

enum
{
	FALLOFFENTRY_MODE_LIGHTEN = 0,	// CYCLE ENTRIES
	FALLOFFENTRY_MODE_DARKEN,
	FALLOFFENTRY_MODE_MULTIPLY,
	FALLOFFENTRY_MODE_AVERAGE,
	FALLOFFENTRY_MODE_ADD,
	FALLOFFENTRY_MODE_SUBTRACT,
	FALLOFFENTRY_MODE_DIFFERENCE,
	FALLOFFENTRY_MODE_NEGATION,
	FALLOFFENTRY_MODE_SCREEN,
	FALLOFFENTRY_MODE_EXCLUSION,
	FALLOFFENTRY_MODE_OVERLAY,
	FALLOFFENTRY_MODE_SOFTLIGHT,
	FALLOFFENTRY_MODE_HARDLIGHT,
	FALLOFFENTRY_MODE_COLORDODGE,
	FALLOFFENTRY_MODE_COLORBURN,
	FALLOFFENTRY_MODE_LINEARDODGE,
	FALLOFFENTRY_MODE_LINEARBURN,
	FALLOFFENTRY_MODE_LINEARLIGHT,
	FALLOFFENTRY_MODE_VIVIDLIGHT,
	FALLOFFENTRY_MODE_PINLIGHT,
	FALLOFFENTRY_MODE_HARDMIX,
	FALLOFFENTRY_MODE_REFLECT,
	FALLOFFENTRY_MODE_GLOW,
	FALLOFFENTRY_MODE_PHOENIX,
	FALLOFFENTRY_MODE_LEVR,
	FALLOFFENTRY_MODE_COLOR,
	FALLOFFENTRY_MODE_COLOR_INV,
	FALLOFFENTRY_MODE_NORMAL,
	FALLOFFENTRY_MODE_SEPARATOR			= -1,

	FALLOFFENTRY_COLORMODE_PASS			= 0,
	FALLOFFENTRY_COLORMODE_COLOR		= 1,
	FALLOFFENTRY_COLORMODE_GRADIENT	= 2,

	ID_FALLOFFENTRY_GROUP	 = 900,		// GROUP

	FALLOFFENTRY_ENABLED	 = 1000,	// BOOL
	FALLOFFENTRY_SELECTED	 = 1001,	// BOOL
	FALLOFFENTRY_LINK			 = 1002,	// BASELINK
	FALLOFFENTRY_STRENGTH	 = 1003,	// FLOAT
	FALLOFFENTRY_MODE			 = 1004,	// INT CYCLE
	FALLOFFENTRY_COLORMODE = 1005,	// INT CYCLE
	FALLOFFENTRY_COLOR		 = 1006,	// COLOR (Vector)
	FALLOFFENTRY_GRADIENT	 = 1007		// GRADIENT
};
#endif														// DESC_FALLOFFENTRY_H__
