#ifndef DESC_FIELDENTRY_H__
#define DESC_FIELDENTRY_H__

enum
{
	FIELDENTRY_MODE_LIGHTEN = 0,	// CYCLE ENTRIES
	FIELDENTRY_MODE_DARKEN,
	FIELDENTRY_MODE_MULTIPLY,
	FIELDENTRY_MODE_AVERAGE,
	FIELDENTRY_MODE_ADD,
	FIELDENTRY_MODE_SUBTRACT,
	FIELDENTRY_MODE_DIFFERENCE,
	FIELDENTRY_MODE_NEGATION,
	FIELDENTRY_MODE_SCREEN,
	FIELDENTRY_MODE_EXCLUSION,
	FIELDENTRY_MODE_OVERLAY,
	FIELDENTRY_MODE_SOFTLIGHT,
	FIELDENTRY_MODE_HARDLIGHT,
	FIELDENTRY_MODE_COLORDODGE,
	FIELDENTRY_MODE_COLORBURN,
	FIELDENTRY_MODE_LINEARDODGE,
	FIELDENTRY_MODE_LINEARBURN,
	FIELDENTRY_MODE_LINEARLIGHT,
	FIELDENTRY_MODE_VIVIDLIGHT,
	FIELDENTRY_MODE_PINLIGHT,
	FIELDENTRY_MODE_HARDMIX,
	FIELDENTRY_MODE_REFLECT,
	FIELDENTRY_MODE_GLOW,
	FIELDENTRY_MODE_PHOENIX,
	FIELDENTRY_MODE_LEVR,
	FIELDENTRY_MODE_COLOR,
	FIELDENTRY_MODE_COLOR_INV,
	FIELDENTRY_MODE_NORMAL,
	FIELDENTRY_MODE_SEPARATOR			= -1,

	FIELDENTRY_COLORMODE_PASS			= 0,
	FIELDENTRY_COLORMODE_COLOR		= 1,
	FIELDENTRY_COLORMODE_GRADIENT	= 2,

	ID_FIELDENTRY_GROUP	 = 900,		// GROUP

	FIELDENTRY_ENABLED	 = 1000,	// BOOL
	FIELDENTRY_SELECTED	 = 1001,	// BOOL
	FIELDENTRY_LINK			 = 1002,	// BASELINK
	FIELDENTRY_STRENGTH	 = 1003,	// FLOAT
	FIELDENTRY_MODE			 = 1004,	// INT CYCLE
	FIELDENTRY_COLORMODE = 1005,	// INT CYCLE
	FIELDENTRY_COLOR		 = 1006,	// COLOR (Vector)
	FIELDENTRY_GRADIENT	 = 1007		// GRADIENT
};
#endif													// DESC_FIELDENTRY_H__
