#ifndef DMLINE_H__
#define DMLINE_H__

enum
{
	SCULPT_DRAWMODE_LINE_TYPE = 20000,
		SCULPT_DRAWMODE_LINE_TYPE_LINEAR,
		SCULPT_DRAWMODE_LINE_TYPE_CUBIC,
		SCULPT_DRAWMODE_LINE_TYPE_AKIMA,
		SCULPT_DRAWMODE_LINE_TYPE_BEZIER,
};

#endif // DMLINE_H__
