#ifndef FCYLINDER_H__
#define FCYLINDER_H__

enum
{
	// Falloff controls
	FIELD_CYLINDER_SIZE_DEPRECATED = 1000,	// Float
	FIELD_CYLINDER_SLICE_DEPRECATED = 1001,	// Float
	FIELD_CYLINDER_DIRECTION = 1005,	// Int Cycle
	FIELD_CYLINDER_HEIGHT = 1006,	// Float
	FIELD_CYLINDER_RADIUS = 1007,	// Float
	FIELD_CYLINDER_CLIP = 1008,	// Bool

	FIELD_CYLINDER_DIRECTION_XP = 0,
	FIELD_CYLINDER_DIRECTION_XN = 1,
	FIELD_CYLINDER_DIRECTION_YP = 2,
	FIELD_CYLINDER_DIRECTION_YN = 3,
	FIELD_CYLINDER_DIRECTION_ZP = 4,
	FIELD_CYLINDER_DIRECTION_ZN = 5
};
#endif	// FCYLINDER_H__
