#ifndef FDWGOBJECTVALUES_H__
#define FDWGOBJECTVALUES_H__

enum
{
	BASECURVE_OUTPUT_LINEAR				= 0,
	BASECURVE_OUTPUT_BSPLINE			= 1,
	BASECURVE_OUTPUT_BEZIER				= 2,
	BASECURVE_OUTPUT_CONVERT            = 3,

	BASESURFACE_OUTPUT_LINEAR			= 0,
	BASESURFACE_OUTPUT_BSPLINE			= 1,
	BASESURFACE_OUTPUT_HYPERNURBS		= 2,
	BASESURFACE_OUTPUT_CONVERT			= 3
};

#endif // FDWGOBJECTVALUES_H__
