#ifndef FLINEAR_H__
#define FLINEAR_H__

enum
{
	LINEAR_SIZE = 1000,	// Float
	LINEAR_CLIP = 1001,	// Bool
	LINEAR_DIRECTION = 1005,	// Int Cycle

	LINEAR_DIRECTION_XP = 0,
	LINEAR_DIRECTION_XN = 1,
	LINEAR_DIRECTION_YP = 2,
	LINEAR_DIRECTION_YN = 3,
	LINEAR_DIRECTION_ZP = 4,
	LINEAR_DIRECTION_ZN = 5
};
#endif	// FLINEAR_H__
