#ifndef FLVOLUMEOBJECT_H__
#define FLVOLUMEOBJECT_H__

enum
{
	// Field Layer controls
	FIELDLAYER_VOLUME_OBJECT							 		= 1000,	// Baselink
	FIELDLAYER_VOLUME_SAMPLEMODE							= 1001,	// Int Cycle
		FIELDLAYER_VOLUME_SAMPLEMODE_NEAREST		= 0,
		FIELDLAYER_VOLUME_SAMPLEMODE_LINEAR 		= 1,
		FIELDLAYER_VOLUME_SAMPLEMODE_QUADRATIC	= 2,
	FIELDLAYER_VOLUME_CLIP										= 1002 // Bool
};
#endif // FLVOLUMEOBJECT_H__
