#ifndef FRANDOM_H__
#define FRANDOM_H__

enum
{
	FIELD_RANDOM_VIEWPLANES_GROUP					= 900,	// Group

	FIELD_RANDOM_MODE											=	1000,	// Int Cycle
		FIELD_RANDOM_MODE_RANDOM							= 0,
		FIELD_RANDOM_MODE_SORTED							= 100,
		FIELD_RANDOM_MODE_NOISE								= 101,
	FIELD_RANDOM_SEED											= 1001,	// Float
	FIELD_RANDOM_SCALE										= 1003,	// Vector
	FIELD_RANDOM_ANIMATIONSPEED						= 1004,	// Time
	FIELD_RANDOM_ANIMATIONPERIOD					= 1005,	// Time
	FIELD_RANDOM_SPACE										= 1006,	// Int Cycle
		FIELD_RANDOM_SPACE_GLOBAL							= 0,
		FIELD_RANDOM_SPACE_OBJECT							= 1,
		FIELD_RANDOM_SPACE_NONE								= 2,
	FIELD_RANDOM_VIEWPLANES_X							= 1008,	// Bool
	FIELD_RANDOM_VIEWPLANES_Y							= 1009,	// Bool
	FIELD_RANDOM_VIEWPLANES_Z							= 1010,	// Bool
	FIELD_RANDOM_VIEWPLANES								= 1011,	// Bool
	FIELD_RANDOM_VIEWPLANES_DENSITY				= 1012,	// Bool
	FIELD_RANDOM_COLORSHIFT								= 1013,	// Float
	FIELD_RANDOM_SCALE_LOCAL							= 1014,	// Vector
	FIELD_RANDOM_VIEWPLANES_SIZES					= 1015,	// Vector
	FIELD_RANDOM_NOISE_MODE								= 1016,	// Int Cycle
		FIELD_RANDOM_NOISE_MODE_NONE					= 0,
		FIELD_RANDOM_NOISE_MODE_BOX						= 1,
		FIELD_RANDOM_NOISE_MODE_BLISTEREDTURBULENCE	= 2,
		FIELD_RANDOM_NOISE_MODE_BUYA					= 3,
		FIELD_RANDOM_NOISE_MODE_CELL					= 4,
		FIELD_RANDOM_NOISE_MODE_CRANAL				= 5,
		FIELD_RANDOM_NOISE_MODE_DENTS					= 6,
		FIELD_RANDOM_NOISE_MODE_DISPLACEDTURBULENCE	= 7,
		FIELD_RANDOM_NOISE_MODE_ELECTRIC			= 8,
		FIELD_RANDOM_NOISE_MODE_FBM						= 9,
		FIELD_RANDOM_NOISE_MODE_GASEOUS				= 10,
		FIELD_RANDOM_NOISE_MODE_HAMA					= 11,
		FIELD_RANDOM_NOISE_MODE_LUKA					= 12,
		FIELD_RANDOM_NOISE_MODE_MODNOISE			= 13,
		FIELD_RANDOM_NOISE_MODE_NAKI					= 14,
		FIELD_RANDOM_NOISE_MODE_NUTOUS				= 15,
		FIELD_RANDOM_NOISE_MODE_OBER					= 16,
		FIELD_RANDOM_NOISE_MODE_PEZO					= 17,
		FIELD_RANDOM_NOISE_MODE_POXO					= 18,
		FIELD_RANDOM_NOISE_MODE_SEMA					= 19,
		FIELD_RANDOM_NOISE_MODE_STUPL					= 20,
		FIELD_RANDOM_NOISE_MODE_TURBULENCE		= 21,
		FIELD_RANDOM_NOISE_MODE_VLNOISE				= 22,
		FIELD_RANDOM_NOISE_MODE_WAVYTURBULENCE= 23,
		FIELD_RANDOM_NOISE_MODE_CELLVORONOI		= 24,
		FIELD_RANDOM_NOISE_MODE_DISPLACEDVORONOI	= 25,
		FIELD_RANDOM_NOISE_MODE_VORONOI1			= 26,
		FIELD_RANDOM_NOISE_MODE_VORONOI2			= 27,
		FIELD_RANDOM_NOISE_MODE_VORONOI3			= 28,
		FIELD_RANDOM_NOISE_MODE_ZADA					= 29,
		FIELD_RANDOM_NOISE_MODE_PERLIN				= 30,
		FIELD_RANDOM_NOISE_MODE_RIDGEDMULTIFRACTAL	= 31,
	FIELD_RANDOM_NOISE_GROUP							= 1017,	// Group
	FIELD_RANDOM_COLORALPHA								= 1018,	// Int Cycle
		FIELD_RANDOM_COLORALPHA_NONE					= 0,
		FIELD_RANDOM_COLORALPHA_STRENGTH			= 1,
	FIELD_RANDOM_INDEXED									= 1019, // Bool
	FIELD_RANDOM_INDEXSEED								= 1020	// Int
};
#endif	// FRANDOM_H__
