#ifndef FTIME_H__
#define FTIME_H__

enum
{
	TIMEFIELD_SHAPE					 = 1000,	// Int Cycle
	TIMEFIELD_SHAPE_NONE		 = 0,
	TIMEFIELD_SHAPE_SINE		 = 1,
	TIMEFIELD_SHAPE_TRIANGLE = 2,
	TIMEFIELD_SHAPE_SAWTOOTH = 3,
	TIMEFIELD_SHAPE_SQUARE	 = 4,
	TIMEFIELD_SPEED					 = 1001,	// Float
	TIMEFIELD_BIAS					 = 1002		// Float
};
#endif // FTIME_H__
