#ifndef FUSDEXPORTER_H__
#define FUSDEXPORTER_H__

enum
{
	USDEXPORTER_GROUP						= 999,

	USDEXPORTER_GRP_GENERAL,
	USDEXPORTER_FILEFORMAT,
		USDEXPORTER_FILEFORMAT_USDA,
		USDEXPORTER_FILEFORMAT_USDC,
	USDEXPORTER_ZIP,
	USDEXPORTER_CAMERAS,
	USDEXPORTER_LIGHTS,

	USDEXPORTER_GRP_GEOMETRY,
	USDEXPORTER_GEOMETRY,
	USDEXPORTER_NORMALS,
	USDEXPORTER_UV,
	USDEXPORTER_DISPLAYCOLOR,
	USDEXPORTER_VERTEXCOLORS
};

#endif // FUSDEXPORTER_H__
