#ifndef FUSDIMPORTER_H__
#define FUSDIMPORTER_H__

enum
{
	USDIMPORTER_GROUP						= 999,

	USDIMPORTER_GRP_GENERAL,
	USDIMPORTER_KEEPBRIDGEOPEN,
	USDIMPORTER_CAMERAS,
	USDIMPORTER_LIGHTS,
	
	USDIMPORTER_GRP_GEOMETRY,
	USDIMPORTER_GEOMETRY,
	USDIMPORTER_NORMALS,
		USDIMPORTER_NORMALS_NONE,
		USDIMPORTER_NORMALS_VERTEX,
		USDIMPORTER_NORMALS_PHONG,
	USDIMPORTER_PHONG_ANGLE,
	USDIMPORTER_UV,
	USDIMPORTER_DISPLAYCOLOR
};

#endif // FUSDIMPORTER_H__
