#ifndef GVDYNINTERACTION_H__
#define GVDYNINTERACTION_H__

#include "gvbase.h"

enum
{
	DYNAMICS_INTERACTION_NODE_OBJECT = 10001,

	DYNAMICS_INTERACTION_NODE_INPUT_ON = 10100,
	DYNAMICS_INTERACTION_NODE_INPUT_INDEX = 10101,
	DYNAMICS_INTERACTION_NODE_INPUT_OBJECT = 10111,
	DYNAMICS_INTERACTION_NODE_INPUT_BROKEN = 10121,

	DYNAMICS_INTERACTION_NODE_OUTPUT_COUNT = 10201,
	DYNAMICS_INTERACTION_NODE_OUTPUT_OBJECT = 10202,
	DYNAMICS_INTERACTION_NODE_OUTPUT_OBJECT_A = 10211,
	DYNAMICS_INTERACTION_NODE_OUTPUT_OBJECT_B = 10212,
	DYNAMICS_INTERACTION_NODE_OUTPUT_TAG_A = 10213,
	DYNAMICS_INTERACTION_NODE_OUTPUT_TAG_B = 10214,
	DYNAMICS_INTERACTION_NODE_OUTPUT_INDEX_A = 10215,
	DYNAMICS_INTERACTION_NODE_OUTPUT_INDEX_B = 10216,
	DYNAMICS_INTERACTION_NODE_OUTPUT_BROKEN = 10221,
};

#endif // GVDYNINTERACTION_H__
