#ifndef GVFORMULA_H__
#define GVFORMULA_H__

#include "gvbase.h"

enum
{
	GV_FORMULA_STRING					= 1000,
	GV_FORMULA_USE_PORTNAMES,
	GV_FORMULA_ANGLE,
			GV_FORMULA_ANGLE_DEGREE = 0,
			GV_FORMULA_ANGLE_RAD,

	GV_FORMULA_INPUT		= 2000,
	GV_FORMULA_OUTPUT		= 3000,

	GV_FORMULA_
};

#endif // GVFORMULA_H__
