#ifndef GVHAIR_SELECTION_H__
#define GVHAIR_SELECTION_H__

enum
{
	GV_HAIR_SELECTION_MODE = 1900,

		GV_HAIR_SELECTION_MODE_ASIS = 0,
		GV_HAIR_SELECTION_MODE_POINTS = 1,
		GV_HAIR_SELECTION_MODE_GUIDES = 2,

	GV_HAIR_SELECTION_INPUT_TAG				= 2000,
	GV_HAIR_SELECTION_OPERATOR_ON,

	GV_HAIR_SELECTION_OUTPUT					= 3000,
	GV_HAIR_SELECTION_OUTPUT_COUNT,

	GV_HAIR_SELECTION_
};

#endif // GVHAIR_SELECTION_H__
