#ifndef GVHAIR_POINT_H__
#define GVHAIR_POINT_H__

#include "gvbase.h"

enum
{
	GV_HAIR_POINT_MODE									= 1900,
		GV_HAIR_POINT_MODE_GUIDE					= 2,
		GV_HAIR_POINT_MODE_DYNAMIC_GUIDE	= 3,
		GV_HAIR_POINT_MODE_HAIR						= 4,
	GV_HAIR_POINT_OBJECT								= 1901,

	GV_HAIR_POINT_INPUT_OBJECT	= 2000,
	GV_HAIR_POINT_INPUT_SEGMENT	= 2001,
	GV_HAIR_POINT_INPUT_GUIDE		= 2003,
	GV_HAIR_POINT_INPUT_T				= 2004,
	GV_HAIR_POINT_INPUT_POINT		= 2005,
	GV_HAIR_POINT_INPUT_ON			= 2006,

	GV_HAIR_POINT_INPUT_SET_POS = 2100,
	GV_HAIR_POINT_INPUT_SET_DYN_POS = 2101,
	GV_HAIR_POINT_INPUT_SET_VELOCITY	= 2102,
	GV_HAIR_POINT_INPUT_SET_MASS	= 2103,
	GV_HAIR_POINT_INPUT_ADD_FORCE	= 2104,

	GV_HAIR_POINT_POINT_VEC			= 3001,
	GV_HAIR_POINT_POINT_TANGENT	= 3002,
	GV_HAIR_POINT_POINT_VELOCITY = 3003,
	GV_HAIR_POINT_POINT_MASS		= 3004,
	GV_HAIR_POINT_POINT_FORCE		= 3005,
	GV_HAIR_POINT_POINT_MATRIX	= 3006,

	GV_HAIR_POINT
};

#endif // GVHAIR_POINT_H__
