#ifndef GVMOGRAPH_WEIGHT_H__
#define GVMOGRAPH_WEIGHT_H__

enum
{
	GV_MG_WEIGHT_IOBJECT	= 1000,
	GV_MG_WEIGHT_ISELECT	= 1001,
	GV_MG_WEIGHT_INDEX		= 1002,
	GV_MG_WEIGHT_OSELECT	= 1003
};
#endif // GVMOGRAPH_SELECTION_H__
