#ifndef HP_VOLUMEPOSITION_H__
#define HP_VOLUMEPOSITION_H__

#include "gvbase.h"

enum
{
	HP_VOLUMEPOS_VERSION				= 1000,
	HP_VOLUMEPOS_TYPE						= 1001,
	HP_VOLUMEPOS_SEED						= 1002,
	HP_VOLUMEPOS_SELECTION			= 1003,
	HP_VOLUMEPOS_OBJECT					= 1004,
	HP_VOLUMEPOS_DEPTH					= 1005,
	HP_VOLUMEPOS_PARTICLE				= 2000,
	HP_VOLUMEPOS_ATIME					= 2001,
	HP_VOLUMEPOS_OUT_POSITION		= 3000,
	HP_VOLUMEPOS_OUT_NORMAL			= 3001,
	HP_VOLUMEPOS_OUT_ALIGNMENT	= 3002,

	HP_VOLUMEPOS_TYPE_INSIDE	=	0,
	HP_VOLUMEPOS_TYPE_OUTSIDE	=	1
};




#endif // HP_VOLUMEPOSITION_H__
