#ifndef IN_SELFDYNAMIC_H__
#define IN_SELFDYNAMIC_H__

#include "gvbase.h"

enum
{
	SELF_VERSION = 1000,
	SELF_TITLE   = 1001,
	SELF_LINK    = 1002,

//Ports
	OUT_SELF_PARTICLE      = 3000,
	OUT_SELF_PARTICLECOUNT = 3001,
	OUT_SELF_INDEX				 = 3002
};


#endif // IN_SELFDYNAMIC_H__
