#ifndef MRENDERMAN_H__
#define MRENDERMAN_H__

enum
{
	RIBMATERIAL_PAGE_SHADERPARAMS   			= 200000,

	GROUP_SURFACE								= 10000,
	RIBMATERIAL_SHADERFILE						= 10001,	// Filename
	RIBMATERIAL_SHADERNAME						= 10002,	// String
	RIBMATERIAL_SHADERTYPE						= 10010,	// LONG
		RIBMATERIAL_SHADERTYPE_UNKNOWN			= 0,
		RIBMATERIAL_SHADERTYPE_SURFACE			= 1,
		RIBMATERIAL_SHADERTYPE_DISPLACEMENT		= 2,
		RIBMATERIAL_SHADERTYPE_VOLUME			= 3,
		RIBMATERIAL_SHADERTYPE_LIGHTSOURCE		= 4,
		RIBMATERIAL_SHADERTYPE_IMAGER			= 5,

	RIBMATERIAL_DISPLACEMENT_BOUND				= 10012,	// Real
	RIBMATERIAL_DISPLACEMENT_SPACE				= 10013,	// String

	RIBMATERIAL_SURFACE_OPACITY					= 10003,
	RIBMATERIAL_SURFACE_COLOR					= 10004,


	ID_SHADERPARAMS								= 100000,
	RIBMATERIAL_NPARAMS							= 100001,	// LONG
	RIBMATERIAL_PARAMS							= 101000,
	RIBMATERIAL_PARAMS_OFFSET					= 10,
	RIBMATERIAL_PARAMS_NAME						= 0,		// String
	RIBMATERIAL_PARAMS_TYPE						= 1,		// LONG
		RIBMATERIAL_PARAMS_TYPE_FLOAT			= 0,
		RIBMATERIAL_PARAMS_TYPE_COLOR			= 1,
		RIBMATERIAL_PARAMS_TYPE_POINT			= 2,
		RIBMATERIAL_PARAMS_TYPE_VECTOR			= 3,
		RIBMATERIAL_PARAMS_TYPE_NORMAL			= 4,
		RIBMATERIAL_PARAMS_TYPE_MATRIX			= 5,
		RIBMATERIAL_PARAMS_TYPE_STRING			= 6,
	RIBMATERIAL_PARAMS_STORAGECLASS				= 2,		// LONG
		RIBMATERIAL_PARAMS_STORAGECLASS_UNIFORM = 0,
		RIBMATERIAL_PARAMS_STORAGECLASS_VARYING = 1,
	RIBMATERIAL_PARAMS_ISOUTPUT					= 3,		// Bool
	RIBMATERIAL_PARAMS_DEFAULT					= 4,		// depends
	RIBMATERIAL_PARAMS_VALUE					= 5,		// depends


	RIBMATERIAL_RELOAD							= 10011,

//	ID_SHADERPARAMS								= 100000,
//	RIBMATERIAL_SHADERPARAMS					= 100100,

	GROUP_SURFACECOORDINATES				= 10100,
	RIBMATERIAL_SSPACE						= 10101,
		RIBMATERIAL_SSPACE_TEXTURE  		= 0,
		RIBMATERIAL_SSPACE_SPECIFY			= 1,
	RIBMATERIAL_SPOSITION			= 10102,
	RIBMATERIAL_SSIZE    			= 10103,
	RIBMATERIAL_SROTATION			= 10104,

	GROUP_DISPLACEMENT				= 20000,
	RIBMATERIAL_DISPLACEMENTFILE	= 20001,
	RIBMATERIAL_DISPLACEMENTNAME	= 20002,
	RIBMATERIAL_DISPLACEMENTBOUND	= 20003,

	GROUP_DISPLACEMENTCOORDINATES	= 20100,
	RIBMATERIAL_DSPACE				= 20101,
		RIBMATERIAL_DSPACE_TEXTURE  = 0,
		RIBMATERIAL_DSPACE_SPECIFY	= 1,
	RIBMATERIAL_DPOSITION			= 20102,
	RIBMATERIAL_DSIZE    			= 20103,
	RIBMATERIAL_DROTATION			= 20104
};

#endif // MRENDERMAN_H__
