#ifndef NEUTRONSCENEHOOK_H__
#define NEUTRONSCENEHOOK_H__

enum
{
	NEUTRON_VIEWPORT_MODE = 10000,
	NEUTRON_VIEWPORT_MODE_NONE = 0,
	NEUTRON_VIEWPORT_MODE_NEUTRON = 1,
	NEUTRON_VIEWPORT_MODE_LEGACY = 2,

	NEUTRON_GROUP_VIEWPORT = 11000,

	NEUTRONSCENEHOOK_DUMMY
};

#endif // NEUTRONSCENEHOOK_H__
