#ifndef OBASE_H__
#define OBASE_H__

enum
{
	// object properties
	ID_BASEOBJECT_VISIBILITY_EDITOR   = 901,	// modes for visible checks in the object manager
	ID_BASEOBJECT_VISIBILITY_RENDER   = 902,	// modes for visible checks in the object manager
		OBJECT_ON    = 0,
		OBJECT_OFF   = 1,
		OBJECT_UNDEF = 2,
	ID_BASEOBJECT_REL_POSITION        = 903,
	ID_BASEOBJECT_REL_ROTATION        = 904,
	ID_BASEOBJECT_REL_SCALE           = 905,
	ID_BASEOBJECT_GENERATOR_FLAG			= 906,
	ID_BASEOBJECT_USECOLOR						= 907,
		ID_BASEOBJECT_USECOLOR_OFF				= 0,
		ID_BASEOBJECT_USECOLOR_AUTOMATIC	= 1,
		ID_BASEOBJECT_USECOLOR_ALWAYS			= 2,
		ID_BASEOBJECT_USECOLOR_LAYER			= 3,
	ID_BASEOBJECT_COLOR								= 908,
	ID_BASEOBJECT_XRAY								= 909,
	ID_BASEOBJECT_GLOBAL_POSITION     = 910,
	ID_BASEOBJECT_GLOBAL_ROTATION     = 911,
	ID_BASEOBJECT_SHADEDWIRECOLOR			= 912,
	ID_BASEOBJECT_SHADEDWIRECOLORMODE = 913,
		ID_BASEOBJECT_SHADEDWIRECOLORMODE_OFF			 = 0,
		ID_BASEOBJECT_SHADEDWIRECOLORMODE_AUTO		 = 1,
		ID_BASEOBJECT_SHADEDWIRECOLORMODE_ALWAYS	 = 2,

	ID_BASEOBJECT_FROZEN_POSITION = 917,
	ID_BASEOBJECT_FROZEN_ROTATION = 918,
	ID_BASEOBJECT_FROZEN_SCALE = 919,
	ID_BASEOBJECT_FREEZE = 920,
	ID_BASEOBJECT_FROZEN_RESET = 921,
	ID_BASEOBJECT_FREEZE_P = 922,
	ID_BASEOBJECT_FREEZE_R = 923,
	ID_BASEOBJECT_FREEZE_S = 924,
	ID_BASEOBJECT_ABS_POSITION = 925,
	ID_BASEOBJECT_ABS_ROTATION = 926,
	ID_BASEOBJECT_ABS_SCALE = 927,
	ID_BASEOBJECT_ROTATION_ORDER = 928,
		ID_BASEOBJECT_ROTATION_ORDER_YXZ	=	0,
		ID_BASEOBJECT_ROTATION_ORDER_YZX	=	1,
		ID_BASEOBJECT_ROTATION_ORDER_ZYX	=	2,
		ID_BASEOBJECT_ROTATION_ORDER_ZXY	=	3,
		ID_BASEOBJECT_ROTATION_ORDER_XZY	=	4,
		ID_BASEOBJECT_ROTATION_ORDER_XYZ	=	5,
		ID_BASEOBJECT_ROTATION_ORDER_HPB  = 6,

	ID_BASEOBJECT_GROUP1							= 800,		// for group
	ID_BASEOBJECT_GROUPVIS						= 801,
	ID_OBJECTPROPERTIES								= 802,
	ID_TAGLIST												= 804,
	ID_BASEOBJECT_FROZEN_COORDS				= 805,
	ID_BASEOBJECT_QUATERNION_ROTATION = 806,

	ID_BASEOBJECT_QUATERNION_ROTATION_INTERPOLATION = 929,
		//////////////////////////////////////////////////////////////////////////

	ID_BASEOBJECT_DUMMY
};

#endif // OBASE_H__
