#ifndef OBASEEFFECTOR_H__
#define OBASEEFFECTOR_H__

enum
{
	// Groups
	ID_MG_BASEEFFECTOR_GROUPPARAMETER	= 990,
	ID_MG_BASEEFFECTOR_GROUPEFFECTOR	= 991,

	// Subgroups
	ID_MG_BASEEFFECTOR_GROUPTRANSFORM	= 995,
	ID_MG_BASEEFFECTOR_GROUPCOLOR			= 996,
	ID_MG_BASEEFFECTOR_GROUPOTHER			= 997,
	ID_MG_BASEEFFECTOR_GROUPMINMAX		= 998,

	// Effector controls
	ID_MG_BASEEFFECTOR_STRENGTH		 = 1000,
	ID_MG_BASEEFFECTOR_MAXSTRENGTH = 1001,
	ID_MG_BASEEFFECTOR_MINSTRENGTH = 1002,

	// Parameter controls
	ID_MG_BASEEFFECTOR_POSITION										= 1010,
	ID_MG_BASEEFFECTOR_SCALE											= 1011,
	ID_MG_BASEEFFECTOR_ROTATION										= 1012,
	ID_MG_BASEEFFECTOR_COLOR											= 1013,
	ID_MG_BASEEFFECTOR_COLOR_MODE									= 1014,
		ID_MG_BASEEFFECTOR_COLOR_MODE_OFF							= 0,
		ID_MG_BASEEFFECTOR_COLOR_MODE_COLOR						= 1,
		ID_MG_BASEEFFECTOR_COLOR_MODE_COLORNOALPHA		= 2,
		ID_MG_BASEEFFECTOR_COLOR_MODE_EFFECTOR				= 3,
		ID_MG_BASEEFFECTOR_COLOR_MODE_EFFECTORNOALPHA = 4,
		ID_MG_BASEEFFECTOR_COLOR_MODE_FIELD						= 5,

	ID_MG_BASEEFFECTOR_COLOR_BLEND								= 1015,
		ID_MG_BASEEFFECTOR_COLOR_BLEND_DEFAULT				= 0,
		ID_MG_BASEEFFECTOR_COLOR_BLEND_ADD						= 1,
		ID_MG_BASEEFFECTOR_COLOR_BLEND_SUB						= 2,
		ID_MG_BASEEFFECTOR_COLOR_BLEND_MUL						= 3,
		ID_MG_BASEEFFECTOR_COLOR_BLEND_DIV						= 4,
		ID_MG_BASEEFFECTOR_COLOR_BLEND_NON						= 5,

	ID_MG_BASEEFFECTOR_TRANSFORMMODE							= 1016,
		ID_MG_BASEEFFECTOR_TRANSFORMMODE_RELATIVE			= 0,
		ID_MG_BASEEFFECTOR_TRANSFORMMODE_ABSOLUTE			= 1,
		ID_MG_BASEEFFECTOR_TRANSFORMMODE_REMAP				= 2,

	ID_MG_BASEEFFECTOR_UNIFORMSCALE								= 1017,
	ID_MG_BASEEFFECTOR_USCALE											= 1018,
	ID_MG_BASEEFFECTOR_POSITIVESCALE							= 1019,
	ID_MG_BASEEFFECTOR_COLOR_ALPHA								=	1020,
	ID_MG_BASEEFFECTOR_SELECTION									= 1021,

	ID_MG_BASEEFFECTOR_POSITION_ACTIVE		= 1060,
	ID_MG_BASEEFFECTOR_SCALE_ACTIVE				= 1061,
	ID_MG_BASEEFFECTOR_ROTATE_ACTIVE			= 1062,
	ID_MG_BASEEFFECTOR_WEIGHT							= 1064,
	ID_MG_BASEEFFECTOR_U									= 1065,
	ID_MG_BASEEFFECTOR_V									= 1066,
	ID_MG_BASEEFFECTOR_VISIBILITY					= 1067,
	ID_MG_BASEEFFECTOR_CLONE							= 1068,
	ID_MG_BASEEFFECTOR_TIME								= 1069,
	ID_MG_BASEEFFECTOR_SPACEMODE					= 1070,
		ID_MG_BASEEFFECTOR_SPACEMODE_NODE			= 0,
		ID_MG_BASEEFFECTOR_SPACEMODE_EFFECTOR	= 1,
		ID_MG_BASEEFFECTOR_SPACEMODE_OBJECT		= 2,

	ID_MG_BASEEFFECTOR_OTHERALPHA						= 1071
};
#endif	// OBASEEFFECTOR_H__
