#ifndef OCACOLLISIONDEFORMER_H__
#define OCACOLLISIONDEFORMER_H__

enum
{
	ID_CA_COLLISION_GROUP_MAPS = 3000,
	ID_CA_COLLISION_GROUP_ADVANCED,
	ID_CA_COLLISION_GROUP_COLLIDERS,
	ID_CA_COLLISION_GROUP_INCLUDE,
	ID_CA_COLLISION_GROUP_MAPS_OUTPUT,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_GROUP,
	ID_CA_COLLISION_GROUP_SUBD,

	ID_CA_COLLISION_DEFORMER_OBJECT_COLLIDERS = 1000,
	ID_CA_COLLISION_DEFORMER_OBJECT_DISTANCE,
	ID_CA_COLLISION_DEFORMER_OBJECT_FALLOFF,
	ID_CA_COLLISION_DEFORMER_OBJECT_COLLISION_MAP,
	ID_CA_COLLISION_DEFORMER_OBJECT_DISTANCE_MAP,
	ID_CA_COLLISION_DEFORMER_OBJECT_COLLISION_MAP_INVERT,
	ID_CA_COLLISION_DEFORMER_OBJECT_DISTANCE_MAP_INVERT,
	ID_CA_COLLISION_DEFORMER_OBJECT_RESTORESHAPE,
	ID_CA_COLLISION_DEFORMER_MOTION,
	ID_CA_COLLISION_DEFORMER_OBJECT_COORDS,
	ID_CA_COLLISION_DEFORMER_OBJECT_SAMPLING,
	ID_CA_COLLISION_DEFORMER_OBJECT_RELAX_ITER,
	ID_CA_COLLISION_DEFORMER_OBJECT_SIZE,
	ID_CA_COLLISION_DEFORMER_OBJECT_ITER,
	ID_CA_COLLISION_DEFORMER_OBJECT_STRUCT,
	ID_CA_COLLISION_DEFORMER_OBJECT_FLEX,
	ID_CA_COLLISION_DEFORMER_OBJECT_FALLOFF_STRENGTH,
	ID_CA_COLLISION_DEFORMER_OBJECTS,
	ID_CA_COLLISION_DEFORMER_OBJECT_FALLOFF_MAP,
	ID_CA_COLLISION_DEFORMER_OBJECT_RESTORE_MAP,
	ID_CA_COLLISION_DEFORMER_OBJECT_STRETCH_MAP,
	ID_CA_COLLISION_DEFORMER_OBJECT_STIFF,

	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_ENABLE = 2000,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_CALCULATE,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_COMPRESSED,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_DELETE,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_INFO1,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_INFO2,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_CACHE_LOAD,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_CACHE_SAVE,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_CACHE_LIMIT,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_TEXT_LIMIT,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_UPDATE,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_AUTOTIME,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_START,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_STOP,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_OFFSET,
	ID_CA_COLLISION_DEFORMER_OBJECT_CACHE_TIMESCALE,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_COLLISION_DEFORMER_OBJECT_COORDS_UV = 0,
	ID_CA_COLLISION_DEFORMER_OBJECT_COORDS_LENGTH,
	ID_CA_COLLISION_DEFORMER_OBJECT_COORDS_SURFACE,
	ID_CA_COLLISION_DEFORMER_OBJECT_COORDS_NONE,
	ID_CA_COLLISION_DEFORMER_OBJECT_COORDS_COLLIDER,

	ID_CA_COLLISION_DEFORMER_MOTION_INTERSECT = 0,
	ID_CA_COLLISION_DEFORMER_MOTION_INSIDE,
	ID_CA_COLLISION_DEFORMER_MOTION_OUTSIDE,
	ID_CA_COLLISION_DEFORMER_MOTION_OUTSIDE_FULL,
	ID_CA_COLLISION_DEFORMER_MOTION_INSIDE_STRETCH,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_COLLISION_DEFORMER_OBJECT_DUMMY
};

#endif // OCACOLLISIONDEFORMER_H__
