#ifndef _O_DIRECT_DELTA_MUSH_DEFORMER_H__
#define _O_DIRECT_DELTA_MUSH_DEFORMER_H__



enum {

	DIRECT_DELTAMUSH_DEFORMER_ROTSMOOTH = 1000,
	DIRECT_DELTAMUSH_DEFORMER_TRANSSMOOTH,
	DIRECT_DELTAMUSH_DEFORMER_ITERATION, 
	DIRECT_DELTAMUSH_DEFORMER_BLEND,
	DIRECT_DELTAMUSH_DEFORMER_PRECOMP,

	__DUMMY_ELEMENT__DIRECT_DELTAMUSH_DEFORMER


};

#endif