#ifndef OEREEFFECTOR_H__
#define OEREEFFECTOR_H__

enum
{

	//groups
	MGREEFFECTOR_GROUPEFFECTOR					= 991,

	MGREEFFECTOR_GROUPTRANSFORM					= 992,
	MGREEFFECTOR_GROUPCOLOR							= 993,
	MGREEFFECTOR_GROUPOTHER							= 994,

	MGREEFFECTOR_GROUPPARAMETER					= 995,
	MGREEFFECTOR_GROUPEFFECTORSLIDERS		= 996,

	//------------------------------
	//Effector controls
	MGREEFFECTOR_STRENGTH								= 1000,

	MGREEFFECTOR_POSITION								= 1110,
		MGREEFFECTOR_POSITION_X							= 1200,
		MGREEFFECTOR_POSITION_Y							= 1201,
		MGREEFFECTOR_POSITION_Z							= 1202,
	MGREEFFECTOR_SCALE									= 1111,
		MGREEFFECTOR_SCALE_X								= 1203,
		MGREEFFECTOR_SCALE_Y								= 1204,
		MGREEFFECTOR_SCALE_Z								= 1205,
	MGREEFFECTOR_ROTATION								= 1112,
		MGREEFFECTOR_ROTATION_H							= 1206,
		MGREEFFECTOR_ROTATION_P							= 1207,
		MGREEFFECTOR_ROTATION_B							= 1208,
	MGREEFFECTOR_COLOR									= 1113,
		MGREEFFECTOR_COLOR_R								= 1209,
		MGREEFFECTOR_COLOR_G								= 1210,
		MGREEFFECTOR_COLOR_B								= 1211,
	MGREEFFECTOR_WEIGHT									= 1114,
	MGREEFFECTOR_CLONE									= 1115,
	MGREEFFECTOR_TIME										= 1116,
	MGREEFFECTOR_U											= 1117,
	MGREEFFECTOR_V											= 1118,
	MGREEFFECTOR_VISIBILITY							= 1119,
	MGREEFFECTOR_POSITION_STRENGTH			= 1120,
		MGREEFFECTOR_POSITION_STRENGTH_X		= 1220,
		MGREEFFECTOR_POSITION_STRENGTH_Y		= 1221,
		MGREEFFECTOR_POSITION_STRENGTH_Z		= 1222,
	MGREEFFECTOR_SCALE_STRENGTH					= 1121,
		MGREEFFECTOR_SCALE_STRENGTH_X				= 1223,
		MGREEFFECTOR_SCALE_STRENGTH_Y				= 1224,
		MGREEFFECTOR_SCALE_STRENGTH_Z				= 1225,
	MGREEFFECTOR_ROTATION_STRENGTH			= 1122,
		MGREEFFECTOR_ROTATION_STRENGTH_H		= 1226,
		MGREEFFECTOR_ROTATION_STRENGTH_P		= 1227,
		MGREEFFECTOR_ROTATION_STRENGTH_B		= 1228,
	MGREEFFECTOR_COLOR_STRENGTH					= 1123,
		MGREEFFECTOR_COLOR_STRENGTH_R				= 1229,
		MGREEFFECTOR_COLOR_STRENGTH_G				= 1230,
		MGREEFFECTOR_COLOR_STRENGTH_B				= 1231,
	MGREEFFECTOR_WEIGHT_STRENGTH				= 1124,
	MGREEFFECTOR_CLONE_STRENGTH					= 1125,
	MGREEFFECTOR_TIME_STRENGTH					= 1126,
	MGREEFFECTOR_U_STRENGTH							= 1127,
	MGREEFFECTOR_V_STRENGTH							= 1128,
	MGREEFFECTOR_VISIBILITY_STRENGTH		=	1129,

	MGREEFFECTOR_EFFECTORS							= 1130,

	MGREEFFECTOR_SELECTION							=	1021
};
#endif // OEREEFFECTOR_H__
