#ifndef OFALLOFF_STANDARD_H__
#define OFALLOFF_STANDARD_H__

enum
{
	//Falloff controls
	FALLOFF_SCALE						= 5101,
	FALLOFF_FALLOFF					=	5102,
	FALLOFF_SIZE						=	5103,
	FALLOFF_SPLINE					=	5104,
	FALLOFF_SETTINGS				=	5109,
	FALLOFF_GENERAL					=	5110,
	FALLOFF_ANIM_SPEED			=	5111,
	FALLOFF_STRENGTH				=	5112,
	FALLOFF_CLAMPED					=	5114,


	FALLOFF_SHAPE_SLICE = 5120,
	FALLOFF_SHAPE_OFFSET = 5121,

	FALLOFF_FUNCTION = 5122,
	FALLOFF_FUNCTION_LIN = 0,
	FALLOFF_FUNCTION_SPLINE = 1,
	FALLOFF_FUNCTION_INV = 2,
	FALLOFF_FUNCTION_INVS = 3,
	FALLOFF_FUNCTION_INVC = 4,
	FALLOFF_FUNCTION_STEP = 5,

	FALLOFF_FUNCTION_SPHERICAL = 5123,
	FALLOFF_FUNCTION_RADIUS = 5124,

	FALLOFF_SHAPE_TORUS_RADIUS = 5125,

	FALLOFF_SHAPE_AXIS = 5126,
	FALLOFF_SHAPE_AXIS_XP = 0,
	FALLOFF_SHAPE_AXIS_XN = 1,
	FALLOFF_SHAPE_AXIS_YP = 2,
	FALLOFF_SHAPE_AXIS_YN = 3,
	FALLOFF_SHAPE_AXIS_ZP = 4,
	FALLOFF_SHAPE_AXIS_ZN = 5,

	FALLOFF_FUNCTION_HIDE_SPHERICAL = 5127

};
#endif // OFALLOFF_STANDARD_H__
