#ifndef OINSTANCE_H__
#define OINSTANCE_H__

enum
{
	INSTANCEOBJECT_LINK						= 1001, // LINK
	INSTANCEOBJECT_RENDERINSTANCE_MODE = 1002, // Instance Mode (Int32 since R20)
		INSTANCEOBJECT_RENDERINSTANCE_MODE_NONE						= 0,
		INSTANCEOBJECT_RENDERINSTANCE_MODE_SINGLEINSTANCE = 1,
		INSTANCEOBJECT_RENDERINSTANCE_MODE_MULTIINSTANCE	= 2,
	INSTANCEOBJECT_MULTIPOSITIONINPUT = 1003, // multiinstance Link
	INSTANCEOBJECT_DRAW_MODE					= 1004,
		INSTANCEOBJECT_DRAW_MODE_NONE			= 0,	
		INSTANCEOBJECT_DRAW_MODE_POINTS		= 1,	
		INSTANCEOBJECT_DRAW_MODE_FULL			= 2,
		INSTANCEOBJECT_DRAW_MODE_CUBE			= 3,
		INSTANCEOBJECT_DRAW_MODE_BBOX			= 4,
};

#endif // OINSTANCE_H__
