#ifndef OMOGRAPH_SPLINEWRAP_H__
#define OMOGRAPH_SPLINEWRAP_H__

enum
{
	MGSPLINEWRAPDEFORMER_SIZE_GRP				= 990,
	MGSPLINEWRAPDEFORMER_ROT_GRP				= 991,
	MGSPLINEWRAPDEFORMER_BOUNDS_GRP			=	992,
	MGSPLINEWRAPDEFORMER_STRENGTH				= 1000,
	MGSPLINEWRAPDEFORMER_SPLINE					= 1001,
	MGSPLINEWRAPDEFORMER_FROM						= 1002,
	MGSPLINEWRAPDEFORMER_TO							= 1003,
	MGSPLINEWRAPDEFORMER_OFFSET					= 1004,
	MGSPLINEWRAPDEFORMER_MODE						= 1005,
	MGSPLINEWRAPDEFORMER_MODE_CLAMP			= 0,
	MGSPLINEWRAPDEFORMER_MODE_EXTEND		= 1,
	MGSPLINEWRAPDEFORMER_AXIS						= 1006,
	MGSPLINEWRAPDEFORMER_AXIS_XP				= 0,
	MGSPLINEWRAPDEFORMER_AXIS_XN				= 1,
	MGSPLINEWRAPDEFORMER_AXIS_YP				= 2,
	MGSPLINEWRAPDEFORMER_AXIS_YN				= 3,
	MGSPLINEWRAPDEFORMER_AXIS_ZP				= 4,
	MGSPLINEWRAPDEFORMER_AXIS_ZN				= 5,
	MGSPLINEWRAPDEFORMER_SIZE						= 1007,
	MGSPLINEWRAPDEFORMER_ROTATE					= 1008,
	MGSPLINEWRAPDEFORMER_BANK						= 1009,
	MGSPLINEWRAPDEFORMER_SIZESTRN				= 1010,
	MGSPLINEWRAPDEFORMER_ROTSTRN				= 1011,
	MGSPLINEWRAPDEFORMER_LENMODE				= 1012,
	MGSPLINEWRAPDEFORMER_LENMODE_FIT		= 0,
	MGSPLINEWRAPDEFORMER_LENMODE_KEEP		= 1,
	MGSPLINEWRAPDEFORMER_SPLINESIZE			= 1013,
	MGSPLINEWRAPDEFORMER_SLINEROTATE		= 1014,
	MGSPLINEWRAPDEFORMER_SPLINESIZESTRN = 1015,
	MGSPLINEWRAPDEFORMER_SPLINEROTSTRN	= 1016,
	MGSPLINEWRAPDEFORMER_UPVECTOR				=	1017,
	MGSPLINEWRAPDEFORMER_FIXBB					=	1018,
	MGSPLINEWRAPDEFORMER_RAIL_SPLINE		=	1019,
	MGSPLINEWRAPDEFORMER_RAIL_TARGET		=	1020,
	MGSPLINEWRAPDEFORMER_RAIL_SCALE			=	1021,
	MGSPLINEWRAPDEFORMER_BB_CENTER			=	1022,
	MGSPLINEWRAPDEFORMER_BB_RADIUS			=	1023
};
#endif // OMOGRAPH_SPLINEWRAP_H__
