#ifndef OREMESH_H__
#define OREMESH_H__

enum
{
	ID_REMESH_POLYGONTYPE												= 1000, // LONG
		ID_REMESH_POLYGONTYPE_QUADRANGLES					= 0,
		ID_REMESH_POLYGONTYPE_TRIANGLES						= 1,
	ID_REMESH_POLYGONTARGET											= 1001, // LONG
	ID_REMESH_KEEPOUTLINE												= 1002, // BOOL
	ID_REMESH_CREASES														= 1003, // BOOL
	ID_REMESH_EDGEANGLE													= 1004, // FLOAT
	ID_REMESH_SMOOTHITERATIONS									= 1005, // LONG
	ID_REMESH_DETERMINISTIC											= 1006, // BOOL
	ID_REMESH_EXTRINSIC													= 1007, // BOOL
	ID_REMESH_ADVANCEDSETTINGS									= 1008, // GROUP
	ID_REMESH_POLYGONSCALE											= 1010, // FLOAT
	ID_REMESH_QUADONLY													= 1011, // BOOL
	ID_REMESH_POLYGONTARGET_MODE								= 1012, // LONG
		ID_REMESH_POLYGONTARGET_MODE_ABSOLUTE			= 0,
		ID_REMESH_POLYGONTARGET_MODE_MESHDENSITY	= 1,
	ID_REMESH_GUIDE_SPLINES											= 1013, //INEXCLUDE
};

#endif // OREMESH_H__
