#ifndef OSHATTER_H__
#define OSHATTER_H__

enum
{
	SHATTEROBJECT_ANGLESPEED	= 1000,
	SHATTEROBJECT_SCALE				= 1001,
	SHATTEROBJECT_RANDOM			= 1002,
	SHATTEROBJECT_STRENGTH    = 1003
};

#endif // OSHATTER_H__
