#ifndef OSPLINE_H__
#define OSPLINE_H__

enum
{
	SPLINEOBJECT_INTERPOL						= 820,

	SPLINEOBJECT_TYPE										= 1000,
		SPLINEOBJECT_TYPE_LINEAR			= 0,
		SPLINEOBJECT_TYPE_CUBIC				= 1,
		SPLINEOBJECT_TYPE_AKIMA				= 2,
		SPLINEOBJECT_TYPE_BSPLINE			= 3,
		SPLINEOBJECT_TYPE_BEZIER			= 4,
	SPLINEOBJECT_INTERPOLATION	= 1001,
		SPLINEOBJECT_INTERPOLATION_NONE       = 0,
		SPLINEOBJECT_INTERPOLATION_NATURAL  = 1,
		SPLINEOBJECT_INTERPOLATION_UNIFORM  = 2,
		SPLINEOBJECT_INTERPOLATION_ADAPTIVE = 3,
		SPLINEOBJECT_INTERPOLATION_SUBDIV   = 4,
	SPLINEOBJECT_CLOSED					      = 1002,
	SPLINEOBJECT_SUB						     			= 1003,
	SPLINEOBJECT_ANGLE									= 1004,
	SPLINEOBJECT_MAXIMUMLENGTH					= 1005
};

#endif // OSPLINE_H__
