#ifndef PREFSPATHS_H__
#define PREFSPATHS_H__

enum
{
	PREFS_PATHS_MAIN_GROUP			= 999,
	PREF_TEXPATHS								= 1000,
	PREF_DATABASE_PATHS					= 1001,

	PREFS_TEXPATH_GROUP					= 2000,
	PREFS_DATABASE_PATHS_GROUP	= 2001,

	PREFS_DUMMY
};

#endif // PREFSPATHS_H__
