#ifndef PREFSNODEEDITOR_H__
#define PREFSNODEEDITOR_H__

enum
{
	PREF_NODE_EDITOR_MAIN_GROUP				= 999,
	PREF_NODE_EDITOR_PREVIEW					= 1000,
	PREF_NODE_EDITOR_GRID							= 1001,
	PREF_NODE_EDITOR_NAVIGATOR				= 1002,
	PREF_NODE_EDITOR_ERRORS						= 1003,
	PREF_NODE_EDITOR_WIRE_STYLE				= 1004,
		PREF_NODE_EDITOR_WIRE_STYLE_BEZIER		= 0,
		PREF_NODE_EDITOR_WIRE_STYLE_STRAIGHT	= 1,

	PREF_NODE_EDITOR_DUMMY
};

#endif // PREFSNODEEDITOR_H__
