#ifndef PREFSHOUDINI_H__
#define PREFSHOUDINI_H__

enum
{
	PREFS_HOUDINI_MAIN_GROUP										= 999,
	PREFS_HOUDINI_ENGINE_VERSION								= 1000,
	PREFS_HOUDINI_ENGINE_INSTALLATION_PATH			= 1001,
	PREFS_HOUDINI_ENGINE_INSTALLATION_STATUS		= 1002,
	PREFS_HOUDINI_ENGINE_LICENSE_TYPE						= 1003,
	PREFS_HOUDINI_ENGINE_STATUS									= 1004,
	PREFS_HOUDINI_ENGINE_API_VERSION						= 1005,
	PREFS_HOUDINI_ENGINE_GET_INSTALLER					= 1006,
	PREFS_PM_DUMMY
};

#endif // PREFSHOUDINI_H__
