#ifndef PREFSGPURENDERER_H__
#define PREFSGPURENDERER_H__

enum
{
	// 1000 to 1099 is reserved for the GPU devices!
	PREFS_GPURENDERER_DEVICES_OFFLINE = 1000,
	PREFS_GPURENDERER_DEVICES_PREVIEW = 1050,
	PREFS_GPURENDERER_DEVICE_CPU_OFFLINE = 1100,
	PREFS_GPURENDERER_DEVICE_CPU_PREVIEW = 1101,
	
	// 1200 to 1250 is reserved for the GPU devices to print "recommended"
	PREFS_GPURENDERER_DEVICE_STATIC_TEXT = 1200,
	PREFS_GPURENDERER_USEINTEROP = 1251,
	
	PREFS_GPURENDERER_DEVICE_GROUP_OFFLINE = 2000,
	PREFS_GPURENDERER_DEVICE_GROUP_PREVIEW = 2001,
	PREFS_GPURENDERER_ENABLE_METAL = 2002,

	PREFS_GPURENDERER_OOC_TEXTURE_CACHE_CUSTOM_PATH_ENABLED = 2003,
	PREFS_GPURENDERER_OOC_TEXTURE_CACHE_CUSTOM_PATH	= 2004,
	
	PREFS_GPURENDERER_GROUP = 3000,
	PREFS_GPURENDERER_OOC_GROUP = 3001,
	PREFS_GPURENDERER_BUTTON_GROUP = 3002,
	
	// 4000 to 4050 is reserved for the GPU device names
	PREFS_GPURENDERER_DEVICES_GPU_NAME = 4000,
	PREFS_GPURENDERER_DEVICES_GPU_COUNT = 4050,
	PREFS_GPURENDERER_DEVICES_CPU_NAME = 4051,

	PREFS_GPURENDERER_COMPILE_SHADERS = 5000,
	PREFS_GPURENDERER_CLEAR_SHADER_CACHE = 5001,
	
	PREFS_GPURENDERER_DUMMY
};

#endif // PREFSGPURENDERER_H__
