#ifndef SBROTATE_H__
#define SBROTATE_H__

enum
{
	ROTATESURFACE_ANGLE_START			= 1101,
	ROTATESURFACE_ANGLE_END				= 1102,
	ROTATESURFACE_LINK_AXIS				= 1103,
	ROTATESURFACE_INVERT_AXIS			= 1104
};

#endif // SBROTATE_H__
