#ifndef TCAMORPH_H__
#define TCAMORPH_H__

enum
{
	MORPHTAG_EDIT_GROUP					=	991,
	MORPHTAG_ANIM_GROUP					=	992,
	MORPHTAG_MORPH_GROUP				=	993,
	MORPHTAG_BMORPH_GROUP				=	994,
	MORPHTAG_TMORPH_GROUP				=	995,
	MORPHTAG_AMORPH_GROUP				=	996,
	//Morphs
	MORPHTAG_STRENGTH						=	1000,
	MORPHTAG_EDITINGMODE				=	1001,
	MORPHTAG_STORE							= 1002,
	MORPHTAG_MORPHMODE					=	1103,
		MORPHTAG_MORPHMODE_ABSOLUTE	= 0,
		MORPHTAG_MORPHMODE_RELATIVE	= 1,
		MORPHTAG_MORPHMODE_ROTATION	=	2,
	MORPHTAG_XREF								=	1004,
	MORPHTAG_STOREPARAM					=	1005,
	MORPHTAG_STOREDELTA					=	1006,
	//Target Morph
	MORPHTAG_ROTPOS							=	1107,
	MORPHTAG_ROTDIR							=	1108,
	MORPHTAG_SETROT_FROMEDGE		=	1109,
	MORPHTAG_SETROT_FROMPOINTS	=	1110,
	//Active Morph
	MORPHTAG_OBJECT							= 1250,
	//Morph Tag
	MORPHTAG_MODE								= 2000,
		MORPHTAG_MODE_EDIT					=	0,
		MORPHTAG_MODE_ANIMATE				=	1,
	MORPHTAG_EDITINPLACE				=	2001,
	MORPHTAG_ADDMORPH						=	2002,
	MORPHTAG_MORPHS							=	2003,
	MORPHTAG_TOMESH							=	2004,
	MORPHTAG_EXPORT							=	2005,
	MORPHTAG_RESET							=	2006,
	MORPHTAG_ADDROTDRIVERS			=	2007,
	MORPHTAG_FULLREFRESH				=	2008
};

#endif // TCAMORPH_H__
