#ifndef TCAWEIGHT_H__
#define TCAWEIGHT_H__

enum
{
	ID_CA_WEIGHT_TAG_RESET = 2001,
	ID_CA_WEIGHT_TAG_SET = 2005,
	ID_CA_WEIGHT_TAG_TOTALWEIGHT = 2007,
	ID_CA_WEIGHT_TAG_JOINT_MAP = 2008,
	ID_CA_WEIGHT_TAG_JOINTS_LIST = 2009,
	ID_CA_WEIGHT_TAG_SET_BUTTON = 2010,
	ID_CA_WEIGHT_TAG_RESET_BUTTON = 2011,
	ID_CA_WEIGHT_TAG_SET_SELECTED_JOINTS = 2012,
	ID_CA_WEIGHT_TAG_SET_DEFORMED_MESH = 2013,
	ID_CA_WEIGHT_TAG_RESET_SELECTED_JOINTS = 2014,
	ID_CA_WEIGHT_TAG_JOINTS_GROUP = 5000,
	//////////////////////////////////////////////////////////////////////////
	ID_CA_WEIGHT_TAG_DUMMY
};

#endif // TCAWEIGHT_H__
