#ifndef TCHARACTERSOLVER_H__
#define TCHARACTERSOLVER_H__

enum
{
	CS_SOLVER_GROUP = 1000, // Group
	CS_SOLVERRESULT_GROUP,

	// Data
	CS_SOURCE_CHARACTER = 2000,
	CS_TARGET_CHARACTER,
	CS_COMPONENTMATCH_RESULT,
	CS_OBJECTMATCH_RESULT,
	CS_ERROR_RESULT,

	// Functions
	CS_GOTORESTPOSE = 4000,

	CS_LAST
};

#endif // TCHARACTERSOLVER_H__
