#ifndef TOOL_MGSELECT_H__
#define TOOL_MGSELECT_H__

enum
{
	MDATA_MGSELECTTOOL_RADIUS				= 1100, //REAL
	MDATA_MGSELECTTOOL_MODE					= 1101,	// LONG
	MDATA_MGSELECTTOOL_SHOWINDEX		= 1102,	//BOOL

	MDATA_MGSELECTTOOL_RECTANGLE = 1,
	MDATA_MGSELECTTOOL_POLYGON	 = 2,
	MDATA_MGSELECTTOOL_FREE			= 3,
	MDATA_MGSELECTTOOL_RADIAL		= 4

};
#endif // TOOL_MGSELECT_H__
