#ifndef TOOLHAIRDYNAMICS_H__
#define TOOLHAIRDYNAMICS_H__

enum
{
	HAIR_TOOL_DYNAMICS_REDRAW = 1000,
	HAIR_TOOL_DYNAMICS_TIME,
	HAIR_TOOL_DYNAMICS_DYNAMICS,
	HAIR_TOOL_DYNAMICS_COLLISIONS,
	HAIR_TOOL_DYNAMICS_GRAVITY,
	HAIR_TOOL_DYNAMICS_STIFFNESS,
	HAIR_TOOL_DYNAMICS_FORCES,
	HAIR_TOOL_DYNAMICS_RESET,
	HAIR_TOOL_DYNAMICS_TUNIT,

	//////////////////////////////////////////////////////////////////////////

	HAIR_DYNAMICS_DUMMY
};

#endif // TOOLHAIRDYNAMICS_H__
