#ifndef TOOLBODYPART_H__
#define TOOLBODYPART_H__

enum
{
	// Groups
	TBP_CHARACTERDEFINITION_ATTRIBUTES_GROUP = 2000,

	// UI elements
	TBP_PART_JOINTS = 3000,
	TBP_PART_JOINTS_NAME,
	TBP_PART_CONTROLS,
	TBP_PART_CONTROLS_NAME,
	TBP_PART_INCLUDESTRING,
	TBP_PART_INCLUDESTRING_NAME,
	TBP_PART_EXCLUDESTRING,
	TBP_PART_EXCLUDESTRING_NAME,
	TBP_PART_IDENTIFIER,
	TBP_PART_IDENTIFIER_NAME,

	// Internal Tool Data
	TBP_CHARACTERDEFINITIONTAG = 4000, // Tag
	TBP_BODYPARTID, // String internedid

	TBP_LAST
};

#endif // TOOLBODYPART_H__
