#ifndef TOOL_MGWEIGHT_H__
#define TOOL_MGWEIGHT_H__

enum
{
	MDATA_MGWEIGHTTOOL_GROUP_OPTIONS			= 900, // GROUP
	MDATA_MGWEIGHTTOOL_GROUP_PAINTING			= 901, // GROUP

	MDATA_MGWEIGHTTOOL_STRENGTH						= 1100, // REAL
	MDATA_MGWEIGHTTOOL_MODE								= 1101,	// LONG
		MDATA_MGWEIGHTTOOL_MODE_ADD						= 0,
		MDATA_MGWEIGHTTOOL_MODE_ERASE					= 1,
		MDATA_MGWEIGHTTOOL_MODE_ABS						= 2,
		MDATA_MGWEIGHTTOOL_MODE_SMOOTH				= 3,
	MDATA_MGWEIGHTTOOL_APPLYALL						= 1102,	// BUTTON
	MDATA_MGWEIGHTTOOL_APPLYSELECTED			= 1103,	// BUTTON
	MDATA_MGWEIGHTTOOL_RADIUS							= 1104, // REAL
	MDATA_MGWEIGHTTOOL_STEP								= 1105, // LONG
	MDATA_MGWEIGHTTOOL_PRESSURE						= 1106, // LONG
		MDATA_MGWEIGHTTOOL_PRESSURE_NONE			= 0,
		MDATA_MGWEIGHTTOOL_PRESSURE_STRENGTH	= 1,
		MDATA_MGWEIGHTTOOL_PRESSURE_RADIUS		= 2,
	MDATA_MGWEIGHTTOOL_DISPLAY						= 1107, // BOOL
	MDATA_MGWEIGHTTOOL_VISIBLE_ONLY				= 1108 // BOOL
};
#endif // TOOL_MGWEIGHT_H__
