#ifndef TOOLHAIRSOFTSELECTION_H__
#define TOOLHAIRSOFTSELECTION_H__

enum
{
	HAIR_SOFTSELECTION = 1000,
	HAIR_SOFTSELECTION_STRENGTH,
	HAIR_SOFTSELECTION_FALLOFF,
	HAIR_SOFTSELECTION_FALLOFF_CURVE,
	HAIR_SOFTSELECTION_WIDTH,
	HAIR_SOFTSELECTION_TYPE,
	HAIR_SOFTSELECTION_RADIUS,
	HAIR_SOFTSELECTION_SPACE,
	HAIR_SOFTSELECTION_PREVIEW,
	HAIR_SOFTSELECTION_CLIP,
	HAIR_SOFTSELECTION_TWEAK,
	HAIR_SOFTSELECTION_VISIBLE,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SOFTSELECTION_FALLOFF_NONE = 0,
	HAIR_SOFTSELECTION_FALLOFF_LINEAR,
	HAIR_SOFTSELECTION_FALLOFF_DOME,
	HAIR_SOFTSELECTION_FALLOFF_BELL,
	HAIR_SOFTSELECTION_FALLOFF_CIRCLE,
	HAIR_SOFTSELECTION_FALLOFF_NEEDLE,
	HAIR_SOFTSELECTION_FALLOFF_SPLINE,

	HAIR_SOFTSELECTION_TYPE_SINGLE = 0,
	HAIR_SOFTSELECTION_TYPE_VOLUME,
	HAIR_SOFTSELECTION_TYPE_ROOT,

	HAIR_SOFTSELECTION_SPACE_WORLD = 0,
	HAIR_SOFTSELECTION_SPACE_SCREEN,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SOFTSELECTION_DUMMY
};

#endif // TOOLHAIRSOFTSELECTION_H__
