#ifndef TOOLHAIRLIVESELECT_H__
#define TOOLHAIRLIVESELECT_H__

enum
{
	HAIR_LIVESELECT_RADIUS = 1000,
	HAIR_LIVESELECT_VISIBLE,
	HAIR_LIVESELECT_RESTRICT,
	HAIR_LIVESELECT_SHAPE,
	HAIR_LIVESELECT_SHAPE_ASPECT,
	HAIR_LIVESELECT_SHAPE_ANGLE,
	HAIR_LIVESELECT_LOCKED,
	HAIR_LIVESELECT_PEN,
	HAIR_LIVESELECT_PRESSURE,
	HAIR_LIVESELECT_KEYPRESSED,

	//////////////////////////////////////////////////////////////////////////

	HAIR_LIVESELECT_SHAPE_CIRCLE = 0,
	HAIR_LIVESELECT_SHAPE_BOX,
	HAIR_LIVESELECT_SHAPE_DIAMOND,

	HAIR_LIVESELECT_PEN_NONE = 0,
	HAIR_LIVESELECT_PEN_RADIUS,
	HAIR_LIVESELECT_PEN_STRENGTH,

	//////////////////////////////////////////////////////////////////////////

	HAIR_LIVESELECT_DUMMY
};

#endif // TOOLHAIRLIVESELECT_H__
