#ifndef TOOLMIRRORBASE_H__
#define TOOLMIRRORBASE_H__

enum
{
	ID_CA_TOOL_MIRROR_BASE = 10000,

	ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_INVALID = 0,
	ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_NONE,
	ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_TOPO,
	ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_POS,
	ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_SPATIAL_PART,
	ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_NAME,
	ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_LAST_RESORT,

	ID_CA_TOOL_MIRROR_BASE_ORIGIN_SELECTED = 0,
	ID_CA_TOOL_MIRROR_BASE_ORIGIN_ROOT,
	ID_CA_TOOL_MIRROR_BASE_ORIGIN_PARENT,
	ID_CA_TOOL_MIRROR_BASE_ORIGIN_HUB,
	ID_CA_TOOL_MIRROR_BASE_ORIGIN_OBJECT,
	ID_CA_TOOL_MIRROR_BASE_ORIGIN_WORLD,
	ID_CA_TOOL_MIRROR_BASE_ORIGIN_MESH,

	ID_CA_TOOL_MIRROR_BASE_SEARCH_RADIUS = 0,
	ID_CA_TOOL_MIRROR_BASE_SEARCH_NEAREST,
	ID_CA_TOOL_MIRROR_BASE_SEARCH_SURFACE,
	ID_CA_TOOL_MIRROR_BASE_SEARCH_NORMALS,

	ID_CA_TOOL_MIRROR_BASE_COORDS_WORLD = 0,
	ID_CA_TOOL_MIRROR_BASE_COORDS_LOCAL,
	ID_CA_TOOL_MIRROR_BASE_COORDS_VIEW,

	ID_CA_TOOL_MIRROR_BASE_DIRECTION_X = 0,
	ID_CA_TOOL_MIRROR_BASE_DIRECTION_Y,
	ID_CA_TOOL_MIRROR_BASE_DIRECTION_Z,

	ID_CA_TOOL_MIRROR_BASE_TYPE_REFLECT = 0,
	ID_CA_TOOL_MIRROR_BASE_TYPE_P2N,
	ID_CA_TOOL_MIRROR_BASE_TYPE_N2P,

	ID_CA_TOOL_MIRROR_BASE_DUMMY
};

#endif // TOOLMIRRORBASE_H__
