#ifndef TOOLSCULPTBRUSHPOLISH_H__
#define TOOLSCULPTBRUSHPOLISH_H__

enum
{
	ToolSculptBrushPolish_Start = 20000,

	MDATA_SCULPTBRUSH_POLISHMODE,
		MDATA_SCULPTBRUSH_POLISHMODE_STANDARD,
		MDATA_SCULPTBRUSH_POLISHMODE_HARD,
};

#endif // TOOLSCULPTBRUSHPOLISH_H__
