#ifndef TOOL_MGGRID_H__
#define TOOL_MGGRID_H__

enum
{
	MDATA_MGGRIDTOOL_CENTER				= 1100, //VECTOR
	MDATA_MGGRIDTOOL_RADIUS				= 1101, //VECTOR
	MDATA_MGGRIDTOOL_COUNT				= 1102, //VECTOR

	MDATA_MGGRIDTOOL_MODE					= 1110,
	MDATA_MGGRIDTOOL_MODE_CLONE		= 0,
	MDATA_MGGRIDTOOL_MODE_INSTANCE = 1
};
#endif // TOOL_MGGRID_H__
