#ifndef TOOLCREATEPOLYGON_H__
#define TOOLCREATEPOLYGON_H__

enum
{

	MDATA_POLYGONCREATE_OBJINDEX 							= 1100, //LINK
	MDATA_POLYGONCREATE_CONTAINER							= 1101, //BASECONTAINER
	MDATA_CREATEPOLYGON_BUTTON								= 1102,
	MDATA_CREATEPOLYGON_NAME									= 1103,
	MDATA_CREATEPOLYGON_CREATE                = 1105,
	MDATA_CREATEPOLYGON_SET_NGON              = 1106,
	MDATA_CREATEPOLYGON_SET_TRI               = 1107,
	MDATA_CREATEPOLYGON_SET_QUAD              = 1108,
	MDATA_CREATEPOLYGON_SNAPTO                = 1109,
	MDATA_CREATEPOLYGON_NGON_SUB              = 1110,
	MDATA_CREATEPOLYGON_NGON_NGON             = 1111,
	MDATA_CREATEPOLYGON_NGON_TRI              = 1112,
	MDATA_CREATEPOLYGON_NGON_QUAD             = 1113,
	MDATA_CREATEPOLYGON_POSITIONX							= 1114,
	MDATA_CREATEPOLYGON_POSITIONY							= 1115,
	MDATA_CREATEPOLYGON_POSITIONZ							= 1116,
	MDATA_CREATEPOLYGON_VISIBLE  							= 1117,
	MDATA_CREATEPOLYGON_
};

#endif // TOOLCREATEPOLYGON_H__
