#ifndef TOOLSCULPTBRUSHKNIFE_H__
#define TOOLSCULPTBRUSHKNIFE_H__

enum
{
	ToolSculptBrushKnife_Start = 3000,
	MDATA_SCULPTBRUSH_KNIFE_PINCH,
	MDATA_SCULPTBRUSH_KNIFE_PUSH,
	MDATA_SCULPTBRUSH_KNIFE_SMOOTH,
};

#endif // TOOLSCULPTBRUSHKNIFE_H__
