#ifndef TPHONG_H__
#define TPHONG_H__

enum
{
	PHONGTAG_PHONG_ANGLELIMIT		= 1001, // Bool
	PHONGTAG_PHONG_ANGLE				= 1002, // Real
	PHONGTAG_PHONG_USEEDGES			= 1003, // Bool
	PHONGTAG_CREATE_NORMAL_TAG  = 1004, // Button
	PHONGTAG_STRING_NORMAL_TAG  = 1005  // String
};

#endif // TPHONG_H__
