#ifndef TSPOOLDUMMY_H__
#define TSPOOLDUMMY_H__

enum
{
	SPOOLDUMMY_DISPLAYPRESET					= 10000,	// LONG
		SPOOLDUMMY_DISPLAYPRESET_FILE			= 0,
		SPOOLDUMMY_DISPLAYPRESET_FRAMEBUFFER	= 1,
		SPOOLDUMMY_DISPLAYPRESET_CUSTOM			= 2,
	SPOOLDUMMY_DISPLAY							= 10001,	// STRING
	SPOOLDUMMY_DOSTART							= 10002,	// BOOL
	SPOOLDUMMY_EXPORTSTART						= 20000,	// BUTTON
	SPOOLDUMMY_EXPORT							= 20001		// BUTTON
};

#endif // TSPOOLDUMMY_H__
