#ifndef TVOLUME_H__
#define TVOLUME_H__

enum
{
	ID_VOLUME_MATERIAL = 7000,
	ID_VOLUME_DENSITY_SELECTION = 7001,
	ID_VOLUME_DENSITY_RANGEMAP_MAX = 7002,
	ID_VOLUME_ALBEDO_SELECTION = 7003,
	ID_VOLUME_ALBEDO_RANGEMAP_MAX = 7004,
	ID_VOLUME_EMISSION_SELECTION = 7005,
	ID_VOLUME_EMISSION_RANGEMAP_MAX = 7006,
		ID_VOLUME_NONE_SELECTED = 0,
	ID_VOLUME_DENSITY_RANGEMAP_MIN = 7007,
	ID_VOLUME_ALBEDO_RANGEMAP_MIN = 7008,
	ID_VOLUME_EMISSION_RANGEMAP_MIN = 7009,
	ID_VOLUME_DENSITY_RANGEMAP_DETECT = 7010,
	ID_VOLUME_ALBEDO_RANGEMAP_DETECT = 7011,
	ID_VOLUME_EMISSION_RANGEMAP_DETECT = 7012
};

#endif // TVOLUME_H__