#ifndef VPBLOOM_H__
#define VPBLOOM_H__

enum
{
	VP_BLOOM_STRENGTH = 1000,
	VP_BLOOM_TONE_MAP = 1001,
	VP_BLOOM_GRADIENT_LOCAL_SPREAD = 1002,
	VP_BLOOM_GRADIENT_GLOBAL_SPREAD = 1003,
	VP_BLOOM_LUMINANCE_CUTOFF_FULL = 1004,
	VP_BLOOM_LUMINANCE_CUTOFF = 1005,
	VP_BLOOM_LUMINANCE_FUNC = 1006,
		VP_BLOOM_LUMINANCE_FUNC_SMART = 0,
		VP_BLOOM_LUMINANCE_FUNC_MAX_CHANNEL = 1,
		VP_BLOOM_LUMINANCE_FUNC_RELATIVE = 2,
		VP_BLOOM_LUMINANCE_FUNC_AVERAGE = 3,
		VP_BLOOM_LUMINANCE_FUNC_HSP = 4,
		VP_BLOOM_LUMINANCE_FUNC_W3 = 5,
	VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC = 1007,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_LINEAR = 0,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_QUADRATIC = 1,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_CUBIC = 2,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_POW4 = 3,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_POW5 = 4,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_POW6 = 5,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_POW7 = 6,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_POW8 = 7,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_POW9 = 8,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_POW10 = 9,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_SQRT = 10,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_SQRT2 = 11,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_SQRT3 = 12,
		VP_BLOOM_LUMINANCE_CUTOFF_DEGRADE_FUNC_SQRT4 = 13,
	VP_BLOOM_LUMINANCE_CUTOFF_USE_SPLINE = 1008,
	VP_BLOOM_LUMINANCE_CUTOFF_SPLINE = 1009,
	VP_BLOOM_OUTPUT_BLOOMING_PIXELS = 1010,
};

#endif // VPBLOOM_H__

