#ifndef VPHAIRTRACE_H__
#define VPHAIRTRACE_H__

enum
{
	HAIR_RENDER_GROUP_SHADOWS = 10000,
	HAIR_RENDER_GROUP_LIGHTS,
	HAIR_RENDER_GROUP_OBJECTS,
	HAIR_RENDER_GROUP_RENDER,
	HAIR_RENDER_GROUP_MULTIPASS,

	HAIR_RENDER_HAIR_AA = 1001,

	HAIR_RENDER_SHADOW_WIDTH,
	HAIR_RENDER_SHADOW_CACHE_SIZE,
	HAIR_RENDER_AA_USER,
	HAIR_RENDER_SHADOW_SAMPLE_SIZE,
	HAIR_RENDER_SHADOW_SAMPLE_ACCURACY,
	HAIR_RENDER_COLOR_SAMPLING,
	HAIR_RENDER_TYPE,
	HAIR_RENDER_COLOR_PER_VERTEX,
	HAIR_RENDER_SHADOWS,
	HAIR_RENDER_LINES,
	HAIR_RENDER_SPLIT,
	HAIR_RENDER_TRANSPARENCY,
	HAIR_RENDER_AA_QUALITY,
	HAIR_RENDER_SHADOW_AA,

	HAIR_RENDER_OBJECTS_MODE,
	HAIR_RENDER_OBJECTS,
	HAIR_RENDER_LIGHTS_MODE,
	HAIR_RENDER_LIGHTS,
	HAIR_RENDER_MEMORY_USE,
	HAIR_RENDER_TRACING,
	HAIR_RENDER_SHADOW_TRANS_ACCURACY,
	HAIR_RENDER_SHADOW_DIST_ACCURACY,
	HAIR_RENDER_SHADOWS_MAP,

	HAIR_RENDER_MP_RGB,
	HAIR_RENDER_MP_DEPTH,
	HAIR_RENDER_MP_ALPHA,
	HAIR_RENDER_MP_SPLIT_BACK,
	HAIR_RENDER_MP_COLOR,
	HAIR_RENDER_MP_DIFFUSE,
	HAIR_RENDER_MP_SPECULAR,
	HAIR_RENDER_MP_SECONDARY_SPECULAR,
	HAIR_RENDER_MP_GLINT,
	HAIR_RENDER_MP_RECIEVE_SHADOW,
	HAIR_RENDER_MP_SELF_SHADOW,
	HAIR_RENDER_MP_ILLUMINATION,

	HAIR_RENDER_OBJECTS_HAIR,
	HAIR_RENDER_OBJECTS_POLYGON,
	HAIR_RENDER_OBJECTS_SPLINE,
	HAIR_RENDER_OBJECTS_PARTICLE,
	HAIR_RENDER_HAIR_LENGTH,
	HAIR_RENDER_HAIR_COUNT,

	HAIR_RENDER_SHADOW_TYPE,
	HAIR_RENDER_SHADOW_AA_LEVEL,
	HAIR_RENDER_SHADOW_AA_USER,

	HAIR_RENDER_AA_MODE,

	HAIR_RENDER_SEPARATOR_A,
	HAIR_RENDER_SEPARATOR_B,
	HAIR_RENDER_SEPARATOR_C,
	HAIR_RENDER_SEPARATOR_D,
	HAIR_RENDER_SEPARATOR_E,
	HAIR_RENDER_SEPARATOR_F,

	HAIR_RENDER_SEPARATOR_PHYSICAL_A,
	HAIR_RENDER_SEPARATOR_PHYSICAL_B,

	HAIR_RENDER_PHYSICAL_CACHE_PRIMARY,
	HAIR_RENDER_PHYSICAL_CACHE_SECONDARY,
	HAIR_RENDER_PHYSICAL_CACHE_BLURRY,
	HAIR_RENDER_PHYSICAL_CACHE_GI,

	HAIR_RENDER_PHYSICAL_GI,
	HAIR_RENDER_PHYSICAL_GI_QUALITY,

	//////////////////////////////////////////////////////////////////////////

	HAIR_RENDER_COLOR_SAMPLING_FULL = 0,
	HAIR_RENDER_COLOR_SAMPLING_VERTEX = 1,
	HAIR_RENDER_COLOR_SAMPLING_ROOTTIP = 2,

	HAIR_RENDER_MEMORY_USE_LOW = 0,
	HAIR_RENDER_MEMORY_USE_MED,
	HAIR_RENDER_MEMORY_USE_HIGH,
	HAIR_RENDER_MEMORY_USE_MAX,

	HAIR_RENDER_AA_QUALITY_NONE = 0,
	HAIR_RENDER_AA_QUALITY_LOW,
	HAIR_RENDER_AA_QUALITY_MED,
	HAIR_RENDER_AA_QUALITY_HIGH,
	HAIR_RENDER_AA_QUALITY_BEST,
	HAIR_RENDER_AA_QUALITY_USER,

	HAIR_RENDER_MODE_INCLUDE = 0,
	HAIR_RENDER_MODE_EXCLUDE,

	HAIR_RENDER_SHADOWS_MAP_250 = 0,
	HAIR_RENDER_SHADOWS_MAP_500,
	HAIR_RENDER_SHADOWS_MAP_750,
	HAIR_RENDER_SHADOWS_MAP_1000,
	HAIR_RENDER_SHADOWS_MAP_1250,
	HAIR_RENDER_SHADOWS_MAP_1500,
	HAIR_RENDER_SHADOWS_MAP_1750,
	HAIR_RENDER_SHADOWS_MAP_2000,
	HAIR_RENDER_SHADOWS_MAP_CUSTOM,

	HAIR_RENDER_MP_DEPTH_OFF = 0,
	HAIR_RENDER_MP_DEPTH_ON,
	HAIR_RENDER_MP_DEPTH_OWN,

	HAIR_RENDER_MP_ALPHA_OFF = 0,
	HAIR_RENDER_MP_ALPHA_ON,
	HAIR_RENDER_MP_ALPHA_OWN,

	HAIR_RENDER_TYPE_RASTER_8BIT = 0,
	HAIR_RENDER_TYPE_RASTER_32BIT,
	HAIR_RENDER_TYPE_RASTER_POST,
	HAIR_RENDER_TYPE_RAYTRACED,

	HAIR_RENDER_SHADOW_TYPE_NONE = 0,
	HAIR_RENDER_SHADOW_TYPE_AUTO,
	HAIR_RENDER_SHADOW_TYPE_SOFT,
	HAIR_RENDER_SHADOW_TYPE_HARD,

	HAIR_RENDER_AA_MODE_OLD = 0,
	HAIR_RENDER_AA_MODE_NEW,
	HAIR_RENDER_AA_MODE_SUBPIXEL,

	HAIR_RENDER_PHYSICAL_GI_PIXEL = 0,
	HAIR_RENDER_PHYSICAL_GI_VERTEX,
	HAIR_RENDER_PHYSICAL_GI_ROOT,

	HAIR_RENDER_FORCE_MODE_DEFAULT = 0,
	HAIR_RENDER_FORCE_MODE_DISABLE,
	HAIR_RENDER_FORCE_MODE_ENABLE,

	//////////////////////////////////////////////////////////////////////////

	HAIR_RENDER_DUMMY
};

#endif // VPHAIRTRACE_H__
