#ifndef VPOLDGI_H__
#define VPOLDGI_H__

enum
{
	VPOLDGI_MAXDIFFUSEDEPTH					= 5102,
	VPOLDGI_MONTECARLOSAMPLES				= 5104,
	VPOLDGI_ACCURACY								= 5105,
	VPOLDGI_MAXRESOLUTION						= 5106,
	VPOLDGI_STRENGTH								= 5108,
	VPOLDGI_MINRESOLUTION						= 5117,
	VPOLDGI_RECOMPUTE								= 5119,
		VPOLDGI_RECOMPUTE_FIRSTTIME				= 0,
		VPOLDGI_RECOMPUTE_ALWAYS					= 1,
		VPOLDGI_RECOMPUTE_NEVER						= 2,
	VPOLDGI_SAVESOLUTION						= 5120,
	VPOLDGI_PREPASS									= 5123,
		VPOLDGI_PREPASS_NONE							= 0,
		VPOLDGI_PREPASS_1									= 1,
		VPOLDGI_PREPASS_2									= 2,
		VPOLDGI_PREPASS_3									= 3,
		VPOLDGI_PREPASS_4									= 4,
		VPOLDGI_PREPASS_5									= 5,
		VPOLDGI_PREPASS_10								= 6,
	VPOLDGI_STOCHASTICDEPTH					= 5127,
	VPOLDGI_STOCHASTICSAMPLES				= 5128,
	VPOLDGI_STOCHASTICACCURACY			= 5129,
	VPOLDGI_LOCKTOSCREEN						= 5130,
	VPOLDGI_MODE										= 5131,
		VPOLDGI_MODE_STANDARD							= 0,
		VPOLDGI_MODE_STOCHASTIC						= 1,
		VPOLDGI_MODE_CAMERAANIMATION			= 2,
		VPOLDGI_MODE_OBJECTANIMATION    	= 3,
	VPOLDGI_SHOWDIFFUSEILLUMINATION	= 5602
};

#endif // VPOLDGI_H__
