#ifndef XHAIR_H__
#define XHAIR_H__

enum
{
	HAIR_SHADER_COLOR = 1000,
	HAIR_SHADER_SPECULAR_STRENGTH,
	HAIR_SHADER_DIFFUSE_STRENGTH,
	HAIR_SHADER_SPECULAR_POWER,
	HAIR_SHADER_SHADOW,
	HAIR_SHADER_ROUGHNESS_VAR,
	HAIR_SHADER_REFLECT,
	HAIR_SHADER_TRANSMIT,
	HAIR_SHADER_ISPECULAR_STRENGTH,
	HAIR_SHADER_ISPECULAR_POWER,
	HAIR_SHADER_ROUGHNESS,
	HAIR_SHADER_GLINT_STRENGTH,
	HAIR_SHADER_GLINT_ANGLE,
	HAIR_SHADER_GLINT_POWER,
	HAIR_SHADER_SURFACE_ROUGHNESS,

	HAIR_SHADER_DIFFUSE_SHADER,
	HAIR_SHADER_SPECULAR_SHADER,
	HAIR_SHADER_ISPECULAR_SHADER,
	HAIR_SHADER_GLINT_SHADER,

	HAIR_SHADER_ALPHA_DEPTH,
	HAIR_SHADER_SHADOW_TRANSPARENCY,
	HAIR_SHADER_FROM_MATERIAL,

	HAIR_SHADER_GROUP_SPECULAR = 2000,
	HAIR_SHADER_GROUP_ISPECULAR,
	HAIR_SHADER_GROUP_GLINT,
	HAIR_SHADER_GROUP_ILLUMINATION,

	//////////////////////////////////////////////////////////////////////////

	HAIR_SHADER_DUMMY
};

#endif // XHAIR_H__
