#ifndef XMG_COLOR_H__
#define XMG_COLOR_H__

enum
{
	MGCOLORSHADER_MODE						= 1000,
	MGCOLORSHADER_MODE_COLOR			= 0,
	MGCOLORSHADER_MODE_UVW,
	MGCOLORSHADER_MODE_WEIGHT,
	MGCOLORSHADER_MODE_TIME,
	MGCOLORSHADER_MODE_LINEAR,
	MGCOLORSHADER_MODE_SIZE,
	MGCOLORSHADER_MODE_ROTATION,
	MGCOLORSHADER_MODE_DELTA,
	MGCOLORSHADER_MODE_INDEXRATIO,
	MGCOLORSHADER_INVERT					= 1001,
	MGCOLORSHADER_SPLINE					= 1002
};
#endif // XMG_COLOR_H__
