#ifndef XMG_MULTI_H__
#define XMG_MULTI_H__

enum
{
	MGMULTISHADER_LAYERCOUNT			= 1000,
	MGMULTISHADER_MODE						= 1001,
	MGMULTISHADER_MODE_INDEXRATIO			= 0,
	MGMULTISHADER_MODE_COLORBRIGHT		= 1,
	MGMULTISHADER_MODE_COLORX					= 2,
	MGMULTISHADER_MODE_COLORY					= 3,
	MGMULTISHADER_MODE_COLORZ					= 4,
	MGMULTISHADER_MODE_AVERAGECOL			= 5,
	MGMULTISHADER_MODE_AVERAGECOL_HSV	= 6,
	MGMULTISHADER_ADD							= 1002,
	MGMULTISHADER_SUB							= 1003,
	MGMULTISHADER_CASTMOVIE				= 1004,
	MGMULTISHADER_CLEAR						= 1005,
	MGMULTISHADER_ADDFOLDER				= 1006,
	MGMULTISHADER_BLENDCOLOR			= 1007,
	MGMULTISHADER_BLENDCOLOR_MODE	= 1008,
		MGMULTISHADER_BLENDCOLOR_MODE_MULTIPLY		= 1,
		MGMULTISHADER_BLENDCOLOR_MODE_OVERLAY			= 2,
		MGMULTISHADER_BLENDCOLOR_MODE_COLOR				= 3,
	MGMULTISHADER_GROUPSHADER			= 1020,

	MGMULTISHADER_LAYER_LINK							= 1050,
	MGMULTISHADER_LAYER_DEL								= 2050,
	MGMULTISHADER_LAYER_UP								= 3050,
	MGMULTISHADER_LAYER_DWN								= 4050,
	MGMULTISHADER_LAYER_SEPARATOR					= 5050,
	MGMULTISHADER_LAYER_GROUP							= 6050,
	MGMULTISHADER_LAYER_GROUP_SHADERLINK	= 7050,
	MGMULTISHADER_LAYER_GROUP_BUTTONS			= 8050,
	MGMULTISHADER_LAYER_ACTIVE						= 9050
};

#endif // XMG_MULTI_H__
