#ifndef COMPOSITING3DTAG_H__
#define COMPOSITING3DTAG_H__

enum
{
	COMP3DTAG_CHILDREN					= 1001, // Bool
	COMP3DTAG_SOLID							= 1002, // Bool
	COMP3DTAG_SIZEX							= 1003,  // Real
	COMP3DTAG_SIZEY							= 1004,  // Real
	COMP3DTAG_MIDPOINT					= 1005,  // LONG
		COMP3DTAG_MIDTL							= 1,
		COMP3DTAG_MIDTR							= 2,
		COMP3DTAG_MIDCTR						= 3,
		COMP3DTAG_MIDBL							= 4,
		COMP3DTAG_MIDBR							= 5,
	COMP3DTAG_COLOR							= 1006,
	COMP3DTAG_MOGRAPH						= 1007,
	COMP3DTAG_ORIENTATION				= 1008,
	COMP3DTAG_PX							= 1,
	COMP3DTAG_MX							= 2,
	COMP3DTAG_PY							= 3,
	COMP3DTAG_MY							= 4,
	COMP3DTAG_PZ							= 5,
	COMP3DTAG_MZ							= 6,
	COMP3DTAG_CACHE					= 1009, // Bool
};

#endif // COMPOSITING3DTAG_H__



