#ifndef DXREFMANAGER_H__
#define DXREFMANAGER_H__

enum
{
	ID_CA_XREFMANAGER_GROUP_REFS = 5000,
	ID_CA_XREFMANAGER_GROUP_FILE,

	ID_CA_XREFMANAGER_REF_LIST = 1500,
	ID_CA_XREFMANAGER_NAME,
	ID_CA_XREFMANAGER_RESOLVED_NAME,
	ID_CA_XREFMANAGER_NAMESPACE,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_XREFMANAGER_DUMMY
};

#endif // DXREFMANAGER_H__
