#ifndef DXREFADD_H__
#define DXREFADD_H__

enum
{
	ID_CA_XREFADD_GROUP_OPTIONS = 5000,
	ID_CA_XREFADD_GROUP_MODIFY,
	ID_CA_XREFADD_GROUP_IMPORT,
	ID_CA_XREFADD_GROUP_FILE,
	ID_CA_XREFADD_PIVOT_GROUP,

	ID_CA_XREFADD_ENCAPSULATED = 1500,
	ID_CA_XREFADD_RELATIVE,
	ID_CA_XREFADD_NAMESPACE,
	ID_CA_XREFADD_PREFIX,
	ID_CA_XREFADD_NAMESPACE_AUTO,
	ID_CA_XREFADD_NAMESPACE_SEP,
	ID_CA_XREFADD_INCREMENTAL,
	ID_CA_XREFADD_GENERATOR,

	ID_CA_XREFADD_HIERARCHY = 2000,
	ID_CA_XREFADD_PARAMETERS,
	ID_CA_XREFADD_USERDATA,
	ID_CA_XREFADD_PSR,
	ID_CA_XREFADD_POINTS,

	ID_CA_XREFADD_PARAMETERS_MODE = 2500,
	ID_CA_XREFADD_USERDATA_MODE,
	ID_CA_XREFADD_PSR_MODE,
	ID_CA_XREFADD_POINTS_MODE,

	ID_CA_XREFADD_ANIM = 3000,
	ID_CA_XREFADD_MATERIALS,
	ID_CA_XREFADD_POINTCACHE,
	ID_CA_XREFADD_ANIM_OFFSET,
	ID_CA_XREFADD_ANIM_SCALE,
	ID_CA_XREFADD_ANIM_FRAME,

	ID_CA_XREFADD_PIVOT_POS = 3500,
	ID_CA_XREFADD_PIVOT_SCL,
	ID_CA_XREFADD_PIVOT_ROT,
	ID_CA_XREFADD_PIVOT,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_XREFADD_NAMESPACE_NONE = 0,
	ID_CA_XREFADD_NAMESPACE_REFNAME = 2,
	ID_CA_XREFADD_NAMESPACE_CUSTOM,

	ID_CA_XREFADD_PSR_MODE_ABS = 0,
	ID_CA_XREFADD_PSR_MODE_REL,

	ID_CA_XREFADD_FLAGS = 9000,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_XREFADD_DUMMY
};

#endif // DXREFADD_H__
