#ifndef FCONE_H__
#define FCONE_H__

enum
{
	// Falloff controls
	FIELD_CONE_SIZE_DEPRECATED = 1000,	// Float
	FIELD_CONE_CLIP = 1002,	// Boolean
	FIELD_CONE_SLICE_DEPRECATED = 1004,	// Float
	FIELD_CONE_DIRECTION = 1005,	// Int Cycle
	FIELD_CONE_RADIUS = 1006,
	FIELD_CONE_HEIGHT = 1007,

	FIELD_CONE_DIRECTION_XP = 0,
	FIELD_CONE_DIRECTION_XN = 1,
	FIELD_CONE_DIRECTION_YP = 2,
	FIELD_CONE_DIRECTION_YN = 3,
	FIELD_CONE_DIRECTION_ZP = 4,
	FIELD_CONE_DIRECTION_ZN = 5
};
#endif	// FCONE_H__
