#ifndef FLRANGEMAP_H__
#define FLRANGEMAP_H__

enum
{
	FIELDLAYER_RANGEMAP_MININ = 1000,		// FLOAT
	FIELDLAYER_RANGEMAP_MINOUT = 1001,		// FLOAT
	FIELDLAYER_RANGEMAP_MAXIN = 1002,		// FLOAT
	FIELDLAYER_RANGEMAP_MAXOUT = 1003,		// FLOAT

	FIELDLAYER_RANGEMAP_DUMMY
};
#endif	// #FLRANGEMAP_H__

