#ifndef FOBJIMPORT_H__
#define FOBJIMPORT_H__

enum
{
	OBJIMPORTFILTER_GROUP					= 999,
	OBJIMPORTFILTER_SCALE		 			= 2000,
	OBJIMPORTFILTER_IMPORTNORMALS	= 2001,
	OBJIMPORTFILTER_OPTIMIZE			= 2002
};

#endif // FOBJIMPORT_H__
