#ifndef FRADIAL_H__
#define FRADIAL_H__

enum
{
	// Falloff controls
	FIELD_RADIAL_STARTANGLE = 1000,		// Float
	FIELD_RADIAL_ENDANGLE = 1001,		// Float
	FIELD_RADIAL_STARTBLEND = 1002,		// Float
	FIELD_RADIAL_ENDBLEND = 1003,		// Float
	FIELD_RADIAL_ITERATIONS = 1004,		// Float
	FIELD_RADIAL_AXIS = 1005,		// Int Cycle
	FIELD_RADIAL_OFFSET = 1006,		// Float
	FIELD_RADIAL_OFFSETFIELD = 1007,		// FieldList
	FIELD_RADIAL_GROUP_OFFSET = 1008,		// Group
	FIELD_RADIAL_CLIP = 1009,		// Bool

	FIELD_RADIAL_AXIS_X = 0,
	FIELD_RADIAL_AXIS_Y = 1,
	FIELD_RADIAL_AXIS_Z = 2,
};
#endif	// FRADIAL_H__
