#ifndef GVMOGRAPH_SAMPLEEFFECTOR_H__
#define GVMOGRAPH_SAMPLEEFFECTOR_H__

enum
{
	GV_MG_SAMPLEEFFECTOR_IOBJECT	= 1000,
	GV_MG_SAMPLEEFFECTOR_IPOSITION = 1001,
	GV_MG_SAMPLEEFFECTOR_ISCALE		= 1002,
	GV_MG_SAMPLEEFFECTOR_IROTATION = 1003,
	GV_MG_SAMPLEEFFECTOR_ICOLOR		= 1004,
	GV_MG_SAMPLEEFFECTOR_IUV			= 1005,
	GV_MG_SAMPLEEFFECTOR_IWEIGHT	= 1006,
	GV_MG_SAMPLEEFFECTOR_ITIME		= 1007,
	GV_MG_SAMPLEEFFECTOR_IMATRIX	= 1008,
	GV_MG_SAMPLEEFFECTOR_RESULT		= 2000,
	GV_MG_SAMPLEEFFECTOR_OMATRIX	= 2001,
	GV_MG_SAMPLEEFFECTOR_OCOLOR		= 2002,
	GV_MG_SAMPLEEFFECTOR_OUV			= 2003,
	GV_MG_SAMPLEEFFECTOR_OVISIBLE = 2004,
	GV_MG_SAMPLEEFFECTOR_OWEIGHT	= 2005,
	GV_MG_SAMPLEEFFECTOR_OTIME		= 2006,
	GV_MG_SAMPLEEFFECTOR_OSTRENGTH = 2007
};
#endif // GVMOGRAPH_SAMPLEEFFECTOR_H__
