#ifndef GVMOGRAPH_FALLOFF_H__
#define GVMOGRAPH_FALLOFF_H__

enum
{
	GV_MG_FALLOFF_POSITION			 = 1000,	// INPUT VECTOR
	GV_MG_FALLOFF_VALUE					 = 1001,	// OUTPUT FLOAT
	GV_MG_FALLOFF_MATRIX				 = 1002,	// INPUT MATRIX
	GV_MG_FALLOFF_NORMAL				 = 1003,	// INPUT VECTOR
	GV_MG_FALLOFF_UVW						 = 1004,	// INPUT VECTOR
	GV_MG_FALLOFF_COLOR					 = 1005,	// OUTPUT VECTOR
	GV_MG_FALLOFF_DIRECTION			 = 1006,	// OUTPUT VECTOR
	GV_MG_FALLOFF_ITERATIONCOUNT = 1007,	// INPUT INTEGER
	GV_MG_FALLOFF_ITERATION			 = 1008,	// INPUT INTEGER
	GV_MG_FALLOFF_ROTATION			 = 1009,	// OUTPUT VECTOR
	GV_MG_FALLOFF_PIVOT					 = 1010		// OUTPUT VECTOR
};
#endif // GVMOGRAPH_FALLOFF_H__
