#ifndef GVMOGRAPH_SELECTION_H__
#define GVMOGRAPH_SELECTION_H__

enum
{
	GV_MG_SELECTION_IOBJECT	= 1000,
	GV_MG_SELECTION_ISELECT	= 1001,
	GV_MG_SELECTION_INDEX		= 1002,
	GV_MG_SELECTION_OSELECT	= 1003
};
#endif // GVMOGRAPH_SELECTION_H__
