#ifndef MGGRIDARRAY_H__
#define MGGRIDARRAY_H__

enum
{
	MG_GRID_RESOLUTION	= 1200,
	MG_GRID_SIZE				= 1201,
	MG_GRID_INSIDE			= 1202,
	MG_GRID_TYPE				= 1203,
		MG_GRID_TYPE_CUBIC	= 0,
		MG_GRID_TYPE_SPHERE = 1,
		MG_GRID_TYPE_TUBE		= 2,
		MG_GRID_TYPE_OBJECT = 3,
	MG_GRID_MODE				= 1204,
		MG_GRID_MODE_PERSTEP	= 0,
		MG_GRID_MODE_ENDPOINT	= 1,
	MG_GRID_OBJECT			= 1205,
	MG_GRID_UVAXIS			= 5508,
		MG_GRID_UVAXIS_XP		= 0,
		MG_GRID_UVAXIS_XN,
		MG_GRID_UVAXIS_YP,
		MG_GRID_UVAXIS_YN,
		MG_GRID_UVAXIS_ZP,
		MG_GRID_UVAXIS_ZN
};
#endif // MGGRIDARRAY_H__
