#ifndef OBASEDEFORM_H__
#define OBASEDEFORM_H__

enum
{
	DEFORMOBJECT_SIZE			 = 1000, // Vector
	DEFORMOBJECT_MODE			 = 1001, // LONG 0=limited, 1=half limited, 2=unlimited
		DEFORMOBJECT_MODE_LIMIT 		= 1,
		DEFORMOBJECT_MODE_BOX   		= 0,
		DEFORMOBJECT_MODE_UNLIMITED	= 2,
	DEFORMOBJECT_STRENGTH  = 1002, // Real
	DEFORMOBJECT_ANGLE     = 1003, // Real
	DEFORMOBJECT_CURVATURE = 1004, // Real
	DEFORMOBJECT_FILLET    = 1005, // Bool
	DEFORMOBJECT_FITTOPARENT = 100001		// Button
};

#endif // OBASEDEFORM_H__
