#ifndef OBEVEL_H__
#define OBEVEL_H__

enum
{
	O_BEVEL_GROUP_MODE									=	2000,
	O_BEVEL_GROUP_OPTION								= 1000,
	O_BEVEL_GROUP_POLYGON								= 5100,
	O_BEVEL_GROUP_SHAPING								= 1200,
	O_BEVEL_GROUP_TOPOLOGY							= 1300,

	O_BEVEL_MASTER_MODE									= 1100,
		O_BEVEL_MASTER_MODE_CHAMFER				= 0,
		O_BEVEL_MASTER_MODE_SOLID					= 1,

	O_BEVEL_OFFSET_MODE									= 1001,
		O_BEVEL_OFFSET_MODE_FIXED					= 0,
		O_BEVEL_OFFSET_MODE_RADIAL				= 1,
		O_BEVEL_OFFSET_MODE_PROPORTIONAL	= 2,

	O_BEVEL_RADIUS											= 1002,
	O_BEVEL_SUB													= 1003,
	O_BEVEL_DEPTH												= 1004,
	O_BEVEL_LIMIT												= 1005,

	O_BEVEL_EXTRUSION										= 1101,
	O_BEVEL_POLY_ANGLE									= 1102,
	O_BEVEL_GROUP												= 1103,

	O_BEVEL_SHAPING_MODE								= 1201,
		O_BEVEL_SHAPING_MODE_ROUND				= 0,
		O_BEVEL_SHAPING_MODE_USER					= 1,
		O_BEVEL_SHAPING_MODE_PROFILE			= 2,

	O_BEVEL_SHAPING_TENSION							= 1202,
	O_BEVEL_SHAPING_SYMMETRY						= 1203,
	O_BEVELL_SHAPING_CONSTANT						= 1204,
	O_BEVEL_SHAPING_SPLINE							= 1205,
	O_BEVEL_SHAPING_SPLINE_LINK					= 1206,

	O_BEVEL_SHAPING_SPLINE_PLANE				= 1207,
		O_BEVEL_SHAPING_SPLINE_PLANE_XY		= 0,
		O_BEVEL_SHAPING_SPLINE_PLANE_XZ		= 1,
		O_BEVEL_SHAPING_SPLINE_PLANE_ZY		= 2,

	O_BEVEL_SHAPING_EXTR								= 1208,

	O_BEVEL_MITERING										= 1301,
		O_BEVEL_MITERING_DEFAULT					= 0,
		O_BEVEL_MITERING_UNIFORM					= 1,
		O_BEVEL_MITERING_RADIAL						= 3,
		O_BEVEL_MITERING_PATCH						= 4,

	O_BEVEL_CORNER_ENDING								= 1302,
		O_BEVEL_CORNER_ENDING_DEFAULT			= 0,
		O_BEVEL_CORNER_ENDING_EXTEND			= 1,
		O_BEVEL_CORNER_ENDING_INSET				= 2,

	O_BEVEL_PROUNDING_TYPE							= 1303,
		O_BEVEL_PROUNDING_TYPE_FLAT				= 0,
		O_BEVEL_PROUNDING_TYPE_FULL				= 1,
		O_BEVEL_PROUNDING_TYPE_CONVEX			= 2,

	O_BEVEL_CORNER_NGON									= 1304,
	O_BEVEL_ROUNDING_NGON								= 1305,

	O_BEVEL_SELECTION_PHONG_BREAK				= 1306,
	O_BEVEL_SELECTION_PHONG_BREAK_M			= 1307,

	O_BEVEL_MODE_COMPONENT_TYPE					= 2001,
		O_BEVEL_MODE_COMPONENT_TYPE_POINT		= 0,
		O_BEVEL_MODE_COMPONENT_TYPE_EDGE		= 1,
		O_BEVEL_MODE_COMPONENT_TYPE_POLYGON = 2,

	O_BEVEL_MODE_SELECTION_TYPE					= 2002,
		O_BEVEL_MODE_SELECTION_CURRENT			= 0,
		O_BEVEL_MODE_SELECTION_TAG					= 1,
		O_BEVEL_MODE_SELECTION_ANGLE				= 2,

	O_BEVEL_RESTRICTION_GROUP							= 2003,
	O_BEVEL_MODE_SELECTION_SELTAG					= 2006,
	O_BEVEL_MODE_SELECTION_ANGLE_VAL			= 2004,
	O_BEVEL_MODE_SELECTION_ANGLE_USE			= 2005,
	O_BEVEL_RESTRICTION_ADD								= 3000,
	O_BEVEL_RESTRICTION_REMOVE						= 3001,
	O_BEVEL_RESTRICTION_COUNT							= 3002,
	O_BEVEL_RESTRICTION_START							= 2007,
	O_BEVEL_RESTRICTION_MAX								= 2100,
	//	O_BEVEL_USE_RESTRICTION							= 2008,
};

#endif // OBEVEL_H__

