#ifndef OCAMUSCLE_H__
#define OCAMUSCLE_H__

enum
{
	ID_CA_MUSCLE_OBJECT_ANCHORS_GROUP = 5000,
	ID_CA_MUSCLE_OBJECT_ANCHORS_LIST_GROUP,
	ID_CA_MUSCLE_OBJECT_GEOM_GROUP,
	ID_CA_MUSCLE_OBJECT_DYNAMICS_GROUP,
	ID_CA_MUSCLE_OBJECT_DYNAMICS_ADV_GROUP,
	ID_CA_MUSCLE_OBJECT_DEFORM_GROUP,
	ID_CA_MUSCLE_OBJECT_DYNAMICS_FORCES_GROUP,
	ID_CA_MUSCLE_OBJECT_TRANSITION_GROUP,

	ID_CA_MUSCLE_OBJECT_SEGMENTS_COUNT = 1002,
	ID_CA_MUSCLE_OBJECT_RADIAL_COUNT,
	ID_CA_MUSCLE_OBJECT_SEGMENTS_RES,
	ID_CA_MUSCLE_OBJECT_RADIAL_RES,
	ID_CA_MUSCLE_OBJECT_ANCHORS_ADD,
	ID_CA_MUSCLE_OBJECT_ANCHORS_REMOVE,
	ID_CA_MUSCLE_OBJECT_MODE,
	ID_CA_MUSCLE_OBJECT_STATE,
	ID_CA_MUSCLE_OBJECT_SHAPE_RELAX,
	ID_CA_MUSCLE_OBJECT_SHAPE_COMPRESS,
	ID_CA_MUSCLE_OBJECT_SHAPE_EXTEND,
	ID_CA_MUSCLE_OBJECT_DYNAMICS,
	ID_CA_MUSCLE_OBJECT_DRAG,
	ID_CA_MUSCLE_OBJECT_SPRINGS,
	ID_CA_MUSCLE_OBJECT_STIFFNESS,
	ID_CA_MUSCLE_OBJECT_STRENGTH,
	ID_CA_MUSCLE_OBJECT_GRAVITY,
	ID_CA_MUSCLE_OBJECT_ITERATIONS,
	ID_CA_MUSCLE_OBJECT_STRUCTUAL_STIFFNESS,
	ID_CA_MUSCLE_OBJECT_RELAX_LENGTH,
	ID_CA_MUSCLE_OBJECT_COMPRESS_LENGTH,
	ID_CA_MUSCLE_OBJECT_EXTEND_LENGTH,
	ID_CA_MUSCLE_OBJECT_STATE_SET,
	ID_CA_MUSCLE_OBJECT_SUBD,
	ID_CA_MUSCLE_OBJECT_TYPE,
	ID_CA_MUSCLE_OBJECT_AUTO_COMPRESS,
	ID_CA_MUSCLE_OBJECT_AUTO_EXTEND,
	ID_CA_MUSCLE_OBJECT_SUBD_CALC,
	ID_CA_MUSCLE_OBJECT_DEFORM,
	ID_CA_MUSCLE_OBJECT_DEFORM_DIRECTION_LINK,
	ID_CA_MUSCLE_OBJECT_STIFFNESS_CURVE,
	ID_CA_MUSCLE_OBJECT_DELETED_1,
	ID_CA_MUSCLE_OBJECT_DELETED_2,
	ID_CA_MUSCLE_OBJECT_DELETED_3,
	ID_CA_MUSCLE_OBJECT_DELETED_4,
	ID_CA_MUSCLE_OBJECT_VOLUME_STIFFNESS,
	ID_CA_MUSCLE_OBJECT_FORCES,
	ID_CA_MUSCLE_OBJECT_FATOFFSET,
	ID_CA_MUSCLE_OBJECT_SHAPE_TRANSITION,
	ID_CA_MUSCLE_OBJECT_DYNAMICS_FRAME,
	ID_CA_MUSCLE_OBJECT_AUTO_ALIGN,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA = 20000,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_DUMMY_CONTAINER,

	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_COUNT = 1000,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_BEGIN = 10000,

	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_LINK = 1000,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_DELETD_1,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_SELECT,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_DIRTY,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_MATRIX,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_OFFSET,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_MARK,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_INDEX,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_STOFFSET,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_ROTATION,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_RESET,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_SET,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_CREATE,
	ID_CA_MUSCLE_OBJECT_ANCHORS_DATA_GMATRIX,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_MUSCLE_OBJECT_MODE_EDIT = 0,
	ID_CA_MUSCLE_OBJECT_MODE_ANIMATE,

	ID_CA_MUSCLE_OBJECT_STATE_RELAX = 0,
	ID_CA_MUSCLE_OBJECT_STATE_COMPRESSED,
	ID_CA_MUSCLE_OBJECT_STATE_EXTENDED,

	ID_CA_MUSCLE_OBJECT_TYPE_LINEAR = 0,
	ID_CA_MUSCLE_OBJECT_TYPE_CUBIC = 1,
	ID_CA_MUSCLE_OBJECT_TYPE_AKIMA = 2,
	ID_CA_MUSCLE_OBJECT_TYPE_BSPLINE = 3,

	ID_CA_MUSCLE_OBJECT_DEFORM_RADIAL = 0,
	ID_CA_MUSCLE_OBJECT_DEFORM_NORMAL,
	ID_CA_MUSCLE_OBJECT_DEFORM_DIRECTION,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_MUSCLE_OBJECT_DUMMY
};

#endif // OCAMUSCLE_H__
