#ifndef OCAMORPHDEFORMER_H__
#define OCAMORPHDEFORMER_H__

enum
{
	ID_CA_MORPH_DEFORMER_OBJECT_TARGETS_GROUP = 2000,

	ID_CA_MORPH_DEFORMER_OBJECT_TAG = 1000,
	ID_CA_MORPH_DEFORMER_OBJECT_STRENGTH,
	ID_CA_MORPH_DEFORMER_OBJECT_APPLY_BASEPOSE,

	ID_CA_MORPH_DEFORMER_OBJECT_ANIMATE_DATA = 4000,	//ID_CA_POSE_ANIMATE_DATA

	//////////////////////////////////////////////////////////////////////////

	ID_CA_MORPH_DEFORMER_OBJECT_DUMMY
};

#endif // OCAMORPHDEFORMER_H__
