#ifndef OECOFFEE_H__
#define OECOFFEE_H__

enum
{
	OECOFFEE_STRING							=	1100,
	OECOFFEE_MODE								=	1102,
		OECOFFEE_MODE_PARAMETERS		= 0,
		OECOFFEE_MODE_FULLCONTROL		=	1,
	OECOFFEEDUMMY
};
#endif // OECOFFEE_H__
