#ifndef OFALLOFF_OBJECT_H__
#define OFALLOFF_OBJECT_H__

enum
{
	//Falloff controls
	FALLOFF_OBJECTMODE_LINK						=	5106,
	FALLOFF_OBJECTMODE_SIZE						=	5107,
	FALLOFF_OBJECTMODE_SPLINEDETAIL		=	5108
};
#endif // OFALLOFF_OBJECT_H__
