#ifndef OLATHELEGACY_H__
#define OLATHELEGACY_H__

enum
{
	LATHEOBJECT_ISOPARM			= 1000,
	LATHEOBJECT_SUB					= 1001,
	LATHEOBJECT_MOVE				= 1002,
	LATHEOBJECT_SCALE				= 1003,
	LATHEOBJECT_ROTATE			= 1004,
	LATHEOBJECT_FLIPNORMALS	= 1005
};

#endif // OLATHELEGACY_H__
