#ifndef OMAPPEDCURVE_H__
#define OMAPPEDCURVE_H__

enum
{
	MAPPEDCURVE_TYPE						= 1001,
		MAPPEDCURVE_TYPE_UNKNOWN		= 0,
		MAPPEDCURVE_TYPE_STANDARD  		= 1,
		MAPPEDCURVE_TYPE_SEGMENT		= 2,

	ID_MAPPEDCURVEPROPERTIES				= 1090
};

#endif // OMAPPEDCURVE_H__
