#ifndef ONULL_H__
#define ONULL_H__

enum
{
	NULLOBJECT_DISPLAY			= 1000,
		NULLOBJECT_DISPLAY_DOT				= 0,
		NULLOBJECT_DISPLAY_POINT			= 1,
		NULLOBJECT_DISPLAY_CIRCLE			= 2,
		NULLOBJECT_DISPLAY_RECTANGLE	= 3,
		NULLOBJECT_DISPLAY_DIAMOND		= 4,
		NULLOBJECT_DISPLAY_TRIANGLE		= 5,
		NULLOBJECT_DISPLAY_PENTAGON		= 6,
		NULLOBJECT_DISPLAY_HEXAGON		= 7,
		NULLOBJECT_DISPLAY_OCTAGON		= 8,
		NULLOBJECT_DISPLAY_STAR				= 9,
		NULLOBJECT_DISPLAY_AXIS				= 10,
		NULLOBJECT_DISPLAY_CUBE				= 11,
		NULLOBJECT_DISPLAY_PYRAMID		= 12,
		NULLOBJECT_DISPLAY_SPHERE		= 13,
		NULLOBJECT_DISPLAY_NONE				= 14,

	NULLOBJECT_RADIUS				= 1001,
	NULLOBJECT_ASPECTRATIO	= 1002,
	NULLOBJECT_ORIENTATION	= 1003,
		NULLOBJECT_ORIENTATION_SCREEN	= 0,
		NULLOBJECT_ORIENTATION_XY			= 1,
		NULLOBJECT_ORIENTATION_ZY			= 2,
		NULLOBJECT_ORIENTATION_XZ			= 3,

	NULLOBJECT_ICONCOL__DEPRECATED__ = 1004,

	//////////////////////////////////////////////////////////////////////////

	NULLOBJECT_DUMMY
};

#endif // ONULL_H__
