#ifndef OPARTICLEBASE_H__
#define OPARTICLEBASE_H__

enum
{
	PARTICLEBASE_SHAPE_DIM = 1001,

	PARTICLEBASE_SHAPE = 5000,
	PARTICLEBASE_SHAPE_SWEEP,
	PARTICLEBASE_SHAPE_RADIUS,
	PARTICLEBASE_SHAPE_EXCLUSION,
	PARTICLEBASE_SHAPE_OFF,
	PARTICLEBASE_FALLOFF_ATTENUATION,
	PARTICLEBASE_FALLOFF_I_DIST,
	PARTICLEBASE_FALLOFF_O_DIST,
	PARTICLEBASE_MODE,

	PARTICLEBASE_MODE_ACCELERATION = 0,
	PARTICLEBASE_MODE_FORCE = 1,
	PARTICLEBASE_MODE_AERODYNAMICS = 2,

	PARTICLEBASE_SHAPE_GROUP = 6000,
	PARTICLEBASE_FALLOFF_GROUP,

	//////////////////////////////////////////////////////////////////////////

	PARTICLEBASE_SHAPE_UNLIMITED = 0,
	PARTICLEBASE_SHAPE_CUBE,
	PARTICLEBASE_SHAPE_SPHERE,
	PARTICLEBASE_SHAPE_CYLINDER,
	PARTICLEBASE_SHAPE_CONE,
	PARTICLEBASE_SHAPE_TORUS,

	PARTICLEBASE_FALLOFF_NONE = 0,
	PARTICLEBASE_FALLOFF_LIN,
	PARTICLEBASE_FALLOFF_INV,
	PARTICLEBASE_FALLOFF_INVS,
	PARTICLEBASE_FALLOFF_INVC,
	PARTICLEBASE_FALLOFF_STEP,

	//////////////////////////////////////////////////////////////////////////

	PARTICLEBASE_DUMMY
};

#endif // OPARTICLEBASE_H__
