#ifndef OSPLINETOVOLUME_H__
#define OSPLINETOVOLUME_H__

enum
{
	ID_SPLINETOVOLUME_GRID_SIZE = 6000,
	ID_SPLINETOVOLUME_HALF_BAND = 6001,
	ID_SPLINETOVOLUME_RADIUS = 6002,
	ID_SPLINETOVOLUME_DENSITY = 6003,
};

#endif // OSPLINETOVOLUME_H__