#ifndef _GoZ_PREFERENCES_
#define _GoZ_PREFERENCES_


enum {
		GOZ_SCALE_FACTOR_EXPORT = 1000,
		GOZ_SCALE_FACTOR_IMPORT,

		GOZ_IMPORT_GROUP,
		GOZ_IMPORT_COLOR_MAP,
		GOZ_IMPORT_NORMAL_MAP,
		GOZ_IMPORT_DISPLACEMENT_MAP,
		GOZ_IMPORT_UVW,
		GOZ_IMPORT_POLYPAINT,
		GOZ_IMPORT_POLYGROUP,

		GOZ_EXPORT_GROUP,
		GOZ_EXPORT_COLOR_MAP,
		GOZ_EXPORT_NORMAL_MAP,
		GOZ_EXPORT_DISPLACEMENT_MAP,
		GOZ_EXPORT_UVW,
		GOZ_EXPORT_POLYPAINT,
		GOZ_EXPORT_POLYGROUP,
		PREFS_GOZ_GROUP,
};


#endif