#ifndef TCAGEOMCACHE_H__
#define TCAGEOMCACHE_H__

enum
{
	ID_CA_GEOMCACHE_TAG_ENABLE = 2000,
	ID_CA_GEOMCACHE_TAG_CALCULATE,
	ID_CA_GEOMCACHE_TAG_COMPRESSED,
	ID_CA_GEOMCACHE_TAG_DELETE,
	ID_CA_GEOMCACHE_TAG_INFO1,
	ID_CA_GEOMCACHE_TAG_INFO2,
	ID_CA_GEOMCACHE_TAG_CACHE_LOAD,
	ID_CA_GEOMCACHE_TAG_CACHE_SAVE,
	ID_CA_GEOMCACHE_TAG_CACHE_LIMIT,
	ID_CA_GEOMCACHE_TAG_TEXT_LIMIT,
	ID_CA_GEOMCACHE_TAG_STORE,
	ID_CA_GEOMCACHE_TAG_RESTORE,
	ID_CA_GEOMCACHE_TAG_DEFORMER,
	ID_CA_GEOMCACHE_TAG_UPDATE,
	ID_CA_GEOMCACHE_TAG_CACHE_AUTOTIME,
	ID_CA_GEOMCACHE_TAG_CACHE_START,
	ID_CA_GEOMCACHE_TAG_CACHE_STOP,
	ID_CA_GEOMCACHE_TAG_CACHE_OFFSET,
	ID_CA_GEOMCACHE_TAG_CACHE_TIMESCALE,
	ID_CA_GEOMCACHE_TAG_CACHE_STRENGTH,
	ID_CA_GEOMCACHE_TAG_CACHE_LOOP,
	ID_CA_GEOMCACHE_TAG_PSR,
	ID_CA_GEOMCACHE_TAG_CACHE_LOOP_BLEND,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_GEOMCACHE_TAG_DUMMY
};

#endif // TCAGEOMCACHE_H__
