#ifndef TCAIKSPLINE_H__
#define TCAIKSPLINE_H__

enum
{
	ID_CA_IKSPLINE_HANDLE_GROUP = 5000,
	ID_CA_IKSPLINE_HANDLE_LINKS_GROUP,
	ID_CA_IKSPLINE_DISPLAY_GROUP,

	ID_CA_IKSPLINE_TAG_SPLINE = 2000,
	ID_CA_IKSPLINE_TAG_DUMMY_1,
	ID_CA_IKSPLINE_TAG_END,
	ID_CA_IKSPLINE_TAG_TYPE,
	ID_CA_IKSPLINE_HANDLE_ADD,
	ID_CA_IKSPLINE_HANDLE_REMOVE,
	ID_CA_IKSPLINE_HANDLE_INDEX,
	ID_CA_IKSPLINE_HANDLE_LINK,
	ID_CA_IKSPLINE_HANDLE_TWIST,
	ID_CA_IKSPLINE_TAG_TWIST,
	ID_CA_IKSPLINE_TAG_STRENGTH,
	ID_CA_IKSPLINE_HANDLE_LENGTH,
	ID_CA_IKSPLINE_DISPLAY_HANDLE_LINES,
	ID_CA_IKSPLINE_DISPLAY_TANGENT,
	ID_CA_IKSPLINE_TAG_TWIST_CURVE,
	ID_CA_IKSPLINE_TAG_ALIGN_TANGENT,
	ID_CA_IKSPLINE_DISPLAY_LINES_COL,
	ID_CA_IKSPLINE_DISPLAY_TANGENT_COL,
	ID_CA_IKSPLINE_DISPLAY_MODE,
	ID_CA_IKSPLINE_HANDLE_OFFSET,
	ID_CA_IKSPLINE_HANDLE_CREATE,
	ID_CA_IKSPLINE_TAG_TWIST_TYPE,
	ID_CA_IKSPLINE_TAG_TWIST_AXIS,
	ID_CA_IKSPLINE_TAG_AIM,
	ID_CA_IKSPLINE_TAG_ALIGN_AXIS,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_IKSPLINE_HANDLE_ELEMENTS = 9999,
	ID_CA_IKSPLINE_HANDLE_COUNT = 10000,

	ID_CA_IKSPLINE_TAG_GROUPS = 110000,
	ID_CA_IKSPLINE_TAG_GROUPS_END = 115000,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_IKSPLINE_TAG_TYPE_NONE = 0,
	ID_CA_IKSPLINE_TAG_TYPE_FIT,
	ID_CA_IKSPLINE_TAG_TYPE_EQUAL,
	ID_CA_IKSPLINE_TAG_TYPE_REL,

	ID_CA_IKSPLINE_TAG_ALIGN_X = 0,
	ID_CA_IKSPLINE_TAG_ALIGN_Y,
	ID_CA_IKSPLINE_TAG_ALIGN_Z,

	ID_CA_IKSPLINE_DISPLAY_MODE_OFF = 0,
	ID_CA_IKSPLINE_DISPLAY_MODE_ACTIVE,
	ID_CA_IKSPLINE_DISPLAY_MODE_OBJECT,
	ID_CA_IKSPLINE_DISPLAY_MODE_ALWAYS,

	ID_CA_IKSPLINE_TAG_TWIST_TYPE_NONE = 0,
	ID_CA_IKSPLINE_TAG_TWIST_TYPE_WORLD,
	ID_CA_IKSPLINE_TAG_TWIST_TYPE_LOCAL,

	ID_CA_IKSPLINE_TAG_TWIST_AXIS_H = 0,
	ID_CA_IKSPLINE_TAG_TWIST_AXIS_P,
	ID_CA_IKSPLINE_TAG_TWIST_AXIS_B,

	ID_CA_IKSPLINE_TAG_AIM_TANGENT = 0,
	ID_CA_IKSPLINE_TAG_AIM_JOINT,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_IKSPLINE_TAG_DUMMY
};

#endif // TCAIKSPLINE_H__
