#ifndef THAIRMATERIAL_H__
#define THAIRMATERIAL_H__

enum
{
	HAIRMATERIAL_TAG_LINK = 1000,
	HAIRMATERIAL_TAG_USE,
	HAIRMATERIAL_TAG_USE_LEVEL,
	HAIRMATERIAL_TAG_SELECTED_LINK,
	HAIRMATERIAL_TAG_SHADER,
	HAIRMATERIAL_TAG_USE_AVAILABLE,
	HAIRMATERIAL_TAG_REMOVE_AVAILABLE,
	HAIRMATERIAL_TAG_CLUMP_RADIUS,
	HAIRMATERIAL_TAG_CLUMP_RADIUS_VAR,
	HAIRMATERIAL_TAG_CLUMP_MAX,
	HAIRMATERIAL_TAG_THRESHOLD,
	HAIRMATERIAL_TAG_THRESHOLD_END,
	HAIRMATERIAL_TAG_USE_MIX,
	HAIRMATERIAL_TAG_SMOOTH_MIX,
	HAIRMATERIAL_TAG_HAIR_UVS,
	HAIRMATERIAL_TAG_BLEND,

	//////////////////////////////////////////////////////////////////////////

	HAIRMATERIAL_TAG_USE_ALL = 0,
	HAIRMATERIAL_TAG_USE_PERCENT,
	HAIRMATERIAL_TAG_USE_SELECTION,
	HAIRMATERIAL_TAG_USE_CLUMPS,
	HAIRMATERIAL_TAG_USE_SHADER,

	HAIRMATERIAL_TAG_HAIR_UVS_SYMMETRICAL = 0,
	HAIRMATERIAL_TAG_HAIR_UVS_FLAT,
	HAIRMATERIAL_TAG_HAIR_UVS_FEATHER,

	HAIRMATERIAL_TAG_BLENDMODE_AVERAGE = 0,
	HAIRMATERIAL_TAG_BLENDMODE_NORMAL,
	HAIRMATERIAL_TAG_BLENDMODE_MULTIPLY,
	HAIRMATERIAL_TAG_BLENDMODE_SCREEN,
	HAIRMATERIAL_TAG_BLENDMODE_DARKEN,
	HAIRMATERIAL_TAG_BLENDMODE_LIGHT,
	HAIRMATERIAL_TAG_BLENDMODE_DIFFERENCE,
	HAIRMATERIAL_TAG_BLENDMODE_NEGATIVE,
	HAIRMATERIAL_TAG_BLENDMODE_EXCLUSION,
	HAIRMATERIAL_TAG_BLENDMODE_OVERLAY,
	HAIRMATERIAL_TAG_BLENDMODE_HARDLIGHT,
	HAIRMATERIAL_TAG_BLENDMODE_SOFTLIGHT,
	HAIRMATERIAL_TAG_BLENDMODE_DODGE,
	HAIRMATERIAL_TAG_BLENDMODE_BURN,
	HAIRMATERIAL_TAG_BLENDMODE_REFLECT,
	HAIRMATERIAL_TAG_BLENDMODE_GLOW,
	HAIRMATERIAL_TAG_BLENDMODE_FREEZE,
	HAIRMATERIAL_TAG_BLENDMODE_HEAT,
	HAIRMATERIAL_TAG_BLENDMODE_ADD,
	HAIRMATERIAL_TAG_BLENDMODE_SUB,
	HAIRMATERIAL_TAG_BLENDMODE_STAMP,
	HAIRMATERIAL_TAG_BLENDMODE_XOR,
	HAIRMATERIAL_TAG_BLENDMODE_HUE,
	HAIRMATERIAL_TAG_BLENDMODE_SATURATION,
	HAIRMATERIAL_TAG_BLENDMODE_LUMINANCE,
	HAIRMATERIAL_TAG_BLENDMODE_RED,
	HAIRMATERIAL_TAG_BLENDMODE_GREEN,
	HAIRMATERIAL_TAG_BLENDMODE_BLUE,
	HAIRMATERIAL_TAG_BLENDMODE_OVERWRITE,
	HAIRMATERIAL_TAG_BLENDMODE_LEVR,

	//////////////////////////////////////////////////////////////////////////

	HAIRMATERIAL_TAG_DUMMY
};

#endif // THAIRMATERIAL_H__
