#ifndef TOOLMESHTOVOLUME_H__
#define TOOLMESHTOVOLUME_H__

enum
{
	ID_TOOLVOLUMEREMESH_VOLUME_DENSITY = 6000,
	ID_TOOLVOLUMEREMESH_SUBDIVIDE_ITERATIONS = 6001,
	ID_TOOLVOLUMEREMESH_SMOOTH_ITERATIONS = 6002,
	ID_TOOLVOLUMEREMESH_ADAPTIVE_VALUE = 6003,
	ID_TOOLVOLUMEREMESH_REMOVE_SOURCE = 6004
};

#endif // TOOLMESHTOVOLUME_H__