#ifndef TOOLCO_H__
#define TOOLCO_H__

enum
{
	CO_OPTIONS			= 1000,
	CO_OPTIONS_HELP,
	CO_RECORD,
	CO_RECORD_WRITE_SPLINE,
	CO_RECORD_WRITE_CAMERA,
	CO_HUD_DISPLAY,

	/////
	CO_SCALE_RANGE			= 1010,
	CO_DISTANCE,
	CO_SPEED,
	CO_SMOOTHING,
	CO_LOCK_PITCH,
	CO_LIMIT_360,
	CO_COLLISIONS_BB,
	CO_RECORD_PROGRESS,
	CO_RECORD_INTERVAL,
	CO_RECORD_RESET,
	CO_RECORD_START,
	CO_RECORD_STOP,
	CO_RECORD_CREATE_SPLINE,
	CO_WRITE_CAMERA_INTERVAL,
	CO_WRITE_CAMERA_TIME,
	CO_WRITE_CAMERA_CREATE,
	CO_DISPLAY_CENTER,
	CO_DISPLAY_COLLISIONS,
	CO_DISPLAY_RECORDING,
	CO_DISPLAY_HPB,

	/////
	CO_VERSION			= 1090,

	/////
	CO_SCALE_01			= 1100,
	CO_SCALE_1,
	CO_SCALE_10,
	CO_SCALE_100,
	CO_SCALE_1000,

	/////
	CO_DUMMY
};

#endif // TOOLCO_H__
