#ifndef TOOLCAALIGN_H__
#define TOOLCAALIGN_H__

enum
{
	ID_CA_JOINT_ALIGN_PRIMARY_AXIS = 2000,
	ID_CA_JOINT_ALIGN_PRIMARY_DIRECTION,
	ID_CA_JOINT_ALIGN_UP_AXIS,
	ID_CA_JOINT_ALIGN_UP_DIRECTION,
	ID_CA_JOINT_ALIGN_UP_FROMPREV,
	ID_CA_JOINT_ALIGN_PRIMARY_LINK,
	ID_CA_JOINT_ALIGN_UP_LINK,
	ID_CA_JOINT_ALIGN,
	ID_CA_JOINT_ALIGN_CHILDREN,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_JOINT_ALIGN_DIRECTION_BONE = 0,
	ID_CA_JOINT_ALIGN_DIRECTION_WORLD_AXIS,
	ID_CA_JOINT_ALIGN_DIRECTION_OBJECT_AXIS,
	ID_CA_JOINT_ALIGN_DIRECTION_OBJECT,
	ID_CA_JOINT_ALIGN_DIRECTION_ROOT_AXIS,
	ID_CA_JOINT_ALIGN_DIRECTION_PARENT,

	ID_CA_JOINT_ALIGN_AXIS_X = 0,
	ID_CA_JOINT_ALIGN_AXIS_Y,
	ID_CA_JOINT_ALIGN_AXIS_Z,
	ID_CA_JOINT_ALIGN_AXIS_FROMJOINT,
	ID_CA_JOINT_ALIGN_AXIS_NONE,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_JOINT_ALIGN_DUMMY
};

#endif // TOOLCAALIGN_H__
