#ifndef TOUTLINER_H__
#define TOUTLINER_H__

enum
{
	TOONRESTRICT_GROUP = 400000,
	TOONRESTRICT_MAPS_GROUP,

	TOONRESTRICT_START = 401000,			// used in BuildToonObject()

	//

	TOONRESTRICT_MATERIAL,
	TOONRESTRICT_LINES_RESTRICT,
	TOONRESTRICT_BORDER_RESTRICT,
	TOONRESTRICT_EDGES_RESTRICT,
	TOONRESTRICT_DUMMY,
	TOONRESTRICT_CONTOUR_UVW,
	TOONRESTRICT_THICKNESS_MAP,
	TOONRESTRICT_OPACITY_MAP,
	TOONRESTRICT_NOISE_MAP,

	TOONRESTRICT_GROUPING_INCCHILDREN,
	TOONRESTRICT_GROUPING_DUMMY1,
	TOONRESTRICT_GROUPING_DUMMY2,
	TOONRESTRICT_ENABLE,

	TOONRESTRICT_BORDER_OBJECTMATERIALS,
	TOONRESTRICT_MOTION_SELECTIONS,

	TOONRESTRICT_MIX,

	TOONUP_STYLE_LOAD,
	TOONUP_STYLE_SAVE,

	TOONRESTRICT_LINES_RESTRICT_MODE,

	//

	TOONRESTRICT_END,

	//

	TOONRESTRICT_MIX_REPLACE = 0,
	TOONRESTRICT_MIX_REPLACE_LINES,
	TOONRESTRICT_MIX_ADD,
	TOONRESTRICT_MIX_SET,

	TOONRESTRICT_LINES_RESTRICT_MODE_INCLUDE = 0,
	TOONRESTRICT_LINES_RESTRICT_MODE_EXCLUDE
};

#endif // TOUTLINER_H__



