#ifndef TPHCONSTRAINTVECTOR_H__
#define TPHCONSTRAINTVECTOR_H__

enum
{
	PH_SCENE_CAL_VECTOR_WORLD_LENGTH_UNKNOWN = 0,
	PH_SCENE_CAL_VECTOR_WORLD_LENGTH_KNOWN = 1,

	//==== Scene Calibration ====
	PH_CAL_GROUP_SCENE_CALIBRATION_VEC = 46000, // This and definitions up to and including MODE settings MUST be consistent between Vec,Planar, and CameraOrient
	// Vector
	PH_SCENE_CAL_VECTOR,

	PH_SCENE_CAL_VECTOR_AXIS,
		PH_SCENE_CAL_VECTOR_AXIS_NONE,
		PH_SCENE_CAL_VECTOR_AXIS_ALL,
		PH_SCENE_CAL_VECTOR_AXIS_X,
		PH_SCENE_CAL_VECTOR_AXIS_Y,
		PH_SCENE_CAL_VECTOR_AXIS_Z,

	PH_SCENE_CAL_VECTOR_MODE,
		PH_SCENE_CAL_VECTOR_MODE_NONE,
		PH_SCENE_CAL_VECTOR_MODE_SCENE, // Not available via GUI selector (i.e. not listed in res file) - intended for use by separate 'Scale overall scene' tag
		PH_SCENE_CAL_VECTOR_MODE_CAMTRACK,
		PH_SCENE_CAL_VECTOR_MODE_SELECT,

	PH_SCENE_CAL_VECTOR_SET_SELECT_DEPRECATED,
	PH_SCENE_CAL_VECTOR_FORCE_EXPORT,
	PH_SCENE_CAL_VECTOR_GET_SELECT_DEPRECATED,

	PH_SCENE_CAL_VECTOR_FLIP_AXIS,
	PH_SCENE_CAL_VECTOR_FLIP_AXIS_STR,

	PH_SCENE_CAL_VECTOR_INTERPRET_MODE = 46500,
		PH_SCENE_CAL_VECTOR_INTERPRET_MODE_LINEAR,
		PH_SCENE_CAL_VECTOR_INTERPRET_MODE_PLANAR,

	PH_SCENE_CAL_VECTOR_HAS_MEASUREMENT,
	PH_SCENE_CAL_VECTOR_WORLD_LENGTH,

	PH_SCENE_CAL_VECTOR_STR_TARGETS = 47000,
	PH_SCENE_CAL_VECTOR_TARGETS,
	PH_SCENE_CAL_VECTOR_TARGET_0,
	PH_SCENE_CAL_VECTOR_TARGET_1
};

#endif // TPHCONSTRAINTVECTOR_H__
