#ifndef TTARGETEXPRESSION_H__
#define TTARGETEXPRESSION_H__

enum
{
	TARGETEXPRESSIONTAG_LINK			= 1001, // ObjectLink
	TARGETEXPRESSIONTAG_UP_LINK			= 1002,
	TARGETEXPRESSIONTAG_PITCH			= 1003
};

#endif // TTARGETEXPRESSION_H__

