#ifndef TTOONUPPREFS_H__
#define TTOONUPPREFS_H__

enum
{
	TOONUP_PREFS_MAIN_GROUP = 999,
	TOONUP_PREFS = 1000,

	TOONUP_PREFS_SETUP = 2000,

	//////////////////////////////////////////////////////////////////////////

	TOONUP_PREFS_SETUP_AUTOVP = 3000,
	TOONUP_PREFS_SETUP_AUTOADDVPMAT,
	TOONUP_PREFS_SETUP_AUTOADDTAGMAT,

	TOONUP_PREFS_PREVIEW,
	TOONUP_PREFS_PREVIEW_BACKGROUND,
	TOONUP_PREFS_PREVIEW_OBJECT,
	TOONUP_PREFS_CUSTOMPREVIEW,

	//

	TOONUP_PREFS_PREVIEW_STANDARD = 0,
	TOONUP_PREFS_PREVIEW_CUBE,
	TOONUP_PREFS_PREVIEW_ROUNDCUBE,
	TOONUP_PREFS_PREVIEW_PLANE,
	TOONUP_PREFS_PREVIEW_CYLINDER,
	TOONUP_PREFS_PREVIEW_TORUS,
	TOONUP_PREFS_PREVIEW_PLANEBACK,
	TOONUP_PREFS_PREVIEW_SPHERE,
	TOONUP_PREFS_PREVIEW_DOUBLETORUS,
	TOONUP_PREFS_PREVIEW_KNOT,
	TOONUP_PREFS_PREVIEW_STROKE,
	TOONUP_PREFS_PREVIEW_CUSTOM,

	TOONUP_PREFS_PREVIEW_OBJECT_DEFAULT = 0,
	TOONUP_PREFS_PREVIEW_OBJECT_WHITE,
	TOONUP_PREFS_PREVIEW_OBJECT_BLACK,
	TOONUP_PREFS_PREVIEW_OBJECT_TRANS,
	TOONUP_PREFS_PREVIEW_OBJECT_SHADED,

	TOONUP_PREFS_PREVIEW_BACKGROUND_DEFAULT = 0,
	TOONUP_PREFS_PREVIEW_BACKGROUND_WHITE,
	TOONUP_PREFS_PREVIEW_BACKGROUND_BLACK,
	TOONUP_PREFS_PREVIEW_BACKGROUND_SHADED,

	//////////////////////////////////////////////////////////////////////////

	TOONUP_PREFS_DUMMY
};

#endif // TTOONUPPREFS_H__



