#ifndef VPPOSITIONPASS_H__
#define VPPOSITIONPASS_H__

enum
{
	VP_POSITIONPASS_INFO											= 10000,		// STATICTEXT
	VP_POSITIONPASS_FLIP											= 10001,		// LONG CYCLE
		VP_POSITIONPASS_FLIP_RGB									= 1,				// CYCLE OPTION
		VP_POSITIONPASS_FLIP_RBG									= 2,				// CYCLE OPTION
		VP_POSITIONPASS_FLIP_GBR									= 3,				// CYCLE OPTION
		VP_POSITIONPASS_FLIP_GRB									= 4,				// CYCLE OPTION
		VP_POSITIONPASS_FLIP_BGR									= 5,				// CYCLE OPTION
		VP_POSITIONPASS_FLIP_BRG									= 6,				// CYCLE OPTION
	VP_POSITIONPASS_SPACE											= 10002,		// LONG CYCLE
		VP_POSITIONPASS_SPACE_WORLD								= 1,				// CYCLE OPTION
		VP_POSITIONPASS_SPACE_CAMERA							= 2,				// CYCLE OPTION
		VP_POSITIONPASS_SPACE_OBJECT							= 3,				// CYCLE OPTION
	VP_POSITIONPASS_SCALE											= 10003,		// REAL
	VP_POSITIONPASS_INVERTZ										= 10004			// BOOL
};

#endif // VPPOSITIONPASS_H__
