#ifndef XCLOUD_H__
#define XCLOUD_H__

enum
{
	CLOUDSHADER_SCALEX				= 1002,	// REAL
	CLOUDSHADER_SCALEY				= 1003, // REAL
	CLOUDSHADER_LEVEL					= 1004,	// REAL
	CLOUDSHADER_COLOR					= 1005, // VECTOR
	CLOUDSHADER_COMPATIBILITY	= 1006
};

#endif // XCLOUD_H__
