DIG_CMT_TOOL_CAMERA_IMPORT_SIZE: 8.5
DIG_CMT_TOOL_CAMERA_IMPORT_OFFSET: 0
DIG_CMT_TOOL_CAMERA_EXPORT_SIZE: 8.5
DIG_CMT_TOOL_CAMERA_EXPORT_OFFSET: 0
DIG_CMT_TOOL_CAMERA_EXPORT_ROTATION_TWEEN: 0
DIG_CMT_TOOL_CAMERA_EXPORT_USE_BAKE: true
DIG_CMT_TOOL_CAMERA_CONVER_DIS: 0
DIG_CMT_TOOL_CAMERA_CONV_ROTATION_TWEEN: 0
DIG_CMT_TOOL_MOTION_IMPORT_SIZE: 8.5
DIG_CMT_TOOL_MOTION_IMPORT_OFFSET: 0
DIG_CMT_TOOL_MOTION_IMPORT_MOTION: true
DIG_CMT_TOOL_MOTION_IMPORT_MORPH: true
DIG_CMT_TOOL_MOTION_IMPORT_MODEL_INFO: true
DIG_CMT_TOOL_MOTION_IMPORT_IGNORE_PHYSICAL: true
DIG_CMT_TOOL_MOTION_IMPORT_DELETE_PREVIOUS_ANIMATION: true
DIG_CMT_TOOL_MOTION_IMPORT_DETAIL: false
DIG_CMT_TOOL_MOTION_EXPORT_SIZE: 8.5
DIG_CMT_TOOL_MOTION_EXPORT_OFFSET: 0
DIG_CMT_TOOL_MOTION_EXPORT_ROTATION_TWEEN: true
DIG_CMT_TOOL_MOTION_EXPORT_MOTION: true
DIG_CMT_TOOL_MOTION_EXPORT_MORPH: true
DIG_CMT_TOOL_MOTION_EXPORT_MODEL_INFO: true
DIG_CMT_TOOL_MOTION_EXPORT_USE_BAKE: 0
DIG_CMT_TOOL_MODEL_IMPORT_SIZE: 8.5
DIG_CMT_TOOL_MODEL_IMPORT_POLYGON: true
DIG_CMT_TOOL_MODEL_IMPORT_NORMAL: true
DIG_CMT_TOOL_MODEL_IMPORT_UV: true
DIG_CMT_TOOL_MODEL_IMPORT_MATERIAL: true
DIG_CMT_TOOL_MODEL_IMPORT_BONE: true
DIG_CMT_TOOL_MODEL_IMPORT_WEIGHTS: true
DIG_CMT_TOOL_MODEL_IMPORT_IK: true
DIG_CMT_TOOL_MODEL_IMPORT_INHERIT: true
DIG_CMT_TOOL_MODEL_IMPORT_EXPRESSION: true
DIG_CMT_TOOL_MODEL_IMPORT_MULTIPART: true
DIG_CMT_TOOL_MODEL_IMPORT_ENGLISH: false
DIG_CMT_TOOL_MODEL_IMPORT_ENGLISH_CHECK: false