#ifndef _O_MMD_MESH_MANAGER_H_
#define _O_MMD_MESH_MANAGER_H_
enum
{
	MESH_MANAGER_GRP = 1000,
	MESH_DISPLAY_TYPE,
	MESH_MODE,

	MESH_DISPLAY_TYPE_ON = 0,
	MESH_DISPLAY_TYPE_OFF,
	MESH_DISPLAY_TYPE_ON_WIRE,
	MESH_DISPLAY_TYPE_QUICK,
	MESH_DISPLAY_TYPE_QUICK_WIRE,
	MESH_DISPLAY_TYPE_HIDDENLINE,
	MESH_DISPLAY_TYPE_WIRE,
	MESH_MODE_EDIT = 0,
	MESH_MODE_ANIM,
	MESH_MODE_VMD
};
#endif //_O_MMD_MESH_MANAGER_H_
