CONTAINER OMMDBoneManager {
	NAME OMMDBoneManager;

	GROUP BONE_MANAGER_GRP {
		DEFAULT 1;

		LONG BONE_DISPLAY_TYPE {
			CUSTOMGUI QUICKTABRADIO;
			ANIM OFF;

			CYCLE {
				BONE_DISPLAY_TYPE_ON;
				BONE_DISPLAY_TYPE_OFF;
				BONE_DISPLAY_TYPE_MOVABLE;
				BONE_DISPLAY_TYPE_ROTATABLE;
				BONE_DISPLAY_TYPE_VISIBLE;
				BONE_DISPLAY_TYPE_ENABLED;
				BONE_DISPLAY_TYPE_IK;
				BONE_DISPLAY_TYPE_CONTROLS;
			}
		}

		LONG BONE_MODE {
			CUSTOMGUI QUICKTABRADIO;
			ANIM OFF;
			FIT_H;
			SCALE_H;

			CYCLE {
				BONE_MODE_EDIT;
				BONE_MODE_ANIM;
				BONE_MODE_VMD;
			}
		}

		BUTTON ADD_BONE_BUTTON {
			FIT_H;
			SCALE_H;
		}

		BUTTON BONE_CONTROLS_CREATE_BUTTON {
			FIT_H;
			SCALE_H;
		}
	}
}
