CONTAINER OMMDCamera {
	NAME OMMDCamera;
	INCLUDE Obase;

	GROUP VMD_CAM_OBJ_ANIMATION_GRP {
		DEFAULT 1;

		LONG VMD_CAM_OBJ_FRAME_AT{
			HIDDEN;
		}

		STATICTEXT VMD_CAM_OBJ_FRAME_AT_STR{
			ANIM OFF;
		}

		LONG VMD_CAM_OBJ_CURVE_TYPE {
			ANIM OFF;
			MIN 0;
			MAX 5;
			FIT_H;
			SCALE_H;

			CYCLE {
				VMD_CAM_OBJ_INTERPOLATOR_POSITION_X;
				VMD_CAM_OBJ_INTERPOLATOR_POSITION_Y;
				VMD_CAM_OBJ_INTERPOLATOR_POSITION_Z;
				VMD_CAM_OBJ_INTERPOLATOR_ROTATION;
				VMD_CAM_OBJ_INTERPOLATOR_DISTANCE;
				VMD_CAM_OBJ_INTERPOLATOR_AOV;
				VMD_CAM_OBJ_INTERPOLATOR_ALL;
			}
		}

		GROUP {
			SPLINE VMD_CAM_OBJ_SPLINE {
				ANIM OFF;
				SHOWGRID_H;
				SHOWGRID_V;
				MINSIZE_H 350;
				MINSIZE_V 350;
				SQUARE;
			}

			GROUP {
				COLUMNS 5;

				BUTTON VMD_CAM_OBJ_INIT_CURVE_BUTTON {
					FIT_H;
					SCALE_H;
				}

				BUTTON VMD_CAM_OBJ_REGISTER_CURVE_BUTTON {
					FIT_H;
					SCALE_H;
				}

				BUTTON VMD_CAM_OBJ_UPDATE_CURVE_BUTTON {
					FIT_H;
					SCALE_H;
				}

				BUTTON VMD_CAM_OBJ_DELETE_CURVE_BUTTON {
					FIT_H;
					SCALE_H;
				}

				BUTTON VMD_CAM_OBJ_DELETE_ALL_CURVE_BUTTON {
					FIT_H;
					SCALE_H;
				}
			}
		}
	}
}
