#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__
enum
{
	//msg
	IDS_MES_OPENFILE = 10000,
	IDS_MES_SAVEFILE,
	IDS_MES_SELECT_ERR,
	IDS_MES_MEM_ERR,
	IDS_MES_OPEN_FILE_ERR,

	IDS_MES_IMPORT_ERR,
	IDS_MES_IMPORT_TYPE_ERR,
	IDS_MES_IMPORT_READ_ERR,
	IDS_MES_IMPORT_CAM_ERR,
	IDS_MES_IMPORT_OK,

	IDS_MES_EXPORT_ERR,
	IDS_MES_EXPORT_TYPE_ERR,
	IDS_MES_EXPORT_TRACK_ERR,
	IDS_MES_EXPORT_WRITE_ERR,
	IDS_MES_EXPORT_OK,

	IDS_MES_IMPORT_MOT_OK,
	IDS_MES_IMPORT_MOT_CF_BONE,
	IDS_MES_IMPORT_MOT_CF_MORPH,

	//tool
	IDS_VMD_TOOL_TITLE,
	IDS_VMD_CAM_TOOL_TITLE,

	IDS_VMD_CAM_IMPORT_TITLE,
	IDS_VMD_CAM_IMPORT_SIZE_NAME,
	IDS_VMD_CAM_IMPORT_OFFSET_NAME,
	IDS_VMD_CAM_IMPORT_BUTTON,

	IDS_VMD_CAM_EXPORT_TITLE,
	IDS_VMD_CAM_EXPORT_SIZE_NAME,
	IDS_VMD_CAM_EXPORT_OFFSET_NAME,
	IDS_VMD_CAM_EXPORT_BUTTON,

	IDS_VMD_MOT_TOOL_TITLE,

	IDS_VMD_MOT_IMPORT_TITLE,
	IDS_VMD_MOT_IMPORT_SIZE_NAME,
	IDS_VMD_MOT_IMPORT_OFFSET_NAME,
	IDS_VMD_MOT_IMPORT_QUAT_NAME,
	IDS_VMD_MOT_IMPORT_DETAIL_NAME,
	IDS_VMD_MOT_IMPORT_BUTTON,

	IDS_PMX_MOD_TOOL_TITLE,

	IDS_PMX_MOD_IMPORT_TITLE,
	IDS_PMX_MOD_IMPORT_SIZE_NAME,
	IDS_PMX_MOD_IMPORT_SETTINGS,
	IDS_PMX_MOD_IMPORT_POLYGON,
	IDS_PMX_MOD_IMPORT_NORMAL,
	IDS_PMX_MOD_IMPORT_UV,
	IDS_PMX_MOD_IMPORT_MATERIAL,
	IDS_PMX_MOD_IMPORT_BONE,
	IDS_PMX_MOD_IMPORT_WEIGHTS,
	IDS_PMX_MOD_IMPORT_IK,
	IDS_PMX_MOD_IMPORT_INHERIT,
	IDS_PMX_MOD_IMPORT_EXPRESSION,
	IDS_PMX_MOD_IMPORT_MULTIPART,
	IDS_PMX_MOD_IMPORT_BUTTON,

	//tag
	IDS_PMX_MATERIAL_TAG,
	IDS_PMX_BONE_TAG,
    IDS_PMX_DISPLAY_TAG,
	IDS_PMX_RIGID_TAG,
	IDS_PMX_JOINT_TAG,
	IDS_PMX_MODEL_TAG,

  // End of symbol definition
};
#endif C4D_SYMBOLS_H__

