#ifndef _PMX_MODEL_TAG_H_
#define _PMX_MODEL_TAG_H_
enum
{
	MODEL_INFO_GRP = 1000,
	MODEL_NAME_LOCAL,
	MODEL_NAME_UNIVERSAL,
	COMMENTS_LOCAL,
	COMMENTS_UNIVERSAL,
	PMX_VERSION,
	MODEL_IK_GRP,
};
#endif _PMX_MODEL_TAG_H_
