#ifndef _PMX_MODEL_OBJ_H_
#define _PMX_MODEL_OBJH_
enum
{
	MODEL_INFO_GRP = 1000,
	MODEL_NAME_LOCAL,
	MODEL_NAME_UNIVERSAL,
	COMMENTS_LOCAL,
	COMMENTS_UNIVERSAL,
	PMX_VERSION,
	MODEL_FUNCTION_GRP,
	MODEL_DEL_ALL_ANIM_BUTTON,
	MODEL_DEL_BONE_ANIM_BUTTON,
	MODEL_DEL_MORPH_ANIM_BUTTON,
	MODEL_IK_GRP,
};
#endif _PMX_MODEL_OBJ_H_
