#undef DELETE
#undef INTERFACE
#undef RELATIVE
#undef ERROR
#undef GetFirstChild
#undef GetMessage
#undef CreateWindow
#undef GetObject
#undef AddJob
#undef GetClassInfo
#undef PASSTHROUGH
#undef SetPort
#undef LoadString
#undef OFFSET
