#ifndef CBCONIC_H__
#define CBCONIC_H__

enum
{
	CONICCURVE_TYPE						= 1101,
		CONICCURVE_DEPRECIATED		= 0,
		CONICCURVE_ELLIPSE			= 1,
		CONICCURVE_HYPERBOLA		= 2,
		CONICCURVE_PARABOLA			= 3,

	CONICCURVE_ABC						= 1102,
	CONICCURVE_DEF						= 1103,

	CONICCURVE_P1						= 1104,
	CONICCURVE_P2						= 1105
};

#endif // CBCONIC_H__
