#ifndef F3DSIMPORT_H__
#define F3DSIMPORT_H__

enum
{
	F3DSIMPORTFILTER_GROUP					= 999,
	F3DSIMPORTFILTER_SCALE					= 2000,
	F3DSIMPORTFILTER_RENAMETEXTURES	= 2001,
	F3DSIMPORTFILTER_TEXTURESUFFIX	= 2002
};

#endif // F3DSIMPORT_H__
