#ifndef FC4DEXPORT_H__
#define FC4DEXPORT_H__

enum
{
	FC4DEXPORTFILTER_GROUP							= 999,
	FC4DEXPORTFILTER_EXPORT_COPYFILEASSETS	= 2000,
	FC4DEXPORTFILTER_EXPORT_COPYNODEASSETS	= 2001,
	FC4DEXPORTFILTER_EXPORT_SAVEPROJECTWITHASSETS = 2002
};

#endif // FC4DEXPORT_H__
