#ifndef FLDELAY_H__
#define FLDELAY_H__

enum
{
	// Falloff controls
	FIELDLAYER_DELAY_MODE = 1000,	// Int Cycle
	FIELDLAYER_DELAY_STRENGTH = 1001,	// Float
	FIELDLAYER_DELAY_FIELDS = 1002,	// FieldList
	FIELDLAYER_DELAY_FIELDS_GRP = 1003,	// Group

	FIELDLAYER_DELAY_MODE_LINEAR = 0,
	FIELDLAYER_DELAY_MODE_SMOOTH = 1,
	FIELDLAYER_DELAY_MODE_SPRING = 2,
};
#endif																// FLDELAY_H__
