#ifndef FVDBEXPORT_H__
#define FVDBEXPORT_H__

enum
{
	VDBEXPORT_GROUP						= 999,
	VDBEXPORT_ANIMATION 			= 1000,
	VDBEXPORT_FRAME_START			= 1001,
	VDBEXPORT_FRAME_END				= 1002,
	VDBEXPORT_SELECTED				= 1003,
	VDBEXPORT_NAMEFORMAT 			= 1004,
		VDBEXPORT_NAMEFORMAT_0 	= 0,
		VDBEXPORT_NAMEFORMAT_1 	= 1,
		VDBEXPORT_NAMEFORMAT_2 	= 2,
		VDBEXPORT_NAMEFORMAT_3 	= 3,
		VDBEXPORT_NAMEFORMAT_4 	= 4,
		VDBEXPORT_NAMEFORMAT_5 	= 5,
		VDBEXPORT_NAMEFORMAT_6 	= 6,
	VDBEXPORT_UNIT_SCALE 			= 1005
};

#endif // FVDBEXPORT_H__


