#ifndef GVVERTEXCOLORMAP_H__
#define GVVERTEXCOLORMAP_H__

enum
{
	GV_VERTEXCOLORMAP_INPUT_TAG = 2000,
	GV_VERTEXCOLORMAP_INPUT_INDEX,
	GV_VERTEXCOLORMAP_INPUT_VALUE_COLOR,
	GV_VERTEXCOLORMAP_INPUT_VALUE_ALPHA,

	GV_VERTEXCOLORMAP_OUTPUT_VALUE_COLOR = 3000,
	GV_VERTEXCOLORMAP_OUTPUT_VALUE_ALPHA,
	GV_VERTEXCOLORMAP_OUTPUT_COUNT,

	GV_VERTEXCOLORMAP_
};

#endif // GVVERTEXCOLORMAP_H__
