#ifndef MGHONEYCOMBARRAY_H__
#define MGHONEYCOMBARRAY_H__

enum
{
	MG_HONEYCOMB_COUNT_X					= 1300,
	MG_HONEYCOMB_COUNT_Y					= 1301,
	MG_HONEYCOMB_MODE							= 1302,
	MG_HONEYCOMB_SIZE_X						= 1303,
	MG_HONEYCOMB_SIZE_Y						= 1304,
	MG_HONEYCOMB_FORM							= 1305,
	MG_HONEYCOMB_FORMOBJECT_LINK	= 1306,
	MG_HONEYCOMB_ORIENTATION			= 1307,
	MG_HONEYCOMB_DIRECTION				= 1308,
	MG_HONEYCOMB_OFFSET						= 1309,
	MG_HONEYCOMB_OFFSET_VARIATION	= 1310,
	MG_HONEYCOMB_VARIATION				= 1311,
	MG_HONEYCOMB_SEED							= 1312,

	MG_HONEYCOMB_MODE_PERSTEP			= 0,
	MG_HONEYCOMB_MODE_ENDPOINT		= 1,

	MG_HONEYCOMB_FORM_CIRCLE			= 0,
	MG_HONEYCOMB_FORM_SQUARE			= 1,
	MG_HONEYCOMB_FORM_SPLINE			= 2,

	MG_HONEYCOMB_ORIENTATION_XY		= 0,
	MG_HONEYCOMB_ORIENTATION_ZY		= 1,
	MG_HONEYCOMB_ORIENTATION_XZ		= 2,

	MG_HONEYCOMB_DIRECTION_WIDTH	= 0,
	MG_HONEYCOMB_DIRECTION_HEIGHT	= 1
};
#endif // MGHONEYCOMBARRAY_H__
