#ifndef OBASEMOGEN_H__
#define OBASEMOGEN_H__

enum
{
	ID_MG_MOTIONGENERATOR_GROUP_EFFECTORS = 990,	// Effectors Group
	ID_MG_MOTIONGENERATOR_GROUP_TRANSFORM = 991,	// Transform Group
	ID_MG_MOTIONGENERATOR_GROUP_TRNPSR		= 992,	// Transform PSR Group
	ID_MG_MOTIONGENERATOR_GROUP_TRNRANDOM = 993,	// Transform Randomize Group
	ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTION = 994,	// Distributions
	ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTIONSELECTEDUI = 995, // Distribution pattern UI
	ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTION_SUBGROUP = 996, // Distribution wrapper group to hide everything when disabled
	ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTIONMODE = 997,

	ID_MG_MOTIONGENERATOR_DRAW						= 2000,	// Allow grid drawing
	ID_MG_MOTIONGENERATOR_EFFECTORLIST		= 2009,	// Effectors list

	ID_MG_MOTIONGENERATOR_MODE						= 2010,	// Cloning mode
	ID_MG_MOTIONGENERATOR_MODE_OBJECT			= 0,		// Object cloning mode
	ID_MG_MOTIONGENERATOR_MODE_LINEAR			= 1,		// Linear cloning mode
	ID_MG_MOTIONGENERATOR_MODE_RADIAL			= 2,		// Radial cloning mode
	ID_MG_MOTIONGENERATOR_MODE_GRIDARRAY	= 3,		// Grid Array cloning mode;
	ID_MG_MOTIONGENERATOR_MODE_HEXARRAY		= 4,		// Honeycomb Grid Array cloning mode;
	ID_MG_MOTIONGENERATOR_MODE_DEPRECATED1 = 5,
	ID_MG_MOTIONGENERATOR_MODE_RESERVED		= 2011,	// Future for using new modes
	ID_MG_MOTIONGENERATOR_DEPRECATED2 = 2014,

	ID_MG_MOTIONGENERATOR_DEPRECATED3			= 2100,
	ID_MG_MOTIONGENERATOR_DEPRECATED4			= 2101,
	ID_MG_MOTIONGENERATOR_DEPRECATED5			= 2102,
	ID_MG_MOTIONGENERATOR_DEPRECATED6			= 2103,
	ID_MG_MOTIONGENERATOR_DEPRECATED7			= 2104,
	ID_MG_MOTIONGENERATOR_DEPRECATED8			= 2105,
};
#endif																					// OBASEMOGEN_H__
