#ifndef OBASEDEFORM_H__
#define OBASEDEFORM_H__

enum
{
  // Note: if adding IDs to this file, double check for ID collisions in obasedeform, obend, obulge, otwist, otaper and oshear as they are using the same 'value space'
	DEFORMOBJECT_SIZE			 = 1000, // Vector
	DEFORMOBJECT_MODE			 = 1001, // LONG 0=limited, 1=half limited, 2=unlimited
		DEFORMOBJECT_MODE_LIMIT 		= 1,
		DEFORMOBJECT_MODE_BOX   		= 0,
		DEFORMOBJECT_MODE_UNLIMITED	= 2,
	DEFORMOBJECT_STRENGTH  = 1002, // Real
	DEFORMOBJECT_ANGLE     = 1003, // Real
	DEFORMOBJECT_CURVATURE = 1004, // Real
	DEFORMOBJECT_FILLET    = 1005, // Bool
	
	DEFORMOBJECT_ALIGNMENT = 1010, // LONG
		DEFORMOBJECT_ALIGNMENT_AUTO = 0,
		DEFORMOBJECT_ALIGNMENT_POSITIVE_X = 1,
		DEFORMOBJECT_ALIGNMENT_NEGATIVE_X = 2,
		DEFORMOBJECT_ALIGNMENT_POSITIVE_Y = 3,
		DEFORMOBJECT_ALIGNMENT_NEGATIVE_Y = 4,
		DEFORMOBJECT_ALIGNMENT_POSITIVE_Z = 5,
		DEFORMOBJECT_ALIGNMENT_NEGATIVE_Z = 6,

	DEFORMOBJECT_FITTOPARENT = 100001		// Button
};

#endif // OBASEDEFORM_H__
