#ifndef OCASQUASH_H__
#define OCASQUASH_H__

enum
{
	ID_CA_SQUASH_OBJECT_LOW = 2000,
	ID_CA_SQUASH_OBJECT_HIGH,
	ID_CA_SQUASH_OBJECT_CENTER,
	ID_CA_SQUASH_OBJECT_FACTOR,
	ID_CA_SQUASH_OBJECT_STRENGTH,
	ID_CA_SQUASH_OBJECT_CURVATURE,
	ID_CA_SQUASH_OBJECT_CURVATURE_TYPE,
	ID_CA_SQUASH_OBJECT_CURVATURE_CUSTOM,
	ID_CA_SQUASH_OBJECT_CURVATURE_SPLINE,
	ID_CA_SQUASH_OBJECT_DELETED_1,
	ID_CA_SQUASH_OBJECT_ASPECT,
	ID_CA_SQUASH_OBJECT_SMOOTH_START,
	ID_CA_SQUASH_OBJECT_SMOOTH_END,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_SQUARE = 0,
	ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_CUBE,
	ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_QUAD,
	ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_CUSTOM,
	ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_SPLINE,

	//////////////////////////////////////////////////////////////////////////

	ID_CA_SQUASH_OBJECT_FITTOPARENT,

	ID_CA_SQUASH_OBJECT_DUMMY
};

#endif // OCASQUASH_H__
