#ifndef _O_DELTA_MUSH_DEFORMER_H__
#define _O_DELTA_MUSH_DEFORMER_H__



enum {


    ID_DELTAMUSH_DEFORMER_WEIGHT = 1000,
    ID_DELTAMUSH_DEFORMER_SMOOTHVIEW, 
    ID_DELTAMUSH_DEFORMER_SMOOTHTYPE, 
    ID_DELTAMUSH_DEFORMER_SMOOTH_ITERATION,
    ID_DELTAMUSH_DEFORMER_PIN_CORNER,
    
    ID_DELTAMUSH_DEFORMER_INITIAL,
    ID_DELTAMUSH_DEFORMER_RESTORE, 


    ID_DELTAMUSH_DEFORMER_INEXCLUDE_MODE,  
    ID_DELTAMUSH_DEFORMER_INEXCLUDE_LIST,

    ID_DELTAMUSH_DEFORMER_GROUP_SEPARATOR,
    ID_DELTAMUSH_DEFORMER_OBJECT_MEM,
    ID_DELTAMUSH_DEFORMER_OPTIONS,
    ID_DELTAMUSH_DEFORMER_TANGENT_TYPE,
    
    // -------
    ID_DELTAMUSH_DEFORMER_INEXCLUDE_MODE_INCLUDE = 0,
    ID_DELTAMUSH_DEFORMER_INEXCLUDE_MODE_EXCLUDE = 1,
    // -------
    ID_DELTAMUSH_DEFORMER_SMOOTHTYPE_FIX = 0,
    ID_DELTAMUSH_DEFORMER_SMOOTHTYPE_PROPORTIONAL = 1,
    // -------
    ID_DELTAMUSH_DEFORMER_TANGENT_A = 0,
    ID_DELTAMUSH_DEFORMER_TANGENT_B,
    ID_DELTAMUSH_DEFORMER_TANGENT_C,
    ID_DELTAMUSH_DEFORMER_TANGENT_UV,


    __DUMMY_ELEMENT__DELTAMUSH_DEFORMER


};

#endif