#ifndef OFFD_H__
#define OFFD_H__

enum
{
	FFDOBJECT_SIZE	= 1000,	// Vector
	FFDOBJECT_XSUB	= 1001,	// LONG
	FFDOBJECT_YSUB	= 1002,	// LONG
	FFDOBJECT_ZSUB	= 1003,	// LONG
	FFDOBJECT_FITTOPARENT = 100001		// Button
};

#endif // OFFD_H__
