#ifndef OFIELDFORCE_H__
#define OFIELDFORCE_H__

enum
{
	ID_FIELDFORCE_FIELDLIST						= 1000,
	ID_FIELDFORCE_STRENGTH						= 1001,
	ID_FIELDFORCE_MODE								= 1002,
		ID_FIELDFORCE_MODE_ADD						= 0,
		ID_FIELDFORCE_MODE_ABSOLUTE				= 1,
		ID_FIELDFORCE_MODE_DIRECTION			=	2,
	ID_FIELDFORCE_DISPLAY_TAB					= 1003,
	ID_FIELDFORCE_DISPLAY							= 1004,
	ID_FIELDFORCE_BOX_SIZE						= 1005,
	ID_FIELDFORCE_DENSITY							= 1006,
	ID_FIELDFORCE_DISPLAY_LENGTH			= 1007,
	ID_FIELDFORCE_CONSIDER_MASS				= 1008,
	ID_FIELDFORCE_SCALE_LENGTH_DISPLAY = 1009,
	ID_FIELDFORCE_VECTOR_MODE					= 1010,
		ID_FIELDFORCE_VECTOR_MODE_LINES	= 0,
		ID_FIELDFORCE_VECTOR_MODE_COLOR	= 1,
};

#endif // OFIELDFORCE_H__
