#ifndef OHAIRFEATHER_H__
#define OHAIRFEATHER_H__

enum
{
	FEATHER_OBJECT_RACHIS_LEFT = 1000,
	FEATHER_OBJECT_RACHIS_RIGHT,
	FEATHER_OBJECT_RACHIS_SECTION_LEFT,
	FEATHER_OBJECT_RACHIS_SECTION_RIGHT,
	FEATHER_OBJECT_BARB_SPACING,
	FEATHER_OBJECT_BARB_LENGTH,
	FEATHER_OBJECT_BARB_SPACING_VAR,
	FEATHER_OBJECT_BARB_LENGTH_VAR,
	FEATHER_OBJECT_BARB_Y_DISP,
	FEATHER_OBJECT_BARB_Y_DISP_VAR,
	FEATHER_OBJECT_BARB_Z_DISP,
	FEATHER_OBJECT_BARB_Z_DISP_VAR,
	FEATHER_OBJECT_RACHIS_ROTATION,
	FEATHER_OBJECT_RACHIS_ROTATION_VAR,
	FEATHER_OBJECT_BARB_ROTATION_Y_VAR,
	FEATHER_OBJECT_BARB_ROTATION_Z_VAR,
	FEATHER_OBJECT_BARB_START,
	FEATHER_OBJECT_BARB_END,
	FEATHER_OBJECT_SEGMENTS,
	FEATHER_OBJECT_RACHIS_CURVE_LEFT,
	FEATHER_OBJECT_RACHIS_CURVE_RIGHT,
	FEATHER_OBJECT_RELATIVE,
	FEATHER_OBJECT_REFERENCE,
	FEATHER_OBJECT_REVERSE,
	FEATHER_OBJECT_RACHIS_RADIUS_TOP,
	FEATHER_OBJECT_SHOW_EDITOR,
	FEATHER_OBJECT_EDITOR_LOD,
	FEATHER_OBJECT_BARB_Y_DISP_T,
	FEATHER_OBJECT_BARB_Y_DISP_T_VAR,
	FEATHER_OBJECT_RACHIS_RADIUS_BASE,
	FEATHER_OBJECT_BARB_GAPS,
	FEATHER_OBJECT_BARB_GAPS_VAR,
	FEATHER_OBJECT_BARB_GAPS_OCCUR,
	FEATHER_OBJECT_GENERATE,
	FEATHER_OBJECT_RACHIS_ROTATION_DELTA,
	FEATHER_OBJECT_RACHIS_ROTATION_DELTA_VAR,
	FEATHER_OBJECT_SPACING,
	FEATHER_OBJECT_BARB_COUNT,

	FEATHER_OBJECT_GROUP_CURVE = 2000,
	FEATHER_OBJECT_GROUP_SECTION,
	FEATHER_OBJECT_GROUP_SHAPE,

	FEATHER_OBJECT_GROUP_GENERATE,
	FEATHER_OBJECT_GROUP_SPACING,
	FEATHER_OBJECT_GROUP_DISPLACE,
	FEATHER_OBJECT_GROUP_ROTATION,
	FEATHER_OBJECT_GROUP_GAPS,

	//////////////////////////////////////////////////////////////////////////

	FEATHER_OBJECT_GENERATE_HAIR = 0,
	FEATHER_OBJECT_GENERATE_SPLINES,

	FEATHER_OBJECT_SPACING_COUNT = 0,
	FEATHER_OBJECT_SPACING_SPACE,

	//////////////////////////////////////////////////////////////////////////
	FEATHER_OBJECT_GROUP_RACHIS,
	FEATHER_OBJECT_DUMMY
};

#endif // OHAIRFEATHER_H__
