#ifndef OMOGRAPH_TRACER_H__
#define OMOGRAPH_TRACER_H__

enum
{
	MGTRACEROBJECT_OBJECTLIST				= 1100,
	MGTRACEROBJECT_LIMITMODE				= 1101,
	MGTRACEROBJECT_LIMITMODE_NONE		= 0,
	MGTRACEROBJECT_LIMITMODE_START	= 1,
	MGTRACEROBJECT_LIMITMODE_END		= 2,
	MGTRACEROBJECT_LIMITMODE_AMMOUNT = 1102,
	MGTRACEROBJECT_USETPSUBGROUPS		= 1103,
	MGTRACEROBJECT_SAMPLESTEP				= 1104,
	MGTRACEROBJECT_USEPOINTS				= 1105,
	MGTRACEROBJECT_ACTIVE						= 1106,
	MGTRACEROBJECT_SPACE						= 1107,
	MGTRACEROBJECT_SPACE_GLOBAL			= 0,
	MGTRACEROBJECT_SPACE_LOCAL			= 1,
	MGTRACEROBJECT_REVERSESPLINE		= 1108,
	MGTRACEROBJECT_MGMODE						= 1109,
	MGTRACEROBJECT_MGMODE_SINGLE		= 0,
	MGTRACEROBJECT_MGMODE_CHILDS		= 1,
	MGTRACEROBJECT_MGMODE_ACHILDS		= 2,
	MGTRACEROBJECT_MODE							= 1110,
	MGTRACEROBJECT_MODE_TRACE				= 0,
	MGTRACEROBJECT_MODE_LINK				= 1,
	MGTRACEROBJECT_MODE_SEGLINK			= 2,
	MGTRACEROBJECT_INCLUDECLONER		= 1111
};
#endif // OMOGRAPH_TRACER_H__
