#ifndef OMOGRAPH_EXTRUDE_H__
#define OMOGRAPH_EXTRUDE_H__

enum
{
	MGEXTRUDEDEFORMER_STEPS			= 1020,
	MGEXTRUDEDEFORMER_SELECTION = 1021,
	MGEXTRUDEDEFORMER_MODE			= 1022,
	MGEXTRUDEDEFORMER_MODE_ROOT = 0,
	MGEXTRUDEDEFORMER_MODE_STEP = 1,
	MGEXTRUDEDEFORMER_SPLINE		= 1023
};
#endif // OMOGRAPH_EXTRUDE_H__
