#ifndef OP_ALIGNMENT_H__
#define OP_ALIGNMENT_H__

#include "gvbase.h"

enum
{
	ALIGN_VERSION =	1000,
	ALIGN_SOURCE,
	ALIGN_TYPE,
	ALIGN_VAR,
	ALIGN_AXIS,
	ALIGN_INVERT,
	ALIGN_LAZINESS,
	ALIGN_XROT,
	ALIGN_YROT,
	ALIGN_ZROT,
	//ALIGN_XFROM,
	//ALIGN_XTO,
	//ALIGN_XGRAD,
	//ALIGN_YFROM,
	//ALIGN_YTO,
	//ALIGN_YGRAD,
	//ALIGN_ZFROM,
	//ALIGN_ZTO,
	//ALIGN_ZGRAD,
	//ALIGN_XLOCK,
	//ALIGN_YLOCK,
	//ALIGN_ZLOCK,

	ALIGN_SOURCE_X = 0,
	ALIGN_SOURCE_Y,
	ALIGN_SOURCE_Z,

	ALIGN_TYPE_NONE = 0,
	ALIGN_TYPE_RANDOM,
	ALIGN_TYPE_TRAVEL,
	ALIGN_TYPE_X,
	ALIGN_TYPE_Y,
	ALIGN_TYPE_Z,
	ALIGN_TYPE_USERDIR,
	ALIGN_TYPE_USERPOS,

//Inports
	IN_ALIGN_ON = 2000,
	IN_ALIGN_PARTICLE,
	IN_ALIGN_ATIME,
	IN_ALIGN_POSITION
};

#endif // OP_ALIGNMENT_H__
