#ifndef OP_PARTICLEDRAW_H__
#define OP_PARTICLEDRAW_H__

#include "gvbase.h"

enum
{
	OP_PARTICLEDRAW_SEED	    = 1000,
	OP_PARTICLEDRAW_TYPE		  = 1001,
	OP_PARTICLEDRAW_RADIUS	  = 1002,
	OP_PARTICLEDRAW_COUNT		  = 1003,
	OP_PARTICLEDRAW_LIFE		  = 1004,
	OP_PARTICLEDRAW_LIFEVAR	  = 1005,
	OP_PARTICLEDRAW_DRAWPOS   = 1006,
	OP_PARTICLEDRAW_REMOVE	  = 1007,

	OP_PARTICLEDRAW_TYPE_POINT		 = 0,
	OP_PARTICLEDRAW_TYPE_SPHERICAL = 1,

	OP_PARTICLEDRAW_ON    = 2000,
	OP_PARTICLEDRAW_ATIME = 2001,

	OP_PARTICLEDRAW_OUT_PARTICLE	    = 3000,
	OP_PARTICLEDRAW_OUT_PARTICLECOUNT	= 3001,
	OP_PARTICLEDRAW_OUT_PARTICLENUM		= 3002
};


#endif // OP_PARTICLEDRAW_H__
