#ifndef OSPLINEDEFORMER_H__
#define OSPLINEDEFORMER_H__

enum
{
	SPLINEDEFORMEROBJECT_ORIGINAL_SPLINE	= 2000,
	SPLINEDEFORMEROBJECT_MODIFY_SPLINE		= 2001,
	SPLINEDEFORMEROBJECT_RADIUS						= 2002,
	SPLINEDEFORMEROBJECT_SPLINECONTROL		= 2004,
	SPLINEDEFORMEROBJECT_USE_LENGTH				= 2005,
	SPLINEDEFORMEROBJECT_USE_POLYS        = 2006,
	SPLINEDEFORMEROBJECT_B_APPROX         = 2007
};

#endif // OSPLINEDEFORMER_H__
