#ifndef OVOLUMESEQUENCE_H__
#define OVOLUMESEQUENCE_H__

enum
{
	ID_VOLUMESEQUENCE_PATH = 6000,
	ID_VOLUMESEQUENCE_ANIMATION_ACTIVE = 6001,
	ID_VOLUMESEQUENCE_FRAME = 6002,
	ID_VOLUMESEQUENCE_FROM = 6003,
	ID_VOLUMESEQUENCE_TO = 6004,
	ID_VOLUMESEQUENCE_OFFSET = 6005,
	ID_VOLUMESEQUENCE_SCALE = 6006,
	ID_VOLUMESEQUENCE_LOOP = 6007,
	ID_VOLUMESEQUENCE_GRID_LIST = 6008,
	ID_VOLUMESEQUENCE_RELOAD = 6009,
	ID_VOLUMESEQUENCE_UNIT_SCALE = 6010,
	ID_VOLUMESEQUENCE_STATS_STRING = 6011,
	ID_VOLUMESEQUENCE_SELECTION_SAVE = 6012
};

#endif // OVOLUMESEQUENCE_H__
