#ifndef UVPREFSCOLOR_H__
#define UVPREFSCOLOR_H__

//4000 because with 1000 conflict with other prefs
enum
{
	PREF_UVCOLOR_MAIN_GROUP = 999,
	PREF_UVCOLOR_COLORS	= 4000,
	PREF_UVCOLOR_LIST		= 4001,
	PREF_UVCOLOR_RESET	= 4002,

	PREF_UVCOLOR_DUMMY
};

#endif // UVPREFSCOLOR_H__
