#ifndef SBPLANE_H__
#define SBPLANE_H__

enum
{
	PLANESURFACE_TYPE					= 1101,
		PLANESURFACE_BOUNDED		= 0,
		PLANESURFACE_UNBOUNDED		= 1,

	PLANESURFACE_DISPLAY_POS			= 1102,
	PLANESURFACE_DISPLAY_SIZE			= 1103,
	PLANESURFACE_A						= 1104,
	PLANESURFACE_B						= 1105,
	PLANESURFACE_C						= 1106,
	PLANESURFACE_D						= 1107,

	PLANESURFACE_LIMIT					= 1108
};

#endif // SBPLANE_H__
