#ifndef TCHARACTERSOLVER_H__
#define TCHARACTERSOLVER_H__

enum
{
	CS_SOLVER_GROUP = 1000, // Group
	CS_SOLVERRESULT_GROUP,
	CS_BODYPARTS_GROUP,

	// Data
	CS_SOURCE_CHARACTER = 2000,
	CS_TARGET_CHARACTER,
	CS_COMPONENTMATCH_RESULT,
	CS_OBJECTMATCH_RESULT1,
	CS_ERROR_RESULT,
	CS_GLOBALSTRENGTH,
	CS_BODYPARTS_SETTINGS, // Base Container containing solving data
	CS_SOLVERMODE,
	CS_OBJECTMATCH_RESULT2,

	CS_STRENGTH_GROUP = 3000, // must stay alone, used in dynamic UI
	CS_PARENTFOLDER_GROUP = 3500, // must stay alone, used in dynamic UI
	CS_ATTRIBUTES_GROUP = 4000, // must stay alone, used in dynamic UI

	// CS_SOLVERMODE
	CS_SOLVERMODE_SKELETONTOSKELETON = 0,
	CS_SOLVERMODE_CONTROLLERTOCONTROLLER = 1,

	// BodyPart Solving Settings
	CS_BPSS_IDENT_ID = 0,	// String
	CS_BPSS_WEIGHT_ID = 1,	// Float
	CS_BPSS_ACTIVE_ID = 2,	// Bool
	CS_BPSS_POSITIONWEIGHT_ID = 3,	// Float
	CS_BPSS_ROTATIONWEIGHT_ID = 4,	// Float
	CS_BPSS_SCALEWEIGHT_ID = 5,	// Float
	CS_BPSS_POSITIONACTIVE_ID = 6,	// Bool
	CS_BPSS_ROTATIONACTIVE_ID = 7,	// Bool
	CS_BPSS_SCALEACTIVE_ID = 8,	// Bool

	// Functions
	CS_GOTORESTPOSE = 10000,


	CS_LAST
};

#endif // TCHARACTERSOLVER_H__
