#ifndef _T_DELTA_MUSH_H__
#define _T_DELTA_MUSH_H__


enum {

		ID_TDELTAMUSH_OBJECT_INITIAL = 1000,
        ID_TDELTAMUSH_OBJECT_RESTORE,
        ID_TDELTAMUSH_OBJECT_MEM,
        ID_TDELTAMUSH_WEIGHT_TYPE,
        ID_TDELTAMUSH_SMOOTH_ITERATION,
        ID_TDELTAMUSH_PIN_CORNER,
        ID_TDELTAMUSH_PREV_SMOOTH,
        ID_TDELTAMUSH_WEIGHTMAP,
        ID_TDELTAMUSH_WEIGHT,
        ID_TDELTAMUSH_WEIGHTMAP_ONOFF,
        ID_TDELTAMUSH_AFFECTMORPH,
        ID_DELTAMUSH_TAG_GROUP_SEPARATOR,
        ID_TDELTAMUSH_TANGENT_TYPE,
    //////
        ID_TDELTAMUSH_WEIGHT_FIX = 0 ,
        ID_TDELTAMUSH_WEIGHT_PROPORTIONAL,

        ID_TDELTAMUSH_TANGENT_A = 0,
        ID_TDELTAMUSH_TANGENT_B,
        ID_TDELTAMUSH_TANGENT_C,
        ID_TDELTAMUSH_TANGENT_UV,







	__DUMMY_ELEMENT__DELTAMUSH_TAG



};

#endif