#ifndef THAIRCONSTRAINT_H__
#define THAIRCONSTRAINT_H__

enum
{
	HAIR_CONSTRAINTS_TAG_SET_ANCHOR = 5000,
	HAIR_CONSTRAINTS_TAG_RELEASE_ANCHOR,
	HAIR_CONSTRAINTS_TAG_CLEAR_ANCHOR,
	HAIR_CONSTRAINTS_TAG_DRAW_ANCHOR,
	HAIR_CONSTRAINTS_TAG_ANCHOR_LINK,
	HAIR_CONSTRAINTS_TAG_STRENGTH,
	HAIR_CONSTRAINTS_TAG_OFFSET,
	HAIR_CONSTRAINTS_TAG_STRENGTH_LINK,
	HAIR_CONSTRAINTS_TAG_OFFSET_LINK,

	//////////////////////////////////////////////////////////////////////////

	HAIR_CONSTRAINT_TAG_DUMMY
};

#endif // THAIRCONSTRAINT_H__
