#ifndef THAIRRENDER_H__
#define THAIRRENDER_H__

enum
{
	HAIR_RENDER_TAG_ENABLE = 1000,
	HAIR_RENDER_TAG_MODE,
	HAIR_RENDER_TAG_COUNT,
	HAIR_RENDER_TAG_SEGMENTS,
	HAIR_RENDER_TAG_LENGTH,

	HAIR_RENDER_TAG_AUTOTIME,
	HAIR_RENDER_TAG_START,
	HAIR_RENDER_TAG_STOP,
	HAIR_RENDER_TAG_TRAIL_LIMIT,
	HAIR_RENDER_TAG_TRAIL,
	HAIR_RENDER_TAG_SCALE,
	HAIR_RENDER_TAG_DEATH,
	HAIR_RENDER_TAG_HAIRS,
	HAIR_RENDER_TAG_RESTRICT,

	//////////////////////////////////////////////////////////////////////////

	HAIR_RENDER_TAG_MODE_POINTS = 0,
	HAIR_RENDER_TAG_MODE_SURFACE,
	HAIR_RENDER_TAG_MODE_LINE,
	HAIR_RENDER_TAG_MODE_INTERPOLATED,
	HAIR_RENDER_TAG_MODE_POSITION,
	HAIR_RENDER_TAG_MODE_VELOCITY,
	HAIR_RENDER_TAG_MODE_TRAIL,

	HAIR_RENDER_TAG_REMAIN = 0,
	HAIR_RENDER_TAG_REMOVE,
	HAIR_RENDER_TAG_RUNOUT,

	//////////////////////////////////////////////////////////////////////////

	HAIR_RENDER_TAG_DUMMY
};

#endif // THAIRRENDER_H__
