#ifndef TOOLHAIRBRUSH_H__
#define TOOLHAIRBRUSH_H__

enum
{
	HAIR_TOOL_BRUSH_GROUP_DISTANCE	= 3000,
	HAIR_TOOL_BRUSH_GROUP_VIEW,
	HAIR_TOOL_BRUSH_GROUP_GUIDE,

	HAIR_TOOL_BRUSH_LOCK = 2000,
	HAIR_TOOL_BRUSH_STRENGTH,
	HAIR_TOOL_BRUSH_FALLOFF,
	HAIR_TOOL_BRUSH_FALLOFF_CURVE,
	HAIR_TOOL_BRUSH_WIDTH,
	HAIR_TOOL_BRUSH_DISTANCE_FADE,
	HAIR_TOOL_BRUSH_DISTANCE,
	HAIR_TOOL_BRUSH_DISTANCE_CURVE,
	HAIR_TOOL_BRUSH_TYPE,
	HAIR_TOOL_BRUSH_SELECTED,
	HAIR_TOOL_BRUSH_IK,
	HAIR_TOOL_BRUSH_COLLISIONS,
	HAIR_TOOL_BRUSH_RADIUS,
	HAIR_TOOL_BRUSH_VIEW_FALLOFF,
	HAIR_TOOL_BRUSH_VIEW_FALLOFF_CURVE,
	HAIR_TOOL_BRUSH_GUIDE_FALLOFF,
	HAIR_TOOL_BRUSH_GUIDE_FALLOFF_CURVE,

	//////////////////////////////////////////////////////////////////////////

	HAIR_TOOL_BRUSH_FALLOFF_NONE = 0,
	HAIR_TOOL_BRUSH_FALLOFF_LINEAR,
	HAIR_TOOL_BRUSH_FALLOFF_DOME,
	HAIR_TOOL_BRUSH_FALLOFF_BELL,
	HAIR_TOOL_BRUSH_FALLOFF_CIRCLE,
	HAIR_TOOL_BRUSH_FALLOFF_NEEDLE,
	HAIR_TOOL_BRUSH_FALLOFF_SPLINE,

	HAIR_TOOL_BRUSH_TYPE_MOVE = 0,
	HAIR_TOOL_BRUSH_TYPE_TWIST,
	HAIR_TOOL_BRUSH_TYPE_REPEL,
	HAIR_TOOL_BRUSH_TYPE_KINK,
	HAIR_TOOL_BRUSH_TYPE_SMOOTH,
	HAIR_TOOL_BRUSH_TYPE_SCALE,
	HAIR_TOOL_BRUSH_TYPE_PAINT_VERTEX,
	HAIR_TOOL_BRUSH_TYPE_STRAIGHTEN,
	HAIR_TOOL_BRUSH_TYPE_DELETE,

	//////////////////////////////////////////////////////////////////////////

	HAIR_TOOL_BRUSH_DUMMY
};

#endif // TOOLHAIRBRUSH_H__
