#ifndef TOOLDUPLICATE_H__
#define TOOLDUPLICATE_H__

#include "toolarrange.h"

enum
{
	MDATA_DUPGROUP													= 9999,
	MDATA_DUPLICATE_COPIES 									= 10000, // 10000 because arrange need some ids
	MDATA_DUPLICATE_INSTANCES								= 10001,
		MDATA_DUPLICATE_INSTANCES_OFF								= 0,
		MDATA_DUPLICATE_INSTANCES_INSTANCE					= 1,
		MDATA_DUPLICATE_INSTANCES_VOLUMEINSTANCE		= 2,

	MDATA_DUPLICATE_
};

#endif // TOOLDUPLICATE_H__
