#ifndef TOOLSCATTERPLACEMENT_H__
#define TOOLSCATTERPLACEMENT_H__

enum
{
  TOOL_RANDOM_SEED = 1100,
  TOOL_EXCLUSION_RADIUS = 1200,
  TOOL_PLACEMENT_OUTER_RADIUS,
  TOOL_INTER_SPLAT_SEP_DISTANCE,
  TOOL_PLACEMENT_ATTEMPTS_PER_SPLAT,

  TOOL_SHOW_PREVIEW_REGION = 1206,
  TOOL_SHOW_PLACEMENTS,
  TOOL_SHOW_SPLAT_REGIONS,

  TOOL_USE_SPLATS,
  TOOL_PLACEMENT_DENSITY,
  TOOL_RANDOMIZE_ORDER,

  TOOL_UNUSED_1,
  TOOL_UNUSED_2,
  TOOL_UNUSED_3,
  TOOL_UNUSED_4,

  TOOL_ROTATION_RANGE,

  TOOL_UNUSED_5,
  TOOL_UNUSED_6,

  TOOL_MIN_MAX_SCALE,
  TOOL_MIN_MAX_Y_OFFSET,

  TOOL_ALIGN_REFERENCE,

  TOOL_OBJECT_PALETTE = 1400,

  TOOL_MODE_INTERACTION = 1500,
  TOOL_MODE_OBJECT_SOURCE = 1502,
  TOOL_MODE_ALIGN_TO,

  PEN_GROUP = 10000,
  OBJECT_GROUP,
  CLONES_GROUP,
  TRANSFORM_GROUP,
  DISPLAY_GROUP,

  // Interaction mode
  TOOL_MODE_SCATTER = 0,
  TOOL_MODE_ERASE,

  // Source
  TOOL_MODE_SOURCE_SELECTION = 0,
  TOOL_MODE_SOURCE_PALETTE,

  // Align to
  TOOL_MODE_ALIGN_STROKE = 0,
  TOOL_MODE_ALIGN_OBJECT,

  // Alignment reference position
  TOOL_REF_AXIS = 0,
  TOOL_REF_BOUNDINGBOX
};

#endif // TOOLSCATTERPLACEMENT_H__
