#ifndef TOOLSPLINEROUND_H__
#define TOOLSPLINEROUND_H__

enum
{
	MDATA_SPLINEROUND_POINTS			 = 2015,	// LONG: Number Of Points To Be Rounded
	MDATA_SPLINEROUND_TYPE				 = 2016,	// LONG: Type Of Interpolation
	MDATA_SPLINEROUND_TYPE_LINEAR	 = 0,
	MDATA_SPLINEROUND_TYPE_CUBIC	 = 1,
	MDATA_SPLINEROUND_TYPE_AKIMA	 = 2,
	MDATA_SPLINEROUND_TYPE_BSPLINE = 3,
	MDATA_SPLINEROUND_TYPE_BEZIER	 = 4,

	MDATA_SPLINEROUND_
};

#endif	// TOOLSPLINEROUND_H__
