#ifndef TOOLCHARACTERDEF_H__
#define TOOLCHARACTERDEF_H__

enum
{
	// Groups
	TCD_UPPERCOMMANDS_GROUP = 2000, 
	TCD_TREE_GROUP,
	TCD_LOWERCOMMANDS_GROUP,

	// functions
	TCD_EXTRACTSKELETON = 3000,
	TCD_EXTRACTRESTPOSE,
	TCD_APPLYRESTPOSE,
	TCD_ADDBODYPART,
	TCD_REMOVEBODYPART,
	TCD_SAVEPRESET,
	TCD_LOADPRESET,

	// UI elements
	TCD_TREE = 4000,

	// Internal Tool Data
	TCD_CHARACTERDEFINITIONTAG = 5000, // Tag
	TCD_BODYPARTID, // String internedid
	TCD_STATUSMESSAGE, // String Status Message

	CD_LAST
};

#endif // TOOLCHARACTERDEF_H__
