#ifndef TOOLTRANSFER_H__
#define TOOLTRANSFER_H__

enum
{
	MDATA_TRANSFER_OBJECT_LINK			= 1000,
	MDATA_TRANSFER_USE_MOVE					,
	MDATA_TRANSFER_USE_MOVE_X				,
	MDATA_TRANSFER_USE_MOVE_Y				,
	MDATA_TRANSFER_USE_MOVE_Z				,
	MDATA_TRANSFER_USE_ROTATION			,
	MDATA_TRANSFER_USE_SCALE				,

	MDATA_TRANSFER_
};

#endif // TOOLTRANSFER_H__
