#ifndef TOOLPATH_H__
#define TOOLPATH_H__

enum
{
	MDATA_PATH_START_POLYGON				= 1100, // LONG
	MDATA_PATH_START_FIRST_VERTEX		= 1110, // LONG
	MDATA_PATH_START_SECOND_VERTEX	= 1120, // LONG
	MDATA_PATH_END_POLYGON					= 1130, // LONG
	MDATA_PATH_END_FIRST_VERTEX			= 1140, // LONG
	MDATA_PATH_END_SECOND_VERTEX		= 1150, // LONG
};

#endif // TOOLPATH_H__
