#ifndef TOOLSTITCHANDSEW_H__
#define TOOLSTITCHANDSEW_H__

enum
{
	MDATA_STITCHANDSEW_OBJINDEX1							= 1100, //LINK
	MDATA_STITCHANDSEW_OBJINDEX2							= 1101, //LINK
	MDATA_STITCHANDSEW_CRTL										= 1102, //BOOL
	MDATA_STITCHANDSEW_SHIFT									= 1103, //BOOL
	MDATA_STITCHANDSEW_HOLE 									= 1104, //BOOL
	MDATA_STITCHANDSEW_BC1										= 1105, //BASECONTAINER
	MDATA_STITCHANDSEW_P1   									= 1106, //LONG
	MDATA_STITCHANDSEW_P2   									= 1107, //LONG
	MDATA_STITCHANDSEW_NGONS   								= 1108, //LONG
	MDATA_STITCHANDSEW_VISIBLE   							= 1109, //BOOL
	MDATA_STITCHANDSEW_ISO		   							= 1110, //BOOL
	MDATA_STITCHANDSEW_
};

#endif // TOOLSTITCHANDSEW_H__
