#ifndef TOOLMODELINGAXIS_H__
#define TOOLMODELINGAXIS_H__

enum
{
	MDATA_SELECTION_TOLERANCE				= 2106,
	MDATA_SELECTION_VISIBLE					= 2107,

	// values between 20000-29999 will be placed in ID_MODELING_LIVESELECTION
	MDATA_AXIS_MODE		              = 20000,
		MDATA_AXIS_MODE_WORLD						= 0,
		MDATA_AXIS_MODE_OBJECT					= 1,
		MDATA_AXIS_MODE_SELECTED				= 2,
		MDATA_AXIS_MODE_ROOT						= 3,
		MDATA_AXIS_MODE_PARENT					= 4,
		MDATA_AXIS_MODE_BOUNDS					= 5,
		MDATA_AXIS_MODE_POINTS					= 6,
		MDATA_AXIS_MODE_CAMERA					= 7,
		MDATA_AXIS_MODE_FREE						= 8,

	MDATA_AXIS_FREE		              = 20001,
	MDATA_AXIS_FREE_MARK	          = 20002,
	MDATA_AXIS_BOUNDS_X	            = 20003,
	MDATA_AXIS_BOUNDS_Y	            = 20004,
	MDATA_AXIS_BOUNDS_Z	            = 20005,
	MDATA_AXIS_DIRTY		            = 20006, // private

	MDATA_AXIS_GROUP								= 20007,

	MDATA_AXIS_ROT									= 20008,
	MDATA_AXIS_NORMAL_PSR						= 20009,
	MDATA_AXIS_USER_POS							= 20010,
	MDATA_AXIS_USER_ROTATION				= 20011,
	MDATA_AXIS_USER_LOCK						= 20012,
	MDATA_AXIS_USER									= 20013,
	MDATA_AXIS_OBJECT_LINK					= 20014,
	MDATA_AXIS_INMOVE								= 20015,
	MDATA_AXIS_GIMBALROTATION				= 20016,
	MDATA_AXIS_USERAXIS							= 20017,
	MDATA_AXIS_DOCMODE							=	20018,
	MDATA_AXIS_COMPONENT						=	20019,
	MDATA_AXIS_LOCALMANIPULATION		=	20020,

	MDATA_OBJECTAXIS_GROUP					= 20021,

	MDATA_MODELINGAXIS_							= 29999,

	//////////////////////////////////////////////////////////////////////////

	MDATA_AXIS_ROT_AXIS = 0,
	MDATA_AXIS_ROT_WORLD,
	MDATA_AXIS_ROT_OBJECT,
	MDATA_AXIS_ROT_ROOT,
	MDATA_AXIS_ROT_PARENT,
	MDATA_AXIS_ROT_NORMALS,
	MDATA_AXIS_ROT_CAMERA,

	MDATA_AXIS_USER_WORLD = 0,
	MDATA_AXIS_USER_OBJECT,
	MDATA_AXIS_USER_CAMERA,

	//////////////////////////////////////////////////////////////////////////

	MDATA_AXIS_
};

#endif // TOOLMODELINGAXIS_H__
