#ifndef TPHCONSTRAINTMASK_H__
#define TPHCONSTRAINTMASK_H__

enum
{
	//==== Scene Calibration ====
	PH_CAL_GROUP_SCENE_CALIBRATION_MASK = 46000,
	// Mask
	PH_SCENE_CAL_MASK,

	PH_SCENE_CAL_MASK_INTEXT_MODE,
		PH_SCENE_CAL_MASK_INTEXT_MODE_INTERIOR,
		PH_SCENE_CAL_MASK_INTEXT_MODE_EXTERIOR,

	PH_SCENE_CAL_MASK_ADDSUB_MODE = 46100,
		PH_SCENE_CAL_MASK_ADDSUB_MODE_SUB,
		PH_SCENE_CAL_MASK_ADDSUB_MODE_ADD,
		PH_SCENE_CAL_MASK_ADDSUB_MODE_OBJECT_ASSIGN_LEGACY,

	PH_SCENE_CAL_MASK_FIRST_FRAME = 46150,
	PH_SCENE_CAL_MASK_LAST_FRAME,

	PH_SCENE_CAL_MASK_FORCE_UPDATE,

	PH_SCENE_CAL_MASK_LINKED_OBJECT_LEGACY = 48000,

	PH_MASK_INSERT_VERTEX_ON_EDGE = 50000,
	PH_MASK_DELETE_SELECTED_VERTICES,

	PH_SCENE_CAL_MASK_DISPLAY = 55000,
	PH_SCENE_CAL_MASK_DISPLAY_MASK,
	PH_SCENE_CAL_MASK_DISPLAY_COLOUR
};

#endif // TPHCONSTRAINTMASK_H__

