#ifndef VP_TONEMAPPING_H__
#define VP_TONEMAPPING_H__

enum
{
	VP_TONEMAPPING_OPERATOR										= 1000,
	VP_TONEMAPPING_LINEAR											= 0,
	VP_TONEMAPPING_PHOTOLINEAR								= 1,
	VP_TONEMAPPING_AUTOLINEAR									= 2,
	VP_TONEMAPPING_MAXWHITE										= 3,
	VP_TONEMAPPING_REINHARD02									= 4,

	VP_TONEMAPPING_SCALE											= 1001,
	VP_TONEMAPPING_EXPOSURE 									= 1002,
	VP_TONEMAPPING_SENSITIVITY 								= 1003,
	VP_TONEMAPPING_FSTOP 											= 1004,
	VP_TONEMAPPING_GAMMA 											= 1005,
	VP_TONEMAPPING_PRESCALE										= 1006,
	VP_TONEMAPPING_POSTSCALE									= 1007,
	VP_TONEMAPPING_BURN												= 1008,

	VP_TONEMAPPING_INFO												= 2000,
};

#endif // VPTONEMAPPING_H__
