#ifndef XMG_CAMERA_H__
#define XMG_CAMERA_H__

enum
{
	MGCAMERASHADER_LINK			= 1000,
	MGCAMERASHADER_HSCALE		= 1001,
	MGCAMERASHADER_VSCALE		= 1002,
	MGCAMERASHADER_CALC_FG	=	1003,
	MGCAMERASHADER_CALC_BG	= 1004
};
#endif // XMG_CAMERA_H__
