#ifndef _VMD_CAM_OBJ_H_
#define _VMD_CAM_OBJ_H_
enum 
{
	VMD_CAM_OBJ_ANIMATION_GRP = 1000,
	VMD_CAM_OBJ_FRAME_ON,
	VMD_CAM_OBJ_CURVE_TYPE,	

	VMD_CAM_OBJ_SPLINE,
	VMD_CAM_OBJ_INIT_CURVE_BUTTON,
	VMD_CAM_OBJ_REGISTER_CURVE_BUTTON,
	VMD_CAM_OBJ_UPDATE_CURVE_BUTTON,
	VMD_CAM_OBJ_DELETE_CURVE_BUTTON,
	VMD_CAM_OBJ_DELETE_ALL_CURVE_BUTTON,
	
	VMD_CAM_OBJ_XCURVE = 0,
	VMD_CAM_OBJ_YCURVE = 1,
	VMD_CAM_OBJ_ZCURVE = 2,
	VMD_CAM_OBJ_RCURVE = 3,
	VMD_CAM_OBJ_DCURVE = 4,
	VMD_CAM_OBJ_VCURVE = 5,
	VMD_CAM_OBJ_ACURVE = 6,

};

#endif _VMD_CAM_OBJ_H_