cmake_minimum_required(VERSION 3.23)

foreach(required SOURCE DESTINATION BUILD_ROOT DEFAULT_CONFIG)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Missing resource sync argument: ${required}")
  endif()
endforeach()
if(NOT DEFINED CONFIG_POLICY)
  set(CONFIG_POLICY reset)
endif()
if(NOT CONFIG_POLICY MATCHES "^(reset|preserve)$")
  message(FATAL_ERROR "CONFIG_POLICY must be reset or preserve")
endif()

if(CMAKE_HOST_WIN32)
  find_program(CMT_RESOURCE_PWSH NAMES pwsh REQUIRED)
  execute_process(COMMAND "${CMT_RESOURCE_PWSH}" -NoProfile -File
    "${CMAKE_CURRENT_LIST_DIR}/sync_runtime_resources.ps1"
    -Source "${SOURCE}" -Destination "${DESTINATION}" -BuildRoot "${BUILD_ROOT}"
    -DefaultConfig "${DEFAULT_CONFIG}" -ConfigPolicy "${CONFIG_POLICY}"
    COMMAND_ERROR_IS_FATAL ANY)
  return()
endif()

cmake_path(ABSOLUTE_PATH SOURCE NORMALIZE)
cmake_path(ABSOLUTE_PATH DESTINATION NORMALIZE)
cmake_path(ABSOLUTE_PATH BUILD_ROOT NORMALIZE)
cmake_path(IS_PREFIX BUILD_ROOT "${DESTINATION}" NORMALIZE inside_build)
cmake_path(IS_PREFIX SOURCE "${DESTINATION}" NORMALIZE inside_source)
cmake_path(IS_PREFIX BUILD_ROOT "${SOURCE}" NORMALIZE source_in_build)
cmake_path(GET DESTINATION FILENAME leaf)
if(NOT inside_build OR DESTINATION STREQUAL BUILD_ROOT OR inside_source OR source_in_build OR NOT leaf STREQUAL "res")
  message(FATAL_ERROR "Unsafe resource output: ${DESTINATION}")
endif()
cmake_path(GET DESTINATION PARENT_PATH ancestor)
while(NOT ancestor STREQUAL "")
  if(IS_SYMLINK "${ancestor}")
    message(FATAL_ERROR "Linked output ancestor is not allowed: ${ancestor}")
  endif()
  cmake_path(GET ancestor PARENT_PATH parent)
  if(parent STREQUAL ancestor)
    break()
  endif()
  set(ancestor "${parent}")
endwhile()

foreach(required c4d_symbols.h description dialogs strings_en-US strings_zh-CN)
  if(NOT EXISTS "${SOURCE}/${required}")
    message(FATAL_ERROR "Missing required resource: ${required}")
  endif()
endforeach()
file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE RELATIVE "${SOURCE}" "${SOURCE}/*")
if(IS_SYMLINK "${SOURCE}")
  message(FATAL_ERROR "Linked source resources are not allowed: ${SOURCE}")
endif()
foreach(entry IN LISTS entries)
  if(IS_SYMLINK "${SOURCE}/${entry}")
    message(FATAL_ERROR "Linked source resources are not allowed: ${entry}")
  endif()
endforeach()

set(config "${SOURCE}/cmt_config.json")
if(NOT EXISTS "${config}")
  set(config "${DEFAULT_CONFIG}")
endif()
if(CONFIG_POLICY STREQUAL "preserve" AND NOT IS_SYMLINK "${DESTINATION}" AND EXISTS "${DESTINATION}/cmt_config.json")
  if(IS_SYMLINK "${DESTINATION}/cmt_config.json")
    message(FATAL_ERROR "Cannot preserve a linked cmt_config.json")
  endif()
  set(config "${DESTINATION}/cmt_config.json")
endif()
file(READ "${config}" config_content)
string(JSON config_type ERROR_VARIABLE config_error TYPE "${config_content}")
if(config_error OR NOT config_type STREQUAL "OBJECT")
  message(FATAL_ERROR "cmt_config.json must contain a JSON object: ${config_error}")
endif()

string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef stage_id)
cmake_path(GET DESTINATION PARENT_PATH output_parent)
set(stage "${output_parent}/.res-stage-${stage_id}")
file(MAKE_DIRECTORY "${stage}")
file(COPY "${SOURCE}/" DESTINATION "${stage}")
file(WRITE "${stage}/cmt_config.json" "${config_content}")
foreach(entry IN LISTS entries)
  if(NOT IS_DIRECTORY "${SOURCE}/${entry}" AND NOT entry STREQUAL "cmt_config.json")
    file(SHA256 "${SOURCE}/${entry}" original_hash)
    file(SHA256 "${stage}/${entry}" copied_hash)
    if(NOT original_hash STREQUAL copied_hash)
      file(REMOVE_RECURSE "${stage}")
      message(FATAL_ERROR "Resource copy verification failed: ${entry}")
    endif()
  endif()
endforeach()
if(IS_SYMLINK "${DESTINATION}")
  file(REMOVE "${DESTINATION}")
else()
  file(REMOVE_RECURSE "${DESTINATION}")
endif()
file(RENAME "${stage}" "${DESTINATION}")
message(STATUS "Runtime resources copied: ${DESTINATION} (config: ${CONFIG_POLICY})")
