#ifndef FGLTFIMPORTER_H__
#define FGLTFIMPORTER_H__

enum
{
	GLTFIMPORTER_GROUP						= 999,

	GLTFIMPORTER_GROUP_SETTINGS,

	_DELME_GLTFIMPORTER_TARGET_IDSTRING, 		// not used, to be removed in 2025
	GLTFIMPORTER_UNITSCALE,
	GLTFIMPORTER_CAMERAS,
	GLTFIMPORTER_GEOMETRY,
	GLTFIMPORTER_NORMALS,
		GLTFIMPORTER_NORMALS_NONE,
		GLTFIMPORTER_NORMALS_VERTEX,
		GLTFIMPORTER_NORMALS_PHONG,
	GLTFIMPORTER_PHONGANGLE,
	GLTFIMPORTER_VERTEXCOLORS,
	GLTFIMPORTER_UVS,
	GLTFIMPORTER_FLIPZ,
	GLTFIMPORTER_MATERIALS,
	GLTFIMPORTER_ANIMATION_TRS,
		_DELME_GLTFIMPORTER_ANIMATION_NONE, 	// not used, to be removed in 2025
		
	_DELME_GLTFIMPORTER_ANIMATION_TRACKS, 	// not used, to be removed in 2025
	GLTFIMPORTER_ANIMATION_POSEMORPHS,

	GLTFIMPORTER_GEOMETRY_SPLIT_MESHPRIMS,
	GLTFIMPORTER_ANIMATION_CLEANTRACKS,
	GLTFIMPORTER_ANIMATION_POSEMORPHS_TARGETSLAYER,
	

	GLTFIMPORTER_GROUP_GEOMETRY,
	GLTFIMPORTER_GROUP_ANIMATION
};

#endif // FGLTFIMPORTER_H__
