#ifndef FLPARTICLEOBJECT_H__
#define FLPARTICLEOBJECT_H__

enum
{
	FIELDLAYER_PARTICLE_OBJECT = 1000, // Baselink
	FIELDLAYER_PARTICLE_DISTANCE = 1001, // Real
	FIELDLAYER_PARTICLE_CLIP = 1002, // Bool
	FIELDLAYER_PARTICLE_COLOR_ALPHA = 1003, // Long cycle
		FIELDLAYER_PARTICLE_COLOR_ALPHA_NONE = 0,
		FIELDLAYER_PARTICLE_COLOR_ALPHA_VALUE = 1,
	FIELDLAYER_PARTICLE_SOURCECHANNEL_VALUE = 1004, // Long cycle, filled dynamically
		FIELDLAYER_PARTICLE_SOURCECHANNEL_VALUE_FALLOFF = 0,
	FIELDLAYER_PARTICLE_SOURCECHANNEL_COLOR = 1005, // Long cycle, filled dynamically
		FIELDLAYER_PARTICLE_SOURCECHANNEL_COLOR_COLOR = 0,
	FIELDLAYER_PARTICLE_SOURCECHANNEL_DIRECTION = 1006, // Long cycle , filled dynamically
		FIELDLAYER_PARTICLE_SOURCECHANNEL_DIRECTION_VELOCITY = 0,
		FIELDLAYER_PARTICLE_SOURCECHANNEL_DIRECTION_TOPARTICLE = 1,
	FIELDLAYER_PARTICLE_SOURCE_MODE = 1007, // Long cycle
		FIELDLAYER_PARTICLE_SOURCE_MODE_NEAREST = 0,
		FIELDLAYER_PARTICLE_SOURCE_MODE_INDEX = 1,
		FIELDLAYER_PARTICLE_SOURCE_MODE_AVERAGE = 2,
		FIELDLAYER_PARTICLE_SOURCE_MODE_MAX = 3,
		FIELDLAYER_PARTICLE_SOURCE_MODE_MIN = 4,
	FIELDLAYER_PARTICLE_SOURCE_MODE_INDEX_MAP_UNIQUE = 1008, // Bool
	FIELDLAYER_PARTICLE_USE_PARTICLE_DISTANCE = 1009, // Bool
	FIELDLAYER_PARTICLE_SOURCECHANNEL_VALUE_CUSTOMPROPERTY_NAME = 1010,
	FIELDLAYER_PARTICLE_SOURCECHANNEL_VALUE_CUSTOMPROPERTY_POPUP = 1011,
	FIELDLAYER_PARTICLE_SOURCECHANNEL_DIRECTION_CUSTOMPROPERTY_NAME = 1012,
	FIELDLAYER_PARTICLE_SOURCECHANNEL_DIRECTION_CUSTOMPROPERTY_POPUP = 1013,
	FIELDLAYER_PARTICLE_SOURCECHANNEL_COLOR_CUSTOMPROPERTY_NAME = 1014,
	FIELDLAYER_PARTICLE_SOURCECHANNEL_COLOR_CUSTOMPROPERTY_POPUP = 1015,
	FIELDLAYER_PARTICLE_SOURCECHANNEL_CUSTOMPROPERTY = 1016
};

#endif // FLPARTICLEOBJECT_H__
