#ifndef FLPROXIMITY_H__
#define FLPROXIMITY_H__

enum
{
	FIELDLAYER_PROXIMITY_DYNAMIC_UPDATE = 1000,
	FIELDLAYER_PROXIMITY_RESET_FRAME_0_DEPRECATED = 1001,
	FIELDLAYER_PROXIMITY_FORCE_SAVE = 1002,
	FIELDLAYER_PROXIMITY_FORCE_SAVE2_DEPRECATED = 1003,
	FIELDLAYER_PROXIMITY_MODE = 1004,
	FIELDLAYER_PROXIMITY_RADIUS = 1005,
	FIELDLAYER_PROXIMITY_EFFECT_RATIO = 1006,
	FIELDLAYER_PROXIMITY_FORCE_CLEAR = 1007,
	FIELDLAYER_PROXIMITY_SELF_AGGREGATE = 1008,
	FIELDLAYER_PROXIMITY_FIELDS = 1009,
	FIELDLAYER_PROXIMITY_FIELDS_GRP = 1010,
	FIELDLAYER_PROXIMITY_USE_INPUT_CRC = 1011,

	// FIELDLAYER_PROXIMITY_MODE
	FIELDLAYER_PROXIMITY_MODE_NONE = 0,
	FIELDLAYER_PROXIMITY_MODE_MAX = 1,
	FIELDLAYER_PROXIMITY_MODE_MIN = 2,
	FIELDLAYER_PROXIMITY_MODE_AVG = 3,
	FIELDLAYER_PROXIMITY_MODE_GROW = 5,
	FIELDLAYER_PROXIMITY_MODE_EXTEND = 6,
};
#endif	// FLPROXIMITY_H__
