#ifndef FLTRACK_H__
#define FLTRACK_H__

enum
{
	TRACKFIELDLAYER_TRACK = 1149, 

	TRACKFIELDLAYER_DERIVATIVE = 1050,
		TRACKFIELDLAYER_DERIVATIVE_NONE = 0,
		TRACKFIELDLAYER_DERIVATIVE_FIRST = 1,
		TRACKFIELDLAYER_DERIVATIVE_SECOND = 2,

	TRACKFIELDLAYER_FROM_MIN = 1051,
	TRACKFIELDLAYER_FROM_MAX = 1052,
	TRACKFIELDLAYER_TO_MIN = 1053,
	TRACKFIELDLAYER_TO_MAX = 1054,
	TRACKFIELDLAYER_ABS = 1055,
	TRACKFIELDLAYER_RECALC = 1056,

	TRACKFIELDLAYER_FIELDS = 1057,	// FieldList
	TRACKFIELDLAYER_FIELDS_GRP = 1058,	// Group
	TRACKFIELDLAYER_OFFSET = 1059,
};
#endif	// FLTRACK_H__

