#ifndef FUSDEXPORTER_H__
#define FUSDEXPORTER_H__

enum
{
	USDEXPORTER_GROUP_SETTINGS = 999,

	_USDEXPORTER_GROUP_, // unused, move to the first place with major release
	USDEXPORTER_EXPORT2LAYER,
	USDEXPORTER_FILEFORMAT,
	USDEXPORTER_FILEFORMAT_USDA,
	USDEXPORTER_FILEFORMAT_USDC,
	USDEXPORTER_ZIP,
	USDEXPORTER_CAMERAS,
	USDEXPORTER_LIGHTUNITS,
	USDEXPORTER_LIGHTUNITS_NONE,
	USDEXPORTER_LIGHTUNITS_NIT,
	USDEXPORTER_LIGHTUNITS_CANDELA,

	USDEXPORTER_MATERIALS,
	USDEXPORTER_MATERIALS_BRIDGE,
	USDEXPORTER_MATERIALS_BRIDGE_INFO,

	USDEXPORTER_MATERIALS_BAKETEXTURES,
	USDEXPORTER_MATERIALS_WIDTH,
	USDEXPORTER_MATERIALS_HEIGHT,
	USDEXPORTER_MATERIALS_DEPTH,
	USDEXPORTER_MATERIALS_DEPTH_8,
	USDEXPORTER_MATERIALS_DEPTH_16,
	USDEXPORTER_MATERIALS_DEPTH_32,

	USDEXPORTER_MATERIALS_FORMAT,
	USDEXPORTER_MATERIALS_FORMAT_STRINGIFIED_ID,
	USDEXPORTER_MATERIALS_FORMAT_USDZ,
	USDEXPORTER_MATERIALS_FORMAT_USDZ_STRINGIFIED_ID,

	USDEXPORTER_GROUP_GEOMETRY,
	USDEXPORTER_GEOMETRY,
	USDEXPORTER_GEOMETRY_NORMALS,
	USDEXPORTER_GEOMETRY_UV,
	USDEXPORTER_GEOMETRY_DISPLAYCOLOR,
	USDEXPORTER_GEOMETRY_VERTEXCOLORS,

	USDEXPORTER_MATERIALS_NONE,
	USDEXPORTER_MATERIALS_EXPORT,
	USDEXPORTER_MATERIALS_EXPORTANDBRIDGE,

	USDEXPORTER_MATERIALS_RESIZE,
	USDEXPORTER_MATERIALS_RESIZE_OFF,
	USDEXPORTER_MATERIALS_RESIZE_DONT_ENLARGE,
	USDEXPORTER_MATERIALS_RESIZE_ALWAYS,

	USDEXPORTER_GROUP_ANIMATION,
	USDEXPORTER_ANIMATION_FRAMES,
	USDEXPORTER_ANIMATION_FRAMES_CURRENTFRAME,
	USDEXPORTER_ANIMATION_FRAMES_PREVIEWRANGE,
	USDEXPORTER_ANIMATION_FRAMES_ALLFRAMES,
	USDEXPORTER_ANIMATION_FRAMES_ALLANIMATEDFRAMES,
	USDEXPORTER_ANIMATION_FRAMES_MANUAL,
	USDEXPORTER_ANIMATION_TIMEFROM,
	USDEXPORTER_ANIMATION_TIMETO,
	
	USDEXPORTER_INSTANCES,

	USDEXPORTER_GROUP_MATERIALS,

	USDEXPORTER_ANIMATION_SKELETON,

	_USDEXPORTER_END_
};

#endif // FUSDEXPORTER_H__