#ifndef FUSDIMPORTER_H__
#define FUSDIMPORTER_H__

enum
{
	_USDIMPORTER_GROUP_ = 999, // unused

	USDIMPORTER_GROUP_SETTINGS,
	USDIMPORTER_KEEPBRIDGEOPEN,
	USDIMPORTER_CAMERAS,
	USDIMPORTER_LIGHTUNITS,
	USDIMPORTER_LIGHTUNITS_NONE,
	USDIMPORTER_LIGHTUNITS_NIT,
	USDIMPORTER_LIGHTUNITS_CANDELA,
	USDIMPORTER_LIGHTUNITS_PERCENT,
	USDIMPORTER_MATERIALS,
	
	USDIMPORTER_GROUP_GEOMETRY,
	USDIMPORTER_GEOMETRY,
	USDIMPORTER_GEOMETRY_NORMALS,
	USDIMPORTER_GEOMETRY_NORMALS_NONE,
	USDIMPORTER_GEOMETRY_NORMALS_VERTEX,
	USDIMPORTER_GEOMETRY_NORMALS_PHONG,
	USDIMPORTER_GEOMETRY_PHONG_ANGLE,
	USDIMPORTER_GEOMETRY_UV,
	USDIMPORTER_GEOMETRY_DISPLAYCOLOR,

	USDIMPORTER_INSTANCES,

	USDIMPORTER_GROUP_ANIMATION,
	USDIMPORTER_ANIMATION_CLEANTRACKS,
	USDIMPORTER_ANIMATION_TRS,
	USDIMPORTER_ANIMATION_SKELETAL,

	_USDIMPORTER_END_,
};

#endif // FUSDIMPORTER_H__