#ifndef GVBOX_H__
#define GVBOX_H__

#include "gvbase.h"

enum
{
	GV_BOX_MODE									= 1000,
		GV_BOX_OPERATOR_MODE_GLOBAL = 100,
		GV_BOX_OPERATOR_MODE_LOCAL,
	GV_BOX_USE_DEFORMED,
	GV_BOX_USE_HIERARCHY,

	GV_BOX_INPUT_OBJECT					= 2000,

	GV_BOX_OUTPUT_POINT_MIN				= 3000,
	GV_BOX_OUTPUT_POINT_MAX,
	GV_BOX_OUTPUT_POINT1,
	GV_BOX_OUTPUT_POINT2,
	GV_BOX_OUTPUT_POINT3,
	GV_BOX_OUTPUT_POINT4,
	GV_BOX_OUTPUT_POINT5,
	GV_BOX_OUTPUT_POINT6,
	GV_BOX_OUTPUT_POINT7,
	GV_BOX_OUTPUT_POINT8,
	GV_BOX_OUTPUT_POINT_SIZE,

	GV_BOX_
};

#endif // GVBOX_H__
