#ifndef GVCOLLISION_H__
#define GVCOLLISION_H__

#include "gvbase.h"

enum
{
	GV_COLLISION_MODE									= 1000,
		GV_COLLISION_OPERATOR_MODE_GLOBAL = 100,
		GV_COLLISION_OPERATOR_MODE_LOCAL,
	GV_COLLISION_USE_DEFORMED,
	GV_COLLISION_USE_HIERARCHY,
	GV_COLLISION_TYPE									= 1100,
		GV_COLLISION_OPERATOR_TYPE_CUBE = 100,
		GV_COLLISION_OPERATOR_TYPE_SPHERE,
		GV_COLLISION_OPERATOR_TYPE_POLYGON,
		GV_COLLISION_OPERATOR_TYPE_DISTANCE,
		GV_COLLISION_OPERATOR_TYPE_TOLERANCE,
	GV_COLLISION_SELECTION1 = 1200,
	GV_COLLISION_SELECTION2,

	GV_COLLISION_INPUT_OBJECT1					= 2000,
	GV_COLLISION_INPUT_OBJECT2,
	GV_COLLISION_INPUT_TOLERANCE,

	GV_COLLISION_OUTPUT						= 3000,
	GV_COLLISION_OUTPUT_DISTANCE,
	GV_COLLISION_OUTPUT_OBJECT,
	GV_COLLISION_OUTPUT_INDEX1,
	GV_COLLISION_OUTPUT_INDEX2,
	GV_COLLISION_OUTPUT_POINT1,
	GV_COLLISION_OUTPUT_POINT2,

	GV_COLLISION_
};

#endif // GVCOLLISION_H__
