#ifndef GVFLOATMATH_H__
#define GVFLOATMATH_H__

#include "gvdynamic.h"

enum
{
	GV_FLOATMATH_FUNCTION_ID			= 1000,
		GV_ADR_NODE_FUNCTION		= 0,
		GV_SUR_NODE_FUNCTION,
		GV_MUR_NODE_FUNCTION,
		GV_DIR_NODE_FUNCTION,

	GV_FLOATMATH_INPUT						= 2000,
	GV_FLOATMATH_REAL,
	GV_FLOATMATH_OUTPUT					= 3000,

	GV_FLOATMATH_
};

#endif // GVFLOATMATH_H__
