#ifndef GVHIERARCHY_H__
#define GVHIERARCHY_H__

enum
{
	GV_HIERARCHY_OBJECT_ID = 1001,
	GV_HIERARCHY_PATH_TYPE,
		GV_HIERARCHY_PATH_TYPE_START = 0,
		GV_HIERARCHY_PATH_TYPE_ABSOLUTE,
		GV_HIERARCHY_PATH_TYPE_RELATIVE,
	GV_HIERARCHY_START_TYPE_ID = 1003,
	GV_HIERARCHY_DISTANCE_ID,
	GV_HIERARCHY_PATH_ID,
	GV_HIERARCHY_ITERATION_ID,
	GV_HIERARCHY_START_ID,
	GV_HIERARCHY_EXCLUDE_ID,

	GV_HIERARCHY_INPUT_OBJECT = 2000,
	GV_HIERARCHY_INPUT_MAX,
	GV_HIERARCHY_OPERATOR_ON,

	GV_HIERARCHY_OUTPUT_OBJECT = 3000,
	GV_HIERARCHY_OUTPUT_COUNT,

	GV_HIERARCHY_
};

#endif // GVHIERARCHY_H__
