#ifndef GVITERATE_H__
#define GVITERATE_H__

#include "gvdynamic.h"

enum
{
	GV_ITERATE_INPUT_LOWER = 2000,
	GV_ITERATE_INPUT_UPPER,
	GV_ITERATE_OPERATOR_ON,
	GV_ITERATE_LINK_INPUT,

	GV_ITERATE_OUTPUT = 3000,
	GV_ITERATE_OUTPUT_COUNT,
	GV_ITERATE_LINK_OUTPUT,

	GV_ITERATE_
};

#endif // GVITERATE_H__
