#ifndef GVMONOFLOP_H__
#define GVMONOFLOP_H__

#include "gvbase.h"

enum
{
	GV_MONOFLOP_MODE = 1000,
		GV_MONOFLOP_NORMAL = 0,
		GV_MONOFLOP_ONESHOT,

	GV_MONOFLOP_TRIGGER = 2000,
	GV_MONOFLOP_TIME,
	GV_MONOFLOP_DURATION,
	GV_MONOFLOP_RESET,

	GV_MONOFLOP_OUT = 3000,
	GV_MONOFLOP_COUNT,
	GV_MONOFLOP_STATE,

	GV_MONOFLOP_
};

#endif // GVMONOFLOP_H__
