#ifndef GVNEARESTPOINTONSPLINE_H__
#define GVNEARESTPOINTONSPLINE_H__

#include "gvbase.h"

enum
{
	GV_NEARESTPOINTONSPLINE_INPUT_SPLINEOBJECT			= 2000,
	GV_NEARESTPOINTONSPLINE_INPUT_GLOBALPOSITION		= 2001,
	GV_NEARESTPOINTONSPLINE_INPUT_PRECISION					= 2002,
	GV_NEARESTPOINTONSPLINE_INPUT_SPLINESEGMENT			= 2003,
	GV_NEARESTPOINTONSPLINE_INPUT_ALLSEGMENTS				= 2004,

	GV_NEARESTPOINTONSPLINE_OUTPUT_SPLINEPOSITION		= 3000,
	GV_NEARESTPOINTONSPLINE_OUTPUT_NEARESTPOINT     = 3001,
	GV_NEARESTPOINTONSPLINE_OUTPUT_NEARESTSEGMENT		= 3002,
	GV_NEARESTPOINTONSPLINE_OUTPUT_TANGENT					= 3003,

	GV_NEARESTPOINTONSPLINE_
};

#endif // GVNEARESTPOINTONSPLINE_H__
