#ifndef GVOBJECT_H__
#define GVOBJECT_H__

enum
{
	GV_OBJECT_OBJECT_ID 				= 1000,
	GV_OBJECT_PATH_TYPE					= 1001,
		GV_OBJECT_PATH_TYPE_START			= 0,
		GV_OBJECT_PATH_TYPE_ABSOLUTE	= 1,
		GV_OBJECT_PATH_TYPE_RELATIVE	= 2,
	GV_OBJECT_START_TYPE_ID			= 1002,
	GV_OBJECT_HISTORY_DEPTH_ID	= 1003,
	GV_OBJECT_DISTANCE_ID				= 1004,
	GV_OBJECT_PATH_ID						= 1005,

	GV_OBJECT_OPERATOR_LOCAL_IN = 30000000, //GV_INPUT_FIRST_PRIVATE_ID,
	GV_OBJECT_OPERATOR_GLOBAL_IN,
	GV_OBJECT_OPERATOR_HISTORY_IN,
	GV_OBJECT_OPERATOR_OBJECT_IN,
	GV_OBJECT_OPERATOR_ON,

	GV_OBJECT_OPERATOR_LOCAL_OUT = 40000000, //GV_OUTPUT_FIRST_PRIVATE_ID,
	GV_OBJECT_OPERATOR_GLOBAL_OUT,
	GV_OBJECT_OPERATOR_OBJECT_OUT,
	GV_OBJECT_OPERATOR_OLD_POS_OUT,
	GV_OBJECT_OPERATOR_OLD_ROT_OUT,
	GV_OBJECT_OPERATOR_OLD_SIZE_OUT,
	GV_OBJECT_OPERATOR_OLD_GLOBAL_OUT,
	GV_OBJECT_OPERATOR_OLD_LOCAL_OUT,
	GV_OBJECT_OPERATOR_VELOCITY_POS_OUT,
	GV_OBJECT_OPERATOR_VELOCITY_ROT_OUT,
	GV_OBJECT_OPERATOR_VELOCITY_SIZE_OUT
};

#endif // GVOBJECT_H__
