#ifndef NEUTRONSCENEHOOK_H__
#define NEUTRONSCENEHOOK_H__

enum
{
	CONVERT_BXDF_TO_COLORCHANNEL = 3,

	NEUTRON_SEPARATOR = 4,
	CONVERT_BXDF_TO_COLORCHANNEL_SEPARATOR = 5,

	NEUTRON_VIEWPORT_MODE = 10000,
	NEUTRON_VIEWPORT_MODE_NONE = 0,
	NEUTRON_VIEWPORT_MODE_NEUTRON = 1,
	NEUTRON_VIEWPORT_MODE_LEGACY = 2,

	NEUTRON_GROUP = 11000,

	NEUTRON_RENDER_ONLY = 12000,

	NEUTRONSCENEHOOK_DUMMY,
};

#endif // NEUTRONSCENEHOOK_H__
