#ifndef NEUTRONSPLINEPRIMITIVEGENERATOR_H__
#define NEUTRONSPLINEPRIMITIVEGENERATOR_H__

enum
{
	NEUTRON_SPLINEOBJECT_OPEN = 0,
	NEUTRON_SPLINEOBJECT_CLOSED,
	NEUTRON_SPLINEOBJECT_AUTO,
	NEUTRONSPLINEPRIMITIVEGENERATOR_DUMMY
};

#endif // NEUTRONSPLINEPRIMITIVEGENERATOR_H__
