#ifndef OARRAY_H__
#define OARRAY_H__

enum
{
	ARRAYOBJECT_RADIUS			= 1000,
	ARRAYOBJECT_COPIES			= 1001,
	ARRAYOBJECT_AMPLITUDE		= 1002,
	ARRAYOBJECT_FREQUENCY		= 1003,
	ARRAYOBJECT_CIRCLEFREQ	= 1004,
	ARRAYOBJECT_RENDERINSTANCES = 1005
};

#endif // OARRAY_H__
