#ifndef OATTRACTOR_H__
#define OATTRACTOR_H__

enum
{
	ATTRACTOROBJECT_STRENGTH	 		= 1000,
	ATTRACTOROBJECT_SIZE			 		= 1001,
	ATTRACTOROBJECT_SPEEDLIMIT 		= 1002,
	ATTRACTOROBJECT_FALLOFF_MODE 	= 1003,
		ATTRACTOROBJECT_FALLOFF_MODE_INV_SQUARED_DIST	= 0,
		ATTRACTOROBJECT_FALLOFF_MODE_INV_DIST					= 1,
		ATTRACTOROBJECT_FALLOFF_MODE_LINEAR						= 2,
	ATTRACTOROBJECT_MIN_DISTANCE 	= 1004,
};

#endif // OATTRACTOR_H__
