#ifndef OBASEMOGEN_H__
#define OBASEMOGEN_H__

enum
{
	ID_MG_MOTIONGENERATOR_GROUP_EFFECTORS = 990,	// Effectors Group
	ID_MG_MOTIONGENERATOR_GROUP_TRANSFORM = 991,	// Transform Group
	ID_MG_MOTIONGENERATOR_GROUP_TRNPSR	= 992,	// Transform PSR Group
	ID_MG_MOTIONGENERATOR_GROUP_TRNRANDOM = 993,	// Transform Randomize Group

	ID_MG_MOTIONGENERATOR_DRAW = 2000,	// Allow grid drawing
	ID_MG_MOTIONGENERATOR_EFFECTORLIST = 2009,	// Effectors list

	ID_MG_MOTIONGENERATOR_DEPRECATED3 = 2100,
	ID_MG_MOTIONGENERATOR_DEPRECATED4 = 2101,
	ID_MG_MOTIONGENERATOR_DEPRECATED5 = 2102,
	ID_MG_MOTIONGENERATOR_DEPRECATED6 = 2103,
	ID_MG_MOTIONGENERATOR_DEPRECATED7 = 2104,
	ID_MG_MOTIONGENERATOR_DEPRECATED8 = 2105,

	ID_MG_DEFORMED_MOMATRIX = 2106,
};

#endif // OBASEMOGEN_H__
