#ifndef OBASEMOGENDISTRIBUTIONMODES_H__
#define OBASEMOGENDISTRIBUTIONMODES_H__

enum
{
	ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTION = 994,	// Distributions
	ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTIONSELECTEDUI = 995, // Distribution pattern UI
	ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTION_SUBGROUP = 996, // Distribution wrapper group to hide everything when disabled
	ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTIONMODE = 997,

	ID_MG_MOTIONGENERATOR_MODE = 2010, // Cloning mode
	ID_MG_MOTIONGENERATOR_MODE_OBJECT = 0, // Object cloning mode
	ID_MG_MOTIONGENERATOR_MODE_LINEAR = 1, // Linear cloning mode
	ID_MG_MOTIONGENERATOR_MODE_RADIAL = 2, // Radial cloning mode
	ID_MG_MOTIONGENERATOR_MODE_GRIDARRAY = 3, // Grid Array cloning mode
	ID_MG_MOTIONGENERATOR_MODE_HEXARRAY = 4, // Honeycomb Grid Array cloning mode
	ID_MG_MOTIONGENERATOR_MODE_NODES = 5, // Nodes distribution mode
	ID_MG_MOTIONGENERATOR_MODE_RESERVED	= 2011,	// Future for using new modes
	ID_MG_MOTIONGENERATOR_DEPRECATED2 = 2014,

	ID_MG_DISTRIBUTIONTYPE = 2107,
		ID_MG_DISTRIBUTIONTYPE_CLASSIC = 0,
		ID_MG_DISTRIBUTIONTYPE_NODE = 1,
	ID_MG_NODEDISTRIBUTION_LINK_INTERNAL_DEPRECATED = 2108,
	ID_MG_NODEDISTRIBUTION_BROWSE = 2109,
	ID_MG_NODEDISTRIBUTION_CREATE = 2110,
	ID_MG_NODEDISTRIBUTION_EDIT_DEPRECATED = 2111,
	ID_MG_NODEDISTRIBUTION_NAME_DEPRECATED = 2112,
	ID_MG_NODEDISTRIBUTION_REVEAL_DEPRECATED = 2113,
	ID_MG_NODEDISTRIBUTION_EXTERNAL_DEPRECATED = 2114,
	ID_MG_NODEDISTRIBUTION_LINK_EXTERNAL = 2115,
	ID_MG_NODEDISTRIBUTION_BUTTONS_GROUP = 2116,
};

#endif // OBASEMOGENDISTRIBUTIONMODES_H__
