#ifndef OBOOLEANGENERATOR_H__
#define OBOOLEANGENERATOR_H__

enum
{
  BOOLEANGENERATOR_OPERATION = 1001,               // LONG
    BOOLEANGENERATOR_OPERATION_NONE = 0,
    BOOLEANGENERATOR_OPERATION_UNION = 1,
		BOOLEANGENERATOR_OPERATION_SUBTRACT = 2,
		BOOLEANGENERATOR_OPERATION_INTERSECT = 3,
	  BOOLEANGENERATOR_OPERATION_WITHOUT = 4,
  BOOLEANGENERATOR_PREPROCESS = 1002,               // BOOL
  ID_BOOLEANGENERATOR_SELECTION = 1003,             // SEPARATOR
	BOOLEANGENERATOR_SELECTION_INTERSECT = 1006,      // BOOL
  BOOLEANGENERATOR_SELECTION_INTERSECT_NAME = 1007, // BOOL
  BOOLEANGENERATOR_HIGH_QUALITY_NORMALS = 1010      // BOOL
};

#endif // OBOOLEANGENERATOR_H__
