#ifndef OENVIRONMENT_H__
#define OENVIRONMENT_H__

enum
{
	ENVIRONMENT_AMBIENT						= 1000,  // VECTOR
	ENVIRONMENT_AMBIENTSTRENGTH		= 1001,  // REAL
	ENVIRONMENT_FOGENABLE					= 1002,  // BOOL
	ENVIRONMENT_FOG								= 1003,  // VECTOR
	ENVIRONMENT_FOGSTRENGTH				= 1004,  // REAL
	ENVIRONMENT_FOGDISTANCE				= 1005,  // REAL
	ENVIRONMENT_AFFECTBACKGROUND  = 1006   // BOOL
};

#endif // OENVIRONMENT_H__
