#ifndef OFPBLEND_H__
#define OFPBLEND_H__

enum
{
	FP_BLEND_OBJECT_GROUP = 2000,
	FP_BLEND_OBJECT_GLOBAL_STRENGTH = 2001,
	FP_BLEND_OBJECT_RADIUS = 2002,
	FP_BLEND_OBJECT_RANDOM_STRENGTH = 2003,
	FP_BLEND_OBJECT_RANDOM_SCALE = 2004,
	FP_BLEND_OBJECT_RANDOM_FREQUENCY = 2005,
	FP_BLEND_OBJECT_RANDOM_GROUP = 2006,
	FP_BLEND_OBJECT_BLEND_MODE = 2007,
	  FP_BLEND_OBJECT_BLEND_MODE_NORMAL = 0,
	  FP_BLEND_OBJECT_BLEND_MODE_MIN = 1,
	  FP_BLEND_OBJECT_BLEND_MODE_MAX = 2,
	  FP_BLEND_OBJECT_BLEND_MODE_ADD = 3,
	  FP_BLEND_OBJECT_BLEND_MODE_SUB = 4,
	  FP_BLEND_OBJECT_BLEND_MODE_MUL = 5,
	FP_BLEND_OBJECT_DISTANCEFALLOFF = 2008,
	FP_BLEND_EXCLUDED_GROUP = 2009,
	FP_BLEND_EXCLUDED_GROUP_CREATE = 2010,
	FP_BLEND_OBJECT_MAXIMUM_CHECKS = 2011,
	FP_BLEND_OBJECT_DETECTION_MODE = 2012,
		FP_BLEND_OBJECT_DETECTION_MODE_FIXED = 0,
		FP_BLEND_OBJECT_DETECTION_MODE_DYNAMIC = 1,
		FP_BLEND_OBJECT_DETECTION_MODE_FULL = 2,

	FP_BLEND_OBJECT_OUTPUT = 3000,
	FP_BLEND_OBJECT_OUTPUT_NEIGHBOURCOUNT = 3001,
	FP_BLEND_OBJECT_OUTPUT_NEIGHBOURCOUNT_ATTRIBUTE_NAME = 3002,
	FP_BLEND_OBJECT_OUTPUT_NEIGHBOURCOUNT_ATTRIBUTE_POPUP = 3003,

	FP_BLEND_OBJECT_DUMMY
};

#endif // OFPBLEND_H__
