#ifndef OFPCONDITION_H__
#define OFPCONDITION_H__

enum
{
	FP_CONDITION_BYPASS = 1000,
	FP_CONDITION_GROUP = 2000,
	FP_CONDITION_CMPOPERATOR = 2006,
		FP_CONDITION_CMPOPERATOR_EQUALS = 0,
		FP_CONDITION_CMPOPERATOR_GREATERTHAN,
		FP_CONDITION_CMPOPERATOR_GREATERTHANEQUALS,
		FP_CONDITION_CMPOPERATOR_INSIDE,
		FP_CONDITION_CMPOPERATOR_LESSTHAN,
		FP_CONDITION_CMPOPERATOR_LESSTHANEQUALS,
		FP_CONDITION_CMPOPERATOR_NOTEQUALS,
		FP_CONDITION_CMPOPERATOR_OUTSIDE,
	FP_CONDITION_CMPLINK = 2007,
	FP_CONDITION_CMPFLOATVALUE = 2008,
	FP_CONDITION_CMPFLOATRANGE_LOWER = 2010,
	FP_CONDITION_CMPFLOATRANGE_UPPER = 2011,
	FP_CONDITION_CMPERRORTOLERANCE = 2014,
	FP_CONDITION_COMBINE_MODE = 2018,
		FP_CONDITION_COMBINE_MODE_AND = 0,
		FP_CONDITION_COMBINE_MODE_OR = 1,
		FP_CONDITION_COMBINE_MODE_XOR = 2,
		FP_CONDITION_COMBINE_MODE_INVERSE = 3,
	FP_CONDITION_CHANCE = 2019,
	FP_CONDITION_SEED = 2020,
	FP_CONDITION_INPUT_FORMULA_GROUP = 2021,
	FP_CONDITION_INPUT_FORMULA = 2022,
	FP_CONDITION_INPUT_FORMULA_VALUE = 2023,
	FP_CONDITION_GROUP_CMPOPERATOR = 2024,
	FP_CONDITION_ALIGN_CMPOPERATOR = 2025,
	FP_CONDITION_DRAW_DISTANCE = 2026,
	FP_CONDITION_CMPINTVALUE = 2027,
	FP_CONDITION_CMPINTRANGE_LOWER = 2028,
	FP_CONDITION_CMPINTRANGE_UPPER = 2029,
	FP_CONDITION_CMPBOOLVALUE = 2030,
	FP_CONDITION_OBJECT_DUMMY
};

#endif // OFPCONDITION_H__
