#ifndef OFPLIQUIDHOSEEMITTER_H__
#define OFPLIQUIDHOSEEMITTER_H__

enum
{
	// SOURCE
	FP_LIQUIDHOSEEMITTER_SOURCE = 1000,
	FP_LIQUIDHOSEEMITTER_SOURCE_SHAPE = 1001,
		FP_LIQUIDHOSEEMITTER_SOURCE_SHAPE_SQUARE = 0,
		FP_LIQUIDHOSEEMITTER_SOURCE_SHAPE_CIRCLE = 1,
	FP_LIQUIDHOSEEMITTER_SOURCE_SHAPE_SIZE = 1002,
	FP_LIQUIDHOSEEMITTER_OUTPUT = 2000,
	FP_LIQUIDHOSEEMITTER_OUTPUT_UVW = 2001,
	FP_LIQUIDHOSEEMITTER_OUTPUT_UVW_ATTRIBUTE_NAME = 2002,
	FP_LIQUIDHOSEEMITTER_OUTPUT_UVW_ATTRIBUTE_POPUP = 2003,
	FP_LIQUIDHOSEEMITTER_OUTPUT_UVW_ATTRIBUTE_CREATE = 2004,
	FP_LIQUIDHOSEEMITTER_OUTPUT_BORN = 2006,
	FP_LIQUIDHOSEEMITTER_OUTPUT_BORN_ATTRIBUTE_NAME = 2007,
	FP_LIQUIDHOSEEMITTER_OUTPUT_BORN_ATTRIBUTE_POPUP = 2008,
	FP_LIQUIDHOSEEMITTER_OUTPUT_BORN_ATTRIBUTE_CREATE = 2009,
	// Emission scatter
	FP_LIQUIDHOSEEMITTER_SCATTER = 3001,
		FP_LIQUIDHOSEEMITTER_SCATTER_GRID = 0,
		FP_LIQUIDHOSEEMITTER_SCATTER_RANDOM = 1,
		FP_LIQUIDHOSEEMITTER_SCATTER_SPHEREPACKING = 2,
	FP_LIQUIDHOSEEMITTER_SCATTER_JITTER = 3002,
	FP_LIQUIDHOSEEMITTER_SCATTER_BORDER_THRESHOLD = 3003,
	FP_LIQUIDHOSEEMITTER_SCATTER_SPHEREPACKING_HEXDIRECTION = 3004,
	// FP_LIQUIDHOSEEMITTER_RESOLUTION = 3002,
	// 	FP_LIQUIDHOSEEMITTER_RESOLUTION_SIMULATIONSCENE = 0,
	// 	FP_LIQUIDHOSEEMITTER_RESOLUTION_OVERRIDE = 1,
	// FP_LIQUIDHOSEEMITTER_RESOLUTION_DISTANCE = 3003,

	FP_LIQUIDHOSEEMITTER_DUMMY
};

#endif // OFPLIQUIDHOSEEMITTER_H__
