#ifndef OFPLIQUIDFILLEMITTER_H__
#define OFPLIQUIDFILLEMITTER_H__

enum
{
	// Source
	FP_LIQUIDFILLEMITTER_MESH = 1000,
	FP_LIQUIDFILLEMITTER_MESH_RESOLUTION_DISTANCE = 1002,
	FP_LIQUIDFILLEMITTER_MESH_SCATTER = 1004,
		FP_LIQUIDFILLEMITTER_MESH_SCATTER_GRID = 0,
		FP_LIQUIDFILLEMITTER_MESH_SCATTER_SPHEREPACKING = 2,
	FP_LIQUIDFILLEMITTER_MESH_RESOLUTION = 1005,
		FP_LIQUIDFILLEMITTER_MESH_RESOLUTION_SIMULATIONSCENE = 0,
		FP_LIQUIDFILLEMITTER_MESH_RESOLUTION_OVERRIDE = 1,
	FP_LIQUIDFILLEMITTER_FILL_DIRECTION = 1006,
		FP_LIQUIDFILLEMITTER_FILL_DIRECTION_POSX = 0,
		FP_LIQUIDFILLEMITTER_FILL_DIRECTION_NEGX = 1,
		FP_LIQUIDFILLEMITTER_FILL_DIRECTION_POSY = 2,
		FP_LIQUIDFILLEMITTER_FILL_DIRECTION_NEGY = 3,
		FP_LIQUIDFILLEMITTER_FILL_DIRECTION_POSZ = 4,
		FP_LIQUIDFILLEMITTER_FILL_DIRECTION_NEGZ = 5,
	FP_LIQUIDFILLEMITTER_FILL_SPACE = 1007,
		FP_LIQUIDFILLEMITTER_FILL_SPACE_GLOBAL = 0,
		FP_LIQUIDFILLEMITTER_FILL_SPACE_LOCAL = 1,
	FP_LIQUIDFILLEMITTER_FILL_PERCENTAGE = 1008,
	// Output
	FP_LIQUIDFILLEMITTER_OUTPUT = 3000,
	FP_LIQUIDFILLEMITTER_OUTPUT_BORN = 3013,
	FP_LIQUIDFILLEMITTER_OUTPUT_BORN_ATTRIBUTE_NAME = 3014,
	FP_LIQUIDFILLEMITTER_OUTPUT_BORN_ATTRIBUTE_POPUP = 3015,
	FP_LIQUIDFILLEMITTER_OUTPUT_BORN_ATTRIBUTE_CREATE = 3016,
	// Draw
	FP_LIQUIDFILLEMITTER_DRAW = 4000,
	FP_LIQUIDFILLEMITTER_DRAW_GEOMETRY = 4001,
	FP_LIQUIDFILLEMITTER_DUMMY
};

#endif // OFPLIQUIDFILLEMITTER_H__
