#ifndef OFPLIQUIFY_H__
#define OFPLIQUIFY_H__

enum
{
    FP_LIQUIFY_GROUP = 1000,
    FP_LIQUIFY_MODE = 1001,
        FP_LIQUIFY_MODE_LIQUIFY = 0,
        FP_LIQUIFY_MODE_SET = 1,
        FP_LIQUIFY_MODE_UNLIQUIFY = 2,
    FP_LIQUIFY_LIQUIDCONTRIBUTION = 1002,
    FP_LIQUIFY_USEDEFAULTRADIUS = 1003,
    FP_LIQUIFY_CONSTRAINTS_GROUP = 2000,
    FP_LIQUIFY_CONSTRAINTS_MASSDENSITY = 2001,
    FP_LIQUIFY_CONSTRAINTS_VISCOSITY = 2002,
    FP_LIQUIFY_CONSTRAINTS_SURFACETENSION =  2003,
    FP_LIQUIFY_CONSTRAINTS_MIXTUREID = 2004,
    FP_LIQUIFY_CONSTRAINTS_EASEIN = 2005,
    FP_LIQUIFY_COLLISIONS_GROUP = 3000,
    FP_LIQUIFY_COLLISIONS_FRICTION = 3001,
    FP_LIQUIFY_COLLISIONS_STICKINESS = 3002,
		FP_LIQUIFY_COLLISIONS_INTERACTION_MASS = 3003,
    FP_LIQUIFY_DAMPING_GROUP = 4000,
    FP_LIQUIFY_DAMPING_DAMPING = 4001,
	FP_LIQUIFY_DUMMY
};

#endif // OFPLIQUIFY_H__
