#ifndef OFPMULTIGROUP_H__
#define OFPMULTIGROUP_H__

enum
{
	FP_MULTI_GROUP_OBJECT_GROUP = 2000,	
	FP_MULTI_GROUP_SCENE_LINK_LIST = 2001,

	FP_MULTI_GROUP_OBJECT_DUMMY
};

#endif // OFPMULTIGROUP_H__
