#ifndef OFPNEUTRON_H__
#define OFPNEUTRON_H__

enum
{
	OFPNEUTRON_GROUP = 1000,
	OFPNEUTRON_EXECUTION_MODE = 1001,
		OFPNEUTRON_EXECUTION_MODE_SUBSTEP = 0,
		OFPNEUTRON_EXECUTION_MODE_SUBSTEP_FIRST = 1,
		OFPNEUTRON_EXECUTION_MODE_SUBSTEP_LAST = 2,
	OFPNEUTRON_EXECUTION_FIELDLIST = 1002,
	OFPNEUTRON_EXECUTION_FIELD_GROUP = 1003,
	OFPNEUTRON_ALL_DATA_MODE = 1004,
		OFPNEUTRON_ALL_DATA_MODE_MASKED = 0,
		OFPNEUTRON_ALL_DATA_MODE_ALL = 1,
	OFPNEUTRON_SCENE_LINK = 1005, // internal use only
	OFPNEUTRON_DUMMY_
};

#endif // OFPNEUTRON_H__
