#ifndef OFPTIMECONDITION_H__
#define OFPTIMECONDITION_H__

enum
{
	FP_TIMECONDITION_BYPASS = 1000,
	FP_TIMECONDITION_GROUP = 2000,
	FP_TIMECONDITION_COMBINE_MODE = 2018,
		FP_TIMECONDITION_COMBINE_MODE_AND = 0,
		FP_TIMECONDITION_COMBINE_MODE_OR = 1,
		FP_TIMECONDITION_COMBINE_MODE_XOR = 2,
	FP_TIMECONDITION_MODE = 2001,
		FP_TIMECONDITION_MODE_SCENETIME = 0,
		FP_TIMECONDITION_MODE_PULSE = 1,
	FP_TIMECONDITION_SCENETIME_CMPOPERATOR = 2002,
		FP_TIMECONDITION_SCENETIME_CMPOPERATOR_EQUALS = 0,
		FP_TIMECONDITION_SCENETIME_CMPOPERATOR_GREATERTHAN,
		FP_TIMECONDITION_SCENETIME_CMPOPERATOR_GREATERTHANEQUALS,
		FP_TIMECONDITION_SCENETIME_CMPOPERATOR_INSIDE,
		FP_TIMECONDITION_SCENETIME_CMPOPERATOR_LESSTHAN,
		FP_TIMECONDITION_SCENETIME_CMPOPERATOR_LESSTHANEQUALS,
		FP_TIMECONDITION_SCENETIME_CMPOPERATOR_NOTEQUALS,
		FP_TIMECONDITION_SCENETIME_CMPOPERATOR_OUTSIDE,
	FP_TIMECONDITION_SCENETIME_CMPTIMEVALUE = 2003,
	FP_TIMECONDITION_SCENETIME_CMPTIMERANGE_LOWER = 2004,
	FP_TIMECONDITION_SCENETIME_CMPTIMERANGE_UPPER = 2005,
	FP_TIMECONDITION_PULSE_STARTFRAME = 2006,
	FP_TIMECONDITION_PULSE_DURATION = 2007,
	FP_TIMECONDITION_PULSE_GAP = 2008,
	FP_TIMECONDITION_CHANCE = 2009,
	FP_TIMECONDITION_SEED = 2010,
	FP_TIMECONDITION_OBJECT_DUMMY
};

#endif // OFPTIMECONDITION_H__
