#ifndef OFPTURN_H__
#define OFPTURN_H__

enum
{
    FP_TURN_GROUP = 1000,
	FP_TURN_DIRECTION = 1004,
		FP_TURN_DIRECTION_AXIS = 0,
		FP_TURN_DIRECTION_VELOCITYDIRECTION = 1, // Unused but important to keep for easy translation from ID to enum
		FP_TURN_DIRECTION_RANDOM = 2,
		FP_TURN_DIRECTION_MAP = 3, // Unused but important to keep for easy translation from ID to enum
		FP_TURN_DIRECTION_VECTOR = 4,
		FP_TURN_DIRECTION_OBJECT = 5,
	FP_TURN_AXIS = 1005,
		FP_TURN_AXIS_POSX = 0,
		FP_TURN_AXIS_NEGX = 1,
		FP_TURN_AXIS_POSY = 2,
		FP_TURN_AXIS_NEGY = 3,
		FP_TURN_AXIS_POSZ = 4,
		FP_TURN_AXIS_NEGZ = 5,
	FP_TURN_VECTOR = 1006,
	FP_TURN_OBJECT_LINK = 1007,
	FP_TURN_SPACE = 1008,
		FP_TURN_SPACE_GLOBAL = 0,
		FP_TURN_SPACE_LOCAL = 1, // Unused but important to keep for easy translation from ID to enum
		FP_TURN_SPACE_ALIGNMENT = 2,
	FP_TURN_FOV = 1009,
	FP_TURN_FOVFALLOFF = 1010,
	FP_TURN_RATELEGACY = 1011,
	FP_TURN_SEED = 1012,
	FP_TURN_MODE = 1013,
		FP_TURN_MODE_SET = 0,
		FP_TURN_MODE_TURN = 1,
	FP_TURN_TURN_ANGLE = 1014,
	FP_TURN_TURN_RATE_UNIT = 1015,
		FP_TURN_TURN_RATE_UNIT_PERFRAME = 0,
		FP_TURN_TURN_RATE_UNIT_PERSECOND = 1,
	FP_TURN_MIX = 1016,
	FP_TURN_END
};

#endif // OFPTURN_H__
