#ifndef OMELT_H__
#define OMELT_H__

enum
{
	MELTOBJECT_RADIUS				= 1000,
	MELTOBJECT_VERTRANDOM		= 1001,
	MELTOBJECT_RADRANDOM		= 1002,
	MELTOBJECT_SIZE					= 1003,
	MELTOBJECT_NOISESCALE		= 1004,
	MELTOBJECT_STRENGTH     = 1005
};

#endif // OMELT_H__
