#ifndef OMOGRAPH_SCATTER_H__
#define OMOGRAPH_SCATTER_H__

enum
{
	MGSCATTER_MODE = 1000,
		MGSCATTER_MODE_BRUSH = 0,
		MGSCATTER_MODE_AREA = 1,
		MGSCATTER_MODE_SURFACE = 2,


	MGSCATTER_EDIT_MODE = 1001,
		MGSCATTER_EDIT_MODE_BRUSH = 0,
		MGSCATTER_EDIT_MODE_SPLINE = 1,
		MGSCATTER_EDIT_MODE_REMOVE = 2,
		MGSCATTER_EDIT_MODE_SURFACE = 3,


	MGSCATTER_ASSET_GROUP = 2000,
	MGSCATTER_ASSET_LIST,


	MGSCATTER_EDIT_GROUP = 3000,
	MGSCATTER_EDIT,
	MGSCATTER_EDIT_PEN_RADIUS,
	MGSCATTER_AREA_INEX_LIST,
	MGSCATTER_SURFACE_LINK,
	MGSCATTER_SURFACE_LINK_EMPTY_TEXT,


	MGSCATTER_DISTRIBUTION_GROUP = 4000,
	MGSCATTER_DISTRIBUTION_LINK,
	MGSCATTER_DENSITY,
	MGSCATTER_DENSITY_PERCENTAGE,
	MGSCATTER_DENSITY_PROBABILITY_MAP_GROUP,
	MGSCATTER_SPACING,
	MGSCATTER_ASSET_COLLISION_RADIUS,
	MGSCATTER_VARIATIONS_RANDOM_UNIFORM_SCALE_VEC,
	MGSCATTER_VARIATIONS_RANDOM_ROTATION_MAX,
	MGSCATTER_ASSET_ALIGN,
	MGSCATTER_SEED,


	MGSCATTER_END,

};

#endif // OMOGRAPH_SCATTER_H__
