#ifndef OMOGRAPH_NODEDISTRIBUTION_H__
#define OMOGRAPH_NODEDISTRIBUTION_H__

enum
{
	MOGRAPH_NODEDISTRIBUTION = 10000,
	MOGRAPH_NODEDISTRIBUTION_LINK_INTERNAL = 10001,
};

#endif // OMOGRAPH_NODEDISTRIBUTION_H__
