#ifndef OPOLYREDUCTION_H__
#define OPOLYREDUCTION_H__

enum
{
	POLYREDUCTIONOBJECT_COPLANAR		= 1000,
	POLYREDUCTIONOBJECT_STRENGTH		= 2000,
	POLYREDUCTIONOBJECT_MESHFACTOR	= 4000,
	POLYREDUCTIONOBJECT_BOUNDARY  	= 5000,
	POLYREDUCTIONOBJECT_QUALITY 		= 7000
};

#endif // OPOLYREDUCTION_H__
