#ifndef OREPROJECT_H__
#define OREPROJECT_H__

enum
{
	MDATA_REPROJECT_SOURCELIST = 1000,
	MDATA_REPROJECT_DEST,
	MDATA_REPROJECT_SUBDIVISION_LEVEL,
	MDATA_REPROJECT_POLY_ESTIMATE,
	MDATA_REPROJECT_PROJECT,
	MDATA_REPROJECT_PROJECT_GROUP,
	MDATA_REPROJECT_CREATECOPY,
	MDATA_REPROJECT_FIT_GROUP,
	MDATA_REPROJECT_FITNEAREST,
	MDATA_REPROJECT_SMOOTH_GROUP,
	MDATA_REPROJECT_SMOOTH,
	MDATA_REPROJECT_SMOOTHSINGLE,
	MDATA_REPROJECT_SMOOTHAMOUNT,
	MDATA_REPROJECT_RESCALE,
	MDATA_REPROJECT_HIDE,
};

#endif // OREPROJECT_H__
