#ifndef OSHRINKWRAPDEFORMER_H__
#define OSHRINKWRAPDEFORMER_H__

enum
{
	SHRINKWRAP_TARGETOBJECT			=		1000,
	SHRINKWRAP_MODE							=		1001,
		SHRINKWRAP_MODE_NORMALS			=		0,
		SHRINKWRAP_MODE_TAXIS				=		1,
		SHRINKWRAP_MODE_SAXIS				=		2,
	SHRINKWRAP_STRENGTH					=		1002,
	SHRINKWRAP_MAXDISTANCE			=		1003
};

#endif // OSHRINKWRAPDEFORMER_H__
