#ifndef OSPLINECONTOUR_H__
#define OSPLINECONTOUR_H__

enum
{
	PRIM_CONTOUR_TEXTURE			= 2140,	// STRING - Filename
	PRIM_CONTOUR_WIDTH				= 2141,	// REAL - Width [>=0.0]
	PRIM_CONTOUR_TOLERANCE		= 2142  // REAL - Tolerance [>0.0]
};

#endif // OSPLINECONTOUR_H__
