#ifndef OVOLUMETOMESH_H__
#define OVOLUMETOMESH_H__

enum
{
	ID_VOLUMETOMESH_ISO = 6000,
	ID_VOLUMETOMESH_ADAPTIVE_VALUE = 6002,
	ID_VOLUMETOMESH_THRESHOLD = 6003,
	ID_VOLUMETOMESH_USE_ISO = 6004,
	ID_VOLUMETOMESH_CREATE_CURVATURE_MAP = 6005,
	ID_VOLUMETOMESH_CURVATURE_DIRECTION = 6006,
		ID_VOLUMETOMESH_CURVATURE_DIRECTION_BOTH = 0,
		ID_VOLUMETOMESH_CURVATURE_DIRECTION_CONVEX = 1,
		ID_VOLUMETOMESH_CURVATURE_DIRECTION_CONCAVE = 2,
};

#endif // OVOLUMETOMESH_H__
