#ifndef PREFSBROWSER_H__
#define PREFSBROWSER_H__

enum
{
	PREF_BROWSER_MAIN_GROUP				= 999,
	PREF_BROWSER_PREVIEWWIDTH			= 1011,
	PREF_BROWSER_PREVIEWHEIGHT		= 1012,

	PREF_BROWSER_DOWNLOAD_LOCATION	= 1013,
	PREF_BROWSER_CLEAR_DOWNLOADED		= 1014,
	PREF_BROWSER_DOWNLOADED_SIZE		= 1015,
	PREF_BROWSER_SHOW_UNAVAILABLE		= 1016,
	PREF_BROWSER_RECALCULATE_SIZE   = 1018,
	PREF_BROWSER_WATCHFOLDER_SEPARATOR = 1017,
	PREF_BROWSER_WATCHFOLDER_AUTOMOUNT_DOCUMENTS = 1019,
	PREF_BROWSER_TREENAV_OPEN_DEFAULT = 1020,
	PREF_BROWSER_WATCHFOLDERS_AUTORUN = 1021,
	PREF_BROWSER_WATCHFOLDERS_AUTORUN_UNSECURE = 1022,

	PREF_BROWSER_MXAI_SEPARATOR		= 1030,
	PREF_BROWSER_MXAI_ENABLED		= 1031,
	PREF_BROWSER_MXAI_IP			= 1032,
	PREF_BROWSER_MXAI_PORT			= 1033,
	PREF_BROWSER_MXAI_GPU_MODE	= 1034, // Int: 0 - Auto, 1 - Force on, 2 Force off
		PREF_BROWSER_MXAI_GPU_MODE_AUTO				= 0,
		PREF_BROWSER_MXAI_GPU_MODE_FORCE_ON		= 1,
		PREF_BROWSER_MXAI_GPU_MODE_FORCE_OFF	= 2,

	PREFS_BROWSER_DUMMY
};

#endif // PREFSBROWSER_H__
