#ifndef PREFSINTERFACE_H__
#define PREFSINTERFACE_H__

enum
{
	PREF_INTERFACE_MAIN_GROUP								= 999,
	PREF_INTERFACE_LANGUAGE									= 1000,
	PREF_INTERFACE_SCHEME										= 1001,
	PREF_INTERFACE_NEWFEATUREHIGHLIGHT			= 1002,
	PREF_INTERFACE_BUBBLE										= 1003,
	PREF_INTERFACE_MENUICONS								= 1004,
	PREF_INTERFACE_MENUSCUT									= 1005,
	PREF_INTERFACE_NEWFEATUREHIGHLIGHT_RESET					= 1006,
	PREF_INTERFACE_NEWFEATUREHIGHLIGHT_RESET_WARNING	= 1007,
	PREF_INTERFACE_STD											= 1008,
	PREF_INTERFACE_EDITSTD									= 1009,
	PREF_INTERFACE_FONTSTD									= 1011,
	PREF_INTERFACE_MONO											= 1012,
	PREF_INTERFACE_EDITMONO									= 1013,
	PREF_INTERFACE_FONTMONO									= 1015,
	PREF_INTERFACE_NEWFEATUREHIGHLIGHT_FADE	= 1016,
	PREF_INTERFACE_AMLIMIT									= 1018,
	PREF_INTERFACE_INSERTAT									= 1019,
		PREF_INTERFACE_I_TOP										= 0,
		PREF_INTERFACE_I_PREV										= 1,
		PREF_INTERFACE_I_NEXT										= 2,
		PREF_INTERFACE_I_PARENT									= 3,
		PREF_INTERFACE_I_CHILD									= 4,
		PREF_INTERFACE_I_ROOT										= 5,
		PREF_INTERFACE_I_BOTTOM									= 6,
		PREF_INTERFACE_I_SAMELEVEL							= 7,
	PREF_INTERFACE_PASTEAT									= 1020,
	PREF_INTERFACE_DRAGCLONEAT = 1065785,
	PREF_INTERFACE_CENTEROBJECT = 1021,

	PREF_INTERFACE_MACMENU									= 1022,
	PREF_INTERFACE_MACDUMMY									= 1023,
	PREF_INTERFACE_SCRIPTWORDWRAP						= 1024,
	PREF_INTERFACE_FONTBIG									= 1025,
	PREF_INTERFACE_HIDEFIELDGRAPH						= 1026,		// LONG CYCLE
		PREF_INTERFACE_HIDEFIELDGRAPH_OFF				= 0,
		PREF_INTERFACE_HIDEFIELDGRAPH_ON				= 1,
		PREF_INTERFACE_HIDEFIELDGRAPH_INFIELDS	= 2,

	PREF_INTERFACE_SIMPLEFIELDUI						= 1027,		// BOOL
	PREF_INTERFACE_SHOWUNDOBUTTONS					= 1028,		// BOOL
	PREF_INTERFACE_AMLIMIT_NODES						= 1029,		// INT32
	PREF_INTERFACE_SCHEME_SEPARATOR					= 1030,
	PREF_INTERFACE_UI_SPACING								= 1031,
		PREF_INTERFACE_UI_SPACING_COMPACT				= 0,
		PREF_INTERFACE_UI_SPACING_MEDIUM	 			= 1,
		PREF_INTERFACE_UI_SPACING_COMFORTABLE		= 2,

	PREF_INTERFACE_FONTSGROUP				= 2000,
	PREF_INTERFACE_TRANSLATIONGROUP	= 2001,
	PREF_INTERFACE_FONTGROUP				= 2002,
	PREF_INTERFACE_HELPERSGROUP			= 2003,
	PREF_INTERFACE_OBJECTGROUP			= 2004,
	PREF_INTERFACE_ATTRIBUTEGROUP		= 2005,

	PREF_INTERFACE_ONLINEHELP				= 3101,
	PREF_INTERFACE_EXTERNALHELP			= 3102,
	PREF_INTERFACE_OPTIONS					= 3200,

	PREFS_INTERFACE_DUMMY
};

#endif // PREFSINTERFACE_H__
