#ifndef PREFSBLSERVER_H__
#define PREFSBLSERVER_H__

enum
{
	PREF_BLSERVER_MAIN_GROUP		= 999,
	PREF_BLSERVER_SQLIP					= 1000,
	PREF_BLSERVER_SQLPORT				= 1001,
	PREF_BLSERVER_SQLUSER				= 1002,
	PREF_BLSERVER_SQLPW					= 1003,
	PREF_BLSERVER_SQLRECONNECT 	= 1004,
	PREF_BLSERVER_USESQL				= 1005,

	PREF_BLSERVER_SQL_GROUP 		= 2000,
	PREF_BLSERVER_DUMMY
};

#endif // PREFSBLSERVER_H__
