#ifndef SLIDESTORYBOARD_H__
#define SLIDESTORYBOARD_H__

enum
{
	STORYBOARDSLIDE_INDEX = 1000,		// Int32
	STORYBOARDSLIDE_DURATION = 1001, 	// BaseTime
	STORYBOARDSLIDE_CAMERA = 1002,	// link
};

#endif // STORYBOARDSLIDE_H__