#ifndef TATTRIBUTETRANSFER_H__
#define TATTRIBUTETRANSFER_H__

enum
{
	ID_TATTRIBUTETRANSFER_GROUP				= 20000, // GROUP
	TATTRIBUTETRANSFER_SOURCE					= 20001, // LINK
	TATTRIBUTETRANSFER_EVAL_METHOD		= 20002, // LONG
		TATTRIBUTETRANSFER_EVAL_METHOD_NEAREST_SURFACE							= 0,
		TATTRIBUTETRANSFER_EVAL_METHOD_NEAREST_POINT								= 1,
		TATTRIBUTETRANSFER_EVAL_METHOD_NORMALS_PROJECTION						= 2,
		TATTRIBUTETRANSFER_EVAL_METHOD_SOURCE_AXIS_PROJECTION				= 3,
		TATTRIBUTETRANSFER_EVAL_METHOD_TARGET_AXIS_PROJECTION				= 4,
		TATTRIBUTETRANSFER_EVAL_METHOD_NEAREST_POLYGON_DATA_BREAKS	= 5,
	TATTRIBUTETRANSFER_TRANSFORM			= 20003, // LONG
		TATTRIBUTETRANSFER_TRANSFORM_OFF		= 0,
		TATTRIBUTETRANSFER_TRANSFORM_FLIPX	= 1,
		TATTRIBUTETRANSFER_TRANSFORM_FLIPY	= 2,
		TATTRIBUTETRANSFER_TRANSFORM_FLIPZ	= 3,
	TATTRIBUTETRANSFER_SPACE					= 20004, // LONG
		TATTRIBUTETRANSFER_SPACE_LOCAL	= 0,
		TATTRIBUTETRANSFER_SPACE_GLOBAL	= 1,
	TATTRIBUTETRANSFER_TRANSFER 			= 20005, // BUTTON
	TATTRIBUTETRANSFER_LIVE_TRANSFER	= 20006, // BOOL
	TATTRIBUTETRANSFER_DEFORMED_POINTS = 20007 // BOOL
};

#endif // TATTRIBUTETRANSFER_H__
