#ifndef TBOOLEANTAG_H__
#define TBOOLEANTAG_H__

enum
{
	BOOLEANTAG_OPERATION = 1001, // LONG
	BOOLEANTAG_OPERATION_NONE = 0,
	BOOLEANTAG_OPERATION_UNION = 1,
	BOOLEANTAG_OPERATION_SUBTRACT = 2,
	BOOLEANTAG_OPERATION_INTERSECT = 3,
	BOOLEANTAG_OPERATION_WITHOUT = 4,
	BOOLEANTAG_PREPROCESS = 1002,							 // BOOL
	ID_BOOLEANTAG_SELECTION = 1003,						 // SEPARATOR
	BOOLEANTAG_SELECTION_POLYGON = 1004,			 // BOOL
	BOOLEANTAG_SELECTION_POLYGON_NAME = 1005,	 // STRING
	BOOLEANTAG_SELECTION_INTERSECT = 1006,		 // BOOL
	BOOLEANTAG_SELECTION_INTERSECT_NAME = 1007 // BOOL
};

#endif // TBOOLEANTAG_H__
