#ifndef TAGFIELDDRIVER_H__
#define TAGFIELDDRIVER_H__

enum
{
	// ID PROPS
	FIELDDRIVER_EVALUATION = 1000,
	FIELDDRIVER_MODE_VALUE = 0,
	FIELDDRIVER_MODE_COLOR = 1,
	FIELDDRIVER_MODE_DIRECTION = 2,
	FIELDDRIVER_STRENGTH = 1001,	
	FIELDDRIVER_MATRIXMODE = 1002,
	FIELDDRIVER_MATRIXMODE_OBJECT = 0,
	FIELDDRIVER_MATRIXMODE_GEOM_CENTER = 1,
	FIELDDRIVER_MATRIXMODE_MIN_AABB = 2,
	FIELDDRIVER_MATRIXMODE_OVERWRITE = 3,
	FIELDDRIVER_MATRIXMODE_OVERWRITE_OB = 1003,	
	// PARAMS
	FIELDDRIVER_PARAMETERS = 2000,
	// FIELD
	FIELDDRIVER_FIELDGROUP	= 1200,
	FIELDDRIVER_FIELD = 1201,
};
#endif // TAGFIELDDRIVER_H__

