#ifndef TMGSCATTERASSETSETTING_H__
#define TMGSCATTERASSETSETTING_H__

enum
{
	MGSCATTER_ASSET_SETTINGS_HASH = 1000,
	MGSCATTER_ASSET_SETTINGS_URL,
	MGSCATTER_ASSET_SETTINGS_COLLISION_RADIUS,
	MGSCATTER_ASSET_SETTINGS_PREVIEW_IMAGE,
	MGSCATTER_ASSET_SETTINGS_ICON_DATA,

	MGSCATTER_ASSET_SETTINGS_COUNT
};

#endif // TMGSCATTERASSETSETTING_H__
