#ifndef TNORMAL_H__
#define TNORMAL_H__

enum
{
	NORMALTAG_ALIGN_FACE2VERTEX = 1000,	// BUTTON
	NORMALTAG_ALIGN_VERTEX2FACE = 1001,	// BUTTON
	NORMALTAG_SWAP_NORMALS			= 1002,	// BUTTON
	NORMALTAG_USE_FIELDS				= 1003,	// BOOL
	NORMALTAG_FIELDS_GROUP			= 1004,	// GROUP
	NORMALTAG_FIELDS						= 1005,	// FIELDLIST
	NORMALTAG_DEFORMEDSTATE			= 1006,	// BOOL
	NORMALTAG_TRANSFER_MODE			= 1007, // LONG
		NORMALTAG_TRANSFER_MODE_FIELDS = 0,
		NORMALTAG_TRANSFER_MODE_ATRTRANS = 1
};

#endif // TNORMAL_H__
