#ifndef TOOLSOLIDIFY_H__
#define TOOLSOLIDIFY_H__

enum
{
	MDATA_SOLIDIFYTOOL_MODE = 1100,                                // LONG 
		MDATA_SOLIDIFYTOOL_MODE_SIMPLE = 10,
		MDATA_SOLIDIFYTOOL_MODE_COMPLEX = 11,

	MDATA_SOLIDIFYTOOL_THICKNESS = 1101,                           // REAL
	MDATA_SOLIDIFYTOOL_POSITION = 1102,                            // REAL
	MDATA_SOLIDIFYTOOL_THICKNESSCLAMP = 1103,                      // REAL

	// only for advanced/complex mode.
	MDATA_SOLIDIFYTOOL_COMPLEX_RESOLVEINTERSECTION = 1104,         // BOOL
	MDATA_SOLIDIFYTOOL_COMPLEX_WELDCOLLAPSED = 1105,               // BOOL
	MDATA_SOLIDIFYTOOL_COMPLEX_FORCEPERPENDICULARBOUNDARY = 1106,  // BOOL
	MDATA_SOLIDIFYTOOL_COMPLEX_PERPENDICULARANGLELIMIT = 1107,     // REAL

	MDATA_SOLIDIFYTOOL_CREATEBOUNDARY = 1108,                      // BOOL
	MDATA_SOLIDIFYTOOL_CREATEINSIDE = 1109,                        // BOOL
	MDATA_SOLIDIFYTOOL_CREATEOUTSIDE = 1110,                       // BOOL

	MDATA_SOLIDIFYTOOL_COMPLEX_PRESERVECORNERS = 1111,             // BOOL
	MDATA_SOLIDIFYTOOL_BOUNDARYSUBDIVISION = 1112,                 // LONG
	MDATA_SOLIDIFYTOOL_COMPLEX_PRESERVECORNERSANGLE = 1113         // REAL
};

#endif // TOOLSOLIDIFY_H__
