#ifndef TOOLSEAMSELECTION_H__
#define TOOLSEAMSELECTION_H__

enum
{
	MDATA_LOOP_SEL_STOP_AT_SELECTIONS	= 1100, // BOOL
	MDATA_LOOP_SEL_STOP_AT_NON_QUADS	= 1110, // BOOL
	MDATA_LOOP_SEL_STOP_AT_POLES			= 1120, // BOOL
	MDATA_LOOP_FIRST_VERTEX						= 1130, // LONG
	MDATA_LOOP_SECOND_VERTEX					= 1131, // LONG
	MDATA_LOOP_POLYGON_INDEX					= 1132, // LONG
	MDATA_LOOP_BOTH_SIDES							= 1133, // BOOL
	MDATA_LOOP_SWAP_SIDES							= 1134, // BOOL
	MDATA_LOOP_SELECTION_TYPE					= 1140, // LONG (must be SELECTION_NEW, SELECTION_ADD or SELECTION_SUB)
	MDATA_LOOP_SEL_POLYGON_OBJECT			= 1150, // LINK

	MDATA_MWS_EDGEMODE = 1001, // LONG
	MDATA_MWS_EDGEMODE_GUIDED = 2,
	MDATA_MWS_EDGEMODE_LINE = 4,
	MDATA_MWS_EDGEMODE_LINE2 = 5
};

#endif // TOOLSEAMSELECTION_H__
