#ifndef TOOLSCULPTBRUSHAMPLIFY_H__
#define TOOLSCULPTBRUSHAMPLIFY_H__

enum
{
	ToolSculptBrushAmplify_Start = 20000,

	MDATA_SCULPTBRUSH_AMPLIFY_MODE,
		MDATA_SCULPTBRUSH_AMPLIFY_MODE_BOTH,
		MDATA_SCULPTBRUSH_AMPLIFY_MODE_CREVICE,
		MDATA_SCULPTBRUSH_AMPLIFY_MODE_RIDGE,
};

#endif // TOOLSCULPTBRUSHAMPLIFY_H__
