#ifndef TOOLSPLINEPROJECT_H__
#define TOOLSPLINEPROJECT_H__

enum
{
	MDATA_SPLINE_PROJECT_MODE						= 2022,	// LONG
	MDATA_SPLINE_PROJECT_MODE_VIEW			= 0,
	MDATA_SPLINE_PROJECT_MODE_XY				= 1,
	MDATA_SPLINE_PROJECT_MODE_ZY				= 2,
	MDATA_SPLINE_PROJECT_MODE_XZ				= 3,
	MDATA_SPLINE_PROJECT_MODE_X_AXIS		= 4,
	MDATA_SPLINE_PROJECT_MODE_Y_AXIS		= 5,
	MDATA_SPLINE_PROJECT_MODE_Z_AXIS		= 6,
	MDATA_SPLINE_PROJECT_MODE_SPHERICAL = 7,

	MDATA_SPLINE_PROJECT
};

#endif	// TOOLSPLINEPROJECT_H__
