#ifndef TTENSION_H__
#define TTENSION_H__

enum
{
	TENSIONTAG_FIX		=	1000,			//fix tension map
	TENSIONTAG_FOLD,							//fold map
	TENSIONTAG_STRETCH,						//stretch map
	TENSIONTAG_AMOUNT,						//distance used in map
	TENSIONTAG_MAKEFOLD,
	TENSIONTAG_MAKESTRETCH,
	TENSIONTAG_SELECTION,
	TENSIONTAG_CLAMPED,
	TENSIONTAG_MODE,
		TENSIONTAG_MODE_RELATIVE	=	0,
		TENSIONTAG_MODE_ABSOLUTE	=	1

};

#endif // TTENSION_H__



