#ifndef TTRANSFER_H__
#define TTRANSFER_H__

enum
{
	TRANSFER_CONTROL = 1064964,
		TRANSFER_CONTROL_OFF = 0,
		TRANSFER_CONTROL_FIELDS = 1,
		TRANSFER_CONTROL_PROPERTY = 2
};

#endif // TTRANSFER_H__
