#ifndef TVERTEXMAP_H__
#define TVERTEXMAP_H__

enum
{
	// tag fields
	ID_TAGFIELDGROUP			= 1000,
	ID_TAGFIELDS					= 805,
	ID_TAGFIELD_ENABLE		= 806,
	ID_TAGFIELD_DEFORMED	= 807,
	ID_TAGFIELD_INVERT = 808,
	ID_VERTEXMAP_TRANSFER_MODE = 809,
		ID_VERTEXMAP_TRANSFER_MODE_FIELDS = 0,
		ID_VERTEXMAP_TRANSFER_MODE_ATRTRANS = 1
};

#endif // TVERTEXMAP_H__
