#ifndef OANIMWAYPOINT_H__
#define OANIMWAYPOINT_H__

enum
{
	ID_ANIM_OWAYPOINT_SETTINGS_GROUP = 1000,
	ID_ANIM_OWAYPOINT_SETTINGS_WEIGHT = 1002,
	ID_ANIM_OWAYPOINT_SETTINGS_FREEDOM = 1003,
	ID_ANIM_OWAYPOINT_SETTINGS_FREEDOMIN = 1004,
	ID_ANIM_OWAYPOINT_SETTINGS_FREEDOMOUT = 1005,
	ID_ANIM_OWAYPOINT_SETTINGS_FREEDOM_OVERWRITE = 1006,
	
	ID_ANIM_OWAYPOINT_SETTINGS_TIME_GROUP = 1100,
		ID_ANIM_OWAYPOINT_SETTINGS_WAITTIME = 1103,
		ID_ANIM_OWAYPOINT_SETTINGS_TOTTIMEFACTOR = 1104,
		ID_ANIM_OWAYPOINT_SETTINGS_MOVEIN = 1105,
		ID_ANIM_OWAYPOINT_SETTINGS_MOVEOUT = 1106,

	ID_ANIM_OWAYPOINT_SETTINGS_TIME_INTERPOLATION = 1107,
		ID_ANIM_OWAYPOINT_SETTINGS_TIME_INTERPOLATION_DEFAULT = (0 << 0),
		ID_ANIM_OWAYPOINT_SETTINGS_TIME_INTERPOLATION_EASYEASE = (1 << 0 | 1 << 1),
		ID_ANIM_OWAYPOINT_SETTINGS_TIME_INTERPOLATION_EASEIN = (1 << 0),
		ID_ANIM_OWAYPOINT_SETTINGS_TIME_INTERPOLATION_EASEOUT = (1 << 1),

	ID_ANIM_OWAYPOINT_SETTINGS_TIME_INTERPOLATION_FACTOR = 1108,
};

#endif