#ifndef UVTOOLBASE_H__
#define UVTOOLBASE_H__

enum
{
	UVTOOLBASE_GROUP = 2200,

	UVTOOLBASE_TILE_GROUP = 2300,
	UVTOOLBASE_TILE_MODE = 2301,
		UVTOOLBASE_TILE_MODE_AUTO_ISLAND_CENTER = 0,
		UVTOOLBASE_TILE_MODE_AUTO_SELECTION_CENTER = 1,
		UVTOOLBASE_TILE_MODE_SINGLE_TILE = 2,
		UVTOOLBASE_TILE_MODE_MULTIPLE_TILES = 3,
	UVTOOLBASE_TILE_SINGLE_TILE = 2302,
	UVTOOLBASE_TILE_MULTIPLE_TILES = 2303,

	UVTOOLBASE_RESOLUTION_GROUP = 2400,
	UVTOOLBASE_RESOLUTION_MODE = 2401,
		UVTOOLBASE_RESOLUTION_MODE_SPECIFY = 0,
		UVTOOLBASE_RESOLUTION_MODE_FROM_TEXTURE = 1,
	UVTOOLBASE_RESOLUTION_SPECIFIED_WIDTH = 2403,
	UVTOOLBASE_RESOLUTION_SPECIFIED_HEIGHT = 2404,
	UVTOOLBASE_RESOLUTION_DEFAULT_WIDTH = 2405,
	UVTOOLBASE_RESOLUTION_DEFAULT_HEIGHT = 2406,

	UVTOOLBASE_TEXELDENSITY_GROUP = 2500,

	UVTOOLBASE_END = 2600
};

#endif // UVTOOLBASE_H__
