#ifndef XCHECKERBOARD_H__
#define XCHECKERBOARD_H__

enum
{
	CHECKERBOARDSHADER_COLOR1	= 1000,  // VECTOR
	CHECKERBOARDSHADER_COLOR2 = 1001,  // VECTOR
	CHECKERBOARDSHADER_SCALEX	= 1002,	 // REAL
	CHECKERBOARDSHADER_SCALEY	= 1003	 // REAL
};

#endif // XCHECKERBOARD_H__
