#ifndef XSLATILES_H__
#define XSLATILES_H__

enum
{
	XSLATiles                             = 1000,

	SLA_TILES_GROUT_COLOR                 = 1001,
	SLA_TILES_TILE_COLOR_1                = 1002,
	SLA_TILES_TILE_COLOR_2                = 1003,
	SLA_TILES_TILE_COLOR_3                = 1004,
	SLA_TILES_PATTERN                     = 1005,
		SLA_TILES_PATTERN_BRICK1            = 2000,
		SLA_TILES_PATTERN_BRICK2            = 2001,
		SLA_TILES_PATTERN_CIRCLES1          = 2002,
		SLA_TILES_PATTERN_CIRCLES2          = 2003,
		SLA_TILES_PATTERN_CIRCLES3          = 2004,
		SLA_TILES_PATTERN_HEXAGONS          = 2005,
		SLA_TILES_PATTERN_LINES1            = 2006,
		SLA_TILES_PATTERN_LINES2            = 2007,
		SLA_TILES_PATTERN_PARQUET           = 2008,
		SLA_TILES_PATTERN_PLANKS            = 2009,
		SLA_TILES_PATTERN_RADIAL_LINES1     = 2010,
		SLA_TILES_PATTERN_RADIAL_LINES2     = 2011,
		SLA_TILES_PATTERN_RANDOM            = 2012,
		SLA_TILES_PATTERN_RINGS1            = 2013,
		SLA_TILES_PATTERN_RINGS2            = 2014,
		SLA_TILES_PATTERN_SAWTOOTH1         = 2015,
		SLA_TILES_PATTERN_SAWTOOTH2         = 2016,
		SLA_TILES_PATTERN_SCALES1           = 2017,
		SLA_TILES_PATTERN_SCALES2           = 2018,
		SLA_TILES_PATTERN_SPIRAL1           = 2019,
		SLA_TILES_PATTERN_SPIRAL2           = 2020,
		SLA_TILES_PATTERN_SQUARES           = 2021,
		SLA_TILES_PATTERN_TRIANGLES1        = 2022,
		SLA_TILES_PATTERN_TRIANGLES2        = 2023,
		SLA_TILES_PATTERN_TRIANGLES3        = 2024,
		SLA_TILES_PATTERN_WAVES1            = 2025,
		SLA_TILES_PATTERN_WAVES2            = 2026,
		SLA_TILES_PATTERN_WEAVE             = 2027,

	SLA_TILES_GROUT_WIDTH                 = 1006,
	SLA_TILES_BEVEL_WIDTH                 = 1007,
	SLA_TILES_SMOOTH_BEVEL                = 1008,
	SLA_TILES_RANDOMIZE_COLOR             = 1009,
	SLA_TILES_ORIENTATION                 = 1010,
		SLA_TILES_ORIENTATION_U             = 2100,
		SLA_TILES_ORIENTATION_V             = 2101,

	SLA_TILES_GLOBAL_SCALE                = 1011,
	SLA_TILES_U_SCALE                     = 1012,
	SLA_TILES_V_SCALE                     = 1013,
	SLA_TILES_RADIAL_SCALE                = 1014,
	SLA_TILES_ROTATE                      = 1016,
	SLA_TILES_DELTA                       = 1015,
	SLA_TILES_SEED												= 1017,

	SLA_TILES_DUMMY_
};

#endif // XSLATILES_H__
