#ifndef XSUNBURST_H__
#define XSUNBURST_H__

enum
{
	SUNBURSTSHADER_SCALE_R		= 1000, // REAL
	SUNBURSTSHADER_SCALE_A 		= 1001, // REAL
	SUNBURSTSHADER_TURBULENCE	= 1002,	// REAL
	SUNBURSTSHADER_FREQUENCY	= 1003,	// REAL
	SUNBURSTSHADER_RADIUS			= 1004,	// REAL
	SUNBURSTSHADER_HEIGHT			= 1005,	// REAL
	SUNBURSTSHADER_COLOR			= 1006	// GRADIENT
};

#endif // XSUNBURST_H__
