name: RefactoringMSBuild

on:
  workflow_dispatch:
  push:
    branches: [ "refactoring" ]
  pull_request:
    branches: [ "refactoring" ]

env:

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
        
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        version: [ '2024' ]
        
    steps:
    - uses: actions/checkout@v3

    - name: Cache SDK Frameworks
      uses: actions/cache@v3
      with:
        path: sdk_${{matrix.version}}/frameworks
        key: ${{ runner.os }}-sdk-${{ matrix.version }}-frameworks-${{ hashFiles('sdk_${{matrix.version}}/frameworks/**') }}
        restore-keys: |
          ${{ runner.os }}-sdk-${{ matrix.version }}-frameworks-

    - name: Cache Dependency Build
      uses: actions/cache@v3
      with:
        path: |
          dependency/*/build
        key: ${{ runner.os }}-dependency-build-${{ hashFiles('dependency/*/CMakeLists.txt', 'dependency/*/src/**', 'dependency/*/include/**') }}
        restore-keys: |
          ${{ runner.os }}-dependency-build-

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run init.bat
      run: ./init.bat
      shell: cmd

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ./sdk_${{matrix.version}}/plugins/project/plugins.sln
